### ISSUE TITLE
Show NBT data on the crafting status and crafting plan of AE2

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8187]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
delta

Considering the decision of removal of EC2 fluids, one way of crafting with fluids is with flasks.
Flasks are showing NBT data on the item list of AE2, but they are not showing it on the crafting status and the crafting plan, making them impossible to identify when 1 type of flask is missing in a crafting.

![javaw_4w7vJkDSvG](https://user-images.githubusercontent.com/17811922/124453368-98464e80-dd87-11eb-9bcf-9676584ad1be.png)
![javaw_YnVWAxw9AL](https://user-images.githubusercontent.com/17811922/124453385-9c726c00-dd87-11eb-89e9-51863cf4403a.png)

I don't know if it's possible, but it would be nice to have the same thing on patterns aswell.
![javaw_zYW6RXvFut](https://user-images.githubusercontent.com/17811922/124453395-9ed4c600-dd87-11eb-8a14-8ae3de656902.png)

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by boubou19** [comment]
i hope this will be possible, because it would be huge QoL for flask players, which should be a great amount of players in some pack versions, as we are removing fluids in AE2.

**Comment by GTNH-Afx237v7** [comment]
Yes please!

**Comment by repo-alt** [comment]
You mean, like, Waila support for crafting status GUI? I'll see what I can do.

**Comment by GTNH-Afx237v7** [comment]
Well at least that an interface terminal or the crafting status GUI can display:

Crafts 1 lubricant volumetric  flask 250mb with 1 empty volumetric flask 250mb

**Comment by repo-alt** [comment]
![crop](https://user-images.githubusercontent.com/23512002/124590748-2d1e7a00-de64-11eb-8a35-8b86e8ffefff.png)
Looks like this. Unfortunately there is no easy way to separate useful information (volume) from useless (R-click instruction), Unless always using just one line from the item tootip.

**Comment by GTNH-Afx237v7** [comment]
Looking good so far, will it show like: one lubricant flask from one empty flask?

**Comment by boubou19** [comment]
is it possible to get full tooltip only if you press a specific key like shift for exemple? that way we don't get the long tooltips whenever we hover the items.

**Comment by repo-alt** [comment]
Yes, it is possible.
![image](https://user-images.githubusercontent.com/23512002/124594860-fa2ab500-de68-11eb-97cb-e759c8be32a0.png)

**Comment by Sphyix** [comment]
That's pretty cool and exactly what is needed for flasks
Ty repo

**Comment by GTNH-Afx237v7** [comment]
QoL +10

**Comment by boubou19** [comment]
Looks like the crafting status gui did not received the new feature from the previous PR

**Comment by GTNH-Afx237v7** [comment]
Works fine for me. Only other thing now would be to add this to the wireless crafting terminal.

**Comment by repo-alt** [comment]
WCT has it's own GUI for crafting status? weird

**Comment by GTNH-Afx237v7** [comment]
Yep, it works fine in any AE terminal but WCT does not show your implementation...

**Comment by GTNH-Afx237v7** [comment]
Can confirm, works fine for the wireless crafting terminal too.
