### ISSUE TITLE
Make Circuit Assembly Line accept other output buses other than ULV

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8188]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
delta

Circuit Assembly Line is voiding LV Circuits when I try to overclock it at UV power, it's making them too fast and the output bus can't push them out fast enough, ULV is single slot.
![javaw_L8RX9sro1i](https://user-images.githubusercontent.com/17811922/124458172-f75a9200-dd8c-11eb-8619-ab18a45026cf.png)

The issue is that the CAL doesn't accept anything else

Request is to make it accept every output bus tier, and/or make it accept the new Output Bus (ME)

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by Prometheus0000** [comment]
It doesn't accept the new buss?

**Comment by Sphyix** [comment]
no

**Comment by GTNH-Afx237v7** [comment]
I believe this is the corresponding code:
https://github.com/GTNewHorizons/bartworks/blob/36206fdd152badd9cd33db24c0b5e7dded6baa55/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_CircuitAssemblyLine.java#L314
