### ISSUE TITLE
Client Crash when putting ae2 Cables into Chisel

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#8190]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Tried to add a MT Script to allow to chisel ae2 glass cables into other ae2 glass cables with other Color. When Putting An AE2 Glass Cable Into the Chisel GUI, i had a client Crash to Desktop. (See Crashlog). I tried it a second time, crashed, so its repeatable.
[crash-2021-07-05_15.15.58-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6765042/crash-2021-07-05_15.15.58-client.txt)

#
#### What do you suggest instead/what changes do you propose?
Fix It
#
#### What is your GTNH Discord username?
TrainerSnow#5086

**Comment by Ethryan** [comment]
Maybe show us the MT script to rule out user error?

**Comment by TrainerSnow** [comment]
Turns out when i delet the Script it doesnt crash anymore, must have been my fault.
