### ISSUE TITLE
Some tipes of villagers are giving 100LP instead of 1000LP on the blood altar

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8193]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
Cinobi was too lazy, so i'm making the ticket for him. He told me some villagers( like foresters) are giving 100 LP when killed instead of 1000 which is the normal amount.
#
#### What happened instead? (Attach screenshots if needed)
(he didn't have a ss to send)
#
#### What do you suggest instead/what changes do you propose?
They should give 1000 normally.

**Comment by Cinobi** [comment]
![2021-07-05_19 29 03](https://user-images.githubusercontent.com/25028786/124499852-6359ec00-ddc7-11eb-9990-0e7daa5c2c22.png)
![2021-07-05_19 29 06](https://user-images.githubusercontent.com/25028786/124499868-68b73680-ddc7-11eb-9af6-c389f17421bb.png)
some screens, look like the problem is for railcraft and stargate villagers, maybe more

**Comment by Prometheus0000** [comment]
There's a config that lists how much blood each mob gives. Maybe they don't count as the villager mob?

**Comment by Prometheus0000** [comment]
There doesn't seem to be an applicable 180LP or 100LP entry, so I dunno.

**Comment by Prometheus0000** [comment]
```
sacrifice {
    D:"LP per (self-)sacrifice with incense"=50.0
    I:"LP per sacrifice"=400
    I:"LP per sacrifice with Well of Suffering ritual"=10
    I:"LP per self-sacrifice"=100
    I:"LP per self-sacrifice (when Soul Fray potion is active)"=1
    I:"LP per self-sacrifice with Ritual of Feathered Knife"=100
```
Maybe GT++ does something with the human meat I see to make BM think it's a player self-sacrificing or something. Try again with just BM and whatever you need for the villagers Or just removing GT++..
