### ISSUE TITLE
Remove Ethereal Blood Stone recipe to split into Potentia.

### ISSUE THREAD

**Issue by anabsolutesloth** [GTNewHorizons/GT-New-Horizons-Modpack#8195]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Checked out JEI, in particular the recipes for and using the various Blood Stone blocks from Blood Arsenal, expected to see a Cutting Machine recipe to split all of them and no Crafting Table recipes.
#
#### What happened instead? (Attach screenshots if needed)
Ethereal Blood Stone has a Crafting Table recipe to turn itself into 9 Potentia reagent from BM, this is clearly a mistake by the mod author if you check the ItemIDs and Metadata values of Potentia and Ethereal Slates.
![image](https://user-images.githubusercontent.com/63694982/124523158-b70a0c80-ddaa-11eb-80d1-11f0913de6e6.png)
#
#### What do you suggest instead/what changes do you propose?
Remove the recipe.
#
#### What is your GTNH Discord username?
Emperdog

**Comment by Prometheus0000** [comment]
See https://github.com/Arcaratus/BloodArsenal/issues/38 for the fix. Could someone with more expertise confirm if we want the rest of the changes? Also, why isn't our version the last one for 1.7.10? Maybe there's other fixes/changes to get?
