### ISSUE TITLE
Patterns placed directly in Molecular Assemblers seem to disappear every now and then

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#8196]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
jimmy's community server
#
#### What did you try to do, and what did you expect to happen?
We have a bunch of molecular assemblers throughout the base for PBI/Platline/Pahoehoe tiny piles.
We decided to use them instead of packagers in some areas to save on power cost.
(yes I know recipes in PBI can use full dust instead of tiny piles, and I probably will switch those over but would still like to see this issue resolved if possible)
#
#### What happened instead? (Attach screenshots if needed)
after a while the assemblers lose the pattern placed in them, I don't know if it's because of server restart or not, but they just seem to disappear over time.
#
#### What do you suggest instead/what changes do you propose?
I don't know what issue is causing this but would love to see this resolved as it's quite a handy way to deal with tiny/small dusts instead of packagers. Obviously has a lot of other applications as well and it's a very tps friendly and efficient way to deal with passive autocrafting in general.
#
#### What is your GTNH Discord username?
Hucking#0193

**Comment by repo-alt** [comment]
This is the first time I hear something like that. The only reasons the patterm may "disappear" are: 
1. Not saving to the disk (in that case not just the pattern but the upgrades and settings would be lost)
2. When loading the chunk the pattern is considered invalid, or some of the ingredients are loaded incorrectly.
That sounds like very much like a server kernel problem tbh

**Comment by hucking** [comment]
fair enough, for the record the acceleration upgrades did not disappear, I'll look into if it's server sided issue or not.

**Comment by repo-alt** [comment]
btw, if that is void/garden dim then incomplete TE saving is a known issue there, but no one was able to find the reason afaik

**Comment by hucking** [comment]
no, overworld
