### ISSUE TITLE
Coin dupe

### ISSUE THREAD

**Issue by Mr-Vovikpro123** [GTNewHorizons/GT-New-Horizons-Modpack#8197]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
accidentally droped a stack of coins in the disassembler, in theory they should be disassembled from 100 to 10 for example
#
#### What happened instead? (Attach screenshots if needed)
only 1 coin consumed and compressed to the next tier (1 => 10 coins conversion not working)

https://user-images.githubusercontent.com/64985356/124561538-adce7d80-de46-11eb-87ca-24440aacceda.mp4

#

#### What is your GTNH Discord username?
A3W10

**Comment by KaneHart** [comment]
Thanks. By default this should be major as it's a dupe. But it's only on the client side and servers have to add it themselves. Will look at it and see if we can throw a PR Patch if it's possible for us to handle.

**Comment by KaneHart** [comment]
I tried this with 2.1.1.0 in MP and could not repeat the issue.
