### ISSUE TITLE
[GTNH AE2] Fluid P2P links do not show up on network visualization tool

### ISSUE THREAD

**Issue by MadMan310** [GTNewHorizons/GT-New-Horizons-Modpack#8200]
#### Which modpack version are you using?
2.1.1.0
#
#### What did you try to do, and what did you expect to happen?
When you use a NetVis on an ME network, it displays normal ME P2P tunnels normally, but it does not do the same thing with fluid tunnels.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/66886359/124643880-79f35800-de46-11eb-9481-17fa259a74c0.png)
In this image, I have 2 fluid P2P tunnels connected to each other on a network, with it being visualized by the NetVis. As you can see, we cannot see the connection between them.
#
#### What do you suggest instead/what changes do you propose?
I would like to have it display the connection just like a normal ME network tunnel, preferably with a different color to differentiate between the two.
#
#### What is your GTNH Discord username?
MadMan310#2048

**Comment by greesyB** [comment]
Worth noting that other types of p2p tunnels also don't seem to show on the visualizer. Fluid is the most important, but it would be nice to see EU and other types as well.

**Comment by Prometheus0000** [comment]
Isn't that because they're a different network?

**Comment by greesyB** [comment]
What do you mean by different network? In MadMan's example there is only one network.

**Comment by boubou19** [comment]
it would be great if the endpoints of every p2p type of tunnels had a different color link between endpoints.

**Comment by Alexdoru** [comment]
Or make it so that you need to click on a certain p2p and it would only show the links for all the p2p of the same frequency

**Comment by repo-alt** [comment]
There is a separate P2P mode of course, so new modes may be added to include just fluid/EU P2Ps, or generic p2p mode may render all kind of links in different colors (what colors though). Not sure about links originating from a given point though, may require too much changes, but perhaps it is viable (in a separate mode too?)

**Comment by Alexdoru** [comment]
> You can print coordinates rn, with a wrench

didn't know about that, thank you

**Comment by SirFell** [comment]
You can track my progress on the topic here: [GTMEGA fork](https://github.com/GTMEGA/ae2stuff/pull/1), but "nicer" p2p would take ages since it'd require basically a complete rewrite of rendering and my scala knowledge is... lets say lacking.
