### ISSUE TITLE
BQ - Wrong status of Quests

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#8203]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
MP, Private Server
#

![image](https://user-images.githubusercontent.com/25156941/124760118-13029b80-df39-11eb-91f7-a6fb25099e61.png)
I can't complete some quests (at least Vacuum Tubes 965, Resistors 966, Basic Circuit Board 963) after I once completed them (that was in the prev version.) It just don't want to consume Technician Coin. I click "Detect/Submit", but coins from my inventory aren't got consumed. But for some already completed quests, like in Red Alloy Cable (1161), I can do so.
![image](https://user-images.githubusercontent.com/25156941/124760528-81dff480-df39-11eb-94b7-8403c2bcfdcc.png)
![image](https://user-images.githubusercontent.com/25156941/124760565-8a382f80-df39-11eb-964c-efaceaf194a5.png)

#### What is your GTNH Discord username?
`TimeConqueror#0001`

**Comment by Prometheus0000** [comment]
Did you check if you meet the current requirements of the quest?

**Comment by TimeConqueror** [comment]
> Did you check if you meet the current requirements of the quest?

Check the last image with arrows.

**Comment by Prometheus0000** [comment]
I don't see the requirements there.

**Comment by TimeConqueror** [comment]
They're in the hotbar - more than a stack of required coins.

**Comment by Prometheus0000** [comment]
Coins don't open up the quest.

**Comment by TimeConqueror** [comment]
Well, after some testing it appears to be a bug of BQ, which incorrectly handles the status of the quest. In fact it is locked on Tier 2, but before update it didn't have such requirements. But instead of "Locked" status, it has "Can be repeated"

**Comment by Prometheus0000** [comment]
It's probably because a new status of "being completed, but can be done again" for the different color was added. If it's been completed previously, but the player doesn't meet the changed quest requirements, you seem to end up with this problem.
