### ISSUE TITLE
Item Frames are not working correct

### ISSUE THREAD

**Issue by Kasparione** [GTNewHorizons/GT-New-Horizons-Modpack#8205]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
On my own server. With Ultramine server core
#
#### What did you try to do, and what did you expect to happen?
Unload chunks and coming back to them disables itemframes to be seen via Waila. I wanted to see what item is in a frame
![2021-07-07_21 22 50](https://user-images.githubusercontent.com/87091579/124810172-aeac0000-df69-11eb-95bf-72b3b4ae4578.png)
#
#### What happened instead? (Attach screenshots if needed)
Just a block behind it
![2021-07-07_21 23 41](https://user-images.githubusercontent.com/87091579/124810259-c5eaed80-df69-11eb-8ae9-6dff9ab56419.png)
#
#### What do you suggest instead/what changes do you propose?
I believe it is needed to be investigated, because I have no idea what could be wrong with with vanilla items
#
#### What is your GTNH Discord username?
Kaspario#2928

**Comment by boubou19** [comment]
can you try again on a pure forge server?

**Comment by Kasparione** [comment]
Looks like a pure forge server is unproblematic in that case. I'm sorry for disturbance, I believe we just have to accept it for that version.
