### ISSUE TITLE
[Request] Support for Aroma1996's Dimensional World

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#8206]
#### Which modpack version are you using?
2.1.1.0
#
#### What did you try to do, and what did you expect to happen?
Tried to add the Mining World dimension to the WorldGeneration.cfg to add ore spawn from all overworld mods to it in addition.
#
#### What happened instead? (Attach screenshots if needed)
Well, nothing as you can see:

![image](https://user-images.githubusercontent.com/1703441/124834264-beceda00-df7f-11eb-84a1-24de7bed9ab4.png)

#
#### What do you suggest instead/what changes do you propose?
Please add support for the Mining World from the stated mod in the title
#
#### What is your GTNH Discord username?
Marcel|Chaoschaot234#7964

**Comment by Prometheus0000** [comment]
No

**Comment by Chaoschaot232** [comment]
Uhm, only posting No and directly closing it ... where is the explination for this?

**Comment by King65868** [comment]
It’s not part of the pack, why would support be added

**Comment by Prometheus0000** [comment]
Why should we go to the effort to do this for you when it has nothing to do with the pack? If you want help with doing it yourself, ask how to on discord to someone who would know.

**Comment by Chaoschaot232** [comment]
@King65868 And because of this I asked to get it implemented. Normaly, it should work by adding the Dimension/World Name to the config file but either smth. is missing or wrong.

@Prometheus0000 Uhm because this pack is arround GT so I assume that it comes from the mod maker and it's staff members? So it wouldn't and shouldn't be a problem to add this in? But maybe it is easier to say: "I/We are to lazy todo this, do it yourself if you want." - Which is realy nice support *ironie off*

**Comment by Prometheus0000** [comment]
It is the other way around, you are demanding we do something that has no value to us. There is _no support_ for non-pack mods, you might as well complain mekanism crashed the pack or something.

**Comment by Chaoschaot232** [comment]
Well, this would definitly do another player who added meka into this pack to break it because of the osmium ore from meka ^^

**Comment by mitchej123** [comment]
> Which is realy nice support ironie off

Mods in the pack are supported.  Other mods are not.  This is GTNH, not GT.  If you want something done like this, hire someone, or do it yourself.
