### ISSUE TITLE
change the way to clear patterns in the knowledge inscriber

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8208]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen?
delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to clear my 2years old ichor ingot recipe in my knowledge inscriber, so i clicked on it, and was about to press erase
#
#### What happened instead? (Attach screenshots if needed)
the oredict unification happened, so the output item is the GT ingot, making impossible to clean my old ichor ingot pattern, so i just lost 1 slot in my knowledge core.

![image](https://user-images.githubusercontent.com/12850933/124978922-ae2b6c00-e032-11eb-91eb-3c47b789105c.png)

**Comment by repo-alt** [comment]
I guess I can make it so that if the ingredients are the same as in existing recipe, 'save' button will overwrite the existing record.

**Comment by boubou19** [comment]
That would be welcomed :)
