### ISSUE TITLE
Simple washers in Processing Arrays

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#8209]
I suggest adding an option to use simple washers in Processing Arrays.
Let me explain why I think this would be a good idea: at the moment there is no native Gregtech way to automate the cauldron part of washing the impure dust. I believe this is an oversight and not properly designed. I think if Gregtech was to natively add that feature, which in my opinion is a good one to have in the native mod, it would be usable in Processing Arrays and therefore there is no reason to restrict it for gameplay reasons at least.

Practically there may be reasons not to add it, such as code incompatibility or gt++ being too much of a hassle to work with, if that is the reason you don't want to add this feature I can live with it, but I think from a gameplay point of view it makes perfect sense.

If however you think from a gameplay point of view that simple washers are too strong, I would suggest adding alternative methods to washing impure dusts with no byproducts. In my opinion as written above, I believe it should be an option in the native mod anyway.

**Comment by boubou19** [comment]
Cauldrons are supposed to be early game only, that's why the simple washers are ULV after you are supposed to have a decent ore treatment. After, i agree that sometimes, you don't care about byprods, so being able to clean them fast would be a cool thing, but not really mandatory. Might be a design choice to force the player clean his dusts with a centrifuge.

**Comment by hucking** [comment]
btw @Prometheus0000 from what I understand the simple washer will stay even after gt++ is removed? or am I wrong about this? (what I've been told on the discord not sure if true)

**Comment by Prometheus0000** [comment]
There's an obama version. I don't know if bot has made a multi version yet or not. We want to get rid of the PA eventually though, so if there isn't one, we'll probably add it later.

**Comment by Alexdoru** [comment]
Alk said that it is supposed to work in a PA and the fact that it is not working is a bug 
https://discord.com/channels/181078474394566657/234936569360809996/887970864933535744
