### ISSUE TITLE
GT++ voiding mode state is not displayed in chat when activated/disabled

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8223]
#### Which modpack version are you using?
2.1.1.0 with http://jenkins.usrv.eu:8080/job/GTPP/19/
#
#### If in multiplayer; On which server does this happen? 
delta
#
We (@Sphyix and me) tried the output bus (ME) on gt++ multis, so we used soldering iron on the controller to get the voiding mode enabled, and we managed to get it to work. The issue is that we don't have a message in the chat to know in what mode we put the controller.

**Comment by sintken** [comment]
not directly relevant but for anyone running 2.1.1.0 wondering if this works, this functionality (soldering iron to override gt++ antivoid) was not included in the 2.1.1.0 release
