### ISSUE TITLE
Tungstate/scheelite can still be electrolyzed directly into tungsten dust

### ISSUE THREAD

**Issue by sintken** [GTNewHorizons/GT-New-Horizons-Modpack#8225]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Tried electrolyzing tungstate and scheelite using the old EV recipe, expected it not to work since the recipe has been removed and is no longer in NEI
#
#### What happened instead? (Attach screenshots if needed)
it worked lol. both tungstate and scheelite electrolyze to tungsten like before
#
#### What do you suggest instead/what changes do you propose?
fix it i guess
#
#### What is your GTNH Discord username?
sintken (taintstainer) #1312

**Comment by Dream-Master** [comment]
but at IV?  @botn365 is this intended or just a alternative way ?

**Comment by GTNH-Afx237v7** [comment]
EV was standard, says it still happens with EV?

**Comment by sintken** [comment]
tested with an EV electrolyzer, yes. same as the old recipe.

**Comment by Dream-Master** [comment]
maybe i am wrong ans ut was ev all the time

**Comment by Prometheus0000** [comment]
I can't reproduce this in 2.1.1.3 with tungstate. The recipe went away after adding botdustries, maybe you don't have it somehow?

**Comment by Miisi** [comment]
works for me in 2.1.1.3 
![image](https://user-images.githubusercontent.com/46682682/134372925-e375052a-500d-45b5-b88c-73792b84f022.png)
![image](https://user-images.githubusercontent.com/46682682/134373082-8a9d42cb-57dd-4d59-ace8-51d8267454c1.png)

**Comment by Dream-Master** [comment]
i can remove the recipes to be sure. So botdustries not need to overrride it
