### ISSUE TITLE
Add alternative recipe for botany pigments

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#8227]
#### Which modpack version are you using?
2.1.1
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Add a recipe to make botany pigments feasible to use in builds, since they add so many tones of colours which would be much appreciated.
Since right now you have to breed flowers to get pigments for the colour you want, which people seldom do, no one uses them, and for good too reason since the process is brain damaging.
It's a shame that there's 100+ useful aesthetic blocks added by Botany that can't be used due to the afore mentioned acquisition process.

Also I doubt you can but if you could make them micro-blockable that would be nice :trollface: 

#
#### What is your GTNH Discord username?
Jimbno

**Comment by Prometheus0000** [comment]
Nobody cares about the botany stuff for the reason you mentioned, but feel free to make a PR?

**Comment by Ngar1** [comment]
I like it, that is not easy to get this special colours. It is one of my next project (parallel to research station ;-)
