### ISSUE TITLE
NEI F7/F9 screen glitches the further you are from spawn

### ISSUE THREAD

**Issue by MrJakobLaich** [GTNewHorizons/GT-New-Horizons-Modpack#8230]
VERSION 2.1.1.0

Happens on my own server but would guess that it does that on every server as it seems to be some float offset issue

I teleported myself far away (reasons not important) and I pressed F7, the crosses are not even remotely matching the block positions anymore and the F9 screen also glitches.
By glitches I mean the lines jump around randomly even if you move the mouse very slowly.
The crosses should be exactly on top of the blocks

As seen in the following screenshots, if I move the mouse a little, the "crosses" jump around a lot, also the crosses are distorted by a lot, same happens with the F9 screen.

![image](https://user-images.githubusercontent.com/40965742/125207597-7c621180-e28d-11eb-8343-8b5a253d9bdd.png)
![image](https://user-images.githubusercontent.com/40965742/125207604-81bf5c00-e28d-11eb-8d42-0bf84325c9c2.png)
![image](https://user-images.githubusercontent.com/40965742/125207609-84ba4c80-e28d-11eb-9f07-840fb8af3626.png)
![image](https://user-images.githubusercontent.com/40965742/125207616-87b53d00-e28d-11eb-89e7-ae235c2cf4da.png)

Suggestion:
I do not know what exactly causes this issue, it seems like NEI is using some offset from 0.0 / 0.0, maybe the player coordinates need to be used instead of the 0.0 / 0.0 coordinate (if that's even the issue)

GTNH Discord username: MrJakobLaich, if you want a video of the crosses jumping around, DM me, the file is a little too big to upload here as a screenshot.

**Comment by GTNH-Afx237v7** [comment]
How far away is far away? Isn’t that inherent to Minecraft anyway (think Farlands)?

**Comment by Prometheus0000** [comment]
What do you mean by "far away"? Like 100 blocks? We aren't mind readers.

**Comment by MrJakobLaich** [comment]
> How far away is far away? Isn’t that inherent to Minecraft anyway (think Farlands)?

I tp'ed around 5M blocks away, yes I know that is far but the effect can be seen at 10k blocks already

**Comment by MrJakobLaich** [comment]
> What do you mean by "far away"? Like 100 blocks? We aren't mind readers.

Yeah, sorry, fair point, above 10k it starts to be noticable if you know that about it and around 100k it starts to become actually noticable even if you don't know about it beforehand

**Comment by MrJakobLaich** [comment]
> > How far away is far away? Isn’t that inherent to Minecraft anyway (think Farlands)?
> 
> I tp'ed around 5M blocks away, yes I know that is far but the effect can be seen at 10k blocks already

Also, I do realise that 5M blocks is insane, if I could I would move my base closer to spawn again but then I would have to move a lot of stuff...

**Comment by leagris** [comment]
This look like caused by 32-bit floating-point rounding errors amplified by larger coordinate numbers.

If you are worried by moving your base, how long have you been there and since how long have you noticed this visual glitch before you report it?

You are one person building insanely far from spawn. This issue is only visual, but you never know how many other mod computation bugs you will be facing with such large coordinates. I strongly advise you to move to saner ranges. Even if one manage to fix this minor visual glitch, other nasty bugs may arise because of such numbers and rounding errors.

**Comment by MrJakobLaich** [comment]
> This look like caused by 32-bit floating-point rounding errors amplified by larger coordinate numbers.
> 
> If you are worried by moving your base, how long have you been there and since how long have you noticed this visual glitch before you report it?
> 
> You are one person building insanely far from spawn. This issue is only visual, but you never know how many other mod computation bugs you will be facing with such large coordinates. I strongly advise you to move to saner ranges. Even if one manage to fix this minor visual glitch, other nasty bugs may arise because of such numbers and rounding errors.

Yeah, I agree, it does.

Has happened since a couple of days now, wouldn't have cared about it but it's so severe that I can't determine where the chunk borders start.

Fair point, will move my base.

Thanks for the help :)
