### ISSUE TITLE
Output bus (ME) causes big lag, especially with megas

### ISSUE THREAD

**Issue by sintken** [GTNewHorizons/GT-New-Horizons-Modpack#8231]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Put ME output bus on mega vacuum freezer and mega blast furnace, expected it to reduce lag. also tested with a normal EBF
#
#### What happened instead? (Attach screenshots if needed)
Controllers for megas ticked way higher:
![image](https://user-images.githubusercontent.com/72178165/125209643-1bb3e400-e24f-11eb-8740-4d46d86d4949.png)
![image](https://user-images.githubusercontent.com/72178165/125209648-1fe00180-e24f-11eb-9a4f-df5bc58d0915.png)

compare to using HV output bus with uhv conveyor + interface:
![image](https://user-images.githubusercontent.com/72178165/125209655-2d958700-e24f-11eb-8a74-9831369af04a.png)
![image](https://user-images.githubusercontent.com/72178165/125209662-34bc9500-e24f-11eb-920c-4c03919feb25.png)

and for normal EBF running 1-tick steel ingots:
![image](https://user-images.githubusercontent.com/72178165/125209689-75b4a980-e24f-11eb-9cc1-82208f48128a.png)
with ME output bus
![image](https://user-images.githubusercontent.com/72178165/125209704-94b33b80-e24f-11eb-82ab-3ada51397896.png)
without ME input bus

#
#### What do you suggest instead/what changes do you propose?
dunno, but it seems like the ME bus is making it lag more
#
#### What is your GTNH Discord username?
sintken (taintstainer)

**Comment by GTNH-Afx237v7** [comment]
A bit of info from repolainen:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7972#issuecomment-850979570
Maybe it has to do with your AE system being pretty large? Lots of storage disks/drives?

**Comment by sintken** [comment]
I've got 120 4096k storage cells, if that counts as pretty large?

**Comment by GTNH-Afx237v7** [comment]
Maybe an option to profile the I/O of your drives with visualvm, though I don’t know where this would be found

**Comment by repo-alt** [comment]
Measuring conveyor + interface actually hides all the time taken by AE searching for the place to store the stuff, it effectively measures only GT part. ME bus measurement takes all that time into account.

**Comment by Sphyix** [comment]
Tested some stuff on delta for the ME Output Bus
I tried using it on an MBF making iron ingots (1 tick recipe, outputting probably 400+ items/tick)
Just for reference for the next screenshots and data, my base ms is around 16-17, my main ME network is composed by 60x 64k drives, 1 infinity chest, too many interfaces (if they even make a difference), and a few (4-5) storage buses on drawers

Connecting the ME Output Bus to my main ME Network caused this:
![javaw_s1XIeXVODb](https://user-images.githubusercontent.com/17811922/126404853-ba7ccee0-2543-4043-b5fe-55ecd1a68432.png)
![wIjIaiu9Tv](https://user-images.githubusercontent.com/17811922/126404864-fc282709-fd3a-4366-ac5a-bef96334d30d.png)

When testing with a really small network composed by 1 ME Controller, 1 infinty chest with a storage bus and the ME output bus the lag was reported 7x lower by the tricorder, ms of the base looked like this:
![z9kUO61BhU](https://user-images.githubusercontent.com/17811922/126404966-f14dc455-e018-44e1-b197-04c766cbf67f.png)

and the same setup with 2 quantum chests for the output storage removed like 95% of the lag, adding just around 3 to 4ms to my base when running (don't have a screenshot for it)

Warmroast report here
[WarmRoast_me_output_bus.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6851621/WarmRoast_me_output_bus.zip)

**Comment by Ydrec** [comment]
> Tested some stuff on ...

Are you storing iron in drawers or in cells of that ae? Do your drawers have filtered storage buses on them to keep ae from cheking them? have you tried same setup but with interface+conveyor on normal bus instead?

**Comment by boubou19** [comment]
the thing is if we use normal output bus + interface combo, it's lagging way less, so network should matter that much i think.

**Comment by Sphyix** [comment]
> Are you storing iron in drawers or in cells of that ae? Do your drawers have filtered storage buses on them to keep ae from cheking them? have you tried same setup but with interface+conveyor on normal bus instead?

Storing in the infinity chest with filtered storage buses
>  have you tried same setup but with interface+conveyor on normal bus instead?

I was about to post this, I tested with 32 Output Bus (HV) facing 32 different interfaces, this is the setup:
![GsCwKyZbD9](https://user-images.githubusercontent.com/17811922/126406317-f8900e4d-a872-4520-841e-c149b5b0c4f8.png)

This setup is outputting to the 1st setup of the previous reply, the laggy one, so it's outputting to an infinity chest connected with filtered storage buses.
This is what came out lag wise
![javaw_f6Rsvl7eAd](https://user-images.githubusercontent.com/17811922/126406408-8681ad98-b0fd-45eb-88d0-c49258ebd715.png)
![Q3FbmoGjv4](https://user-images.githubusercontent.com/17811922/126406419-135146e3-ce30-4880-b219-5d853134b02d.png)

From warmroast we noticed lag in this case is not caused by the items being stored, but from other MBF checks
[WarmRoast_normal.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6851685/WarmRoast_normal.zip)

**Comment by repo-alt** [comment]
Well, when multiblock is outputting the same stuff at high rate I guess I can buffer it and store like once per second, but what if AE would be full or offline, would it be ok to void it? Because it is either that or spill it on the ground

**Comment by boubou19** [comment]
The thing with voiding items at such rate is that you'll be salty if it happens to you, but that's totally inline with defaut GT behavior so yeah voiding them is ok. In worse case, the MBF can bake 256 items/tick so throwing on the ground ~5k items/s will definitely kill the server.

**Comment by Sphyix** [comment]
Voiding them is ok, but a redstone signal in this case is needed, i can understand voiding a few ticks of items, but not an entire batch

**Comment by repo-alt** [comment]
well, if it outputs every tick and ME went offline at the 19-th tick, then 19 ticks worth of stuff will be voided. But that is the same that will happen with default buses I guess.

**Comment by repo-alt** [comment]
After that the bus will raise an internal flag and won't buffer until the next successfull store

**Comment by repo-alt** [comment]
Does MEBF have a built-in overflow control?

**Comment by boubou19** [comment]
i don't think so

**Comment by repo-alt** [comment]
Well, then it is the same as now from the user point of view, just make sure the system is online when you roast tons of stuff

**Comment by Sphyix** [comment]
> well, if it outputs every tick and ME went offline at the 19-th tick, then 19 ticks worth of stuff will be voided. But that is the same that will happen with default buses I guess.

No, interfaces have a storage and they get emptied only when AE is online, so whenever it goes offline, interfaces and buses won't be emptied and stuff is gonna remain into the interface.
With gt output buses i can setup covers to check when the output is full, so if AE goes offline, the output buses fill up and redstone can turn off the machine, so nothing gets voided.

**Comment by repo-alt** [comment]
I was talking about the current behaviour of the ME output bus, it won't change, cache or not. I guess I can raise redstone on the hatch block if the last output failed

**Comment by repo-alt** [comment]
(Or, actually, modify the item detector cover to handle this case)
