### ISSUE TITLE
[Test Bug] NEI seems to have an issue with the bookmark bar when acessing recipies in some slots

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8232]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
SO
#
#### What did you try to do, and what did you expect to happen?
Click on a recipe while using the Tconstruct table with a chest hooked up and expected it to show the desired recipie
#
#### What happened instead? (Attach screenshots if needed)
It did not and did nothing

The following image will give you an idea on what the issue areas are
The red X is the problem area. Please note that this will work with any item its just that positioning
![image](https://user-images.githubusercontent.com/38770780/125218007-f72c2c00-e28f-11eb-9e7b-fff70536cfbb.png)
Again, you can bookmark any item, it will happen only in the area where I marked a red X
#
#### What do you suggest instead/what changes do you propose?
to fix this

Please Note that Im using a test version of NEI for the purposees of testing a visual bug
NEI version: NotEnoughItems-1.7.10-2.1.5-GTNH-universal (<--- Test Version Provided by @Glease for testing another bug patch that has seem to be fixed [regarding the darkend JEI like tabs])
#
#### What is your GTNH Discord username?
Doggo_9000

**Comment by boubou19** [comment]
what is your gui scale and screen resolution?

**Comment by SteamDoge9000** [comment]
automatic,
Screen res: 1680 X 1050

**Comment by SteamDoge9000** [comment]
oh heres somehting else

you can still hover over it and it will light up
But it wont show recipies or uses when you click on it
![image](https://user-images.githubusercontent.com/38770780/125728924-874d8871-4967-4fe6-83e9-5f173ebf8af5.png)

**Comment by slprime** [comment]
I changed algorithm for drawing nei panels. Bug still there?
