### ISSUE TITLE
AE2 search pannel further adjastments 

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#8233]
#### Which modpack version are you using?
zeta-live
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
Related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8126 issue

It could be veri nice to able to switch modes from gui, with new added button somewhere - here or here for example
![изображение](https://user-images.githubusercontent.com/25028786/125277738-7fefaa00-e31a-11eb-8a54-e75a8d94fcbe.png)

#
#### What is your GTNH Discord username?
Cinobi

**Comment by boubou19** [comment]
That would be a great addition for those who are too lazy to change it in the configs

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/126064775-a305383a-4adc-487c-8bee-b32a37b94246.png)
If anyone is unimpressed with my superior Paint skills, fill free to edit https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/a7e81c1c359e5983025527a9c8bd7cfa8e83c12d/src/main/resources/assets/appliedenergistics2/textures/guis/states.png and PR
