### ISSUE TITLE
[Official server] Thaumic Horizons Pocket Plane not generating

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#8235]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
Delta (couldn't be reproduced in singleplayer)

#
#### What did you try to do, and what did you expect to happen?
I opened a node into a thaumic horizons portal and entered it, expecting to land on a platform.

#
#### What happened instead? (Attach screenshots if needed)
I was teleported into mid-air and fell into the void. There was no worldgen except for some nether thorns, so no boundary blocks either.

#
#### What do you suggest instead/what changes do you propose?
This should work as in singleplayer.

#
#### What is your GTNH Discord username?
Combuster

**Comment by boubou19** [comment]
Mhm this is weird if it works in single player but not on Delta. I'll try to investigate this.

**Comment by combusterf** [comment]
This hasn't been fixed, and Barsikus is now complaining about the same issue in the server support chat.
