### ISSUE TITLE
add findit in server pack because it is missing in serverpack

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8236]
#### Which modpack version are you using?
2.1.1.0
#
this is the reason why the "search in the world"keybind doesn't work on servers.

**Comment by Dream-Master** [comment]
Oh never know it is a server mod too.

**Comment by KaneHart** [comment]
Likewise haha. Mitch brought it up to me Yesterday. It actually works now :)

**Comment by boubou19** [comment]
ngl, since i put it server side on the officials, i can now understand the true potential of this mod.
