### ISSUE TITLE
Wireless terminals do not discharge the capacitor bank.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#8237]
Which modpack version are you using?

2.1.1.0

ExtraCells Wireless terminals (Fluid and Universal) do not discharge the capacitor of the ender io can. 
https://imgur.com/a/v8PGcFO

**Comment by boubou19** [comment]
This is likely to be never fixed, as EC2's future is kinda dark.
