### ISSUE TITLE
Mega Blast Furnace cannot be redstone controlled

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8245]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
Tried to turn on mbf only when power was available with covers

#
#### What happened instead? (Attach screenshots if needed)
I cannot get redstone signal to the mbf sides cause it's surrounded by glass

#
#### What do you suggest instead/what changes do you propose?
Change controller placement to 2nd row instead of 3rd
![c0yFCVAggI](https://user-images.githubusercontent.com/17811922/125742625-cd2c9c1d-8cac-49b6-a83f-207349f6578b.png)

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5526

**Comment by Sphyix** [comment]
Solved by #5526
