### ISSUE TITLE
UEV conveyor belt uses double the needed amount of Silicone Rubber

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8250]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
Craft UEV conveyor belt

#
#### What happened instead? (Attach screenshots if needed)
Noticed recipe was changed like all the other conveyor belts to use silicone rubber sheets instead of fluid
UEV conveyor belt recipe is requiring both
![javaw_fJ0LkJCtj0](https://user-images.githubusercontent.com/17811922/125862101-9c2c44b6-3ce0-40ab-abc7-ce24626a3ece.png)

#
#### What do you suggest instead/what changes do you propose?
Remove the molten silicone rubber from the recipe

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by alphaNOVAircraft** [comment]
I think it should stay, having one more fluid in a UEV Component isnt a big deal, UEV components in general arent that hard for being the highest tier in the entire game ...

**Comment by alphaNOVAircraft** [comment]
Changing it would also break current setups for the sake of a few ingots silicone rubber when they dont matter at all in UEV tier

**Comment by boubou19** [comment]
it will not break anything, as the recipe is stored on the datastick.

**Comment by alphaNOVAircraft** [comment]
So you wanna tell me it updates my patterns as well?

**Comment by alphaNOVAircraft** [comment]
Does the old recipe still work when you change it?

**Comment by boubou19** [comment]
old datasticks aren't updated between updates, you have to rescan them manually if you want the new recipes. So if you don't change your automation between updates, there is no reason it stops working.

**Comment by Prometheus0000** [comment]
The whole reason to add the sheets was so it was oredicted, which you can't do with fluids. _Not_ changing it would be stupid.
