### ISSUE TITLE
night vision enchantment don't work

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#8254]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
night vision enchantment don't work
![image](https://user-images.githubusercontent.com/59776356/126040500-71733de0-6a9b-4240-b68d-ddc60ad1fe22.png)
there is no night vision  effect on me
![image](https://user-images.githubusercontent.com/59776356/126040515-87f388d8-be7a-4535-a0e0-4dd6271407e4.png)

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
fix it 
#
#### What is your GTNH Discord username?
Eason1134HK#5098

**Comment by Methes** [comment]
Not at PC so can't check correct names, but have you tried pressing the key triggering Night Vision for IC2 helmets? That works for the enchant too (although Night Vision V seems off. Shouldn't it have just 1 level?)

**Comment by Dream-Master** [comment]
yea guess i need to change it to level 1. Guess there is no better night vision beyond level 1

**Comment by Fuuuuuu502** [comment]
use 'dark steel armor' night vision

**Comment by Impos913** [comment]
Yeah dark steel armor night vision key is the key for night vision enchant.
