### ISSUE TITLE
a suggestion to ease  for people that like to keep vampire playstyle well over higher tiers

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/GT-New-Horizons-Modpack#8256]
this is a suggestion for the vampirism playstyle, the debate about it wont be mentioned, but I'll have to give some background,
many people love the playstyle even if most of the vampirism perks practically  already have better replacements by tech options once players progress in tiers ( for example getting a healing axe, or getting a jetpack).

 this suggestion became necessary especially for people who love to play on the servers and love playing as vampires in them, as a  preferable middle ground suggested by boubs.
 
anyways ,my suggestion is giving vampires a better survivability in the sun once they reach max level  or they reach a better tier

one of the suggestions  that the max level gets  a much longer survivability in the sun, as the current max level  with the vampire armor is only about 1 minute when full on blood (with any other armor/no armor, its  around 30 seconds while full on blood), so perhaps a much longer time in the sun  would benefit vampires alot as they can for example: quickly do what they need to do  in the sun without worrying that any moment they'll spawn 20 graves because they got overkilled by the sun.

a way to nerf it  is to lock the max  vampire level behind something like ichor or something either cheaper or more expensive.

another suggestion is  to code for  an umbrella of sorts, held in hand or if we want to be nice in the hotbar, i do not recommend that the cover  be a block that spawns above the head as that can act weird with the tps, although im assuming suggestion is harder to implement though so perhaps the first one is easier.

=======================================================
a good source about all vampire abilities, levels, its a comprehensive video so i recommend it to everyone as it covers everything one needs to know when deciding on the playstyle
https://youtu.be/zIPvMNb3oAQ
here with it timestamped about how to achieve the last level because  the video is long
https://youtu.be/zIPvMNb3oAQ?t=1918

another video about the many ways to become a vampire from the same guy https://youtu.be/nZ67fD5on_0 

one last thing, the youtube videos i put are one of the best sources about witchery in video form he has a full comprehensive series about almost everything in the mod this is the playlist https://youtu.be/xqxSpeitRM0
also here's the official documentation for the  whole mod it has all the info, https://sites.google.com/site/witcherymod/

**Comment by boubou19** [comment]
I'm heavily for something like that to be implemented, it's a source a conflicts since forever on the officials (and maybe on other servers) because most of the players want to skip night/rain/thunderstorm (bed/wand of focus time/sundial/weather controller...). Witchery is already underused in the pack, so if the players wanting to invest time in the mod by becoming a vampire, then it makes them de facto a pain for the other players, as vampires need night/rain to go outside. Also, witchery tries to be smarter about the night being passed, so villagers never recover blood if the night is not passed normally.

**Comment by PoptartOverlord-Xabedo** [comment]
as you said vampires usually need rain/night to go outside for the usual reasons like resource gathering in the overworld, usually most of the time like any other NH player we're in our base ~~afk~~ uh i mean progressing in tiers, so we don't actually care about the night/day cycle until we happen to need it sometimes
after all, the perfect GT player is the one always automating in their base :3

**Comment by PoptartOverlord-Xabedo** [comment]
something i forgot to mention: there is a way to  gate levels, it the default config option, B:AllowVampireQuests=true, (its already required) which requires vampires to complete "observations of an immortal" book thats found in villages, gathering lost pages by either raiding enough villages or having the book in inventory and murdering mobs until they drop a lost page with a total of 9 needed to complete, do with this info what you will

**Comment by GTNH-Colen** [comment]
Increasing the max time outside seems fine if you are using something like ichor for the final tier but I will say this, vampirism is just too darn powerful and dying in sunlight is pretty much the only counter effect. It's so ridiculous that you can survive /kill AND a hit from an infinity sword with something that you can get at the stone age. So nerfing the only counter to this with something like an umbrella seems to be really broken.

Imo the vampirism needs a lot more work to fit properly into GTNH than just making the max level need ichor, but it's a good step.

**Comment by PoptartOverlord-Xabedo** [comment]
I don't think vampirism should be locked behind anything higher than steam as it simply is not worth it after that as I've stated , the only thing really op about it is that you don't directly die from some things while the things you still die from are amplified, so like you cant die from a skeleton but if that skeleton is an infernal with lightening fire or explosions or simply a flame bow you'd die faster than a human, what's wrong with being able to evade something so far out  of gameplay as /kill or just an infinity sword, most players wont really experience either be it vampire or human or any augmented mess of a thaumcraft monstrosity you made yourself to be. 

if you finally reach higher tiers and get good armor then you're practically as unkillable as the human counterpart except other players cant kill you with their fancy  pre-endgame weapons, i personally never knew the centre of gtnh is pvp to the point we need to nerf stuff that interact with pvp.

keeping with the topic of pvp if you get angry that you cant kill me with your fancy sword maybe that says more about your mod knowledge than anything, think outside of the box and vampires will die like flies with your fly swatter..actually its not a swatter its more of a wooden stake but anyways.

lastly i dont think vampirism really needs that much integration with the pack as its a small part of the witchery mod, as im afraid that if we touch on it too much we might just end up ruining the fragile reasons people using vampirism and we'll just be left off with the masochism of constantly dying to the sun

**Comment by monroth** [comment]
I suggest that gtnh-way to fix vampire survivability is to give you ability to automatically restore your blood bar
like, some sort of ritual that fill your blood from your LP

or item that you put in your tier-6 blood altar that send blood from it to your blood bar
this will both gate it behind ichorium and will force you to do some setup for it

I am a vampire and currently i'm doing automating infusion for Warm blood+placing it in ender chest that i access with soulbound enderbag, but relying on remembering to drink it is annoying

**Comment by monroth** [comment]
> It's so ridiculous that you can survive /kill AND a hit from an infinity sword with something that you can get at the stone age.

btw, it's a myth. At least at GNTH 2.1.1.0 vampires are killed by /kill, by infinity sword and by falling into the void
![Screenshot](https://user-images.githubusercontent.com/28282020/128502860-67714664-3c79-4e62-b64d-cbb770517d46.png)

**Comment by GTNH-Colen** [comment]
> > It's so ridiculous that you can survive /kill AND a hit from an infinity sword with something that you can get at the stone age.
> 
> btw, it's a myth. At least at GNTH 2.1.1.0 vampires are killed by /kill, by infinity sword and by falling into the void
> ![Screenshot](https://user-images.githubusercontent.com/28282020/128502860-67714664-3c79-4e62-b64d-cbb770517d46.png)

I can tell you from experience that /kill does not always one shot a vampire as I consistently /kill xabedo on eta near daily to little effect. I have no idea what the mechanism for this is as sometimes it'll work but most of the time it will not. The inf sword is usually effective but same can apply.

**Comment by PoptartOverlord-Xabedo** [comment]
/kill does not work,  but every time he does it i have to wait  5 minutes to be able to break blocks again 
also you can simply kill a vampire from block suffocation too
for the usual player experience nobody would get  a Colen  or an endgame player to bully them so ultimately those dont matter.

**Comment by monroth** [comment]
well i can file an issue, as inf sword/void/kill work on me on my server consistently

not that it matters, tbh, but still
