### ISSUE TITLE
Add perfect OC to CAL again

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#8259]
The CAL used to feature a perfect OC wich was more or less removed as a bugfix. Now the CAL doesnt feature any advantages over a circuit assembler PA anymore (excpt the crystal+ circuits requiring it) 

See #7016

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/bartworks/commit/e137d2fb58e4672024167347126873bd03de10e2 did not fixed it?

**Comment by alphaNOVAircraft** [comment]
Hm my bad, seems like i missed that change, sry
