### ISSUE TITLE
Shadowmetal Wand Cap Recipe and Entry isn't correct, needs a recipe shift.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#8262]
#### Which modpack version are you using?
2.1.1.0
#
#### What did you try to do, and what did you expect to happen?
I didn't do this but someone else did, but the shadow metal caps specifically say they won't eat the Primordial Pearl used in it, yeah I know, y'all changed the recipe, but like it does *literally* say right there the pearl won't get consumed

<img width="920" alt="Screen Shot 2021-07-18 at 10 50 00 PM" src="https://user-images.githubusercontent.com/78517796/126095711-9a05206c-7a10-481c-85a0-c18985e5cb62.png">

<img width="1030" alt="Screen Shot 2021-07-18 at 10 50 10 PM" src="https://user-images.githubusercontent.com/78517796/126095724-8195e8f7-0e9e-4c7c-a164-05c7f90ffa64.png">

#
#### What happened instead? (Attach screenshots if needed)
pearl gets consumed.
#
#### What do you suggest instead/what changes do you propose?
shift the pearl with the void cap at the top and make it not be consumed. duh. I mean like, or I guess change the text entry, but you know thats a lame cop-out, just shift the cap and the pearl. I mean you know as well as I do that 10% discount isn't going to make a hell of beans that late into thaumcraft with the kind of wands bodies you can make at that point. 
#
#### What is your GTNH Discord username?
Alastors_Game

**Comment by Prometheus0000** [comment]
The repo lang file does not have this text, but the repo version can't be used since it deletes a bunch of items. I don't know where our build comes from. Also see #6868. I was able to edit the script though.

Also, not changing the recipe. It's the best discount for caps, or course it should be expensive, just grow some more pearls.

**Comment by Dream-Master** [comment]
We need to update to the last version but I fear most of the script part need rewritten.
