### ISSUE TITLE
Brewing machine doesnt accept fluids from cells

### ISSUE THREAD

**Issue by JosephStar318** [GTNewHorizons/GT-New-Horizons-Modpack#8265]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
i tried to put creosote fluid cell from gregtech into the advanced brewing machine II (HV tier) by right clicking the cell to the empty tank slot of the machine. i was expecting from cell to pour its content to the machine
#
#### What happened instead? (Attach screenshots if needed)
it didnt pour. the problem stands for the other cells as well
#
#### What do you suggest instead/what changes do you propose?
fix the bug
#
#### What is your GTNH Discord username?
akiswarrior45
![2](https://user-images.githubusercontent.com/44904505/126178837-98e3c909-c28b-44b7-a065-e1820157d75b.png)
![1](https://user-images.githubusercontent.com/44904505/126178844-0fe4255e-ed34-4698-a798-49b2c007ac77.png)

**Comment by TrainerSnow** [comment]
It actually accepts the fluids, just only 750 liters. The gt cells can only I/O 1000 liters at a time. To insert partial amounts, use ic2 universal fluid cells.

**Comment by boubou19** [comment]
why the internal tank of this machine is lower than a bucket is a mystery tho.

**Comment by Prometheus0000** [comment]
bottle/potion = 250L, 3xbrewing machine (like brewery) = 750L.

**Comment by boubou19** [comment]
i would personally call this a stupid restriction, because the machine is more used for stuff unrelated to potions than to potions themselves. Adding a "4th slot" to match 1kL wouldn't hurt imo.

**Comment by Prometheus0000** [comment]
They complained about a bug, the bug doesn't exist. I don't think have a problem with increasing it to 1k, but they didn't ask for that, and the ticket isn't about that. Also, there might be some kind of reason to leave it like this, so I'd want input from other people first.

**Comment by TrainerSnow** [comment]
Made an issue about it having an increased Capacity : https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8272
