### ISSUE TITLE
Feature Request: Add Option to see entire Quest Book

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#8266]
As said in title, i think an Option/Command/Config to be able to see the entire Questbook, without having all quests unlocked, would be nice. Similar to "/bq_admin edit true", just without edit mode, only being able to see all quests. On SP with Cheats enabled this may not be a big issue to quickly run that command to see what quests locks which quests, but in e.g. the official servers players dont have acces to that command.

Example Command: 
/bq viewmode true 
(Would not require OP perms)

#### What is your GTNH Discord username?
TrainerSnow#5086

**Comment by bombcar** [comment]
this would be useful for search, after steam you can get to a place where you need to build a machine, but can't see which quest it is behind.

**Comment by chavalitp** [comment]
Added "View mode" button
https://github.com/GTNewHorizons/BetterQuesting/pull/37

**Comment by Prometheus0000** [comment]
Personally I feel like using a button to activate view mode is like cheating. The quests were not revealed for a reason. Therefore I think a config setting to enable/disable the button would be appropriate, with it defaulting to disabled.

**Comment by mitchej123** [comment]
It's not like people can't view the raw json file... or goto SP and edit mode.  I strongly oppose hiding information.

**Comment by chavalitp** [comment]
I can add "/bq_user viewmode true", "/bq_user spoiler true" command to toggle visibility of the button. Player can run this without cheat enabled.

**Comment by Prometheus0000** [comment]
It sounds like a good idea to me?

**Comment by chavalitp** [comment]
https://github.com/GTNewHorizons/BetterQuesting/pull/38

**Comment by GTNH-Afx237v7** [comment]
There is also now a view button, think this can be closed?

**Comment by miozune** [comment]
yeah and it's enabled by default in the pack
