### ISSUE TITLE
Add Shapeless recipes for hatches/buses

### ISSUE THREAD

**Issue by matt-159** [GTNewHorizons/GT-New-Horizons-Modpack#8273]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Zeta
#### What do you suggest instead/what changes do you propose?
Input/Output hatches/buses have exactly the same recipe apart from the programmed circuit. It would be nice if there was a 1x1 shapeless recipe to swap input hatches/buses to output hatches/buses and vice versa.

**Comment by Prometheus0000** [comment]
They use a chest or tank, they're completely different.

**Comment by King65868** [comment]
They are talking about buses with buses and hatches with hatches, not combining the two

**Comment by GTNH-Afx237v7** [comment]
Please no. This is not FTB. Wether it’s input or output is clearly identified with the control circuit. You will need so many of these anyway for all the setups, best to check what you need and then craft it.

**Comment by alphaNOVAircraft** [comment]
This would let you only automate one of the hatches instead of both. GTNH should be about automatisation of everything not interchangeability of stuff

**Comment by bombcar** [comment]
They’re identical and if you’re automating input busses and swapping the circuit now and then really is gameplay, well then i feel for you son.

if it’s too easy make it take the soldering iron and use a solder

**Comment by Glease** [comment]
Reopening giving it now gains some more attention.

**Comment by bombcar** [comment]
I think it’s reasonable if you want to make it non:free but it would be convienent. Probably everyone would just make inputs and convert to output when needed.
