### ISSUE TITLE
UV GT transformer cannot output 4 full amps

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8274]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
delta (with enet change)
#
#### What did you try to do, and what did you expect to happen?
I was redoing my power grid, and i noticed that my UV transformers weren't outputting 4A. So i made a quick test setup:
![2021-07-21_23 15 10](https://user-images.githubusercontent.com/12850933/126561478-c0824a7a-768e-4b5f-b93e-e8edc055ac8d.png)

As you can see, the measured current is not 4 but 3. In each battery buffer, there are 2 ultimate batteries.
I made a similar setup but by shifting the power 1 tier below:

![2021-07-21_23 16 11](https://user-images.githubusercontent.com/12850933/126561737-a7dbe6b6-642b-4f5e-813d-d8d12959de0b.png)

And i correctly gets the 4A. could it be related to https://github.com/GTNewHorizons/GT5-Unofficial/commit/8badd4b8b614e038b4944dc2e17468c5d2999ffb ?

**Comment by Glease** [comment]
It looks like the increased cap is still not enough and needs increasing further 🤦‍♂️

**Comment by boubou19** [comment]
tested it, and it fixed the issue for UV transformers, but i'm not sure if it affects all the later tiers.
