### ISSUE TITLE
[Quests] Blood magic tier 5 altar (and others) have non-mainline quest requirements

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#8276]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I was working my way down the questline towards convocation of the damned and expected new quests to appear

#
#### What happened instead? (Attach screenshots if needed)
The questline abrubtly ended after tier 4, with no greyed out hints in the questbook on which quests were missing.

After looking at the quest file, it turns out that several BM quests have dependencies on kill-all-the-things quests. In particular, quest 928 for the T5 altar was blocked by quest 916 which is the wither grind quest. This quest in turn requires you to kill tons of all flavours of mobs first, including some pretty uncommon ones such as vanilla slimes. So despite being an UV+ player that quest never finished, the wither quest never unlocked, and the blood magic quests were too far off to even render.

#
#### What do you suggest instead/what changes do you propose?
- Remove the wither hunting quest (916) as a dependency. on the altar quest (928)
- Turn all the twilight forest boss kill quests into mainline quests since these are used as dependencies in several places

- Consider upgrading the enchantment table quest to mainline, and establish a main questline on the `Adept Thaumaturgy` tab, then the beacon quest (1102) can be used as the appropriate prerequisite for the T5 altar with the appropriate mainline status

#
#### What is your GTNH Discord username?
Combuster

**Comment by Prometheus0000** [comment]
The thing is, they might be required for BM, but BM itself is optional. I don't think anything in the main tiers requires TF bosses either.

**Comment by combusterf** [comment]
Blood magic itself is a hard dependency for the `Legendary Quests` tab, and I suspect that through DE it's also a dependency for the `Endgame Goals` tab as a result.

**Comment by Prometheus0000** [comment]
DE isn't required. Neither is endgame goals. Determining what is 'the end' is hard though. Is it getting to UEV? Making a stargate? Completing all the quest? Who knows. Same thing for what is 'required'.

**Comment by Alastors** [comment]
> * Consider upgrading the enchantment table quest to mainline, and establish a main questline on the `Adept Thaumaturgy` tab, then the beacon quest (1102) can be used as the appropriate prerequisite for the T5 altar with the appropriate mainline status

Feck that shite, jesus christ no don't add any more mainline adept thaumaturgy quests, the current mainline quests are absolute ass with how thaumcraft's progression is very non-linear in general.

**Comment by Alastors** [comment]
Have you considered, that bloodmagic, in this pack I mean, is an offshoot of thaumcraft, extremely filled with warp, and by no means should be even close to mainline thaumcraft?

**Comment by Prometheus0000** [comment]
> including some pretty uncommon ones such as vanilla slimes

The special mobs count, so I'm not sure what you mean by this? Also, maze slimes, which are super common in mazes.

> Remove the wither hunting quest (916) as a dependency. on the altar quest (928)

Done, and I mentioned the beacon quest is on the AT tab, but didn't require it.

> Turn all the twilight forest boss kill quests into mainline quests since these are used as dependencies in several places

I'm going with no.

> Consider upgrading the enchantment table quest to mainline, and establish a main questline on the Adept Thaumaturgy tab, then the beacon quest (1102) can be used as the appropriate prerequisite for the T5 altar with the appropriate mainline status

I changed some icon frames to make the path clearer, but I'm not adding a bunch of unnecessary quests.

Just to be clear, they have different icon frames in the magic tabs to guide you through them, not to indicate that they're necessary for main progression.

**Comment by Sphyix** [comment]
> > including some pretty uncommon ones such as vanilla slimes
> 
> The special mobs count, so I'm not sure what you mean by this? Also, maze slimes, which are super common in mazes.

They don't?
Blue slimes don't count, slime beetles have their own quest
Which slimes are the ones in the mazes?

**Comment by Prometheus0000** [comment]
> They don't?

The special mobs ones like blueberry and stuff.

> Blue slimes don't count, slime beetles have their own quest

If blues slimes don't, that's too bad. Slime beetles are not slimes. 

> Which slimes are the ones in the mazes?

The maze slimes are the ones in mazes. I already said this. Just go in one for 5m.
