### ISSUE TITLE
Minnor issue wtih the LV advanced boiler GUI

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#8279]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/38770780/126716232-fd000f73-12ab-449d-9408-c555825b1a5b.png)
I think the renders for the water, heat, and steam are in the wrong layer
#### What do you suggest instead/what changes do you propose?
putting the GUI into the front and the other renders behind it like it does in the HP boiler
![image](https://user-images.githubusercontent.com/38770780/126716404-f3ee96ca-ea83-4f4d-954f-ba6bf7c78f7b.png)

Not sure if this is present in the other boiler types, all I know is that the Bronze and HP coal boiler are fine
#
#### What is your GTNH Discord username?
Doggo_9000

**Comment by SteamDoge9000** [comment]
Update: it also eats up buckets if you put a fluid in the burn slot  and dosent return the empty bucket (ie. iron Creosote bucket)

**Comment by SteamDoge9000** [comment]
Edit 2: it does return dark ashes instead if you give it another Creosote bucket to comsume and burn
