### ISSUE TITLE
Recipe of sulfur dioxide wrong

### ISSUE THREAD

**Issue by s9hysky** [GTNewHorizons/GT-New-Horizons-Modpack#8287]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Check recipes about sulfur dioxide in nei
#
#### What happened instead? (Attach screenshots if needed)
Sulfur dioxide has two ways

way 1: 1sulfur dust+288mb oxygen->432mb sulfur dioxide(Mixer)
           432mb sulfur dioxide->1sulfur dust+288mb oxygen(Distillation Tower)
![srceenshot1](https://user-images.githubusercontent.com/73462892/126934503-eab97a7a-8565-4994-9b91-20f74d4a4c03.png)
![srceenshot2](https://user-images.githubusercontent.com/73462892/126934524-7a2e8aec-6ba4-4de0-a6b1-4d5f0968160c.png)
way 2: 1sulfur dust+2000mb oxygen->1000mb sulfur dioxide(Chemical Reactor)
           1000mb sulfur dioxide->1sulfur dust+2000mb oxygen(Electrolyzer)
![srceenshot3](https://user-images.githubusercontent.com/73462892/126936940-a6ce26e5-b4be-4767-ac6d-998237bcd584.png)
![srceenshot4](https://user-images.githubusercontent.com/73462892/126936948-a001c973-12da-4baf-ba32-2e5cf8c34d9b.png)
Unlimited sulfur can be obtained with chemical reactor and distillation tower recipes.
#
#### What do you suggest instead/what changes do you propose?
Delete sulfur dioxide recipe in mixer and distillation tower
#
#### What is your GTNH Discord username?
s9hy_sky

**Comment by PolkageistHS** [comment]
Yeah, and with 2.1.2.0, sulfur dioxide can be made in a mixer
![image](https://user-images.githubusercontent.com/9247381/147392307-7ffc3d63-4abb-48b1-82ce-5d5c3539463c.png)
1 sulfur + 2 oxygen = 3 SO2

1 SO2 in electrolyzer = 1 sulfur + 2 oxygen
![image](https://user-images.githubusercontent.com/9247381/147392320-967a84f4-62e1-46ce-bed2-fc512d268c4b.png)

Free infinite sulfur (meh) and oxygen (yay) at MV with only two machines.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/179050823-c0f4b29f-d3a4-4104-b349-38c92daebeff.png)

fixed in dev actually.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1062 or similar
