### ISSUE TITLE
extend the fluid hatch locking settings to any other fluid container else than ic2 fluid cells

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8290]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
I was setting up a LCR, and when i wanted to lock the fluid to specific ones, i couldn't use anything else than ic2 fluid cells (not universal ones). Could this be extended to any fluid container? For exemple i know that EIO allows ExU drums to set the fluid filters in the ender fluid conduits.

**Comment by repo-alt** [comment]
Interesting. FluidContainerRegistry.getFluidForFilledItem is used to get the fluid. Should work for all containers
