### ISSUE TITLE
Long Distance Fluid Pipeline quest has confusing text copied from LDIP

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8291]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
mmcc
#
#### What did you try to do, and what did you expect to happen?
The Long Distance Fluid Pipeline quest appears to have a copy-paste from the Long Distance Item Pipeline quest -  it refers to "arrows" that you need to align but doesn't actually have arrows, it has squiggles.
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Reword the quest to correctly describe the LDFP
#
#### What is your GTNH Discord username?
bombcar

**Comment by Prometheus0000** [comment]
What? It has arrows.

**Comment by bombcar** [comment]
I didn’t realize it was referring to the v shaped blocks of pixels on the input and output end and thought it was referring to the orange arrows on the side of the LDIP.  Adding the “pipeline input” and “pipeline output” that waila shows would be jcie
