### ISSUE TITLE
Output Bus ME Duplicates Pu-239 with the Smaller Recipe

### ISSUE THREAD

**Issue by General-Ike** [GTNewHorizons/GT-New-Horizons-Modpack#8293]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
I replaced my Output Bus and ME Interface with an Output Bus (ME), and expected the system to function identically to how it functioned before. Processing 8 Pu-239 and 1 tiny pile of Uranium 238 for 100 Radon.
#
#### What happened instead? (Attach screenshots if needed)
Pu-239 was sent to the output slot of the ULV output hatch in addition to the ME system, resulting in duplication of Pu-239. I blocked the output hatch with an item to prevent the creation of further Pu-239.

Witnesses were administered amnestics, and the anomalous matter was contained for further research :P
#
#### What do you suggest instead/what changes do you propose?
Correct the issue I suppose. I assume this is a different issue from the larger batch recipe, but I don't know why the Output Bus (ME) would case this.
#
#### What is your GTNH Discord username?
Commander Crankshaft

**Comment by Prometheus0000** [comment]
I'm pretty sure @repo-alt  already fixed the ME output bus.
