### ISSUE TITLE
Incorrect Rendering on Railcraft Iron Tank Gauge

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#8295]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private server with no mods added
#
#### What did you try to do, and what did you expect to happen?
I expect the railcraft iron tank gauge to render correctly
#
#### What happened instead? (Attach screenshots if needed)

When items are held in hand it renders correctly:
![javaw_eO4MvpOgd7](https://user-images.githubusercontent.com/31759736/127109531-1a6e0c0b-001b-479e-9829-868d863d91e1.png)

When no items are held in hand, it renders incorrectly:
![javaw_JXwThGSPHm](https://user-images.githubusercontent.com/31759736/127109658-cecd388c-63e2-41ca-808e-0f60a19c75bb.png)

#
#### What do you suggest instead/what changes do you propose?
If possible, fix the rendering
#
#### What is your GTNH Discord username?
ALongStringOfNumbers

**Comment by Prometheus0000** [comment]
Does this happen with _only_ RC? As in, is it RC or some other mod that messes with it?

**Comment by YannickMG** [comment]
Doesn't appear to happen with just Railcraft because this doesn't happpen in runClient.

When I tried in the fullpack the bug was always present when not rendering an inventory.

**Comment by bombcar** [comment]
Do something in the railcraft rendering code only triggers if an inventory. Fun

**Comment by YannickMG** [comment]
I have a real hard time pinning down what causes it. In one case it seems to matter which items are on your itembar but impossible to reproduce in the runClient.

**Comment by bombcar** [comment]
There’s a similar issue here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9418

some OpenGL call isn’t wrapped correctly

**Comment by Glease** [comment]
Any dumb item (i.e. not a block, no enchantment, no durabiliy bar shown) will lead to incorrect render somehow. Presumably RC is not correctly setting up its block rendering.

**Comment by Glease** [comment]
I'd assume it probably forgot to turn on blending for a transparent block.
