### ISSUE TITLE
Ammonium Nitrate Dust missing a capitalization

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#8298]
#### Which modpack version are you using?

2.1.1.0 (latest)

#
#### If in multiplayer; On which server does this happen? 

Private server

#
#### What did you try to do, and what did you expect to happen?

I looked at the name of the dust, and expected every word to be capitalized

#
#### What happened instead? (Attach screenshots if needed)

Well..

![image](https://user-images.githubusercontent.com/16748195/127251702-1ba26454-cdb7-444e-971b-859a243b3729.png)

#
#### What do you suggest instead/what changes do you propose?

Should just be a single character change in a language file somewhere.

#
#### What is your GTNH Discord username?

Shadows

**Comment by botn365** [comment]
is there so it wont oredict with gt++ ammonia nitrate and allow for nitric/ammonia dupes
will be fixed once gt++ is gone

**Comment by iouter** [comment]
just change it......
![image](https://user-images.githubusercontent.com/62897714/127332262-969ec44a-720b-414c-a5ff-9fe6daeab68c.png)

**Comment by boubou19** [comment]
changing it will just enable some duplication in the chemlines.

**Comment by iouter** [comment]
what? this is just need to change a display name.

**Comment by botn365** [comment]
https://github.com/botn365/Botdustries/blob/4e453829d525cf21a25b16a3e033e21d4e42bb98/src/main/java/com/github/botn365/botdustries/loaders/MaterialsClass.java#L61
then go make a pr where only the display name gets changed but not the oredict name

**Comment by iouter** [comment]
why not change the GregTech.lang?

**Comment by Shadowsoftime99** [comment]
Does OreDict really use the display name instead of the internal name for the item? That sounds... Incorrect.

Seconding iouter, don't we have the .lang files that just control display name? That should be all that needs to get changed.

**Comment by botn365** [comment]
they are difrent things but that file is autogenerated or at least that part of the file is

**Comment by iouter** [comment]
yes, changing gregtech.lang can fix it, or something similar.
![image](https://user-images.githubusercontent.com/62897714/127518930-49acbe69-51b9-4e93-ab51-8b301127d2a1.png)

**Comment by Shadowsoftime99** [comment]
It seems like there are some manual display names defined in this directory: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/master/resources

Would this work to add one in here?
