### ISSUE TITLE
A gross error in the logic of the ME system.

### ISSUE THREAD

**Issue by bamik69** [GTNewHorizons/GT-New-Horizons-Modpack#8299]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
other
#
#### What did you try to do, and what did you expect to happen?
If you make two orders of the same items, the result of crafting the item is counted in both orders. Which leads to a decrease in the expected result. I assume that when ordering different items, but with the crafting of the same intermediate items, one of the orders will not be completed, because the intermediate items will not be made in the right quantity.
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
It is necessary to change the logic of the ME system. Parallel crafts should not overlap.
#
#### What is your GTNH Discord username?
bamik

**Comment by repo-alt** [comment]
Eh?

**Comment by boubou19** [comment]
AE is made in a way so you can teach him how to do stuff. But because crafts use the same pattern, they use the same machine. So overlap happens. If you want to avoid overlap, make parallel. Also, if two crafts ask for the same intermediate product, if you want to avoid both craft having the same priority, i think the priority on the ME interfaces work for that.

**Comment by Skiftcha** [comment]
> I assume that when ordering different items, but with the crafting of the same intermediate items, one of the orders will not be completed

no, this is fine

also, result counts only when crafting is started. so if one request is crafting and second is waiting, second wont complete. if both requests are crafting and waiting result, you will get all the results, because ingredients already stored in target machine and does not void

**Comment by repo-alt** [comment]
Looks like everyone but me understands what is the issue...

**Comment by GTNH-Afx237v7** [comment]
I guess if you were to craft 32 LV circuits and then 32 LV machines (assuming each machine takes one circuit) you will end up with „only“ 32 LV machines instead of having both the 32 machines and the 32 LV circuits.

**Comment by GTNH-Afx237v7** [comment]
PS: I just asked my AE to make 32 LV circuits and immediately the same craft again (in parallel on a different crafting CPU) and ended up with 64 circuits just fine...

**Comment by Sphyix** [comment]
> I guess if you were to craft 32 LV circuits and then 32 LV machines (assuming each machine takes one circuit) you will end up with „only“ 32 LV machines instead of having both the 32 machines and the 32 LV circuits.

this is false, you end up with 32 circuits + 32 machines

**Comment by boubou19** [comment]
so not a bug then.

**Comment by GTNH-Afx237v7** [comment]
> > I guess if you were to craft 32 LV circuits and then 32 LV machines (assuming each machine takes one circuit) you will end up with „only“ 32 LV machines instead of having both the 32 machines and the 32 LV circuits.
> 
> this is false, you end up with 32 circuits + 32 machines


Then I don’t understand the issue either...

**Comment by boubou19** [comment]
i'm closing this, as it seems to be an user error.

**Comment by bamik69** [comment]
I'm sorry that I didn't join the discussion in time. I thought I had clearly described the problem.  It turned out that there was no.
At least in version version 2.0.9.0, when ordering items of the same type twice, the item crafting credit was only in one order. Now the situation is different. When a ready-made item appears in the system, it goes to the offset of both orders. As a result, we do not get the sum of the items in two orders, but a certain amount of finished products and a bunch of intermediate ingredients. Because I thought that the work was done, and something was left superfluous. This is not an intersection problem in the mechanisms. This is a problem in the logic of the ME system itself.

**Comment by repo-alt** [comment]
You mean - this is something that changed since version 2.0.9.0, where it worked correctly? Are the items crafted in molecular assemblers or in external machines? Can you reproduce that in a minmal example?, because, as you see, people tried and it worked ok.

**Comment by bamik69** [comment]
I will give an example, although it is not quite correct, but it was with the help of this that I caught the problem.
With the help of the ME system, the automation of the Taumcraft of the altar through the chest is performed. The process is long. A part of the items in the amount of 20 pieces was ordered. After a while, I make a second order of the same items in the amount of 10 pcs. The total for two orders should be 30. But by the end of the execution of orders, there were only 24 items in the system. The ingredients for the remaining six were left in the chest and the altar. And these 6 items were received already without the management of the ME system. That is, if there was no chest, then the ingredients simply returned to the system. And 6 items would not have been done.

**Comment by bamik69** [comment]
> Вы имеете в виду - это то, что изменилось с версии 2.0.9.0, где корректно работало? Созданы ли предметы на молекулярных ассемблерах или на внешних машинах? Можете ли вы воспроизвести это в минимальном примере? Потому что, как вы видите, люди пытались, и это сработало.

They're talking about something else. They didn't understand the situation.

**Comment by bamik69** [comment]
Previously, everything worked correctly. The system could not accept the finished product if resources were not spent on it. Now, some of the resources from one order can be successfully used in another. One order will hang with a lack of resources, and the other will end with a surplus.

**Comment by Sphyix** [comment]
I see what you mean with the issue, this is something that I can reproduce with the final item of a craft going back to the ME system being counted on multiple craft orders.
So ordering the same item twice on 2 different craft orders, I see both crafts ending prematurely when only the items from 1 craft was done.
Example:
I ordered 256 1x aluminium cables, recipe is going to smelt it, make wires, make cables
![javaw_SO4k9QKKpY](https://user-images.githubusercontent.com/17811922/127389072-a224b712-e786-4e79-ba50-5dfd96e2d3a4.png)
This is what I got at the end, but both crafts finished at the same time after receiving just 256 cables, then I received the 256 more of the 2nd craft that was already considered finished from the same 256 cables that finished the first craft
![javaw_7pndbp4pWl](https://user-images.githubusercontent.com/17811922/127389119-ede6bdd9-3235-4213-a814-706a57ffaab0.png)


I cannot reproduce what you explained @bamik69, and for how an ME system should work I can't see how this caused your craft to not finish.
When something is being crafted, and is highlighted as green on the crafting status, items are already out of the ME system and are in the target inventory.
For the items needed in the craft (example: alumium wires) I don't see the bug happening, or causing the craft to wait for items that are never gonna come.
I expected something maybe to dupe when a craft thinks it got items that it never received, but that was not the case either.

**Comment by repo-alt** [comment]
I think it did finish, it just was marked as finished earlier than the job was done. I don't see how it might change since 2.0.9, but I understand the issue. Need to test with simple manual chest base processing recipes.

**Comment by Skiftcha** [comment]
> But by the end of the execution of orders, there were only 24 items in the system. The ingredients for the remaining six were left in the chest and the altar

so you shoud get 30 items total when altar process is done
the problem is not incorrect crafting or item voiding, just wrong status of crafting. ME says its finished when its not yet.
this is useful when something gone wrong with recipe and you need extra ingredients, so you just order them and they are automatically used in first craft.

for your altar crafts you can set blocking mode so you dont have a lot of ingredients in chest

**Comment by bamik69** [comment]
Earlier, I did not attach importance to the fact that there was a stop in the execution of the order in long crafts. And it used to happen that some of the items were lost in the intersection of recipes. Or any other accidents. But I was somewhat surprised that when re-ordering, most of the resources were suddenly found. Now I understand how it happened.

**Comment by bamik69** [comment]
> это полезно, когда что-то пошло не так с каким-то длинным рецептом, и вам нужны дополнительные ингредиенты, поэтому вы просто заказываете их, и они автоматически используются в первом длинном ремесле.

I was also happy about this at first, because earlier I had to re-order a long craft. But, obviously, this entails other problems.

**Comment by bamik69** [comment]
> для ваших поделок на алтаре вы установите режим блокировки, чтобы у вас не было много ингредиентов в сундуке

There will be no excess in the chest without that.

**Comment by bamik69** [comment]
I ordered 2048 solar panels and a couple of batches of components for assembling magic solar panels. As a result, the solar panels were not assembled, since some of the schemes were counted in other crafts. And the system has components for these schemes in the right amount. This is more upsetting than pleasing. And these problems are already making themselves felt with 3 processors of the ME system. And if there are 10 of them? It is unlikely that half of the orders with overlapping components will be completed correctly.

**Comment by Sphyix** [comment]
bamik are you using ec2 crafting storages? (256k+)

**Comment by bamik69** [comment]
> bamik, ты используешь хранилища крафта ec2? (256 КБ +)

No

**Comment by bamik69** [comment]
I put two crafting storages 256 and 1024 in separate blocks, but the system does not see them and does not use them. I haven't figured out why yet. Not required yet.

**Comment by boubou19** [comment]
you need to put at least an AE2 crafting storage to get the EC2 ones to be recognized.

**Comment by bamik69** [comment]
> вам нужно поставить как минимум хранилище крафтинга AE2, чтобы распознать EC2.

Thank you for the hint. But this does not apply to the problem in any way.
