### ISSUE TITLE
Catwalks should have disassembly recipes

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8301]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
mmcc
#
#### What did you try to do, and what did you expect to happen?
The various items in the catwalks mod do not have disassembly recipes, just pulverization to a very small amount of steel
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Some thing like arc furnace to get back 80/90? of the steel used would be nice. Totally amazing would be a recipe that returned the component steel rods
#
#### What is your GTNH Discord username?
bombcar

**Comment by Ngar1** [comment]
look at #5962
