### ISSUE TITLE
Incorrect operation of the ME system.

### ISSUE THREAD

**Issue by bamik69** [GTNewHorizons/GT-New-Horizons-Modpack#8302]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
other
#
#### What did you try to do, and what did you expect to happen?
If you make two orders of the same items, the result of crafting the item is counted in both orders. Which leads to a decrease in the expected result. I assume that when ordering different items, but with the crafting of the same intermediate items, one of the orders will not be completed, because the intermediate items will not be made in the right quantity.
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
It is necessary to change the logic of the ME system. Parallel crafts should not overlap.
#
#### What is your GTNH Discord username?
bamik

**Comment by boubou19** [comment]
you just posted an issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8299 and everyone told you it was not a bug. So stop opening new issues.
