### ISSUE TITLE
Bugs in GT_Recipe.isRecipeInputEqual()

### ISSUE THREAD

**Issue by D-Cysteine** [GTNewHorizons/GT-New-Horizons-Modpack#8303]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
Singleplayer

#
#### What did you try to do, and what did you expect to happen?
I think this method has a few minor bugs:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Recipe.java#L368

Specifically, there's three cases where it returns incorrect results, two of which I confirmed in-game:

1.  Say we have a recipe which uses 72 iron, which is stored internally as a stack of 64 iron and a stack of 8 iron. If we input two stacks of iron, each size 48, the recipe check will incorrectly fail due to the 64-stack of iron in the recipe checking both of the 48-stacks of iron in the input, leaving no stacks left to satisfy the 8-stack of iron in the recipe.
2. Say we have a recipe which uses 72 iron, which is stored internally as a stack of 64 iron and a stack of 8 iron, and we're calling the check with `aDontCheckStackSizes = true`. If we input a single stack of iron, the recipe check will incorrectly fail due to the 64-stack of iron in the recipe checking the single input stack, leaving no stacks left to satisfy the 8-stack of iron in the recipe.
3. This is the one I was unable to confirm; there might not actually exist any recipes in-game which can trigger this case. But say we have a recipe which consumes a feather with certain NBT set. The recipe input check will look at NBT, but the stack size decreasing code ignores NBT, so if we input two feathers, one without NBT and one with NBT, then the code might consume the feather without NBT.

I also talked about the first case here: https://github.com/GTNewHorizons/GT5-Unofficial/pull/594#issuecomment-886060051

#
#### What do you suggest instead/what changes do you propose?
I wrote up an algorithm which should fix all three cases. I'd like to ask for some help in testing this, both making sure that it works correctly, and that it's not significantly slower than before. I wrote up a profiling harness, which will compare the timing and return values of both the current and new algorithms:
https://github.com/D-Cysteine/GT5-Unofficial/compare/experimental...D-Cysteine:recipe-input-check-profiling
(sorry, not the best code, I know, but it's only temporary anyway)
Though, the [stopwatch](https://guava.dev/releases/19.0/api/docs/com/google/common/base/Stopwatch.html#elapsed(java.util.concurrent.TimeUnit)) I'm using says not to use nanosecond precision because it's too precise, but we don't really have a choice because the code runs too fast to use microseconds.

I don't have a good world handy (with lots of machines) to test this in, so could someone build and run that profiling harness in some worlds with lots of machines (probably make a copy, in case a bug deletes all your stuff)? Or send me a world download, and I can test it myself. If you do want to test it, you should see stuff like this in the logs:

```
[12:05:46] [Server thread/ERROR] [gregtech.api.util.GT_Recipe/]: [isRecipeInputEqual] Curr impl times: 4600 ns one run, 895.703 ns over 1024 runs, 407.085 ns overall
[12:05:46] [Server thread/ERROR] [gregtech.api.util.GT_Recipe/]: [isRecipeInputEqual] New impl times: 6600 ns one run, 261.133 ns over 1024 runs, 254.593 ns overall
[12:05:46] [Server thread/ERROR] [gregtech.api.util.GT_Recipe/]: [isRecipeInputEqual] Total calls: decrease 23, don't decrease 487782
```
I'm interested in this timing info after running a machine-heavy world for like at least 5 minutes. Also, look for `[isRecipeInputEqual-diff]`; those are cases where the current and new algorithms return different values. They look like this:
```
[12:05:46] [Server thread/ERROR] [gregtech.api.util.GT_Recipe/]: [isRecipeInputEqual-diff] Got diffs in return (true, false, false, true) for:
Recipe: [[]], [[64xtile.button@0, 40xtile.button@0, 1xic2.itemPartCircuit@0, 1xgt.metaitem.02@18019]]
Inputs: [[null]], [[28xic2.itemPartCircuit@0, 28xgt.metaitem.02@18019, null, null, 48xtile.button@0, 64xtile.button@0, null, null, null]]
[12:05:46] [Server thread/ERROR] [gregtech.api.util.GT_Recipe/]: [isRecipeInputEqual-diff] Got diffs in stacks (true, false, false, true) for:
Recipe: [[]], [[64xtile.button@0, 40xtile.button@0, 1xic2.itemPartCircuit@0, 1xgt.metaitem.02@18019]]
Inputs: [[null]], [[28xic2.itemPartCircuit@0, 28xgt.metaitem.02@18019, null, null, 48xtile.button@0, 64xtile.button@0, null, null, null]]
Curr stacks: [[null]], [[28xic2.itemPartCircuit@0, 28xgt.metaitem.02@18019, null, null, 48xtile.button@0, 64xtile.button@0, null, null, null]]
New stacks: [[null]], [[27xic2.itemPartCircuit@0, 27xgt.metaitem.02@18019, null, null, 0xtile.button@0, 8xtile.button@0, null, null, null]]
```
This is a good test case to see the bug:
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8215

Give the assembler two stacks of 60 buttons each to test the first case; give it a single stack of buttons to test the second case. You'll see diff messages show up in the logs for both cases.

In my limited testing, I'm seeing the new algorithm taking about 103% of the time vs. the current algorithm for `aDecreaseStacksizeBySuccess = false`, and ~50% of the time for `aDecreaseStacksizeBySuccess = true`, but the results might be skewed because I don't have a good world to test this on. Thanks in advance for any help!

#
#### What is your GTNH Discord username?
D-Cysteine

**Comment by GlodBlock** [comment]
yeah, that's true. and your algorithm seems can solve this problem prefectly.
the main optimization in your algorithm is 
https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L550 and https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L592 . 
that why it takes less time than the old one at most time. nice pruning.
i think you can make a pr so we can test performance of your algorithm in zeta testing server.

> sorry, not the best code, I know, but it's only temporary anyway

theoretically, the recipe find/equal algorithm can be optimized into O(NlogN). (now is O(N^2))

1.  sort the mInputs and aInputs according to the item/fluid type, merge the same item type(itemstack may over 64). O(NlogN)
2.  use KMP to check wheather aInputs is the substring of mInputs. O(N+M)

but it is too hard to implement because of the code complexity, and since N is not very large in gt recipes, this algorithm is only a bit faster than yours.

my english is not good, so i may misunderstand something or express my ideas inappropriately.

**Comment by D-Cysteine** [comment]
Hmm, for these lines:
 * https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L550 
 * https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L592

I think they end up pretty much equivalent to the `temp` check, which serves the same purpose as the `amt > 0 || !found` check:
 * https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L641
 * https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L673

There is an optimization in the removal of the second set of `O(n * m)` loops in case `aDecreaseStacksizeBySuccess = true`:
 * https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L677-L729

In the new algorithm, that is instead replaced by just some `O(n)` loops, since we already did the amount calculations:
 * https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L600-L615

So I didn't actually expect to see much of a speed-up in the `aDecreaseStacksizeBySuccess = false` case. In fact, it would make sense for there to be a slight slow-down due to the need to do a pre-copy step in the new algorithm:
 * https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L524-L530
 * https://github.com/D-Cysteine/GT5-Unofficial/blob/723430fec817b12d1bc39fed4ca9fba8973afcdb/src/main/java/gregtech/api/util/GT_Recipe.java#L559-L565

---

I was curious, so I did some more testing, and it looks like there is actually a sizable time penalty applied to the first method that is called. This is probably why they discourage using nanosecond precision with this implementation of `Stopwatch`. I attempted to mitigate this: https://github.com/D-Cysteine/GT5-Unofficial/commit/d0909f85b8c713972e61a205feeba68b1cd6584b

Now we see results that make more sense, with the new algorithm taking slightly longer:
```
[21:02:58] [Server thread/ERROR] [gregtech.api.util.GT_Recipe]: [isRecipeInputEqual] Curr impl times: 800 ns one run, 137.500 ns over 1024 runs, 389.756 ns overall
[21:02:58] [Server thread/ERROR] [gregtech.api.util.GT_Recipe]: [isRecipeInputEqual] New impl times: 3700 ns one run, 153.613 ns over 1024 runs, 391.296 ns overall
[21:02:58] [Server thread/ERROR] [gregtech.api.util.GT_Recipe]: [isRecipeInputEqual] Total calls: decrease 128, don't decrease 567656
```
I added some more optimization by lazily initializing the arrays of copied amounts (https://github.com/D-Cysteine/GT5-Unofficial/commit/9e5190b00a20a4fa88daac10cad1919d43fee3f5), and was able to get time spent down to about 103% of the current algorithm for `aDecreaseStacksizeBySuccess = false`, and ~50% of the time for `aDecreaseStacksizeBySuccess = true` (not enough data for this case, but 50% makes sense since we skip about half the code).

For the theoretical best case, I think we could actually get `O(n + m)` if we iterate over all inputs and recipe ingredients, and store the sum of their amounts in a hash map (with recipe ingredient amounts being negated). But it may not be worth doing this; the algorithm is already so fast that any speed gains we may get may be outweighed by the hash map overhead (and the cost of reconstructing the new stack sizes, if `aDecreaseStacksizeBySuccess = true`), and we'd have to figure out a good hashing algorithm that handles ore dictionary.

Thanks for your thoughts! Your English is perfectly readable.
