### ISSUE TITLE
[AE2] Oredictionary filter card issues

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#8306]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Use the oredictionary filter card in combination with storage and export busses for the ore processing setup to filter based on various settings
#
#### What happened instead? (Attach screenshots if needed)
Issue 1:
Set oredictionary filter card in export bus to `oreBr*` and expect it to export only `oreBrownLimonite`. However it also exports `oreBarite` and `oreBandedIron` as if the filter setting was actually `oreB*r*`, meaning it will export all ores that start with **B** and contain an **r**
Issue 2:
Set oredictionary filter card in storage bus to `gem* & !gemDiamond* & !gemCertus*` in order to separate Diamonds and Certus Quartz gems from other (e.g. chipped, flawed etc) variants. Works as expected.
However when shortening the term to `gem* & !gem(Diamond*|Certus*)` the filter functionality is completely disabled, meaning no gems pass through this storage bus at all.
The shortening works just fine when using only `gem(Diamond*|Certus*)` however.
#
#### What do you suggest instead/what changes do you propose?
Review how filtering works.
Also, additional suggestion: Rename the card to `Ore Dictionary Filter Card` instead of `Oredictionary Filter Card`

#
#### What is your GTNH Discord username?
Afx237v7

**Comment by repo-alt** [comment]
Well, I cannot reproduce 1. (can you test in new Dev Pack (2.1.1.1) just released?)
As for 2, it is "as designed", because anything containing brackets (or any special symbols except & and |) is interpreted as a regexp

**Comment by GTNH-Afx237v7** [comment]
I have had my ore processing running with AE2 beta51 from Jenkins. Just updated to beta52 (latest as of today), built a small test setup and can also not reproduce it.

As for item 2, I do not understand what your answer means. I take it that this combination is simply not possible?

**Comment by repo-alt** [comment]
"Complex" strings are interpreted as regular expressions, you can do anything with them.
https://en.wikipedia.org/wiki/Regular_expression

**Comment by GTNH-Afx237v7** [comment]
I’ll keep an eye on issue 1, but consider it `cannot reproduce` for now. As for issue 2 I’ll have to have a look at how to setup the regex correctly. For now I’ll close this.
