### ISSUE TITLE
MV energy hatch gated behind lubricant not really good

### ISSUE THREAD

**Issue by remyr** [GTNewHorizons/GT-New-Horizons-Modpack#8308]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
It's not related to multiplayer
#
#### What did you try to do, and what did you expect to happen?
I want to craft MV energy hatch, but there is no quest for that because I didn't do the lubricant quest that is gated behind Pump & Oil and I didn't go to that route. I craft my lubricant with creosote oil and distilery. So I have to craft a pump for "nothing".
#
#### What happened instead? (Attach screenshots if needed)
I have no quest for MV energy hatch, but I have tech to craft it.
#
#### What do you suggest instead/what changes do you propose?
Maybe an easy solution is to move the lubricant quest somewhere else, or change the MV quest to not be gated behind lubricant.
#
#### What is your GTNH Discord username?
Shelby.

**Comment by Dream-Master** [comment]
Mv Hatch need lubricant so i dont see the point in changing it. Many Quest have dependencies and the Lubricant Quest is a Main Quest.

**Comment by Prometheus0000** [comment]
See #8379

**Comment by chochem** [comment]
the lubricant/hatch is fine. needing a basic pump and drilling pipes for lubricant is weird though. Can still be main, its important but not a requirement for a distillery ideally.
