### ISSUE TITLE
ae2 subnet is connected to the drive BUG

### ISSUE THREAD

**Issue by Fuuuuuu502** [GTNewHorizons/GT-New-Horizons-Modpack#8313]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
multiplayer server
#
#### What did you try to do, and what did you expect to happen?
drive access to the sub-network, reduce the main network channel consumption
#
#### What happened instead? (Attach screenshots if needed)
after the ae2 sub-network is connected to the drive, take away some of the items of the drive and move away from the block to unload it. after returning to the block, the items in the drive remain the same
![}P11(02844}J(3HM3TL`Y_J](https://user-images.githubusercontent.com/55508096/127660543-317b60bd-e849-44db-8af6-b5ec3ec32a29.png)

![0SC_`TQYDPHK0C`R1EB}L R](https://user-images.githubusercontent.com/55508096/127660180-44703ce7-b4e5-464b-8a97-114d3352d73e.png)

#
#### What do you suggest instead/what changes do you propose?
fix it. this happened in overworld
#

**Comment by repo-alt** [comment]
1. "ae2 subnet is connected to the drive" - can you explain? Is that just usual storage subnetwork, visible from the main one through the storage bus? Or do you somehow connect to the drive from 2 different networks?
2. What is the server kernel, if it is the server?

**Comment by Fuuuuuu502** [comment]
> 1. "ae2 subnet is connected to the drive" - can you explain? Is that just usual storage subnetwork, visible from the main one through the storage bus? Or do you somehow connect to the drive from 2 different networks?
use p2p-me to connect the Me-drive. one network provides the channels needed by p2p-me, one network delivers p2p-me, and the Me driver connects to the delivered p2p-me network. a single network will not this bug
> 2. What is the server kernel, if it is the server?
Thermos

**Comment by Sphyix** [comment]
considering thermos is used, this looks like the chunk where the drives are located rolled back when it got unloaded and reloaded

**Comment by boubou19** [comment]
there is a rumour about how to fix those small rollbacks in chunks: place a block in the chunk.

**Comment by repo-alt** [comment]
Looks very much like that, because cells in drives write NBT immediately after the transaction. (Unlike, e.g. quantum chests)

**Comment by Fuuuuuu502** [comment]
the drive is black because there is no p2p-me and it is not connected

![image](https://user-images.githubusercontent.com/55508096/127664679-9255ee53-e393-4bbd-8d00-17bdd1649503.png)

> considering thermos is used, this looks like the chunk where the drives are located rolled back when it got unloaded and reloaded

very likely
