### ISSUE TITLE
Proposition for better wand tiering. We all know its bad right now as Tungstensteel has 90% of wands

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#8314]
#### Which modpack version are you using?
It hasn't changed, but for what it's worth 2.1.1.0 and 2.1.0.6b (about to update to 2.1.1.1a but whatever)
#
#### What do you suggest instead/what changes do you propose?
Aight, those who've done thaumcraft (even if only a little bit) in this pack have noticed one major thing

<img width="1159" alt="Screen Shot 2021-07-30 at 12 26 15 PM" src="https://user-images.githubusercontent.com/78517796/127683016-98fb699c-c9c7-4709-872a-9663be075980.png">

that over approximately 63% (12/19) of wands are gated above titanium, close to 53% (10/19) of those being gated at *tungstensteel alone*. 

Sure one could argue the 6 primal wands that all reside using titanium screws make it more like 48% of all wands. But as you can see even y'all, the devs, think that the functionality is so similar that you just shove them all into one giant wand core slot, since they are literally the exact same wand that recharges 10% of a different primal in each case. My point here being, no, they are the same wand just attuned differently. 

You may be saying to yourself now "Get on to the point, why are you bothering me with this useless fluff?" 

Well you see, I wish to fix that. I want to shift each wand tier down a peg. As noted below, the only shift between hv wands and ev wands is the maximum 30 additional vis if you go through the thaumic bases route. (Or 37.5-45 if you include scepters)
<img width="407" alt="Screen Shot 2021-07-30 at 12 33 15 PM" src="https://user-images.githubusercontent.com/78517796/127683868-55b92407-bd8b-4cbe-a540-c208def4ef79.png">

However, once you get to tungstensteel, you get this massive jump that spanns from the 100 vis possible (silverwood, blood, blood infused, dreamwood, livingwood, and witchwood) to flippin 250 capacity possible (warpwood). The most common jump that doesn't involve massive warp (that being the warpwood wand) being the void wand core of thaumic bases with it's rather simple recipe and 160 vis capacity. 
<img width="639" alt="Screen Shot 2021-07-30 at 12 38 29 PM" src="https://user-images.githubusercontent.com/78517796/127684468-5f313952-b41d-412c-8886-02d4926267fc.png">
<img width="411" alt="Screen Shot 2021-07-30 at 12 36 31 PM" src="https://user-images.githubusercontent.com/78517796/127684275-2ba52c31-b9da-40d8-ab0d-b0fd2dadf6ab.png">

You may be asking yourself, "Jesus wtf happened here, why are there so many of the exact same wands gated in tungstensteel? And that would be my point exact. 

#### My Proposition
Shift every wand thats silverwood and below down one tier, and honestly, use a different material than titanium for ev tiered wands. 

and combine the current mv wands with the current 2 main wands while leaving the profaned wand at hv. while obviously making the "3 ev" wands hv instead.

This would provide a big relief away from the current meta of wand crafting that involves you making like 17 million different wands the second you can make tungstensteel in hv.

You want to know the real reason everyone tierskips ev wands? It's literally because 1. they are all useless as is. And 2. *newsflash* tungstensteel is easier to obtain than titanium in ev. Like incredibly easier. You literally can just go to the end and mine up endstone to turn it into tungstate if you want to. Or even go a step further and mine the end for scheelite and achieve tungstensteel with machines that you can make in hv (double energy hatch the lcr, don't @ me everyone knows you can do that, quadroupling the voltage didn't change anything) 

#
#### What is your GTNH Discord username?
Alastors_Game

**Comment by Alastors** [comment]
I will also be making a ticket for changing how caps are tiered too, since it's just as bad as wand core tiering as of right now.

**Comment by AiramProvoker** [comment]
Seems like a thought-out suggestion, however, it won't change the meta of making the fattest scepters ASAP.
I like it overall.

Also to shamelessly bring my own issue into this thread, on a related note, the offensive foci still need a buff: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6941 👀

**Comment by repo-alt** [comment]
Well, you cannot make tungstensteel at HV in the current version. but I agree that the gating may be more gradual.

**Comment by Alastors** [comment]
> Well, you cannot make tungstensteel at HV in the current version. but I agree that the gating may be more gradual.

can you not? as I recall it was simply 4 amps of hv for the 1 amp ev equivalent into 2 hv energy hatches, which would be doable in hv since you can use 2 energy hatches with lcrs?

though I will say, I haven't updated to the latest dev yet since I've been hecka way too busy.

**Comment by repo-alt** [comment]
Tungstate -> Sheelite step requires EV autoclave, and I don't think you can get pure Sheelite before Mars.

**Comment by ScriptedPiky** [comment]
Here are my thoughts on retiering most of them. I know I forgot some of them but this should cover a good portion of it?
**Pre-EV age**
Basic/iron wands: still aluminium
Greatwood: darksteel
Gold wand caps: still aluminium
Silver wand caps: still stainless
Thaumium wand caps: vibrant alloy
The 6 wand cores before Silverwood: energetic alloy
Transmutative rod core: energetic alloy
Silverwood wand core: vibrant alloy
Thaumium wand core: vibrant alloy(?)
Livingwood and Dreamwood rod core: vibrant alloy
Terrasteel & Manasteel wand caps: vibrant alloy
(Other rods & caps I forgot can fall into these materials)

**EV+ age**
Crismon-Stained Cloth Caps: **this cloth material will need an infusion altar recipe instead and or just a different material right before EV or slightly after EV due to its 15% vis cost reduction**
Void metal wand caps: titanium or tungstensteel or HSS-G
Elementium wand caps: titanium or tungstensteel or HSS-G
Voidmetal wand core: titanium or tungstensteel
Warpwood wand core: HSS-G
Shadowmetal wand caps: HSS-G or Iridium if you want it to be gregified even harder
Ichorium wand caps and Ichorium wand cores: Unchanged

**Comment by ScriptedPiky** [comment]
There are currently two Pull Requests I have to begin to alleviate the problems, though this is particularly aimed towards the Wand Caps. As for the Wand Core shenanigans, I have absolutely no idea how to modify them, as they are using GT tiers and thus, result in the +50% of the wands being Titanium or Tungstensteel+

https://github.com/GTNewHorizons/Scripts/pull/1 - Tainted Magic Cap Rebalance
https://github.com/ScriptedPiky/Scripts/pull/1 - Thaumium Cap Retier (I really hope I got this pull right, if not, please tell me if it'll merge into GTNH Master)

**Comment by D-Cysteine** [comment]
Should this line:
 * https://github.com/GTNewHorizons/GTNH-TC-Wands/blob/master/src/main/java/com/gtnewhorizons/tcwands/api/wandinfo/WandDetails.java#L27

be `tieredMaterials[i] = ...` instead?

I think right now, if we add more tiers, we may get null pointer exceptions since their indices in the array aren't getting set, and they instead just overwrite `tieredMaterials[7]`?

**Comment by ScriptedPiky** [comment]
That I have no idea. Boubou was the one that helped implement that and so maybe? Not sure what'd happen if it's possible to even add more tiers.

@boubou19 Need thy help for this, heh.

**Comment by boubou19** [comment]
yeah small oversight

**Comment by Dream-Master** [comment]
@boubou19 @ScriptedPiky can you fix that ?

**Comment by boubou19** [comment]
will do a PR when i'll have some free time. Right now it's not an issue as that part of the code is never executed as the loop condition is never met. It will tho if we add a new tier in the GTTier enum it will tho hence why it need to be fixed
