### ISSUE TITLE
AE2 refuses to start the craft

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8315]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
Tried to autocraft void miner 2, asked for 1 and tried to click Start from the crafting plan

#
#### What happened instead? (Attach screenshots if needed)
Craft refuses to start
All the items for it are available
I'm not using ec2 at all in my system
Disk space is available (around 18 64k drives empty)
I tried removing power to restart the system, no difference
Whole base should be correctly chunkloaded
![eXzdhVbvUN](https://user-images.githubusercontent.com/17811922/127712493-50814daa-9e71-401a-bbc7-b33f76485c97.gif)

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by repo-alt** [comment]
What is the recipe pattern? Perhaps the interface with the pattern is in blocking mode and points to a non-empty inventory?

**Comment by Sphyix** [comment]
Is that going to prevent an entire craft to start?
There is a ton of stuff in that recipe that needs to be crafted

**Comment by GTNH-Afx237v7** [comment]
Have encountered this too, however rarely. Maybe need to restart the game and try again. Alternatively I have the feeling that AE won’t start if there is not enough energy stored in the network (though I have no proper explanation for this), so you can try add more (dense) energy cells to give AE more power reserve.

**Comment by Sphyix** [comment]
I just tested the blocking mode and is not stopping me to craft stuff
I can try adding a few dense energy cells, but there's a neutronium energy cell installed
![javaw_KrFSeR9Zqm](https://user-images.githubusercontent.com/17811922/127731996-a8a316cd-d61d-48bd-9814-b1e9c56671cb.png)

**Comment by Sphyix** [comment]
I added 16 dense and charged them with EU (they won't charge from the neutronium energy cell) and craft started.
Not sure if it's just a case, I'll report back in a few days if it happens again.
If it doesn't then there's something wrong on how the neutronium energy cell gives power to AE

**Comment by GTNH-Afx237v7** [comment]
Well I noticed it too, that the neutronium energy cell will not charged any attached energy cells (dense or regular), don’t know if that is intended or not.

**Comment by repo-alt** [comment]
Interesting, looks like creative cell capacity is not quite counted in simulation...

**Comment by Sphyix** [comment]
> Interesting, looks like creative cell capacity is not quite counted in simulation...

It looks like this is the issue, it happened once or twice that a craft wouldn't start, but nothing like when I had no dense energy cells in the system.

**Comment by repo-alt** [comment]
Well, I was unable to see just from the code, why creative cell may be somehow not counted, and it is not trivial situation to reproduce in dev, so I'll consider this bug a low priority, since there is a workaround.
