### ISSUE TITLE
Large boiler , incoplete structures 

### ISSUE THREAD

**Issue by degree414** [GTNewHorizons/GT-New-Horizons-Modpack#8316]
#### Which modpack version are you using?
2.1.1.1 dev
#

#
#### What did you try to do, and what did you expect to happen?

Tried to put the Large Boiler

And also those that stood the boiler, they also stand with incoplete structures 

#
#### What happened instead? (Attach screenshots if needed)
Instead, it issues an incoplete structure
![2021-07-30_22 32 46](https://user-images.githubusercontent.com/88080877/127714587-f1e59a19-4176-446c-9197-0d9231829619.png)
![2021-07-30_22 32 49](https://user-images.githubusercontent.com/88080877/127714590-9ff1788a-f447-4d0a-a9f2-a7910e81a45e.png)
![2021-07-30_22 32 57](https://user-images.githubusercontent.com/88080877/127714591-6c2d9fc9-beca-4eca-8ba1-e50e0d033fba.png)
![2021-07-30_22 33 14](https://user-images.githubusercontent.com/88080877/127714592-c4c7c0bd-80d6-49ca-8a2e-12ef84871a45.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it or tell me that I'm stupid and what I'm doing wrong
![2021-07-30_22 33 14](https://user-images.githubusercontent.com/88080877/127714592-c4c7c0bd-80d6-49ca-8a2e-12ef84871a45.png)
#

**Comment by Dream-Master** [comment]
@degree414 try this file and report if it is fixed or not. Thanks
http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1415/

**Comment by degree414** [comment]
> @degree414 try this file and report if it is fixed or not. Thanks
> http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1415/

Ty it's fixed
