### ISSUE TITLE
Pyrolyse Oven Won't Form

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#8319]
#### Which modpack version are you using?
2.1.1.1a
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Just checking multi-blocks and such after update. Noticed the following tooltips were wrong on casing count:

- [x] Processing Array - Changed from 13 casings required to 14 casings required.
- [x] Mult-Smelter - Won't form with Energy hatch in the top layer anymore.
- [x] Implosion Compressor - Requires more casings than tooltip says. I think it says 16 but needed more. Not sure of number.
- [x] Pyrolyse Oven - No longer forms. Tried rebuilding multi. Still won't form. Meet all requirements stated on tooltip.

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
The tooltips are sort of cosmetic, albeit misleading. Pyrolyse not forming is sort of a big issue (at least for me).
#
#### What is your GTNH Discord username?
shawnbyday

**Comment by Glease** [comment]
> Processing array

I have checked the git history dating back to 2018. The actual structure checking code and the description of this multi always says 14 at minimal. Not sure where your 13 comes from.

> Multi-Smelter

Same as above.

> Implosion Compressor

Yeah I used `>` where `>=` should be used. Will send PR once I know where the other problems in this issue comes from.

> Pyro Oven

Will check later. Kind of in a rush atm.

**Comment by shawnbyday** [comment]
I guess a better way to put it is: last version I was on 2.1.0.7a I used one less casing to form the Processing Array and Implosion Compressor. In order to get them to form after switching to 2.1.1.1a I had to remove a bus and add a casing. Maybe another > >= type of thing?

**Comment by Glease** [comment]
Yeah you are right. They are actually using the same structure checking code so they have the same kind of problem. Upgrading to [latest gregtech](http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1418/artifact/build/libs/gregtech-5.09.37.04.jar) should fix the compressor and PA problems. Fixing the pyro oven problem however require also updating to [structurelib 1.0.8](http://jenkins.usrv.eu:8080/job/StructureLib/lastSuccessfulBuild/artifact/build/libs/StructureLib-1.0.8.jar).

What about the multi smelter thing though?

**Comment by shawnbyday** [comment]
The multi-smelter problem was only prior to the upgrade it worked with the energy hatch on the top layer (above the coil) after the upgrade the energy hatch had to be moved to the bottom layer (below the coil). The number of casings and everything else stayed the same on that one.

**Comment by Glease** [comment]
It seems to be bart's decision to allow energy hatches everywhere, where previously (pre 2.1.0.0) it is allowed in bottom only. I won't object anyone changing it to bart's form, but I won't do it.

**Comment by shawnbyday** [comment]
I have no complaints with it being bottom only. The tooltip reflects it properly so good there.

**Comment by Glease** [comment]
The related PRs are all merged. Closing for now.
