### ISSUE TITLE
Molecular Transformer making amps disappear

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8322]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
delta, eta

#
#### What did you try to do, and what did you expect to happen?
Tried to connect 16 molecular transformers to a 64A UEV dynamo to make platinum dust
Expected no fairies to interfere and make my amps disappear

#
#### What happened instead? (Attach screenshots if needed)
Only 2 molecular transformers turned on, consuming 64 amps and only outputting like 2-3 amps were being used
Screenshot shows the test made on eta with colen, tried both on delta and eta to understand if the new enet changes were at fault, but both servers behave the same.
![javaw_2pq7y2Yhqk](https://user-images.githubusercontent.com/17811922/127750255-d183dfdc-0d62-4aed-a21f-bdf30b2a3af3.png)
![CHar3YiZYP](https://user-images.githubusercontent.com/17811922/127750257-57198260-e828-40b7-863e-997f0b3a4853.png)

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
Pandoro#4811

--Edit
wrong machine name

**Comment by repo-alt** [comment]
I thought first MT would eat everything

**Comment by Glease** [comment]
Multi amp GT EU will have reduced efficiency when converted to IC2 EU. I don't quite know the exact formula, but this is working as intended.

**Comment by Sphyix** [comment]
64 amps transformed to 2 amps? I don't believe there is a 95+% loss on the conversion

**Comment by Sphyix** [comment]
I should add that I can get the same 2 molecular transformers to work at the same rate by feeding 2 amps on the same cable instead of 64, the other 62 amps are just disappearing

**Comment by Glease** [comment]
I'm currently busy fixing something else and lack the time. Could you please help do the following test: Try snap a said machine right next to a GT lightning rod. See if they are producing on the same rate. 

If not I'll reopen the issue, but otherwise it's working as intended.

**Comment by Sphyix** [comment]
They always produce at 1 tick rate, 64 or 1 amp... I don't understand what's going to change with a lightning rod but I can try

**Comment by Glease** [comment]
Ah ok, sorry for premature closing. It sounds like a problem with how molecule assembler accept energy. Reopen for now.

**Comment by Sphyix** [comment]
> Ah ok, sorry for premature closing. It sounds like a problem with how molecule assembler accept energy. Reopen for now.

Maybe my first explanation wasn't clear enough, my fault

I tested again with a debug power generator set to 4482 amps UEV, connected to 2 molecular transformers
cable is saying 4482 amps are being used
![javaw_NKPrNdmGoD](https://user-images.githubusercontent.com/17811922/127750874-9352e79e-5b3d-41d7-a33a-3dd9f93bb3f1.png)

**Comment by GTNH-Colen** [comment]
Can't believe you're giving away exclusive pics of my secret eta lair ;)

**Comment by Sphyix** [comment]
Oh no, didn't know it was a secret :(
