### ISSUE TITLE
[Discussion] Is the GT++ threaded Super Buffer actually threaded?

### ISSUE THREAD

**Issue by D-Cysteine** [GTNewHorizons/GT-New-Horizons-Modpack#8324]
So I've been poking around in the buffer code, and I think the GT++ Super Buffer threading code might just be broken? I don't know a whole lot about threading, so can any Java threading experts / Super Buffer experts take a look at this?

---

Here is the code for the base class of the Super Buffer:
> https://github.com/GTNewHorizons/GTPP/blob/master/src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_ThreadedBuffer.java

and here is the code for the thread that this base class starts:
> https://github.com/GTNewHorizons/GTPP/blob/master/src/Java/gtPlusPlus/xmod/gregtech/api/objects/GregtechBufferThread.java

Here is the Super Buffer class itself (doesn't contain any threading code, so probably not relevant):
> https://github.com/GTNewHorizons/GTPP/blob/master/src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/automation/GT_MetaTileEntity_ThreadedSuperBuffer.java

---

It looks like this class is attempting to do multi-threading by moving the implementation of many methods into the thread class, and then calling the thread's method instead of the superclass's method, e.g.:
> https://github.com/GTNewHorizons/GTPP/blob/master/src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_ThreadedBuffer.java#L323-L326

but my understanding is that this just causes the calling thread to execute the thread's method, i.e. still single-threaded. In order for this to truly be multi-threaded, the operations would have to be done within the thread's `run()` method, but you can see that this is not the case:
> https://github.com/GTNewHorizons/GTPP/blob/master/src/Java/gtPlusPlus/xmod/gregtech/api/objects/GregtechBufferThread.java#L189-L222

---

So am I missing something? Is this really just broken and basically just single-threaded, but with the overhead of an additional thread that doesn't actually do anything?

If I'm right, and this threading is not working, then can we delete the GT++ Super Buffer? I want to make some changes to the GT Buffer, which this is a subclass of, and those changes will break the Super Buffer if we don't update it or delete it. (Not to mention, the GT++ Super Buffer code has not picked up some other changes to GT Buffer, such as the addition of stocking mode and sorting, and so may already be broken)

The GT++ Super Buffer is craftable in-game currently, and in fact is more expensive than the regular GT Super Buffer (recipe is data orb + GT Super Buffer + conveyor belt). So players may have placed these already. If we do want to delete it, is it possible to replace existing instances with the regular GT one? I checked, and it looks like for each tier, the GT++ Super Buffer and regular GT Super Buffer actually have the same capacity, so the only differences I think are this threading stuff, and the GT++ one requires EU while the GT one doesn't.

**Comment by repo-alt** [comment]
Should be deleted, yes.

**Comment by D-Cysteine** [comment]
Okay, works for me. How do we delete this safely (i.e. replace existing instances with the regular GT Super Buffer)? Is it something like, we delete the code, but leave behind a dummy item with the same item ID, and add in a crafting recipe that just converts it into the GT Super Buffer? Or do people not use this at all, so we can just straight delete it?

**Comment by Glease** [comment]
It's GT meta generated stuff, so it will leaves behind a dummy item/block automatically if you remove the related code.

**Comment by repo-alt** [comment]
If it uses same NBT as normal super buffer, might just remap it. See example of remapping e.g. in Railcraft (mods.railcraft.common.core.Railcraft.missingMapping)
If not then we may remove the recipe first, and after some time interval remove the block as well.

**Comment by Glease** [comment]
You cannot remap a GT meta generated item. All gt machines (and most if not all addon machines) uses the same Item and Block class, and hence reuse the same ID. This is also the reason to have the whole meta generated mess in the first place.

**Comment by repo-alt** [comment]
Indeed, forgot about that

**Comment by D-Cysteine** [comment]
Thanks for the help! I'll see if I can get this thing safely deleted, then.

One more question: where is the block inventory saved? It doesn't look like the NBT code saves the inventory, so is it saved somewhere else? I know that both Super Buffers subclass `IInventory`, so maybe it's handled by that? Trying to see if there's a way to guard against contents being lost, though it might not be doable.

**Comment by botn365** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/299f679f82ca60701d9d183b674d79b767270eb0/src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntity.java#L62
iirc you could overide this method and make it return the normal buffer instead of the threaded one

**Comment by repo-alt** [comment]
Super buffers probably use common MetaTileEntity inventory, just like Quantum Chests, etc.

**Comment by D-Cysteine** [comment]
Thanks again for the help! I wasn't able to get automatic metadata ID updating to work, but I got something working, at least. Sent a PR; closing this so discussion can move to the PR.
 * https://github.com/GTNewHorizons/GTPP/pull/18
