### ISSUE TITLE
Remove Extracells Fluid Storage Components from LootBag LootTable

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#8325]
#### Which modpack version are you using?
Any
#
#### If in multiplayer; On which server does this happen? 
Any
#
#### What did you try to do?
Opened some AE2 Lootbags. I got extracells fluid storage components. 
#
#### What do you suggest instead/what changes do you propose?
As extracells fluid storage is/can be very laggy and you arent supposed to use it on servers, i recommend to remove them from the lootbags loottable, to not give players more reasons to use extracells fluid storage.
#
#### What is your GTNH Discord username?
TrainerSnow#5086

**Comment by miozune** [comment]
Fixed by #10123
