### ISSUE TITLE
RFC: Mirrors are overnerfed

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#8326]
#### Which modpack version are you using?
2.1.1.1
#
Magical mirror is currently gated behind enderioum, which means TS coils, so, kind of, late EV. At that stage it is easier to wait until trasceivers which are much superior. (Mirrors require ordo vis source nearby to have any throughput)
#
To make them less useless, perhaps replace enderium plates in the recipe with enderium base? It still requires some platinum, so not cheap at late HV. Or some early EV alloy? Maybe even tungstensteel, there is quite some gap between first TS ingot and TS coils

**Comment by monroth** [comment]
Agree
It is the most useless transdimensional item transport already - without special setup with energised ordo node it has low speed and it voides items
There is no way you would use them unless there is literally no other way
No reason to not give this ability at HV

**Comment by leagris** [comment]
Remember not to use them in Galacticraft dimension or expect memory leak and run-away mob spawns in GT Planets chunks where a mirror is placed.

**Comment by repo-alt** [comment]
> Remember not to use them in Galacticraft dimension or expect memory leak and run-away mob spawns in GC Planets chunks where a mirror is placed.

Doesn't that also affect any chunkloader?
