### ISSUE TITLE
Storage bus can't push newly filtered items to infinity chest

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8327]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
Filtering items that need to be inserted into an infinity chest with more than 1 storage bus
Expected any new item going into the AE network to end up into the infinity chest
#
#### What happened instead? (Attach screenshots if needed)
Items that are already filtered are working fine, but every time I add a new item I have to break and replace the infinity chest to make it recognize and accept it.

How I tested this:
I disconnected my drives and left only the infinity chest connected as storage
When inserting by hand into my ME system from a terminal the newly filtered item it refused it like the storage was full, but there was space into the infinity chest.
I then broke the infinity chest and placed it back, after that I was able to insert the item into the ME system from a terminal

My setup:
![javaw_AShbbWmPJp](https://user-images.githubusercontent.com/17811922/127780433-ca635ccb-e7af-452b-a856-95a8ddff0b0e.png)

Number of filtered items in the storage buses is 190 across 4 of them, chest always has free spaces

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by repo-alt** [comment]
This happens only with infinity chest? weird, what's so special about it

**Comment by Sphyix** [comment]
I don't know to be honest, it happened with the infinity chest cause it's the one that makes the most sense to filter like this.
The thing could be multiple storage buses on a single chest? I didn't test anything else but i can try with some other storages
