### ISSUE TITLE
Void Miner not working on Ross128b

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#8333]
#### Which modpack version are you using?
2.1.1.1a with newest Bartworks from jenkins
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Placed void miner on ross128b expecting it to mine.
#
#### What happened instead? (Attach screenshots if needed)
It didn't mine anything although it consumed both energy and fluid.
#
#### What do you suggest instead/what changes do you propose?
Fix
#
#### What is your GTNH Discord username?
Pxx500#6984

**Comment by boubou19** [comment]
looks like the drops aren't calculated, like in the tf

**Comment by Pxx500** [comment]
Shouldn't it be fixed with twilight?
It was mentioned in the issue about twilight

**Comment by boubou19** [comment]
twilight is fixed, but looks like a similar fix needs to be applied on ross128b. Can you tell us if ross128ba is having issues as well?

**Comment by Pxx500** [comment]
Ross128ba doesn't work as well

**Comment by GTNH-Afx237v7** [comment]
See also: #7738 
Glease mentioned having a fix for this
