### ISSUE TITLE
OC microcchips recipe does not accept all kinds of circuits 

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#8334]
#### Which modpack version are you using?
2.1.0.0
#

T1 chip and T3 chip accept only fixed ccircuit (Workstation)
and not accept Quantenprocessor
But T2 can acept all kinds of HV ciruit

If i want to make some T3 chips, I have to make workstation from MV.
Is it a bug?
if it isn't .why HV circuit all accepted?

**Comment by botn365** [comment]
i wonder how many times we already have had a issue for this

**Comment by Prometheus0000** [comment]
Duplicate, use search.
