### ISSUE TITLE
Solar goggles of revealing not having radiation protection 

### ISSUE THREAD

**Issue by King65868** [GTNewHorizons/GT-New-Horizons-Modpack#8335]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Jimmy’s community server
#
#### What did you try to do, and what did you expect to happen?
I put on solar goggles of revealing, and picked up both GT plutonium and IC2 plutonium. I expected I would get no bad effects. 
#
#### What happened instead? (Attach screenshots if needed)
I got radiation effects. 
#
#### What do you suggest instead/what changes do you propose?
If solar googles of revealing gave radiation protection like the quantum goggles of revealing it is made from that would be great. 
#
#### What is your GTNH Discord username?
King#4098

**Comment by Prometheus0000** [comment]
Why _should_ they have hazmat protection? They're goggles.

**Comment by King65868** [comment]
Why does the quantum goggles have radiation protection then?

**Comment by Prometheus0000** [comment]
Probably because they're made from the quantum armor? You should ask for it to be removed from it then.

**Comment by King65868** [comment]
This is also made from the armor, it is crafted using the quantum goggles of revealing. So I am confused why they shouldn’t get radiation protection.

**Comment by Glease** [comment]
All armor made from something with hazmat capability should have hazmat capability as well. Otherwise it's a strict downgrade considering how useful hazmat capabillity is.

**Comment by Sphyix** [comment]
Hazmat is already on the goggles in the new version.
It's already added to nano, quantum and solar goggles
here https://github.com/GTNewHorizons/GT5-Unofficial/pull/606 to check the list of the armor pieces

**Comment by King65868** [comment]
Ah, didn’t see that. Thanks for telling me
