### ISSUE TITLE
[RFC] neuro processing unit is overnerfed

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#8336]
#### Which modpack version are you using?

# 2.1.1.1a

#### What do you suggest instead/what changes do you propose?

this is NPU recipe, which needs HSSS bolt and Fluxed Electrum casing
![image](https://user-images.githubusercontent.com/60341015/127960310-39138446-db37-4cfa-b9ff-caa0d47c8a05.png)

this is BPU recipe, which needs Tungstensteel bolt and Tungsten casing
![image](https://user-images.githubusercontent.com/60341015/127961123-2cbe7b79-984d-48f1-9c8b-1f5dd09bec1b.png)

Both HSSS and Fluxed Electrum are higher tier material than Tungstensteel and Tungsten, but NPU is lower tier material than BPU.

so, i think Naquadah casing and Stainless Steel bolt should be more reasonable for NPU.

this is the origin nerf:

https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/7ebeb95e1533f2abccd7f90a351bb37104bde1a3#diff-d6259082b962b8eb1100fcd56bc3f38d6b97c1bd1ea62b356f68fc072ac2bb71

#### What is your GTNH Discord username?

GlodBlock

**Comment by botn365** [comment]
iirc the fluxed electrum and hss-s bolts where always a thing
but the materials for the bio where just picked wrong

**Comment by GlodBlock** [comment]
so do you mean that BPU needs nerfing?

**Comment by GTNH-Colen** [comment]
Switch the material, not the quantity around? That should resolve it.

**Comment by alphaNOVAircraft** [comment]
nerf the bio ones, nano is fine 
not like the casings would be the expensive part of it...

**Comment by Sphyix** [comment]
don't add more ebf time to the bio, it's already annoying enough for the amount of uv stuff and neutronium needed

**Comment by alphaNOVAircraft** [comment]
bio is end of the line, it should be expensive, it already got buffed a few patches before as well. 
Even 10 nt ingots would really impact the price (but that wouldnt be the right material, i suggest smth like awdr, osmium)

**Comment by miozune** [comment]
I think this should be addressed properly
