### ISSUE TITLE
Ultimate Capacitor (UHV) wrong unpackager recipe

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8337]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What do you suggest instead/what changes do you propose?
Change Unpackager recipe of Ultimate Capacitor (UHV) to give an Ultimate Battery (UMV) to match the other lapotronic capacitors recipe
Right now the recipe gives back 1 Ultimate Battery (UV) but the craft of the ultimate capacitor is asking for 8 of them

LuV to UV lapotronic capacitors need the previous tier battery to craft (ZPM to UV need 8 of the previous tier) and the Unpackager recipe gives back 1 battery of the lapotronic capacitor tier
So example: UV lapotronic capacitor needs 8 ZPM batteries, unpackager gives back 1 UV battery

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by Prometheus0000** [comment]
If we did that, then you could make it out of the UV battery and get back the UHV one.

**Comment by Sphyix** [comment]
The umv ultimate battery is made with 8 uv ultimate batteries already

**Comment by Dream-Master** [comment]
Are this recipe reverse autogenerated ones or manual added in the code ?

**Comment by Sphyix** [comment]
Didn't check..
I can try to take a look later, I'm not home
