### ISSUE TITLE
[TecTech] _ Laser Source hatches losing stored energy

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#8338]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Build a Lapotronic Super Capacitor using 9x IV capacitors, Osmium Glass (UV-tier), an LuV Energy hatch as input (fed by LuV water kinetic) and a 1,048,576 Amp IV laser source hatch
Active it with soft mallet and expect the internal buffer of the laser source hatch to fill gradually.
#
#### What happened instead? (Attach screenshots if needed)
The internal buffer begins to fill, however shortly thereafter the buffer drops; the energy is simply lost, as it is also not transferred to the LSC.
Tested also with the other IV laser source hatches, and the behaviour is similar. Observed that the smaller the Amp capacity, the slower the stored energy drops, e.g. a 1,024 Amp hatch fills completely before the internal buffer of the LSC starts to fill. However at this point in time, the buffer of the laser hatch begins to decrease.
#
#### What do you suggest instead/what changes do you propose?
Not sure if this is intended?  I would assume that the laser hatches were to store the energy until it can be transferred to a laser target hatch.
This might be related: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7274 - however I don't understand the explanation by Tecnus.
Or the loss calculation of the LSC is incorrect when using laser hatches? When the LSC is deactivated, the hatches lose energy as well.
#
#### What is your GTNH Discord username?
Afx237v7

**Comment by GTNH-Afx237v7** [comment]
I also tried different combinations of capacitor tiers and laser hatches, the result is however the same. All energy that is input into the LSC is directly transferred to the laser source hatch where it dissipates into nothing. Gut feeling tells me it has to do with the loss calculation of the hatches, as the bigger the hatches are, the more you can see the stored energy vanish.

**Comment by Pnc6lx** [comment]
i find same thing a few mouths ago, it loss the same A eu/t， means 1048576 A IV laser loose 0.5A UHV /t

**Comment by botn365** [comment]
looking at the code its not a bug
so while more amps is cheaper it is more loss

**Comment by GTNH-Afx237v7** [comment]
That was my assumption as well...

**Comment by botn365** [comment]
this is a loss seperate to LSC 
a loss closer to cable loss

**Comment by Prometheus0000** [comment]
So is it the TT code (laser source) or the KT code (LSC) doing this? Do all laser sources lose power over time?

**Comment by GTNH-Afx237v7** [comment]
I tested the TT IV laser ones (1,024 to 1,048,576) and they all lost power, albeit at different rates).

**Comment by Prometheus0000** [comment]
Did you test them in something that's not the LSC though?

**Comment by botn365** [comment]
https://github.com/GTNewHorizons/TecTech/blob/8a3e36cadb3519860ebd3258d3470852936fd0a4/src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_DynamoTunnel.java#L124
no need to test when it in the code
