### ISSUE TITLE
SFM block gate behaves unexpectedly with AE blocks

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#8339]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
My friend's server (can provide IP on request) and in singleplayer

#
#### What did you try to do, and what did you expect to happen?
I tried to use SFM to disconnect part of AE system from it's controller on a condition. I wanted SFM block gate to break dense cables and store them in some inventory, and later to be able to place it back.

#
#### What happened instead? (Attach screenshots if needed)
SFM was not able to break cables. It was able to break AE2 energy cells, but placing it back with SFM causes server to crash.
Openblocks and projectred block breakers\placers don't have any of these problems, but they are a lot harder to use in any complicated automation.

#
#### What do you suggest instead/what changes do you propose?
allow breaking of these blocks by SFM
or at least fix server crash from placing by SFM

#
#### What is your GTNH Discord username?
monroth#4236

**Comment by repo-alt** [comment]
No way I would support that, wtf.

**Comment by yukieiji** [comment]
Why not use a toggle bus?

**Comment by monroth** [comment]
>No way I would support that, wtf.
what do you mean?

**Comment by Prometheus0000** [comment]
But you don't want anything done?

**Comment by repo-alt** [comment]
I mean, breaking and placing of the AE components by the fake player is not supported, and I don't feel like implementing that support is a good idea.

**Comment by monroth** [comment]
> I mean, breaking and placing of the AE components by the fake player is not supported, and I don't feel like implementing that support is a good idea.

1)openblock and projectred place it just fine, so it is not impossible, it is just a little bit more annoying

2)even if you don't want it to work, crashing server is probably not a good way to prevent it

**Comment by repo-alt** [comment]
Well, actually, I don't object to someone else fixing that issue.
