### ISSUE TITLE
Remote interface with AE2 upgrade disconnects on chunk unload

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#8340]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
My friend's server (can provide IP on request) and in singleplayer

#
#### What did you try to do, and what did you expect to happen?
I tried to use Remote IO to build spread out base (so it won't hit fps that much). I planned to use remote interfaces looking on ME controller to be able to connect different buildings to same system.

#
#### What happened instead? (Attach screenshots if needed)
If for any reason ME controller that is in the target of remote interface is not avaible (destroyed, chunk unloaded, etc), then any cables that connects to Remote IO disconnects themselves. But if interface is avaible again, cables DO NOT connect back. 
It means that if for instance if you restart server, and for any reason chunk with remote interface loads before chunk with it's targeted ME controller, then all cables that were connected to remote interface disconnects from it. You need to break them and place them back. That leads to some rather strange automations, [and they have other bugs and problems ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8339)

#
#### What do you suggest instead/what changes do you propose?
allow automatic reconnecting of AE cables to remote interfaces with AE2 extension

#
#### What is your GTNH Discord username?
monroth#4236

**Comment by repo-alt** [comment]
I think you are supposed to use quantum bridges to connect really remote parts.

**Comment by Prometheus0000** [comment]
So no change needed?

**Comment by monroth** [comment]
> I think you are supposed to use quantum bridges to connect really remote parts.

i know about this option, and it is inferiour even to strange buggy automations mentioned in linked ticket

**Comment by repo-alt** [comment]
mhm, "inferior", as in, it takes power

**Comment by monroth** [comment]
> mhm, "inferior", as in, it takes power

it eats an unreasonable amount of power, ofc
but it is not main problem, there are ways to produce unreasonable amount of power
like power every quantum gate with triple compressed ignis solar placed in hell
i'd say production of remote interface with AE2 upgrade has similar difficulty on crafting

even with power consumption remote interfaces would be a lot more convent than quantum gates
and designs with with remote interfaces are a lot easier to extend that designs on quantum gates

**Comment by monroth** [comment]
I understand that in that modpack you have to pay with blood to have any conveniencies; this is not the right mindset to balance things, but ok. If convenienve of Remote interfaces are too big (they are not to big at the moment when you are able to craft them), make them more pricey (although they are already very pricey). Just please make them work normally.

**Comment by repo-alt** [comment]
Idk, for me Remote IO is something like Thermal expansion. It is indeed very convenient. As for balance dicisions, it is up to Dream.

**Comment by boubou19** [comment]
Remote IO has also a non neglictible amount of issues (mainly crashes), and at one point it was even considered to remove the mod from the pack.
