### ISSUE TITLE
Nuclear reactor does not output EU from all it's blocks

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#8341]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
My friend's server (can provide IP on request) and in singleplayer

#
#### What did you try to do, and what did you expect to happen?
Tried to get sweet EU from two-block nuclear reactor (main block one chamber) and automate it a bit

#
#### What happened instead? (Attach screenshots if needed)
Only was able to do it on fourth attempt
1)placed it horisontally, conduits\hoppers did not want to take depleted rods from main block (only from chamber)
2)flipped it over, cables did not want to take EU from main block (only from chamber)
3)decided that it just can't be automated by intefacing main block; placed reactor vertically, and cables were not able to take EU from chamber (only from main block)
here's screen of this 
![image](https://user-images.githubusercontent.com/28282020/128023519-6fd71b5e-9c02-482e-b1b2-60c877dcfc28.png)
you can see that reactor on the right half of picture fuel both lamps, but similar reactor on left side only fuels lower lamp
4)moved last reactor just one block diagonally, and everything mirracliously started to work

#
#### What do you suggest instead/what changes do you propose?
Make so nuclear reactor can always output eu and\or items from any of it's sides

#
#### What is your GTNH Discord username?
monroth#4236

**Comment by Prometheus0000** [comment]
So no change needed?

**Comment by monroth** [comment]
> So no change needed?

I may be worded it poorly
when i said "everything started to work" i meant that reactor in last position worked
reactor on 3-rd position still does not work (or at least does not emit eu from upper block)

i don't see any pattern when reactor does or does not emit eu from one of it's blocks
(or does or does not allow piping items from and to it)
so don't have any ideas about why that can happen

**Comment by repo-alt** [comment]
You mean - if you connect a cable to the main block of a 2 chamber reactor, it does not output EU (at least sometimes)?

**Comment by Prometheus0000** [comment]
fixing = ?
Emit from multiple sides? Not emitting from multiple sides?

**Comment by monroth** [comment]
1)on first (horisontal) reactor, i put hopper under main block, and hopper did nothing
but when i put hopper under chamber, it worked as expected

2)on second and third reactor, when i connect cable to one block (main block in 2nd, chamber in 3rd) it does not output eu; but if i connect cable to another block, it does output eu. This behaviour does not depend on wether there are another cables  or not - i have two cables on screenshot, but even if i destroy lower cable, upper cable still does not provide power.

**Comment by boubou19** [comment]
the code of the ic² nuclear reactor is kinda buggy and allowed in the past both item and energy dupes. If this is going to be reworked, then we must make sure those dupes aren't back in the game after the changes.

**Comment by mitchej123** [comment]
It's using the ic2 enet.  Smack the wires with a scanner and see if it says "joined ic2 enet". If so it's an enet problem most likely. If not, needs more investigation m
