### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by omegaelit** [GTNewHorizons/GT-New-Horizons-Modpack#8342]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
local multiplayer server
#
#### What did you try to do, and what did you expect to happen?
Clicked on blocks from lootgames game
#
#### What happened instead? (Attach screenshots if needed)
Crash: 
https://pastebin.com/HSR1fkWT
#
#### What is your GTNH Discord username?
ὦelit#7045

**Comment by TimeConqueror** [comment]
@omegaelit LootGames were completely rewritten, try new version (also contains Minesweeper, yay): https://www.curseforge.com/minecraft/mc-mods/loot-games/files/3412179
