### ISSUE TITLE
[Suggestion] some buffs to lategame armor options

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#8343]
#### Which modpack version are you using?
2.1.1.0

#
#### What changes do you propose?

GTNH is a modpack with a lot of mods with a lot of armor options. However, many options have an unnecesary drawbacks, especially taking in account prerequisites to craft them.

Some suggestion aiming to increase amount of relevant choices of armors:
#
1)Ender IO. 
Darksteel armor is great, but it's upgrades from endsteel and stellar alloy are barely better. Almost any lategame set has better defences than stellar alloy armor (even with upgrades), and it's not that it has that much utility for that. Yes, it can have apiarist upgrade, but it does not provide hazmat protection, and in this pack it is generally more useful.

#
2)Hazmat protection and apiarist protection.
More armors should have hazmat protection. Lategame armors that has hazmat protection should have apiarist protection too - if your armor is cool enough to protect you from ten stacks of depleted plutionium rods, how can they not protect you from some bees?

I suggest adding hazmat (and therefore apiarist) protection to those items and sets:

a)KAMI set from thaumic tinkerer - it is one of the two most lategame armor sets from thaumcraft addons; another one is primordial armor set, and it has hazmat protection already. Even downgrade of primordial set (shadow fortress armor) has hazmat protection, and it is easier to craft than KAMI set. Not to mention that you need to do a filthy amount of TC research just to see recepie for them.

b)Stellar (and may be even endsteel) armor - as i said previously, this armor deserve more love

c)Voidmetal goggles of revealing - they are the most advanced goggles from shadow\primordial branch of thaumcraft; they give the most vis discount out of all helmets before avaritia. They are probably not the hardest helmet to craft, but definitely not too easy and definitely harder than nano helmet.

d)Probably some bloodmagic armor, but i'm not familiar with blood alchemy and don't know how hard it is, so can't provide with balanced input

If there are ways to add apiarist\hazmat enchantment to game, I suggest to do so - no armor has it's main individuality about this kind of protection.

#
3)Buff primordial boots
Main utility of boots are speed, jump heigh and highstep. In this modpack primordial boots are direct upgrade of boots of voidwalker. They have some advantages, but their main utility is heavily compromised.
a)Jump height - 3.5 blocks of voidwalker vs 1 block of primordial
b)Speed boost - voidwalker is ~nano boots of traveller vs primordial is ~electric boots of traveller.
c)Fly speed boost - voidwalker has it, primordial boots does not.
d)Voidwalker sash - if you wear voidwalker's sash, it further boosts all bonuses of voidwalker's boots (speed up to ~quantum boots of traveller, flight speed to >avaritia set, jump height to 5 blocks); so it is a nice togglable way to increase speed when you need it in unreasonable amounts. But sadly voidwalker's sash does not work at all with primordial boots.

Therefore i suggest to buff mobility of primordial boots, preferably in some togglable way - otherwise they are mostly a downgrade to boots of voidwalker
#
4)Make quantum armor enchantable
ATM there is no easy way to enchant quantum (and nano) armor. Cinobi said to me that blood magic can do it, but i'm not good enough in blood magic to test it, and no other way worked. 
While quantum armor is good even by itself - good protection, mobility, thaumic sight\night vision, hazmat protection - there are some ehcnantments that are not covered by innate properties of quantum armor. For instances, you can't enchant them with soulbind, which is must for someone who does anything dangerous - if you managed to die with quantum armor on, you'll definitely die if you try to get it from your grave. If blood magic indeed can enchant quantum armor, then it is just strange that one ways to enchant thing works while others don't.
#
#### What is your GTNH Discord username?
monroth#4236

**Comment by Prometheus0000** [comment]
? Lategame is infinity/draconic armor? These are all ridiculously before that.

**Comment by monroth** [comment]
> ? Lategame is infinity/draconic armor? These are all ridiculously before that.
they are endgame armors )
IV\LuV is kinda lategame for me, and all these mentioned sets (primordial\kami\quantum\stellar) can't be crafted before that

btw, draconic armor does not have hazmat protection too, so more power to draconic armor too!

**Comment by boubou19** [comment]
draconic armor does have the hazmat protection in devpack.

**Comment by Sphyix** [comment]
A lot of armors now have hazmat protection
here https://github.com/GTNewHorizons/GT5-Unofficial/pull/606 to check the list of the armor pieces
Not sure about apiarist protection, some armors like draconic don't really need it, they negate all damage already, but I didn't play enough with bees to see how other armors behave
I agree that the Ender IO armors are really forgotten in this pack, maybe they just don't give enough compared to other armors considering their tier?

**Comment by alphaNOVAircraft** [comment]
> > ? Lategame is infinity/draconic armor? These are all ridiculously before that.
> 
> they are endgame armors )
> IV\LuV is kinda lategame for me, and all these mentioned sets (primordial\kami\quantum\stellar) can't be crafted before that
> 
> btw, draconic armor does not have hazmat protection too, so more power to draconic armor too!

Lol IV/LuV is so fckn far from lategame xD 

Quantum is already extremly powerful for only requiring ZPM. 
Some of the thaumcraft stuff might benefit from some buffs, hard to tell for me, never used them. 

Hazmat should be part of all armor past LuV imo, (you are forced to handle radiocative stuff, and chaning armor to do so is kinda annyoing)

**Comment by monroth** [comment]
> here [GTNewHorizons/GT5-Unofficial#606](https://github.com/GTNewHorizons/GT5-Unofficial/pull/606) to check the list of the armor pieces

yeah, i already saw that, and this was part of why i wrote this ticket. I was surprised when after update my primordial+voidwalker set suddenly got hazmat protection, and my friend's KAMI set did not, as it is at ~ as it is i think even later and harder to craft and it is a lot more about "utility" vs "just defense in combat" of my set. If you don't own draconic\infinity armor, and want four basic things from armor - 
a)hazmat protection
b)decent speed
c)decent defence
d)ability to add soulbound

then you are struck with "boots of the voidwalker+primordial head\chest\legs"

and it does not has any intristic night vision/thaumic sight, you have to enchant it on
and if you want hazmat protection AND flight or apiarist protection - no such luck at all, these three options (hazmat, apiarist, flight) are mutually exclusive

>Quantum is already extremly powerful for only requiring ZPM.

I would agree if there was a way to add soulbound to it. Without soulbound you don't own it, you're just borrow it from your grave. And for me it is enough to not use it.

>I agree that the Ender IO armors are really forgotten in this pack, maybe they just don't give enough compared to other armors considering their tier?

I think darksteel armor is in a good place - probably best armor at mv-early hv age, especially if you're not using thaumcraft. The sad thing is that it's "upgrades" are almost same.

**Comment by Sphyix** [comment]
kami set should definitely have hazmat..
it's the thaumic tinkerer robes of the stratoshpere, cowl of the abyssal depths etc.. set right?

**Comment by monroth** [comment]
> kami set should definitely have hazmat..
> it's the thaumic tinkerer robes of the stratoshpere, cowl of the abyssal depths etc.. set right?

yeah
i'm not talking about basic ichorium set

**Comment by Sphyix** [comment]
kami armor is working as expected for me, 2.1.1.1a
![javaw_8RqQe8qX8H](https://user-images.githubusercontent.com/17811922/128335262-94dd33f4-481a-4a9a-85bb-37a56e5c5ea1.png)
for ic2 items and fuel rods, they give you poison in 2.1.1.1a, it's already fixed in dev
