### ISSUE TITLE
[NEI] click on Tico Fluid not redirect you back to smeltery recipe

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#8344]
#### Which modpack version are you using?

2.1.1.1-dev
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

I open up Nei and click on Alumite recipe. I cant enter the smelter recipe like before
#### What happened instead? (Attach screenshots if needed)

Open up the smelter recipe part when click on a fluid
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
:)

![image](https://user-images.githubusercontent.com/2970688/128051465-1e2aad6d-4e1b-4ca8-8aa8-3bc7c7c27a32.png)
![image](https://user-images.githubusercontent.com/2970688/128051489-4528f916-2d8e-457f-ae3d-4d4d491766e9.png)

**Comment by DarkYuan** [comment]
I figured this out today actually. The link to the fluid entry is actually down where it would originally be in a normal view of NEI
![image](https://user-images.githubusercontent.com/3029695/134988710-514db605-e45a-4f3d-9a12-07124ec0f3df.png)
