### ISSUE TITLE
Increase computation requirements on recipes (overall nerf)

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#8345]
#### Which modpack version are you using?
2.1.0.0
#
Currently there is no real need for any powerful research station, even stargate components can be unlocked with ez. 

I suggest generally increasing the required computation and computation/s for nearly all recipes (especially UEV stuff etc). Researching should be expensive and also draw a decent amount of energy, currently you can build a 2 long quantum computer and its enough for nearly everything, i would prefere if you would have to upgrade and reward player for building more then the comp/s requirement in computers. 

#### What is your GTNH Discord username?
alphaNOVA

**Comment by Dream-Master** [comment]
@alphaNOVAircraft make a list for me with suggested computations for the recipes. Thanks

**Comment by alphaNOVAircraft** [comment]
will do, wanted to hear a general opinion on this topic first.

**Comment by Sphyix** [comment]
I approve for the fact of rewarding the player for more comp/s than what's is needed, maybe some kind of overclock of the research to speed it up? (perfect overclock in this case, or the amps needed in some cases are just nosense)

All the UHV and UEV definitely need a nerf, so circuits, components and hatches
![javaw_aprgWwdH2I](https://user-images.githubusercontent.com/17811922/128082391-c6ccfbf8-8f8a-42bc-b258-067e15ce3fde.png)
![javaw_J0wp2ivllO](https://user-images.githubusercontent.com/17811922/128082395-fbefc2d6-766d-465e-9afb-d8814864d2c9.png)

Not everything needs it, like, how can you even think about nerfing this lol
![javaw_Aie6x7CQ0D](https://user-images.githubusercontent.com/17811922/128082429-d24c1cb9-eb1f-477d-b7f8-63412eb85638.png)

Some other changes, like the auto-taping maintenance requires a crazy amount of time compared to the amps actually needed, so a change of like 1/2 or 1/4 of the time and 2x or 4x on the amps needed would be nice.
Asking for a bit more comp/s can be done aswell
![javaw_dMfKCfC1rW](https://user-images.githubusercontent.com/17811922/128082612-c47f4acc-36b0-44e5-8cd9-991b497eed13.png)

Similar to auto-taping we have the void miners, vm3 takes 4,4 hours to research

**Comment by alphaNOVAircraft** [comment]
Imo the base time should be extremly high with only the required comp/s. The more you have the faster it will get. e.g. i researched the vm3 way under 10 min

**Comment by alphaNOVAircraft** [comment]
you already get rewarded for higher then required computation, its just not really worth it cz the general requiremnts are extremly low

**Comment by Prometheus0000** [comment]
I agree with this, it would be nice if people were actually _required_ to chain the quantum computers, but right now you don't need to even remotely get close to using a single one.

**Comment by boubou19** [comment]
also, could be nice to nerf OC components for the computation time, they are far better than last circuit tiers.
https://github.com/GTNewHorizons/TecTech/blob/5fc2d0d29543776ae0ae35898d8b47896b770911/src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_Rack.java#L344

**Comment by alphaNOVAircraft** [comment]
yeah comp is a bit wierd, highest you can get is with crystals xD

**Comment by Prometheus0000** [comment]
Did those actually work? I think I tested them and they didn't?

**Comment by boubou19** [comment]
they weren't working until this commit, which fixed the internal lookup for oc components: https://github.com/GTNewHorizons/TecTech/commit/34b58d35f3c70a7ebc3bce4a81a6055147fd21ab#diff-476bbbccb4110372438dec25d30203bf4b303debdfa231ebd294475474efcd62

**Comment by alphaNOVAircraft** [comment]
https://docs.google.com/spreadsheets/d/1UW6Bzb8TtYH9_C0_aUst7-LMhWgosqC4fAQtveAoJC4/edit?usp=sharing

Here are my suggestions.
The hardest recipe would now require 5 max size computers with 90 comp per hatch. That is totally doable
The energy usage (max) is way higher then before, this will reward players if they build more then the minimum required computation.

**Comment by Sphyix** [comment]
I don't understand the reason for the nerf with the values that you posted alphanova
Wasn't it supposed to force ppl into making more quantum computers and chain them?
I only see a general nerf making it more annoying cause now it takes a lot more time (energy wise and time wise), without really forcing ppl into making more quantum computers except for a few recipes
All the recipes were changed into asking more power and more overall computation, but nearly none got changed to actually require more comp/sec.

Documentation on this stuff is basically none, so it's not obvious to many players that having more comp/sec equals less time, this really looks like just a time gate with the numbers you posted.

Another thing, I don't really like the nerf on the batteries.
If PSS gets removed, only the LSC will remain and those batteries are then really needed to be able to store power to do the researches. 
Gating them behind being able to produce that much power without storing it, with the current situation, means asking players to spam turbines to be able to do research, which is not fun either.

Overall I see this only as more annoying for the player without actually solving the initial issue.

**Comment by alphaNOVAircraft** [comment]
Increasing the min computation to a value that requires multiple quantum computers is hard cz at the beginning you cant even propperly supply a max size qc with power. 
I though about it quite some time and come the conclusion that increasing the power usage and computation requred (in total) will make ppl want to build more quantum computers instead of just paying the energy / waiting the time. 
Forcing ppl to build it cz minimum requirement would also be a option but i personally dont like it. 

Gating the Really Ultimate a bit higher was intentionally (but again personal reasoning). The really ultimate battery is one of the first true lategame goals, it provides infinit storage and IO so you should proove your energy gen is worthy imo. 
32Meu/t is for sure no trivial amout at the time you want to make a really ultimate battery but it is also far from imposible or requireing insane amount of additional spam (32Meu/t are not even 10 Turbines, not quite spam). 

Imo it solves the initial issue. Computation and research will be releveant and it will be smth to look out for when progressing instead of "hmm and now i am gonna throw a item in and wait 10 sec". 
I choose to push ppl towards bigger computer setups with energy / time inistead of simply telling them you NEED more. 

The computation behaviour could be explained in the quest. I dont think that shouldnt be the issue. 

Feel free to copy the sheet and suggest your own values.

**Comment by boubou19** [comment]
i thought time gates were a poor gating mecanism?

**Comment by Sphyix** [comment]
Yea I'll try to suggest my values
I approve all the uhv and uev nerfs, they are needed, even if the minimum comp/sec is pretty low and you can still research mostly all of them with a single qc

I still don't understand the need for that much time on batteries
Really ultimate battery is a lategame goal, ok, but it still takes like a week of crafting to be able to build it, I was running out of power when trying to make it on a 120 mil eu/t production, so I don't see the reason to ask for that much power to research it.
I understand you want to push people to build infrastructure to be able to get it, but forcing them in this case by just asking like 4096 min comp/sec and force them to build 3 qc without requiring hours or days of power is better.
It's still gonna take days or even weeks to actually craft it, so I don't see the reason to timegate it on the research aswell.

Same exact thing goes for the stargate components, do you think it's too easy to craft so you just timegate it on the power needed for the research some more? Or do you really want me to build 256 large plasma turbines to do the research?

**Comment by GTNH-Colen** [comment]
41 Trillion EU for nigh infinite storage is a small price to pay imo. Endgame goals should be better gated and this puts it more in line with what it should cost. If you are crafting that item, then these costs should be of no concern. The only value that seems rather insane is the quantum circuit but that has literally 0 uses so we can always rebalance it in future if needed. Until then it's just a meme item I suppose.

**Comment by alphaNOVAircraft** [comment]
> i thought time gates were a poor gating mecanism?

Yes but in this case i think it is decent, because unlinke normal recipes you can make it faster AND more efficient (by adding more computation) instead of normal overclocks that make it use way more energy. So it is rewarding to make it faster and not punishing like classic gt oc behaviour. 

>Really ultimate battery is a lategame goal, ok, but it still takes like a week of crafting to be able to build it, I was running out of power when trying to make it on a 120 mil eu/t production, so I don't see the reason to ask for that much power to research it.

If you build 3 qc it doesnt require hours of power...... thats the cool thing with the research station, you can make it faster and cheaper by adding more computation. With 3 qc (which isnt that much but would definitly be reasonable to have at that stage) it takes slightly above 10 minutes. If you cant handle that you shouldnt build a really ultimate battery. 

>but forcing them in this case by just asking like 4096 min comp/sec and force them to build 3 qc without requiring hours or days of power is better.

All i am doing here is ask them to build at least 3 qc to make it at least a bit efficient, i mean if it makes you happy i can increse the min required. I though ppl would figgure out themselfe that using more then the min required is a good idea. But if it pleases you feel free to increase it in you suggestion. The total value isnt overkill imo (its still quite humane tbh)

>Same exact thing goes for the stargate components, do you think it's too easy to craft so you just timegate it on the power needed for the research some more? Or do you really want me to build 256 large plasma turbines to do the research?

When you go for a stargate those numbers are still the least of your problems...... (and stargate is supposed to be a meme / expensve af)

**Comment by alphaNOVAircraft** [comment]
The reason i didnt just increase the base min requirement is that you have to put it to insane numbers to be truely noticable. Then again it would become a machine you would run for 10 seconds. 
I really enjoy the way it works with less time for more computation as a reward instead of a straight up requiremnt. So i suggest values encouraging to build more but not forcing insane numbers that then make every recipe be 5 sec..
