### ISSUE TITLE
Void Miner doesn't work in Everglades

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#8347]
#### Which modpack version are you using?
2.1.1.1a
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I placed void miner to get ores just like I always do.
#
#### What happened instead? (Attach screenshots if needed)
Void Miner didn't mine anything
#
#### What do you suggest instead/what changes do you propose?
Fix
#
#### What is your GTNH Discord username?
Pxx500#6984

**Comment by Prometheus0000** [comment]
We don't care about this dim, which is due for removal with the rest of GT++. Also, I don't think the normal miners work there either, but I could be wrong.

**Comment by GTNH-Afx237v7** [comment]
Not a bug as GT++ dims are not in code. Only OW, End, Nether, Galacticraft, Galaxyspace, Ross128b, Ross128ba and just recently Twilight Forest.

**Comment by Prometheus0000** [comment]
Major version after next hopefully. There's no ETA. If someone wants to fix it, that's fine. But they don't even use GT oregen.

**Comment by Pxx500** [comment]
That's exactly why void miner is the best for this job since it doesn't need spawned ores.

**Comment by Alastors** [comment]
> That's exactly why void miner is the best for this job since it doesn't need spawned ores.

no one's gonna fix it though, because there really isn't a point to do so tho...

**Comment by Pxx500** [comment]
Understandable

**Comment by Pnc6lx** [comment]
> We don't care about this dim, which is due for removal with the rest of GT++. Also, I don't think the normal miners work there either, but I could be wrong.

gt++ ore was used to unobtainable by normal miner, and it was fix long time ago

**Comment by boubou19** [comment]
after inspecting the code of the void miner base class, this seems impossible without a drastic rework of the dropmap:
the VM expects the ores to be either from BW or from GT. Also, GT++ has a block/ore, where BW/GT have a block/meta. So we would need to edit an hardcoded list of ores each time the worldgen of GT++ dims are changed.
