### ISSUE TITLE
Render Issue with TC Node Tracker and Adventure Backpacks Tank render

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8349]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
its self explanitory by the title
#
#### What do you suggest instead/what changes do you propose?
when the tanks are not rendering
![image](https://user-images.githubusercontent.com/38770780/128125945-b79637e0-7adf-4093-b17d-88a1d8ae72b4.png)

when its present
![image](https://user-images.githubusercontent.com/38770780/128126031-accb22fd-f56a-46a5-a04b-956fe820682c.png)

A fix for this issue would be nice
#

**Comment by boubou19** [comment]
try to reproduce it in a not modified version of the pack.

**Comment by SteamDoge9000** [comment]
... ah shit, forgot this was not part of the pack, let me try to reproduce with TC node tracker only

**Comment by SteamDoge9000** [comment]
Successfully re-created with a fresh non-tampered instance of GTNH

![image](https://user-images.githubusercontent.com/38770780/128198658-f8e7a298-ab98-4f0b-b080-27d94ae507dc.png)

**Comment by SteamDoge9000** [comment]
Steps to Reproduce
1: Grab the following items; a adventure backpack, a node (Creative), Goggles or Revealing, Thaumomiter
2: Put goggles on
3: Place and scan node
4: select the node form the TC Node Tracking Menu
5: take note of the arrow
6: Put on the adventure backpack 
7: Visual bug with the "node compass" render surfaces

**Comment by SteamDoge9000** [comment]
Small side issue: It also seems that the fluid cells fictionality is not present for adventure backpack fluid manipulation; just thought I should add this since this is a bug report. XP
