### ISSUE TITLE
HydroEnergy crash in pre init stage (optifine)

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8353]
#### Which modpack version are you using?
dev 2111a
#

I tried to update to the latest dev but the pack will not load.
After a clean reinstall, i removed fastcraft and added optifine and it crashed in Pre initialization (keeping fastcraft makes no difference)
More info in the log 
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6932287/fml-client-latest.log)

Never had problem before, i played lot of versions with optifine.

OptiFine_1.7.10_HD_U_E7
#
#### What is your GTNH Discord username?
szajkop # 0522

**Comment by Prometheus0000** [comment]
There's no support for optifine. Remove optifine and see if it works.

**Comment by Szajkop** [comment]
without optifine it loads just fine. but the fps is crap
my point is that it was working before and with the current devpack it does not

**Comment by Dream-Master** [comment]
> without optifine it loads just fine. but the fps is crap
> my point is that it was working before and with the current devpack it does not

maybe change fastcraft not sure what version is shipped. You need fastcraft 1.2.5

**Comment by Prometheus0000** [comment]
_Unsupported_. If you can find which change caused it, _maybe_ someone will feel like fixing it.

**Comment by Szajkop** [comment]
Its shipped with fastcraft-1.25
After a few reloads and testing i found out that hydroenergy-0.1.1.jar is causing the error, When i removed it the pack loaded just fine with optifine installed

**Comment by Glease** [comment]
Good catch. I can see hydroenergy is indeed hooking into that problematic class.

@SinTh0r4s I suggest you to rediect the RenderGlobal#renderEntities call to your own callhook instead to minimize the possibility of locals and stacks problem, i.e. replace the INVOKEVIRTUAL with a INVOKESTATIC to a method like this:

```java
public static void renderEntities(RenderGlobal thiz, EntityLivingBase p1, ICamera p2, float p3) {
	thiz.renderEntities(thiz, p1, p2, p3);
	HETessalator.render(p2);
}
```

**Comment by Glease** [comment]
I suppose this doesn't crash any more.
