### ISSUE TITLE
Add More Kitchen Tile Options to Cooking for Blockheads

### ISSUE THREAD

**Issue by General-Ike** [GTNewHorizons/GT-New-Horizons-Modpack#8354]
#### Which modpack version are you using?
2.1.1.0

#
#### What do you suggest instead/what changes do you propose?
Being forced to use a single black/white texture tile to connect everything in the kitchen can lead to less diverse appearances (especially the walls, the floor looks pretty good as it is). I suggest adding in at least one block, if not a few others, that functions identically the the existing kitchen tiles, but has a different texture. You can even just pull an existing texture like regular quartz block. Anything to keep my walls from being a checkerboard mess.

#
#### What is your GTNH Discord username?
Commander Crankshaft

**Comment by Prometheus0000** [comment]
Feel free to add it yourself, but this sounds like feature creep, and I'd prefer mitch work on _actual_ bugs.
