### ISSUE TITLE
[Warning]log print warning when cutting wood logs

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#8355]
#### Which modpack version are you using?

2.1.1.2 dev
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

I cutting redwood logs from Natura with a saw and got this warnings
![image](https://user-images.githubusercontent.com/2970688/128230762-7610d614-77cc-4120-9d7c-c6f97d9412ca.png)

#### What happened instead? (Attach screenshots if needed)

remove the warnings and fix it
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
:)

@jss2a98aj any idea what went wrong in Natura

**Comment by chochem** [comment]
still in issue in 2.3.0 stable but seems to be fixed in dev. probably was a script problem?
