### ISSUE TITLE
Bad Oil Cracking Unit description

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#8356]
#### Which modpack version are you using?
2.1.1.1a with newest bartworks from jenkins
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I had oil crackers set up and running
#
#### What happened instead? (Attach screenshots if needed)
They stopped working because their structure changed and I couldn't figure out why
#
#### What do you suggest instead/what changes do you propose?
Change description of oil cracking unit to "Energy chatch any middle ring casing" because it says "any casing" and is not true.
#
#### What is your GTNH Discord username?
Pxx500#6984

It is also possible that description change occured in different file and this issue is useless.

**Comment by Glease** [comment]
Sounds like an oversight when I migrate it over. Should be fixed soon.
