### ISSUE TITLE
Thaumcraft - TConstruct GUI conflict with aspect display [Misalinment or "incorrect aspect display"] (difficult to explain)

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#8359]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
its hard to explain this issue, please refer to this conversation to get the best idea of what this bug is
https://discord.com/channels/181078474394566657/234936569360809996/872677514571571220

Steps to reporduce:
View an items aspcest in a TConstruct Crafting table wtih a chest connected to it and you will see theres a mis-alinment issue with the aspects probaly due to the GUI shifting (click link above for more context)

#### What do you suggest instead/what changes do you propose?
A fix to this bug via ThaumTweaks4 would be nice (is even present on unmodified instances of GTNH

#
#### What is your GTNH Discord username?
Doggo_9000

**Comment by SteamDoge9000** [comment]
Notice: this issue seems to be happening on this as well, maybe theres a connection

https://github.com/GTNewHorizons/NotEnoughItems/issues/142
