### ISSUE TITLE
Energy problems (spectral solar panel, portable scanner)

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8360]
#### Which modpack version are you using?
2111a - dev
#
#### What did you try to do, and what did you expect to happen?
Measure energy going through the cable with the tricoder. 1tick measurement is okay 20tick is 0
![kép](https://user-images.githubusercontent.com/7230430/128330598-52ba560b-e586-433e-a831-7a43373ed5bb.png)

Also im experiencing a weird behavior with spectral solars. Some panels in my base are working just fine after the upgrade, some are not. After replacing them (even the cabling) - still not. They collecting energy into the buffer but not outputting it. While writing this tix i did some more testing and eventually i managed to fix them by just replacing them until they started outputting.
This bug is mostly happened when the solar are connected to an AFSU

#
#### What is your GTNH Discord username?
szajkop

**Comment by Szajkop** [comment]
tricoder issue is still persist in 2112 dev pack

**Comment by boubou19** [comment]
sometimes solars need to be deconnected/reconnected so just use the wire cutter on the wire connected to them. I never could get this consistantly happening, seems very random.
