### ISSUE TITLE
[Meta] Add links to mods' websites in the readme

### ISSUE THREAD

**Issue by makamys** [GTNewHorizons/GT-New-Horizons-Modpack#8361]
It would be nice if the modlist in the readme had links that took you to the corresponding mod's website (ideally the GitHub repo). There are some mods I can't find the source code of anywhere, like `backpack-2.2.4-1.7.x.jar`.
Note that this could be a violation of LGPL, which requires you to provide a way to obtain the source code for works licensed under it that you distribute.

**Comment by Prometheus0000** [comment]
Go to https://github.com/orgs/GTNewHorizons/repositories and search. Or, go to http://jenkins.usrv.eu:8080/ and search. If you can't find it there, it should be something that we didn't fork and probably on curseforge.

**Comment by makamys** [comment]
I already checked both of these and Backpack isn't in either. And the latest version on CurseForge for 1.7.x is 2.0.1.
But I managed to find [the repo](https://github.com/runescapejon/Minecraft-Backpack-Mod) based on a clue I found by looking into the decompiled mod, so that part of the question is solved.

Still, this stuff really needs to be documented better. I can make a PR for it if that's OK.

**Comment by repo-alt** [comment]
That may actually be useful for those mods that we have not forked.

**Comment by boubou19** [comment]
well better documentation never hurts, so if you want to do it, go ahead.

**Comment by Dream-Master** [comment]
Guess we using a fork will check later.

**Comment by makamys** [comment]
Cool, I'll do it then. Do you want me to reformat it as a table while I'm at it? I think it would be less messy that way. It would look something like this:
## Modlist - NewHorizons<BR>

| Name                                 | Version                         |
| ------------------------------------ | ------------------------------- |
| [Advanced Solar Panels](https://www.example.com/)             | 3.5.1a                           |
| [Adventure Backpack](https://www.example.com/)                   | 0.9h15-GTNH                           |
| [AE2 Stuff](https://www.example.com/) | 0.5.1.11_GTNH                           |
| [AE2 Wireless Crafting Table](https://www.example.com/)                           | 1.8.7.8-GTNH                           |

---

> 
> 
> Guess we using a fork will check later.

I already figured the Backpack thing out, it was https://github.com/runescapejon/Minecraft-Backpack-Mod

**Comment by Prometheus0000** [comment]
Feel free to go ahead, it's just a pain to do.

**Comment by Dream-Master** [comment]
Done

**Comment by makamys** [comment]
The CurseForge page links added in d3deaee362080038074f45740586759e23c8bcf1 don't have the exact version of mods GTNH has (for example GTNH's version of Extra Utils is 1.2.13a, while the newest on CurseForge is 1.2.12, suggesting GTNH is using a fork).
Also BoP's link is broken.
And I just noticed I messed up RF Expansion's line, oops.

**Comment by Dream-Master** [comment]
Bop Link is private
Extra utilities has some clsses fixed
rf expansions is out so far i know

**Comment by Prometheus0000** [comment]
We have 2 cofh libraries for RF compat AFAIK.
