### ISSUE TITLE
RFC: Autoselect assembler craft from NEI to AE pattern

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#8362]
#### Which modpack version are you using?
2.1.1.1
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
want to make pattern for crafting recipe in assembler
#
#### What happened instead? (Attach screenshots if needed)
it's most borring part of the game
#
#### What do you suggest instead/what changes do you propose?
Autoselect assembler craft from NEI to AE pattern
gif explanation:
https://imgur.com/mzjTDrW

source code:
https://github.com/vfyjxf/NotEnoughEnergistics/blob/08442003b695b31113ff1798caa637e330cce6b3/src/main/java/com/github/vfyjxf/nee/network/packet/PacketNEIPatternRecipe.java
#
#### What is your GTNH Discord username?
John S

**Comment by RaitGamerGR** [comment]
Now it works only with 3x3 pattern terminal, needs to do it for 4x4.

**Comment by Prometheus0000** [comment]
What's the bug?

**Comment by GlodBlock** [comment]
he means that mod in #mod-dev
![image](https://user-images.githubusercontent.com/60341015/128531845-28d9d533-aa5b-4f09-bbcc-93065ff5503d.png)

**Comment by GlodBlock** [comment]
> Now it works only with 3x3 pattern terminal, needs to do it for 4x4.

in fact it has been done, but vfyjxf haven't merge his code.

**Comment by GTNH-Afx237v7** [comment]
If this gets added it’d be nice to not have to de-select the assembler, as it’s Part of the pattern as shown in the video.
