### ISSUE TITLE
Bug in AppliedEnergistics2

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#8365]
Latest build from http://jenkins.usrv.eu:8080/job/Applied-Energistics/
When using the do not save search option, the following occurs:
In the search, you write the name of the item, the item is in the terminal.
You leave the terminal and enter back. The search string is cleared, but the last search result remains in the terminal. If you enter and exit the terminal again, the terminal already shows without saving.
Also, if you open the config file AppliedEnergistics2.cfg and watch the changes when you change any parameter from the game, for example, synchronization with NEI, the file is updated and the corresponding option changes to the one that is installed in the game. But when you change the option not to save the search in the game, nothing happens in the file. There is no file write for this option.

**Comment by repo-alt** [comment]
What is the actual version you took from Jenkins?

**Comment by Pilad** [comment]
> 
> 
> What is the actual version you took from Jenkins?

last , http://jenkins.usrv.eu:8080/job/Applied-Energistics/74/changes

**Comment by repo-alt** [comment]
I 'm pretty sure config saving was fixed 2 builds ago

**Comment by Pilad** [comment]
But not work ((

**Comment by Pilad** [comment]
> 
> 
> I 'm pretty sure config saving was fixed 2 builds ago

Sorry for disturbing. I was wrong. The file with the same name was probably. I downloaded it again and now it works.
