### ISSUE TITLE
Mixer recipe conflict: IC2 coolant

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8367]
#### Which modpack version are you using?
2111a - dev
gregtech-5.09.37.06
GT-PlusPlus-1.7.08.GTNH

#
#### What did you try to do, and what did you expect to happen?
Create ic2 coolant from lapis dust + config1 + distil water
#
#### What happened instead? (Attach screenshots if needed)
Blue dye mix created
https://user-images.githubusercontent.com/7230430/128609469-01e09862-000c-4a05-b80b-481219b02c3f.mp4
#
#### What is your GTNH Discord username?
szajkop

**Comment by Szajkop** [comment]
If i read your code right, I dont think the solution (change circuit to 2) will fix the problem.
The dye water recipe is done without a config, its not colliding with conf1 for coolant
![kép](https://user-images.githubusercontent.com/7230430/128610230-edbe0dd2-65c4-4823-ab3a-72e4da6cd3de.png)

**Comment by GlodBlock** [comment]
wait, if the blue dye recipe doesn't need the circuit, this bug should have exist since a long time ago, but why it doesn't happens until today?

**Comment by Sphyix** [comment]
recipe with lapis dust doesn't exist in 2.1.1.0, only dust that can be used for water mixed blue dye is sodalite dust
rest is dyes, lapis lazuli and sodalite

**Comment by GlodBlock** [comment]
ok, i have added the circuit in dye recipes. the conflict can be actually solved now.
