### ISSUE TITLE
Super/Quantum chest causing obscene lag

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#8368]
![image](https://user-images.githubusercontent.com/54497873/128610814-aff7eacf-d3ea-4717-b3b7-01fe3cb0b9d5.png)

![image](https://user-images.githubusercontent.com/54497873/128610816-4e26c561-3a5a-42a1-aab3-511057c56ec0.png)

Not really sure what is going on here, but it just seems to be getting worse and worse. These never used to cause anywhere near this much lag and now they are spiralling into multiple ms alone. The conveyors on them are not even high tier, just IV and EV respectively. Removing the conveyor does seem to reduce the lag to like a few hundred ns and thus resolve the issue but it's baffling me why they would cause this much lag.

**Comment by D-Cysteine** [comment]
The only recent functional change to these seems to be [implementing `isPrioritized()`](https://github.com/GTNewHorizons/GT5-Unofficial/commit/83b5d8703d5f34f17a70f30fa04ce13f41c44afe#diff-f55655b85712f3b30bad288d6e14155209b466103ecae0d548e10a7e13f088b2), which I think is an AE2 method:
https://github.com/GTNewHorizons/GT5-Unofficial/commits/experimental/src/main/java/gregtech/common/tileentities/storage

I'm not exactly sure how that method works, but I do see that it looks like you have an AE2 storage bus connected, so I wonder if this change could be the cause? Is it possible to test with a version of the mod without the `isPrioritized()` change?

**Comment by GTNH-Colen** [comment]
> The only recent functional change to these seems to be [implementing `isPrioritized()`](https://github.com/GTNewHorizons/GT5-Unofficial/commit/83b5d8703d5f34f17a70f30fa04ce13f41c44afe#diff-f55655b85712f3b30bad288d6e14155209b466103ecae0d548e10a7e13f088b2), which I think is an AE2 method:
> https://github.com/GTNewHorizons/GT5-Unofficial/commits/experimental/src/main/java/gregtech/common/tileentities/storage
> 
> I'm not exactly sure how that method works, but I do see that it looks like you have an AE2 storage bus connected, so I wonder if this change could be the cause? Is it possible to test with a version of the mod without the `isPrioritized()` change?

I have literally hundreds of super chests in my base but these two seem to cause insane lag for no rhyme or reason. I've got nearly 300 other super chests with buses doing nearly no lag but these ones just fly off the handle with multiple ms each. Also a bunch of others with no bus on them and no lag either. Really odd bug, not sure what is causing it.

**Comment by repo-alt** [comment]
Lag was caused by the pipe (automation) changing chest contents, causing grid updates.
