### ISSUE TITLE
Server lost connection by Electric Prospector's Scanner with DD

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8372]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
multi
#
#### What did you try to do, and what did you expect to happen?
using Electric Prospector's Scanner with DD(the part of DD that was generated before the vein stopped being generated)
#
#### What happened instead? (Attach screenshots if needed)
Server lost connection

log:
[Channel: DetravScanner] Payload may not be larger than 2097050 bytes
[04:04:16 INFO]: yukieiji lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2189823 into 3

#
#### What do you suggest instead/what changes do you propose?
Fix it?
#
#### What is your GTNH Discord username?
yukieiji

**Comment by Sphyix** [comment]
use a smaller electric prospector scanner, you are getting disconnected cause it's sending too much data

**Comment by botn365** [comment]
DD shound even have ores anymore

**Comment by Sphyix** [comment]
yea, only way i found to reproduce it now is by using the 41x41 prospector in bartworks dims to check fluids
