### ISSUE TITLE
IC2 Crop seed bag drop chance bug

### ISSUE THREAD

**Issue by xcube16** [GTNewHorizons/GT-New-Horizons-Modpack#8375]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
This happens on both single player and multiplayer.
#
#### What did you try to do, and what did you expect to happen?
While trying to optimize my IC2 crops, I started writing a python script to graph and find the best stats (growth, gain, resistance, and environmental factors). In the process of looking at and debugging the IC2 crop code, specifically `ic2.core.crop.TileEntityCrop`, `ic2.api.crops.CropCard`, and other CropCard sub-classes, I discovered a bug that prevents the resistance stat from having much (if any) effect for crops, especially those that reset to the first growth stage after being harvested normally. This also makes the drop chance lower than it should be.

In summery, `TileEntityCrop#pick(boolean)` calculates two mutually exclusive drop chances that result in the crop dropping 0 to 2 seed bags when breaking a fully grown crop. The first drop chance (the main one that is 80% plus) is partly calculated by `CropCard#dropSeedChance(ICropTile)` in which most (all?) implementations rely on the crop's current size. However, before that happens, `TileEntityCrop#harvest(boolean)` is called and that RESETS THE SIZE to the size after harvest!

decompiled TileEntityCrop#pick(boolean):
```
    public boolean pick(boolean manual) {
        if (this.crop == null) {
            return false;
        } else {
            boolean bonus = this.harvest(false);                // <------- SIZE GETS RESET
            float firstchance = this.crop.dropSeedChance(this); // <------- dropSeedChance() USES SIZE

            int drop;
            for(drop = 0; drop < this.statResistance; ++drop) {
                firstchance *= 1.1F;
            }

            drop = 0;
            int x;
            if (bonus) {
                if (IC2.random.nextFloat() <= (firstchance + 1.0F) * 0.8F) {
                    ++drop; // <------------ firstChance is 0.0 so we get this drop only 80% of the time.
                }

                float chance = this.crop.dropSeedChance(this) + (float)this.statGrowth / 100.0F;
                if (!manual) {
                    chance *= 0.8F;
                }

                for(x = 23; x < this.statGain; ++x) {
                    chance *= 0.95F;
                }

                if (IC2.random.nextFloat() <= chance) {
                    ++drop;
                }
            } else if (IC2.random.nextFloat() <= firstchance * 1.5F) {
                ++drop;
            }

            ItemStack[] re = new ItemStack[drop];

            for(x = 0; x < drop; ++x) {
                re[x] = this.crop.getSeeds(this);
            }

            this.reset();
            if (IC2.platform.isSimulating() && re.length > 0) {
                for(x = 0; x < re.length; ++x) {
                    if (re[x].func_77973_b() != Ic2Items.cropSeed.func_77973_b()) {
                        re[x].field_77990_d = null;
                    }

                    StackUtil.dropAsEntity(this.field_145850_b, this.field_145851_c, this.field_145848_d, this.field_145849_e, re[x]);
                }
            }

            return true;
        }
    }
```

decompiled TileEntityCrop#harvest(boolean) and harvest_automated(boolean):
```
    public boolean harvest(boolean manual) {
        ItemStack[] drops = this.harvest_automated(false);
        if (drops == null) {
            return false;
        } else {
            if (IC2.platform.isSimulating() && drops.length > 0) {
                ItemStack[] var3 = drops;
                int var4 = drops.length;

                for(int var5 = 0; var5 < var4; ++var5) {
                    ItemStack drop = var3[var5];
                    StackUtil.dropAsEntity(this.field_145850_b, this.field_145851_c, this.field_145848_d, this.field_145849_e, drop);
                }
            }

            return true;
        }
    }

    public ItemStack[] harvest_automated(boolean optimal) {
        if (this.crop == null) {
            return null;
        } else if (!this.crop.canBeHarvested(this)) {
            return null;
        } else if (optimal && this.size != this.crop.getOptimalHavestSize(this)) {
            return null;
        } else {
            double chance = (double)this.crop.dropGainChance();
            chance *= Math.pow(1.03D, (double)this.statGain);
            int dropCount = (int)Math.max(0L, Math.round(IC2.random.nextGaussian() * chance * 0.6827D + chance));
            ItemStack[] ret = new ItemStack[dropCount];

            for(int i = 0; i < dropCount; ++i) {
                ret[i] = this.crop.getGain(this);
                if (ret[i] != null && IC2.random.nextInt(100) <= this.statGain) {
                    ++ret[i].field_77994_a;
                }
            }

            this.size = this.crop.getSizeAfterHarvest(this); // <---------- SIZE GETS RESET TO 'size after harvest'!
            this.dirty = true;
            return ret;
        }
    }
```

decompiled CropCard#dropSeedChance(ICropTile):
```
    public float dropSeedChance(ICropTile crop) {
        if (crop.getSize() == 1) { // <--------- For most crops, size is 1 after harvest
            return 0.0F;
        } else {
            float base = 0.5F;
            if (crop.getSize() == 2) { // <------- Crops with a 'size after harvest' of 2 also take a hit, but its not as bad
                base /= 2.0F;
            }

            for(int i = 0; i < this.tier(); ++i) {
                base = (float)((double)base * 0.8D);
            }

            return base;
        }
    }
```

#
#### What happened instead? (Attach screenshots if needed)
A tier 1 crop, without this bug and with only a little resist (1 should be good enough), should drop at least one seed bag 100% of the time. However after testing in-game and using a java debugger (Intellij IDEA with a 1.7.10 forge MDK and all the GTNH mods visible to the debugger) Oak Bonsai with growth 1, gain 1, and resist 1 was found to drop seed bags only 80% of the time.

#
#### What do you suggest instead/what changes do you propose?
I believe that the IC2 developers intentions are self evident that the crop's size going into `CropTile#dropSeedChance(ITileCrop)` should be the crop's current size and not the 'size after harvest'. Simply flipping the harvest() call and the dropSeedChance() call lines in `TileEntityCrop#pick(boolean)` would fix this bug.
```
boolean bonus = this.harvest(false);
float firstchance = this.crop.dropSeedChance(this);
```
should be
```
float firstchance = this.crop.dropSeedChance(this);
boolean bonus = this.harvest(false);
```

I am unfamiliar with how GTNH does patches like this to it's mods, however I have worked on ASM patches for mods in the RLCraft modpack. I would be willing to submit a pull request to fix this bug in whatever patch system that GTNH uses, if this bug is indeed an undesired behavior.

#
#### What is your GTNH Discord username?
Minecraft IGN: xcube, Discord: xcube#6187

related issues:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7512

**Comment by boubou19** [comment]
well if you could make a PR in hodgepodge for a mixin that adresses the issue (with a config option to toggle it) that would be nice of you :D

**Comment by leagris** [comment]
At that point, for the few IC2 we use, we could have our own mod  ^ ^

**Comment by Prometheus0000** [comment]
I honestly wonder how much of IC2 GT even uses.
