### ISSUE TITLE
Witching gadgets bug that I thought would have been fixed (Entity Lighting up when "Polaroids" are on item frames)

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8376]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
when you aproach a village with Witching Gadgets structure wtih those photos in item frames it will cause mobs to be brighter than they should for some unkown reason
#
####Attach screenshots if needed
![image](https://user-images.githubusercontent.com/38770780/128646222-6124d98d-36e5-40c9-b5a4-6bc1f4919840.png)

#
#### What do you suggest instead/what changes do you propose?
to please try and fix this rendering issue
#
#### What is your GTNH Discord username?
Dogg- Ya know what, you already know who this is. 
#
####Bonus Issue
The structure when it generated, the glowstone block sometimes needs a block update to make it light it up

Thanks for reading in Advanced

**Comment by SteamDoge9000** [comment]
XD, I forgot about this one

and I see a possible fix in a pull request

thank you! it may not mean much but visual fixes like this mean the world to me and those that cant stand visual bugs like this XP

if you want, I can test it on my end to see if it works. id be more than willing to help in any way I can ^w^

**Comment by eigenraven** [comment]
I tested it in creative in my dev environment, but if you want to confirm try the build from here: <http://jenkins.usrv.eu:8080/job/WitchingGadgets/41/artifact/build/libs/WitchingGadgets-1.7.10-1.2.18-GTNH-2-g30b76e2.jar>

**Comment by SteamDoge9000** [comment]
thanks, this should be easy to test since its been a base mod issue {i mean that it existed even in the original mod itself[

ill run it both on a lite pack im messing around on and in the GNTH instance I have as well

ill get back to za

**Comment by SteamDoge9000** [comment]
ok, I should have expected that this would not work outside of the pack (I mean as in it would work without gregtech being a dependency)
oh well, 

off to test it in the pack now

**Comment by SteamDoge9000** [comment]
![image](https://user-images.githubusercontent.com/38770780/178158500-f0b547ae-9304-4ddd-ad04-10f4d7cd5854.png)
the issue is fixed, you can close this issue as completed once its merged into the main pack itself 

thank you

although the GT requirement is a bit... eh. I must ask, why did GT become a required dependency out of curioucity

**Comment by SteamDoge9000** [comment]
DOH WRONG IMAGE
