### ISSUE TITLE
Wrong research station recipe for UMV energy hatch

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8377]
#### Which modpack version are you using?
GTNH 2.1.1.0
#

UEV energy hatch is both used to write the research data for the UIV and UMV energy hatch

![image](https://user-images.githubusercontent.com/57050655/128649618-bc1663ea-5257-415e-af27-1751e0d9f058.png)

**Comment by Prometheus0000** [comment]
Pretty sure this (or something similar) was fixed already.

**Comment by hucking** [comment]
can confirm fixed in dev:
![image](https://user-images.githubusercontent.com/1339552/132097867-73bd3b36-f52f-4ece-99fb-d2c2189ac517.png)
![image](https://user-images.githubusercontent.com/1339552/132097875-495a3867-62aa-498e-98a9-fcdf52a37475.png)
