### ISSUE TITLE
Oil and lube quest gating conditions change proposal 

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#8379]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I skipped lv pump and went straight for the drilling plant. 
#
#### What happened instead? (Attach screenshots if needed)
I couldn't find the mv energy hatch quest to get to hv. It is gated behind lv pump quest alongside with all the oil quest, lv pump is basically useless for me right now. And lube behind oil is a weird gate as I made the mv energy hatch way before I have oil using creo. 
#
#### What do you suggest instead/what changes do you propose?
Add an Or on the conditions of the oil quest (blackgold), or rearrange it to tell you that creo makes lube too.... 
The intent is to make Oil quest accessible from fluid/gas drilling plant, instead of only for lv pump. And maybe change lube quest to be accessible from creo quest in stone age.
#
#### What is your GTNH Discord username?
Hebi

**Comment by Prometheus0000** [comment]
I changed it to be an OR from the brewing machine as well, anything else wouldn't really fit.
