### ISSUE TITLE
Thaumcraft 4 tweaks scaling shrinks back

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/GT-New-Horizons-Modpack#8381]
#### Which modpack version are you using?
GTNH 2110
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Set scaling x2 in mod options. Expect no changes in thaumonomicon interface size when open.
#
#### What happened instead? (Attach screenshots if needed)
Interface size changes. Open book and close it with esc button few times in a row to see effect.
Twitch clip to illustrate:
[https://clips.twitch.tv/CrepuscularPluckyVampireCoolStoryBro-BgaL-qPu-sn01gE3](url)
#
#### What do you suggest instead/what changes do you propose?
Fix it. :)
#
#### What is your GTNH Discord username?
Usernm

**Comment by Glease** [comment]
Set the infer option just above the one you tweaked to false.

**Comment by Usernm0** [comment]
Ok, infer to false works. But it's not proper work anyway. Option should do thaumonomicon resize once, or not do resize at all. Not make many small steps everytime i open book.

**Comment by Glease** [comment]
because your window size can change while you play the game, e.g. kvm switch, dragging it around, toggle fullscreen etc.

**Comment by Usernm0** [comment]
But window size not change during twitch clip. I see problem with calculation new size. It should be same if window size not changed.

**Comment by Glease** [comment]
It's technically hard to figure out whether window size changed. Unlike any proper GUI toolkit/framework Minecraft does not notify you when resize happens.

**Comment by Usernm0** [comment]
You talk about situation where minecraft resized with book interface open? It shrinks when I change window size, and even size back if i resize minecraft window to extreme small and back. So mod (or thaumcraft) know about window size changes and do something.

And this case not describe why size changes with small steps every time i open book.

**Comment by Glease** [comment]
> You talk about situation where minecraft resized with book interface open? It shrinks when I change window size, and even size back if i resize minecraft window to extreme small and back. So mod (or thaumcraft) know about window size changes and do something.

What you are describing is the end result. The technical detail does not work in this way. Minecraft effectively close and reopen the current GUI when the window resizes (under the hood the same event got sent). This makes it near impossible to distinguish between window opened and window resized.

> And this case not describe why size changes with small steps every time i open book.

It's likely minecraft didn't properly clean up some variables. I compute scale from what minecraft gives me and a few constants (dumb numbers like 2, 24 that cannot be changed). Not much I can do here.
