### ISSUE TITLE
Witchery Seeds garlic description outdated

### ISSUE THREAD

**Issue by ARADPLAUG** [GTNewHorizons/GT-New-Horizons-Modpack#8384]
#### Which modpack version are you using?
2.1.0.0QF1-1.7.10
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Break tall grasses to get Witchery garlic
#
#### What happened instead? (Attach screenshots if needed)
After about a thousand tall grasses broken, still don't have a Witchery garlic
#
#### What do you suggest instead/what changes do you propose?
Update the description for Witchery Seeds to reflect that you need to Mattock the ground to get Witchery garlics
#
#### What is your GTNH Discord username?
ARADPLAUG

**Comment by ARADPLAUG** [comment]
I've also noticed that the Mid-tier Wand quest refers to the "To Grind, or Not To Grind" tab which has been removed

**Comment by chochem** [comment]
They dont have a tooltip and the quest looks correct: 

![image](https://user-images.githubusercontent.com/40274384/182028163-f3fda166-1e5e-47f2-896c-972fd808d9f2.png)

I also dont see any reference to To Grind, or Not To Grind in any wand quest.
