### ISSUE TITLE
wrong recipe for LuV conveyor module

### ISSUE THREAD

**Issue by stlchase40** [GTNewHorizons/GT-New-Horizons-Modpack#8391]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Make LuV conveyor module
#
#### What happened instead? (Attach screenshots if needed)
It no make
#
#### What do you suggest instead/what changes do you propose?
Fix the conveyor module recipe in nei to show it needs molten styrene butadiene rubber
#
#### What is your GTNH Discord username?
stlchase40
![2021-08-11_12 31 16](https://user-images.githubusercontent.com/86484890/129076400-883b2ba9-2e98-416e-914d-ca54ecf9af6f.png)
![2021-08-11_12 31 37](https://user-images.githubusercontent.com/86484890/129076408-6c2bca83-57ef-42e2-8674-688f5ecf7115.png)

**Comment by GTNH-Afx237v7** [comment]
Recipes on data sticks do not change after updating. That means you will still be able to make the conveyor using styrene butadiene rubber. If you rescan the IV conveyor to a new datastick in your current version, you will have the new recipe using the rubber sheets on the data stick that is also shown in NEI.
So not a bug I guess...

**Comment by boubou19** [comment]
yup, it's intended, even if it's weird.
