### ISSUE TITLE
[Officials] Anomalous plugin settings for Ross128ba dimension

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#8394]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I went to Ross128ba on mining expedition, and then tried to get back home

#
#### What happened instead? (Attach screenshots if needed)
I tried to take the stargate back, but it was unpowered. Then as an attempt to not be stuck indefinitely I tried /home which did work despite being on a planet.

#
#### What do you suggest instead/what changes do you propose?
Ross128ba (the moon) should probably work like other planetary dimensions and not allow /home and /sethome

If someone can fix the stargate while they're at it, that would be appreciated <3
#
#### What is your GTNH Discord username?
Combuster

**Comment by boubou19** [comment]
will look into it today

**Comment by boubou19** [comment]
ross should have the same issue with /home command i guess

**Comment by combusterf** [comment]
The planet is habitable, so it makes more sense if you want to set up base there and have a /home available

**Comment by boubou19** [comment]
fixed
