### ISSUE TITLE
Suddenly very low FPS

### ISSUE THREAD

**Issue by JohnWarrior01** [GTNewHorizons/GT-New-Horizons-Modpack#8397]
Latest version
Singleplayer, local world

Hi there) Really enjoy playing GTHN. But, suddenly, game fps drops down to 5-9. Literally, I finished session, fps was 40-50, i closed game and after a fwe hours, when i try to play again - fps became 5-9.

There were no reboot, no drivers or program updates and etc. What could happen and what can i do.

PC spec 
FX-8320E
24Gb DDR3
GTX 1060 6G
Mine on SSD.

**Comment by TimeConqueror** [comment]
First of all, please add logs (fml-client-latest.log).

Extra option you could do: dowload opis and debug the game using it.

**Comment by boubou19** [comment]
in that case, opis is better as it directly points out what stuff is causing rendering load, while with warmroast or visualvm, you have to check the code calls inside the client thread. Known offenders of fps drops are thaumcraft stuff, bibliocraft stuff, DE's placed items in the world, drawers, and many others that i forgot.

**Comment by JohnWarrior01** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6975995/fml-client-latest.log)
That latest log.

What exactly should I look for in Opis?

**Comment by JohnWarrior01** [comment]
> in that case, opis is better as it directly points out what stuff is causing rendering load, while with warmroast or visualvm, you have to check the code calls inside the client thread. Known offenders of fps drops are thaumcraft stuff, bibliocraft stuff, DE's placed items in the world, drawers, and many others that i forgot.

That's case, I dont have many stuff yet. And it worked fine till last launch.

**Comment by boubou19** [comment]
you should use the client tab, and measure the rendering. if rendering is fine, then it's something happening either in the console (ie a console spam) or something heavy is happening, and in that case, you should use visualvm/warmroast to see what happens.

**Comment by JohnWarrior01** [comment]
866 uS - TileEntities
766 uS - Entities.

![Безымянный](https://user-images.githubusercontent.com/28770016/129216505-fe73cf20-f304-437d-bd31-602acf1348bb.png)

Screen of Monitor tab

After GTNH I tried Vanila 1.7.10 and 1.17 - they have stupidly low 30 fps.

**Comment by boubou19** [comment]
what's displayed in the client timing tab?

**Comment by JohnWarrior01** [comment]
![2](https://user-images.githubusercontent.com/28770016/129218466-2878becc-418d-4f26-9656-f8d11cabe743.png)
![3](https://user-images.githubusercontent.com/28770016/129218471-153bf7e2-a1cd-4734-bfc1-8cdbb4c5ea33.png)
![1](https://user-images.githubusercontent.com/28770016/129218472-de121b69-fcf9-4363-a03b-009e430e6cdc.png)

Handlers tab is clear.

**Comment by boubou19** [comment]
anything above 80µs is suspicious, look what are those tile entities (you have coordinates) but with that amount of rendering time you should have better than 40-50 fps. Check if your game is running on your gtx and not on integrated gpu, also, activate windows, as i saw some reports that windows starts reducing its performances after running inactivated for a while.

**Comment by JohnWarrior01** [comment]
I don't have integrated GC. Also I checked these coordinates, there were nothing. Literally it is coordinates of stone or dirt in ground. Some are TiC Forge or Spawners.

Looks like anything changes. FPS still low

**Comment by JohnWarrior01** [comment]
Today, after reboot - first launch was at 50-60 fps, when running it drops to 30, after restart game - again 2

**Comment by boubou19** [comment]
looks very related to your setup specifically, not the pack itself, as you are the only one who reported such behavior. You should check globally your system. Not much we can do as every possible lag spot aren't lagging. I'm closing this.
