### ISSUE TITLE
Component missing in a craft (Steel to Diamond tank upgrade)

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#8398]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What do you suggest instead/what changes do you propose?
![image](https://user-images.githubusercontent.com/76914762/129214408-dccdc2f3-d64f-4540-aa40-e5d0ec9f98d4.png)
Well since it's upgrading a steel tank to a diamond one, there should be a dimond double plate in the craft no?
#
#### What is your GTNH Discord username?
AdamR 0072
#

**Comment by boubou19** [comment]
the recipe is fonctional, but lacks the double diamond plate, which doesn't exists, so i suggest taking 2 diamond plates in the recipe.

**Comment by Dream-Master** [comment]
yea will change this or add double diamond plates

**Comment by boubou19** [comment]
other upgrade recipes involving diamond are using 1 plate instead of 2 plates or a double plate, so you might want to change it as well
