### ISSUE TITLE
Suggestion: Mega Blast Furnace/Vacuum Freezer

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#8402]
#### Which modpack version are you using?
2.1.1.1a
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
I built the Mega Blast Furance according to the following tooltip currently in game:
![image](https://user-images.githubusercontent.com/33701188/129417985-2026c564-fbed-43c7-b162-968bb46710a9.png)

I expected the Mega Blast Furnace to form. It did not form. I had to move the controller up to the 3rd layer (floating in the middle of the glass) like in the following screenshot:
![image](https://user-images.githubusercontent.com/33701188/129418085-1e0aac25-2571-4489-b6ae-422322457999.png)

#
#### What happened instead? (Attach screenshots if needed)
The Mega Blast Furnace didn't form when built as described in the controller tooltip.

#
#### What do you suggest instead/what changes do you propose?
I would like to SUGGEST (first choice) that the controller for the Mega Blast Furnace AND the Mega Vacuum Freezer be moved to the bottom layer. I realize this is entirely a preference based suggestion based on "how it looks" but (at least in the case of the Mega Vacuum Freezer) would be a quality of life improvement to be able to reach the controller from the ground. In the case of the Mega Blast Furnace it just makes it not look goofy.

**OR**

If my suggestion is rejected I would recommend that we at least change the tooltip to reflect how to properly build the Mega Blast Furance. Again the screenshot of the current tooltip in 2.1.1.1a but with suggested change:
![image](https://user-images.githubusercontent.com/33701188/129418476-fdd253ed-5ad5-47b0-8442-0be3d686f664.png)

#
#### What is your GTNH Discord username?
shawnbyday

**Comment by Glease** [comment]
Not sure about the mega freezer, but I can do MBF tooltip change. If later we decided it's worth the effort the structure code can be easily changed and have the tooltip change reverted.

**Comment by GTNH-Afx237v7** [comment]
This is like the 3rd time this tooltip is corrected...

**Comment by leagris** [comment]
Maybe as an improvement, we could have the Tool-Tip automatically generated as per Structurelib multi-block blue-print rules. It would remove errors when transcribing changes made to the structure.

**Comment by Prometheus0000** [comment]
I think that would probably be way more trouble than it's worth, even if it can be done. It's not like it's hard to change the TTs. Just that someone has to bother to do so. Plus there's comments about how to use them in there too sometimes, even in the structure part.

**Comment by Glease** [comment]
Autogenerating is possible, but the original design of TT structure api is too flexible. It's going to take some work to add it in.
