### ISSUE TITLE
OpenComputers Navigation Upgrade is uncraftable

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#8403]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Craft the navigation upgrade from OpenComputers
![image](https://user-images.githubusercontent.com/69092953/129419623-a9dfa702-5179-4556-bfa8-4ca9f6ce4c0a.png)

#
#### What happened instead? (Attach screenshots if needed)
It cannot be crafted with crafted maps. Only with a spawned-in #0 map.
#
#### What do you suggest instead/what changes do you propose?
Remove the map from the recipe, as the origin point can be changed by crafting the upgrade with a map.
#
#### What is your GTNH Discord username?
Sampsa

**Comment by KamenriderZO** [comment]
And redstone card Tier2 also not craftable,I don't know why . is it an issue of circuitassembler???

**Comment by bombcar** [comment]
Did Redstone card Tier2 get fixed?

**Comment by xTwi** [comment]
I was able to craft it using all 3 different fluids while swapping the empty map recipe in for the pull request, so it's a "I can't replicate this" thing. Might have been accidentally fixedindev at some point.
