### ISSUE TITLE
EMT Compressed Solar craft merge bug

### ISSUE THREAD

**Issue by sintken** [GTNewHorizons/GT-New-Horizons-Modpack#8406]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Craft the EMT compressed and double-compressed solars in the arcane assembler
#
#### What happened instead? (Attach screenshots if needed)
It does some fine and then merges the craft with a different craft and stops making them?? 
![image](https://user-images.githubusercontent.com/72178165/129451448-54a4ad4b-3f79-42de-84ac-5f5ec04f4407.png)
like? it just shoves the materials in the bio mainframe craft and goes "well guess these will just sit in the crafting computer lol"
#
#### What do you suggest instead/what changes do you propose?
what the fuck is going on here
#
#### What is your GTNH Discord username?
sintken (taintstainer)

**Comment by Pnc6lx** [comment]
what kind and how many compressed solar in this picture?

**Comment by sintken** [comment]
> what kind and how many compressed solar in this picture?

single compressed EMT solar, craft was for 250k, 21k were made before this happened. it's happened multiple times, usually gets about 5k-25k in before it bugs out.

**Comment by sintken** [comment]
addl info: isolated that the bug happens on chunk reload/server restart, and it happens every time

**Comment by Sphyix** [comment]
What crafting storage is being used for the craft?
I never encountered this and I'm using only 64k to avoid EC2
