### ISSUE TITLE
Feature request+bugs for structurelib

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8407]
#### Which modpack version are you using?
2.1.1.1a
#
1) A way to determine if the MB cannot be rotated (An X in the middle?)
2) A way to determine if it's compatible with rotating+MSHP (the grid already doesn't show up, but maybe add a circle with a cross through it?)
3) A way to clear a currently showing hologram (shift builds it, so maybe ctrl or alt on the controller to clear?)
4) Compat for GT wrench and hologram projector with TT MBs (though I like the scrench)
5) Remove the unneeded FRT
6) The flip image appears to be based on the block direction, and will sometimes not look accurate
![image](https://user-images.githubusercontent.com/8517039/129455664-ed66e169-3675-4cf4-bb06-0a86bc1084d3.png)
![image](https://user-images.githubusercontent.com/8517039/129455658-fa0c42f5-6f2a-4da6-96d8-40e53afc179d.png)
![image](https://user-images.githubusercontent.com/8517039/129455671-76562c0b-6567-4bdb-a121-ea515648a833.png)
![image](https://user-images.githubusercontent.com/8517039/129455676-37c30101-eb7b-49bf-8980-bdd24b9660d1.png)
If possible, please make it always look the same. PS: the rotate icon is the same.
7) An upgraded MSHP that will place stuff for you even when not in creative (for people who place a lot of stuff)
8) Did you add a recipe for the MSHP yet?

**Comment by Glease** [comment]
What even is MSHP or FRT?

**Comment by Glease** [comment]
Anyway, I know flip display might be rotated, but I have no intention to fix it. Figuring out which direction should have it rotated is too much for my limited CG knowledge. I have no objection if anyone go fix it though.
