### ISSUE TITLE
The assemblyline NEI page doesn't show the voltage tier, unlike other pages

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8408]
#### Which modpack version are you using?
2.1.1.1a
#
![image](https://user-images.githubusercontent.com/8517039/129456736-55938f8a-d54d-4a56-8c5b-5b135c9b79e9.png)
![image](https://user-images.githubusercontent.com/8517039/129456723-2b4217b0-d6b9-4c69-939f-6fde58b60885.png)

Also, why is there a usage and a voltage and amperage on every page? This is only useful on a few things like the arc furnace. It might be better to just show something like: "Usage: 90 EU/t (30 EU/t LV * 3A)" for the machines that need more than 1A instead.
![image](https://user-images.githubusercontent.com/8517039/129456869-de0338ca-8f92-45df-9158-e67b23ab6111.png)

PS: The EBF also doesn't show the tier, and the voltage and amperage lines are unused.
![image](https://user-images.githubusercontent.com/8517039/129456839-7802e3f4-6be7-441f-a445-1d70707b50b4.png)

**Comment by yukieiji** [comment]
The Vacuum Freezer, Bacterical Vat, and GT++ multi-block machines also doesn't show the tier.
![2021-08-15_07 51 00](https://user-images.githubusercontent.com/40425798/129462129-ac8bb60a-2ae2-41b9-ac38-65c067726794.png)
![2021-08-15_07 55 26](https://user-images.githubusercontent.com/40425798/129462130-3e9f86b1-467b-4696-badb-ec400903ac59.png)

**Comment by bombcar** [comment]
EBF at least is because it can be fed multiple ways. One amp of MV or 4 amps of LV say. But maybe then you could put a minimum

**Comment by Prometheus0000** [comment]
Are you saying you can't do that with other MBs? You can! The exception is the ones that can only take one energy hatch. But in no case does it affect the recipe unless it wants more than 1A of the tier of the recipe. Like the research station.
