### ISSUE TITLE
Processing array full of UEV machines does not parallel as much as they are supposed to

### ISSUE THREAD

**Issue by MadMan310** [GTNewHorizons/GT-New-Horizons-Modpack#8409]
#### Which modpack version are you using?
2.1.1.0
#
#### What did you try to do, and what did you expect to happen?
In these screenshots, I have a processing array full of 64 UEV macerators. However, when you scan the controller, it shows that the maximum parallel is 256. This should mean that the PA should parallel 256 at a time.

![image](https://user-images.githubusercontent.com/66886359/129462545-8f3aa130-445d-435d-8dfc-2d61a7776d35.png)

![image](https://user-images.githubusercontent.com/66886359/129462543-4b272fb9-a7ba-4952-a252-91a2497501f3.png)
_This is the output when scanning the controller block. Notice how it says `Parallel processing: 256`_
#
#### What happened instead? (Attach screenshots if needed)
However, the PA only did 64 operations at a time instead of the expected 256 (It was only running at 1 stack at a time)
#
#### What do you suggest instead/what changes do you propose?
The PA should actually parallel 256 at a time.
#
#### What is your GTNH Discord username?
MadMan310#2048

**Comment by boubou19** [comment]
looks like the tricorder is displaying wrong info, as a PA is supposed to have its amount of parallel equals to the amount of machines

**Comment by GTNH-Colen** [comment]
I don't see an issue with allowing 256x parallel only IF you use UEV machines given they are essentially the last tier as the above ones are not craftable. It should still use 256x UEV to run, obviously. Gives an incentive to actually use UEV machines in a PA I suppose.

**Comment by boubou19** [comment]
PA are already enough of a hack, and their use should be diminished once obama will be out.

**Comment by GTNH-Colen** [comment]
> PA are already enough of a hack, and their use should be diminished once obama will be out.

I mean PAs will likely always have a place. I use GT++ heavily in my base but still use PAs in places just because of the mass parallel they offer. It's not competing with Obama or GT++, just a different option that is sometimes useful.

**Comment by Prometheus0000** [comment]
> I mean PAs will likely always have a place.

Yes, in the garbage _once they're deleted_.

**Comment by GTNH-Colen** [comment]
> > I mean PAs will likely always have a place.
> 
> Yes, in the garbage _once they're deleted_.

I don't think you can realistically delete PAs from the game, they're base GT multiblocks that are used all over the place. It seems needless to destroy content just for offering an alternative option.

**Comment by Prometheus0000** [comment]
We'll see once obama gets finished. Talking about it now is kinda pointless.

**Comment by Phineasor** [comment]
ti does 64 parallels with 16 machines though so the scanner is not snowing the wrong info.

**Comment by botn365** [comment]
it is showing the wrong info 
in the code PA wont go above 64

**Comment by mitchej123** [comment]
> > > I mean PAs will likely always have a place.
> > 
> > 
> > Yes, in the garbage _once they're deleted_.
> 
> I don't think you can realistically delete PAs from the game, they're base GT multiblocks that are used all over the place. It seems needless to destroy content just for offering an alternative option.

Base as in added by blood asp, not Greg.  They are a garbage hack and need no buffs.

**Comment by alphaNOVAircraft** [comment]
paying a stack UEV machines is expensive enough xD

**Comment by GTNH-Colen** [comment]
> Base as in added by blood asp, not Greg. They are a garbage hack and need no buffs.

Why are you so opposed to them even existing? It does no harm to you to allow them to exist given it's fully implemented and in wide use in many peoples bases. Seems really toxic to want to purge it for the sake of it.

**Comment by boubou19** [comment]
seems like internally it's so gross it should be removed/reworked, but given obama is coming out soon(tm), reworking it seems a bit awkward. PAs are good if you want extreme parallele and you don't necessarily care about the speed. But again, PAs vs dedicated multi debate seems a bit weird, as you can just use either one or the other to reach the same output recipe rate. Easiest thing to do is to leave PA as is, claim everywhere they are not the prefered way of mass processing stuff, then eventually fixing visual bugs. That way no dev touch the PAs anymore, players wanting to go without "cheaty multiblocks" can play, and others will just use dedicated multis. But if you want to stick to the usual "your base will break after the update because of x" then removing PAs are the way to go, but a lot of ppl will be unhappy from that. Only advantage of that is to cleaning the GT code.

**Comment by GTNH-Colen** [comment]
I broadly agree with that sentiment, they should be mostly left as be. I think balance wise a 256x parallel on UEV machines is a cool idea but don't seriously expect anyone to implement it. Bricking peoples bases for no tangible reason is completely absurd, they should be left as.

**Comment by Prometheus0000** [comment]
Listen, we'd do the same thing as obama/GT++, make them uncraftable for a version before removing. But again, decisions now don't matter until obama is done.

**Comment by mitchej123** [comment]
> > Base as in added by blood asp, not Greg. They are a garbage hack and need no buffs.
> 
> Why are you so opposed to them even existing? It does no harm to you to allow them to exist given it's fully implemented and in wide use in many peoples bases. Seems really toxic to want to purge it for the sake of it.

Please point out where I say I want them purged?  Stop being toxic yourself 🙄 and cut the strawmanning.  I said they need no buff

Bad code, bad gameplay design.  Leave them as is and discourage their use.

**Comment by boubou19** [comment]
thing is there is no legit reason outside of cleaning the GT code, and afaik nothing relies on the PA code, so forcing a transition is really not needed. Also the decision "doesn't matter" now, but it will eventually matter so stating on them even internally now will improve vision on the stuff made by the team. Otherwise it's just an endless pushback until it obama comes out.

**Comment by repo-alt** [comment]
PA is a typical ducttape solution, like "World Accelerator", and as the pack has scaled GT far beyound its original design, more ducttape is needed to keep it working.

**Comment by Phineasor** [comment]
then can I know about how the Obama machines will work and their sizes so I can plan my ore processing correctly? Because I dont want to wait another 6 months or redo all of my ore processing

**Comment by MadMan310** [comment]
Obama multiblocks should honestly act like the next step up from PAs instead of being a forced replacement for them IMO
