### ISSUE TITLE
OC charger ist not craftable 

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#8411]
#### Which modpack version are you using?
2.1.1.0
#

The recipe from NEI:
![{B K V3X`H73JF{Q6~EPZLR](https://user-images.githubusercontent.com/77818313/129463164-99dc5262-abc4-4132-bc60-8953f0a92266.png)

And the realife:
![W}T2JT18R(_%7WLYI}X~$MX](https://user-images.githubusercontent.com/77818313/129463185-bd85f32e-9103-4e02-9d8d-7b5088d1fc12.png)

The charging pads are not stackable as the recipe.

**Comment by Prometheus0000** [comment]
Did you _try_ crafting it?

**Comment by KamenriderZO** [comment]
After restart the game it works. The game was in a huge lagging
