### ISSUE TITLE
Infusions for BM not behaving properly

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8415]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
Tried to automate an infinity armor craft, had to rework the automation when the infusion automation had issues with stuff not being used and getting stuck

#
#### What happened instead? (Attach screenshots if needed)
Lava Sigil craft is not using the Lava Crystal

Sigil of Elemental Affinity is consuming the Air Sigil.
It's not consuming the Lava Sigil, but it's changing the meta adding a :2000 to the ID and making it unusable for the next recipes. It's not using the Water Sigil but in this case the sigil can be reused.

#
#### What do you suggest instead/what changes do you propose?
I don't know what's actually supposed to happen, but that's the first time I see an infusion leaving items behind (except from empty cells/buckets)
So I guess, make the infusion actually consume the items or make all the 3 sigils reusable

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by Prometheus0000** [comment]
It also happens with one of the cloths (there was another ticket). I don't really know what can be done here other than changing the recipe.

**Comment by sintken** [comment]
known bug with some BM sigils not getting consumed in crafts (like water sigil for the lightning sigil infusion, see #6875. iirc the consensus was "enjoy your free sigil"

**Comment by GTNH-Afx237v7** [comment]
Only time an item consumption is ensured is when it is placed on the center pedestal. Seems Thaumcraft tries to add 2000 damage to the item in the hopes of it being destroyed...

**Comment by Sphyix** [comment]
This is still an issue

**Comment by mitchej123** [comment]
> This is still an issue

Would you mind either digging into it yourself, or finding someone who might?  Based on the linked issue it doesn't seem Trivial to fix.  I'll reopen as "looking for help" for now.

```
Prometheus: I don't think this bug can be resolved without diving deep into BM code. Both sigils are defined the same way in the script, and I tried playing with the ownership too. Just enjoy the free sigil.
```
