### ISSUE TITLE
Change formula of the wireless connector

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#8416]
The wireless connector currently uses the following to calculate its energy usage:
```scala
val power = cfg.powerBase + cfg.powerDistanceMultiplier * (dx * dx + dy * dy + dz * dz)
```
However this grows extremely quickly and quite frankly is really just not practical to use on a large scale before having access to the AE Neutronium creative energy cell. Therefore I would suggest a change to the following formula:
```scala
val dist = math.sqrt(dx * dx + dy * dy + dz * dz)
val power = cfg.powerBase + cfg.powerDistanceMultiplier * dist * math.log(dist * dist + 3)
```
Given we really should be encouraging the use of these items over cable spam for lag reasons I don't see why it should cost 100s of thousands of EU to go any reasonable distance. Additionally I recommend we lower the powerBase value to around 60 as at present it takes I think around 200 EU/t? Just to reach 1 block over into a cleanroom which feels rather excessive as it has to remain online even when not in use.

<img width="574" alt="Screenshot 2021-08-16 at 12 51 15" src="https://user-images.githubusercontent.com/54497873/129559394-62802380-e8a3-4cca-a577-e5561b564965.png">

**Comment by boubou19** [comment]
hehe i agree that wireless AE is currently too harsh, and allowing that should reduce gross setups like quantum bridges inside CRs, or transvector interfaces outside of the CR linked to machines inside the CRs. It would also clarify the use cases of the wireless connectors and the quantum bridges. I'm just curious about how big are the differencies for distances like 2-3k. Can you scale up the curves please?

**Comment by xtake** [comment]
Yeah it's said quantum bridges are bad.
But when I connect to my other base which is 12 chunks over and like 60 blocks up thats 200k+ eu/t for only the wireless....

**Comment by repo-alt** [comment]
why bridges are bad? (not related to that issue, just curious)

**Comment by boubou19** [comment]
> why bridges are bad? (not related to that issue, just curious)

i think it comes from the AE2 guide we wrote a while ago: in it, we say that quantum bridges are more laggy than wireless connectors.

**Comment by repo-alt** [comment]
well, if compared like that yes, although I can hardly imagine someone building a hundred of them for it to be noticeable.

**Comment by Prometheus0000** [comment]
I don't understand why you want to change this though? What's the use case for it _other_ than going into a cleanroom? You're supposed to use the QB to go any real distance, and has the cost to match, if we make these things super easy to use, people won't use the appropriate method.

Also, if the QB is laggy, maybe make a ticket and/or ask repo to look at it? As he said, I have no clue why you would need so many that it would cause lag.

**Comment by repo-alt** [comment]
If I remember correctly cable length matter when the network node cache is rebuilt, that is - when some part is loaded, unloaded, disconnected, etc. That usually does not happen very often. 
I never used many wireless connectors myself though, so if someone did (presumably with neutronium cell), it would be interesting to hear if they did any measurement before/after replacing cables with wireless connectors.

**Comment by Sphyix** [comment]
> I don't understand why you want to change this though? What's the use case for it _other_ than going into a cleanroom? You're supposed to use the QB to go any real distance, and has the cost to match, if we make these things super easy to use, people won't use the appropriate method.

The use case is inside the base to avoid p2p, right now it's impossible to use them even inside a 8x8 chunks base
Now I totally overused them, but out of 1.78M eu/t, wireless is using 1.74
All of them are inside the 8x8 chunks range
![javaw_LvpagjXZve](https://user-images.githubusercontent.com/17811922/129577005-163ca314-aa06-41fd-9f74-d426a6b3cefc.png)

Now, the current cost is totally not justified, but I agree that making it linear is not a smart move cause it then makes the quantum bridges useless. I think the change should make them usable inside a base instead of the p2p, but unusable to go any further

> I never used many wireless connectors myself though, so if someone did (presumably with neutronium cell), it would be interesting to hear if they did any measurement before/after replacing cables with wireless connectors.

I rewired my entire base with wireless only and, if I remember correctly, I was around 2 amps EV when using cables and p2p
now with wireless it's close to 1 amp UHV

**Comment by repo-alt** [comment]
Eh, by "measured" I mean TPS impact...

**Comment by Prometheus0000** [comment]
> I rewired my entire base with wireless only

This is your problem. You're not supposed to do this. Which you agree with:

> Now I totally overused them

So I don't see why the cost should reduced still? You're supposed to use the regular cables. If you don't want to make cables everywhere you gotta pay the cost in power. Or not, if you have the NEC.

**Comment by Sphyix** [comment]
> > I rewired my entire base with wireless only
> 
> This is your problem. You're not supposed to do this. Which you agree with:
> 
> > Now I totally overused them

This is not my problem, they are unusable even for small bases
Going over 32 blocks costs 10k eu/t
at 48 blocks it's 24k eu/t
How do you expect to be able to sustain this without the NEC?

**Comment by repo-alt** [comment]
A bit of clarification: I don't object to anything I'm just trying to understand if there is a performance problem here or it is, like widening gameplay choices/esthetics thing?

**Comment by Sphyix** [comment]
I'll leave the performance issues to @boubou19 on the p2p, I believe there are some.
I'm just trying to explain that the cost is just nosense right now and restricting them to endgame only with a neutronium energy cell in the system

**Comment by repo-alt** [comment]
mm, so, no real reason then, just a choice.

**Comment by GTNH-Colen** [comment]
Well I was told they are better for TPS than spamming large cable networks, this was more a bonus than the primary point of my post though. I just think they cost way too much energy atm.

**Comment by repo-alt** [comment]
> Well I was told they are better for TPS than spamming large cable networks

Yes, and I'm trying to get down to the source of that information, because I don't see much reason for it, unless you e.g. trigger a toggle bus every second or something like that.

**Comment by botn365** [comment]
i also would like to know how much of a TPS inpact these have

**Comment by Prometheus0000** [comment]
BTW, I'm not opposed to it going down a little, I just think most of the use should be after you get the NEC, and only used when you really need to before that, as it's clear from how AE2 works that you're not supposed to wireless everywhere.

Also, if I'm reading the chart right, it sounds like a perfectly reasonable amount of power use. It's 255 EU for 16 blocks, which sounds cheap to me. Personally I wouldn't be upset if the limit was 16 blocks, but I never used them or had a large AE system to begin with.

https://www.reddit.com/r/feedthebeast/comments/3fr1f9/new_in_ae2_stuff_050_wireless_connector/ctr6xzk/
The author indicates it's for short range connections less than 19 blocks. So at 32 blocks you're supposed to use a QB. Or have a NEC.

**Comment by boubou19** [comment]
original intended use doesn't matter, what matters is what we want it to be used for. Do we want it to be useless before the neutronium energy cell? Do we want it to be dirt cheap so you spam them everywhere and make the quantum bridge only for interdim? Or do we want it to be for ~100 block max before the neutronium energy cell, making the quantum bridge attractive until the neutronium energycell?

**Comment by GTNH-Colen** [comment]
I mean we can always make it a piecewise function, my proposed one for < 300 blocks and then the exponential one for > 300 blocks for example.

**Comment by Prometheus0000** [comment]
Well, I'd say free (or almost) for 2 blocks for CR, 32EU for 8, 128EU for 16, 512EU for 24, 2048EU for 32, and then just cap it there. Maybe another version for after NEC that just uses 1M everywhere?

BTW, the graph says 32 is 1000, so where is 10K coming from?

> Going over 32 blocks costs 10k eu/t

**Comment by GTNH-Colen** [comment]
I really don't like the idea of capping the distance, that seems to go against the point of the thread which is to make them more usable not less?

**Comment by boubou19** [comment]
when i say ~100 block max, it means that the consumption start to become an issue, not a hardcoded limitation.it would be a poor way of nerfing it

**Comment by Prometheus0000** [comment]
The name is "Change formula of the wireless connector", not "Make the wireless connector way cheaper so people use it constantly, and not the QB".

> However this grows extremely quickly and quite frankly is really just not practical to use on a large scale before having access to the AE Neutronium creative energy cell. Therefore I would suggest a change to the following formula:

The thing is here, _you want people to use it on a 'large scale'_, and I want people to _only use it when needed_. Until you have the NEC, at which point, I say go ahead and do whatever.

**Comment by Sphyix** [comment]
> BTW, the graph says 32 is 1000, so where is 10K coming from?
> 
> > Going over 32 blocks costs 10k eu/t

Tested it ingame on delta

**Comment by GTNH-Colen** [comment]
My graphs are rough estimates, they do not include the config multipliers or the base EU amount. This is probably why it's showing so high. My main point was to show the rate of growth, not an exact numerical figure

**Comment by sintken** [comment]
anecdotal evidence only, but i recently rebuilt my AE system to use about 250 wireless connectors instead of ~100 p2p connections and removed ~400 blocks of cabling, and it gave a minor but noticeable tps increase and a major fps increase.

**Comment by laquazi** [comment]
> <img alt="Screenshot 2021-08-16 at 13 00 58" width="252" src="https://user-images.githubusercontent.com/54497873/129560490-4a88059b-e3b7-4018-8351-4fc086ba8d42.png">
> 
> Edit as you please: https://www.desmos.com/calculator/6naw2nsi7f

just wanted to point out that desmos uses base 10 log, not base e that PR implements. so for example in this case g(3000) ≈ 48038
