### ISSUE TITLE
Disassembling chest yields more than it should

### ISSUE THREAD

**Issue by dipo33** [GTNewHorizons/GT-New-Horizons-Modpack#8418]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
LAN world

#
#### What did you try to do, and what did you expect to happen?
I have disassembled a chest and expected it to yield 8 wooden planks

#
#### What happened instead? (Attach screenshots if needed)
It yielded two wooden logs and two wooden planks, which is not the cheapest variant, since it's basically 14 planks, while 8 planks is enough to assemble a chest

#
#### What do you suggest instead/what changes do you propose?
I suggest it to yield 8 planks instead to prevent grinding wood, because that's the cheapest variant

#
#### What is your GTNH Discord username?
Dipo#3713

**Comment by repo-alt** [comment]
Disassembling chest..., sounds like what a QA engineer would do
