### ISSUE TITLE
Search in thaumonomicon does not work

### ISSUE THREAD

**Issue by Evil1ck** [GTNewHorizons/GT-New-Horizons-Modpack#8419]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
I try click to search bar in thaumonomicon and write something.
#
#### What happened instead? (Attach screenshots if needed)
Nothing happens in response. Search bar is not clickable.
https://gyazo.com/aea6bf24d9257dbbfdae4bb106f06c7d
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
Murzik#9472

**Comment by GTNH-Colen** [comment]
I've noticed this occurring as well on occasion. Not sure what triggers it but definitely something that happens time to time.
