### ISSUE TITLE
Suggestion: AE2 Crafting Storage Recycling

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#8420]
#### Which modpack version are you using?
2.1.1.1a
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Would like to see some way of recycling AE2 Crafting Storage or an upgrade path for them.
#
#### What is your GTNH Discord username?
shawnbyday

**Comment by Prometheus0000** [comment]
What? Just remove the cell and put another one in?

**Comment by repo-alt** [comment]
There is no cell in crafting storage. Indeed this request makes sense.

**Comment by Prometheus0000** [comment]
? All of them have a cell in them?
![image](https://user-images.githubusercontent.com/8517039/129638442-15391194-4654-4c8a-9997-39f815b399b9.png)
As for the one without anything in it, I don't see the point, as unless you craft 100+ of them, you'll always want more eventually, and if you did this, it's your own fault.

**Comment by repo-alt** [comment]
AE2 registers disassemble recipes for the crafting storage (there is a config setting "EnableDisassemblyCrafting")  but I guess we nuke them somewhere in Minetweaker script

**Comment by repo-alt** [comment]
Oh, except we don't. Ok, this can be closed then.
