### ISSUE TITLE
Prospector functionality broken & needs improvement

### ISSUE THREAD

**Issue by Cleista** [GTNewHorizons/GT-New-Horizons-Modpack#8421]
# Which modpack version are you using?
2.1.1.0

# If in multiplayer; On which server does this happen? 
Private server I run

# What did you try to do, and what did you expect to happen?
Scan with Prospector Scanner & Electric Prospector to see nearby ores 

# What happened instead? (Attach screenshots if needed)
1. Unlocalized ore names are shown
![image](https://user-images.githubusercontent.com/67157844/129797742-67b9b6cb-c1f3-4980-a3d1-c2256aa0dcf9.png)
Occurs with both one-time-use scanner and the rechargeable electric scanner. 

2. Electric scanner shows small ores even when mode is set to "Ores" without small ores. 
![image](https://user-images.githubusercontent.com/67157844/129798206-2c5325d7-138c-47b1-90fd-9b15167516ee.png)

# What do you suggest instead/what changes do you propose?

1. Fix localization (and possibly implement better formatting as previously suggested):
![image](https://user-images.githubusercontent.com/67157844/129798016-23ff1fad-6384-4fd4-935b-e6514810e708.png)
2. Either remove Small Ores mode or make Ores scan not show Small Ores

# What is your GTNH Discord username?
Cleista#7481

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8092

**Comment by repo-alt** [comment]
Actually, only first part is dulpicate
