### ISSUE TITLE
Reinforced Glass recipe

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8425]
#### Which modpack version are you using?
v2.1.1.0 and v2.1.1.2
#
#### If in multiplayer; On which server does this happen? 
single and multi
#
#### What did you try to do, and what did you expect to happen?
I was trying to use Carbon Plate to craft Reinforced Glass.
#
#### What happened instead? (Attach screenshots if needed)
In v2.1.0.0, the recipe existed, but in v2.1.1.0 and v2.1.1.2, it did not.

・v2.1.0.0
![2021-08-19_08 40 58](https://user-images.githubusercontent.com/40425798/130006660-1b8f65b2-9357-4495-a39d-d7d13a65d5af.png)
・v2.1.1.0 and v2.1.1.2
![2021-08-19_13 15 23](https://user-images.githubusercontent.com/40425798/130006758-c1a944fa-6c57-4c26-88a3-659fa0819032.png)
#
#### What do you suggest instead/what changes do you propose?
fix it
#
#### What is your GTNH Discord username?
yukieiji

**Comment by Dream-Master** [comment]
code is thisll there but not shown. Need check why it not working

```            case "plateAlloyAdvanced":

                GT_ModHandler.addAlloySmelterRecipe(
                        GT_Utility.copyAmount(1L, aStack),
                        new ItemStack(Blocks.glass, 3, W),
                        GT_ModHandler.getIC2Item("reinforcedGlass", 4L),
                        400, 4, false);```
