### ISSUE TITLE
Disassemble FieldGenerator dupe

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8426]
#### Which modpack version are you using?
v2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
multi
#
#### What did you try to do, and what did you expect to happen?
Craft FieldGenerator with Assembler and disassemble it.
#
#### What happened instead? (Attach screenshots if needed)
dupe materials

Materials that duping in one cycle
・LV FieldGenerator : +2 Red Steel
・MV FieldGenerator : +2 Tungsten Steel
・HV FieldGenerator: +4 Niobium-Titanium
・EV FieldGenerator: +4 HSS-G
・IV FieldGenerator: +6 HSS-S
#
#### What do you suggest instead/what changes do you propose?
fix it
#
#### What is your GTNH Discord username?
yukieiji

**Comment by Prometheus0000** [comment]
Where are the metals coming from though, the wires?

**Comment by GlodBlock** [comment]
it is the metal plates. the disassembler return the material accroding to the crafting table reipe, but assembler recipe only use half of the metal plates compared with crafting table reipe.
