### ISSUE TITLE
NEI tooltips are obscured by potion effects

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8430]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
mmcc [GT]
#
#### What did you try to do, and what did you expect to happen?
I was trying to look at the cleanroom controller's tool tip in NEI (which is different than when built, but the Fire Resist aura box overlapped it making it hard to read.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/533931/130252235-131a3993-4ec4-4b03-956a-231a0792cb87.png)
I had to wiggle around to determine what it said (or take off my backpack)
#
#### What do you suggest instead/what changes do you propose?
NEI/item tooltips should overlap most if not all the UI
#
#### What is your GTNH Discord username?
bombcar

**Comment by Prometheus0000** [comment]
This is a duplicate, and a known issue, though I can't find the ticket at the moment.

**Comment by repo-alt** [comment]
Because there wasn't. Fix is in 2.1.1.1a
