### ISSUE TITLE
GT Cover Configuration Copy Paste Tool

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#8433]
I suggest adding an item that will let you copy configurations of covers and paste them onto others. I don't think this will be too tricky to implement although correct me if I'm wrong.

It's really annoying when building hundreds of turbines to setup each fluid regulator individually, would be very useful to have a copy paste tool (for other applications too obviously) I tried searching for it on the github and asking around on discord, I couldn't find anything that does this and I couldn't find anyone suggesting this before.

**Comment by leagris** [comment]
Instead of another tool, I'd see left-clicking with a cover on a placed cover of same type would copy the settings in the cover item.

**Comment by hucking** [comment]
yeah not necessary to add a new tool to do this, can add the functionality to existing tools or as u say just left clicking or whatever

**Comment by hucking** [comment]
although I will add as it stands I don't believe covers keep their information when removed so this wouldn't really work in the exact way you have described it, the information would have to be stored somewhere.
