### ISSUE TITLE
Removing fluids from machine inventory with partially-filled cells leaves a ghost fluid

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/GT-New-Horizons-Modpack#8435]
#### Which modpack version are you using?
2.1.1.2

![image](https://user-images.githubusercontent.com/16054364/130347472-41ae8c28-ba93-4d79-8e61-1b66193cf277.png)

If you try to remove fluids from an inventory using a large fluid cell that is partially full, it will leave a ghost fluid in the machine.

![image](https://user-images.githubusercontent.com/16054364/130347496-c4954403-b76f-4673-bf6b-17be77a2e3f1.png)

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/645
