### ISSUE TITLE
Blood-soaked thaumium block recipe only accept thaumcraft version of thaumium blocks

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8436]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

I wanted to craft some blood-soaked thaumium blocks with GT thaumium block version, expected it to work normally.

### The Reality

Only thaumcraft version works:
![image](https://user-images.githubusercontent.com/12850933/130355688-7977fe54-6fbd-48b7-9f07-557d8fb355df.png)

### Your Proposal

Looks like it should default to GT thaumium block version or accept oredict. The item is from the NH core mod.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Which block do you get out of the compressor when making thaumium blocks though? I changed the others so you wouldn't have to chisel it, but I forget which you get. Also, the BS version texture doesn't look like the GT texture.
