### ISSUE TITLE
NEI Addons fork from Bdew github

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/GT-New-Horizons-Modpack#8437]
### Your GTNH Discord Username

Usernm#4396

### Your Pack Version

2.1.1.0

### Mod Name

NEI Addons

### The Mod to Add

In fact mod already in modpack. 

### Your Reason

I want to suggest fork nei addons mod from bdew github. I make small feature to add stack size with fake item in pattern terminal. And want to pull request this feature in gtnh modpack.

Now if you open pattern terminal, switch pattern mode to processing and take fake item from nei with middle mouse button you only can put items in empty slot or replace one items to other. 

With this feature you can take one fake item from nei. When you click with this item on slot in pattern terminal where you already have same item stack size adds. 
For example we have oak log in first slot and take fake oak log from nei. When we click we have 2, 3, 4 and so on items in slot. 

[commit](https://github.com/Usernm0/neiaddons/commit/99233cac7afd47de53f4a52deb74116cdca356e9) - to see what i add. 

### Preliminary Investigation

.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by GTNH-Afx237v7** [comment]
That feature was just implemented in NEI recently...

**Comment by Usernm0** [comment]
Just fork and build latest gtnh nei version, this feature not implemented. And this feature not work at all without nei addons.

**Comment by GTNH-Afx237v7** [comment]
Implemented here:
https://github.com/GTNewHorizons/NotEnoughItems/pull/150
a bit buggy currently, a fix PR has been sent and is awaiting review by Mitch

**Comment by Usernm0** [comment]
This PR just always show nei quantity item field. It helps with ae patterns, but not implement left click feature.
