### ISSUE TITLE
Infinity cheese

### ISSUE THREAD

**Issue by Peytob** [GTNewHorizons/GT-New-Horizons-Modpack#8447]
### Your GTNH Discord Username

Peytob#8767

### Your Pack Version

Newest: 2.1.1.0

### Your Server

My own local server

### Type of Server

Multiplayer LAN

### Your Expectation

I eat cheese. The cheese disappears from the inventory. How does a self-respecting good cheese make.

### The Reality

I eat cheese. The cheese does NOT disappear from the inventory. I made a small video showing all my actions and their results. Here is the link to youtube: https://youtu.be/FQM47qe0-44

### Your Proposal

I think that something is wrong in the processing of cheese-eating events.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I encounter something like this with many foods if they are eaten but not in the lunch pail first. The eat appears to work but then reverts and the item reappears in the inventory. It doesn’t seem to actually work.

**Comment by Peytob** [comment]
> 
> 
> I encounter something like this with many foods if they are eaten but not in the lunch pail first. The eat appears to work but then reverts and the item reappears in the inventory. It doesn’t seem to actually work.

Maybe I should make a list of all the broken food and try to formalize the moment when the bug appears? I think this would help the developers. However, it is necessary to formalize the actions for the food dupe. Sometimes it doesn't appear again

**Comment by Skiftcha** [comment]
iirc it is because eating time on server is longer than on client
hold eating key longer and it will be actually consumed

**Comment by Prometheus0000** [comment]
Does SoL have a different config for client and server or something? Or does something else mess with how long it takes to eat something?

> Multiplayer LAN

Reproduce it _without_ this (SP, normal MP), this is _not_ supported as it's incredibly buggy.

**Comment by Peytob** [comment]
> 
> 
> Does SoL have a different config for client and server or something? Or does something else mess with how long it takes to eat something?
> 
> > Multiplayer LAN
> 
> Reproduce it _without_ this (SP, normal MP), this is _not_ supported as it's incredibly buggy.

In my case , SoL is 8 at server and client, I don't know about other players.
In the singleplayer, i can't repeat the error. I'll try it on the official servers a little later
Let me clarify: my client and server work on the same computer.

**Comment by bombcar** [comment]
I wonder if this possibly has to do with the eating time change between eatings of the same item. The first takes five seconds - the second will take longer because of SoL (I believe it does this) but the client may not have received that and thinks it will still take five.

**Comment by 04Slash** [comment]
I have the same issue in single player. Tried with both 2.1.1.0 and 2.1.1.2-dev. I tried holding down eat for a good 20 seconds and it still didn't eat it (tps is fine, I don't even have machines yet). Placing it within the Lunch Box then eating it did actually eat it though.
