### ISSUE TITLE
Server config folder collision  (Case Sensitive)

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8452]
### Your Pack Version

2112

### Your Server

priv

### Your Expectation

config folders should not collide even when running the server from windows or linux

### The Reality

Got duplicated folders:
GalacticGreg
galacticgreg

LootGames
lootgames
![kép](https://user-images.githubusercontent.com/7230430/130664178-b65cd54f-c50f-46ea-b0e0-bd151a1043f3.png)

### Your Proposal

fix the folder names, always use case sensitive paths and names

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I can verify this going forward but previous installs could have it forever
