### ISSUE TITLE
Vanadium Pentoxide dust recipe

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8454]
### Your Pack Version

2112 - dev

### Your Server

priv

### Your Expectation

Creating Vanadium Pentoxide dust in a blast furnance has worng recipes.
Withouth o2 gas and less heat capacity it gives 5x more output making the second recipe useless

### The Reality

![kép](https://user-images.githubusercontent.com/7230430/130786283-3bed1ac3-2ad3-4ec3-82df-711f69d2c18b.png)

### Your Proposal

Swap the outputs and make the conf2 recipe produce a single dust while conf24+o2 makes 5 dusts

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
because bot and i both register the vanadium pentoxide separately, and we add the different recipe for it.
