### ISSUE TITLE
Show Quests Locking tabs in questbook

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#8460]
### Your GTNH Discord Username

ALongStringOfNumbers

### Your Pack Version

2.1.1.0

### Your Proposal

I am putting this here because issues are off on the Better Questing Repo.

For tabs in the questbook that are locked behind certain quests, I would like there to be a hover box that displays the quest that locks the tab that is displayed when hovering over the locked out tab in the questbook.

This came about because I was going through the HV tab in the questbook and unlocked the `Dimensional Goal: Moon` quest in that tab, which said to refer to the `Space Race` tab for more information. However, the `Space Race` tab was still locked, and I had no idea what quest was required to unlock the tab, so that I could look for the information.

Adding a hover when hovering over the locked tab with the quest that unlocks the tab would have helped me know in what direction I need to focus my efforts so that I could get the tab unlocked.

### Your Goal

To better guide players through the tiers of the questbook, and help them understand what requirements they need to unlock a specific tab in the questbook.

### Your Vision

It would make the progression through the questbook easier to understand, as players would know where they need to focus their efforts to unlock certain tabs in the questbook.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Yeah, sounds more like inappropriate quest text or incorrect quest prereq than a missing feature.

**Comment by bombcar** [comment]
View mode, when implemented, would probably solve this. And if you know the name of the first quest on the tab you can back search it already.

**Comment by boubou19** [comment]
view mode is implemented. let me know if it wasn't what you asked for, i'll reopen the ticket
