### ISSUE TITLE
Wrong quest text regarding the dislocation focus.

### ISSUE THREAD

**Issue by Mattery** [GTNewHorizons/GT-New-Horizons-Modpack#8462]
### Your GTNH Discord Username

Mado#8340

### Your Pack Version

2.1.1.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

After reading the text on the quest i was led to understand that the dislocation focus was able to move aura nodes.

### The Reality

The dislocation focus is not capable of moving any node on 1.7.10 as that capability was later added into Thaumic Tinkerer for 1.12.2, the text in the quest was copied from the FTB wiki and that only applies to the latter.

### Your Proposal

Replace the text for something like: "Wand Focus: Dislocation allows the user to take and place any blocks, even some Tile Entities and things usually unobtainable, like spawners, planted IC2 Crops, and others. (It can't move Aura Nodes or Energized Nodes)".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by MaxLunar** [comment]
Hasn't it already been fixed by #8139 ? Anyway, you can't move regular, non-energized nodes, and definitely can move energized ones, but be careful as the game counts that as breaking the node, thus causing a huge flux explosion around.
