### ISSUE TITLE
Cranberry Juice and Fruit Punch recipe conflict

### ISSUE THREAD

**Issue by 04Slash** [GTNewHorizons/GT-New-Horizons-Modpack#8463]
### Your Pack Version

2.1.1.0

### Your Server

SP

### Your Expectation

I tried to make Cranberry Juice
![](https://i.imgur.com/BhE3213.png)

### The Reality

But got Fruit Punch instead
![](https://i.imgur.com/hVk1r2U.png)

### Your Proposal

A similar issue appeared in the past (#7166). Much like the other issue, this conflict does not always happen and it seemed to have temporarily "fixed" itself by exiting the world and rejoining. The solution from the previous issue seems to have been removing sugar from the recipe. The below does exactly that and doesn't cause any further issues.

`recipes.remove(<harvestcraft:cranberryjuiceItem>);`
`recipes.addShapeless(<harvestcraft:cranberryjuiceItem>, [<ore:toolJuicer>, <ore:cropCranberry>]);`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Try the latest version to see if it's fixed there. I'm not sure if it is, but it might be.

**Comment by 04Slash** [comment]
I tried with 2.1.1.2-dev and the same issue occurs.
