### ISSUE TITLE
Add a Type filter presist for siftable purified ore 

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8465]
### Your GTNH Discord Username

Shibva#3140

### Your Pack Version

2.1.1.0

### Your Proposal

Im suggesting that a new type filter setting to be added that will only allow for any purified ore thats a crystal (or something that be uses in a sifting machine) to pass though and not other types of purified ore that are not usable in the sifter

### Your Goal

It would be a nice feature for automating resoure processing

### Your Vision

I think we have all been there with the anoyance of trying to mass process stuff and not being able to properly Sift out purified ore that can be used in the sifter without having a build up.

In the set up that I have I have a mode that is supposed to process siftables but am unable to have it where a buffer can be added wtihout it filling up with unsiftable and then being unable to extract the non-usable ones without taking the ones that can be sifted out as well. Adding this will fix this problem and may open some doors to better mass-resource processing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SteamDoge9000** [comment]
yes, ik this is a dupe #7277 but it has gone stale and something like this would be a handy thing to have in a type filte; after all, its purpose to filter out certain items from a pool of them for machines to work with

**Comment by Prometheus0000** [comment]
Read the rules, christ.
