### ISSUE TITLE
OC Robot cannot to interact with bee and frames in Industrial Apiary

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#8467]
### Your GTNH Discord Username

John S#7565

### Your Pack Version

2.1.1.0

### Your Server

Local

### Type of Server

Single Player

### Your Expectation

I try to remove Bee Queen, Bee drone, Apiary Upgrade from **Industrial Apiary** with robot, and it cannot to do it. He is see all the stuf but cannot to move it.

### The Reality

Robot cannot to take out stuff from Industrial Apiary.

### Your Proposal

Make that robot can interact with stuff in the Industrial Apiary.

The reason why i  think this is a bug is that at the tier at which Industrial Apiary become available(end of LUV+), and they material and Energy cost and complexity, they should be able to be automated **_at least_** with the robot.  It is unbalanced that in LUV - ZPM+ tier to have an automated BEE i should use only regular alvearies.

Thank you guys, team of GTNH, you're - the best!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Why do you want to remove a *Queen*? To my knowledge no beehousing support removing queens through any means. I'd be pretty surprised if you can do it via OC.

**Comment by Retster** [comment]
> Why do you want to remove a _Queen_? To my knowledge no beehousing support removing queens through any means. I'd be pretty surprised if you can do it via OC.
Because automation reason, when i not need production from queen in alveary why i cannot to move it out? It's much more convinient to have posibility to replace it with another bee in any time. Also you can do it manually, why hi-tech and wery smart robot is hould not to be able do that simple task?

**Comment by repo-alt** [comment]
Yes, I think at least alveary and industrial apiary should allow that

**Comment by repo-alt** [comment]
Looks like the only good way to implement that is adding some kind of "bee keeper" robot upgrade

**Comment by Retster** [comment]
> Looks like the only good way to implement that is adding some kind of "bee keeper" robot upgrade

That's would be good solution. And also, if it's posible, to add to this upgrad possibility to scan bee nbt(full genome code).

**Comment by repo-alt** [comment]
There is quite a bit of information in bee NBT, what kind of information do you need (imagine LUA table you receive)

**Comment by repo-alt** [comment]
[OpenComputers-MC1.7.10-1.7.5.14-GTNH+3311876b4-universal.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7161389/OpenComputers-MC1.7.10-1.7.5.14-GTNH%2B3311876b4-universal.jar.zip)
Version for testing. When/if this PR will be merged, it would be necesserary to add a recipe for the upgrade (to GTNH core), perhaps the same as for geolyzer, just with a beealyzer as a component

**Comment by repo-alt** [comment]
API reference: 
```
swapQueen(side:number):boolean -- Swap the queen from the selected slot with the apiary at the specified side.
swapDrone(side:number):boolean  -- Swap the drone from the selected slot with the apiary at the specified side.
getBeeProgress(side:number):number -- Get current progress percent for the apiary at the specified side.
canWork(side:number):boolean -- Checks if current bee in the apiary at the specified side can work now.
analyze(slot:number, honeyslot:number):boolean (slot:number, honeyslot:number):boolean -- Analyzes bee in the slot, uses honey from the second slot.
addIndustrialUpgrade(side:number):boolean -- Tries to add industrial upgrade from the selected slot to industrial apiary at the given side.
getIndustrialUpgrade(side:number, slot: number):table -- Get industrial upgrade in the given slot of the industrial apiary at the given side.""")
removeIndustrialUpgrade(side:number, slot: number):boolean -- Remove industrial upgrade from the given slot of the industrial apiary at the given side.""")
```

**Comment by repo-alt** [comment]
[OpenComputers-MC1.7.10-1.7.5.14-GTNH+3311876b4-universal.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7162928/OpenComputers-MC1.7.10-1.7.5.14-GTNH%2B3311876b4-universal.jar.zip)
Next version for testiong. `analyze` fixed

**Comment by repo-alt** [comment]
[OpenComputers-MC1.7.10-1.7.5.14-GTNH+772d327ed-universal.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7164929/OpenComputers-MC1.7.10-1.7.5.14-GTNH%2B772d327ed-universal.jar.zip)
Version with bee species favorite temperature and humidity added

**Comment by repo-alt** [comment]
[OpenComputers-MC1.7.10-1.7.5.14-GTNH+ccdd48045-universal.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7165442/OpenComputers-MC1.7.10-1.7.5.14-GTNH%2Bccdd48045-universal.jar.zip)
Hopefully last testing version with species being properly represented by a table.
