### ISSUE TITLE
game crashes while stuck in a block

### ISSUE THREAD

**Issue by juisss** [GTNewHorizons/GT-New-Horizons-Modpack#8470]
### Your Pack Version

2.1.1.0

### Your Server

SP

### Your Actions

I was riding my horse when I got stuck in a tree log and my game immediately crashed. Everytime I rejoin the world it instantly crashes.

### Crash Report

https://paste.ee/p/68wP6

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ydrec** [comment]
Crash on item render, ways to fix
1. load backup, single player world have a button for it on world select screen
2. use nbtedit or mcedit to first move player away to see if its item in inventory or on ground, if crash continues clear player inventory either completely or seletively targeting items suspected to cause crash.
If cleared completely restore player inventory from backup

**Comment by juisss** [comment]
oh right.... backups. I really didn't think of them, thank you so much I thought my world was gone.
