### ISSUE TITLE
Fluid Storage/Carrying

### ISSUE THREAD

**Issue by xtake** [GTNewHorizons/GT-New-Horizons-Modpack#8472]
### Your GTNH Discord Username

Glueky#6757

### Your Pack Version

2.1.1.0

### Your Proposal

I have two suggestions.

1. **Larger Fluid Storage** 

There are people with Hundreds of Billions of Fluids (1 Trillion Oxygen Colen). There should be a better way to store it then spamming full bedrockium drums into super chests. 
Either an Ultimate Quantum Tank (2^63 Liter) or a tiered multiblock (Better then TFFT which is only 16B max).

2. **Higher Tier Hand Pumps** (_And OFC moving it to out of G++ to Obama_) or **partially able to full fluid cells/drums**

If I have to move like 40 smth M Liter I usually use 1 32M Cell some 2M cells some drums and handheld fluid pumps.
Would be great if there was higher tier then HV (EV parts) Handheld pump. (UEV maybe 65M so you can carry bedrockium drums and 1 handheld pump and easily carry stuff over)
Or just the ability to partially fill fluid cells/drums for moving, when you put them in a super/quantum tank (Or right click the tank)

 

### Your Goal

1. There are people who don't like voiding gases even if they have WAY too much
2. Just nice QoL, less hassle 

### Your Vision

Fluid handling would be made a lot easier for late game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Colen** [comment]
I do agree the quantum tank is pretty useless honestly, it costs UEV circuits and you only get 2B L storage. The cost/benefit ratio just makes it totally worthless, expanding on the logic and adding a new tank tier with 2^63 storage seems reasonable and probably quite easy technically speaking as it's just a bigger internal number.

In regards to the hand pumps yea, I do find myself often having to use multiple tiers of cells of descending tier just to empty a larger tank. I don't see the issue with having a hand pump that is much larger and just more expensive but we do need to probably do this part in Obama as GT++ is going anyways.

The code for both of these things already exists, just a matter of expanding it to higher tiers.

**Comment by Prometheus0000** [comment]
What about changing the TFFT so that it holds more fluid, and has more tiers? As it is it seems kind of useless, but this could be a use for it, and it's more interesting than just a larger container.

**Comment by bombcar** [comment]
If super tanks become useless at high tiers make the high tier ones dollyable

**Comment by Prometheus0000** [comment]
? What are you talking about? Just make an osmium cell, they hold the same amount, don't they? Why would dollying help? Also, I don't think the point is portability to begin with, instead colen is talking about the cost for how much storage you get.

Also, I don't think you can just increase the number, it's already at the max for the type, so you would have to change that, and that might mess up other stuff that interacts with it.

**Comment by bombcar** [comment]
Fair point - I really do like the look of the rail craft steel tanks with windows - giant tanks full of liquid look really cool. Maybe I should take a look at rail craft tank code and see if it could be tiered up (is rc source avail?)

**Comment by Prometheus0000** [comment]
It is not, It's ARR. Not to mention it eats cells.

**Comment by Glease** [comment]
> handpump something

We have this pick fluid via GUI feature built into literally every GT based tile entity. Dunno why you still need hand pump.

> arr railcraft

It's CJ's own license, neither freeware nor arr. It does forbid distributing derivates, but it definitely is not ARR.

**Comment by bombcar** [comment]
> We have this pick fluid via GUI feature built into literally every GT based tile entity. Dunno why you still need hand pump.

Only thing I need hand pump for anymore is taking the last drops of fuel out of a combustion engine. Cells don't work there.

The only other multi block I know of that "shows its contents" is the GT++ ore washer - are there others?

**Comment by Glease** [comment]
> Only thing I need hand pump for anymore is taking the last drops of fuel out of a combustion engine. Cells don't work there.
![ignorance](https://user-images.githubusercontent.com/4586901/131560188-7f8341ec-aa48-4fb3-8d5f-e3db91ac7afe.gif)
No comment.

**Comment by Glease** [comment]
> Larger Fluid Storage
 Now implemented in the form of yotta tank and high tier RC tank.

> Higher Tier Hand Pumps (And OFC moving it to out of G++ to Obama) or partially able to full fluid cells/drums
As I said before it's already implemented before this issue is made.

---

Marking as FixedInDev now as these requests are all satisfied somehow.
