### ISSUE TITLE
Add Fluid Hatch Prioritization

### ISSUE THREAD

**Issue by General-Ike** [GTNewHorizons/GT-New-Horizons-Modpack#8475]
### Your GTNH Discord Username

Commander Crankshaft

### Your Pack Version

2.1.1.0

### Your Proposal

I think it would be a great addition to add an option to prioritize a specific fluid input hatch for multiblocks. The input hatches could screwdrivered to set priority as they do not yet have a screwdriver function (defaults to no prioritization as they function now, each time you hit it, you increase priority). Or you could put a programmed circuit in input hatches and if given the option between a recipe with a fluid from either hatch, it would always prioritize any hatch with a circuit, and always from the hatch with the lower (or higher) numbered circuit.

### Your Goal

There are some recipes that have multiple fluid options, with one fluid being more expensive than the other, but offering some benefit, like higher tier rubbers/plastics/soldering materials costing less fluid than their lower tier options, or higher tier gases decreasing smelt time in the EBF.

Currently, it is not apparent how fluid hatches are prioritized; my experimentation has shown that it prioritizes based off of the last used fluid, I have not yet discovered more details. The goal would be to allow a person to use multiple of these fluids in the same multiblock and prioritize one fluid over another based off of their needs. So someone with huge amounts of generic Rubber could prioritize that fluid whenever it is an option while still using the higher tier rubbers to make the cables as required. Or do same with say Polyethylene over PBI for making hatches/buses.

### Your Vision

Players would be able to make a single multiblock dedicated a group of parts, be they machine hulls, cables, circuits, or EBF ingots, and provide all the fluids necessary to the machine, allowing the player to easily make decisions for which fluids to be used first, rather than fighting to know how priority is assigned, giving up, and creating multiple machines or just ponying up and only using the more expensive fluid for the convenience.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Another implementation that would work would be to allow "locking" input hatches the same way output can be - and then used locked hatches first if possible

**Comment by Prometheus0000** [comment]
Why can't you use a fluid filter cover?

**Comment by Pxx500** [comment]
> Why can't you use a fluid filter cover?

Isn't the issue about prioritizing fluids that are already in hatches?

**Comment by Prometheus0000** [comment]
I see, I just skimmed it before. This seems pointless then. And removing the mechanic of not shoving all fluids into 1 MB makes it less interesting.

You should instead focus on increasing your production of EBF gasses or using a lower tier one. For soldering, I can't imagine people using anything other than soldering alloy unless they're lazy (and honestly non-SA options shouldn't even exist). For rubber, you should just make the one that's easiest for you to make and/or alternate machines/recipes if you really want to make both. And later on you can't even use normal rubber for higher tier parts anyway, so you can just dump it or use it only on LV stuff if you need to make it.

**Comment by Glease** [comment]
While the usecase is a bit rare here, it does let player control the previously undeterminstic input consumption order.

> And removing the mechanic of not shoving all fluids into 1 MB makes it less interesting.

Don't quite get what you mean here.

**Comment by Prometheus0000** [comment]
If you can just shove all the EBF gasses into 1 EBF and then prioritize it, that make it less interesting than having different EBFs for different gasses. Like how removing voiding on MBs would make it less interesting for RS setups, which wouldn't even be needed any more.

**Comment by General-Ike** [comment]
The main use I imagine is for rubbers/plastics for cables/hatches & buses. I know many people will continue to use low tier when possible because they have so much, myself included. As for the soldering fluid, someone could pump lead from off-planet and only use SA when the recipe demands it (I know someone who did this), though I do also agree that only SA should be useable (it would clean up NEI if nothing else).

> If you can just shove all the EBF gasses into 1 EBF and then prioritize it, that make it less interesting than having different EBFs for different gasses.

People already don't have EBF's for different gases, because you can choose a single gas of each "type", and only one recipe exists for each dust in the EBF. Though for the EBF, it's a bit of a corner case, but I specifically imagine being able to prioritize a nitrogen hatch, allowing a blast furnace to create glowstone doped boules without circuit type 1 turning silicon into ingots (a problem that I had to address). Or prioritizing argon to cook the europium boule (I think that's what it is) without your regular ingots consuming the radon.

> Like how removing voiding on MBs would make it less interesting for RS setups, which wouldn't even be needed any more.

Unlike RS to stop MB's from voiding, being required to make twice as many machines to use 2 different kinds of materials is not any more interesting, just more tedious.
