### ISSUE TITLE
Update/recreate reauth to work with Microsoft accounts

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8477]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Proposal

Players with migrated accounts are forced to reload the pack, while the mojang account owners can still use reauth.

### Your Goal

Soon enough, it'll impact every player, so might be good to plan it ahead.

### Your Vision

Sadly the code is ARR, but here is the repo of the mod: https://github.com/TechnicianLP/ReAuth/tree/1.7

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Colen** [comment]
We have around a year until this is compulsory for all MC accounts so while it's not necessarily urgent at present I agree this does need to be properly looked at.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8593
