### ISSUE TITLE
Robot arms can be used to import batteries into batbuffs

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8479]
### Your Pack Version

Stripped test build, I forget which version

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

No batteries moved

### The Reality

Battery was moved from chest to bat buff

### Your Proposal

Batbuffs are not supposed to allow I/O, so this should be prevented.

This also works in the charger and turbo charger (had to change the adjacent setting for the latter).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
Ohh no :-(

**Comment by MMunier** [comment]
Why did we tell him 😢 ^^

**Comment by Savallator** [comment]
But it is not that bad because output does not work, one would have to use a wrench to get the batteries out

**Comment by Savallator** [comment]
But honestly, it would be nice if only Batteries would be forbidden for this (Like, only items that can be discharged), so you could still automate charging of tools etc? Or is there some other way for tools apart from the wireless charger?

**Comment by Prometheus0000** [comment]
See https://gtnh.miraheze.org/wiki/Wrench_Cooled_IC2_Fission_Reactor for what people will do.

It's doubtful this is really worth it, but better to fix it so as not to confuse people that it should be possible and they're doing it wrong.

**Comment by Prometheus0000** [comment]
The charger or turbo charger might allow other item I/O, I haven't tested.

**Comment by Pnc6lx** [comment]
i think it is for disposable battery, like Hg and Acid batteries. and empty batteries is the only thing can be output from batbuff

**Comment by repo-alt** [comment]
I don't see any bug here tbh. Batbuffs are not supposed to _output_, except, as stated above, for empty acid batteries

**Comment by Prometheus0000** [comment]
Should we just leave it as is then? Worrying about someone coming up with a wrench contraption is probably pointless, so the main point is whether people will get confused being able to input into them. Would some quest text explaining it be enough? I don't think there is any about I/O, personally, I didn't even know you could output disposable batteries.

**Comment by repo-alt** [comment]
I think it may be left as is.
(In GTNH acid batteries are a bit pointless, but in vanilla GT5 they were somewhat useful in LV/MV to recycle excessive sulfuric acid)

**Comment by Prometheus0000** [comment]
We already agreed it was ok to leave it as is? I just need to add some quest text.

**Comment by Prometheus0000** [comment]
I added some text to the batbuff text about this. Also, conveyors DID work.
