### ISSUE TITLE
Gregtech tools are broken (Harvest Level behavior)

### ISSUE THREAD

**Issue by Minepolz320** [GTNewHorizons/GT-New-Horizons-Modpack#8480]
### Your GTNH Discord Username

Minepolz320#9473

### Your Pack Version

2.1.1.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When we destroying block using wrong tool type block just get destroyed and leave no drop, even if tool has higher harvest Level

it means that harvest Level bonus must apply only on suitable block<->tool pairs  

for example if we try to break Coal Ore with using iron hoe that block just get destroyed and leave no drop, its  like we use bare hand
![Vanilla](https://user-images.githubusercontent.com/42765118/131547459-97a31798-ad74-4f4b-87cc-d528f49d4c7b.gif)

### The Reality

Couple updates ago Gregtech tools just doesn't mine any wrong type of block
but now something wrong and any tool can harvest stone, like it's now have Harvest level of (0=stone) 
![gtTool](https://user-images.githubusercontent.com/42765118/131547586-2cde7b84-97e5-4907-99b6-e4b0b7ccf693.gif)

![gtTool2](https://user-images.githubusercontent.com/42765118/131547591-ee2b15d9-f408-427f-83e0-5d828cac29ec.gif)

### Your Proposal

I propose to solve this problem by reverting the old behavior of the tools
because changing the behavior of the tools to the correct version (Minecraft's Vanilla Style) requires a lot of fixes in Gregtech code which will eventually break GT++
and any addon because Java Reflection :P

but maybe it's just me...

I made a couple of fixes to show how it should work
![Done](https://user-images.githubusercontent.com/42765118/131548319-73dff999-0af0-4399-a9d2-9d1bb507dd10.gif)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Sounds like something bart would love. Honestly I don't know why we reenabled them to begin with. Also, GT++ will be removed later.

**Comment by KiloJoel** [comment]
Issues with the Sense have existed for a long time, it used to be able to break bedrock. Is it just the Sense which has this problem or all tools?

**Comment by Minepolz320** [comment]
@KiloJoel all GT

**Comment by Minepolz320** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/2a8be34d86cf35ab6e77d4bdad84b3c26d53d432
and
https://github.com/GTNewHorizons/GT5-Unofficial/commit/1ed85c72f194d996ad3a1b44c0e74c9597b5326e#diff-d3aa7d3f14e914c1c677e5d05cc1373a08da90f2de728f11de4473d2eca2e0f4
