### ISSUE TITLE
[BibiloCraft]  Backport the "improved Clipboards" feature

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8484]
### Your GTNH Discord Username

Shibva

### Your Pack Version

2.1.1.0

### Your Proposal

To backport a 1.12.2 feature for the clipboard to render its contents like it does in 1.12.2 when in hand

![image](https://user-images.githubusercontent.com/38770780/131594273-bb6460a1-877b-4673-95a5-e9a5133fd11a.png)

### Your Goal

I think we all have been there with us needing to check out clipboard for things we set we need todo on it and are anoyed a tad when you have to open the GUI to see the content.

### Your Vision

By adding this feature back into Bibilocraft 1.7.10, it will be easier for people to keep their clipboard on them and be able to see what the current rendered contents of their list are.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SteamDoge9000** [comment]
on another note, this can be used to provide "sneek peaks" of new features and using the futionality of this clipboard with its render showing in hand can allow for information as used in the demonstration shots and feature shots that were shown on the bibilocraft home page

**Comment by bombcar** [comment]
“ Public distribution of modified versions of this MOD requires advance written permission of the OWNER and may be subject to certain terms.”

not quite ARR but possible at least in theory

**Comment by Dream-Master** [comment]
wich we don't have. I ask the dev allready and get no answer.
