### ISSUE TITLE
ME Level Emitters causing lag when checking external inventories

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8491]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.1.0

### Your Server

delta

### Type of Server

Thermos

### Your Expectation

Setting up passive automation with level emitters

### The Reality

Noticed lag peaks when setting up passive automation for solars.
Setup is using level emitters to stop production when the amount of materials needed is reached, all the machines output are going to an ender chest and then to an infinity chest
The infinity chest is connected to my main AE system with a storage bus set to extract only.
AE System is pretty big if that somehow matters(close to 200 interfaces, 60 64k disks, 3 infinity chests)

Setup:
![javaw_HDipjuZskV](https://user-images.githubusercontent.com/17811922/131747659-99d35f1c-bad8-421c-8498-36357c24fd16.png)
![javaw_0FGTRVcx13](https://user-images.githubusercontent.com/17811922/131748393-0f9b3d96-2b59-4105-b3fa-731d7bcc4fb7.png)
![javaw_eoBL5a2yRH](https://user-images.githubusercontent.com/17811922/131748335-e0ea77f4-55db-43da-a3f5-3091b3de0008.png)

My dim is 202, I'm normally around 18 to 20ms
![chrome_s1SOhITusC](https://user-images.githubusercontent.com/17811922/131748026-2647132d-b9fe-4b5d-9ca0-a80108da6437.png)

Warmroast
![](https://cdn.discordapp.com/attachments/775734555629584395/882737295613100042/unknown.png)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Sphyix** [comment]
After testing some more, this is not about the infinity chest itself, but most likely the big ME system that the level emitters need to check

I made a separate ME system with just the infinity chest and all the previous level emitters
![javaw_x075uvxY5H](https://user-images.githubusercontent.com/17811922/132119949-26171a42-bb0e-403f-a859-99e419d1f808.png)
This is not causing lag, might need to check warmroast but I can't see any ms differences in my base

**Comment by GTNH-Colen** [comment]
This kinda parallels the lag I've been seeing from these on eta, my AE is also pretty large. I'm not sure how much can be done about this, maybe @repo-alt can illuminate us.

**Comment by Methes** [comment]
Maybe an optional setting could be to only check selected inventory(ies).

**Comment by repo-alt** [comment]
Storage bus on an external inventory (like infinity chest) resets ME cache every time the chest contents change. Rebuilding the cache is somewhat expensive. It may be somewhat optimized by backporting new cache system from 1.16, but that is not a real solution. In the topic discussing higher tier ME cells recipes I advocated making them cheaper, exactly to avoid the necessity to use infinity chests in late game. I guess it is also possible to make dedicated "ME infinity chest" that would be not directly accessible from outside, like it was necessary to disable conveyors on the Quantum chests to make them not lag the system.

**Comment by boubou19** [comment]
243 slots with a 2B storage capacity seems very interesting, so if it could have the same AE compatibility as the Quantum Chests, would be top.

**Comment by Sphyix** [comment]
So to understand it correctly, if i push items in an infinity chest by importing them from the ME system cache shouldn't get rebuilt right?
And the lag was then caused by me pushing items in the chest with a gt pipe instead?

**Comment by repo-alt** [comment]
Well it triggers cache recet every time it receives `onNeighborBlockChange` notification. I think the chests triggers this notification every time it is changes, regardless of the way it is changed (pipe, storage bus, GUI)

**Comment by boubou19** [comment]
How hard would it be to avoid rebuilding the cache when the change is made via AE? because if AE does the change, then theorically AE knows what changed. That could eliminate quite a lot of lag issues due to AE. Also does it rebuild the cache of the whole AE or does it rebuild the cache of the storage bus?

**Comment by repo-alt** [comment]
Generic inventory handler keeps inventory cache in the form (slot -> stack), and it has no idea which stack will end up in which slot after insertion, or which stack will change after extraction.  When checking for changes, the handler iterates the target inventory slots and compares the contents to the cache. Note that target invetory may do anything with the received stack, like generify it, or delete (void chest). It is not impossible to write a more intelligent "chest" handler, but it should handle very specific tiles, because e.g. void chest may be an extension of the vanilla chest.

**Comment by leagris** [comment]
I like the idea of locked chest when it is connected to ME (even disallowing another ME to connect by making it an exclusive access). Not sure this is possible without changing chests code-wise though.

If it was possible to get exclusive use of chest by an ME, all requests to chest would be redirected to the ME, including player interaction with the ME connected chest.

**Comment by Sphyix** [comment]
I don't like the idea of a chest being accessible by only 1 ME system at a time.

Speaking about lag again, I saw lag only when using level emitters on the big ME system, so I still actually have to understand what's going on.
My changes to the original setup on the 1st post were to just move the level emitters on another system, and put a storage bus on the infinity chest.
So now infinity chest is accessible by both systems (the main one, and the level emitters one)
Now, the setup is not causing massive lag anymore, but both systems should rebuild cache like before?
![IfAjYhjr7R](https://user-images.githubusercontent.com/17811922/132262771-f2d93fe5-34da-4831-a0b1-286407aeb01b.png)

I still think there's something wrong with level emitters

**Comment by repo-alt** [comment]
When storage bus on the infinity chest posts update to the grid, level emitter receives the update notification, and requests the actual grid cache to check the level of the item it is configured to. If the connected grid is small, the grid cache is small too and fast to request. Global cache is also reset in this case, but cache rebuilding is lazy, so until someone (like level emitter) actually requests the cache, it is not rebuilt.

**Comment by Sphyix** [comment]
> When storage bus on the infinity chest posts update to the grid, level emitter receives the update notification, and requests the actual grid cache to check the level of the item it is configured to. If the connected grid is small, the grid cache is small too and fast to request. Global cache is also reset in this case, but cache rebuilding is lazy, so until someone (like level emitter) actually requests the cache, it is not rebuilt.

Now it makes a lot more sense, ty

**Comment by boubou19** [comment]
I think we still should make the infi chests behave the same as quantum chests, as it's the ultimate storage of the pack.
