### ISSUE TITLE
Menu music corrupt file

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#8493]
2.9+ is affected

![image](https://user-images.githubusercontent.com/50430417/132017871-99e8ab83-c9c5-4e08-acc2-72a25cb754da.png)
In a recent update menu3.ogg somehow became corrupted, and is a file that cannot be deleted or modified without the use of powershell.
This could prevent deleting the pack or cause other more severe problems.

To force delete this locally goto  .minecraft\resources\minecraft\sounds\music\menu and open powershell (shift+rmb)
then type remove-item menu3.ogg.
Bot confirmed this too.

**Comment by GlodBlock** [comment]
it is true that it is a corrupted file. but i can confirm it can be deleted it in normal way. maybe you should unzip the file and then delete it.

**Comment by Dream-Master** [comment]
nope we reduce filezize and add 0 kb files inside that not always will play the music. Not sure why menu 4not be 0k as well.

**Comment by Dream-Master** [comment]
lets remove this files better

**Comment by Glease** [comment]
Appears solved for 2.1.2.0.
