### ISSUE TITLE
[Art] I made a beautiful Bacterial Vat

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8495]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.1.0

### Your Server

delta

### Your Expectation

Made a bacterial vat with blocks that have a glass tier
Expected it to not form, as they are not really glass

### The Reality

![javaw_cHrEsGG0s6](https://user-images.githubusercontent.com/17811922/132091659-62cae92b-0fbe-4d73-a02e-7912b879ff39.png)
![javaw_4RDqiFzjlG](https://user-images.githubusercontent.com/17811922/132091661-5bf59873-d591-4cbd-8d30-cbe4b69322e4.png)

### Your Proposal

Limit the blocks that can be used in a bacterial vat

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Colen** [comment]
Weirdly I believe this was intended by bart, I recall being in vc with him when he made a bacterial vat out of magic mirrors from thaumcraft.

**Comment by Prometheus0000** [comment]
My understanding is that it's intended too. I'd still have no problem limiting it to borosilicate ones if people care though.

**Comment by Sphyix** [comment]
Well if that's actually intended, then i guess we can just close the ticket

**Comment by boubou19** [comment]
the issue comes from the fact that BW recognize these blocks as HV-tier glass blocks. And that makes no sense. Hopefully all of them are HV tier glass, except 1 that i won't post here because it allows severe tier skip for all the bartworks multis using the glass tier mecanic.

**Comment by Dream-Master** [comment]
Known issue. Bart show that this is possible a long time ago.

**Comment by GTNH-Colen** [comment]
The only reason I said it was intended was because of the bug label, however I do also believe this shouldn't really be possible as it makes absolutely no sense. No reason to extend support beyond borosilicate glass and maybe reinforced glass imo.

**Comment by basdxz** [comment]
This is not an issue, this is working as expected. 

Source: I have spoken to Bart when it was created and the original demo of the machine used thaumcraft magic mirrors with items bouncing along to make a liquid-forcefield to keep the fluids inside the vat. Cheers.

**Comment by Prometheus0000** [comment]
Yes, it's working as _currently_ intended, but that doesn't mean we won't change it. Because how do blocks that don't fully cover a space hold liquids in?

**Comment by GTNH-Colen** [comment]
> This is not an issue, this is working as expected.
> 
> Source: I have spoken to Bart when it was created and the original demo of the machine used thaumcraft magic mirrors with items bouncing along to make a liquid-forcefield to keep the fluids inside the vat. Cheers.

Yes I know, I was there as well but it makes absolutely no sense and really should be restricted to borosilicate glass along with perhaps a few others. I get what bart was going for, trying to allow any glass to be used but it's just way too broad in what it allows at present.

**Comment by bombcar** [comment]
Allow it to use the cleanroom list of glasses.
