### ISSUE TITLE
[BQ#1570] Uncorrect description in quest

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/GT-New-Horizons-Modpack#8497]
### Your GTNH Discord Username

ko5h#0024

### Your Pack Version

2.1.1.2

### Your Proposal

In quest for craft tormented twine u need **3 string**, 3 misfortune and 12 disturbed cotton
![](https://i.imgur.com/YsEolfJ.png)

### Your Goal

For recipe needed **3 blood burned string** from Blood Arsenal 
![](https://i.imgur.com/hDWIDCw.png)
its t2 BM altar
![](https://i.imgur.com/S4CJcBd.png)

### Your Vision

Change description and prerequire BM t2 altar

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
It was changed at some point.

**Comment by Dream-Master** [comment]
Yes i change the recipe when witchery extras was done.
