### ISSUE TITLE
[BQ#346] Get any poppet for complete quest

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/GT-New-Horizons-Modpack#8499]
### Your GTNH Discord Username

ko5h#0024

### Your Pack Version

2.1.1.2

### Your Server

private server

### Type of Server

Other MCPC+ fork

### Your Expectation

For complete quest u need craft Death Protection Poppet

### The Reality

But, any poppet complete this quest

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
I changed the quest, since it was impossible to check for only one type for some reason, even though they're different meta #s. I have no clue what's up with that, but now you'll only need the basic one.
