### ISSUE TITLE
[Witchery] Spinning wheel - secondary inputs

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/GT-New-Horizons-Modpack#8500]
### Your GTNH Discord Username

ko5h#0024

### Your Pack Version

2.1.1.2

### Your Server

private server

### Type of Server

Other MCPC+ fork

### Your Expectation

in NEI spinning wheel for 3 recipes u need 8 srting or 4 disturbed cotton or 4 wispy cotton
![](https://i.imgur.com/rrpwxxR.png)

### The Reality

![](https://i.imgur.com/b63WZ8S.png)
but, you only spend 1 each
![](https://i.imgur.com/GGaZLrX.png)

### Your Proposal

can replace the secondary ingredient with threads of gtnh core? silver & viteum thread not used in craft

or swap threads and cotton
![](https://i.imgur.com/Lbcuwyn.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
So we need to fix witchery extras
