### ISSUE TITLE
LCR wallsharing bugged in latest dev build

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#8501]
### Your GTNH Discord Username

Hucking#0193

### Your Pack Version

2.1.1.2

### Your Server

Jimmy Jammers

### Your Expectation

Before updating to latest dev build (we were on 2.1.1.0 before updating) this type of wallsharing worked
![2021-09-05_11 18 49](https://user-images.githubusercontent.com/1339552/132120355-b09c16ae-5190-4e40-bf1a-5180dffa839d.png)

### The Reality

The bottom one forms because it doesn't have more than 1 coil in it's 3x3x3, but the one above it (and all the ones above that) does not form even though before updating from 2.1.1.0 to 2.1.1.2 it would form correctly
![image](https://user-images.githubusercontent.com/1339552/132120440-9f6c8bae-0924-4dbe-a701-abefd5f13b61.png)
![image](https://user-images.githubusercontent.com/1339552/132120432-25ff64a5-ea2d-4647-844a-d3bce43c4808.png)

### Your Proposal

Allow LCRs to have more than 1 coil in their multiblock, like it used to be.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
This is the tooltip in 2.1.1.0:
![image](https://user-images.githubusercontent.com/12850933/132120823-89122b28-84a3-4b22-b357-52f9c5382c6b.png)
The tooltip implies there is only one cupronickel in the structure, so it makes me think it's intended, and the previous pack versions have a bug allowing for more than 1 cupronickel coil block.

**Comment by GTNH-Afx237v7** [comment]
Had the same issue and after consulting with @Glease it is defined as one coil per LCR.

**Comment by Sphyix** [comment]
I think that you can just remove the middle coil and all of them should form

**Comment by Glease** [comment]
This is an intended change. Won't fix. You could probably just replace one of them with ptfe casing and they will all form.

**Comment by GTNH-Colen** [comment]
Yikes, this is gonna hurt a lot of setups when the update goes through.

**Comment by Glease** [comment]
When I asked on discord everyone said huh how is using multiple coils useful. I guess it's not really *a lot of setup*.

**Comment by repo-alt** [comment]
I really don't see why you would want several coils in LCR, that was an obvious bug in the structure check before.
