### ISSUE TITLE
Cottage pie from Pam's harvest craft automaticly becomes Shepherd's pie

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#8503]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.1.2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I want to eat the food that not yet eaten to gain HP buff

### The Reality

This item automaticly turned to another item that i have already eaten

### Your Proposal

Is it a ore direction auto union? can they be separated into different things?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Cannot reproduce in 2.1.2.0. Probably solved.
