### ISSUE TITLE
OpenComputers Disk Drive recipe needs epoxy

### ISSUE THREAD

**Issue by funjobie** [GTNewHorizons/GT-New-Horizons-Modpack#8504]
### Your Pack Version

2.1.1.0

### Your Proposal

I propose to change the disk drive recipe from requiring 3 tier 2 chips to 3 tier 1 chips.
Then for further consistency, I propose to add one quest to assemble a disk drive in front of the "Your first computer" quest.
To go along with this change, the quest "Computer case" should be adapted: Currently it gives you a disk drive for free and a power adapter for free, with text description that both require tier 2 chips and that both are needed. I would remove those rewards (maybe replace with e.g. bitcoin). I also propose to adapt the text, because currently it states you must have a converter to power a pc - but in my case i could hook a pc to a gregtech cable just fine and install from the disk drive without issues (so the text must be outdated).

### Your Goal

to offer a consistent gate to the OpenComputers mod, for those players who either don't play by the quest book order or don't want to rely on their rewards

### Your Vision

i have the impression the disk drive from OpenComputers is gated incorrectly.
In order to assemble a tier 1 computer, basically everything requires Polyethylene or below
(computer case,cpu,ram,gpu,disk,eeprom,monitor,keyboard,os floppy)
but the one block to put it together, just to install the os onto the disk, requires to go down the epoxy route
since it requires 3 tier 2 microchips.

Beginning with OpenComputers is already a rabbit hole due to many components one did not think about initially. I would like to prevent players from stumbling into yet another one on the finish line.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by KamenriderZO** [comment]
I think many OC recipes are too expensive,need to be rebalanced.For example database upgrade Tier1 needs 12Lv circuit 3MV and 5HV circuits.But it is just a list for 9 items!Why it is so expensive.

**Comment by Prometheus0000** [comment]
Many people don't use it, and I don't know if the people that edit recipes (like me) use it. Theoretically you can use it earlier, but the target audience of users might be those at LuV who are trying to automate their assline, and I don't think it would be considered expensive then. Personally I wouldn't even know how to balance it because I've never used a single part. If you want it balanced, suggest all the changes, not just one or two, and then have people comment on it.

**Comment by repo-alt** [comment]
Actually robot is useful for tedious tasks automation, like crops breeding, prospecting and now even bee breeding, (as soon as you can make a robot, at MV) BTW, assembly line is usually automated w/o OC, because it is way too slow for that. (And there is recently found simple AE-only solution)

**Comment by Prometheus0000** [comment]
I really feel like automating crop and bee breeding is like cheating unless you coded it yourself. I can also imagine dream saying they should both be nerfed into oblivion to counter it.

**Comment by repo-alt** [comment]
Well, I'm not actually saying it should be made cheaper. But I disagree about coding yourself: crop breeding scripts that I saw and used required adjustments, so it is not trivial to use. I suggest you to try it out to get the feeling of ho much cheating it is

**Comment by Prometheus0000** [comment]
I'd probably fail at turning a computer on, I'll just believe you.
