### ISSUE TITLE
cannot enter GTNH

### ISSUE THREAD

**Issue by ivanfei-1** [GTNewHorizons/GT-New-Horizons-Modpack#8506]
### Your GTNH Discord Username

ivan

### Your Pack Version

2.1.1.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

i installed GTNH through HMCL on my intel based mac with bootcamp, it loaded utill 100% and then it crushed. I've tried 16,12,8G of ram while none of them worked.

### Crash Report

[hs_err_pid4500.log](Censored for security reason)
[minecraft-exported-logs-2021-09-06T17-49-37.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7115068/minecraft-exported-logs-2021-09-06T17-49-37.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
Here is an extract of your hs_err_pid4500.log:
```#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 1247376 bytes for Chunk::new
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Zero Based Compressed Oops mode in which the Java heap is
#     placed in the first 32GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 32GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (allocation.cpp:389), pid=4500, tid=0x0000000000001204
#
# JRE version: Java(TM) SE Runtime Environment (8.0_301-b09) (build 1.8.0_301-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.301-b09 mixed mode windows-amd64 compressed oops)
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
```
You are not properly allocating ram for the jvm, and if you do, then maybe it's because you try to run the pack on mac. In the end, it's not really a pack issue. I'm closing this.
