### ISSUE TITLE
The quest that rewards the player with an iron pick should be changed

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#8507]
### Your GTNH Discord Username

johnch18

### Your Pack Version

2.1.1.0

### Your Proposal

The quest at present allows the user to get an iron pick head by mining 64 cobblestone, however, it is completely  antithetical IMO to the spirit of GTNH and is unnecessary. Limonite, (an iron ore), is mineable with pickaxes available to the player at the point the quest is.  The quest should be changed to require limonite and give some other reward, the player is fully capable of making an iron pick at this point.

### Your Goal

Helping the player understand how GT veins work + nerf lmao

### Your Vision

Improve flow of modpack

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by observeroftime01** [comment]
I think the idea of mining 256 cobble is to show you that tinkers tools accumulate experience, and that you can repair and swap out parts, but need experience (like the flint head for the new iron one). Mining the 256 cobble helps with doing that upgrade.

The flint pickaxe you craft the quest before doesn't let you mine limonite, you need the iron head for that. So it kind of makes sense if you follow the quest.

**Comment by bombcar** [comment]
I mean you can force the player to mine smalls. The iron pick head was 👍🏻 but I’d already made one. 

Perhaps it can be some other iron tool head

**Comment by johnch18** [comment]
> I mean you can force the player to mine smalls. The iron pick head was 👍🏻 but I’d already made one.
> 
> Perhaps it can be some other iron tool head

That's the thing, this quest presently feels like a shortcut, and it sticks out to me in NH. It's been almost 2 years since I did it last and it stuck out to me enough to make a thread about it.

**Comment by bombcar** [comment]
To be fair a bunch of quests are shortcuts if you’re playing attention (especially when you get to the fluids) but you end up having to make the things anyway. 

I feel gtnh is kind of oriented to “get you to machines pretty quickly” or it would have bundled primaltech or similar.

**Comment by Methes** [comment]
Another pointless nerf extending the gameplay suggested by someone not really touched by the early game.
The correct way actually is to make a second pickaxe - one original with flint head and one with iron head.
The flint one you later get to mining level 12 with a few haste upgrades and then level it up to lvl 14-17 by mining netherrack.
The iron one you use to finally mine some ores. Even when 'skipping' making smeltery and lava and small ores first, you'll still spend 10 hours easily just to find the veins you need and then slowly mine them, only to quickly spend all the resources you've been mining.
