### ISSUE TITLE
Be able to utilize Red Sand for Grout in the Mixer recipe..

### ISSUE THREAD

**Issue by ApexPredaturr** [GTNewHorizons/GT-New-Horizons-Modpack#8513]
### Your GTNH Discord Username

ApexPredaturr#3181

### Your Pack Version

2.1.1.0

### Your Proposal

Add the "Red Sand" to the list of items allowed to craft Grout via the Mixer recipe. As of right now, you can only use vanilla Minecraft sand.

### Your Goal

Some of us choose the massive Mesa biome that has tons of red sand rather than the normal sand. Doesn't seem too farfetched to have changed as it doesn't necessarily impact progress too much.

### Your Vision

Many people like me wouldn't have to go hike to a normal desert biome just to make tons of grout.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
sure I need to add this recipe

**Comment by bombcar** [comment]
Red Sand -> Centrifuge = Sand + Red Dye ;)

**Comment by ApexPredaturr** [comment]
Hmm in my pack I’m seeing red sand can go down to iron dust, diamond dust, and sand via the centrifuge but not the recipe you’re saying unless I’m just confused. Either way tragic that it’s only an MV recipe too. I wanted tons of grout early on and if I can use regular sand I think it’s just kind of dumb that I can’t use red sand when it is just as abundant (at least in SP) 😛

**Comment by bombcar** [comment]
Fair enough, didn’t realize there was already a red sand centrifuge. Makes sense it could be used in grout
