### ISSUE TITLE
Remove buck converter energy usage

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/GT-New-Horizons-Modpack#8514]
### Your GTNH Discord Username

Usernm#4396

### Your Pack Version

2.1.1.0

### Your Proposal

I put battery buffer with one iv battery and attach buck converter to it. Buck converter set to 16A 512 eu. Buck converter not connected to anything. A look at battery and converter drain 8k eu every few seconds (5 maybe). 

It drain not much energy but we have alternative: ev transformer and Hi-amp hv transformer in chain. They drain nothing. 

If i should select from little drain and no drain at all, I select second option. 

I propose remove energy drain from buck converter at all to make it equal to transformer chains. 

### Your Goal

Make buck converter great again

### Your Vision

Make buck converter totally better than transformer chain. Less blocks on base, less lag to servers. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Sphyix** [comment]
That could be a good alternative to transformers, making it have the same efficiency of transformers is a good idea...
