### ISSUE TITLE
travellers' gear's title aren't hidden when the invisible effect is triggered

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8516]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

I expected the title to be hidden when in invisible mode.

### The Reality

Was playing a hide and seek with some guys on delta, and i lost because of that title.

### Your Proposal

Please make it work so it's hidden when you drink an invisible potion.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment]
You are just a sore looser ngl, thanks for the void miner III btw ^^
