### ISSUE TITLE
the incessant need for a sigma male grindset in the game

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/GT-New-Horizons-Modpack#8517]
### Your GTNH Discord Username

poptartoverlord xabedo#4042

### Your Pack Version

the bad one

### Mod Name

 https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-mca/files/2323497

### The Mod to Add

Becoming the sigma male who'll produce countless children

### Your Reason

this mod is needed to add Estrogen and  possibly also Testosterone to the pack,  you get them by making the babies you get from grinding those sweet sweet hearts with your loved one, putting the baby inside a pulverizer which produces androstenedione, for obvious reasons its abit hard to get estrogen from a baby, so through the process of aromatization to estrone, followed by conversion of estrone to estradiol by 17β-HSD, as for testosterone thats much easier to get so just throw a male baby in an LCR with HCL to get some of that sweet sweet sigma production going

as for uses, testosterone could be injected directly on the player which gives him strength and resistance 100, and "insight on ascension" buff which simply fully automates a polybenzimidazole process chain along with all the materials needed within 1 hour.
another  use for testosterone is in the production of stargates, as the stargate honestly lacks the sigma energy

as for estrogen its  main use would be to reset player data as who the hell takes that gay shit? it produces negative energy which is harmful for your sigma grindset! it should be mainly used as a weapon against people who say the pack is too hard!

### Preliminary Investigation

it just works :^)

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Rongmario** [comment]
Silly suggestion? That's racist.
