### ISSUE TITLE
Russian server ip changed

### ISSUE THREAD

**Issue by boozzeeboom** [GTNewHorizons/GT-New-Horizons-Modpack#8522]
### Your Pack Version

2.1.1

### Your Proposal

pls change the ip in servers list on our server (wabulabudaba) to: 49.12.204.132:25565

### Your Goal

-

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
why don't you use a domain name to avoid any issue like that?
