### ISSUE TITLE
Industrial Wand Charging Station did not work in 2.1.1.2

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#8524]
### Your GTNH Discord Username

John S#7565

### Your Pack Version

2.1.1.2

### Your Server

Local

### Type of Server

Single Player

### Your Expectation

Try to charge any wand in Industrial Wand Charging Station.

### The Reality

Any wand didnot charge at all. Trying also in isolated EU system with one battery buffer, one diode and a wand charger.

https://i.imgur.com/WvuZGHJ.jpg

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
I've not tested on dev versions, but for reference this setup works fine on 2.1.1.0 so a more recent change must have broken it.
![image](https://user-images.githubusercontent.com/73182109/132997939-be0718a1-5cf7-40be-ab5a-bed8e0f9bfd0.png)

**Comment by Retster** [comment]
> I've not tested on dev versions, but for reference this setup works fine on 2.1.1.0 so a more recent change must have broken it.
> ![image](https://user-images.githubusercontent.com/73182109/132997939-be0718a1-5cf7-40be-ab5a-bed8e0f9bfd0.png)

I know. And i know that in 2.1.1.2 was implemented new logic for EU network that, i think, cause this bug. And i reporting that bug to make next stable wersion also working fine. Best regards.

**Comment by boubou19** [comment]
what if you put a GT machine hull on the superconductor as well?

**Comment by Retster** [comment]
> what if you put a GT machine hull on the superconductor as well?


Stil not work.

https://cdn.discordapp.com/attachments/838444551160594484/886696754085523556/unknown.png

**Comment by boubou19** [comment]
Can you post your gregtech.log file?

**Comment by Retster** [comment]
> gregtech.log

here is:
https://drive.google.com/file/d/14v9Y50_MnQ35hjeqmMklXk5rVmI7qeRN/view?usp=sharing

**Comment by aka-zaratustra** [comment]
Tesla coils stopped working. Version 2.1.1.3. I tried it with superconductors and an additional consumer on the wire - the same result, Tesla coils not working. Tried on my server and solo - the same result, Tesla coils not working. On 2.1.1.0 it worked without problems, I had a Wither farm.
![unknown](https://user-images.githubusercontent.com/24389462/136701910-fafe4736-7a85-49cb-a245-0617cbe83204.png)

**Comment by Retster** [comment]
> Disable the wand charging station then. It circumvents a core thaum mechanic, and you can already auto-charge with pure thaum.

Amazing solution. :Trollface:

**Comment by Prometheus0000** [comment]
What problem? I don't see any problems? If there's a problem, someone should make a ticket about it instead of making this thing (bart or whoever made it).

If there's a problem with wands not charging fast enough or...whatever the problem is, make a ticket about that. If it's that, then I'd say you need more wand charging pedestals, energized nodes, and wands.

**Comment by Retster** [comment]
> What problem?

Cannot to charge wand with EU its a problem? Make another ticket for it?
