### ISSUE TITLE
thaumcraft "Witchy (Wo)man" quest's emergence?

### ISSUE THREAD

**Issue by shippeel** [GTNewHorizons/GT-New-Horizons-Modpack#8527]
### Your GTNH Discord Username

homo economicus#5771

### Your Pack Version

2.1.1.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

![i expected](https://user-images.githubusercontent.com/75339211/133098082-97608fa0-f041-4770-9a92-0dc3b2320d12.png)

### The Reality

![first](https://user-images.githubusercontent.com/75339211/133098134-36e23bd7-3fef-4f28-8bce-48ee589b7744.png)
![second](https://user-images.githubusercontent.com/75339211/133098242-3cbe6fa1-21b0-443e-a2a8-798740ddc7c9.png)

### Your Proposal

want to learn how to fix that and being able to claim the reward when or even i make that quest 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
This is due to deleting quests and reusing the ID by adding another, there's nothing you can do other than resetting the quest.
