### ISSUE TITLE
Add the cooking-for-block-heads fridge upgrade(s) from the newer versions of the mod

### ISSUE THREAD

**Issue by MrJakobLaich** [GTNewHorizons/GT-New-Horizons-Modpack#8531]
### Your GTNH Discord Username

MrJakobLaich#6170

### Your Pack Version

2.1.1.0

### Your Proposal

Newer version of "cooking for blockheads" add the items "Preservation Chamber", "Ice Unit" and some other small block upgrades.

They aren't in this pack, I suggest adding at least the "preservation chamber", I think this could be a nice small addition.
(The milk glasses would probably also be a cool addition)

I don't really know what would break by adding this, it would just keep one item of each food in the fridge when using the cooking table, imo that's very nice and has no drawbacks.

### Your Goal

Keep the last item in the fridge(s) when using the cooking table

### Your Vision

Nobody would have to remember what foods go into the fridge, just start cooking!

It's a very small addition but probably helps a lot when using the cooking for blockheads kitchen :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
Mitch just hasn't gotten around to it yet.

**Comment by MrJakobLaich** [comment]
Can I help in some way?

**Comment by Prometheus0000** [comment]
The repo is at https://github.com/GTNewHorizons/CookingForBlockheads, other than that, ask @mitchej123
