### ISSUE TITLE
Add recipes to high tier diodes

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#8536]
### Your GTNH Discord Username

Pxx500#6984

### Your Pack Version

2.1.1.2

### Your Proposal

Add new recipes to high tier diodes (for some reason only 16A UHV diode has recipe)

### Your Goal

Better energy management

### Your Vision

It would make energy grid management better and safer

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
So, which tiers exactly are missing recipes? And it's only the 16A ones that are missing them?

**Comment by GlodBlock** [comment]
all diodes except 16A ones don't have recipe for UHV and higher tier. the 16A ones don't recipe for UEV and higher tier

**Comment by Pxx500** [comment]
> So, which tiers exactly are missing recipes? And it's only the 16A ones that are missing them?

From the UHV tier only 16A UHV diode has a recipe
Voltages UHV and up don't have recipes, athough I don't think UIV+ diodes are needed

**Comment by Sphyix** [comment]
> > So, which tiers exactly are missing recipes? And it's only the 16A ones that are missing them?
> 
> From the UHV tier only 16A UHV diode has a recipe
> Voltages UHV and up don't have recipes, athough I don't think UIV+ diodes are needed

Considering the new generators, uiv and umv 16a diode might be useful soon

**Comment by Pxx500** [comment]
> Considering the new generators, uiv and umv 16a diode might be useful soon
Also more dynamo hatches? I rember some of those higher tier ones don't have recipes.

**Comment by Prometheus0000** [comment]
What? Didn't I add recipes up to UMV?

**Comment by Pxx500** [comment]
I could've missed that

**Comment by combusterf** [comment]
These recipes would certainly be nice to have. Currently one would have to do tricks with battery buffers to do current limiting

**Comment by POPlol333** [comment]
So, I and Boubou spent 6 hours (me, tried to help me for about 2 hours) to find what was actually happening. Unfortunately couldn't come with any good result. We indeed noticed  a few thing:
- the machine_hull variable that determine the hull in the recipe is based on a list which doesn't contain upper than UHV Hull (named MAX_Hull in the said list), so even if someone fix the archwizardry happening to UHV diode he would still has to edit the machine_hull variable to have every hulls
- We did added a small if else to make him take hulls by metaidea, which made the ArrayOutOfBoundError that was occurring at index 10 (UEV) to 13 (UXV, didn't tried more than UMV) but unfortunately even with this craft weren't generating at all,
stacktrace doesn't show anything else than the ArrayOutOfBoundError

**Comment by boubou19** [comment]
I suspect somehow the UHV diode recipes get removed because of some null objects being passed, but i cba to actually check
