### ISSUE TITLE
Whole computer freezes on game startup

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8537]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

GTNHdev 2.1.1.2 with bartworks1.7.10-c9836c6-0.5.21.jar & gregtech-5.09.37.10.jar & GoodGenerator-0.2.0.jar

### Your Server

solo

### Your Expectation

I expect the game to start without frezzing my whole computer and other applications

### The Reality

When starting the game and reaching this point in the loading my whole computer froze for 5 seconds 

It was at this point in the console 
https://media.discordapp.net/attachments/401118216228831252/887771241103114250/unknown.png
https://media.discordapp.net/attachments/401118216228831252/887771281506844702/unknown.png
https://media.discordapp.net/attachments/401118216228831252/887771334329909298/unknown.png

I was profiling the JVM with visualVM206 and here is the data 
https://cdn.discordapp.com/attachments/401118216228831252/887770222830977045/Profiling_starting_client.nps

extra info : I am using graalVM

### Your Proposal

investigate

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
still happening on dev 2.1.1.3

**Comment by Alexdoru** [comment]
fun 
![image](https://user-images.githubusercontent.com/57050655/134714645-4991879e-a7c2-4224-a102-98510a1afe77.png)

**Comment by TimeConqueror** [comment]
That's because Gregtech uses as much threads as possible while loading its stuff (speeds up the loading)

**Comment by Alexdoru** [comment]
Is that new in 2.1.1.3 ? Because is wasn't happening before. I wouldn't mind my game taking 30 sec longer to load and not have that gigantic freeze.

**Comment by Methes** [comment]
![cpuusage](https://user-images.githubusercontent.com/8257735/134735284-69c8ad26-eb4d-4489-b7d0-6093b149bb97.png)
I am still using 2.1.1.0 and got the same CPU spike. It doesn't completely freeze my PC though, usually other apps (like youtube video) only severly stutter for 2-3 seconds, nothing terrible. Might be just your setup getting hit more severly.
