### ISSUE TITLE
Semi Transparent Chests

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#8541]
### Your GTNH Discord Username

TimeConqueror#5294

### Your Pack Version

2.1.1.2dev

### Your Server

private one

### Type of Server

Thermos

### Your Expectation

-

### The Reality

The chest becomes transparent from some angle, when enchanted spike from extrautils (tested with diamond one) is in player's frustrum. 
To reproduce: firstly place the enchanted spike, then a chest.

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
> frustrum.

? Inventory? View?

**Comment by TimeConqueror** [comment]
View

**Comment by Ngar1** [comment]
I have the same situation, sometimes get the chests invisible. If I try it at the identical position again, it does not occure.
