### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by idkimanerd** [GTNewHorizons/GT-New-Horizons-Modpack#8542]
### Your GTNH Discord Username

Some Nerd With A Keyboard#4823

### Your Pack Version

2.1.1.3 dev 2

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Load/create creative world

### Crash Report

[crash-2021-09-16_16.29.04-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7181536/crash-2021-09-16_16.29.04-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.
Edit: It only happens in creative

**Comment by TimeConqueror** [comment]
Please, also provide logs.

**Comment by idkimanerd** [comment]
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7182543/GregTech.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7182545/latest.log)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7182546/fml-client-latest.log)
here

**Comment by idkimanerd** [comment]
OK 2.1.1.3 dev official fixed this

**Comment by idkimanerd** [comment]
Nevermind, but it no longer crashes and happens with any world

**Comment by idkimanerd** [comment]
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7192550/latest.log)
new latest.log
