### ISSUE TITLE
Infinity Chest Overflow 

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#8543]
### Your GTNH Discord Username

Colen (His Supreme Holiness, HBM manager XIV, Colen | RADM. Supreme Gay🎖🎖🎖🎖)

### Your Pack Version

2.1.1.0

### The Reality

Infinity chest overflows and resets the stack size to 0, deleting 2 billion items.

![image](https://user-images.githubusercontent.com/54497873/133718229-d374f292-e0c2-4970-bdeb-9beecc46eba6.png)

This stack was around 1.9 billion, I checked it today and seems to have looped round to 600m (Storage bus is on an infinity chest).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
This was also happening with quantum tanks V but it got fixed. Now I am wondering : does it happens with quantums chests ?

**Comment by repo-alt** [comment]
No, it cannot happen to quantum chest, at least via AE interface. Also, what do you think about limiting any infinity chest automation access except storage bus, as @boubou19 suggested in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8491?

**Comment by GTNH-Colen** [comment]
Can I ask what exactly the end result was @GlodBlock, would an inf chest now simply start a new stack if the first one fills or just refuse new items to prevent an overflow?

**Comment by GlodBlock** [comment]
it will start a new stack.

**Comment by Prometheus0000** [comment]
What if all slots are full?

**Comment by GlodBlock** [comment]
didn't test when all slots are full, but i think it will refuse to accept item like normal chest

**Comment by PredVesTNiK2142** [comment]
2.1.1.3 
The bug has not been fixed yet. Fixed only display and transition to a new slot. The old slot still breaks into a negative value and the items actually disappear

**Comment by GlodBlock** [comment]
do you mean that you already had a negative slot before this fix and this slot didn't get fixed after update?

**Comment by boubou19** [comment]
Well on delta with the fix server side, we saw the slot in the render that appears empty, but with a storage bus everything is still here, so must be visual.

**Comment by Alexdoru** [comment]
Break it and pick it up to do /mt hand to see what it says

**Comment by PredVesTNiK2142** [comment]
> do you mean that you already had a negative slot before this fix and this slot didn't get fixed after update?

No. I took a new chest and began to fill it again. But even in the old chests, nothing was repaired.



> Break it and pick it up to do /mt hand to see what it says

![image](https://user-images.githubusercontent.com/63409840/135574689-e68739aa-780c-4ec3-acc5-d617c926a1ae.png)

**Comment by PredVesTNiK2142** [comment]
Moreover, when it goes into the mechanism, the value becomes more and more negative.

**Comment by PredVesTNiK2142** [comment]
I can also add one more bug to this. There is 373kk of stone dust in the chest, but after storage bus, only 3 dust is shown in the system. All new dust is also invisible in the system.
![image](https://user-images.githubusercontent.com/63409840/135575651-51b2b9d9-44b1-4ae9-bc71-e38d967d8afb.png)
![image](https://user-images.githubusercontent.com/63409840/135575702-363e2a87-f43b-411a-a5b2-c90d8ced12b4.png)

**Comment by GlodBlock** [comment]
> 
> 
> > do you mean that you already had a negative slot before this fix and this slot didn't get fixed after update?
> 
> No. I took a new chest and began to fill it again. But even in the old chests, nothing was repaired.
> 
> > Break it and pick it up to do /mt hand to see what it says
> 
> ![image](https://user-images.githubusercontent.com/63409840/135574689-e68739aa-780c-4ec3-acc5-d617c926a1ae.png)

the nbt shows the chest actually spit the stack into two stacks to avoid overflow, if you open the chest the item's amount shouldn't be nagetive.
the display error in ae is ae's fault, the max store amout per item in ae is 2147483647

**Comment by PredVesTNiK2142** [comment]
It is displayed correctly in the chest. If you look at the chest through glasses, it is not correct. And from the chest from the filled slot, objects cannot be taken into mechanisms.

**Comment by GlodBlock** [comment]
ok, i see. this seems to be another bug instead of overflow. i will try to fix it.

> I can also add one more bug to this. There is 373kk of stone dust in the chest, but after storage bus, only 3 dust is shown in the system. All new dust is also invisible in the system.

is you device offline?

**Comment by Prometheus0000** [comment]
Maybe add another ticket for this if it's something different. Unless you're going to fix it right away I guess.

**Comment by PredVesTNiK2142** [comment]
Everything is connected and working. Besides what I wrote

**Comment by GTNH-Afx237v7** [comment]
AE2 developers: Nobody is going to store more than 2B items, lol
GTNH players: Hold my beer!
