### ISSUE TITLE
OC Glasses not binding to Glasses Terminal in other dimensions

### ISSUE THREAD

**Issue by DisasterMoo** [GTNewHorizons/GT-New-Horizons-Modpack#8544]
### Your GTNH Discord Username

DisasterMoo#1105

### Your Pack Version

2.1.1.0

### Your Server

SP, StoneHuts

### Type of Server

Don't know

### Your Expectation

Trying to bind OC Glasses to a glasses terminal in Garden DIM: 183.

### The Reality

OC Glasses bound to a fixed DIM: 0.

### Your Proposal

Most certainly an easy fix, probably no one noticed since not many players uses the mod.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
I tested in dev in the nether and the glasses are bound to the terminal just fine

**Comment by DisasterMoo** [comment]
Tested a bit and looks like what I have is a buggy dim, at least, for the glasses binding. Just created a new world and it worked just fine. Closing the issue (and sorry for the trouble).
