### ISSUE TITLE
Active transformer voids all power you give it

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#8545]
### Your GTNH Discord Username

Pxx500#6984

### Your Pack Version

Latest jenkins

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

I expected active transformer to be the best possible transformer

### The Reality

It has flat 0,004% loss but also it voids all power you give it even if there is nothing using it, you can give it at least 1A and even if you won't use it all it will void it anyway making real loss much bigger (in my test build I had 40%+ loss and had to limit with battery buffer to make it about 5% loss) making it the worst transformer.

### Your Proposal

Either state that it's not for transforming normal power and that it's used only for lasers or fix it to not void power.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
Care to elaborate on how your active transformer was built?
I operate one that receives 256A LuV and gives out 64A ZPM and have not noted such loss at all...

**Comment by Pxx500** [comment]
![image](https://user-images.githubusercontent.com/81298696/133834382-2d283c40-b0aa-4c0a-940d-17fa0938099b.png)
@GTNH-Afx237v7

**Comment by Pxx500** [comment]
Looks like it was caused by bad scanner reading, I would love to have a scanner like eu-reader that let's you scan over time
