### ISSUE TITLE
Wrong recipe for Chromium Dioxide Dust

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#8548]
### Your GTNH Discord Username

AdamR#1117

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Don't know

### Your Expectation

It say "CrO2" so I expected it to be a chromium dust with 2.000L of Oxygen

### The Reality

Instead he ask for 5.000L of oxygen, so O5 and not O2?
![image](https://user-images.githubusercontent.com/76914762/133865453-fa456e74-723e-4d8c-8989-2ea6dd526dc4.png)

### Your Proposal

So, as you might have guessed, I'd like to propose to switch it to 2.000L of oxygen, as I think it should be? 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Uh, do you know where it's from? So we know who to ask which part is wrong.

**Comment by Pxx500** [comment]
> Uh, do you know where it's from? So we know who to ask which part is wrong.

It's for benzimidazole iirc

**Comment by Prometheus0000** [comment]
I see, so it isn't new.

**Comment by Dream-Master** [comment]
it isnt generated in gt or the core mod.
