### ISSUE TITLE
No crafting for all EnderStorage items

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#8549]
### Your GTNH Discord Username

Pxx500#6984

### Your Pack Version

Latest jenkins

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

See recipes for 
![image](https://user-images.githubusercontent.com/81298696/133867433-bca06c6e-6e1e-4f20-8f3b-cf076e8a2061.png)
in NEI

### The Reality

I see no recipes since last jenkins update (could be longer since I don't check those recipes everyday)
I can craft those items

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by yukieiji** [comment]
They are locked in TC research, so the recipe will not appear until it is complete.

**Comment by Pxx500** [comment]
I am aware of that, I should see them

**Comment by Pxx500** [comment]
Looking at the thaumonomicon doesn't fix 
![image](https://user-images.githubusercontent.com/81298696/133868636-9ed7659e-7cc8-4d8a-b159-4cc990c756a1.png)

**Comment by Glease** [comment]
Sounds like a bug with NEI TC plugin. @TimeConqueror heard you have been doing some work with it. Thoughts?

**Comment by kuba6000** [comment]
Seems fixed
