### ISSUE TITLE
Railcraft Tank gauge item duplication

### ISSUE THREAD

**Issue by DennisCorvers** [GTNewHorizons/GT-New-Horizons-Modpack#8550]
### Your Pack Version

2.1.1.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Recycling of Steel/Iron tank gauge gives as many items or less than is required to craft.

### The Reality

Recycling of Steel/Iron tank gauge gives more items than it takes to craft.
Recycling via Arc furnace (nets 11 nuggets) or via pulverization (nets 2 dust and 3 glass dust).

### Your Proposal

- Arc furnace should net at most 9 nuggets of the relevant material.
- Pulverization should net 1 dust of the relevant material and 1 glass dust.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by QQLazors** [comment]
Similar issue applies to railcraft iron tank walls in v2.1.2.0
Iron tank walls require 2 iron plates to craft in an assembler, but can be pulverized into 20 tiny piles of iron, netting a profit of 2 tiny piles of iron dust.
![image](https://user-images.githubusercontent.com/10213974/146600531-b2543785-09a4-4985-9473-6761c08ff111.png)
![image](https://user-images.githubusercontent.com/10213974/146600471-9a39d865-865b-48ad-b8f8-eea61024cd69.png)
