### ISSUE TITLE
Have Charcoal Pile Igniter display error

### ISSUE THREAD

**Issue by uthbees** [GTNewHorizons/GT-New-Horizons-Modpack#8556]
### Your GTNH Discord Username

uthbees#0012

### Your Pack Version

2.1.1.0

### Your Proposal

When the Charcoal Pile Igniter has a problem preventing it from working, instead of displaying "Running Fine Efficiency 0%", show something like "Error: Base Incomplete/Invalid" "Error: East wall Incomplete/Invalid" "Error: Gap In Logs" and so on.

### Your Goal

Currently, the CPI gives no feedback other than saying it's working, or saying it isn't working in a confusing way.

### Your Vision

Giving more feedback will make setting up the CPI friendlier so you don't have to tear out everything if you make an error. I just spent an hour fighting it before realizing that it had to be centered. Then it still didn't work because I had a log missing. Then it *still* didn't work because I missed a stone block in the wall.

This feature isn't neccessary, but I think it would help smooth the experience, both when figuring out how it works (you might get confused or misread something) and when setting up large size charcoal pits (it's easy to make mistakes on a large scale).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [x] I believe this feature would make the pack better.

**Comment by leagris** [comment]
A few remarks though:
- The charcoal pile is a very low tech you are not supposed to operate for much time.
- The machine has no specific state. It is always scanning structure witch include the walls ceiling, ground but also the logs space. This means there is no such things as errors or incomplete walls/logs structure elements. The structure is either complete or incomplete and both situations are valid.
- The hover tool-tip with % operation is a WAILA extension. The Gregtech Igniter itself has no such display. It has no display or GUI at all. It is a very dumb bronze box with a lighter. The only smartness in it is that it automatically start converting logs to charcoal blocks once everything is in the structure. This machine is so dumb that normally it would have required player wacking a soft mallet on it to start the process.
- Finally, inspecting walls, ground and ceiling is a one time task you only need to care when assembling or modifying the room. So if it fail to start, the only possible cause is missing log.

So yes it would be certainly possible to extend the igniter code to have different states for room check and for logs checks and have WAILA extension pull this information additionally to the location of missing blocks. But this would really be overly complex, for such a very basic machine, only used for a very short period until you can automate Coke Ovens.

**Comment by uthbees** [comment]
I think your points can be condensed down to two things:

* It would be difficult to code
* It doesn't matter for very long

It's true that it's pretty much only useful when setting it up for the first time, but setting it up for the first time can be difficult when you might be unsure or confused about how it works - these things happen to everyone.

However, if it would be relatively difficult to implement as you say, then although I think adding this would make the pack better, it may not be worth the developer time.

**Comment by uthbees** [comment]
If the full suggestion isn't implemented, it would be worth adding to the description of the block that it reaches up to 5 blocks in each direction. Something like, "up to 5 blocks in each direction, for a full size of 1-11x1-6x1-11"

It was a pain for me to figure that out (I was trying to put it off center in a max pit) and from trying to research it, it looks like others have had similar problems in the past.
