### ISSUE TITLE
GT Teleporter is not craftable

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8557]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Your Expectation

Expected to be able to craft a GT Teleporter

### The Reality

Teleporter is not craftable because IC2 Stargate Power Unit doesn't have a recipe

### Your Proposal

Change it to RF Stargate Power Unit or make a recipe for IC2 Stargate Power Unit

--Edit after discussion under here--
Add a whitelist to limit the planets that you can tp to with the Teleporter
Re-enable the use of plasma and/or the ender dragon, as it was disabled by Technus 4 years ago (around line 250)
https://github.com/GTNewHorizons/GT5-Unofficial/blame/experimental/src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Teleporter.java

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by idkimanerd** [comment]
Not a bug, report as a suggestion

**Comment by Sphyix** [comment]
I don't see why it's not craftable, it was possible, then recipe got changed for a nerf, from what I know, and stargates parts were used in the recipe.
Why does it still have a recipe if it shouldn't be craftable?

**Comment by idkimanerd** [comment]
You can report it as a suggestion

**Comment by boubou19** [comment]
@idkimanerd can you stop telling him to report it as a suggestion? it's indeed a bug, as before the teleport nerf years ago it was craftable. He reported it after i told him to open a ticket for that.

**Comment by idkimanerd** [comment]
Sorry, I thought it was intentional

**Comment by Sphyix** [comment]
If it was intentional i would expect the item to not have a recipe at all, like I said when I replied, but you just ignored my questions...

**Comment by GTNH-Colen** [comment]
Ok so both are you are kinda right here, I suggested not fixing this previously during the teleporter rebalance because it would open up issues as that teleporter can go to any dimension (bypassing numerous mechanics, not just rockets). I would say the recipe should just be disabled though, the original state was unintentional I'd agree but at this point it's semi intendedly broken.

**Comment by boubou19** [comment]
why would we remove the recipe? Adding stargate components inside it just make it gated behind T8 rocket. No need to worry about potential mecanic being skipped since you actually reached the endgame. If they are any mecanic left that players can bypass without having a legit access to it, then i think it's fair to give them this incredibly pricey way to skip them. For @Sphyix's case, if he needs one it's just to tp on the chaos guardian islands without generating GB of map in the end dim.

**Comment by Sphyix** [comment]
Only mechanics that I can think of that can be skipped are all the dims that need to be made some special ways with some magic mods, or maybe gt++ dim? 
rockets can't be skipped, you need stargates components for the teleport xD

**Comment by leagris** [comment]
Coumd we get it into something more reasonable and blacklist dimensions from inter-dimension transport rather than turn this teleporter unto a late game useless fad?

GT Teleporter already requires plasma or dragon egg to teleport inter-dimensionally and its running cost is already very significant. Turning it to end-game only is very unjust and stupid.

First there are plenty of good reasons to allow teleportation within same dimension mid-game, even early for shorter distances. As long as you say went to the Moon with a rocket, if you want to teleport at another lockation on the moon, this is ok.

If you can afford plasma and enough energy, why restrict you teleport inter-dimensionally from overworld to the end at your favourite far away chaos dragon's lair?

This gating of the teleporter with stargate components is non-sense.

**Comment by boubou19** [comment]
> GT Teleporter already requires plasma or dragon egg to teleport inter-dimensionally and its running cost is already very significant.

Source? because my test on delta (2.1.1.0) says otherwise. And it has been like that since i got access to it (pre teleport nerf)

**Comment by Sphyix** [comment]
> > GT Teleporter already requires plasma or dragon egg to teleport inter-dimensionally and its running cost is already very significant.
> 
> Source? because my test on delta (2.1.1.0) says otherwise. And it has been like that since i got access to it (pre teleport nerf)

It's written on it.. i didn't test yet

**Comment by boubou19** [comment]
just tested it again, and i went from my void dim 16 to the overworld without giving it plasma nor dragon egg.

**Comment by leagris** [comment]
So the feature is either disabled by config option or has been broken sometime in the past by a commit.

**Comment by GTNH-Colen** [comment]
> This gating of the teleporter with stargate components is non-sense.

However this isn't just a teleporter it's a block capable of teleporting to essentially any position in the entire game, including bugged dimensions, ones which are not meant to be accessed randomly (like the witchery stuff) not to mention personal dims on the officials such as gardens/voids. The fact there is like 100 dims in the game just made me eek a bit and stay on the cautious side of leaving it "disabled by proxy" but I don't care *that* much if people want to re-enable it.

**Comment by leagris** [comment]
@GTNH-Colen Sure the teleporter need fixes before it is re-enabled.

1. Re-Implement use of plasma that has been removed by some commit some time ago or other fuel to teleport inter-dimensionally
2. Implement a cross-dimension white-list to only allow inter-dimensional transport between whitelisted dimensions.
3. Check the EU power cost per teleportation distance and inter-dimension factor is correctly balanced, so mid-early game say at EV tier, one can start using the teleporter on same dimension and for say 2048 blocks radius. (power usage is proportional to distance anyway) 2048 blocks is not a hard-coded value but something someone having EV power generation can manage to power a teleporter going 2048 blocks away.

Sure nobody wants the teleporter used to by-pass other mechanics in the game, or to trigger bugs by accessing unintended/broken dimensions. Implementation of an inter-dimensional white-list should be sufficient to address this concern.

**Comment by Prometheus0000** [comment]
All good points, but fixing it was brought up before and didn't end up happening, so who knows if it'll happen this time. I was also for removing the recipe until it's fixed, but it didn't end up happening for some reason.

Stuff like tiering can wait until it works properly, but I really don't think EV is appropriate, if you compare it to the other TP options.

**Comment by GTNH-Colen** [comment]
If you want to put in the leg work on that @leagris then it sounds fine to me but otherwise I don't think it should be re-enabled at present.

Also EV is far too early, I absolutely believe teleporting should be easy as it simply prevents stupidly long and boring walks however this specific teleporter is not suited for that goal.

**Comment by Prometheus0000** [comment]
One thing to keep in mind is that if, say, pluto is whitelisted, you'd be able to go there before the moon, depending on how you do advance. And if it's blacklisted, you can't ever use it to go there. You don't need a receiver or to have gone somewhere before after all. So there would need to be tiers to it (and assign dims to tiers), or make it available after DD or after UHV rocket + not allow DD.

I'm just not sure we _need_ another TP option.

**Comment by Sphyix** [comment]
All I wanted was this to be craftable... As boubs said, right now I need it to avoid timing out delta and generating GB of map in the end to get to draconic evolution dragons

I think the whitelist would solve all the issues that were brought up by colen

I don't like that I need stargates components to craft it, but that's not part of this discussion

**Comment by Prometheus0000** [comment]
I think a way of getting more chaos shards once you have one would be more appropriate for your 'problem'. Unless that's not what you're doing it for?

**Comment by Sphyix** [comment]
I'm doing it for the chaos shards, yes.
Right now the only way is by killing dragons

**Comment by Prometheus0000** [comment]
Then please make a ticket about your _actual_ issue, and not the workaround you want to use. I would suggest something like how you make the green crystal chips. Though I can't remember exactly why there's a bunch of smaller shards already.

**Comment by Sphyix** [comment]
This ticket is about the Teleporter as there's no explanation why it's uncraftable anywhere.
We raised some issues that can be solved by a whitelist, and if that's enough to get it enabled again, it should be done.
The chaos shard is the main reason why I wanted to make the Teleporter, but that's just an example of usage of it, not the reason of the ticket

**Comment by Prometheus0000** [comment]
> If the crafting of the chaos shards can be considered, I'll make a separate ticket for sure

That's what I said? They're separate things.

**Comment by boubou19** [comment]
a git blame indicates that all the code related to egg check or plasma check was disabled 4 years ago: https://github.com/GTNewHorizons/GT5-Unofficial/blame/experimental/src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Teleporter.java

**Comment by repo-alt** [comment]
(probably even earlier, since it is a merge from upstream unstable branch)

**Comment by dimondmine2** [comment]
Bump to prevent this from going stale

**Comment by barsikus007** [comment]
comment to make it open again xD

**Comment by chochem** [comment]
just someone abusing the bot.

**Comment by chochem** [comment]
I guess there is a missing cleanup though, Ill do that.
