### ISSUE TITLE
Migrator cape is not visible

### ISSUE THREAD

**Issue by RinWate** [GTNewHorizons/GT-New-Horizons-Modpack#8558]
### Your Pack Version

2.1.1.0

### Your Server

private server

### Type of Server

Multiplayer LAN

### Your Expectation

I have the migrator cape and i want to see it in the game

### The Reality

Migrator cape is not visible in game

### Your Proposal

Make a cape visible, please

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Minepolz320** [comment]
Same problem

**Comment by boubou19** [comment]
first does it appear in vanilla 1.7.10?

**Comment by RinWate** [comment]
@boubou19 yes. Migrator cape is visible in vanilla version of 1.7.10

**Comment by boubou19** [comment]
Maybe it's GT custom capes' rendering code then. Optifine also adds custom capes. What happens if you install it on a vanilla 1.7.10? Still displayed or not?

**Comment by RinWate** [comment]
if i install optifine on vanilla version, migrator cape is visible. But in GTNH is not

**Comment by Alexdoru** [comment]
Optifine capes don’t work either in GTNH

**Comment by RinWate** [comment]
@Alexdoru kk. I think it's need to be fixed.

**Comment by Minepolz320** [comment]
@boubou19 i guess...
[https://github.com/GTNewHorizons/GT5-Unofficial/blob/4275142856117665d60a841710e8d9bd75d086ff/src/main/java/gregtech/common/render/GT_CapeRenderer.java#L47](url) 
can be replaced by ` ResourceLocation tResource = aPlayer.getLocationCape();`
