### ISSUE TITLE
chunk wise invisible Botany flowers

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#8563]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.1.1.

### Your Server

myFTB

### Your Expectation

from chunk to chunk flowers of Botany (Binnies) not visuable. It changes which chunk flowers are not visible - If I come back in this area.

### The Reality

tested with and without texturepack. I use Optifine HD_U_D6.

### Your Proposal

no unwanted invisibility
![Inked2021-09-20_08 30 42_LI](https://user-images.githubusercontent.com/7759876/133964568-daffa8a8-8f64-4747-a9db-573502f7d553.jpg)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Did you try without OF though?

**Comment by Ngar1** [comment]
Same problem without Optifine

**Comment by Ngar1** [comment]
Problem also checked by an other player: same invisibility chunk wise.

**Comment by Ngar1** [comment]
I found a wired effect: 
only sunflowers as a mincraft flower will not changed into Binnies Botany flower. 
If one of them is placed in the invisible chunk, botany flowers getting visible until the sunflower will be picked...

May be this can help to find the reason of the bug....
