### ISSUE TITLE
Tiering of Draconic Chest is completely wrong (it's just a better compressed chest)

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8564]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.1.0

### Your Proposal

Draconic Chest is just a compressed chest, but with a furnace and a crafting table included in it.
The furnace is kinda slow, but can be really useful at low tiers, it needs RF to run.
I think the Draconic Chest should be tiered like the Compressed chest, so at HV

I understand that most or all Draconic Evolution items right now require a Dire Crafting Table, but some things in that mod are just not used at all as they are gated completely wrong or, since the crafting table needed is expensive at low tiers, it's not worth it at all to make some of them.
I think that Draconic chest is in this case explained above, it shouldn't require a Dire Crafting Table to craft it, as it literally is just a better compressed chest, and based on what it can offer, gating it behind a Dire Crafting Table makes it not worth it anymore.

A proposal for the recipe would be, in a 3x3,  to use a Compressed Chest, HV Furnace, Crafting Table Cover, Basic Capacitor Bank and 5 Meteoric Iron Plates.
This way it's gated after moon, if that's too late it can be gated before moon by changing the plates

Current Recipe:
![javaw_Lm3axzbigv](https://user-images.githubusercontent.com/17811922/133994870-3fe9d12b-7e78-415d-90a8-f364e105b8df.png)

### Your Goal

Make the Draconic Chest usable 

### Your Vision

Draconic Chest right now is gated after T8 Planets, so it's not used since it's pretty much useless at that tier.
It should be gated a lot better, as it can be useful around HV like the Compressed Chest

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
I agree that it's abslutely useless once you can craft it. It would be nice to have before AE2 at EV.

**Comment by Houstonruss** [comment]
Fixed in mega
