### ISSUE TITLE
Industrial Information Panel not updating lines

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#8567]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.1.2

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

The Information Panel should show the desired Information.

### The Reality

There is a bug regarding the visual update of the drawing that messes up the display, which is long known. But right now i encountered a different bug: It just showed wrong values.
Look at the Used Capacity here, tricking me into thinking the battery was full:
![2021-09-20_19 25 26](https://user-images.githubusercontent.com/10967188/134048492-476ffec3-7870-4df2-b1db-506543f4b572.png)
![2021-09-20_19 25 33](https://user-images.githubusercontent.com/10967188/134048494-7debf7ad-8dbc-44bc-955f-9ba0a3ccc987.png)

Interestingly, after a while, without doing anything special it started to sync again.

### Your Proposal

The Information Panel mod has very broken rendering, and needs fixing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Colen** [comment]
Yea can also confirm this, it's super broken and when you go slightly out of range of the block it'll re-render over it but not remove the original text so it ends up blurring and becoming unreadable. Basically makes it useless ish in large bases, resulting in a lot of OC screens.

**Comment by Savallator** [comment]
Also, the funny thing is, while the Bug with not removing the old lines is really common and happens all the time, it is not even reported in the repo here:
https://github.com/xbony2/Nuclear-Control/issues
