### ISSUE TITLE
Illumar recipe consumes programmed circuit

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/GT-New-Horizons-Modpack#8568]
### Your Pack Version

2.1.1.3

### Your Server

Zeta

### Your Expectation

I expected the circuit #8 to not get consumed.
![image](https://user-images.githubusercontent.com/16054364/134054393-4631eaf6-aabb-4bf6-a29b-7c4d504ed9cd.png)

### The Reality

![image](https://user-images.githubusercontent.com/16054364/134054490-20a16883-384c-4d69-85d0-0e0b02ddf707.png)

### Your Proposal

please check to make sure the illumar recipes don't consume the programmed circuit

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Similar to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8559

**Comment by Dream-Master** [comment]
oh nice need to change
