### ISSUE TITLE
Make it possible to hide available Crafting Patterns in Terminal

### ISSUE THREAD

**Issue by Blade8895** [GTNewHorizons/GT-New-Horizons-Modpack#8574]
### Your GTNH Discord Username

Blade8895#6067

### Your Pack Version

2.1.1.0

### Your Proposal

I think it would be a great Idea to hide some crafting recipes in the terminal.
Because you just want your final items visible in your AE System and not the 10 inbetween item steps.

### Your Goal

I think this is needed for faster and better workflow and can be done with simply adding a button to the Pattern Terminal and handle it with a variable in the pattern itself.
![pattern terminal](https://user-images.githubusercontent.com/76847661/134173174-b9f06f17-cf23-44fd-ab88-7a3972b08665.png)

Or the next step is to make a toggle button on the interfaces itself. 
![interface](https://user-images.githubusercontent.com/76847661/134173290-efa69780-6c28-45af-82be-fba23948be7d.png)

### Your Vision

I think for a few of us this is a nice feature because in my case i got many duplicated items for automated renaming for my Assline. And this would lead to a cleaner look in our Systems.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
How would you define the "inbetween" crafts tho?

**Comment by repo-alt** [comment]
Perhaps just don't show "renaming" interface in the terminal? (I see it is already hidden in your screenshot)

**Comment by Blade8895** [comment]
yeah the interface itself will hide. 
But alle the Patterns in the interafe will still show up as a craftable option in the normal terminal.

and with inbetween crafts i mean the steps that nobody need as an item itself. But that everyone see this on its own way. For me i never neet (rarely...) bolts. I need only the Screws. so i want to hide all bolts from my crafting terminal but i still need them in a pattern as an dependencie for the screws. i hope this make it a bit more clear :D

**Comment by repo-alt** [comment]
Idk, use view cells maybe. I don't see a clean way to implement something like that.

**Comment by Prometheus0000** [comment]
> Because you just want your final items visible in your AE System and not the 10 inbetween item steps.

While you may not, I do. Also, this is exactly what view cells are for?
