### ISSUE TITLE
Add Logistic Pipes Integration to AE2

### ISSUE THREAD

**Issue by KeinNiemand** [GTNewHorizons/GT-New-Horizons-Modpack#8575]
### Your Pack Version

-

### Your Proposal

AE2 Logistics Pipes Integration (Requesting Items in a LP network trough AE) this used to be a possible in AE1 1.6.4

### Your Goal

Proper AE2 LP integration is somthing that's been missing since 1.6.4. While LP supports AE witch means you can pull sutff out of an AE network with Logistic Pipes you can't do the reverse and access things stored in a LP network from an AE network.
Somone already tried to make a [pull request](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/2735) to add this to feature howerever it got rejected becouse AE2 1.7.10 was already no longer in development at the time, since the GTNH version of AE2 is still in development it could be added there.

### Your Vision

Adding Logistic Pipes integration to AE2 would make it easier to use AE2 and Logistics Pipes together.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by xigua46685** [comment]
Hoping the developers to look into this issue and add this feature. Compatibility between LP and AE2 would significantly assist players during the EV-IV stage transition. Previous attempts have been made to implement this feature in vanilla AE2, as detailed in [pull request](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/2735)
请开发者们关注这个问题并加入此项功能，LP和AE2的兼容能够帮助玩家更好的在EV-IV时期进行过度。过去已经有人尝试在原版AE2上加入此功能，详见[pull request](https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/2735)
