### ISSUE TITLE
Radon big recipe should be cheaper in terms of energy

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8578]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.2

### Your Proposal

In my opinion the big recipe should have the same energy cost / L of radon than the small recipe.

Change the voltage of the big recipe the 224 eu/t instead of the current 480 eu/t. (224eu/t * 20ticks * 150s /8 = 84 000eu)
 
This way the recipe :
- is still HV
- still takes 150 sec so there is the same amount of overclocks available until you reach the tick limit
- it takes 840 000 EU to make a bucket of radon, same as the tiny dust recipe
- it is in line with the tiny dust recipe

![image](https://user-images.githubusercontent.com/57050655/134230977-c1e038a2-3dfb-4530-865a-e90e0ffb97ba.png)

### Your Goal

make it cost the same amount of energy as the tiny dust recipe

### Your Vision

yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
When making it I saw the number, and thought people would be happier if I doubled such a weird number and halved the time again. We could revert it and double the number, but why do something so annoying?

Also, the math is super weird when OCing from ULV, your math might be wrong, I remember having to redo it multiple times, though I'm not great with math.

**Comment by Alexdoru** [comment]
> Also, the math is super weird when OCing from ULV, your math might be wrong, I remember having to redo it multiple times, though I'm not great with math.

why ? ULV doesn't exists it counts as LV 

Since it's an LCR the energy is preservative across overclocks so you just do 84000\*8 = 672000 eu and that should be the energy used by the big recipe and then if you fix the new recipe to be 150s you find that it needs to be 224eu/t

**Comment by Alexdoru** [comment]
I don't see why the big recipe should more than twice as expensive energy-wise as the tiny dust recipe

**Comment by Prometheus0000** [comment]
Original recipe:
LV:
8 EU
12000t

MV:
32 EU
3000t

HV:
128 EU
750t

However if I make it 128, that's MV. So it would OC again, so I made it x4 to be HV tier, and /4 the time again. The GT code automatically shaves off a certain amount to account for possible loss, so 8->7, 512->480 (dream asked me to change this part in code for some reason, even though it does so automatically).

New recipe:
128x4=512->480
750tx8=6000t, 6000t/4=1500t, so I guess I messed this part up, since it's 3000 right now.

```java
GT_Values.RA.addChemicalRecipe(GT_OreDictUnificator.get(OrePrefixes.ingot, Materials.Plutonium, 8), GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Uranium, 1), Materials.Air.getGas(1000), Materials.Radon.getGas(100), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Plutonium, 8), 12000, 8);

GT_Values.RA.addMultiblockChemicalRecipe(new ItemStack[]{GT_OreDictUnificator.get(OrePrefixes.ingot, Materials.Plutonium, 64L), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Uranium, 1L),  GT_Utility.getIntegratedCircuit(8)}, new FluidStack[]{Materials.Air.getGas(8000L)}, new FluidStack[]{Materials.Radon.getGas(800L)}, new ItemStack[]{GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Plutonium, 64L)}, 3000, 480);
```

**Comment by Alexdoru** [comment]
You get something different from my calculation because 7x4^3!=480 
To make it energy conservative with a recipe that requiers 480eu/t you need the duration to be 84000 * 8 / 480 = 1400ticks 

Your choice I guess

**Comment by Prometheus0000** [comment]
It's not 7 though, it's 8. Like I showed above and in the code snippet.
And then I also showed the x4 to make it HV.

**Comment by Alexdoru** [comment]
From the user point of vue it is 7 in NEI, but your choice to make it 1400 or 1500 ticks
