### ISSUE TITLE
Add a full dust recipe for the platinum salt dust / reprecipitated platinum dust

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8579]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.2

### Your Proposal

This is the current recipe for the platinum salt dust / reprecipitated platinum dust.

![image](https://user-images.githubusercontent.com/57050655/134239644-8014f5f1-fd77-4bb0-acce-3435e14bdc47.png)

We should add a full dust version of the same recipe for the same reasons a full dust recipe was added for the radon.

The new recipe should be :
Input
Programmed circuit 24
1800L Ammonium chloride
18000L Platinum concentrate

Output
16x Platinum salt dust
2x reprecipitated platinum dust
1800L palladium enriched ammonia
9000L nitrogen dioxide
9000L diluted sulfuric acid

The energy cost should be : 36000\*9+18\*400\*2\*2 = 352 800 eu ( to account for the packaging cost at HV)

If we set the power at 480 eu/t it makes 36,75sec duration for the recipe
Or
If we say we want the recipe to last 60sec, we need a power requirement of 294eu/t (this option gives room for one more overclock before tick limit)

### Your Goal

ease the load on the servers
refrain people from spamming more of the same machine which is a boring mechanic

### Your Vision

would be cool right ?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alexdoru** [comment]
There is really no difficulty in spamming the same multi block over and over, you just have to place them in a line and have parallel pipes that feeds them all the same thing.  
It just affects the TPS for really no reason and if you want more throughput it makes you spam more and more.
For instance I have 5 LCR for 20 platinum/sec, I would be happy to replace them with one
![image](https://user-images.githubusercontent.com/57050655/134260501-e6a9b9c1-98be-497b-96bf-208e89068369.png)

**Comment by observeroftime01** [comment]
I would take this suggestion one step further and look at all platline recipes that spit out tiny dusts (palladium, etc.) and adjust the recipes accordingly. I did that for my own personal server, and it is _so_ nice to not have to build extra packagers dedicated to a single type of dust.

![image](https://user-images.githubusercontent.com/57168924/134600689-18569a94-28cc-4155-836b-66b075b860be.png)

**Comment by Alexdoru** [comment]
tiny pile of platinum residue dust 
![image](https://user-images.githubusercontent.com/57050655/134600969-2ca32a9e-ce3e-4f9e-9ae6-54d0af9b5b60.png)

tiny reprecipitated palladium dust and palladium salt dust
![image](https://user-images.githubusercontent.com/57050655/134601032-87d16614-72b7-4ca4-8e10-ccbb4e996e3e.png)
