### ISSUE TITLE
Rotating Elevator doesn't work as described

### ISSUE THREAD

**Issue by ApexPredaturr** [GTNewHorizons/GT-New-Horizons-Modpack#8581]
### Your GTNH Discord Username

ApexPredaturr#3181

### Your Pack Version

2.1.1.0

### Your Server

SP

### Your Expectation

Tried to teleport up (0-20 blocks, nothing worked) to a rotating elevator from a normal elevator.

### The Reality

I did not move at all. If I place a normal elevator in the same spot as the rotating though I get teleported on que.

### Your Proposal

Figure out why the rotating elevator may not be in the code properly? Not sure.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
Seems that only normal to normal or rotating to rotating works, but not when the two types are mixed. Guess that’s intended? Not sure though.

**Comment by Prometheus0000** [comment]
Works perfectly fine to me, both a long time ago, and on latest build.

**Comment by ApexPredaturr** [comment]
I have one set that goes normal -> normal -> rotating but even that one I had to do some weird Houdini magic to get it to work. This one I submitted the issue for will not let me no matter what I do. Interesting it works for Prom though.

**Comment by Prometheus0000** [comment]
Are you using a thermos server, we can blame thermos for almost anything.

**Comment by ApexPredaturr** [comment]
Nope Forge via MultiMC 🤷🏽‍♂️

**Comment by Ngar1** [comment]
on myFTB Server (Thermos?) works rotating rotating elevator fine

**Comment by kubasz** [comment]
I couldn't reproduce this locally, I found an issue with placing colored elevators and fixed that - other than that, the code checks for an IElevator implementation and does not care which implementation (elevator or rotating elevator) it is at any point, so I can't see how there can be a difference.

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
