### ISSUE TITLE
quest 1659 wrong capsule in retrieval task

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#8582]
### Your GTNH Discord Username

CatsLeftEar

### Your Pack Version

2.1.1.0

### Your Server

Epsilon

### Type of Server

Thermos

### Your Expectation

Expected quest #1659 to have capsule with GT enderium

### The Reality

Quest asks for unobtainable capsule with Tinker's construct enderium

### Your Proposal

change capsules

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
This should be fixed in dev already.
