### ISSUE TITLE
Make IC2 fluid regulator require no energy to work

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8583]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Proposal

The IC2 fluid regulator is used as a fine automation tool for plasma flow control on plasma turbines and it shouldn't require energy to work for two reasons : 

- All the gregtech covers don't need power to work anymore and this machine has a similar utility as what the gregtech covers can do

- sometimes the cable powering the regulator randomly stops delivering energy packets to the ragulator, all the packets go to the energy buffer, the regulator will stop because the cable stops powering it, it causes plasma turbines to randomly stop and the user has to go around the base to find the turbine that stoped

For instance here my turbine randomly stopped despite the fact that I didn't touch the setup and it was running fine for the previous 500+hours
![2021-09-23_02 33 27](https://user-images.githubusercontent.com/57050655/134439905-1e20e95f-d91c-4346-bdca-d432a5270afd.png)

### Your Goal

see above

### Your Vision

yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
Why use it over the GT fluid regulator? You do know it has finer control to it now, right? I don't see any reason to even have this block be craftable any more.

**Comment by Alexdoru** [comment]
I did not know it has finer control now lmao

**Comment by GTNH-Afx237v7** [comment]
Yeah that had been introduced some time ago and works fine, all my plasma turbines use the GT covers and it works like a charm.

**Comment by Alexdoru** [comment]
can close this ticket then

**Comment by repo-alt** [comment]
It would be nice if someone actually compiled a changelog with new features once in a while
