### ISSUE TITLE
Suspiciously cheap craft of iron and diamond bows (Mine & Blade: Battlegear 2)

### ISSUE THREAD

**Issue by RinWate** [GTNewHorizons/GT-New-Horizons-Modpack#8586]
### Your GTNH Discord Username

RinWate#5645

### Your Pack Version

2.1.1.0

### Your Proposal

Crafting recipe of standard bow is using assembler, but iron and diamond bows just can be crafted using default style of minecraft recipes.

### Your Goal

Iron and diamond bows crafting recipe must be Gregified

Standart (Greg-style) bow recipe:
![image](https://user-images.githubusercontent.com/42698624/134521505-d4a31b35-146e-421d-9a4e-5dbfce845574.png)

Iron and diamond bows (Non-gregified):
![image](https://user-images.githubusercontent.com/42698624/134521660-dd362ddf-4dfd-46c9-8b78-f11482b2f737.png)
![image](https://user-images.githubusercontent.com/42698624/134521731-c3b67bc0-1398-4dcf-946b-b24cccf344a6.png)

### Your Vision

Iron and diamond bows crafting recipe must be Gregified

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Minepolz320** [comment]
Hmmm...

**Comment by repo-alt** [comment]
Who even uses non-tinkers bows

**Comment by RinWate** [comment]
@repo-alt nobody. But i think it's callous eyes
