### ISSUE TITLE
Taking items out of chest while machine outputting to it, game crashed.

### ISSUE THREAD

**Issue by ApexPredaturr** [GTNewHorizons/GT-New-Horizons-Modpack#8588]
### Your GTNH Discord Username

ApexPredaturr#3181

### Your Pack Version

2.1.1.0

### Your Server

SP

### Your Actions

Pulling cleaned dust out of chest that a washer was outputting to. Just loaded into game about 2 minutes prior.

### Crash Report

https://paste.ee/p/hDqE1

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ApexPredaturr** [comment]
[crash-2021-09-23_13.36.47-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7219749/crash-2021-09-23_13.36.47-client.txt)

**Comment by Pxx500** [comment]
I wonder if this issue has the same cause as my unresolved issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7959
