### ISSUE TITLE
Add a recipe for crafting natura clouds

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#8589]
### Your GTNH Discord Username

Logos#2981

### Your Pack Version

2.1.1.0

### Your Proposal

I would propose adding a recipe by which natura clouds may be crafted, giving a way to obtain them aside from mining naturally existing clouds. The precise recipe doesn't matter too much; it might be steam in a fluid solidifier, it might involve ender i/o's cloud seed.

### Your Goal

At present, the only way I know of to obtain these blocks is by mining them out of the sky in chunks generated before cloud generation was disabled in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7092. A method to obtain them through crafting used to exist in the cloud in a bottle, but this recipe was disabled apparently due to issues with griefing in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/1051.

This makes clouds a limited resource which may be entirely unavailable on servers created after 2020/12/12, which I don't believe was intended

### Your Vision

Having access to cloud blocks would add to the palette of blocks available for base building, and be especially useful for certain building styles such as settlements built in the clouds, or for building custom cloud layers and storms.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by YannickMG** [comment]
How about spawning some of these clouds in the aftermath of a machine's explosion?
