### ISSUE TITLE
Wrench able to break wires

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8590]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Your Expectation

I shouldn't be able to break wires with a wrench

### The Reality

I am able to break wires with a wrench (HV) neutroniu
![2021-09-23_23 58 44](https://user-images.githubusercontent.com/57050655/134592700-3ac63361-b4bd-4df5-b226-e4ee8aa23cdd.png)
m

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Elisis** [comment]
Does breaking it return the item?

**Comment by Alexdoru** [comment]
yes it does

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4037

**Comment by Alexdoru** [comment]
I was wearing traveller’s gloves and apparently that’s causing the bug
