### ISSUE TITLE
Can't craft a spruce fence

### ISSUE THREAD

**Issue by queenizzy** [GTNewHorizons/GT-New-Horizons-Modpack#8591]
### Your GTNH Discord Username

isabellej#1289

### Your Pack Version

2.1.1.0

### Your Server

SP

### Your Expectation

Tried to craft a spruce fence with the normal recipe, (6 sticks and 3 spruce planks), expected a spruce fence from extra trees.

### The Reality

The only thing that would craft was a normal vanilla oak fence.

### Your Proposal

How do I get the spruce fence to correctly craft?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Probably need to move these to chisel recipes instead.
