### ISSUE TITLE
Make it more obvious how to get Rubber for LV Machine Hull

### ISSUE THREAD

**Issue by DarkYuan** [GTNewHorizons/GT-New-Horizons-Modpack#8592]
### Your GTNH Discord Username

DarkYuan#5002

### Your Pack Version

2.1.1.0

### Your Proposal

It's possible for the player to make it all the way to the LV machine hull quest without knowing how to make the necessary rubber. I'd suggest changing this one of two ways:
- Making the sulfur ore quest visible with either the Nether OR extractor quest (instead of AND), so it hints at getting access to the Nether to progress further.
- Gating the machine hull quest after the Nether instead of right after steel.

### Your Goal

Showing the player how to make rubber earlier.

### Your Vision

I was confused flipping through all the recipes to figure out how to get the rubber I needed, not realizing there was still a main quest line to do.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
I already changed the quests, this ticket might be obsolete, go check 2.1.1.3.

**Comment by DarkYuan** [comment]
Ah, I see there were some changes around those lines. It must just not be on Curseforge yet.

**Comment by Prometheus0000** [comment]
There won't be a CF build for a loooong time. Not until the next stable build, which is nowhere near. So, like next year?

**Comment by DarkYuan** [comment]
Oh! Well then consider this fixed in dev I guess.

**Comment by Prometheus0000** [comment]
I'm not sure it's fixed, I'm just saying it might be.

**Comment by DarkYuan** [comment]
Probably not quite the way I suggested, but I will download 2.1.1.3 to try out soon and give more feedback.
