### ISSUE TITLE
exchange reauth for oauth

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8593]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Original Request

exchanging reauth for oauth

### Responding developer

@Dream-Master 

### Context

https://discord.com/channels/181078474394566657/522098956491030558/890590398811082812

### Developer's Promise

.

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8080/view/3rd%20Party%20Mods/job/Oauth/
