### ISSUE TITLE
Make Mega EBF controllable

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#8598]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.1.2

### Your Proposal

The Mega EBF can not be controlled by a machine controller cover, since the controller is encased by glass completely. The glass can also not even strongly powered by a torch or repeater, so the only way to controll it would be using the front face, but then you could no longer see the tooltip etc...

### Your Goal

Add a way to control it. The easiest way i can think of would be either move the controller down one level or allow one of the blocks touching the controller to be a heat proof casing instead of glass.

### Your Vision

Mega EBF being controllable would help a lot, e.g. when power is sparse and one would like to controll it based on battery contents etc...

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
You can use one of the wireless covers on the other sides. Check the quest in tips and tricks for how they work.

**Comment by Savallator** [comment]
Okay, i totally missed them, sorry. I guess this is not really needed then.
