### ISSUE TITLE
Rework some recipes lacking logic or common sense

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#8601]
### Your GTNH Discord Username

leagris

### Your Pack Version

2.1.1.3dev

### Your Proposal

Some recipes like this one below are lacking logic and common sense: ![](https://user-images.githubusercontent.com/73182109/134753811-a0ac04b6-5bd0-4b57-8338-2d7b382bb8bb.png)

1. 1 Ultimate battery, (ok), I would not have put it as 1st component, but it is not an issue. It is logical it is part of the recipe.
2. 4×frame: Non-sense. Frames are full-block assembled structures already. 1 frame would be plenty enough. Add some plates panels if you want to complete the structure. Although honestly, the final product is a block that is placed in-world. It should use a casing rather than multiple frames.  
  At the very least, if you don't want to introduce many manufactured complex ingredients like a machine casing add the ingredients that compose a machine casing (plates, cables).
3. 24 screws would be ok if these are part of the corresponding casing.
4. Circuit 6: This one is totally illogical. There is no 6 number neither in input ingredients, neither as an output of the recipe. This 6 is wholly arbitrary. Please don't do this. Never do this. The programmable circuit number used to relate to either the output count or an input count. This thing is already very abstract for the player. Don't add non-sense to it by choosing arbitrary unrelated number. I am also pretty sure that if you choose better input ingredients than 4 frames and 24 screws, you will create much less issues and have recipe not need a programmed circuit at all.

### Your Goal

Improve game-play

### Your Vision

Re-focus Gregtech and Pack onto coherent style, logic and re-introduce a bit of the fantasy that was gone with trying to make stuffs too realistic when it does not help.

Logic ≠ Realism

A logic recipe is a recipe that player is able to understand, make sense of it, memorise with classification because it is linked with logic.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
I don't have any problem with a PR of this, though keep in mind that it might have the same frames in the assline recipe that you'd want to change as well.

Dream demands all assembler recipes have programmed circuits, even if they don't need it.

**Comment by Alexdoru** [comment]
Don’t forget to change the assline recipe that fives the same block as well as the uncrafting recipe that retunes the ressources

**Comment by Dream-Master** [comment]
@Prometheus0000 i guess you not understand that a programmed circuit give us more flexibility to add recipes. I dont need to check if igredients x allready use. I ran often in the trap want to make a recipe and got another item i dont want.

**Comment by Prometheus0000** [comment]
That's why you always check to see if there's recipe conflicts?

**Comment by boubou19** [comment]
> That's why you always check to see if there's recipe conflicts?

yeah sure go through thousands of recipes each time you add one... Using circuit config like Dream does is just time saving.
