### ISSUE TITLE
Double components button in Pattern terminal 

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#8604]
### Your GTNH Discord Username

John S#7565

### Your Pack Version

2.1.1.2

### Your Proposal

Add the button in pattern terminal that is make all components(in and out) that's already inside pattern double  each time that button is pressed.

Here is screnshot with example of behavior:
https://i.imgur.com/VgAipyu.png

### Your Goal

It's feature mostly needed in midle-late game when you started to make components in big ammount. The usage of old pattern with 1x components makes much more server load compare with x4/x8/x64 etc recipes. But if you need manually to change hundreds of recipes it's pure nightmare to calculate mats, collect components and put it in the pattern for **EACH recipe** individually. So mos players just not make it at all and that make servers more laggy.

### Your Vision

Definitely that feature will push players to not make boring things and make servers TPS larger and that also will make players more happy.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
or, you use the the NEI ghost item function with stacks of the size you set? what recipe could justify this? i'm curious.

**Comment by Retster** [comment]
> Wow, that sounds pointless. Or maybe super-niche would be more accurate?

Maybe you add at least some arguments, or share your experience in such situation. Or you use always default amount of items?




> or, you use the the NEI ghost item function with stacks of the size you set? what recipe could justify this? i'm curious.
Use NEI ghost items is the same as make recipe manually, thre is no any difference. Same boring routine.

**Comment by Prometheus0000** [comment]
> Maybe you add at least some arguments, or share your experience in such situation. Or you use always default amount of items?

Do the ghost item thing, or, set it to the maximum number of items from the start, or do it over time instead of all at once.

**Comment by Retster** [comment]
> > Maybe you add at least some arguments, or share your experience in such situation. Or you use always default amount of items?
> 
> Do the ghost item thing, or, set it to the maximum number of items from the start, or do it over time instead of all at once.

Any actions with ghos items are equivalent to using ordinary items, and not solve problem at all. Because you need to calculate/collect items and manually make pattern with with corrected DIFFERENT values for each item.

**Comment by boubou19** [comment]
> Use NEI ghost items is the same as make recipe manually, thre is no any difference. Same boring routine.

I don't see why clicking on a button once you set up all the items in the terminal is different from setting it up with ghost items? and i think NEE is already implementing shift click from NEI already.

**Comment by Prometheus0000** [comment]
I don't see the problem. But I also don't want to argue with you about this, I was just stating my opinion.

**Comment by Retster** [comment]
> > Use NEI ghost items is the same as make recipe manually, thre is no any difference. Same boring routine.
> 
> I don't see why clicking on a button once you set up all the items in the terminal is different from setting it up with ghost items? and i think NEE is already implementing shift click from NEI already.

Because click count only. How much click you need to make the same like in screnshot attached?
And that is not problem at all if you need to change one recipe. But if you need to change 10 or 100 it's a huge pain in ass.

**Comment by Florexiz** [comment]
This can greatly increase QoL for volumetric flasks based AE systems and make switching from single item crafting to batch crafting for late game bases less tedious

**Comment by repo-alt** [comment]
I would have preferred if people used OC script for that, but I understand that it is kind of unfair to force OC on everyone.

**Comment by Retster** [comment]
> I would have preferred if people used OC script for that, but I understand that it is kind of unfair to force OC on everyone.

So hard to implement? It's not necesarry feature but greatly improving the QOL. Anyway take your time. And GTNH is the best pack ever.  Best regards.

**Comment by repo-alt** [comment]
The logic as you may guess is trivial, GUI work is a bit tedious. That was not an objection anyway.
