### ISSUE TITLE
Heavy Duty plate name unification

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#8605]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.1.2

### Your Server

private

### Your Expectation

When searching for "Heavy Duty", you find all the alloy ingots, and all plates except T1-3, sicne they are named "Heavy-Duty"

### The Reality

The names dont match.

### Your Proposal

Change the name of the Heavy-Duty Plates T1-3 to Heavy Duty Plates.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
Should be there: https://github.com/GTNewHorizons/Galacticraft/blob/40d95d7d1c00710b3b95027a0f0ca81d650876b2/src/main/resources/assets/galacticraftcore/lang/en_US.lang#L22

on mobile for now, so maybe someone is willing to take care of this

**Comment by Savallator** [comment]
The T2 and T3 plate have wrong still wrong names (Currently "Heavy-Duty", when it should be "Heavy Duty"), at least in 2.1.2.0.
