### ISSUE TITLE
Iridium and Osmium ore processing without water

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8606]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.1.0

### Your Server

MP(private server) and SP

### Type of Server

Cruicible

### Your Expectation

I checked the recipe for processing Iridium and Osmium ore  with Chemical Reactor.

### The Reality

Those recipes didn't consume any water
![2021-09-27_18 38 53](https://user-images.githubusercontent.com/40425798/134884565-278abaa1-f903-4394-9965-d12f69ed1c9c.png)
![2021-09-27_18 38 29](https://user-images.githubusercontent.com/40425798/134884574-05a4ca14-4ef8-4ffa-9ca6-8686aebf5704.png)
.

### Your Proposal

Fix it. I think some metal was produced in earlier versions, but I can't remember.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
because the output water should be molten osmium/iridium/platinum in origin recipe, bart nerf them into water. should we simply remove the water or replace them with something else?

**Comment by Prometheus0000** [comment]
I say replace with something useful, as you're already barely getting anything worthwhile out of these things compared to using it on a non-platline ore. Saltwater maybe?

**Comment by yukieiji** [comment]
What about Acidic Iridium Solution and Acidic Osmium Solution as not so far from the previous ones?

**Comment by GlodBlock** [comment]
> 
> 
> What about Acidic Iridium Solution and Acidic Osmium Solution as not so far from the previous ones?

what for molten plantium then?

> 
> 
> I say replace with something useful, as you're already barely getting anything worthwhile out of these things compared to using it on a non-platline ore. Saltwater maybe?

i think the salt water is a bit cheap.

**Comment by yukieiji** [comment]
>what for molten plantium then?
How about Platinum Concentrate or molten mithril?

**Comment by Prometheus0000** [comment]
Mithril is on the list of things I want to remove. Why would you even want it?

**Comment by yukieiji** [comment]
I only suggested it because that's what the fluids was, not far from the platinum.

**Comment by Prometheus0000** [comment]
Mithril is a magical fantasy metal, Iridium and osmium are real.

**Comment by yukieiji** [comment]
But other than that, I just didn't find anything fluids that wasn't too far from platinum.

**Comment by GTNH-Afx237v7** [comment]
I believe it would be OK to receive some quantity of acidic osmium / iridium solution and platinum concentrate, but keep it at a low rate like 100mb.

**Comment by yukieiji** [comment]
Acidic osmium solution is 1 osmium in 8000L, acidic iridium solution is 1 iridium in 1000L, and platinum concentrate is 1 platinum in 9000L(v2.1.1.0)
Acidic osmium solution and acidic iridium solution need to be processed and amounts, so no need to be low rate them, in my opinion.

**Comment by GlodBlock** [comment]
> Acidic osmium solution is 1 osmium in 8000L

it is 1 Os dust in 10000L acidic osmium solution

**Comment by Prometheus0000** [comment]
Why would you add it to a milestone if it's fixed? And why not close it?

**Comment by Dream-Master** [comment]
it get closed in a fe days anyway. Milestone for next release only to tag this issue to see in wich issue solven in which version
