### ISSUE TITLE
Show Hot Ingots in NEI

### ISSUE THREAD

**Issue by Bauntilein** [GTNewHorizons/GT-New-Horizons-Modpack#8609]
### Your GTNH Discord Username

Baunti#1259

### Your Pack Version

2.1.1.0

### Your Proposal

Most of the hot ingots you can smelt at the moment are hidden in NEI, which made it difficult for us to automate Titanium ingots with SFM, as they simply don't show up in the filter section. We found a workaround for this at this point but it'd be handier if it would be just shown in NEI.

### Your Goal

Due to this feature missing, automation processes made with SFM are made harder and you have to find workarounds for it to work properly, changing it would make it alot easier.

### Your Vision

Mentioned above.^^

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
Again?

**Comment by Pxx500** [comment]
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8464

**Comment by Bauntilein** [comment]
Ah, I searched multiple times to see if there was already an issue about this but didn't find that one. Excuse me.^^
