### ISSUE TITLE
Missleading of #2306 (I also fucked up)

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#8612]
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Your Expectation

Actually it's also my fault, can't say the opposite, but well
![image](https://user-images.githubusercontent.com/76914762/135119637-c8d13240-8fd0-435c-b1c1-1cf597ede66e.png)
it said "you can void it" so, I voided it, but the quest need the steam for completation

### The Reality

.

### Your Proposal

change the line to "keep it for the quest"

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
It shows right there the quest requirements, and it talks about automating the previous sentence, and HRT isn't even the next step. I can't help it if you messed up, putting text saying 'don't void it until you complete the quest' would just insult people's intelligence.

You can just get some more cells of steam with a fluid heater or w/e, so I don't see any problem.
