### ISSUE TITLE
Change stacksize of hot ingots from 16 to 64

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#8613]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.1.0

### Your Proposal

Change stacksize of hot ingots from 16 to 64 as this limitation has no actual purpose.

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
I think it's 
```java
ingotHot("Hot Ingots", "Hot ", " Ingot", true, true, false, false, false, false, false, true, false, false, B[1], M * 1, 16, 12), // A hot Ingot, which has to be cooled down by a Vacuum Freezer.
```
in OrePrefixes.

**Comment by Dream-Master** [comment]
I think it is wired at all you can hold hot ingots with your hands. 16 or 64.

**Comment by Prometheus0000** [comment]
While that's true, you can also hold neutronium, which is even weirder.

**Comment by bombcar** [comment]
The long term solution is removing hot ingots entirely and the ebf drains liquid into the now liquid supporting vacuum freeze

**Comment by Alexdoru** [comment]
> The long term solution is removing hot ingots entirely and the ebf drains liquid into the now liquid supporting vacuum freeze

Please no, it is going to be a mess with Mega EBF spitting out thousands of different ingots per second

**Comment by boubou19** [comment]
fluids are less easier to handle than items for both game and players so let's keep it that way. Also imagine the amount of new fluids required to replace the hot ingots. That sounds like a terrible idea.

**Comment by Dream-Master** [comment]
Yes but the fluid out of ebf. will be the end goal. So we need to find a way handle fluids better. In factorio it works too

**Comment by Prometheus0000** [comment]
> Yes but the fluid out of ebf. will be the end goal.

What? Who decided this and when? I've never heard anything about this? Where's the discussion about it? Also, this is basically just the ABS, which I thought people didn't like?

**Comment by boubou19** [comment]
can't wait to see players handle 36864 mb / tick of fluid with the mbf. Outside of the endertanks having no bandwith, i don't think there are much alternatives, and replacing the vacuum freezer with a PA of fluid soldifiers isn't much of a change, except the time to solidify the ingots at endgame will be 1 tick instead of a couple of seconds for endgame ingots. I don't feel like it's an interesting change.

**Comment by hohounk** [comment]
Long distance pipelines have no throughput cap and can teleport things around as fast as you can pump fluids into them. A single LuV pump as a cover can move 32760mb/t

**Comment by boubou19** [comment]
> Long distance pipelines have no throughput cap and can teleport things around as fast as you can pump fluids into them. A single LuV pump as a cover can move 32760mb/t

I'd personally use the ender tanks, to avoid the cabling, but still that change is not really needed imo.
