### ISSUE TITLE
Add better ways of handling the item/fluid voiding in the GT multiblocks

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8615]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Proposal

My suggestion is to add two things:
1) a "smart mode" for the multiblocks, that would likely behave like GT++ when full, ie stop processing the input if it can't add the recipe output in the hatches/buses (default off for backward compat with current setups)

2) add GT overflow covers/rework gt++ ones, as the GT++ ones work only on fluids, and are barely usable precisely, so you can start voiding stuff when the GT item/fluid container is full.

### Your Goal

I suggest those two options because they are lacking in the game, and right now players use some redstone as an alternative, which is fun at start when you have the design, but then it's boring when you have to place it everywhere, while it could just be a part of GT itself. 

### Your Vision

About the smart mode:

- It is a shame that single block machines do that, but multiblock don't do that. It feels like a regression where multiblocks should actually be smarter than the single blocks. 
- allowing a smart mode *could* reduce the lag from all the complex chem lines that players do with LCRs due to it's perfect overclock, by removing all the redstone from those lines.
- the smart mode would remove some tedium while making the line by just setting the mode on the controller instead of doing a redstone control on each output bus/hatch desired.

About the overflow cover:
- many storage mode do have their overflow/void upgrade, but not GT, so it would make GT a bit more complete, by adding a cover that would void received content in any GT fluid/item container.
- Sometimes, when you use a multi, you do want to avoid voiding part of the recipe outputs, but not save all the recipe outputs (typically you want to trash water, but want to save all the other outputs of the recipe). This is not achievable with the smart mode, and will result in redstone usage if this cover doesn't exist.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by POPlol333** [comment]
Could prevent dumbass's move as mine 👍

**Comment by bombcar** [comment]
Would it make sense to add additional hatches/busses of a non-voiding type?

**Comment by combusterf** [comment]
It would also reduce lag from players like me that resort to stacking arrays of singleblocks to guarantuee non-voiding behaviour instead

**Comment by boubou19** [comment]
> Would it make sense to add additional hatches/busses of a non-voiding type?

well voiding mode has been proven to be a result of the logic in gt multis (see gt++). I think adding overflow covers for item/fluids will be more beneficial than your idea, because they'll be able to apply on tanks and superchests as well.

**Comment by bombcar** [comment]
Voiding is a “bad surprise” you have to worry about - but later it becomes a useful feature (like I might want to void water and co2). 

Another option could be - hatch and bus equal or greater to muffler (or other part) no voiding - but lower - voiding. So if you build an EBF with an EV muffler but LV hatches you’ll void, but if you upgrade the hatches you won’t. 

Against - that could be a noobtrap again.

**Comment by Pxx500** [comment]
> Voiding is a “bad surprise” you have to worry about - but later it becomes a useful feature (like I might want to void water and co2).
> 
> Another option could be - hatch and bus equal or greater to muffler (or other part) no voiding - but lower - voiding. So if you build an EBF with an EV muffler but LV hatches you’ll void, but if you upgrade the hatches you won’t.
> 
> Against - that could be a noobtrap again.

Cover makes much more sense since in some machines you want small output buses/hatches

**Comment by boubou19** [comment]
>Voiding is a “bad surprise” you have to worry about - but later it becomes a useful feature (like I might want to void water and co2).
Another option could be - hatch and bus equal or greater to muffler (or other part) no voiding - but lower - voiding. So if you build an EBF with an EV muffler but LV hatches you’ll void, but if you upgrade the hatches you won’t.
Against - that could be a noobtrap again.

that seems to be complicated for the sake of it.
What about selecting normal gt voiding mode or smart mode that avoid any loss, then if you want to void part of it, just put overflow covers where you want?

**Comment by bombcar** [comment]
That also works - maybe it would need to be upgraded in steps somehow. Can the code do different things for “existing” multiblocks vs new ones? I know I’ve seen “old” seismics that upgrade to new ones, perhaps that could be done for the controller blocks?

Otherwise existing players who rely on voiding have to go set it up, and if machines void as default it doesn’t help new players much.

**Comment by bombcar** [comment]
Another voiding is powerloss void - I think that is a decent “punishment” but perhaps instead of voiding the materials it should produce useless output? Scrap?

**Comment by Pxx500** [comment]
> That also works - maybe it would need to be upgraded in steps somehow. Can the code do different things for “existing” multiblocks vs new ones? I know I’ve seen “old” seismics that upgrade to new ones, perhaps that could be done for the controller blocks?
> 
> Otherwise existing players who rely on voiding have to go set it up, and if machines void as default it doesn’t help new players much.
 "a "smart mode" for the multiblocks, that would likely behave like GT++ when full, ie stop processing the input if it can't add the recipe output in the hatches/buses (default off for backward compat with current setups)" - Boubou

**Comment by Pxx500** [comment]
> Another voiding is powerloss void - I think that is a decent “punishment” but perhaps instead of voiding the materials it should produce useless output? Scrap?

This issue is not about that

**Comment by GTNH-Colen** [comment]
Smart mode needs to have consequences though, someone on the discord suggested increasing processing time by say 20% if smart mode is on. Or even losing perfect OC capabilities with the LCR. If there is no consequences then it's just a straight buff, I think it's more interesting if there is some side effect.

**Comment by mitchej123** [comment]
I'd propose we approach this from a "what should the design be" rather than anchoring on what it is now.  As discussed with Leagris, the state of GT5u is (often) not what greg intended, but was unfinished -- ie voiding.  This was not the case in earlier versions, and isn't the case in later versions.  Rather than looking at it as a buff/nerf; let's independently decide what the behavior should be.  I'd say the smart mode should be the baseline, and if we want to keep voiding/expert mode, that should have a *slight* advantage.

**Comment by combusterf** [comment]
I think Bombcar's suggestion of having a dedicated non-voiding output bus/hatch is a very straightforward and practical one - you can craft one from the normal with logic components not unlike the ones you would use to manually automate it. Then you have your choice and your optional investment and possible tech gate set up to qualify for balance.

Crafting a hatch with a HV circuit could very well be an appropriate implementation for this.

**Comment by Prometheus0000** [comment]
> I'd propose we approach this from a "what should the design be" rather than anchoring on what it is now. As discussed with Leagris, the state of GT5u is (often) not what greg intended, but was unfinished -- ie voiding. This was not the case in earlier versions, and isn't the case in later versions. Rather than looking at it as a buff/nerf; let's independently decide what the behavior should be. I'd say the smart mode should be the baseline, and if we want to keep voiding/expert mode, that should have a slight advantage.

From this point of view you could say that voiding is a feature, and the upgrade would be voiding stuff you don't want instead of halting. Presumably with slightly more expensive hatches/busses as mentioned, or a cover.

**Comment by boubou19** [comment]
> I think Bombcar's suggestion of having a dedicated non-voiding output bus/hatch is a very straightforward and practical one - you can craft one from the normal with logic components not unlike the ones you would use to manually automate it. Then you have your choice and your optional investment and possible tech gate set up to qualify for balance.

> Crafting a hatch with a HV circuit could very well be an appropriate implementation for this.

Well that would only cover the case where you want to void part of the recipe, but not cover the voiding needs for tanks/super chests. I totally know you can void stuff by sending it through the ExU trashes for exemple, i feel like GT itself should have a way to do it. At worse, giving new overflow covers to players will just give them one more way of doing the voiding, which can't hurt.

**Comment by hohounk** [comment]
There are loads of quests and items in the pack with the singular goal of voiding things.

It'd make sense to have the default to be non-voiding and if one wants to void then they combine the hatch with some machine that has the feature.
