### ISSUE TITLE
Improve the output of Solid-Oxide Fuel Cells

### ISSUE THREAD

**Issue by Steelux8** [GTNewHorizons/GT-New-Horizons-Modpack#8617]
### Your GTNH Discord Username

Steelux#1934

### Your Pack Version

2.1.1.3 dev

### Your Proposal

I will focus on the Mk I version of the multiblock, since it's the one I was going to build, currently being in the HV tier.

The Solid-Oxide Fuel Cell (SOFC) works like a singleblock gas turbine, but it produces 2 HV amps and an additional 18000 L/s of steam, which is 450 EU/t at 100% efficiency, not even a third HV amp. It's almost equivalent to 3 singleblock HV turbines, while being a 3x3x5 multiblock. Even worse, it consumes 400 L/s of Oxygen, even though it only has an efficiency of 97%, which is higher than singleblock turbines but at a hefty cost, and much lower than multiblock turbines that can be built in EV. The extra bonus of using this multiblock is that it produces no pollution, but obviously that feature is disabled right now. Moreso, I personally enabled it, and the amount of pollution saved is minimal, given how few singleblock turbines this replaces.

My suggestion is to increase the input and output, perhaps to 4 or 5 HV amps with a considerable bonus in steam, and/or increase the efficiency to go above 100%, but not the same as EV turbines. Additionally, the oxygen input should be reduced for this tier.

The Mk II version should be changed as well, although I'm not personally in that tier yet.

### Your Goal

This multiblock has an interesting design and is a rare option for multiblock generators before EV, so I think it has merit in being more useful since it's already in the game.

### Your Vision

It's unlikely that a lot of people would use this instead of Diesel, unless it was made really efficient, but for people that use Benzene, this could be both a useful and a very fun addition to the powergen setup before settling in EV and switching to multiblock turbines.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
Given that this is a low-pollution gen, and there's no pollution right now, there's no way to balance it until the pollution rework is done unless we want to do it twice.

**Comment by Steelux8** [comment]
> Given that this is a low-pollution gen, and there's no pollution right now, there's no way to balance it until the pollution rework is done unless we want to do it twice.

Pollution rework is now underway so this issue might be worth considering.

**Comment by bombcar** [comment]
Power at a given tier that doesn’t pollution can be compared (roughy) to similar power that does + plus the cost of mitigation. So if this is still worse than normal gens + scrubbers then it should be buffed somehow.
