### ISSUE TITLE
EU informations retrieved from opencomputers returns wrong value if said value is > 2^32 EU

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8619]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

Retrieving EU value from a GT machine via OC should correctly work when using normal calls to get it.

### The Reality

Retrieving EU value via OC for players with big EU storage is painful when the EU value is above 2^32 EU:

when the value is below 2^32 EU:
```lua
lsc = component.proxy(lsc_address)
sensorInformation = lsc:getSensorInformation()
storedEU = lsc:getEUStored()
EUCapacity = lsc:getEUMaxStored()

```

when the value is above 2^32 (credit to Sampsa)
```lua
lsc = component.proxy(lsc_address)
sensorInformation = lsc:getSensorInformation()
storedEU = parser.getInteger(sensorInformation[2])
EUCapacity = parser.getInteger(sensorInformation[3])
function parser.getInteger(string)
    local numberString = string.gsub(string, "([^0-9]+)", "")
    if tonumber(numberString) then
        return math.floor(tonumber(numberString) + 0)
    end
    return nil
end
```

### Your Proposal

It would be cool if the overflow could be fixed, so we don't end up using heavy code just to work around it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by asiekierka** [comment]
Will be fixed in OpenComputers 1.8.0-pre1 and above

**Comment by repo-alt** [comment]
(reopening to test)

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/205454640-3b0b0398-4d9c-4280-9515-c6b9c950691d.png)
Looks like it works now!
