### ISSUE TITLE
A problem of conveyor

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#8621]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

delta

### Your Proposal

![image](https://user-images.githubusercontent.com/59776356/135608840-023d275f-9035-4889-8bfa-36a0adbb9ccb.png)
![image](https://user-images.githubusercontent.com/59776356/135608852-23ed4d5d-c0d3-4a6a-b578-6a2dea5b7dad.png)
a problem of conveyor is it can't import and export at the same time
because AE interface cannot Auto eject
so I need 2 interface one for export and one for import
which is weird

### Your Goal

allow conveyor import and export at the same time just like the item conduit

### Your Vision

More compact and clean machine setup 
Reduce the number of surplus conveyor belts
Better quality of life

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
put the conveyor into import allow output, then put the output side of the machine on the same side of the conveyor, allow the onput from output side with a screwdriver on the front side, then enable the auto output in the machine.
