### ISSUE TITLE
Silicon-Aluminium-change

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#8623]
### Your GTNH Discord Username

DreamMasterXXL

### Your Pack Version

2.1.1.4-dev

### Your Proposal

Changing how Silicon and Aluminium is smelted in the EBF.

### Your Goal

Aluminium and Nitrogen is the existing recipes. This not realy fit.
We change Titanium Line, Tungsten Line, Platinum Line and the Naquadah Line.
So its time to change the Alu Line as well.

### Your Vision

Make Alu processing more interresting. You can smelt Aluminium out of Aluminiumoxide and Cryolite and save a lot of energy compared to the old recipes.
You can used more advanced processing to make the alu output better per Bauxite Ore.

We can change the values if they not fit. You can make suggestions. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

* https://github.com/GTNewHorizons/GT5-Unofficial/pull/670
* https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/209
* https://github.com/GTNewHorizons/bartworks/pull/45
* https://github.com/GTNewHorizons/GTplusplus/pull/29

TODO LIST:
- [x] Add old recipe back 80 sec 120 eu alu dust = alu ingot
- [x] Add new recipe 60 sec with oxygen and alu dust = alu ingot

**Comment by Dream-Master** [comment]
Silicon changes

**Comment by Dream-Master** [comment]
Alumina or Aluminiumoxide can be get from mot of the Electrolyzer recipes instead of pure Aluminium.
Only Pure Aluminium Ores and a few others give pure Aluminium Dust

**Comment by Dream-Master** [comment]
Cryolite can be found the the Twilight Forest in the LEad and Galena mix (need new chuncks generated)
or can make in a gt recipe i will show below

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/135624667-47468807-25df-40e5-bdc2-db542d07c964.png)
![image](https://user-images.githubusercontent.com/2970688/135624697-1b0e1b60-27e5-41b1-8d04-1aadb0a9d537.png)
![image](https://user-images.githubusercontent.com/2970688/135625154-2c833746-e8be-4459-9fef-b6c93d3f4624.png)
![image](https://user-images.githubusercontent.com/2970688/135625172-e046dec9-b0fa-4aa5-a228-386b3008a622.png)
![image](https://user-images.githubusercontent.com/2970688/135625191-aa8d4be8-fdbe-48c6-a3ed-ee89e9b33741.png)
![image](https://user-images.githubusercontent.com/2970688/135625220-9101c7d0-0f8b-4629-9b73-cde51b35565b.png)

**Comment by Dream-Master** [comment]
Aluminium Hydroxide can be made out of mixing Bauxite and SodiumHydroxide
![image](https://user-images.githubusercontent.com/2970688/135625378-baaacfbe-ad6b-4958-8281-ec2a35f3092d.png)
and smelted to Alumina in the EBF
![image](https://user-images.githubusercontent.com/2970688/135625432-cd4547bb-1fdc-41be-9d17-c6af9e647694.png)

**Comment by Dream-Master** [comment]
Alumina Dust can be made out of Sapphire, Blue Sapphire and Ruby Dust as well
With Carbon and without.
![image](https://user-images.githubusercontent.com/2970688/135625654-aa987f6d-0054-48f0-9590-cd0b0a9f6be6.png)
![image](https://user-images.githubusercontent.com/2970688/135625665-95325e47-c4c8-49eb-8aa8-5ecfa6e14db4.png)
![image](https://user-images.githubusercontent.com/2970688/135625698-fd5b0f5e-892a-4545-836d-177aef949432.png)

**Comment by Dream-Master** [comment]
Sodium Aluminate can be used to recycle all your Aluminium Dust.
![image](https://user-images.githubusercontent.com/2970688/135626265-1d9251d5-bd0c-478a-b32d-6a7f2e00712a.png)
![image](https://user-images.githubusercontent.com/2970688/135626348-897613a7-7061-440d-a4d5-178bdd6032fb.png)
![image](https://user-images.githubusercontent.com/2970688/135626443-d723a683-22be-44b4-a0ef-d72818eff50b.png)
![image](https://user-images.githubusercontent.com/2970688/135626455-d1aa5106-3a79-4fd2-a894-fdc5bba30332.png)
![image](https://user-images.githubusercontent.com/2970688/135626469-9409e9b0-ebbf-4bd7-805a-406465a4907d.png)
maybe we can add a recipe used Alumina as well

**Comment by Dream-Master** [comment]
more advanced variant
![image](https://user-images.githubusercontent.com/2970688/135626583-c737903d-d9e8-4172-b183-c2bc931379f3.png)
or with sodium carbonate
![image](https://user-images.githubusercontent.com/2970688/135626611-1aedf8ab-7f3c-4a2f-8017-b847349a783e.png)
![image](https://user-images.githubusercontent.com/2970688/135626633-43c82dd6-2d60-4a1c-b0e9-219477f6d195.png)
![image](https://user-images.githubusercontent.com/2970688/135626666-a4c697ae-4891-45d2-aa88-3ceeb2989dca.png)
maybe we add a alumina recipe varian too

**Comment by Dream-Master** [comment]
Autoclave get 2 output slots in LV and MV
![image](https://user-images.githubusercontent.com/2970688/135626832-a4a28f77-39f4-467e-9ee7-f55c109f0681.png)
3 in HV
![image](https://user-images.githubusercontent.com/2970688/135626923-2e7f99ff-dd1d-4094-8499-b6e3b9a93349.png)
4 in EV
![image](https://user-images.githubusercontent.com/2970688/135626990-7f3363e0-4b4b-45c4-a0a0-938cc2be90cd.png)

**Comment by Dream-Master** [comment]
Please discuss in the #early-game-aluminium-rework channel on Discord and here on Github. Thanks

**Comment by Pyromanc3r** [comment]
Well, I think that alternative or new ways to create materials and sub-products is always good. Even if it is not always profitable. Sometimes you want to create something in a non-standard way using new machines. Or for example, get rid of excess materials that do not want to throw out :) Sometimes it is easier to go to the goal with a heavy way than light. In any case, it is some kind of new gaming experience.

**Comment by Savallator** [comment]
May I ask about the reasoning for the SiO2 Electrolyzing recipe being removed in combination with this? I mean, it provided a complicated, multi-step way to make Oxygen in early MV. It felt quite rewarding actually when it was done, and needed a complex chain consisting of 6 different steps together with a method to recirculate some of the O2... Actually, instead of removing this imho it should have gotten a quest to explain it, so people can use it to learn the basics for the more difficult chemical processing lines later.
Was it really needed to remove that, when people still can easily spam crops to get O2 in much larger quantities?
