### ISSUE TITLE
Move bauxite to overworld, replace moon bauxite with rutile

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#8624]
### Your GTNH Discord Username

querns#3785

### Your Pack Version

2.1.1.0

### Your Proposal

As part of the aluminum changes in #8623, move Bauxite Ore to the overworld (or TF/Nether), and replace all its spawns on the moon with Rutile Ore.

As part of this process, eliminate the Rutile dust output from processing Bauxite. This will not block no-rocket runs, as the primary source of bauxite today in no-rocket runs (centrifuging stone dust) has an ilmenite output, which should allow for titanium acquisition without having a rocket.

### Your Goal

Increasing the availability of aluminum-bearing ores in the overworld will allow for more raw materials for producing aluminum at low tech levels. It will also allow for clay to potentially be nerfed as an aluminum source, if needed.

### Your Vision

Doing this increases the availability of aluminum in the early game without negatively affecting availability of titanium from the moon.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
Any idea what ore it should replace though? Or if a new vein should be added or if it should be a small ore (probably not a good idea).

**Comment by querns** [comment]
I think a straight swap of the bauxite in an ilmenite vein would work.

![image](https://user-images.githubusercontent.com/33518699/135651586-1d46275e-0356-4f08-8131-e813e55c8ef6.png)

Alternatively, if this is too easy, change the bauxite to also be ilmenite, and make the rutile sporadic inside.

**Comment by Prometheus0000** [comment]
What? I don't mean on the moon.

**Comment by querns** [comment]
Perhaps change the kaolinite vein to be bauxite instead? Remove the kaolinite entirely, and keep the zeolite, fullers earth, and glauconite. Kaolinite's only use is to be electrolyzed for aluminum dust.

A completely new vein would also work.

**Comment by Prometheus0000** [comment]
Is there none with 2 of the same thing? I don't want to make more orphaned ores that are DD only.

**Comment by querns** [comment]
The fullers earth component of a kaolinite vein could be swapped instead. Fullers earth is available in a basaltic mineral sand vein as well.

**Comment by bombcar** [comment]
Bauxite is associated with kaolinite in the real world, so that would be a good option. Fullers earth isn't used until later.

**Comment by Elisis** [comment]
We can't really change ores that drastically, else players end up missing out on ores on worlds already generated.

**Comment by querns** [comment]
One thing that was brought to my attention is that the Metal Mixture Dust centrifuging recipe is at EV voltage, so it isn't suitable for acquiring pre-moon titanium in no-rocket runs. Currently, the primary way to get the seed titanium you need for titanium crops in no-rocket is to laboriously search the world for aluminium gravel, then process it. This relies on the rutile component of the bauxite that arises as a byproduct of aluminium gravel processing.

**Comment by Dream-Master** [comment]
We not touch overworld. Ores are set.
