### ISSUE TITLE
ME output bus doesn't respect storage priority

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8625]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Your Expectation

I have 4 multi smelters in my ore processing system, they have ME output bus, the storage in the system is 3 infinty chests with decresing storage priority.

 I expect the copper ingots to be stored in the first chest that has a priority 10.

![image](https://user-images.githubusercontent.com/57050655/135651082-17afe3b0-c4b8-46de-b6e1-1e04402269fa.png)

### The Reality

Some of the ingots end up in the chest with priority 5 
![image](https://user-images.githubusercontent.com/57050655/135651183-e7e51930-941a-4edf-9b3a-354b5a4bff49.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Does it do this with a non-infinity chest though?

**Comment by GTNH-Colen** [comment]
I have also been experiencing this lately, I think it's related to the fact the inf chest can only accept items so fast so if you try go faster it will just assume it is full and move to the next priority. I could but wrong but this is my best guess.

**Comment by Alexdoru** [comment]
Yes it’s in the same network
