### ISSUE TITLE
Change Tinker's Construct cast material away from Aluminum Brass and remove Aluminum Gravel

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#8626]
### Your GTNH Discord Username

querns#3785

### Your Pack Version

2.1.1.0

### Your Proposal

As part of the aluminum changes in #8623, eliminate the dependence on rare aluminum spawns to create tool part casts in Tinker's Construct. With this, aluminum gravel can be eliminated.

### Your Goal

Right now, you confusingly need to gather aluminum for casts, since making casts out of gold is disabled in GTNH. Providing an alternate pathway for making casts with materials otherwise available means that you no longer need an MV material, processed in a strange and unique way, to make bronze age tools.

### Your Vision

Some ideas for replacement materials:

* Bronze. This already has an alloying recipe in the smeltery. One potential difficulty may be that tin-bearing ores (such as cassiterite) require a mining level of 3, which requires at least a leveled iron pickaxe to mine. Perhaps reduce the material hardness?
* Brass. This would require a new alloying recipe in the smeltery. Brass has very little use outside of a few LV components. Availability of zinc for alloying, however, is very low in the overworld.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by D-Cysteine** [comment]
Another possible idea is to provide an alternate recipe for aluminum brass specifically. I'm thinking that the place where this would make sense would be a crucible transmutation recipe, like `copper ingot + instrumentum = aluminum brass ingot` or something.

This would let us avoid needing to add cast recipes for a new material, in case that turns out to be tricky. We'd need to make sure that the crucible transmutation research is accessible early enough though. I did check that it's not possible to extract aluminum from aluminum brass, so it shouldn't be possible to use this as an alternate pathway to aluminum.

**Comment by Prometheus0000** [comment]
Uh, this is for the smeltery, which is for your first metal tools in steam. Way way way before thaum.

**Comment by bombcar** [comment]
One possible alternative is to *very early* use something like clay/stone "forms" that break after each use - and then when you get some basic equipment you can now make forms that are durable.

**Comment by querns** [comment]
In versions of TiCon after minecraft 1.7.10, they added just that -- you can melt clay in a smeltery, and use it to create a single-use mold.

**Comment by Dream-Master** [comment]
if someone can backport 1.12 stuff why not
