### ISSUE TITLE
Change Kanthal Coils to be in MV instead of HV

### ISSUE THREAD

**Issue by Steelux8** [GTNewHorizons/GT-New-Horizons-Modpack#8628]
### Your GTNH Discord Username

Steelux#1934

### Your Pack Version

2.1.1.3 dev

### Your Proposal

Changing the crafting process of Kanthal coils, the second coil tier, to allow them to be crafted at MV as the tooltip mentions, instead of being directly followed by the third tier, Nichrome, both in HV. Right now, both are crafted from ingots that need cooling, so both are locked behind Vacuum Freezer, but can be crafted one after the other without any other restrictions.

### Your Goal

Altering the process to use IC2 Coolant instead of a Vacuum Freezer, the same way Advanced Coke Ovens use it for Infernal Bricks.

![Capture](https://user-images.githubusercontent.com/70096037/135652258-d12718b1-d57d-4f36-a5d7-a39a21354d4f.PNG)

This change allows for coil crafting in MV, matching what the tooltip says about Kanthal coils (Coil Tier = Medium Voltage). The hot Kanthal ingot coming from the EBF could be changed so that it can be cooled down with IC2 coolant, instead of requiring the freezer.

### Your Vision

This change would add more content to the MV tier, since it's quite small compared to HV. Additionally, it allows EBF recipes to be locked in different ways.

For example, the aluminium change in #8623 has an option to use carbon dust, which is more common than the alternative, but needs a higher temperature than what Cupronickel can manage. Given it's the case, it would need progression until mid-HV, after you've spent aluminum to make a Vacuum Freezer, to make Kanthal Coils and use the cheaper aluminium recipe when it's barely needed anymore. With this change, it would become a recipe that's usable at mid-MV.

For reference, the temperatures for the 3 coils are as follows:

Cupronickel = 0-1801K (Low Voltage)
Kanthal = 1802-2701K (Medium Voltage)
Nichrome = 2702-3601K (High Voltage)

This change would also need a rebalance in temperatures for some EBF recipes, though. Here are the ones I've found, and have suggestions for:

(These are in the HV page of the questbook, so they should need Nichrome)
Energetic Alloy Ingot - 2200K -> 3100K
Platinum Nuggets from Powder Dust - 2041K -> 2941K

(These are in the MV page of the questbook and could be made post-Kanthal)
Soularium Ingot - 1000K -> 1850K
Dark Steel - 1800K -> 2700K

(Stainless Steel is one of the last parts of MV, so it should need Kanthal Coils if they are changed to be made in mid-MV)
Stainless Steel - 1700K -> 1900K

These values are just suggestions, and there are many I probably missed. I'd appreciate contributions for this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Skiftcha** [comment]
not sure about solution, but having kanthal coild only to make nichrome (which are better and cheaper in cost of chrome) is weird indeed

**Comment by johnch18** [comment]
It's kind of pointless considering the vacuum freezer is gated as well

**Comment by bombcar** [comment]
> It's kind of pointless considering the vacuum freezer is gated as well

It can be cooled in the chemical bath now (see PR)

**Comment by PolkageistHS** [comment]
Should we change the quest to not be gated behind the vacuum freezer though?  Maybe gate it behind the MV mixer quest.

**Comment by Dream-Master** [comment]
i change that already. Dont worry check the quest book @PolkageistHS
