### ISSUE TITLE
The energy loader does not take energy

### ISSUE THREAD

**Issue by Gansyn** [GTNewHorizons/GT-New-Horizons-Modpack#8630]
### Your GTNH Discord Username

Paralelepiped

### Your Pack Version

2.1.1.3

### Your Server

SP

### Your Expectation

Tried to transfer energy (32, 128, 512, 2048) to the energy loader by GT wires and away from the battery buffer.

### The Reality

The energy loader does not receive energy.

### Your Proposal

Fix error.  This problem didn't exist before.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Probably because it receives IC2 EU and not GT EU. Try hooking it up to an IC2 power gen like the RTG or nuke.

**Comment by Gansyn** [comment]
I connected it to the GT and IC2 transformers.   I connected it to the battery buffer GT and IC2. To no avail.

**Comment by boubou19** [comment]
Can you post a picture of a minimal setup that reproduce the bug please?

**Comment by Gansyn** [comment]
I just double-checked. It works fine with IC2 devices set to point-blank, but it doesn't work with GT wires. Before version 2.1.1.0 it worked with GT wires.

**Comment by boubou19** [comment]
That is because we introduced a change in the GT5U enet.
