### ISSUE TITLE
UDMH Fuel mix eating Cells

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#8631]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.1.2

### Your Server

private 

### Your Expectation

When mixing Unsymmetric Dimethylhydrazine and Trinitramid, it should return the correct amount of cells.

### The Reality

Taking 2 cells of UDMH, it returns one empty cell.
![bug](https://user-images.githubusercontent.com/10967188/135690974-f3881d47-1dbc-4e71-bfd7-cb4bfff0522d.PNG)

### Your Proposal

Fix the return cells, and also add the reverse recipe (where trinitramide is in the cells).
Also, consider adding a LCR recipe to remove the need of cells at all.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
It's a mixer recipe, not an LCR recipe.

**Comment by Savallator** [comment]
I know?

**Comment by Elisis** [comment]
> It's a mixer recipe, not an LCR recipe.

We have mixer recipes that can be done in LCR already.

**Comment by Savallator** [comment]
> 
> 
> > It's a mixer recipe, not an LCR recipe.
> 
> We have mixer recipes that can be done in LCR already. It's not unreasonable to do it here too

That is what i was suggesting.

**Comment by GlodBlock** [comment]
mixing is mixing, chemical reaction is chemical reaction. they are completely different two things. adding mixer recipe to large chemical reactor is wired. a better solution is to add a large mixer that don't use cell

**Comment by Prometheus0000** [comment]
> We have mixer recipes that can be done in LCR already. It's not unreasonable to do it here too

That doesn't mean we should. Those should be transferred to the MB mixer as soon as obama is done.

**Comment by Savallator** [comment]
In the meantime, can we just add a second empty cell to the output? It is not that bad anymore, since the reverse recipe was added and that is correct, but the recipe above is still broken.
