### ISSUE TITLE
Potential new circuit stuff

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8634]
### Your Pack Version

2.1.1.3

### Your Proposal

Add new circuit stuff for high tiers, alter existing.

### Your Goal

So there's circuits at that level. This will also allow SoC, and future expansion if wanted.

### Your Vision

Same as above?

This is the real stuff:

Circuit parts by voltage, excludes barts
Resistor: LV, MV
SMD: LV-IV
ASMD: LV-UEV
Transistor: LV, MV
SMD: LV-EV
ASMD: LV-UEV Skips from EV to UV
Capacitor: MV-HV
SMD: MV-IV
ASMD: MV-UV
Diode: LV-MV
SMD: LV-IV
ASMD: LV-UEV
About these, the first thing I have to question is allowing the advanced ones to be used in any of the lower ones. They're too expensive for people to do this, so why allow it? Not to mention that many of them are used for far too many tiers. Transistors also appear to be underused. I'd suggest adding more tiers, and adjusting them as such:
Non SMD: LV-MV(2)
SMD: LV-IV(4)
ASMD: IV-UV(4)
New SMD: UV-UIV(4)
New SMD 2: UIV-MAX(5)
With them unlocking/being required at 1 tier past when they can be used (ASMDs unlocked and needed in LuV being able to be used in IV voltage circuits for example).

Small coil: MV-UV
This should be removed, replaced in anything past MV/HV, or a higher tier(s) added, similar to above. But seriously, a coil? In a circuit?

Circuit series themes/names. This is just text basically. It won't necessarily correlate to how you make it, but it's better if it does.
Non 4-circuit series go here, but too lazy to add.
MV, HV, EV, IV -No unified name. Should that be changed?
HV, EV, IV, LuV -nano
EV, IV, LuV, ZPM -quantum
IV, LuV, ZPM, UV -crystal
LuV, ZPM, UV, UHV -wetware
ZPM, UV, UHV, UEV -bio
UV, UHV, UEV, UIV
UHV, UEV, UIV, UMV
UEV, UIV, UMV, UXV
UIV, UMV, UXV, OpV
UMV, UXV, OpV, MAX

Material/oredict. These are for that tier, regardless of series. Some of these are weird, but it would be a pain to replace.
Primitive			ULV
Basic				LV
Good				MV
Advanced			HV
Data				EV
Elite				IV
Master				LuV
Ultimate			ZPM
Superconductor		UV
Infinite			UHV
Bio					UEV
Nano				UIV
Piko				UMV
Quantum				UXV
None				OpV
None				MAX

Potential names for either:
optical, piko, super, ultra, best, ultimate, complete, perfect, infinite, temporal, gravitational, compact, micro, organic (similar to bio and wetware), magical (there's various magical themes that could be used, like bloody, 4 elements, etc. They don't have to use the magic mods), THE BEST, MAX, chuck norris, cyborg, AI, heavenly, demonic, godlike, alien, invincible, refined, holographic, slime, ender, undead, skeletal, space, yin-yang, futuristic. Please suggest some, as names aren't really my thing.

Special items used in FG, emitters (IV+) and sensors (IV+)
Nether Star = EV
Quantum = IV, LuV, ZPM
Gravi = UV, UHV, UEV
Temp Star 1 = UIV, UMV, UXV
Temp Star 2 = OpV, MAX
Names needed. Neutron Star & Black Hole would fit the theme.
Should there be a better endereye chain and use that for one or more of them? Or maybe 3 types? Or different crystals, like mysterious?

Just to be clear, some of these might not get recipes, but I think it's better to have things decided ahead of time.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GlodBlock** [comment]
oh god, he is backporting gregicality to gtnh

**Comment by Prometheus0000** [comment]
I have never played that. I only heard optical circuits were used in another pack, I guess it's that one?

**Comment by GlodBlock** [comment]
gregicality add different smds for every tier like you suggested

**Comment by Prometheus0000** [comment]
I didn't suggest every tier, just more than 3 total.

**Comment by Pxx500** [comment]
Maybe add new line for making wafers as proposed here? https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8596

**Comment by GTNH-Colen** [comment]
While we are on the topic of high tier circuits I do think that nano and quantums (the endgame versions) need a rename as it's confusing there is nano and quantum twice.

**Comment by Pxx500** [comment]
Also maybe a graphical redesign? They look kinda weird and not very "high tech"

**Comment by Prometheus0000** [comment]
Those ones are just going to be replaced. Just ignore them.

**Comment by Ngar1** [comment]
I do not see the pro of "higher" SMD electrical surface mounted devices. It makes it just harder, because more parts have to be developed for the next stage, but without realy play value (Spielspass, Fantasie, Herausforderung). If they are in an other  - higher  - technological view like: from electrical computer to optical components (half mirror, photon multipier crystals, optical polymeres,  ...) to bio components like encyme, synaptic interfaces, bacteria, RNA,... may be ending in somthing mysticaly (µ-worlds, µ-universe, massive parallel worlds,... - in a chip) it could be  - in my view - be interesting.

**Comment by observeroftime01** [comment]
Would be nice if the circuit assembler had more than 6 slots to allow for a wider variety of components to be used for crafting circuits. It's often a tradeoff between SMD components, wafers, fine wire, bolts or another circuit. By adding 3 extra slots to the circuit assembler one could add some different components to the circuits. I've always found the 6 slot limit to be somewhat of a constraint when looking at adjusting circuit recipes. 

Then there's the bio and wetware circuits, but who actually crafts those unless a UHV / UEV circuit is needed?

**Comment by Prometheus0000** [comment]
There's no need to make every machine effectively a crafting station that uses power. There's no need to use every component on every circuit. If necessary, they can be combined as a new part (multi-SMD for example).

**Comment by redmage17** [comment]
Are you going for relatively cheaper components in volume vs higher tiers? As well as using unused materials? I also assume the magic circuits are supposed alternatives?

**Comment by Prometheus0000** [comment]
Absolutely not. Adding new ones after removing old ones is more likely. No.

**Comment by redmage17** [comment]
> Absolutely not. Adding new ones after removing old ones is more likely. No.

Care to elaborate?

**Comment by Prometheus0000** [comment]
I thought that it would be completely clear, but apparently not.
- Using large amounts of old materials like compressed solars is bad, full stop.
- There's a ton of stupid materials, why restrain ourselves to using something like vyroxeres when we can remove it and add something like super soldering alloy or quantum computing alloy?
- No, they are not.

**Comment by redmage17** [comment]
> I thought that it would be completely clear, but apparently not.
> 
> * Using large amounts of old materials like compressed solars is bad, full stop.
> * There's a ton of stupid materials, why restrain ourselves to using something like vyroxeres when we can remove it and add something like super soldering alloy or quantum computing alloy?
> * No, they are not.

Okay that's what I thought you were getting at. It's a good idea. Burning through 1000 copper for a few circuits is nuts. Look up the unused/underused rare earth metals. 5hose would be a good start

**Comment by Dream-Master** [comment]
Guess we need add a few new items like smaller cables wires and a lot of circuit stuff. Much processing but use only 1/100 materials.

**Comment by redmage17** [comment]
> 
> 
> Guess we need add a few new items like smaller cables wires and a lot of circuit stuff. Much processing but use only 1/100 materials.

I don't think smaller insulated cables would be necessary outside certain items like mainframes.

**Comment by Prometheus0000** [comment]
Do you have a better name+icon? I know it doesn't make sense, but changing it is hard if you can't draw.

**Comment by Prometheus0000** [comment]
We already use SoC for very specific and different items though, which have their own series and purpose.
