### ISSUE TITLE
Better ore prospecting

### ISSUE THREAD

**Issue by ahmetsad** [GTNewHorizons/GT-New-Horizons-Modpack#8636]
### Your GTNH Discord Username

Ahmetsa#1741

### Your Pack Version

2.1.1.0

### Your Proposal

-Increase range of adv seismic prospectors
or/and
-Increase durability of handheld prospectors and reduce cost.
or/and
-add new prospecting tool

### Your Goal

Currently there is no proper prospecting tool between HV-LuV ages. handheld prospectors break after few scans, usually fail to scan, and they are expensive as a consumable item. adv seismic prospectors take long to prospect and they have very little range for time investment given. 

### Your Vision

I hope prospecting ores will be less painfull wouldn't take hours find the ore you want. Changes i propose doesn't make LuV scanner obsolete since it has better gui, good range, takes 1 second to prospect .

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
It's silly but something that is basically the "ore finder wand" but for pre LuV tier planets would work. Make it cost a mainframe or two and some other EV equiv and there you go. Siesmic for detail, ore finder radar for specific.

**Comment by Dream-Master** [comment]
Why we not make the radius from the prospector bigger or add a gui so they can show ore too

**Comment by ahmetsad** [comment]
I'm fine with both adding a gui with current range or at least doubling the range. Adding gui will get rid of machine mess you need to carry with yourself. it is currently 1 prospector 3 machine 1 generator 2 liquid 3 item. It takes 40 seconds to prospect and takes 2 powder barrels.

**Comment by bombcar** [comment]
> Why we not make the radius from the prospector bigger or add a gui so they can show ore too

The MV or HV prospector doing a gui that is NOT as detailed as the LuV could be nice - basically, show the ore chunks and what was "found" there - and nothing further, no size, no over lap, etc. Basically a gui version of what the seismic shows.

**Comment by Prometheus0000** [comment]
So, basically make the handheld one completely useless?

**Comment by Skiftcha** [comment]
industrialcraft scanners? much better than handheld prospectors

**Comment by bombcar** [comment]
Isn’t the handheld currently just worse than both the seismic and drilling down to bedrock?

**Comment by Prometheus0000** [comment]
Mostly, yeah. Which is why improving it instead of the previous version would make vastly more sense.

**Comment by Glease** [comment]
This suggestion is probably obsoleted by SinTh0r4s's VisualProspecting mod.
