### ISSUE TITLE
Enet doesn't recognize non-GT-EU producer if cable was already connected

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8642]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Your Expectation

I placed a solar panel on the cable and expected the solar panel to give energy to the battery buffer

Steps to reproduce the bug : 
- place wire 
- use wire-cutter on the wire to make it point up
- place the solar panel
- the solar panel isn't pushing eu to the buffer
- if you now desconnect & reconnect the wire it will now work

![2021-10-04_20 36 05](https://user-images.githubusercontent.com/57050655/135906554-426d7c6a-9aa2-4664-8c32-646df59ecddb.png)

### The Reality

It doesn't push EU into the buffer

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Is this a different Enet bug from needing a GT machine on the cable network?

**Comment by boubou19** [comment]
well, sometimes, solar panels had issues connecting to the GT enet, even before the experimental change. So can't really blame the enet change this time.
