### ISSUE TITLE
Bacterial-Vat Efficiency off by one

### ISSUE THREAD

**Issue by MMunier** [GTNewHorizons/GT-New-Horizons-Modpack#8644]
### Your GTNH Discord Username

MMunier#1337

### Your Pack Version

2.1.1.2 with minimal patches

### Your Server

private

### Your Expectation

Bacterial Vat scaling from 1 to 1000 according to the quadratic formula in
https://github.com/GTNewHorizons/bartworks/blob/fc0ca5948cab0af1b120bec9f05241cef701e748/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_BioVat.java#L134
```java
    private int calcMod(double x) {
        double y = (((double) this.getOutputCapacity()) / 2D),
               z = ConfigHandler.bioVatMaxParallelBonus;

        int ret = MathUtils.ceilInt(((-1D / y * Math.pow((x - y), 2D) + y) / y * z));
        return MathUtils.clamp(1, ret, ConfigHandler.bioVatMaxParallelBonus);
    }
```

### The Reality

Efficiency is always 1 higher than calculated because of an off-by-one in check-recipe
https://github.com/GTNewHorizons/bartworks/blob/fc0ca5948cab0af1b120bec9f05241cef701e748/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/GT_TileEntity_BioVat.java#L211

To be precise it returns exactly one fluid output batch more than batches of input consumed.

Doesn't really matter for all recipes using any kind of solid input, 
however the intended recipe output can be doubled for fluid to fluid recipes if it's running with an empty output hatch.
( Albeit extremely slow and with a relatively large power draw )

### Your Proposal

`s/int times = 1/int times = 0/`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by sintken** [comment]
i remember a note somewhere in the code that the 1001 was intentional and served some purpose - cant remember where it was for the life of me though
