### ISSUE TITLE
Switch HEE quest progression - Infested Island/Ghost Amulet

### ISSUE THREAD

**Issue by CharlieTuna8** [GTNewHorizons/GT-New-Horizons-Modpack#8645]
### Your GTNH Discord Username

Charlie Tuna#7949

### Your Pack Version

2.1.1.0

### Your Proposal

Either remove the ectoplasm requirement from the quest "Visit the Infested Island".

Or open the quest "Ghost Amulet" before/at the same time as the Infested Island quest.

### Your Goal

The only way to get ectoplasm without the amulet is through bees.

This might force players to use bees instead of the intended HEE way using the ghost amulet.

### Your Vision

Just imagine,

Someone tries their best and spends hours to get that one bee that makes ectoplasm and then waits for enough combs.

Only to find out there is a much easier way.

At least I would be very frustrated.

Changing this would prevent this from happening.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
I would hope they would check the HEE book with the P button.
