### ISSUE TITLE
Storage monitor don't update properly on game startup

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8647]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Your Expectation

I have a ME subnet with all my ores and dusts, it is connected to my main system with a storage bus(main) + interface setup(subnet), my main system can see all the content of the ME subnet with all the ores.

I have storage monitors connected on the main network that display the number of certain dusts stored in the subnet

I expect the storage monitor to display the amount of dusts in the ME subnet

### The Reality

It doesn't work just after game startup 
![image](https://user-images.githubusercontent.com/57050655/136250652-5f72c77c-dbda-40f4-a639-a05e602a0a3c.png)

However if I grab some of the dusts in the terminal it updates the storage monitor properly, and if I disconnect and reconnect the storage bus of the main system facing the interface of the subenet if also updates the amounts properly.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Can't reproduce that in dev. Is the subnetwork connected via quantum bridge? How is stuff stored in it? Is it in some remote and player loaded chunk perhaps?

**Comment by Alexdoru** [comment]
The subnetwork is 4 chunks away connected by a cable

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
