### ISSUE TITLE
See throught feature displays wrong block with structurelibs's hologram

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8654]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Type of Server

solo

### Your Expectation

display all blocks properly

### The Reality

When you stack one paper and click the multi it displays the hologram with tier I coil, then if you stack a second paper and click the controller again, it displays tier II coils for the blocks in line of sight but tier I coil for the blocks that are behind a block 

![2021-10-07_20 43 37](https://user-images.githubusercontent.com/57050655/136446585-614b0f27-4baa-4762-8418-1e2ffa34a5f0.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
because i miss some tectech metheds to replace during the tectech structurelib update, won't be diffcult to fix.
