### ISSUE TITLE
IC Gate doesn't initialize properly

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8655]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Your Expectation

It is the same gate it should work the same in both cases

### The Reality

I have an hysteresis gate that contains an RS latch and a NOT gate, when there is a signal ranging from 8 to 15 the output is turned on and when the signal ranges from 0 to 6 it is turned off.

![image](https://user-images.githubusercontent.com/57050655/136447257-88a876fe-925c-409a-8e52-d862f501b65f.png)

If I first place a torch first and then the gate (top on the picture) the output doesn't turn on despite the fact that the input signal strenght is 15, if I place the gate first and then the torch it works as expected.
![2021-10-05_22 13 27](https://user-images.githubusercontent.com/57050655/136447575-28be102b-8b7b-4158-a74f-b18996ff8ee5.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Trying to place an IC Gate in the world results in a client crash - maybe this is related?

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7785829/latest.log)

**Comment by Rikenbacker** [comment]
I have same problem. Schemes after install need initialisation by fake signals. It is not obvious to fix.

**Comment by usagirei** [comment]
Also ran into this issue and spend some time trying to figure out why it wasn't working.

### Some more information:

If the gate is placed in the world, ***without a redstone signal or a redstone signal of 0***, analog channel 0x0 in particular will not be high.
All other (0x1~0xf) channels work as expected.

My blind guess is the initial gate state is zero on placement, and on tick, the new input state is the same as the old, unitialized state of zero, then it never propagates the state changed event, causing channel 0 in particular to not be high on placement.

---

Dummy 'Bus Decoder' Gate
![image](https://user-images.githubusercontent.com/12700106/236047225-17d39891-88df-4351-8004-5b2c2cfa33d8.png)

<details>
<summary>Placed with 0 Signal, then flicked lever on and off, internal state updated</summary>

![image](https://user-images.githubusercontent.com/12700106/236047130-c1036b73-e4ca-4666-9266-cf5762e7514b.png)

![image](https://user-images.githubusercontent.com/12700106/236047466-af4f5205-a222-4a8c-a178-3b7c0a043a6b.png)
</details>

<details>
<summary>Placed with 1 and 14 signal respectively, works as expected</summary>

![image](https://user-images.githubusercontent.com/12700106/236047829-f1c1de3c-6000-4e57-82e6-d5e91286a51b.png)

![image](https://user-images.githubusercontent.com/12700106/236047755-88582d1f-130c-4977-b07c-e776e3768d50.png)
</details>
