### ISSUE TITLE
Remove AE2 Extracells fluid handling

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#8656]
### Your GTNH Discord Username

Pxx500#6984

### Your Pack Version

Irrelevant

### Your Proposal

Remove crating for AE2 Extracells fluid handling until (if ever) someone fixes it.

Fluid interface
Fluid storage bus
Fluid export/import bus
Fluid drives

### Your Goal

So people won't fall into this lag trap.

### Your Vision

People who don't read the quests or who didn't know just how bad it is won't have to rebuild their bases. You can quite often see people in discord who didn't realize how poor the choice to use EC2 was, until they showed their base on discord and were explained how bad it is.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7927

**Comment by Pxx500** [comment]
> #7927

I love how the title doesn't contain anything I searched for.



> There is no other fluid logistic capable of delivering exact amount of fluid for recipes. GTNH's abuse of micro-crafting is the issue, because it cause the use of insane amounts of low tier basic materials to be used. Sure, if you handle these amounts as fluids and on-demand, you are wrongly handling and amplifying the micro-crafting damaging side-effects on overall game performance.

Isn't that an early game problem? At EV you can make p2p and automate LCR this may, assemblers with PA at IV
You unlock EC2 as soon as you unlock p2p and it doesn't take much time until PA is unlocked and can be used to add many fluid hatches to more machines. Maybe I missed the point and if I did give me an example of a hard to automate recipe

**Comment by leagris** [comment]
> earlier it was said that "proper" usage of EC2 won't slow down the game. Well, using extruder instead of solidifier is a similar trick to use to have lower performance requirement. If one wants to argue about performance then at least it'd be nice if the argument was consistent
> 
> [edit] Just checked, extruding _two_ steel rods takes 10080EU vs 18000 for solidifying _one_. For tungstensteel it is 85680 to extrude two vs 72k to solidify one so it is actually significantly less energy intensive to extrude stuff than to solidify. In addition you get double the output per operation/computing power

I did not notice GTNH diverged so much from the standard Gregtech5 by inflating the cost of solidifying to the point of making it useless. Then building up arguments to remove features from ExtraCells, to the point of making it useless to provide argument to remove it entirely later.

I know how this incrementally destructive process works from real life experience. Progressively destroy superior options to make inferior option looks relevant. Have seen this way too much times.

**Comment by hohounk** [comment]
> Why are you writing [edit]? 

Old habits from forum times.

Just for the fun of it I downloaded the oldest version of GTNH from curse, 1.0.9.2 from 2016, and looked at the numbers there. Apparently, back then it wasn't even possible to solidify rods. Though extruding steel took 10752EU and 91392 for tungstensteel so at least for extruding the numbers are effectively the same today as they were years ago. 

What did exist was making blocks. For steel it took 2304 to solidify vs 1280 to extrude. For tungstensteel it took 2304 EU to solidify it vs 5120 to extrude. Today it takes 2016 to solidify a block of steel vs 1200 to extrude. For tungstensteel it is 2016 vs 4800 to extrude. So, compared to 5y ago it the energy costs have been dropped, not increased - the exact opposite of what was asserted.

I'm willing to bet the energy requirements for solidifying and extruding haven't changed enough to have it make sense to complain about "incrementally destroying" the modpack.

**Comment by Ngar1** [comment]
In transition time from "tank" to "ME fluid distribution" it is easy and safe to use fluid storage on (existing) tanks.  And tanks are better available as a "virtual" ME fluid storage cells, special if the power supply of the power hungry ME is not stable (wcc: power is supplied by fluids out of ME) or explosions interrupt ME availability.

There are some other posibilities to dupe fluids and items without ME fluid system...

**Comment by Pxx500** [comment]
> Or add a tooltip in red saying: This item causes lag, better use fluid P2P.

It's already in questbook, people do it anyway and regret later

**Comment by GTNH-Afx237v7** [comment]
Maybe a direct hint in NEI is more obvious...

**Comment by Pxx500** [comment]
No crafting recipe is even more obvious

**Comment by Steelux8** [comment]
Warning on the tooltip is fine too, as long as they aren't outright disabled in my eyes. I'm curious about why they perform so badly, though, since as you said people might have used EC2 before. Was it a backport or something?

**Comment by repo-alt** [comment]
Performance-wise it just doesn't scale. Not like it got broken just recently, it was even somewhat improved, but further improvement is not worth the efforts.

**Comment by 0lafe** [comment]
Don't flasks provide discrete quantities of fluids within AE recipes? They have tons of filtering options that make it really easy to bundle them in the same recipe as items while ensuring everything ends up in the right place. 

Not as cool as fluids, but they seem like a decent solution with how bad fluid AE is

**Comment by Pxx500** [comment]
> Don't flasks provide discrete quantities of fluids within AE recipes? They have tons of filtering options that make it really easy to bundle them in the same recipe as items while ensuring everything ends up in the right place.
> 
> Not as cool as fluids, but they seem like a decent solution with how bad fluid AE is

That's how Asslines are automated on my save, normal pattern with flasks

**Comment by 0lafe** [comment]
Yeah, im not sure anyones doing full automation of the assline without flasks these days. Can't really handle missing ingredients otherwise. I've used it for LCRs, fluid extractors, assemblers, solidifiers, and some other processes. They work really well and seem to be able to handle every recipe I've come across. Only issue was automating their creation of certain quantities, but iirc thats been fixed 

Not sure if this ticket is still relevant, but I do think you can retain all fluid crafting ability without EC2s fluid crafting.
