### ISSUE TITLE
Add Quantum Chest Drive to AE2 

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#8657]
### Your GTNH Discord Username

alphaNOVA#9875

### Your Pack Version

2.1.1.0

### Your Proposal

Add a ME Quantum Chest Disk. One typ only but equivalent storage to a quantum chest. That way we can avoid large drawer storages or buggy qunatum chest storage which would be server friendly without needing to make the normal drives stupidly cheap. 
Could be multiple tiers of those (according to the normal gt quantum chests) and crafted with them to. Cost shouldnt be much more then the chest involved. 

### Your Goal

I dislike the idea of making storage components cheap but see the need of server friendly storage. Moving quantum chests directly into me disks would be best for server performance while making sense given the storage already exists and is sort of balanced. 

### Your Vision

How many fields shall i fill out xD 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by alphaNOVAircraft** [comment]
It wont be stalled, its still a good idea

**Comment by GlodBlock** [comment]
ec2 has me block container which is similar to what you want. maybe we can add more tiers to it with larger capacity
