### ISSUE TITLE
Mega Item Duping

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#8658]
### Your GTNH Discord Username

BangBang#8842

### Your Pack Version

2.1.1.3

### Your Server

SP and MP

### Type of Server

Single Player

### Your Expectation

Имеется схема рудопереработки. В ней есть:
1. SFM
2. AE
3. GT (обнаружил на супербассах)
4. GT++
5. Infinity chest
Самая простая схема: дробилка - рудомойка - дробилка - центрифуга
Закидываем стак руды - дробится на 2 стака крашед руды и...
Дальше начинается дюп. За 3 меха 2 стака (128 штук) превращаются в 100к+ чистой пыли на выходе (не учитывая побочки).
Из того что заметил - сначала просто забивается на максимум супербасс (гт++ мех еще не работает) и потом мех работает в нормальном режиме. 

### The Reality

Описал все выше

### Your Proposal

Исправить:)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cinobi** [comment]
Добавь пожалуйста больше информации, хотя-бы скриншот всей системы и что там у тебя в СФМе, по текущему описанию ничего понять нельзя.

Please add more info, screen of whole system and ur SFM programm atleast. Its impossible to understand anything at current level of data.

**Comment by PredVesTNiK2142** [comment]
В СФМ все стандартно - триггер - забрать по вайтлисту - положить по вайтлисту. Схема тоже стандартная - СФМ забирает из АЕ - ложит в супербасс (superbus) - из меха уходит в outputbus me. Хранение на инфинитичестах (infinitychest) на сторейдж шинах(storage bus).

![image](https://user-images.githubusercontent.com/63409840/136567150-4c3b9444-4ae5-473e-9e17-69ca3574c4d1.png)
![image](https://user-images.githubusercontent.com/63409840/136567193-1b453067-3b0f-4dbb-89df-fa29ec61750e.png)
![image](https://user-images.githubusercontent.com/63409840/136567260-33d71b98-d628-4d43-9a38-d6c6dece9e1a.png)
![image](https://user-images.githubusercontent.com/63409840/136567308-280cd794-bea3-4b00-85c5-497b41a4408f.png)

**Comment by PredVesTNiK2142** [comment]
I hear a ringing but I don't know where he is. on the case - it was checked without the SFM connector to ae. but I feel that the next ticket has gone into a bunch of crit bugs that no one will decide

**Comment by PredVesTNiK2142** [comment]
Честно - заебали ваши багрепорты. Пишешь вам баги - в итоге нихера не правится и в лучшем случае придумываешь костыли что бы что то работало. Но по вашим словам "все нормально - все работает".
