### ISSUE TITLE
IC2 Tesla coils stopped working

### ISSUE THREAD

**Issue by aka-zaratustra** [GTNewHorizons/GT-New-Horizons-Modpack#8662]
### Your GTNH Discord Username

ZARATUSTRA#1025

### Your Pack Version

2.1.1.3

### Your Server

SP

### Type of Server

Multiplayer LAN

### Your Expectation

Use Tesla coils to kill mobs. On 2.1.1.0 it worked without problems, I had a Wither farm.

### The Reality

Tesla coils stopped working. Version 2.1.1.3. I tried it with superconductors and an additional consumer on the wire - the same result, Tesla coils not working. Tried on my server and solo - the same result, Tesla coils not working. On 2.1.1.0 it worked without problems, I had a Wither farm.
![unknown](https://user-images.githubusercontent.com/24389462/136706919-2acc8197-fb8f-450e-8982-0b43777e68f9.png)

### Your Proposal

Fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by aka-zaratustra** [comment]
![unknown1](https://user-images.githubusercontent.com/24389462/136707249-ae5557ee-4c0d-4b76-8135-eb7833da88b7.png)
Tesla coils work with IC2 transformer. 
Problem solved. There is no more sense in this issue.

**Comment by Prometheus0000** [comment]
It's the enet thing again. Honestly, I'm not sure why we even make these craftable.

**Comment by Prometheus0000** [comment]
I mean, I don't know why someone would use them over spikes given that they use power, that's all.
