### ISSUE TITLE
Breaking a certain block set the vajra durability to 0 and sometimes makes it disappear entirely 

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#8669]
### Your GTNH Discord Username

Jimbno

### Your Pack Version

2.1.1.0

### Your Server

Dedidated SP server

### Type of Server

Multiplayer LAN

### Your Expectation

Break block with vajra and pick amd pick up without issues

### The Reality

When you break a castle roof tile block it sets your vajra's durability to 0 and sometimes if you are unlucky enough it'll just disappear

### Your Proposal

I humbly propose that the player should be able to break castle roof tile (#1242:3) without hinderance or loss of expensive tooling

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Team1Warlord** [comment]
Bug isn't fixed yet, vajra's durability jumps from one value to another when you r breaking blocks like castle bricks, runes, dead rock etc. 
Ver 2.1.2.1 i'm KOT_BHE_3AKOHA#7758 in discord
@repo-alt

**Comment by repo-alt** [comment]
that may be fixed by https://github.com/GTNewHorizons/twilightforest/pull/15

**Comment by miozune** [comment]
Confirmed fix
