### ISSUE TITLE
Disable energy consumption of microcontrollers

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#8673]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.1.3

### Your Proposal

Microcontrollers have insignificant energy consumption right now (about 1 rf/t) and have very limited use scenarios.  Like smarter version of conduit on 1 block item transfer or just advanced redstone logic gate. In terms of balance 1 rft on hv (when you can make microcontroller) doesn't really affect anything.

### Your Goal

Tweak config config values for energy consumption of microcontrollers

Current config value:
```
`# Amount of energy a microcontroller consumes per tick while running.
      microcontroller=0.1`
```

### Your Vision

Increase QoL while using microcontrollers, so you don't have to pull AE or GT cables to each microcontroller and make them more attractive to use for performance friendly setups.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
putting the consumption to 0.1rf is pointless, at that point maybe we could just remove it completely instead.

**Comment by Florexiz** [comment]
This is current config values

**Comment by Glease** [comment]
Is this still needed? IIRC we had a RTG like generators for them now.

**Comment by repo-alt** [comment]
Yes, RTG upgrade was added exactly for that. Not sure if it has a recipe though.

**Comment by Retster** [comment]
There is still no resipe for RTG upgrade and Configurator upgrade, that was added recently.

Also in the progress is waiting for add the recipe for Riteg upgrade:
https://github.com/GTNewHorizons/OpenComputers/pull/47#issuecomment-1013840912
recipe suggested by the author:

Riteg upgrade:
x1 Pellets of RTG fuel
x2 Microchip (Tier 3)
x4 Dense Lead Plate
x1 Programmed Circuit (# 1)
voltage 256 eu/t (HV)
Time 15 sec

**Comment by Retster** [comment]
aded PR for missing recipes:
https://github.com/Retster/NewHorizonsCoreMod/pull/1

**Comment by Glease** [comment]
Where are you sending PR? Your PR is directed towards your own repo, not ours.

**Comment by Retster** [comment]
> Where are you sending PR? Your PR is directed towards your own repo, not ours.

ops, this one too?
https://github.com/Retster/NewHorizonsCoreMod/pull/1/commits/90b95e24dc4d897032b1a18fb61c8f66571af581

**Comment by Retster** [comment]
already make PR properly:
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/282
