### ISSUE TITLE
Add new storage bus button

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#8675]
### Your GTNH Discord Username

Colen (His Supreme Holiness, HBM manager XIV, Colen | RADM. Supreme Gay🎖🎖🎖🎖)

### Your Pack Version

2.1.1.0

### Your Proposal

Add a button which can read the items in the inventory it is attached to and auto format the storage bus filter to hold all those items. Especially useful for large inventories like an infinity chest.

### Your Goal

/

### Your Vision

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
That’s already there, unless you mean something different?

**Comment by TrainerSnow** [comment]
As far as im concerned the "Partition Storage Bus" Nutton already exists, no?

**Comment by Alexdoru** [comment]
There is already a button that does this but the storage bus GUI isn’t big enough to hold all the items in an infinity chest

**Comment by GTNH-Colen** [comment]
Bruh I literally never knew this button was there until today, a larger storage bus would be cool but until then I'm happy.
