### ISSUE TITLE
add new cleanroom glass

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#8678]
### Your Pack Version

2.1.1.3

### Your Proposal

in last version, bart's glass was allowed to use in cleanroom. but there is another glass, quantum glass in tectech is a UV glass, and can not use in cleanroom like Os glass. quantum glass is much more expansive than Os glass, so i want it can use in cleanroom

### Your Goal

allow quantum glass use in cleanroom

### Your Vision

a uv tier glass obvious can use in cleanroom, and, maybe it can be light source

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pnc6lx** [comment]
[issue](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8487)

**Comment by bombcar** [comment]
Not sure how to add a glass to the config, something like this in GregTech/GregTech.cfg:

```
cleanroom_allowed_blocks {
    reinforced_glass {
        S:Name=blockAlloyGlass
        I:Percentage=5
    }
    bw_reinforced_glass {
        S:Name=BW_GlasBlocks
        I:Percentage=80
    }
    tt_wahtever_spendyglass {
        S:Name=TT_GlasBlocks
        I:Percentage=80
    }
    elevator {
        I:Count=1
        S:Name=tile.openblocks.elevator
    }

    travel_anchor {
        I:Count=1
        S:Name=tile.blockTravelAnchor
    }
}

```
