### ISSUE TITLE
Visual Prospecting: GregTech + JourneyMap = <3

### ISSUE THREAD

**Issue by SinTh0r4s** [GTNewHorizons/GT-New-Horizons-Modpack#8680]
### Your GTNH Discord Username

SinTh0r4s#7579

### Your Pack Version

2.1.1.3 dev

### Mod Name

[Visual Prospecting](https://github.com/SinTh0r4s/VisualProspecting)

### The Mod to Add

Tracking of ore veins and oil fields. Adds custom overlays in journeymap for them.
Also provides easy to use API if anybody would like to implement further prospecting mechanisms.

![Oil fields in JourneyMap overlay](https://i.ibb.co/crPhR1X/2021-10-12-15-45-25.png) \
_Oil fields in JourneyMap overlay._

![GregTech ore veins in JourneyMap overlay](https://i.ibb.co/cg7gH0P/2021-10-13-16-32-06.png) \
_GregTech ore veins in JourneyMap overlay._

### Your Reason

Provide some structure especially for newer players. Streamlines the prospection process and removes likely headaches if coordinates are wronly calculated. Also potential for new features via API.

### Preliminary Investigation

Integration tested and worked with current dev release

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [X] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by SinTh0r4s** [comment]
"I assume you can turn them off? I really wouldn't want it on all the time."
 - Yes. There are two separate toggle buttons for ores and underground fluids at the top.

"How do you 'discover' them? If it's on all the time, it's just super OP. If it's reading the books from the seismic prospector (I recall something on discord like that), it still seems maybe too easy."
 - You may interact with ores (break the block or right-click it) to prospect a single vein. The resulting book from a Seismic Prospector is integrated as well. A client only sees ore veins/underground fluids he has found. The database is only available server side.

"It makes the handheld one completely worthless."
 - One could think about integrating it. Also, more importantly, no small ores are listed in Visual Prospecting.

"It makes the seismic one maybe too powerful."
 - How so? It just displays the available information to the player and saves manual waypoint management.

"Is there a manual? It really needs an explanation."
 - Of course it does, but it does not exist yet. The mod was written within the last month.
 
"The colors in the fields seem weird, it seems to be lighter based on amount? But the highest value one in a 100L field would be the same color as a 1000L one of the same fluid in a different field, so you can't really tell how good it is based on that. Additionally, unlike the electric one, there isn't really a sense of how much the difference between the colors is, and this would be meaningless."
 - Colors are relative to their individual 8x8 chunk field. Suggestions for visual updates are welcome.

"What's with the yellow borders on some? Is it the highest amount ones? Is that really meaningful? Isn't the full field one only EV? So you'd get to it really fast."
 - You assume correctly: The best chunks are highlighted. I wanted to do something with that information. For early tiers it will be interesting.

"Additionally, will it update? Actually, will it update at all based on pumped amount?"
 - It will not update unless the client reads a prospecting book about the underground fluid field again. Frequent updates are a network hazzard, server load and complex coding. I think it is simply not worth the effort.

"What happens if worldgen changes, will it still detect accurately in already generated terrain?"
 - I implemented a hook into world gen. Changed oregen will overwrite existing information so everything is up to date when the user interacts with it.

"Does it work with BW ore?"
 - Yes it does. However on existing worlds the first start will scan the whole world (less than a minute per GB) and reconstruct placed ore veins. ´This works with over a success rate of over 90%, although a bit lower for BW ores. They are generated in a different structure. Ore veins generated after the mod is present will work 100%.

"Why are the ores revealed in such a weird pattern? This would probably make more sense if there was any kind of explanation of how it works."
 - Are you familiar with GT ore chunks? They are worth a read. TL;DR: All 3x3 chunks you will get a new ore vein.

"Did you add icons for the other JM themes?"
 - Yes, but only for the ones present in JM's jar.

**Comment by iouter** [comment]
i want test it, could you upload this mod?

**Comment by SinTh0r4s** [comment]
> The example you gave is not 3x3 veins or 5x5, so I guess it's the result of manual checking, which I didn't realize was possible, and I thought it was skipping some or something.
The screenshots are from my test world and show the player's progress. Manual + Advanced Seismic Prospector.

> Did the handheld one show small ores? Are you thinking about the electric one? Having it work with this would make it more useful, I didn't realize you could add more ways to find/show the ore.
You can certainly add more ways to find ores. I exposed an API and documented it. So you can dream of some new features and implement them quickly. Maybe you want to code a prospecting satellite? :P

> Is there a way to cheese this, by, say, placing down ore and then mining it? Does it check for natural generation?
I hope not. I spend quite some time and effort to implement checks against this. You need to interact with a ore from the vein. So you could try to cheese it, but you need to know which ore veins is placed there or try every ore. You may just as easily mine vertically down to actually find the vein.

**Comment by boubou19** [comment]
it is in the pack now
