### ISSUE TITLE
Change fluid amount for UIV energy & dynamo hatch

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8684]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Proposal

currently the UIV energy/dynamo hatch in the 4A 16A 64A versions require 8000L of molten metal, could we change this to a multiple of 144L like 9216L for instance

### Your Goal

make it easier and more consistant with the other molten metal recipes

### Your Vision

yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by observeroftime01** [comment]
How about 7920L, since that divides by 144L evenly, do the last 80L really make a difference?
