### ISSUE TITLE
Add TT EV 4A Energy Hatch

### ISSUE THREAD

**Issue by Elisis** [GTNewHorizons/GT-New-Horizons-Modpack#8686]
### Your Pack Version

2.1.1.3

### Your Proposal

Add an EV 4A energy hatch in a similar vein to the later tier ones.

### Your Goal

There is no particular reason as to why these hatches are limited to IV+. You can easily get >2A EV power generation.

### Your Vision

Consistency and QoL are cool.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by 0lafe** [comment]
This is a pretty solid idea given the exitance of the buffered EV dynamos
