### ISSUE TITLE
Problem in Mega freezer logic

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8689]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Your Expectation

I expect my mega vaccum freezer to not try to make recipes that require 2A when it only has one energy hatch

### The Reality

- make freezer with one UIV energy hatch

- put 256 hot infinity catalyst ingots in the input bus
![image](https://user-images.githubusercontent.com/57050655/137415372-49e23b81-9740-4e32-9651-5394d775e04f.png)
- turn on the machine
- it takes 136 ingots and stops + void the items

the multi tried to run 136 items in parallel which requires 2A UIV

In my opinion a multi with one energy hatch should try to do recipes that need 2A 

A multi should either consume 1A with one energy hatch or 4A with two hatches

### Your Proposal

change it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
I assumer the mega EBF works the same

**Comment by GTNH-Afx237v7** [comment]
Isn’t it that both MBF and MVF try parallel first and then overclock while consuming as much energy as is available? I believe this is what Bart intended...

**Comment by alphaNOVAircraft** [comment]
I never encounted that issue with the MBF. But for mega vac its definitly as you described

**Comment by Alexdoru** [comment]
> Isn’t it that both MBF and MVF try parallel first and then overclock while consuming as much energy as is available? I believe this is what Bart intended...

Yes but in my opinion it shouldn’t try to take two amps when it has one energy hatch, it should only take one

**Comment by Alexdoru** [comment]
just look at the hatch tier and say that the available power is one amp of that tier ?

**Comment by Alexdoru** [comment]
> > Can't see a problem with this logic. It always use full energy throughput of energy hatches and I like it
> 
> That's different from how every single other multi works though. Plus it's voiding apparently.

yeah it's different from every other multi hence why I made a ticket, and it's voiding because I am only providing one amp. It will void when it tries to draw two amps.

**Comment by hohounk** [comment]
EBF with two LV hatches will run recipes requiring one amp of MV as the default hatches have 2 amp input per hatch. From the descriptions here it seems like MVF uses the same logic - if it has one hatch that inputs two amps it presumes you are capable of actually delivering those two amps.
