### ISSUE TITLE
Recipe conflict in mixer with #2

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8691]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Your Expectation

e

### The Reality

if you make yttriium barium cuprate dust and energetic alloy dust in the same mixer it conflicts with the rose gold recipe

![image](https://user-images.githubusercontent.com/57050655/137531742-22d1fdb7-3c57-4942-9eb2-cda33423b59a.png)
![image](https://user-images.githubusercontent.com/57050655/137531776-b450e237-64fe-46b8-8cb9-40e1d38dc68f.png)

![image](https://user-images.githubusercontent.com/57050655/137531723-077f7a12-7048-459d-ae37-f43694f40c5e.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Florexiz** [comment]
Also same thing with energetic silver while making energetic alloy
![image](https://user-images.githubusercontent.com/29033773/147389692-f79b9414-0c91-45a5-a6e1-a87d0166bf2e.png)
![image](https://user-images.githubusercontent.com/29033773/147389712-675c9e96-650a-4362-b696-cc2cdd23b644.png)
![image](https://user-images.githubusercontent.com/29033773/147389715-1ed6d525-2ceb-49a3-83d2-c86a40a5fa5e.png)

**Comment by Godelboard** [comment]
Same issue with Enderium dust, Pulsating iron dust, and Conductive iron dust:

![image](https://user-images.githubusercontent.com/6662420/202973199-9b5cdf64-8c0e-4ac5-890b-6e76da593b23.png)
