### ISSUE TITLE
No Boom Tomorrow gives Fused Quartz

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8694]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

The quest "No Boom Tomorrow" tells you to not used Fused Quartz but then gives you ten as a reward.

Bronze Plated Reinforced Stone is cheap enough, I suggest we change the reward to that. Or Warded Glass. Or a "pick one" from a various list of blast-proof materials.

### Your Goal

Give a useful reward instead of a useless one.

### Your Vision

Have rewards be consistent with the quest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
If a replacement is determined I can update the quest.

**Comment by Elisis** [comment]
I thought this was supposed to be a joke, giving you an item that doesn't work anymore?

**Comment by bombcar** [comment]
Could be - in which case I can revert. Not sure what the quest was before the fused quartz nerf
