### ISSUE TITLE
Assembling Line Tooltip has ambiguous maximum length

### ISSUE THREAD

**Issue by MMunier** [GTNewHorizons/GT-New-Horizons-Modpack#8695]
### Your GTNH Discord Username

MMunier#1337

### Your Pack Version

2.1.1.2 with minimal patches

### Your Server

private

### Your Expectation

The Assembling Line should have a maximum length specified that doesn't conflict with it's own tooltip.

### The Reality

It specifies a maximum length of 15 when going by the Dimensions, however it later states `Up to 16 repeating slices`, resulting in a unclear maximum length.
![assline-tooltip](https://user-images.githubusercontent.com/43609314/137600068-ea0733d6-f150-4710-a20c-2c0f14c913ff.png)

### Your Proposal

Didn't check whether 15 or 16 is the maximum length, but in any case one of the lengths stated should be corrected.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
this tooltip has been changed slightly but is still incorrect. we even have recipes with 16 solid inputs now.
current version (2.1.2.4 dev18)

![image](https://user-images.githubusercontent.com/40274384/180576418-adf4cd76-0fc3-450b-9293-772464bbf488.png)


Specifically:

- it should be 16 not 15 in the dimensions
- layer 1 description is not correct, the last can also be input (with output to the side).
- remove 'aside from the last' in the line starting with 'up to 16...'
