### ISSUE TITLE
Sensor Location Cards Should Have a More Sensible Recycle Recipe

### ISSUE THREAD

**Issue by The1stRonin** [GTNewHorizons/GT-New-Horizons-Modpack#8698]
### Your GTNH Discord Username

Stallion#2856

### Your Pack Version

2.1.1.0

### Your Proposal

The 'reactor sensor location card' (as well as the other sensor location cards) should be able to be recrafted into a relevant blank sensor kit.

The current recycle recipe for 'reactor sensor location cards' requires 2 reactor sensor location cards. The resources required to build these are:

- 6 LV circuits
- 4 MV circuits 

As well as various other miscellaneous resources. The recycled recipe returns:

- 2 LV circuits.

### Your Goal

Current implementation incentivizes players to ignore using the displays because they provide a horrendously bad return on resources which seems to arbitrarily punish players for moving a display. It doesn't make sense from a logical perspective as the electronic data should easily be reformatable nor does it make sense from a balance perspective as by the time the player is using these displays they have much better options to recycle much more advanced machines and receive vastly more components back.

### Your Vision

More people would use the displays and the displays could be appropriately moved when changes to a base occurred (as they frequently do in GT:NH).  The change would benefit both game balance and immersion.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Does the nbt wiper reset them

**Comment by Prometheus0000** [comment]
Pretty sure this was fixed ages ago. Try dev.

**Comment by The1stRonin** [comment]
> 
> 
> Pretty sure this was fixed ages ago. Try dev.

It was not.

**Comment by Prometheus0000** [comment]
Looks like there's more than 1 card that needs fixing I guess.
