### ISSUE TITLE
[Officials?] High connection usage of AE2 when terminal is open

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8700]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.1.0

### Your Server

delta

### Your Expectation

Opening AE2 crafting terminal to get some stuff, wireless or not.
Expected it to behave normally and not make me lag

### The Reality

Every time I open the terminal, doesn't matter if it's wireless or not, the connection usage of the game spikes up to 10, 15 or up to 20 Mbit/sec
![Taskmgr_5BeJeHouya](https://user-images.githubusercontent.com/17811922/137619120-0acdba50-33f4-49e4-a420-ad1c7aa332ad.png)

This is happening only on delta from what I can see, I tested a similar AE2 on eta, Colen's AE, as we have both similar networks, and his AE is fine.

Both AE have 1 or more infinity chests
We both use Wireless extensively
Colen has 600+ disks compared to me with 120
And yet when I join his base on eta and open his AE, my connection stays at 0.6 Mbit/sec compared to the 15 or 20 Mbit/sec of my base on delta.

I don't know if it's some type of config or what's going on, but this makes my game unplayable sometimes as, from what I know, routing from Italy to rest of europe is always been shit, so most of the time I end up on a saturated route that can't offer me the 20 Mbit/sec needed
That makes my ping skyrocket to 1000+ until I close my AE and wait for it to stabilize

### Your Proposal

Please check this issue :(

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Probably something is constantly pushing updates to your ME system? (And, like, sizeable updates)

**Comment by repo-alt** [comment]
idk, perhaps just send updated less often? I have no idea how updates are propagated to the client tbh, have to have a look

**Comment by Sphyix** [comment]
An update to the issue.

I tried with boubs to check for heavy nbt items in my system using Open Computers, but it crashes the server
[crash-2021-11-14_21.25.05-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7538699/crash-2021-11-14_21.25.05-server.txt)
Not sure what's going on, maybe it's related to what I'm about to explain, don't really want to test again to avoid the 3rd possible crash.

Back to my issue, If I disconnect this contraption, AE bandwidth usage goes back to normal.
![javaw_JW9lSpl2WY](https://user-images.githubusercontent.com/17811922/141784019-692584c3-9d41-4313-92f2-7ec1e28aea6a.png)

Now, at a first glance you'd blame my stupidity for connecting an infinity chest with 4 storage buses, but the issue is not the infinity chest, or the 4 storage buses.

You see, on the right, there's a lonely storage bus connected to nothing.
Well, that lonely storage bus made me go crazy over my stupid ME system lagging out my connection for the past month.

If I remove it, issue is gone.
If I place it back, issue comes back.

**Comment by repo-alt** [comment]
Wow, interesting, like it is trying to find a supported inventory at that side. What if you just slap a storage bus in the random place?

**Comment by Sphyix** [comment]
> Wow, interesting, like it is trying to find a supported inventory at that side. What if you just slap a storage bus in the random place?

I edited my reply at the end, there was some type of storage (chest/drawer) on that block, storage got removed but storage bus was left in place

**Comment by repo-alt** [comment]
Ok, thanks, I'll think about it

**Comment by repo-alt** [comment]
Well, it looks like every time the infinity chests received stuff, it sends block update, so the bus pointing nowhere also receives the update, and tries to find an inventory nearby and make a handler for it. I suspect that in the setup you posted the chests sends block updates _really often_

**Comment by Sphyix** [comment]
Yes, that chest is receiving a TON of items.

And yes, your theory is correct.
I can reproduce it on every smart cable of that setup

**Comment by boubou19** [comment]
That's concerning: some server hosters limit their bandwith usage so this could put some players in a bad situation. Also @Sphyix did you see any load reduction in your dim after you fixed the issue?

**Comment by Sphyix** [comment]
Rectifying previous test, load on the dim goes up when I open my terminal even without storage buses, so there's no impact on server load.
The 25 Mbit/sec are kinda scary tho.
