### ISSUE TITLE
Buff GT light concrete walk speed bonus to be the same as chisel concrete 

### ISSUE THREAD

**Issue by MrJakobLaich** [GTNewHorizons/GT-New-Horizons-Modpack#8701]
### Your GTNH Discord Username

MrJakobLaich#6170

### Your Pack Version

2.1.1.0

### Your Server

My own Server

### Your Expectation

These two concretes should be the same:
![image](https://user-images.githubusercontent.com/40965742/137624203-e04892da-54fa-4760-905a-c3d614dad88f.png)
Bottom right one is made like so:
![image](https://user-images.githubusercontent.com/40965742/137624214-74166c8e-1bc3-4e79-a5fb-98a7960eec7f.png)
But the top left one (from the Chisel mod) has a noticably higher walking speed than the one on the bottom right (from the GregTech mod)

### The Reality

see above, imo chiseling shouldn't change this

### Your Proposal

idk, change walking speed to be the same?
Except if this is intended... ;)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment]
Why do they need to be the same though? They're from different mods.
