### ISSUE TITLE
Game crashed after placing stack of 3 existing items filters in the player 2*2 crafting grid

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8703]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Your Actions

Game crashed after placing stack of 3 existing items filters in the player 2*2 crafting grid

### Crash Report

[crash-2021-10-17_22.20.05-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7360773/crash-2021-10-17_22.20.05-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
Synchronization problem. Same as problem in NEI parallelized handler. Not sure what we can do here without tossing out the whole optimization in BW.

This affects single player games only though. Both clients playing multiplayer games and dedicated server is safe from this.
