### ISSUE TITLE
Aqua Solar works at night when thundering

### ISSUE THREAD

**Issue by sintken** [GTNewHorizons/GT-New-Horizons-Modpack#8705]
### Your GTNH Discord Username

sintken #1312

### Your Pack Version

2.1.1.0

### Your Server

Prospercraft

### Type of Server

Don't know

### Your Expectation

Placed aqua solar at night, tested with various weather conditions, expected it to  not work

### The Reality

Aqua solar will work as normal during the day, and also at night with 6x multiplier if it's thundering; if raining or clear, it will not work at all. seems like it probably shouldnt work at night regardless of the light level?

### Your Proposal

make it not work at night? idk man

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
This is quite intentional based on the code. Doesn't the game count thunderstorms as night time regardless of actual time since you can sleep through them?

**Comment by xTwi** [comment]
It does. This is not caused by any modded behaviour, so it's purely vanilla.
https://minecraft.fandom.com/wiki/Thunderstorm

> Thunderstorms can be skipped entirely with the use of a bed, regardless of the time of day.

> Unlike during regular rainstorms or snowstorms, the light level from the sky is treated as if it were 5 for the purposes of hostile mob spawning, which allows hostile mobs to spawn at any time of the day.

The problem is with my guess, there would have to be a modification to how time works and force it to be in a default state, however this would disallow players from sleeping to skip the thunderstorm.
06:00 is when day begins and you wake up.
18:32 is when night begins and you can sleep normally
