### ISSUE TITLE
2.1.1.4 dev server crash-reports

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#8709]
### Your Pack Version

2.1.1.4

### Your Server

Sp

### Type of Server

Multiplayer LAN

### Your Actions

disable Avaritiaddons-1.4b.2-GTNH.jar
start server

### Crash Report

[crash-2021-10-19_16.08.22-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7371437/crash-2021-10-19_16.08.22-server.txt)
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7371438/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
2.1.1.4 Dev have a newer version of avaritia addons

**Comment by AdminXiaoMai** [comment]
This server zip have two avaritia addons

**Comment by AdminXiaoMai** [comment]
The server cannot start normally, if possible, please fix it as soon as possible

**Comment by AdminXiaoMai** [comment]
thx
