### ISSUE TITLE
Lathe doesn't work on all logs

### ISSUE THREAD

**Issue by DarkYuan** [GTNewHorizons/GT-New-Horizons-Modpack#8721]
### Your GTNH Discord Username

DarkYuan#5002

### Your Pack Version

2.1.1.0

### Your Server

SP

### Your Expectation

Using the lathe to make long wood sticks out of Bloodwood, Eucalyptus (Natura)

### The Reality

Natura logs don't seem to have a recipe in the lathe

### Your Proposal

~~Adding all <ore:logWood> recipes to the lathe~~
Adding recipes for specific logs to the lathe (see below)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Same story. They are added too late in the initialization process that automatica recipe generation doesn't work. We had this problem with other wood related recipes before.

**Comment by DarkYuan** [comment]
Huh, didn't know you could have spaces in ids
```
Natura:tree
Natura:tree:1
Natura:tree:2
Natura:tree:3
Natura:redwood
Natura:redwood:1
Natura:redwood:2
Natura:willow
Natura:bloodwood
Natura:bloodwood:15
Natura:Rare Tree
Natura:Rare Tree:1
Natura:Rare Tree:3
Natura:Dark Tree
Natura:Dark Tree:1
```
