### ISSUE TITLE
Nitration mixture requires a single block mixer

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8722]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

There's no way to make nitration mixture without a single block mixer and cells.

Either it should be added to the LCR (or perhaps modify the LCR recipes to take sulfuric and nitric acid) or perhaps the multi block mixer could do it, or something else.

Arguably even though it's called "nitration mixture" it should be made in a chemical reactor anyway.

### Your Goal

No other mixture *requires* the single block mixer without having another method (diesel, for example, is mixed in an MV Mixer but can be made in the LCR).

### Your Vision

Allow iTNT to be made via multi blocks without having to drop to a single block or a PA.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by iouter** [comment]
https://github.com/GTNewHorizons/GTplusplus/pull/38
finished
