### ISSUE TITLE
Adding fortune to IV lootbag isn't using oredicted circuits

### ISSUE THREAD

**Issue by hohounk** [GTNewHorizons/GT-New-Horizons-Modpack#8728]
### Your GTNH Discord Username

Hoho#6758

### Your Pack Version

2.1.1.4qf-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Crafting the lootbag with any IV circuit and fortune book should result in a lootbag with fortune
E.g here I use master quantumcomputer as the circuit, the thing that takes 3 levels of recursion to craft from EV circuits
![image](https://user-images.githubusercontent.com/4471281/138564830-90664c16-b279-4dee-96b9-36841b6144a5.png)

### The Reality

Only one recipe exists using the LuV circuit that takes four levels deep recursion to craft from HV circuits (nanoprocessor mainframe)
![image](https://user-images.githubusercontent.com/4471281/138564810-40b446e4-4dba-4d7e-af12-f1fb4128f99d.png)

### Your Proposal

Oredict the recipe to allow for all the IV circuits to be used

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
i change all gt lootbags to a motor instead
