### ISSUE TITLE
Hotkey for Voidwalker's Sash of Runic Shielding

### ISSUE THREAD

**Issue by Quetz4l** [GTNewHorizons/GT-New-Horizons-Modpack#8742]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.1.4QF-2

### Your Proposal

The belt has two on/off modes. I propose to add a hotkey to change the mode.
(Voidwalker's Sash of Runic Shielding from Tainted-Magic)

### Your Goal

It is much more convenient to use the modes

### Your Vision

A convenient switch might attract others to use this belt and immerse themselves in Taumcraft for it :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Zereff06** [comment]
If you can integrate it into Traveller's Gear, that would be great

**Comment by Sheodar** [comment]
Just a bump. It is the best belt for traveling. But it's so uncomfortable to switch mode for it...
