### ISSUE TITLE
High voltage level item should more expensive than lower voltage level item.

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#8747]
### Your GTNH Discord Username

iouter

### Your Pack Version

2.1.1.3

### Your Proposal

good circult board need gold foil, advance circult board need gold and electrum foil, and more advance circult only need copper and annealed copper foil. hv motor need 4x electrum wire. it's cost exceeds the ev motor only need 4x annealed copper wire.

I think aluminum can replace copper (but I’m not sure if aluminum is more expensive than gold and silver at ev), the material that can replace annealed copper may be titanium(maybe use too much at ev), black steel, or a new alloy that requires moon ore.

### Your Goal

higher voltage level items are no more expensive than lower voltage level items.

### Your Vision

this is more reasonable and also increases the difficulty at ev.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
what about in ev 4 nichrom wires in motors ?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/718
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/219
@bombcar @iouter

**Comment by iouter** [comment]
1. and the more advanced circult board.
2. each nichrome ingot need 100s in ebf (ev, nitrogen). that's mean you need 800s to make one ev motor.

**Comment by Dream-Master** [comment]
title "High voltage level item should more expensive than lower voltage level item. #8747"

**Comment by Dream-Master** [comment]
Black Steel have ev wires as well

**Comment by Dream-Master** [comment]
@iouter

**Comment by iouter** [comment]
> title "High voltage level item should more expensive than lower voltage level item. #8747"

copper and annealed copper are low-level material. and you can consider use 1x or 2x wire, no one will accept 800s to make a ev motor.

**Comment by Methes** [comment]
A suggestion like this has no ending. Next you'll be dealing with "EV material takes 90s in EBF while IV material takes 85s. It should take longer because it's higher tier." and end up in neverending pointless nerfs bringing nothing in terms of gameplay.
Electrum takes alloy smelter while annealed copper takes Arc Furnace (+ oxygen production) so more complex machinery.

**Comment by boubou19** [comment]
Also, time gates are terrible way of gating stuff

**Comment by Dream-Master** [comment]
Black steel will work. Not that complex. Just add a oygen ebf recipe to make it a bit cheaper.

**Comment by iouter** [comment]
and the electrum is not cheap because gold ores is rare, you must use some other way to get a lot of gold.

**Comment by iouter** [comment]
@Dream-Master dont forget the the more advanced circult board.

**Comment by Dream-Master** [comment]
kk will check now

**Comment by Dream-Master** [comment]
done

**Comment by Glease** [comment]
Discussion has not ended yet. Why close it?

**Comment by defanivee** [comment]
I suggest conductive iron instead of enegetic alloy for making adv circuit board. The temperature requirement for energetic alloy is bad since an iv player without hsss coils can only overclock losslessly once. It will take 15 secs for making one board with IV hssg coil EBF. But at the time when the player is about to construct the assline, the difficulties of smelting between two eio alloys are about the same as it should have the hsss coil that time. Plus it's better to reduce the foil consumption to 8 instead of 12 as you upgrade the level of those foils.

**Comment by defanivee** [comment]
> It will take 15 secs for making one board with IV hssg coil EBF.

I didn't calculate the time of smelting Al.
BTW, the tiers setting of EIO wires doesn't seem well. Wire below EV shouldn't need EBF to make! Conductive iron wires should be in EV tier. And that is also suitable for the wires. I don't like black steels :-( It's kinda mess. 
And I should mention that one reason that higher tier items should require advanced material is to lower the unreasonably huge consumption of elementary materials. 
Or it will lead to INFINITE NERFS if you only add to the difficulties monotonously on all dimensions as Methes said above.
