### ISSUE TITLE
[Quest] Pulverize the Planet #212 (Tier 4 EV) requirements bug

### ISSUE THREAD

**Issue by Shuan97** [GTNewHorizons/GT-New-Horizons-Modpack#8748]
### Your GTNH Discord Username

Shuan#8215

### Your Pack Version

2.1.1.0

### Your Server

private

### Your Expectation

One of the quest requirements in Pulverize the Planet #212 quest is 16 Universal Fluid Cells of Ender Goo, but quest triggers even with **empty** universal cells.

### The Reality

I took stack of empty universal fluid cells from chest and it completed the quest.

### Your Proposal

I found #4628 - change to normal cells could work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by D-Cysteine** [comment]
I think the quest still needs to be updated, so we probably want to keep this open until that's done
