### ISSUE TITLE
[RFC] Fluid size normalization

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8751]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

Based on the discussion mentioned in #8743 we may want to standardize/normalize fluid "hatch" sizes on both single and multi blocks.

Currently what we have is (I can add to this table)

Tier | Material | Hatch | Cell Equivalent | Assembler
-- | -- | -- | -- | --
Steam | Iron | 8 | 1 |  
LV | Steel | 16 | 8 | 16
MV | Aluminum | 32 | 32 | 24
HV | Stainless | 56 | 64 | 32
EV | Titanium | 88 | 128 | 48
IV | Tungstensteel | 128 | 512 |  64
LuV | Palladium | 176 | 2048 | 96
ZPM | Iridium | 232 | 8192 | 128
UV | Osmium | 296 | 32768 | 160
UHV | Neutronium | 368 | 131072 | 192

### Your Goal

We should define and normalize across tiers what the "size" is roughly - some may need to be up tiered and some machines should have a fixed size perhaps, but right now we have a large difference between items.

(And some strange cases such as the UHV hatch taking a supertank II (8000k) but only holding 368).

In the past there was desire to limit fluid input in some machines because of difficulty removing fluid - but that's "fixedindev" now - you can even easily remove fluid from input hatches.

### Your Vision

Normalize the fluids cells/hatches/machines to line up consistently - either tier up reliably, or level off at a particular tier.

It's especially annoying not being able to "load" an HV input hatch from an "HV" cell.

A *potential* unification could look like this (each is a "buff" technically so there shouldn't be recipe harm):

Tier | Material | Old Hatch | New Hatch
-- | -- | -- | --
Steam | Iron | 8 | 8
LV | Steel | 16 | 16
MV | Aluminum | 32 | 32
HV | Stainless | 56 | 64
EV | Titanium | 88 | 128
IV | Tungstensteel | 128 | 256
LuV | Palladium | 176 | 512
ZPM | Iridium | 232 | 1024
UV | Osmium | 296 | 2048
UHV | Neutronium | 368 | 4096

and make "single block" machines match (or top out at 64/128 perhaps).

It would be *nice* to make cells match the above but this would be a pretty *substantial* nerf to some, and even a reasonable change would likely reduce some cell sizes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
would this be the formular 

   ``` public int getCapacity() {
        return 16000*(mTier*(mTier+1)>>1);
    }````

**Comment by Dream-Master** [comment]
```public int getCapacity() {
        return 8000+8000*(mTier*(mTier+1)>>1);
    }

this was the old values
