### ISSUE TITLE
Storage bus

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#8752]
### Your GTNH Discord Username

BangBang#8842

### Your Pack Version

2.1.1.3

### Your Server

SP and MP

### Your Expectation

Does not transfer the specified ores if you specify them in the filter.
Perlite Ore. Uvarovite Ore. Atnimony Ore. Titanium Ore. Vyroxeres Ore. Lithium Ore.
There may still be ores. After reworking the ore processing, I have not yet reached everyone.

### The Reality

Fix

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PredVesTNiK2142** [comment]
![image](https://user-images.githubusercontent.com/63409840/139726693-bf0d38b9-3a6f-4a89-93ab-d9e22bc09ab3.png)
На 1.4 упорно не хочешь идти в указанный сторедж... В остальном все что новое в фильтр добавляется - очень долго тупит но спустя минут 5 начинает работать.

**Comment by PredVesTNiK2142** [comment]
Вообщем те руды что были добавлены до обновления в фильтры (и побочки) - стали нормально летать. Все что новое добавляю - так же не летит по фильтрам.
![image](https://user-images.githubusercontent.com/63409840/139793968-e9b3d184-f096-49a2-9f5f-376f99ddc0cb.png)

**Comment by repo-alt** [comment]
Если тебе удалось воспроизвести это в single, загрузи куда нибудь, иначе что я сделаю

**Comment by PredVesTNiK2142** [comment]
Все это на сервере тестилось

**Comment by repo-alt** [comment]
Я понимаю, но пользы из этого знания никакой не извлечь.

**Comment by PredVesTNiK2142** [comment]
Есть подозрение что баг решается выгрузкой чанков на версии 1.4. Если игрок не на сервере и долго не появлялся (у нас выходило больше 8 часов) и никто больше базу не грузил из игроков - те предметы что летали мимо фильтров начинают нормально летать. Но если новые добавлять - опять багует (но опять же не все предметы). У другого игрока схожая проблема но сеть построенная немного другим образом и в фильтрах предметы вообще не с рудопереработки.

**Comment by repo-alt** [comment]
Ну т.е. и после перезагрузки значит должно начинать нормально работать. Это даёт конечно кое какую пищу для размышлений но без возможности просто проверить такой баг не найти.

**Comment by PredVesTNiK2142** [comment]
У нас большая часть фильтров стала работать. Причем в основном те которые были раньше периода выгрузки добавлены
