### ISSUE TITLE
Storage Drawers Is too slow

### ISSUE THREAD

**Issue by abitaredomdepo** [GTNewHorizons/GT-New-Horizons-Modpack#8763]
### Your GTNH Discord Username

angeldust23 #2076

### Your Pack Version

2.1.1.0

### Your Server

private

### Type of Server

Don't know

### Your Expectation

до обновления 2.1.1.0 ящики мода "Storage drawers" работали исправно а именно: выдавали предмет без задержек и скорость выдачи зависела от скорости блока который вынимает предметы

before the update 2.1.1.0, the boxes of the "Storage drawers" mod worked properly, namely: they gave out the item without delays and the speed of issuing depended on the speed of the block that takes out the items

### The Reality

после обновления 2.1.1.0 появилась некая задержка на извлечение предмета из системы ящиков. на чем она основывается задержка не понятно. и задержка настолько большая что пользоваться ящиками стало не удобно и бесмысленно

after update 2.1.1.0, there was a certain delay in retrieving an item from the crate system. on what it is based on the delay is not clear. and the delay is so great that it became inconvenient and pointless to use the boxes

### Your Proposal

я не уверен является ли  это ошибкой, но я предлагаю вернуть как было в любом случае.
не могли бы подсказать как исправить это в конфиге или где именно в моде было это изменено? я не хочу ждать выхода новой версии

I'm not sure if this is a bug, but I suggest returning it anyway.
Could you tell me how to fix this in the config or where exactly in the mod it was changed? I do not want to wait for the release of the new version

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Retster** [comment]
Can prove that all is fine with drawers work at 2.1.1.0 with conveyors/conduit.

**Comment by repo-alt** [comment]
I didn't experienced that, I also asked in discord, and no one confirmed such issue, so idk. You can also try version 2.1.1.4qf2

**Comment by Ydrec** [comment]
There seems to be quite an obvious reason to his case

Screenshot he posted of his drawer "storage"
https://media.discordapp.net/attachments/838835379523682414/900496583777456158/unknown.png

**Comment by abitaredomdepo** [comment]
even with this number of drawers, the ejection delay is already noticeable. check made in single.
Could you reproduce this system and check how quickly items are retrieved?
![image](https://user-images.githubusercontent.com/51705777/139906447-93d11c93-3521-4548-a515-a3afa0632c60.png)

**Comment by Retster** [comment]
> even with this number of drawers, the ejection delay is already noticeable. check made in single. Could you reproduce this system and check how quickly items are retrieved? ![image](https://user-images.githubusercontent.com/51705777/139906447-93d11c93-3521-4548-a515-a3afa0632c60.png)

how about your TPS is doing?

**Comment by abitaredomdepo** [comment]
> There seems to be quite an obvious reason to his case
> 
> Screenshot he posted of his drawer "storage" https://media.discordapp.net/attachments/838835379523682414/900496583777456158/unknown.png

Before update this system works pretty fast, so i think this is bug

**Comment by abitaredomdepo** [comment]
> how about your TPS is doing?

![image](https://user-images.githubusercontent.com/51705777/139907700-21c679d6-0954-4c03-8495-0da2a82cadb7.png)
I'm not sure about your question, but TPS on single player is normal

**Comment by Skiftcha** [comment]
i confirm this is strange

**Comment by repo-alt** [comment]
Well, I admit I didn't use large drawer systems. What was the version that did not have the delay?

**Comment by mitchej123** [comment]
The maximum number of drawers that can be looked at from the controller was added recently(ish) to prevent large drawer cubes on servers.  It's a configurable option.

**Comment by repo-alt** [comment]
I doesn't explain delay though

**Comment by abitaredomdepo** [comment]
> Well, I admit I didn't use large drawer systems. What was the version that did not have the delay?

I not sure which latest version when this works correctly but on last server where i played on 2.1.0.0 this is was work exactly
