### ISSUE TITLE
Healing Axe quest in Coins suggests the original doesn't work for party, but it apparently does

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8764]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

The "Healing Axe 2.0" quest implies that "Hunger No More" is not shared with the party, but apparently it is.

### Your Goal

The quest text should be updated to reflect how it works

### Your Vision

Clarify if Healing Axe quest is to be shared for party.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Eldrinn-Elantey** [comment]
As far as I can tell, my question is posed correctly. If each player makes an axe for himself, then let the result of completing the quest not be transmitted to all team members. But if now this quest is shared, then you need to change the text of related quests.
