### ISSUE TITLE
Better Questing visual glitch when viewing long task list

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#8766]
### Your GTNH Discord Username

Pao

### Your Pack Version

2.1.1.4QF2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

After scrolling down a long list of tasks in the questbook and closing it, any task in Step 2 or later disappears until you scroll up or down with the mouse.  Happens on Large GUI scale without Optifine installed.  
![image](https://user-images.githubusercontent.com/9247381/139961390-49125c3e-10d3-4790-950a-03cc1595d0ad.png)
![image](https://user-images.githubusercontent.com/9247381/139961425-f71b115e-368d-4dd6-945e-7ebcf40ca37a.png)

### The Reality

Tasks disappear until scrolling, making it a bit of a pita when trying to quickly check the questbook for what you're working on

### Your Proposal

Make the task steps not disappear when you reopen the questbook

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I get this on gui scale large in 2.1.1.0 with Optifine; haven’t tested if it happens without optifine.

**Comment by Steelux8** [comment]
I get this as well, with 2.1.1.3 and have Optifine. There's also another issue, where long descriptions need me to scroll down to read the rest, but the page jumps back up to the beginning constantly.

**Comment by Minepolz320** [comment]
Yep same problem
