### ISSUE TITLE
Suggestion: Unification of storage of things performing the same functions

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#8774]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.1.0

### Your Proposal

Add the ability to store additional cast added by the GT: New Horizons mod in the Chest Pattern from Tinker's Construct mod

### Your Goal

Unification of storage of things performing the same functions

### Your Vision

To solve some issues of combining and expanding mods, several cast have been added and it's quite sad that they can't be put in the Pattern Chest

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by PolkageistHS** [comment]
I got the Shard Cast from Tinkers Gregworks done, just waiting on a PR to be accepted.  The other ones in GTNHCore will take a bit more to do.

**Comment by PolkageistHS** [comment]
Should be resolved with these two accepted PRs: 

https://github.com/GTNewHorizons/TinkersGregworks/pull/7

https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/231

**Comment by Eldrinn-Elantey** [comment]
> Should be resolved with these two accepted PRs:
> 
> [GTNewHorizons/TinkersGregworks#7](https://github.com/GTNewHorizons/TinkersGregworks/pull/7)
> 
> [GTNewHorizons/NewHorizonsCoreMod#231](https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/231)

As far as I can see these two were closed. What to do about it?

**Comment by TheElan** [comment]
> > Should be resolved with these two accepted PRs:
> > [GTNewHorizons/TinkersGregworks#7](https://github.com/GTNewHorizons/TinkersGregworks/pull/7)
> > [GTNewHorizons/NewHorizonsCoreMod#231](https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/231)
> 
> As far as I can see these two were closed. What to do about it?

They are merged, so it should be in dev now.

**Comment by Eldrinn-Elantey** [comment]
> > > Should be resolved with these two accepted PRs:
> > > [GTNewHorizons/TinkersGregworks#7](https://github.com/GTNewHorizons/TinkersGregworks/pull/7)
> > > [GTNewHorizons/NewHorizonsCoreMod#231](https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/231)
> > 
> > 
> > As far as I can see these two were closed. What to do about it?
> 
> They are merged, so it should be in dev now.

I mean, who will close this issues?
