### ISSUE TITLE
Recipie for Schematic Conflict

### ISSUE THREAD

**Issue by Evuflow** [GTNewHorizons/GT-New-Horizons-Modpack#8775]
### Your GTNH Discord Username

Evuflow#9718

### Your Pack Version

2.1.1.4QF-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Materials for the recipie are put in an assembler.
4 Steel Plates
4 LV Circuits
Programed Circuit set to 1

Expected to receive Schematic 6956:32490

### The Reality

Receiving instead Steel Tank Wall (1159:13)

Recipie:
2 Steel Plates
Programmed Circuit set to 1

### Your Proposal

Change the recipie to use a differend programmed Circuit number.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/782a3cadc80f5df0fb7882d4a66ab362f79b1bcc
