### ISSUE TITLE
Typo in solar quest

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#8776]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.1.4QF-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Quest : Power of the sun 1x1 luv
chapter: how to generate power
Quest requires zpm tier solar panel  but quest name states that its luv tier, change quest name
![image](https://user-images.githubusercontent.com/39595617/140494123-87cbe2e7-f0c4-402e-a362-7cfdac8ec76d.png)

### The Reality

-

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Is that possibly correct? Compared to the other ones? I know that solars are usually built two tiers lower than you currently are.

If it *is* incorrect I can fix.

**Comment by bombcar** [comment]
checked, it's wrong but hard to see because of where it is in the json file; PR above
