### ISSUE TITLE
Steam grinder can no longer be built in steam age

### ISSUE THREAD

**Issue by kenken244** [GTNewHorizons/GT-New-Horizons-Modpack#8781]
### Your GTNH Discord Username

Kenken244#9849

### Your Pack Version

2.1.1.3

### Your Server

sp

### Your Expectation

The steam grinder should be buildable in the steam age, where it was intended

### The Reality

after the changes to input and output bus recipes, they are no longer craft able in steam age,as those now require an assembler.

### Your Proposal

either:
make a bronze/wrought iron bus specifically for use with the steam grinder, or:
make the ulv and/or lv busses craftable without an assembler, like they used to be

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by iouter** [comment]
The steam grinder must use the input/output bus (STEAM). it can't use the ulv or lv input/output bus.

**Comment by kenken244** [comment]
ah, my mistake. I'll close the issue. thanks for the help
