### ISSUE TITLE
Addition of fluid display cover

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8785]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.1.1.0

### Your Proposal

It would be nice to have a fluid display cover - that when applied to a pipe or supertank would show a “window” displaying proportionaly the amount of fluid in the block. 

### Your Goal

Be able to see at a glance from across the room if your supertank III of radon is almost full or almsot empty (similar to how you can easily visually check a railcraft tank with valve). 

### Your Vision

This would also allow the “wall of fluid tanks” and preserve the ability to quickly identify what is in each tank (similar to how you can do with barrels and buildcraft tanks).

If it would introduce fps issues people can simply not use them or only use them selectively. 

It could also be possible to modify the fluid detector cover to display this type of “window”. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
This would be especially useful to compensate for the lack of Extra Cells 2, due to the massive hit to performance that addon causes if used. Having a quick overview of all your fluid amounts is one of its purposes.

**Comment by Glease** [comment]
This is now actually possible as we can specify cover texture dynamically.
