### ISSUE TITLE
Pattern terminal 64x select

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#8786]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.1.4QF-2

### Your Proposal

Add x64 button here
![image](https://user-images.githubusercontent.com/39595617/140624114-106cf010-a163-47b1-b1d6-15487ffc61b0.png)
can also add x16

### Your Goal

tired of clicking 

### Your Vision

It will make pack less clicky XD

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
ghost items with a stack size of 64 is a thing...

**Comment by LewisSaber** [comment]
when i shiftclick from jei i get only 1 item per slot

**Comment by boubou19** [comment]
dragging the four stacks in the grid is faster tho

**Comment by iouter** [comment]
you can hold down shift and click the button to scale to maximum possible now.

**Comment by repo-alt** [comment]
As said above, shift click "x2" button. added for this purpose.
