### ISSUE TITLE
Translocators are causing lag

### ISSUE THREAD

**Issue by Silivek** [GTNewHorizons/GT-New-Horizons-Modpack#8789]
### Your Pack Version

2.1.1.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

I used a steam grinder to process redstone ore into the impure redstone dust. Translocators automatically take the redstone from the output hatch and place it into a gold chest and a separate translocator that further processes the crushed ores into a steam oven to smelt them into ingots. I expected the impure redstone sitting in the chest to exist with little to no tps lag.

### The Reality

I have large amounts of tps lag that was fixed after washing all of the impure dust. The tps drops based on how many slots are taken up by the redstone dust, so stack size doesn't matter for it.
Screenshot of the tps being low with the impure dust in a chest:
![2021-11-07_14 47 22](https://user-images.githubusercontent.com/43481327/140662109-b362eaa8-4d96-4b82-ab30-e8a15753e996.png)

### Your Proposal

I have no idea how to fix this. I imagine it has something to do with either the translocators or the impure items.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Silivek** [comment]
Further testing reveals that it is the translocators being the issue, the more stacks the translocator tries to move the more the tps reduces, especially if the translocator cannot place the item into the inventory it is targeting. Translocators reducing tps is a known issue, although unsure if this specific instance of the tps lag is known.

**Comment by boubou19** [comment]
can you profile it with warmroast / visualVM?

**Comment by Silivek** [comment]
I don't know what that means unfortunately

**Comment by Silivek** [comment]
Alright, I've figured out what those are but I have no idea how to use them.

**Comment by bombcar** [comment]
https://gtnh.miraheze.org/wiki/Warmroast Has some hints

**Comment by Silivek** [comment]
I have Warmroast installed and I have it running, but I don't know how to look at the results. It says to use a url but i have no idea what url it wants.

**Comment by bombcar** [comment]
http://localhost:23000 by default.

Open in Chrome, save as Web Page Complete, zip, post.

**Comment by Silivek** [comment]
[WarmRoast.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7670736/WarmRoast.zip)
Alrighty, it's definitely the translocators. Super cool tool, I'm gonna be using this more

**Comment by Silivek** [comment]
The lag is definitely a lot better on singleplayer for me but when I was on a server I could instantly drop the tps down.

**Comment by boubou19** [comment]
![image](https://user-images.githubusercontent.com/12850933/145086388-8d5fca36-0ae1-41b4-93b7-da245fa14875.png)
i guess it's because it must spin over all the furnace recipes

**Comment by Silivek** [comment]
Yeah, GTNH has a lot of those so it makes sense.

**Comment by bombcar** [comment]
translocators seem to verify if the slot is not only empty, but also "valid" or something
speedup may let it push items into something that shouldn't normally take them

**Comment by bombcar** [comment]
> [WarmRoast.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7670736/WarmRoast.zip)
> Alrighty, it's definitely the translocators. Super cool tool, I'm gonna be using this more

@mitchej123 heres a decent warmroast which matches what we’ve seen - the devices trigger the “recipe search” in the attached block (c.f. The chisel stupidity)

**Comment by Silivek** [comment]
It seems to me that CodeChicken keeps having efficiency issues, I've seen mods from them messing up many times. It could just be the sheer amounts of recipes but idk

**Comment by mitchej123** [comment]
It's a combination of 1) the target inventory iterating over... every... single.. furance recipe... every... attempted... insert.  and 2) translocators trying to insert really, really fast

**Comment by mitchej123** [comment]
Also, re: CodeChicken - it (and MC 1.7.10) was never designed with the sheer number of recipes that GTNH has in mind.  It also has been used by many mods, and largely untouched for 7+ years.  I'm sure some small tweaks here and there can improve the performance, especially as we get more detailed profiling results like this.

**Comment by mitchej123** [comment]
Thanks for the profiling, I was able to put together a fix for this - https://github.com/GTNewHorizons/Hodgepodge/pull/37

On my testing it took it down from this:
![image](https://user-images.githubusercontent.com/1894689/145665708-44cc05a7-dc7b-44ef-882c-3b81bf5100f8.png)

to this:

![image](https://user-images.githubusercontent.com/1894689/145665699-07db3962-6128-463d-9886-b48ac8c1e147.png)

**Comment by bombcar** [comment]
hmmm now take a 🔨 to java.lang.Thread.sleep() it’s using a ton of time
