### ISSUE TITLE
Change HSS-G quest to not be gated unnecessarily

### ISSUE THREAD

**Issue by Elisis** [GTNewHorizons/GT-New-Horizons-Modpack#8790]
### Your Pack Version

2.1.1.0

### Your Proposal

Remove the IV Mixer prerequisite of the HSS-G quest. 
![Uploading image.png…]()

### Your Goal

The IV Mixer isn't required to get HSS-G dust in actual playthrough
![image](https://user-images.githubusercontent.com/28530295/140705899-8988b9e0-48fb-48da-94a9-ddc3d48dcc59.png)

### Your Vision

So people aren't forced to make IV mixer, a relatively annoying process, in order to complete the HSS-G quest/get naquadah/a ton of other stuff.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GlodBlock** [comment]
dream has planned to remove these alloy dusts' handcraft recipe.

**Comment by Elisis** [comment]
Okay, then make it an EV mixer recipe as in every other sense is HSS-G more of a late EV material.

**Comment by Dream-Master** [comment]
i did Already. There is a pr but no one checked or approved it :)

**Comment by Elisis** [comment]
> So people aren't forced to make IV mixer, a relatively annoying process, in order to complete the HSS-G quest/get naquadah/a ton of other stuff.
 What about this, then? Deleting the hand crafting recipe and moving it to an EV mixer does the job pretty fine

**Comment by Dream-Master** [comment]
is the recipe an iv one ? Need to check

**Comment by Elisis** [comment]
Is in 2.1.1.0
![image](https://user-images.githubusercontent.com/28530295/140715428-f9ddbc2f-4ee5-455b-8ccf-bff7b2207968.png)

**Comment by dipo33** [comment]
Hi, I would like reopen this issue and point out that this is still an issue. As @Dream-Master mentioned, the recipe was moved to an EV Mixer, but the quests weren't updated accordingly to this change. Meaning the quests still requires us to make IV mixer before the HSS-G dust quest.

This is an issue on 2.1.2.3qf
