### ISSUE TITLE
Universal fluid cells gives tin dust when macerated

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8797]
### Your GTNH Discord Username

Maniifestantes

### Your Pack Version

2.1.1.4QF2

### Your Proposal

Change or remove macerating universal fluid cell

### Your Goal

You can make empty cells out of tin, steel and PTFE on a bending machine. you can then turn the empty cells into universal fluid cells and macerate it to get 2 tin dusts and 3 glass dusts.

### Your Vision

That needs to be removed or rearranged somewhat.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
To be precise, you can use two ingots to get a fluid cell, convert it to universal, and macerate it for 2 tin dust and 3 tiny glass dust, for free glass.
