### ISSUE TITLE
Tweaking Multiblocks / Light Sources Fixing

### ISSUE THREAD

**Issue by xTwi** [GTNewHorizons/GT-New-Horizons-Modpack#8799]
### Your GTNH Discord Username

Neo-Twilight#6828

### Your Pack Version

2.1.1.0

### Your Proposal

Add a new craftable "cheap" Air/Similar block that can be added optionally to any multiblock (preferably with a hollow inside that cannot be replaced by: 
-Warp Theory effects
-Amber Lamps (thaumcraft)
-Other things that spawn light effects/spawn things around the player.

Alternatively, allow multiblocks to function when they have something inside them.

### Your Goal

This would allow for Amber Lamps as a viable light source as currently they spawn invisible light sources 16 blocks each direction around themselves until the area is deemed "safe"/non-spawnable for mobs.

It would also directly buff multiblocks and prevent them from being griefed unknowingly.

### Your Vision

Would make multiblocks unable to be griefed by filling their insides with a fluid/block that they cannot function with.  Quality of life/better pack experience.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Even if it wasn’t exactly cheap - and potentially Gated in thaum similar to the amber lamps themselves - this would be a nice addition.

**Comment by boubou19** [comment]
i thought the multi were checking for any air type block and not the air block itself already?

**Comment by xTwi** [comment]
the warp status that in chat is listed as "You feel revitalized" can spawn water source blocks in any enclosed space. including multis, causing them to stop functioning, amber lamps and maybe floodlights spawn invisible light source blocks which can cause basically the same thing

**Comment by D-Cysteine** [comment]
Rather than making the new "air" block craftable and manually placed, we could also just have the multiblock itself automatically replace "interior" air blocks with the new block when it forms?

Though, I imagine that it wouldn't be possible to automatically change them back to regular air when the multiblock is being dismantled, so we should tell the player that this is happening so that they know to break the new blocks too. Or maybe we could give the new block a texture so that it's visible, if it's only ever going to be placed inside things like EBFs where it wouldn't be seen anyway.

**Comment by GTNH-Afx237v7** [comment]
I take it this issue adresses two topics:

1. Multis no longer working when artificial light blocks are placed inside -> would need to check which mod causes this and look at the „isAir“ check that is being performed by the multi (as boubou mentioned).
2. Modify warp effects, such as spawning water blocks, to ensure not happening inside of multis 

I believe this is the better approach over adding a new block spawning mechanism to avoid the above mentioned issues.

**Comment by boubou19** [comment]
For me, if a block should have air property but isn't detected by the multi, then we should ensure the structure check use the "isAir" check and modify the property of said block.

The warp effects would have a hard time to determine if a block is in a non hollow multi, and how to detect the places were multi expect air blocks ? (in front of the turbine, or on the side of the tectech quantum computer for exemple) Also, that would need a list of all the multis, not just GT typed ones. The warp effects are fine as is, it's part of the warping mecanic. The more you do magic, the more strange things can happen. I experienced it once where it messed with my multismelter, and once it happened,you'll remember to check it when the multi doesn't form spontaneously. The only thing that can be done imo is tweaking the warps with block spawn to not be availiable too early in the warp levels. In addition of that, players or server owner are free to disable warp effects in the warp theory config iirc.

**Comment by Glease** [comment]
isAir is universally used automatically as long as you use structruelib, i.e. everyone. Dunno why you still find multis broken by arcane lamps.

**Comment by bombcar** [comment]
So the remaining issue is warp spawning liquids/plants inside it - do bats still do that too? @D-Cysteine would it be possible to modify those warp effects to avoid multi blocks?

**Comment by D-Cysteine** [comment]
Do you mean, does the bats warp effect spawn bats within multiblocks? It should be able to - the same check is used for all warp effects. Though, I don't think that having bats within your multiblock would break it, as bats aren't blocks.

As for avoiding multiblocks, like boubou said, it would be difficult as we'd have to check against all possible multiblocks. This would be complicated even more with the addition of hollow variable-length multiblocks, which we might want to add in the future. I agree that the suggestion in this issue, having a new not-quite-air block replacement, would be a much cleaner way to accomplish this.

Also, note that an [unstable ingot block](https://ftbwiki.org/Unstable_Ingot_Block) provides x-ray functionality. I *think* those are craftable. So you can place one of them against each multiblock to have a "window" that will let you see inside it. Won't prevent the problem, but will help you find it at least.

**Comment by xTwi** [comment]
I think what D-Cysteine suggested aka 
> Rather than making the new "air" block craftable and manually placed, we could also just have the multiblock itself automatically replace "interior" air blocks with the new block when it forms?

would be a good thing, but it would be rather a pain-in-the-ass task to do for multis.

> Do you mean, does the bats warp effect spawn bats within multiblocks? It should be able to - the same check is used for all warp effects. Though, I don't think that having bats within your multiblock would break it, as bats aren't blocks.
this is correct. only blocks placed inside the multi can break the multi.
--
> isAir is universally used automatically as long as you use structruelib, i.e. everyone. ~Dunno why you still find multis broken by arcane lamps.~ Arcane lamps etc. will not break any of your multi in 2.1.1.4+ because that's when structurelib merge takes place.

Thank you for checking, Glease. I just wanted to be certain.

Is it possible to utilize structurelib to generate isAir blocks inside a multi upon forming?
