### ISSUE TITLE
Fluid hatch locked to water does not display it

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#8801]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

2.1.1.4qf2

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Locked fluid display does not work with water

### The Reality

![image](https://user-images.githubusercontent.com/23512002/140936679-f3579444-241c-4113-9888-667a12c8b86e.png)
![image](https://user-images.githubusercontent.com/23512002/140937123-6eb64170-5cc4-46b0-8c21-741d59ff4e58.png)
Scanner shows that the hatch is correctly locked

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
does it happen with any other ic2 fluid?

**Comment by repo-alt** [comment]
Which fluids are ic2?

**Comment by boubou19** [comment]
i'd say UUM for sure, there is also a steam one, and maybe lava as well. Iirc to determine if it's a fluid, just right click with the cell on the ground and if it breaks the cell while placing the fluid then it's ic2.

**Comment by repo-alt** [comment]
Lava doesn't work too

**Comment by Florexiz** [comment]
![image](https://user-images.githubusercontent.com/29033773/141084663-528ec69d-27b3-4bef-a8b1-ac6f618c7115.png)
Scanner display latest fluid actually, Hatch above not even locked at all

**Comment by repo-alt** [comment]
Ok, scanner should check for `isFluidLocked()`

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/722
