### ISSUE TITLE
EV Conveyor belt can't use rubber sheets in assembler, but can handcrafted

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8803]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

The EV conveyor belt can be built with rubber sheets if hand crafting, but if assembling the rubber sheet recipe is missing.

### Your Goal

Either the hand-craft should remove rubber sheets or the assembler recipe should include them

### Your Vision

This would be consistent

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
The EV pump works with rubber rings so I suspect the assembler for conveyor was just an oversight.

**Comment by Dream-Master** [comment]
yea will check it
