### ISSUE TITLE
[RFC] Lanthanide Group Overhaul

### ISSUE THREAD

**Issue by Elisis** [GTNewHorizons/GT-New-Horizons-Modpack#8805]
### Your Pack Version

2.1.1.0

### Your Proposal

Addition of a new Platline-esque processing chain for lanthanide metals, stemming from monazite ore. (See graphs below for a non-exhaustive impression). 
![image](https://user-images.githubusercontent.com/28530295/141034114-2eeaf6d5-6b28-4c2b-a7bb-c9eb2f112237.png)
![image](https://user-images.githubusercontent.com/28530295/141034125-9471cd78-778c-4a6e-ad85-e7d9620d46b8.png)

### Your Goal

This line will allow the player to gain metallic lanthanides in a way that offers more of a challenge than the current way, which simply involves centrifuging Rare Earth from redstone. It will also add much-needed content to tiers where such content is considered lacking.

### Your Vision

See Goal

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
Okay I'm just going to make work a PR at this point given it's obvious nobody cares about this either way

**Comment by Dream-Master** [comment]
if no one replay means not nobody cares.

**Comment by boubou19** [comment]
and if nobody cares then nobody wants it to be forced uppon them

**Comment by Elisis** [comment]
> and if nobody cares then nobody wants it to be forced uppon them

If people hated it enough, they would've said that this is not something they want added

**Comment by draknyte1** [comment]
> > and if nobody cares then nobody wants it to be forced uppon them
> 
> If people hated it enough, they would've said that this is not something they want added. I've not seen one suggestion made towards it, nor any kind of opinion towards the thing in general.

That suggests > 1% of people read GitHub.

**Comment by Elisis** [comment]
> hat suggests > 1% of people read GitHub.

I also put a ton of stuff in the Discord and still nothing resulted.

**Comment by boubou19** [comment]
lot of stuff get posted on the discord and in comparison few things made it in the pack. That's probably why: people may have thought it was yet another suggestion that won't make it.

**Comment by Elisis** [comment]
Hence the RFC. I'll put the link to this in #github-discussion but I really doubt it'll make much of a difference.

**Comment by boubou19** [comment]
honestly we have already the plat line and the naq line in the pack. no actual new mecanic or machine. It's just a line just to add steps for no other reason than tedium called reality. but that's just my opinion

**Comment by GTNH-Colen** [comment]
So, no more Europium fusion?

**Comment by Elisis** [comment]
This'll either be the low volume or high volume alternative to Eu fusion, so either of higher or lower tier, but it's not intended to directly replace fusion.

**Comment by GlodBlock** [comment]
> honestly we have already the plat line and the naq line in the pack. no actual new mecanic or machine. It's just a line just to add steps for no other reason than tedium called reality. but that's just my opinion

at least I add a new mulit machine which has a complete different work mechanism from other machines in the naquadah line.

**Comment by Steelux8** [comment]
Lanthanides don't have many uses IRL, so what gives this processing line a proper use in GTNH?

**Comment by Elisis** [comment]
> Lanthanides don't have many uses IRL, so what gives this processing line a proper use in GTNH?

I mean, we already use Yttrium, Europium, Neodymium, Samarium. Plus I'm planning on changing UHV+ tier materials to alloys that require other lanthanides.

**Comment by GlodBlock** [comment]
@Elisis are you still working on it?
