### ISSUE TITLE
Volumetric flasks should report content to/by OC 

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#8807]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

2.1.1.4qf2

### Original Request

subj

### Responding developer

@repo-alt

### Context

https://discord.com/channels/181078474394566657/794285628141207552/907791464786976918

### Developer's Promise

fix

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/141085013-f537b26e-5922-4499-8d39-64fc7ae7f9e5.png)

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/OpenComputers/pull/34
