### ISSUE TITLE
NULL instruments in AE pattern

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#8808]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.1.4 QF2

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Shift click + ? in nei for auto completion should produce correct patterns

### The Reality

When you auto fill pattern terminal from NEI via "?" it place NULL material GT tools there.
![image](https://user-images.githubusercontent.com/29033773/141080065-c9ea8d72-f98b-4fd5-aa14-094a05facfc9.png)
This sadly tricks AE into thinking that every GT instrument used to craft this item is single use, those requiring more tools than it have to.

### Your Proposal

Make AE accept NULL GT tools as valid tools, so you shouldn't replace autofilled tools with random tools from your AE

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
AE only Version of GT Tool(s) with zero durability?
