### ISSUE TITLE
Opencomputers Item.tag for Forestry circuit board with lamps does not work correct

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#8809]
### Your GTNH Discord Username

John S#7565

### Your Pack Version

2.1.1.2

### Your Server

Local

### Type of Server

Single Player

### Your Expectation

Want to read with Opencomputers Item.tag for Forestry circuit board with lamps.
![image](https://cdn.discordapp.com/attachments/690956623463710770/908300613178249256/unknown.png)

### The Reality

Opencomputers Item.tag for Forestry circuit board with lamps does not work correct, it return somethings unreadable strings like this:
```
‹       гb``b`a`ж``uvФу4fђOКМЛЛLХKО,J.Н,С+.ЙМ-НI,Й/ТKIM,ЙЂ*4$VЎ±

€PИдЙ ‡ЄК'±2їґ$®” C}.У   
```

### Your Proposal

Make possible to determine lamps used in Forestry circuit board with Opencomputers. 
Thank you wery much. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Fixed via https://github.com/GTNewHorizons/OpenComputers/pull/34
