### ISSUE TITLE
GT++ Extruder feature(bug)

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#8810]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.1.1.0

### Your Server

Eta

### Your Expectation

Trying to put maximum busses into GT++ Extruder.

### The Reality

If you put muffler hatch **at opposite side of controller**, you can put maximum+1 bus.

### Your Proposal

Muffeler hatch can be placed only at opposite side of controller

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
all a2 multis are using structurelib now and such structure bug should no more exist.
