### ISSUE TITLE
Incorrect display of information in the interface of the TinkersConstruct foundry

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#8812]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.1.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

When using the TinkersConstruct foundry, you can hover the cursor over the molten metal and get information about its quantity
![image](https://user-images.githubusercontent.com/46845681/141348312-9a73010f-7dc3-4940-b062-30e54e1779da.png)

### The Reality

When I hover the cursor, I expect to see the amount of liquid, for example, molten bronze in ingots, but instead I see only in mB. I conducted a couple of tests and it turned out that this happens when the game language is changed from English to Russian.
![image](https://user-images.githubusercontent.com/46845681/141348329-adb8b2e3-2863-498d-a359-83489bc4e196.png)

### Your Proposal

I would like the mod's functions to work the same regardless of the game's interface language.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eldrinn-Elantey** [comment]
Me and @bomber assume that the problem lies here https://github.com/GTNewHorizons/TinkersConstruct/blob/1b99d5adf9eb00d9c2494eb86b70caf19e5af0fc/src/main/java/tconstruct/smeltery/gui/SmelteryGui.java#L367

**Comment by bombcar** [comment]
Perhaps it is confused by the translation being slightly different in some cases? It seems to not realize metals are metal.

**Comment by bombcar** [comment]
gui.smeltery.molten.check=Расплавленн.
fluid.lumium.molten=Расплавленный ламиум

gui.smeltery.molten.check=Molten
fluid.lumium.molten=Molten Lumium

Is the period trying to be a wild card to support the different matchings? If so It apparently isn't working.

Based on DE it seems:

gui.smeltery.molten.check=Schmelze
fluid.lumium.molten=Geschmolzenes Lumium

the fix will be

gui.smeltery.molten.check=Расплавленн

(remove period)

**Comment by bombcar** [comment]
Huh or maybe German doesn't work either.

**Comment by Eldrinn-Elantey** [comment]
I checked this fix with myself `gui.smeltery.molten.check=Расплавленн` 
Everything works
![image](https://user-images.githubusercontent.com/46845681/141675776-1bfc5047-dbea-43d4-b516-7da2d1f7739f.png)
