### ISSUE TITLE
ME Sub-net Problem

### ISSUE THREAD

**Issue by berta24** [GTNewHorizons/GT-New-Horizons-Modpack#8813]
### Your GTNH Discord Username

Berta24

### Your Pack Version

2.1.1.4Q-F2

### Your Server

Private Online Server

### Type of Server

Multiplayer LAN

### Your Expectation

I've connected my main network with another network with an interface-storage bus connection.
![image](https://user-images.githubusercontent.com/25983005/141373973-332d42b0-a77f-4423-8406-3a629a964ba5.png)
Yellow is my Main network, Red is new one. 
The system works, i can see the Main inventory from the new network and i can pick up and put down items.
I would expect that interfaces and export/import bus would work 

### The Reality

In reality that one doesn't happen...
![image](https://user-images.githubusercontent.com/25983005/141373843-2c2f1e3d-6bb8-4a58-9d79-afa394337af8.png)
There is a filter (Salt) in the interface, and a conveyor belt on the input bus but it's not taking any item in it... 

### Your Proposal

Extract items from Main network like it should

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Do you have security terminal in the main network. If yes, does it have an empty configured card in it

**Comment by berta24** [comment]
Ok with the correct card now it work, thanks

**Comment by boubou19** [comment]
Might be worth mentionning this elsewhere if it's not already.

**Comment by repo-alt** [comment]
I thought it to be a well known fact (or ancient design flaw, depending how you look). It may be mentioned in quests for sure.
