### ISSUE TITLE
Dogecoins not detected in Coin Conversion quest

### ISSUE THREAD

**Issue by chellebodnar** [GTNewHorizons/GT-New-Horizons-Modpack#8815]
### Your Pack Version

2.1.0.0

### Your Server

private server

### Type of Server

Multiplayer LAN

### Your Expectation

I crafted 32 dogecoins using the recipe (brass plate and coinage mold in the forming press).  I expected that when I clicked "detect/submit" on the Coin Conversion quest in the Open Computers tab it would consume them and allow me to claim a BitCoin as a reward.

### The Reality

When I click detect/submit nothing happens, even though the 32 dogecoins are in my inventory.

### Your Proposal

Fix the quest!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Florexiz** [comment]
Working fine in dev versions tho
