### ISSUE TITLE
Remove GT++

### ISSUE THREAD

**Issue by Oklahomo1922** [GTNewHorizons/GT-New-Horizons-Modpack#8817]
### Your GTNH Discord Username

ADeus#8041

### Your Pack Version

2.1.1.0

### Your Proposal

Just remove GT++
It has tons of lags, bugs, and incorrect stuff going on.
Since Alkalus don't want to fix it, eventho we asked him, it will be easier just to remove it.

### Your Goal

Game will be better

### Your Vision

Just do it, cmon

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Impos913** [comment]
Replacement where

**Comment by Oklahomo1922** [comment]
> Replacement where

Gregtech PA's :) No lag - no bug - no problem

**Comment by GTNH-Afx237v7** [comment]
The decision to remove GT++ has been made months ago. There is even a milestone for that. The replacement (Obama) is in progress, though no definitive ready date available.

**Comment by Impos913** [comment]
One multiblock as replacement for a whole giant mod. Nice

**Comment by Oklahomo1922** [comment]
> The decision to remove GT++ has been made months ago. There is even a milestone for that. The replacement (Obama) is in progress, though no definitive ready date available.

Give me at least one reason why we need a REPLACEMENT?
If you replace a piece of shit with another piece of shit - it's not helping

Why do you need tons of weird cringe alloys, cringe machines? When you can just make PA's?

Alk is just fucking trash piece of gay shit that don't know how to code. Fuck him.

**Comment by Impos913** [comment]
> The decision to remove GT++ has been made months ago. There is even a milestone for that. The replacement (Obama) is in progress, though no definitive ready date available.

Is it really in progress? I thought bot was making it and he left.

**Comment by GTNH-Afx237v7** [comment]
Please be civilized.

**Comment by Oklahomo1922** [comment]
> Please be civilized.

Tell that to your dead mom

**Comment by Impos913** [comment]
Also ban this hater troll already

**Comment by boubou19** [comment]
As stated above, it's already on its way. Now i'm closing and locking this, as clearly this is not needed.
