### ISSUE TITLE
OC components vanishing

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#8819]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.1.4 QF2

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

OC components aren't single use

### The Reality

For some reason OC components in computers are constantly vanishing. Cant figure out exact timing when this happens, but I already lost few sets of working computers. Also same happened to Cinobi and spawn computer.

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
Was this reproduced outside of zeta? because zeta ran into some storage issues lately, we are on it to prevent that kind of issues from happening again.

**Comment by Florexiz** [comment]
No idea actually. If nobody created this issue before - maybe only zeta related

**Comment by Glease** [comment]
Tagging as zeta only for now.
