### ISSUE TITLE
NEI lying on Silicon Dioxide + Carbon = .. and "2000L" of Carbon Monoxide

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#8822]
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Don't know

### Your Expectation

Well, as the recipe say 
![image](https://user-images.githubusercontent.com/76914762/141605661-9270b6b9-3a09-4ca0-96f2-c7d79c4eeded.png)
I was expecting 2 buckets of carbon monoxide

### The Reality

![image](https://user-images.githubusercontent.com/76914762/141605666-7c215738-d5b3-46e5-afab-f5e6aa8ee42d.png)
But it only gived me 0.1 bucket per iteration 

### Your Proposal

Fix the quantity it seems to be giving 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
You need maximum tier muffler to get the full amount of top gasses from EBF.

**Comment by POPlol333** [comment]
oh the gasses quantity come from the muffler quality? thanks for the information
