### ISSUE TITLE
Keyboard cannot be craftedin a PA

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#8824]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

2.1.1.4qf2

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Craft OC keyboard in a PA with an IV assembler
![image](https://user-images.githubusercontent.com/23512002/141609446-c4d112e7-162a-4928-b15d-c377af6aea9d.png)

### The Reality

It doesn't work

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
It does work in single block assembler, so maybe the fix with the multiple stacks of the same type should be somehow extened to the PA

**Comment by D-Cysteine** [comment]
Possibly related issue:
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8303

The bug above should only apply when input item stack sizes are not compacted, so the screenshot looks like it shouldn't be affected though. Maybe the PA checks recipe inputs in a slightly different way than the assembler? Or maybe the above bug is not related to this one.

**Comment by GlodBlock** [comment]
the detect order is inverted

**Comment by D-Cysteine** [comment]
Oh, so it iterates through backwards? Yeah that would mean that the bug I linked above might be the cause then. If you have this open, could you try with two stacks of 64 buttons and see if it works with that?

**Comment by Florexiz** [comment]
Just tested with 2 full stacks of buttons - recipe working

**Comment by D-Cysteine** [comment]
Okay, might be the linked bug then. I was thinking of going back and getting my fix for it ready for PR, so that would hopefully fix this issue then. One more check to confirm: does it work if the button stacks are size 40, 64 (i.e. reverse order of the screenshot in the first post)?

**Comment by Florexiz** [comment]
Yeah, with sorting disabled and reverse order recipe launched

**Comment by D-Cysteine** [comment]
Thanks for testing! Seems like we can confirm that it's due to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8303 then.

I'll clean up the fix I had for that bug and send it out for PR. Maybe I'll do some more profiling first.
