### ISSUE TITLE
Add larger railcraft tanks 

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8827]
### Your GTNH Discord Username

bombcar 💣 

### Your Pack Version

2.1.1.0

### Your Proposal

Add more railcraft tanks - sure supers are great but there’s nothing like the visual of a huge tank filled with benzene or whatever. 

### Your Goal

We can keep them balanced and they take a lot of space but they’re fun (space/material trade off)

### Your Vision

![](https://media.discordapp.net/attachments/181078474394566657/909114872820801626/unknown.png)

the “max size” is some numbers I calculated as possible values for larger tanks

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by redmage17** [comment]
I love this
