### ISSUE TITLE
Using NEI's automatic placement of recipe items will remove Infinity Booster card installation

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8828]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.1.0

### Your Server

private server

### Type of Server

Cruicible

### Your Expectation

Use NEI's automatic placement of recipe items.

### The Reality

A's installation has been removed. Sometimes this issue occurs, sometimes it doesn't.
video:https://youtu.be/HxTabOpVG8w

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
Do you have inventory tweaks installed? if yes try to reproduce this without it.

**Comment by yukieiji** [comment]
I tried uninstall the inventory tweaks, but it didn't fix this...
