### ISSUE TITLE
add support to ME interfaces for Holo Inventory

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8830]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Proposal

I want to suggest the addition of ME interfaces to Holo Inventory to see their content.

### Your Goal

When you build massive arrays of interfaces (i.e. molecular assembler arrays) you want to see the "fullness" of their pattern storage, so you don't have to lose time by opening each interface until you find free slots for your patterns. I am perfectly aware that the pattern terminal already exists, but that requires it to be linked to all the interfaces, which is, in certain cases, not possible yet.

### Your Vision

I think this would help people moving their patterns more easily when they are rebuilding their AE.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by DarkGaterau** [comment]
it's be awesome if add this

**Comment by repo-alt** [comment]
That may work on block interfaces but not on part interfaces because HoloGlasses can only work with something exposing IInventory

**Comment by repo-alt** [comment]
Actually, the mod is pretty primitive, so perhaps this limitation may be removed

**Comment by repo-alt** [comment]
Just wondering - _why_ interface terminal is worse for that? I myself practically never place patterns in the interfaces directly. The only scenario where I see that feature as useful is faster finding a full interface on some machine, to put pattern capacity card in it.

**Comment by boubou19** [comment]
There is also the case were you are mass moving patterns: space + click in an interface directly is way faster than moving one by one in the interface terminal. But i agree it's a niche case.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/142227466-003727a8-3219-40e5-9571-a2f393160ab7.png)
All patterns are rendered as, well, patterns.

**Comment by repo-alt** [comment]
Although, I think I can change that to real items. Not sure if that is actually good for looking for free slots though.

**Comment by boubou19** [comment]
To be honest it should be more than enough. If you render them as real items not sure if it won't impact the performances.

**Comment by repo-alt** [comment]
>> not sure if it won't impact the performances.

Compared to the big chests, I don't think so. The question is just what would be more useful

**Comment by DarkGaterau** [comment]
I think that's enough. the more that for interface cover

**Comment by boubou19** [comment]
> Compared to the big chests, I don't think so. The question is just what would be more useful

Well if you can make them render as pattern result outputs for no performance reduction, then it's good :D But don't bother if it's too hard to implement.
