### ISSUE TITLE
[RFC] New Assembler Recipes that don't have one but can be handcrafted.

### ISSUE THREAD

**Issue by xTwi** [GTNewHorizons/GT-New-Horizons-Modpack#8837]
### Your GTNH Discord Username

Neo-Twilight#6828

### Your Pack Version

dev

### Your Proposal

If there's a recipe you would like to be part of an Assembling Machine recipe, but is handcraftable only, please comment down below or attach pictures.

Please also specify if there are any adjustments you'd like made to the recipe.

### Your Goal

Implement this into the next dev release.

### Your Vision

If it can be handcrafted, it can be put into an assembler.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
The nukes are certainly one - though the output exchangers etc are not stackable but auto eject into chest solves that

**Comment by Steelux8** [comment]
Here's a list of recipes that *need* tools, and need an assembler recipe to save on those tools:
- Meteorite Compass
- ME Wireless Access Point
- Cell Workbench
- Vibration Chamber
- All of the Storage Cells
- ME Pattern Terminal

**Comment by bombcar** [comment]
Some more I found:

* Nuclear Control - At least the Advanced Information Panel, Industrial Information Panel, and yeah basically everything from that mod

**Comment by bombcar** [comment]
#5306 could also be fixed but probably not in assembler? maybe? somehow we have fifty billion assembler recipes for chests.

**Comment by MrJakobLaich** [comment]
Alright, first: Thanks for this, now I don't have to figure out how to add recipes myself
Second, list of recipes:
- Compass (1x magnetic iron rod, 1x glass pane, 2x iron ring ?)
- dispenser
- dropper
- cfb fridge (chest + normal iron plates ?)
- OpenBlocks elevator
- vanilla item frame
- ztone blocks? (not the ztone block but the ones that use the ztone block, azur, bitt, etc) I want cheaper azur :P
- same but with chisel blocks (factory block for example ?)
- pam's recipes? (I know, nobody likes food but we already have a slicing machine for GregTech sandwiches, why not automated jelly too?)
- note block
- vanilla redstone lamp
- flat lamp (ztones)
- (inverted) lamp (PR:Illumination)
- jukebox ? does anyone actually use that one ?
- vanilla activator track, detector track, booster track
- daylight sensor
- fishing rod
- firework rocket
- all other food stuff (for example pumpkin pie) (I KNOW that nobody likes food but I can't even automate the pies D: )
- flint and steel
- paintings ;)
- shear

If you want me to write down the recipes for each of the above just tell me and I'll activate my brain xD
(for example recipes for the chisel, ztones and food recipes, that would probably take some work off your hands :D )

Now that I know that this exists I'll add more when I find stuff that could get a recipe :D

**Comment by bombcar** [comment]
Note that the CFB kitchen effectively automated cooking on a human scale, if you will.

**Comment by MrJakobLaich** [comment]
> Note that the CFB kitchen effectively automated cooking on a human scale, if you will. 

True, forgot about that for a second but I still like the idea of having an assemblyline just for sandwiches 😁😉

**Comment by xTwi** [comment]
some thoughts on these two lists:

-foods = do you know just how many recipes that would be? i'm probably not even going to attempt that.
-meteorite compass = i'm pretty sure ae2 meteors were disabled.
-the chests = basically oredicted wood, for some reason, wood types added by some mods don't actually count as oredicted, or need to be added to oredict, but mods could be arr so i dont know.
-ztones = potentially a lot of recipes. haven't even looked into the mod.
everything else looks fairly doable.

**Comment by Steelux8** [comment]
I am somewhat interested in helping out with adding recipes myself, I've never done anything for GTNH and I know little of Java but this looks like a decent starting point for getting something done.

**Comment by MrJakobLaich** [comment]
> some thoughts on these two lists:
> 
> -foods = do you know just how many recipes that would be? i'm probably not even going to attempt that. -meteorite compass = i'm pretty sure ae2 meteors were disabled. -the chests = basically oredicted wood, for some reason, wood types added by some mods don't actually count as oredicted, or need to be added to oredict, but mods could be arr so i dont know. -ztones = potentially a lot of recipes. haven't even looked into the mod. everything else looks fairly doable.

- foods -> I know, it's not really that important, was just something I noticed while looking for stuff and I wanted to add it as a note
- ztones -> it wouldn't be that many recipes, we just need one for the block (azur for example) and the other variants can be chiseled anyways
That would be 33 ztones recipes for all cool blocks:
1. Agon (already made from glue in assembler)
2. Bitt (wool + 8x ztone)
3. Cray (aurora + 8x hardened clay)
4. Fort (aurora + 8x ztyl-9)
5. Iszm (aurora + 8x ztyl-8)
6. Jelt (gold ingot + 8x ztone)
7. Korp (obsidian + 8x ztone)
8. Kryp (soul sand + 8x ztone)
9. Lair (netherrack + 8x ztone)
10. Lave (ice + 8x ztone)
11. Mint (slimeball + 8x ztone)
12. Myst (aurora + 8x mushroom-block)
13. Reds (redstone + 8x ztone)
14. Roen (sandstone + 8x ztone)
15. Sols (blaze powder + 8x ztone)
16. Tank (iron ingot + 8x ztone)
17. Vect (ghast tear + 8x ztone)
18. Vena (ender pearl + 8x ztone)
19. Zech (aurora + 8x ztyl-4)
20. Zion (aurora + 8x ztyl-7)
21. Zome (aurora + 8x ztyl-6)
22. Zone (aurora + 8x ztyl-3)
23. Zorg (aurora + 8x ztyl-5)
24. Tinted Glass (aurora + 8x glass)
25. Reed (sugar canes + 8x ztone)
26. Sync (emerald + 8x ztone)
27. Zkul (aurora + 8x ztyl-10)
28. Azur (lapis + 8x ztone)
29. Zeta (aurora + 8x ztyl-13)
30. Zest (aurora + 8x ztyl-11)
31. Zoea (aurora + 8x ztyl-14)
32. Zane (aurora + 8x ztyl-12)
33. Zyth (aurora + 8x ztyl-15)
34. Ztyl (block of coal + block of iron + 7x ztone)

**Comment by bombcar** [comment]
#7968 - could be fun if you want to try your hand at making an entirely new recipe

**Comment by MrJakobLaich** [comment]
what do you mean?

**Comment by bombcar** [comment]
> what do you mean?

See #7968 - there's no recipe for purple drink at all.

**Comment by CharlieTuna8** [comment]
EnderIO machine chassis only have handcrafting options.

**Comment by bombcar** [comment]
If updating AE2 recipes be aware of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7847

**Comment by bombcar** [comment]
Various galacticraft items including Heavy Oxygen Tank (and the others) and various parts like the oxygen van, compressor, etc.

**Comment by MrJakobLaich** [comment]
> some thoughts on these two lists:
> 
> -foods = do you know just how many recipes that would be? i'm probably not even going to attempt that. -meteorite compass = i'm pretty sure ae2 meteors were disabled. -the chests = basically oredicted wood, for some reason, wood types added by some mods don't actually count as oredicted, or need to be added to oredict, but mods could be arr so i dont know. -ztones = potentially a lot of recipes. haven't even looked into the mod. everything else looks fairly doable.

Now that I've had some time to think about the food stuff:
In what format do you need the recipes so you can just copy paste them all in?
Because I could try to do the food recipes for you if you tell me in what format you need them ;)

**Comment by bombcar** [comment]
#8055

**Comment by MrJakobLaich** [comment]
Foresty worktable also doesn't have an assembler recipe

**Comment by bombcar** [comment]
Factory block

**Comment by MrJakobLaich** [comment]
> Factory block

all the chisel blocks from what I remember, probably only need to have recipes for the base block and (auto)chisel it into the chiseled versions

**Comment by bombcar** [comment]
> > Factory block
> 
> all the chisel blocks from what I remember, probably only need to have recipes for the base block and (auto)chisel it into the chiseled versions

correct, this is just one that stood out and is embarrassing, can't make a factory in a factory

**Comment by MrJakobLaich** [comment]
Agree :D

**Comment by Elisis** [comment]
SSP's Ender-Quantum Component
