### ISSUE TITLE
Dolly works on nuke chambers - they shouldn’t. 

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8838]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.1.1.0

### Your Proposal

The regular dolly will pick up a nuke chamber

### Your Goal

I had one in my hot bar and accidentally picked up a nuke chamber, spilling its contents. 

Luckily it was off and didn’t meltdown. 

### Your Vision

Dollies shouldn’t move nuke chambers. Moving molecular transformers is ok I guess. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ethryan** [comment]
This seems a tad bit dangerous to carry around on a Dolly

**Comment by bombcar** [comment]
> This seems a tad bit dangerous to carry around on a Dolly

It’s perfectly safe because everything falls out onto the floor 🤣
