### ISSUE TITLE
[RFC]Disable some unfinished/unused mulits of GT++

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#8843]
### Your Pack Version

2.1.1.0

### Your Proposal

there are some unfinished, uncraftable or some seldom-used mulits in gt++. they are going to be disabled.
list:
 - Tesla Tower
 - Advanced Assline
 - Industrial Sinter
 - Bedrock Miner
 - SH Steam Turbine
 - Large Steam Turbine
 - Large Elemental Duplicator
 - Fast Neutron Reactor
 - Large Naquadah Reactor
 - Mini Fusion
 - ~~Liquid Fluoride Thorium Reactor~~
 - ~~Generator Array~~
 - ~~Tree Farmer~~
 - ~~Fission Fuel Processing Unit~~
 - Solar Tower
 - Multi Fluid Tank

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by xTwi** [comment]
I'm pretty sure people use Fluid Nukes, which can produce SH Steam from the LHE for SH Steam Turbine, which also feeds a Large Steam Turbine.

**Comment by GlodBlock** [comment]
i think you may mistake HP Steam Turbine with SH Steam Turbine, and the large steam turbine is added gt5 itself. these turbines added by gt++ don't recipe

**Comment by draknyte1** [comment]
Tree farm works fine. 
Only disabled by request because it’s unbalanced. Just needs better output scaling that isn’t infinitely exponential. 

LFTR and FFPP work fine afaik?

Generator array also works fine, just had some weird quirks due to supported 5.07-5.09 + GTNH. Easily fixed.

**Comment by CrusaderFishes** [comment]
good news everyone，these wipes（maybe forever） need to be removed loooooooooong ago.  nnless alk will comes back and clean up the mess

**Comment by GlodBlock** [comment]
i even don't know how to build the LFTR and FFPP, the structure description is not very understandable. if you can provide me with the screenshot of them, i can keep them

**Comment by redmage17** [comment]
> 
> 
> i even don't know how to build the LFTR and FFPP, the structure description is not very understandable. if you can provide me with the screenshot of them, i can keep them

Not messed them much but they are older machines and they should work

**Comment by bombcar** [comment]
The three RTG power units (LV-HV) do not have recipes. They work, but they were never reciped and balanced. The fuel is very expensive.

**Comment by GlodBlock** [comment]
the hatch isn't what we are discussing here

**Comment by GlodBlock** [comment]
the generator array works fine and i can add it back
@draknyte1 i need you to tell me how to build the rest multis so i can keep them or i only can disable them

**Comment by Sphyix** [comment]
> Tree farm works fine. Only disabled by request because it’s unbalanced. Just needs better output scaling that isn’t infinitely exponential.

Tree farm works? How do you set it up?

**Comment by Steelux8** [comment]
> they are going to be disabled

Disabled, how? A lot of them are already unusable without cheats because they don't have recipes, is this a change to only leave in the multis that are functional, recipe or no?

**Comment by Sphyix** [comment]
I'll just say if there's a chance to have the tree farm working, please get it working.
Lag generated from eio/forestry tree farms on officials is pretty bad and it'd be really cool to have a multi

**Comment by GlodBlock** [comment]
> Disabled, how? A lot of them are already unusable without cheats because they don't have recipes, is this a change to only leave in the multis that are functional, recipe or no?

the 'disable' means these things won't exist anymore in game. now you still can get them in creative or see them in nei

> I'll just say if there's a chance to have the tree farm working, please get it working.
> Lag generated from eio/forestry tree farms on officials is pretty bad and it'd be really cool to have a multi
> Especially if it's already working and it just needs a bit of balancing

we can add such a multi in gt5 or core mod. gt++ will be removed in some day eventually

**Comment by Sphyix** [comment]
> > I'll just say if there's a chance to have the tree farm working, please get it working.
> > Lag generated from eio/forestry tree farms on officials is pretty bad and it'd be really cool to have a multi
> > Especially if it's already working and it just needs a bit of balancing
> 
> we can add such a multi in gt5 or core mod. gt++ will be removed in some day eventually

I expect it to be added on obama at some point if it exists on GT++, but I don't think it's coming anytime soon.
If it's not too much work, having the GT++ working for now would be cool.

**Comment by draknyte1** [comment]
> gt++ will be removed in some day eventually

In like a year. 

Tree farm has its logic disabled in code, someone just needs to scale the outputs better. But that involves math

**Comment by Steelux8** [comment]
I see little point in disabling GT++ multis without adding alternatives at the same time, with the argument that GT++ will be disabled eventually, given that there is still no progress on Obama in any of the dev versions.

**Comment by bombcar** [comment]
The Multis are already "dead" as in they cannot be used without creative mode anyway.

Perhaps the first step would just be hiding them in NEI

**Comment by GlodBlock** [comment]
what i listed are all wip or uncraftable multis in gt++, the only effect of removal is game loading speed will be cut down

**Comment by Steelux8** [comment]
Fair enough, I was just interested in a few of these multis even if they don't have a recipe. There's probably a way to bring them back after this, I'd wager.

**Comment by bombcar** [comment]
It’s always just code. If you dig in and/propose some tiering fixes for the wood thing maybe it could be resurrected or a equivalent added.
