### ISSUE TITLE
All "cover" recipes should have circuit

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8844]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

The covers such as Fluid Filter Cover, or Shutter Module Cover, all have assembler recipes without circuits.

This causes collisions as other recipes are migrated to assembler - they should all have a circuit.

### Your Goal

Prevent collisions, e.g. as being found by #8837 

### Your Vision

Where are the various covers defined? Perhaps it would be easy to find and add a circuit.

They all take two ingredients - perhaps circuit 2 is available? if not, maybe 20?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
No. I object.

**Comment by draknyte1** [comment]
It’s not. They conflict with recipes that are being added by people.

**Comment by Glease** [comment]
If that's the case.

**Comment by Elisis** [comment]
Anyway we don't close issues just because we feel like it

**Comment by bombcar** [comment]
I thought there was a general trend toward circuiting all the things - if that's not the case what do we do in case of a conflict?

**Comment by Elisis** [comment]
> I thought there was a general trend toward circuiting all the things - if that's not the case what do we do in case of a conflict?

Not necessarily all the things, but inevitably there do become conflicts just because the modpack grows so much. And we use circuits in that case

**Comment by draknyte1** [comment]
> And we use circuits in that case

Nope, Glease objects.

**Comment by bombcar** [comment]
Oh, because Java is object-oriented. I get it.

But for real - if we get a case where a new recipe with circuit conflicts, just PR it anyway? Assuming we can't dig out the other recipe?
