### ISSUE TITLE
Tooltips for multi blocks are either fixed (5x5x5) or require a "range" on all dimensions (5-5,1-18,5-5)

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8847]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Server

MMCC

### Type of Server

Thermos

### Your Expectation

The tooltip maker doesn't allow you to have a multi block that is only variable in one dimension so you get things like:

![image](https://user-images.githubusercontent.com/533931/141801715-9f4bade6-191b-43bf-9fa3-31c174f0c0e4.png)

Another known example is the YOTTA tank. The 3-3 or 5-5 is confusing to players.

### The Reality

Tooltip maker should allow (5,1-18,5) for descriptions.

### Your Proposal

Fix tooltip maker to work well. 

https://discord.com/channels/181078474394566657/522098956491030558/909814670821572608 has some discussion

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by D-Cysteine** [comment]
Hmm, what if we just move the numbers around a bit in the tooltip? Like, instead of `3-3x3-12x3-3`, what if we just put `3x3x3-3x12x3`? Or more precisely, instead of `A1-A2xB1-B2xC1-C2`, we'd have `A1xB1xC1-A2xB2xC2`?

**Comment by bombcar** [comment]
Transitive property! I like it.
