### ISSUE TITLE
Input Hatch Shutter/Machine Controller Disconnects Fluid Pipe/Does Not Reconnect

### ISSUE THREAD

**Issue by Arkanomen** [GTNewHorizons/GT-New-Horizons-Modpack#8848]
### Your GTNH Discord Username

Arkanomen

### Your Pack Version

 Stable -11-15-21 

### Your Server

SP

### Your Expectation

A system to control fluid input into an input hatch on an LCR was proposed in the discord. A fluid detection cover sits on the output hatch and connects to a machine controller on the input hatch. A red alloy redstone wire connects the detector to the controller. On the input hatch's input face, a shutter is affixed. The theory is that when the output hatch is full, the signal will close the shutter and not allow fluid input. This way the LCR doesn't operate if that operation will void output product. 

Detector set to  Inverted
Machine Controller set to Enable with Redstone
Shutter set to Open if Work Allowed.

**Should Be:**  When Output Hatch is full, no fluid enters the Input hatch

**Notes:**  When the shutter is in its "closed" state, you cannot connect a fluid pipe, similar to how a single block machine face will not allow things to connect to it.  When the shutter is in its "open" state  you can wrench the fluid pipe back and connect it.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/94399472/141844428-f05c62fb-d178-4ada-87e6-5b911d5a78f0.gif)

### The Reality

**Is :**   When Output Hatch is full, shutter disconnects fluid pipe connected to the input hatch. Clearing output hatch does not reconnect fluid pipe. 

### Your Proposal

Unclear how a shutter should operate w/r to a fluid pipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Would you be able to try having the pipe come in "straight"? I can't imagine that would change what it does ...

**Comment by Arkanomen** [comment]
> Would you be able to try having the pipe come in "straight"? I can't imagine that would change what it does ...

Okay, so I moved the pipe into a direct connection like you suggested. It actually worked but only for a moment, but not for long. If I do not disturb anything touching the multiblock or change the state of the setup  it breaks the connection.

**Comment by Arkanomen** [comment]
To add, this behavior does not apply when used directly on the pipe and functions correctly.
![image](https://user-images.githubusercontent.com/94399472/141867859-2a1daf4e-f2c3-4d49-8184-b22cfbe8b421.png)

**Comment by Evuflow** [comment]
I had this issue happening also. Although behaviour is inconsistent. I had an item pipe setup using this method, no problems with it staying connected. It only seems to be affecting fluid pipes.

**Comment by bombcar** [comment]
This is *possibly* related to the enet changes involving shutters ... but I don't know.
