### ISSUE TITLE
Circuit assembler shouldn’t use lead past LV or tin past mv

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8850]
### Your GTNH Discord Username

bombcar 

### Your Pack Version

2.1.1.0

### Your Proposal

There are tons of almost identical recipes in NEI for circuits compounded by lead and tin and solder for each one. 

### Your Goal

Remove lead above LV and remove tin above MV. 

Or at least hide them in NEI. 

### Your Vision

Reduce the number of recipes to reduce load time and NEI clutter 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by POPlol333** [comment]
Soldering alloy could be expensive until HV sometime, so I prefer let the tin until HV but I agree with the idea

**Comment by Sphyix** [comment]
Tin and Lead are already more expensive than soldering iron.
I don't see a reason why it shouldn't be allowed to use them past MV, especially considering how rare antimony is early game.
Antimony is found in high quantities on T2 planets, so removing lead and/or tin before that is just going to cause a lot of frustration when making chips before EV.

If they need/want to be removed, it should be done at EV or higher, but I don't think there's a valid reason for that

**Comment by bombcar** [comment]
If we remove lead for HV circuits and tin from IV+ we still would save a large number of recipes.
