### ISSUE TITLE
Add direct mixer recipes for all EIO alloys

### ISSUE THREAD

**Issue by ArtherCasan** [GTNewHorizons/GT-New-Horizons-Modpack#8851]
### Your GTNH Discord Username

ArtherSnow#6574

### Your Pack Version

2.1.1.4 qf2

### Your Proposal

Too many EIO alloys are used in future version.I suggest add direct mixer recipes for all EIO alloy.

### Your Goal

Like vivid alloy
We can use
* Redstone
* Silicon
* Coal
* Iron
* Silver
* Blacksteel
* EnderEye dust
* Chrome
to craft vivid alloy dust directly

### Your Vision

Make it pay more attention to material acquisition instead of recursive material craft

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GlodBlock** [comment]
that is going to be a lot of conflict recipes lol

**Comment by bombcar** [comment]
New mixer supports more slots doesn’t it?

**Comment by iouter** [comment]
no more input slots.

**Comment by Steelux8** [comment]
Not to mention, having to mix complicated alloys in steps makes more sense. Generally, throwing everything in the mix at once makes for low-quality alloys when done IRL.

**Comment by GlodBlock** [comment]
the real life alloy smelting is more similar to gt++'s ABS instead of mix the metal dusts in mixer. i think it will be better to add one step mixer recipe for these alloy

**Comment by ArtherCasan** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/230
Thank for your work
