### ISSUE TITLE
Add a way to make superheated steam from other (solid) fuels

### ISSUE THREAD

**Issue by Steelux8** [GTNewHorizons/GT-New-Horizons-Modpack#8855]
### Your GTNH Discord Username

Steelux#1934

### Your Pack Version

2.1.1.4 QF2

### Your Proposal

Enable superheated steam production from other kinds of fuels.

### Your Goal

Superheated steam is a good mechanic that is currently only involved in the Large Heat Exchanger, which only takes in hot coolant or lava.

### Your Vision

This existing mechanic could add more efficiency to other kinds of fuels if the player put in the effort to make a HP Steam Turbine. Even the more advanced Large Boilers only make normal steam, so it would be interesting to have a way to turn them into hot coolant, for example, to be used in the Large Heat Exchanger, or to change one of the boilers to produce superheated steam instead of normal steam.

This would also help the Tungstensteel Large Boiler stand out, when currently it produces little power for the expenses.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
I thought much of the point of the LHE was that it was the only way of getting SH steam...

**Comment by Steelux8** [comment]
After all this time, a new option to make hot coolant from other fuels could also happen. That way, the LHE would still be the only way to get SH steam.

**Comment by bombcar** [comment]
If the SHS is basically “nuke steam” maybe a magic powered or fueled device making it would be appropriate

**Comment by Steelux8** [comment]
![2021-11-17_01 24 19](https://user-images.githubusercontent.com/70096037/142092246-827c9a7b-29cc-4ba1-9009-17ad645b3636.png)

After a quick test in creative, it does appear that the SOFC mkII makes superheated steam out of gas fuels. As such, I don't see a reason why solid fuels, at least ones with high burn values, could not produce it as well.

**Comment by yukieiji** [comment]
I think Fuel value and Fuel efficiency are two different things.

**Comment by Steelux8** [comment]
As an update, I discovered that what I was asking for is actually possible, with the Deep Earth Heating Pump, which turns an HV amp into an equivalent of around two IV amps of power by heating up coolant fed into it. However, it's a really expensive LuV recipe with 2 stacks of IV pumps and 8 LuV field gens, so it's not really sustainable given that the main obstacle is the cost of building the multi, not the power input into it.

**Comment by bombcar** [comment]
That costing is equivalent to solars - I suspect it would run indefinitely?

**Comment by Steelux8** [comment]
It should run indefinitely, with a small energy input for the tier.
