### ISSUE TITLE
Various OpenComputer parts can be made outside of a cleanroom when they really shouldn't

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8857]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

![image](https://user-images.githubusercontent.com/533931/142210597-e4c229c9-747a-4632-bcd7-ea87da0d8162.png)

### Your Goal

Arguably this is one of the things that SHOULD require a cleanroom, lest the drive not work.

### Your Vision

Add a cleanroom requirement - shouldn't be an issue as anyone building it should already have a cleanroom or be using PAs.

Also that's a lot of memory - more than even the computer has. It should be reduced to one stick.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Memory also is outside of a cleanroom, probably other components are, too. Not exactly sure how early people start with OC.

**Comment by Dream-Master** [comment]
yes but a cleanroom isnt that hard to build.

**Comment by boubou19** [comment]
Well cleanroom is annoying for some recipes that have barely a link with cleanroom, while many OC components are made irl with a cleanroom. Looks a bit weird to me.

**Comment by bombcar** [comment]
I can start building an OC setup and note which ones "thematically" seem to require a cleanroom.

**Comment by bombcar** [comment]
* Microchip
