### ISSUE TITLE
Adept Thaumaturgy quests unlock out of order with enough tech progression

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#8862]
### Your GTNH Discord Username

Pao

### Your Pack Version

2.1.1.0

### Your Server

SP

### Your Expectation

Quest book progresses normally in the Adept Thaumaturgy 

### The Reality

In the Adept Thaumaturgy tab, the More Durable Screws quest unlocks if any of the 6 elemental rod quests are completed, or if the Titanium quest in HV is completed.  By doing HV quests before the Advanced Thaumaturgy quests, some of the quests are skipped, causing confusion for players doing Thaumcraft in the pack for the first time.  

![image](https://user-images.githubusercontent.com/9247381/142261082-e528fe57-23c5-4cbe-899b-849c0752e25a.png)

Looks like this is caused by the OR quest prerequisite.  

### Your Proposal

Ideally, make the quest require OR(Obsidian, Bone, Blazing, Icy, Reed, Quartz Rod) AND (Titanium).  

If it's not possible for BQ to handle a combined AND and OR prerequisite, then probably just remove the Titanium quest prerequisite from that quest.  

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I was wondering why that popped up when I made titanium screws to make drawers …
