### ISSUE TITLE
Rearrange laser engraver lens/wafer combos to make sense

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#8863]
### Your GTNH Discord Username

Pao

### Your Pack Version

2.1.1.4QF2

### Your Proposal

While looking through the laser engraver recipes and which lenses are used for which wafers, I noticed there were some weird combinations for the different tiers of doped wafers.  Here's what the current recipe combinations are, along with the quantity of wafer produced: 

| | Silicon | Glowstone | Naquadah | Europium | Americium |
| --- | --- | --- | --- | --- | --- |
| **Blue**  | -- | PIC (1) | PIC (4) | -- | QPIC (1) |
| **Cyan** | RAM (1) | RAM (4) | RAM (8) | SSoC (64) | -- |
| **Green**  | ULPIC (2) | ULPIC (8) | SSoC (16) | RAM (16) | RAM (32) |
| **Orange**  | SSoC (1) | SSoC (4) |ASoC (1) | NPIC (1) | NPIC (4) |
| **Red**  | ILC (1) | ILC (4) | ILC (8) | ASoC (2) | ASoC (4) |
| **White**  | CPU (1) | CPU (4) | CPU (8) | -- | -- |
| **Yellow**  | LPIC (1) | LPIC (4) | SoC (1) | SoC (4) | SoC (8) |

As you can see, RAM uses 2 different colors of lenses, SSoC uses 3 different, ASoC uses 2, etc.  Doesn't make much sense.  

### Your Goal

Rearranging these would make more sense for progression and automation.  Instead of changing the lens color for higher tiers of wafers used, they could be rearranged for simplicity.  Here's my proposal: 

| | Silicon | Glowstone | Naquadah | Europium | Americium |
| --- | --- | --- | --- | --- | --- |
| **Blue**  | -- | PIC (1) | PIC (4) | -- | QPIC (1) |
| **Cyan** | RAM (1) | RAM (4) | RAM (8) | RAM (16) | RAM (32) |
| **Green**  | ULPIC (2) | ULPIC (8) | ASoC (1) | ASoC (2) | ASoC (4) |
| **Orange**  | SSoC (1) | SSoC (4) | SSoC (16) | SSoC (64) | -- |
| **Red**  | ILC (1) | ILC (4) | ILC (8) | NPIC (1) | NPIC (4) |
| **White**  | CPU (1) | CPU (4) | CPU (8) | -- | -- |
| **Yellow**  | LPIC (1) | LPIC (4) | SoC (1) | SoC (4) | SoC (8) |

### Your Vision

Obviously this would mess with existing setups, but there's already plenty of that going on with other 2.1.2.0 changes.   This at least simplifies during progression (keep the same laser/lens setup, just increase the output quantity in the AE2 pattern when you drop in a new wafer) and makes it easier to keep track of what lens does what (orange always does SSOC, cyan always does RAM).  

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
Very much appreciated!
