### ISSUE TITLE
New Titanium & Steel & Stainless Steel processing lines

### ISSUE THREAD

**Issue by validHS** [GTNewHorizons/GT-New-Horizons-Modpack#8864]
### Your GTNH Discord Username

journalist12#2112

### Your Pack Version

2.1.1.0

### Your Proposal

Make new Titanium & Steel & Stainless Steel processing lines, similar to existing aluminum & naquadah.
Using advanced chemistry and more recipes.

### Your Goal

Those materials are too easy to get in huge amounts.

### Your Vision

It should be harder.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by validHS** [comment]
Please, suggest anything, cmon people

**Comment by yukieiji** [comment]
Isn't the first thing to present the processing line you have in mind?

**Comment by validHS** [comment]
> Isn't the first thing to present the processing line you have in mind?

No, I'm just suggesting

**Comment by GlodBlock** [comment]
![image](https://user-images.githubusercontent.com/60341015/142398728-13990bf1-46f0-4297-bbef-6324449320ec.png)
:pog:

**Comment by validHS** [comment]
> ![image](https://user-images.githubusercontent.com/60341015/142398728-13990bf1-46f0-4297-bbef-6324449320ec.png) :pog:

Please, keep it without offtop. Thanks. Any suggestions?

**Comment by iouter** [comment]
titanium has its line, steel need 4min or 6min in bricked blast furnace, stainless steel is a alloy.

**Comment by validHS** [comment]
> titanium has its line, steel need 4min or 6min in bricked blast furnace, stainless steel is a alloy.

Great, thank you.
What about adding some chemistry for stainless steel?
Steel itself is fine, but stainless should be adjusted.

**Comment by iouter** [comment]
> Great, thank you.
> What about adding some chemistry for stainless steel?
> Steel itself is fine, but stainless should be adjusted.

https://en.wikipedia.org/wiki/Stainless_steel
stainless steel is not a magic alloy.

**Comment by validHS** [comment]
Please stop placing kekw in discord under my messages. That is not fun.

**Comment by Impos913** [comment]
Stainless Steel doesn't require any chemistry in real life. You just melt the raw materials in an electric furnace and you have the alloy.

**Comment by validHS** [comment]
> > Great, thank you.
> > What about adding some chemistry for stainless steel?
> > Steel itself is fine, but stainless should be adjusted.
> 
> https://en.wikipedia.org/wiki/Stainless_steel stainless steel is not a magic alloy.

That's fine, but that is real life wikipedia page. For game - it should be nerfed to make processing harder.

**Comment by Impos913** [comment]
Go do your research and suggest the nerf.

**Comment by validHS** [comment]
> Go do your research and suggest the nerf.

Will do, but also would like to see other player suggestions.

**Comment by validHS** [comment]
I mean, I'm same as that gay nigger alkalus - I'm pure zero in development

**Comment by Impos913** [comment]
I knew it

**Comment by validHS** [comment]
But the main difference - I'm not being fucked in ass by other man. Fuck niggers, fuck gays

**Comment by Impos913** [comment]
You are that hater noob
