### ISSUE TITLE
Item Filter doesn't work poprerly with Universal Fluid Cell

### ISSUE THREAD

**Issue by SGrober** [GTNewHorizons/GT-New-Horizons-Modpack#8868]
### Your GTNH Discord Username

SGrober#9546

### Your Pack Version

2.1.1.0

### Your Server

Private server

### Your Expectation

I connect ME Interface and Output Hatch (LV) via Item Conduit with Item Filter attuned for Universal Fluid Cell (empty).
![image](https://user-images.githubusercontent.com/94621882/142430722-07ff2c7b-b837-41b5-9c11-f8c4975aeb18.png)
![image](https://user-images.githubusercontent.com/94621882/142430806-6d096d0a-247e-4e8b-b30a-e1bb17d8e923.png)
![image](https://user-images.githubusercontent.com/94621882/142431141-9678b55e-64dc-40c3-8ad1-a848e3c8b12d.png)
I expect Universal Fluid Cell come inside Output Hatch (LV).

### The Reality

Universal Fluid Cell (empty) is stuck in ME interface.
If I add a chest, Universal Fluid Cell is stored in it.
![image](https://user-images.githubusercontent.com/94621882/142432001-42be9eab-fafc-40e5-b007-f027b95811f7.png)
![image](https://user-images.githubusercontent.com/94621882/142439092-4db87c6d-cb18-4510-b312-4331520f93ff.png)
If I add another Cell from inventory. It go to Output Hatch (LV).

### Your Proposal

If I remove Item Filter, it work properly.
![image](https://user-images.githubusercontent.com/94621882/142435775-3e5c512b-8419-4c95-95f6-45fcfb4bf5bc.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
can't reproduce that

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
