### ISSUE TITLE
Cryolite doesn't spawn in TF in 2.1.1.4qf2

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8872]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.4qf2

### Your Server

self-hosted

### Type of Server

Single Player

### Your Expectation

Cryolite doesn't spawn.

### The Reality

It should

### Your Proposal

Fix it with this jar

[gregtech-5.09.38.05.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7564441/gregtech-5.09.38.05.jar.zip)

and using this config:

[WorldGeneration.cfg.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7564452/WorldGeneration.cfg.txt)

Replace your existing GregTech jar with the one here (unzip the zip file) and rename the config file to WorldGeneration.cfg and put it in config/gregtech/

Restart your game and find a *new* vein.
 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Closed, this is for reference

**Comment by PolkageistHS** [comment]
Also requires GT++ 1.7.11 or newer: http://jenkins.usrv.eu:8080/job/GTPP/59/
