### ISSUE TITLE
Name mold in Processing Array won't work with more than one itemstack in the input bus

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#8875]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.1.4 QF2

### Your Server

SSP

### Type of Server

Single Player

### Your Expectation

Try to rename items via Forming Press in a Processing Array. Expect to be able to input more than one item at a time and for the PA to subsequently process the items in the input bus

### The Reality

The PA will not process anything if there are two or more items in an input bus, not counting the name mold.
Example: Name mold + 1 iron ingot + 1 cobblestone = PA does not work.
Take out either iron ingot or cobblestone and the PA will rename the input item.
Also, if you have two stacks of the same items (e.g. one stack of 64 iron ingots and another stack of 2 iron ingots) the PA will not work either.

This is also independent if you have one forming press inside the PA or multiple forming presses

Automation via blocking mode on the interface is also not possible as the name mold inside the input bus sets the condition "Do not push crafting items if inventory contains items" to true

### Your Proposal

Allow the PA to process all items in the input bus.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
Don't know if it helps but I did some more testing:
1. The Name mold only has one use within GT according to NEI: make a copy of itself with an empty shape plate in a forming press
2. When using a blank name mold, i.e. one that has not been renamed in an Anvil, the behaviour is the same as described above.
3. Other recipes don't seem to be affected when using the forming press inside a PA. Tried two stacks of glass dust with a ball mold and received 100 glass tubes as intended. Also works fine with the AE2 Inscriber Presses, ordered 100 Logic Circuits and had no issues.

**Comment by GTNH-Afx237v7** [comment]
Guess the forming press was not meant to process more than one itemstack, as by design it has two slots - one for the actual item, one for the mold?
https://github.com/GTNewHorizons/GT5-Unofficial/blob/e6a9dd1221c2f822383000f7dbf4481e1f768b84/src/main/java/gregtech/common/GT_RecipeAdder.java#L1187 

But then again why does it work with a ball mold and not the name mold?
I could not find anything specific to the name mold with GT code...

**Comment by GTNH-Afx237v7** [comment]
There may also be something here (special class for forming press recipe, incl. the name mold):
https://github.com/GTNewHorizons/GT5-Unofficial/blob/e6a9dd1221c2f822383000f7dbf4481e1f768b84/src/main/java/gregtech/api/util/GT_Recipe.java#L1576

**Comment by repo-alt** [comment]
Indeed forming press recipe map expects 2 inputs one of which should be a mold/press.

**Comment by GTNH-Afx237v7** [comment]
Why though will it work fine with anything but the name mold? It is just not possible to have more than one itemstack in an input bus, otherwise the PA won't start...

**Comment by repo-alt** [comment]
It works if the mold is not in the first slot. GT_Recipe_Map_FormingPress just is not adapted to PA
![image](https://user-images.githubusercontent.com/23512002/143566737-2ea171a1-da6c-47d9-a998-4292bbf6c529.png)

**Comment by GTNH-Afx237v7** [comment]
I am dying inside right now... so the solution is to disable sorting mode in the input bus and simply not put the mold in the first slot. Plus you need to turn off sorting mode for ae2 to be able to insert items at all, though it would need to be checked again with the mold not being in the first slot...

**Comment by repo-alt** [comment]
Technically it should work fine if you put it in the last slot, and turn off sorting

**Comment by repo-alt** [comment]
(Or I can just fix the press recipe map)

**Comment by GTNH-Afx237v7** [comment]
Whatever you prefer - guess fixing the recipe map is more work but eventually less trouble for the player.

**Comment by GTNH-Afx237v7** [comment]
Can confirm this is now working fine (tested with 2.1.2.0 pre5).
