### ISSUE TITLE
Bauxite electrolizer recipie gives free cells

### ISSUE THREAD

**Issue by Evuflow** [GTNewHorizons/GT-New-Horizons-Modpack#8876]
### Your GTNH Discord Username

Evuflow#9718

### Your Pack Version

2.1.1.4QF2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Recipe should gives cells for free.

### The Reality

Recipie should require 10 empty cells instead of a circuit.

### Your Proposal

Recipie should require 10 empty cells instead of a circuit.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
Update to latest GT version - fixedindev.
