### ISSUE TITLE
Tinkers construct Slime parts recipes

### ISSUE THREAD

**Issue by Minepolz320** [GTNewHorizons/GT-New-Horizons-Modpack#8877]
### Your GTNH Discord Username

Minepolz320#9473

### Your Pack Version

2.1.1.0

### Your Server

Private Server

### Your Expectation

![image](https://user-images.githubusercontent.com/42765118/142612515-38e7cd79-7d2b-4c0c-a3d2-20c21c828122.png)
![image](https://user-images.githubusercontent.com/42765118/142612536-87a38923-dbce-4ca4-ab44-2cca4ece6cc2.png)

### The Reality

Looks like there is an error 
with slime tools

### Your Proposal

Change or delete an invalid recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Here: [Link](https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/6f77a6259ae5621d6f208585c219c19da03f42f5/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L1145)
It's supposed to give you the Pig Iron Version.
