### ISSUE TITLE
It would be nice for the circuit programmer to support biocircuits

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8878]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

The bartworks circuit programmer is useful, but it would be nice for it to also be able to reprogram biocircuits from gt++.

### Your Goal

I know gt++ is slated for removal, but perhaps this is a relatively easy change? If someone knows where to look I can take a crack at adding it.

### Your Vision

Ability to easily reprogram biocircuits until gt++ sunsets.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by draknyte1** [comment]
Bart explicitly didn’t want to add support. 

You will have to check the Container for it and allow them into the slot. Then check in the change code to make sure it outputs the right item.

**Comment by Glease** [comment]
Bart retired. That's all.

**Comment by GlodBlock** [comment]
🙏🏻 bart 🙏🏻

**Comment by bombcar** [comment]
I got bartworks to build so I will take a look at this

**Comment by draknyte1** [comment]
> Bart retired. That's all.

I was just saying why the support is missing, I then said how to fix it. :p

**Comment by Glease** [comment]
Not needed any more, given you can configure them with a right click now.
