### ISSUE TITLE
Add Netty Patcher to the pack

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8880]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Mod Name

NettyPatcher

### The Mod to Add

fixes that annoying vanilla crash when refreshing the multiplayer screen, or when loading it for the first time if you are very unlucky.
https://github.com/draknyte1/Netty-Patcher/releases/tag/Release_1

For the license, @draknyte1 said it was made to address #8757 
https://discord.com/channels/181078474394566657/603348502637969419/911329412178378842

### Your Reason

waiting for the pack to boot just to see it crash quickly after, or when the server reboots/crashes, just so you crash by going back on the multiplayer screen is no fun at all. Especially for potato computers

### Preliminary Investigation

I added the mod in my 2.1.1.0 instance, mod triggered the patching when i went on the multiplayer screen. Then i spent 5 mins hitting the refresh button as if my life was depending on it, nothing happened. So the mod works :D

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by draknyte1** [comment]
I can add a license to the repo after the weekend, but it was developed solely to flex on @boubou19 and fix the linked issue.

**Comment by Dream-Master** [comment]
I will add it when i can put it inside the GTNH organisation und link it to jenkins.

**Comment by bombcar** [comment]
> I can add a license to the repo after the weekend, but it was developed solely to flex on @boubou19 and fix the linked issue.

LICENSE: this may be used by anyone anywhere as long as it flexes on @boubou19
