### ISSUE TITLE
Reduce the amount of required Muffler Hatches on MBF

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8883]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.1.0

### Your Proposal

Change the muffler hatches to be a non-ticking block after MBF is built, or change the number of the required mufflers to build the multiblock to 1 or 9?.

### Your Goal

Avoid lag when too many MBFs are built.
Right now I have 16 MBFs.
(Off-ticket)
This amount of MBFs is because some endgame materials smelt time is ridicoulus, and as it is now, for some materials the overclock of the MBF is limited, at some point it consumes so much that it makes no sense to overclock more, but it makes more sense to spam machines. This is an issue that I'll probably cover on another ticket.
(End Off-ticket)
16 MBFs in my base means having a total of 2704 muffler hatches.
A single muffler average load is between 200 and 700, with a worst time of 700 to 1200 microseconds
This is 0.5 milliseconds of minimum average to 3.2 milliseconds of maximum worst of useless load.
This is load that is constant, multiblock on or off doesn't matter.

This example is just to highlight an issue that can occur on servers or on high end bases when there are multiple MBFs and it is lag that is totally avoidable as this amount of mufflers is not necessary. It's pure aesthetics of the multiblock, but it's too much load on the server to be justifiable in my opinion.
I'm not asking to make it mandatory only 1 muffler, but to be able to use only 1 to form the multiblock, and make the rest of them optional.

### Your Vision

Avoid MBFs useless lag.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
There is a recipe for a giant output hatch made from 64 hv hatches. 

Does a giant muffler made from 64 mufflers make sense?

**Comment by iouter** [comment]
after the blueprint, it might be possible to create a smaller but more complex, more beautiful MBF but not cuboid.

**Comment by bombcar** [comment]
Also is the pollution handling code in the muffler and not the multiblock? Shouldn’t it be once per multi and shut down when the MB has no pollution left?

**Comment by Sphyix** [comment]
> Also is the pollution handling code in the muffler and not the multiblock? Shouldn’t it be once per multi and shut down when the MB has no pollution left?

Didn't check code, just tested ingame.
I never played with pollution so I have no idea.


> There is a recipe for a giant output hatch made from 64 hv hatches.
> 
> Does a giant muffler made from 64 mufflers make sense? Or even more?

Right now MBF uses 169 mufflers. Using 1 giant could be good. It's a buff in case of high tier mufflers, so right number would be 3 giant, idk

**Comment by Glease** [comment]
Each muffler handles up to 10k pollution per tick, but I guess even MBFs don't pollute as much. On its own, muffler is as laggy as a machine casing.

**Comment by Sphyix** [comment]
> Each muffler handles up to 10k pollution per tick, but I guess even MBFs don't pollute as much. On its own, muffler is as laggy as a machine casing.

MBF is 102400 pollution/sec, 1 muffler would be enough

Yea, on its own muffler is not that laggy, but being forced to use 169 on every multi can add up quickly

**Comment by boubou19** [comment]
Bart told me once in VC that it was purely aesthetical to have 169 mufflers. He said 1 was more than enough for the pollution exhaust, but he wanted the multi to be difficult, hence that dumb amount of hatches.

**Comment by Sphyix** [comment]
I should add, putting down that many hatches is really annoying when building the multi aswell.
The whole multi can be built with a wand, then hatches must be placed 1 by 1 by hand

**Comment by ScriptedPiky** [comment]
Would it be possible, although very silly, to add "Mega Muffler Hatch <tiers>" to the multiblock? Like, it requires at least one in the middle, acts as if it were 169 mufflers and requires 169 of that muffler tier to be made, and is basically just a less laggier and less aesthetical solution for longer terms involving multiple MEBFs. Granted the Mega Mufflers would probably need to start at a high tier, both to avoid cost cheese and less IDs used for blocks.

**Comment by bombcar** [comment]
> Bart told me once in VC that it was purely aesthetical to have 169 mufflers. He said 1 was more than enough for the pollution exhaust, but he wanted the multi to be difficult, hence that dumb amount of hatches.

Isn’t mufflers pretty easy to make or does it need 169 at tier? LV mufflers would be cheap … and just annoying

**Comment by Steelux8** [comment]
Yeah, I don't see the mufflers adding to the challenge now that pollution is disabled, LV mufflers are all that's needed for any multi that requires them.

**Comment by bombcar** [comment]
Polly will be back though, so a change that would have to revert wouldn’t work. But if they’re only decorating then it can be reconsidered. 

Not like we haven’t had multiblocks built entirely out of maintenance hatches before

**Comment by draknyte1** [comment]
> Each muffler handles up to 10k pollution per tick, but I guess even MBFs don't pollute as much. On its own, muffler is as laggy as a machine casing.

From memory 1 || 100 mufflers won't change multi internal handling of 10k.

>Mufflers lag hurrdurr

Mufflers don't actually do shit, code wise.
They will render particles when active, but that's nothing. On a server this has no impact.
169 Mufflers won't impact overall performance of anything.

>16 MBFs in my base means having a total of 2704 muffler hatches.

This isn't the fault of mufflers, nor this multi. If you have processing bottlenecks, you need a better solution.

**Comment by boubou19** [comment]
> If you have processing bottlenecks, you need a better solution

I like this kind of answer given to someone at the very end of the game: the guy cannot do better lol

**Comment by Sphyix** [comment]
Since this is clearly confirmed only aesthetical, can the request be considered?


> Mufflers don't actually do shit, code wise. They will render particles when active, but that's nothing. On a server this has no impact. 169 Mufflers won't impact overall performance of anything.

Oh sorry alk, you clearly know better than the tricorder ingame.

**Comment by bombcar** [comment]
Can you warmroast it

**Comment by Sphyix** [comment]
> Can you warmroast it

I don't really know how to read warmroast reports, delta warmroast can be checked even now since my base was loaded after server restart.

I noticed a 4-5ms increment in my base after setting up 16 mbfs, 64 mvfs and the power transportation with active transformers.
Part of this load, after checking everything with the tricorder, seems to come from the mbf mufflers.
This is with all machines off.

**Comment by boubou19** [comment]
it is really hard to warmroast, as the lag get hidden by bigger sources of lag from GT and AE. I already checked and the code of the muffler hatch is dead simple, the only issue is the amount required that make it become an issue lag wise

**Comment by bombcar** [comment]
@boubou19 can you check delta? If it’s an issue we could make it take one or 169 I guess. 

Though if it’s just rendering time on the client not sure that would show on warmroast but might show on the tricorder

**Comment by boubou19** [comment]
i just told it was pure amount of them being an issue lagwise. the numbers pandoro gave on the opening message are from my observations in game. Because despite the world being almost empty we had abnormal amount of lag. By adding up all the muffler hatches tick time, we found out the missing part of the lag we couldn't identify

**Comment by bombcar** [comment]
So I made it so it can have one hatch, and it forms - but ....

```
        for (GT_MetaTileEntity_Hatch_Muffler e : this.mMufflerHatches)
            if (GT_MetaTileEntity_MultiBlockBase.isValidMetaTileEntity(e))
                mPollutionReduction = Math.max(e.calculatePollutionReduction(this.mPollution), mPollutionReduction);
```

It wouldn't do well, and that seems to iterate over all mufflers. 

https://github.com/GTNewHorizons/bartworks/blob/768c63bde49b22c58f97a53a8b9d25698a82460b/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java#L297

I can push what I have as a draft, but if we use it we'd need a "compressed muffler" or something that could cost/work equivalent to about 169 of that tier.

**Comment by Sphyix** [comment]
There is an issue with mufflers.
You need a giant for every tier since it changes the amount of pollution outputted from the multiblock

**Comment by GTNH-Colen** [comment]
> let make a new muffler simulate 64 muffler or so

MEBF has 13^2 so 169 mufflers, this is the amount that should be needed in an assembler recipe (with some soldering alloy I guess).

**Comment by Sphyix** [comment]
We can use 3 super mufflers, total would be 192 instead of 169.
Issue remains with the amount of pollution output for each muffler tier.
If I make the super muffler with LV, it needs to output 100% of the pollution, but if I make it with UHV mufflers, it needs to output 0%

**Comment by Dream-Master** [comment]
> We can use 3 super mufflers made by 64 mufflers each, total would be 192 instead of 169. Issue remains with the amount of pollution output for each muffler tier. If I make the super muffler with LV, it needs to output 100% of the pollution, but if I make it with UHV mufflers, it needs to output 0%

yes good idea. MAybe a super muffler is a tier or two higher then  his mufflers in base recipe

**Comment by Sphyix** [comment]
> yes good idea. MAybe a super muffler is a tier or two higher then his mufflers in base recipe

Not really a good idea, right now to avoid pollution i need 169 UHV mufflers, so I expect to need at least UHV mufflers to make the 0% super muffler.
Tiering should remain the same

**Comment by Dream-Master** [comment]
maybe they cleaning the air :P
