### ISSUE TITLE
NEI key for disassembly

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8886]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.1.1.0

### Your Proposal

Somethings like this:

![](https://media.discordapp.net/attachments/234936569360809996/911733447100342313/unknown.png)

can’t be arc furnaces (I think) because they’d provide too much materials. 

### Your Goal

Ability to press a key while hovering over the item in NEI to show if it could be disassembled

### Your Vision

Knowing it could be disassembled if it doesn’t work saves a round trip to creative when working out what certain things do. 

Rather than showing all disassembler recipes basically have a way of confirming it hasn’t been removed/blocked (eg turbines)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by D-Cysteine** [comment]
Maybe we should just enable NEI for the disassembler? Sure, it's full of a lot of junk, but probably most players would use it when looking up usages for an item, which should be manageable. There might be more than one recipe shown, but it's probably going to always be either the first or the last recipe shown that ends up being used.

It's literally as easy as changing the `false` to `true` at the end of this line:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/3e4bf6f97c246738768b1cc92f3fe8f98b8cbd4d/src/main/java/gregtech/api/util/GT_Recipe.java#L667
though we'd need to update NEI to display the new handler properly. Maybe we could also update the GT NEI handler to only show the correct disassembler recipe.

**Comment by bombcar** [comment]
If it loads against 2.1.1.0 or .4 I can try to estimate the additional load time (if any)

**Comment by D-Cysteine** [comment]
I think all of the work searching through the recipes is done when you invoke NEI on an item, so it shouldn't have any noticeable effect on loading time

**Comment by Glease** [comment]
Just register a usage handler without adding it to craftinghandlers list.

**Comment by Glease** [comment]
Also AFAIK bart intializes the recipe map lazily, meaning you'd see nothing in that map anyway. We'd probably need a new `TemplateRecipeHandler` for it.
