### ISSUE TITLE
cannot get GT "Aluminium" archivement

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#8887]
### Your GTNH Discord Username

NoXъ#0667

### Your Pack Version

1.7.10-2.1.1.0

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

I smelted aluminium ingot in EBF, but achievement did not count. I tried to re-place main EBF block to ensure I am it's owner, but it's not solved the issue. Also I tried to place a chest to output bus, but even in this case, the achievement wasn't counted.

### The Reality

![2021-11-21_11 38 51](https://user-images.githubusercontent.com/4730256/142750138-c92b8f6f-cf2a-4e91-8966-832798e2b522.png)

### Your Proposal

I suppose the problem can be in "new TecTech EBF nature", because in previous modpack version (1.7.10-2.1.0.0) the archivement was counted with no problem. Please fix so players can get this and following archivements.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Anyone know where achievements are stored in the code?

**Comment by Glease** [comment]
AFAIK it fires just fine on latest GT5u in dev. Maybe it's fixed already. Will check later.

**Comment by Dream-Master** [comment]
guess because we cahnge the alu cooking

**Comment by Glease** [comment]
Cannot reproduce on latest dev. Probably fixed.
