### ISSUE TITLE
Ignore disabled energy hatches when ticking multiblocks

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#8888]
### Your GTNH Discord Username

NoXъ\#0667

### Your Pack Version

1.7.10-2.1.1.0

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

To save fuel, I turned off 1 of 2 MV EBF energy hatches, start smelting and expect EBF to run at MV voltage, but...

### The Reality

EBF is started again at HV (same smelting time with same ingots smelted before) and also disabled hatch begin to consume energy as if nothing had happened!

### Your Proposal

In general, is it intended to disable energy hatches? BTW, it's happening not only with EBF - also, with pyrolyse oven!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
What do you mean by “disable”?

**Comment by NoX-programer** [comment]
I mean state after hit e.hatch with soft mallet.

**Comment by Glease** [comment]
This gonna be some hilarious way to sabotage your friend's base, but I guess it's fine.

**Comment by NoX-programer** [comment]
May be not, if add more info to hatch WAILA's info in such case, for example:
Status: \<red\>Disabled\</red\>
Or this suggestion is too cool and it will be cool to add such status everywhere for GT/GTPP.
