### ISSUE TITLE
Mods not affecting game

### ISSUE THREAD

**Issue by idkimanerd** [GTNewHorizons/GT-New-Horizons-Modpack#8889]
### Your GTNH Discord Username

Some Nerd With A Keyboard#4823

### Your Pack Version

2.1.1.5pre1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Mods to affect the game

### The Reality

Mods did not affect game
https://pastebin.com/6MsQPZvN latest.log

### Your Proposal

 Mods to affect game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Install forge somehow.

**Comment by idkimanerd** [comment]
*facepalm*
