### ISSUE TITLE
ME memory card may remember many settings

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#8890]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

2.1.1.4qf2

### Your Proposal

subj
- Shift right click on p2p adds it to the list
- Shift right click in the air removes currently selected setting from the list
- Shift scroll wheel changes currently selected setting and prints the name in the chat
- Perhaps a shapeless recipe to clear everything

### Your Goal

-

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
:D I asked for this like months ago - glad to see it’s considered

**Comment by repo-alt** [comment]
Well, I didn't think is is so serious until I saw a screeshot with a full inventory of cards :)

**Comment by repo-alt** [comment]
Ok, that idea was quickly buried as wat lees convenient than just a view cell filtering cards in a wireless terminal. New idea was:
```
Sampsa — Today at 1:15 PM
Something that might be feasible: Add right-click functionality (without a card) to P2P tunnels, that opens a terminal-esque GUI (just copy over the terminal GUI) with memory cards only, which you can then click to set that tunnel 
Could reuse most of the terminal code I think
```
