### ISSUE TITLE
EBF has a slot that should work with a circuit

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8895]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

The new TT interface has a slot: 
![image](https://user-images.githubusercontent.com/533931/142873762-01f5e540-af7d-415d-8520-0d98b987a277.png)

that looks like it should take a circuit. New player put a circuit there and wondered why EBF wasn't working.

### Your Goal

That slot should work with a circuit, it exists and is convenient.

### Your Vision

It makes sense that the circuit is in the controller. No need to disable them being in the input bus optionally.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ngar1** [comment]
If this usage is a must, you can't put more than one receipt (by putting cirquit in input bus) on one EBF.

**Comment by iouter** [comment]
tt gui don't exist in structure lib

**Comment by Glease** [comment]
No longer valid as EBF GUI is reverted back to its previous state in dev.
