### ISSUE TITLE
Increase vertical range of pollen collection from bees

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#8902]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.1.1.

### Your Server

myFTB

### Your Expectation

Try getting pollen of a coast sequoia by sieve with industrieal apiary. 

### The Reality

Put a sieve upgrade in it and no pollen occure.
![grafik](https://user-images.githubusercontent.com/7759876/142875764-1ac2854b-e5ca-42db-a2f6-840db98894d3.png)

Testing same on the level (in the air) were the tree has leaves, it work.
![grafik](https://user-images.githubusercontent.com/7759876/142876106-4d12fc5a-1012-4bf3-b515-0f630c7e9c83.png)

### Your Proposal

Sieve shall be usable also with high trees

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
It's likely a vanilla forestry limitation. I'd be rather skeptic at changing it. I don't want apiaries to check unnecessarily huge area for pollens.

**Comment by bombcar** [comment]
Is there a quest that can be updated?

**Comment by Ngar1** [comment]
a quest for gigant sequoia, were a pollen from coast sequoia would be helpfull.
