### ISSUE TITLE
Extreme server lag on world save

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8903]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Server

MMCC [GT]

### Type of Server

Thermos

### Your Expectation

We have extensive lag on save - 5-10 second spikes of zero TPS when writing out the world save.

We can reproduce this all the time, and we can run profilers against it or try other things if needed.

### The Reality

Here's what we've found so far:

![image](https://user-images.githubusercontent.com/533931/142887453-51321eee-200d-46ef-896c-fbd2974d22c6.png)

and

![image](https://user-images.githubusercontent.com/533931/142887499-836c8053-9bcd-42c0-baeb-df20933716a9.png)

### Your Proposal

Example warm roast here:
[gt_warmroast.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7582268/gt_warmroast.zip) (is there an easier way to combine the needed files)

We have an 80GB world save, perhaps there's something we can do to improve performance, maybe a dimension should be reset, maybe BQ is saving way too much each time instead of just minor stuff?
 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
More context for the thaumcraft stuff: 
![image](https://user-images.githubusercontent.com/533931/142888479-613d6e8a-20e4-438b-a352-f7ba2533dc27.png)

**Comment by bombcar** [comment]
https://static.moddedminecraft.club/paste-moaner%27s-monkcraft-quin-theotokos.txt dimension listing, maybe delete overworked is the way to go.

**Comment by bombcar** [comment]
`241M	betterquesting` is a bit high, is that a quest file for each player or ? I thought it was saved in playerdata ...

**Comment by bombcar** [comment]
```4.0K	LifeDatabase.json
120K	QuestingParties.json
332K	NameCache.json
852K	QuestProgress.json-bak
9.4M	QuestDatabase.json
62M	QuestProgress.json
169M	backup```

Is backup important?

```7.5M	pre-251
21M	3.0.320
32M	3.0.322
46M	3.0.334-GTNH
63M	3.0.337-GTNH```

**Comment by Glease** [comment]
These backups are created at world load if BQ version changed. They should not have a performance impact whatsoever.

**Comment by Glease** [comment]
BTW for the BQ save thing you might be using a very crappy disk. The `awaitDone()` is basically just waiting for writing the bytes into disk. There is honestly not a lot of stuff we can do here.

**Comment by boubou19** [comment]
we experience the same kind of lag, but because the officials are saved once every 60 mins, it's not that terrible.

**Comment by bombcar** [comment]
The disks are ssd but that doesn’t preclude them being crappy. Perhaps the filesystem takes long to sync

**Comment by RaVenInTheDark** [comment]
> BTW for the BQ save thing you might be using a very crappy disk. The `awaitDone()` is basically just waiting for writing the bytes into disk. There is honestly not a lot of stuff we can do here.

Disks aren't crappy, they shouldn't be the bottleneck at all. I will note that none of our other servers (even a second GTNH server) have this major savelag.

**Comment by Glease** [comment]
which suggest it simply have too much data to process.

and yes, BQ save everything in one go. Given you have a 62MB QuestProgress.json, it's probably the source of problem.

To be clear, the BQ api is pretty inefficient in terms of serialization. Data is copied and transformed between different in memory representations twice before actually written into disk (object -> NBT -> JSONElement -> bytes). My optimization got rid of one pass. To get rid of the other however requires very significant rewrite - which is probably not going to happen.

I might later try to find a way to just rewrite QuestProgress.json saving. It should require significantly less work while give enough boost to solve this specific problem.

**Comment by bombcar** [comment]
And it saves everything for all players who ever joined? I wonder if it could "retire" players somehow until they connected again...

**Comment by Gateswong** [comment]
I also found the lag spike happens during the following functions:

https://github.com/GTNewHorizons/GT5-Unofficial/blob/cfe0df76ab423d4dc9853d3ef5625ec2983f3523/src/main/java/gregtech/common/GT_Pollution.java#L401

https://github.com/GTNewHorizons/GT5-Unofficial/blob/cfe0df76ab423d4dc9853d3ef5625ec2983f3523/src/main/java/gregtech/common/GT_UndergroundOil.java#L175

During the lag, disk I/O is roughly 5MB/s. I tried to use ramdisk as well, it doesn't have too much improve either.
