### ISSUE TITLE
Allow gas selection in Mega Blast Furnace

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#8906]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.1.4 QF2

### Your Proposal

It seems that currently the Mega Blast Furnace will randomly select a gas to be used when smelting items.
Example: I have both Radon and Argon in my MBF, add Mysterious Crystal dust to the input bus, it will always use Argon instead of Radon.
I know that a preferred circuit can be selected via screwdriver on the controller (though that seems to be broken as well?), but the player has no control over what gas to be used.

### Your Goal

QoL for when you want to select what gas to use to reduce smelting time.

### Your Vision

Optimize smelting times (at least to a degree) for the player and not be upset about ~~time gates~~ smelting times.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
The code has to pick a gas *somehow* - is it going through input hatches in a specific order?

**Comment by GTNH-Afx237v7** [comment]
In my case the controller is facing north and the input hatch with Argon is preferred; it is far west relative to the face of the controller. The input hatch with Radon is also west of the controller but closer to it, therefore I assume the choice of input hatch is made from west to east.

**Comment by bombcar** [comment]
Would it be possible to try to prove that by temporarily disconnecting the gas lines, and moving the gases around?

Because the other option is it picks gasses in some "internal recipe" order.

**Comment by GTNH-Afx237v7** [comment]
Will check next time I have the game open.

**Comment by GTNH-Afx237v7** [comment]
Having swapped the inputs of Radon and Argon, the MBF is indeed preferring Argon over Radon, if both are present. Looking at the smelting recipes for Mysterious Crystal dust and the available gases, I assume the MBF will select the gas with the lowest meta-ID.
List of meta-IDs as follows:
Oganesson: 1058
Radon: 112
Xenon: 1057
Krypton: 800
Argon: 84
Neon: 1060
Helium: 86

Just tested again with both Radon and Helium present, and the MBF uses Helium (86) over Radon (112).

If a selection of a preferred gas were to be added, I suggest being able to set a priority of a fluid hatch, as I believe this will be easier to implement.

**Comment by kenken244** [comment]
I think this could be done by having a different circuit number for each gas used. That way you can only use the rarer gasses on more important smelts. Otherwise, a priority system would be ok

**Comment by bombcar** [comment]
#8475 is similar, would have to apply to the MEGA also
