### ISSUE TITLE
Wrong number of plates for T7 rocket quest (ID 2641)

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#8914]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.1.4 QF2

### Your Server

SSP

### Type of Server

Single Player

### Your Expectation

Craft the indicated amount of 71 Tier 7 rocket plates according to quest 2641. Expect amount of plates to be sufficient to craft the entire rocket.

### The Reality

After crafting the components (booster, fins etc), there are 8 plates missing to finish the T7 rocket.

### Your Proposal

Increase requested amount of T7 ingots and plates from 71 to 79. 
Also increase the  amount of neutronium bolts from 710 to 790 and the amount of compressed mysterious crystal plates from 852 to 948.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I can modify this - but are we sure there's not an expectation of reusing something?

**Comment by GTNH-Afx237v7** [comment]
Have not looked at the recycle recipe of the T6 rocket; can do that tomorrow.

**Comment by bombcar** [comment]
Recycling usually just gives you plates - but if it gives an intermediate step I can update the text on this quest to indicate that you may need more.

**Comment by Skiftcha** [comment]
i request changing it back to 1 plate without intermediate resources. just plate.
just state needed amount in quest text if someone need it
all this stuff is autocrafted. you do not need to hold all ingredients and plates to prove you can make rocket

**Comment by bombcar** [comment]
That is perhaps a better discussion - should the higher tier rockets just require you to hold the rocket? Is there a cheese/skip that can happen?

If we're abusing quests to serve as recipe checklists perhaps we should think about that.

**Comment by GTNH-Afx237v7** [comment]
T4 quest asks for 13 plates which is not enough.
T5 quest asks for 61 plates and this is the exact amount  for a T5 rocket.
T6 quest asks for 13 plates which is not enough.

It is somewhat inconsistent....

**Comment by bombcar** [comment]
> T4 quest asks for 13 plates which is not enough. T5 quest asks for 61 plates and this is the exact amount for a T5 rocket. T6 quest asks for 13 plates which is not enough.
> 
> It is somewhat inconsistent....

Can you give me the exact numbers for T4 and T6? I can modify the quest
