### ISSUE TITLE
OpenComputer: No native libraries support for aarch64 servers

### ISSUE THREAD

**Issue by ducanh2002123** [GTNewHorizons/GT-New-Horizons-Modpack#8915]
### Your GTNH Discord Username

Xx__THK__xX#1273

### Your Pack Version

2.1.1.0

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

The OpenComputer mod to not complain about a missing lib (Native Lua libraries are not available, computers will not be able to persist their state. They will reboot on chunk reloads.)

### The Reality

The OpenComputer mod complains about the missing library (Native Lua libraries are not available, computers will not be able to persist their state. They will reboot on chunk reloads.)
and of course, all computers start to reboot on chunk reload

### Your Proposal

Adding the native lib for aarch64 CPU in the OpenComputer mod, as instructed by this GitHub thread: https://github.com/MightyPirates/OpenComputers/issues/3466

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
We may be able to add the libs, but .... force loading one particular architecture may break others

**Comment by bombcar** [comment]
This is not as simple as "adding the libs" as the files don't exist in the repository - it's dynamically getting them somehow and building them into the resultant JAR file.

**Comment by bombcar** [comment]
I think it would be ... aarch64

I assume it's a linux?

**Comment by bombcar** [comment]
> This is not as simple as "adding the libs" as the files don't exist in the repository - it's dynamically getting them somehow and building them into the resultant JAR file.

eep found them I think ....

[OpenComputers-MC1.7.10-1.7.5.15-GTNH+87faadb97-universal.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7598500/OpenComputers-MC1.7.10-1.7.5.15-GTNH%2B87faadb97-universal.zip)

rename this to .jar and replace your existing (save it as a backup) and see if it works .... may only work against dev if there have been other changes to OC.

**Comment by bombcar** [comment]
The jar above has a typo, but this should be fixed soon, GTNewHorizons/OpenComputers#36 fixes

**Comment by bombcar** [comment]
http://jenkins.usrv.eu:8080/job/OpenComputers/lastSuccessfulBuild/artifact/build/libs/OpenComputers-MC1.7.10-1.7.5.15-GTNH.38-universal.jar should work for testing purposes

**Comment by ducanh2002123** [comment]
> We may be able to add the libs, but .... force loading one particular architecture may break others

Tbh, I think that adding the lib would fixes the issue already, the force load step might not be necessary at all, OC is smart enough right? And yeah, I get the pain of having something that’s not part of the original repo downloaded and merged..
