### ISSUE TITLE
Creeper Egg can power magical energy abosrbers

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8916]
### Your GTNH Discord Username

Maniifestantes

### Your Pack Version

2.1.1.4QF2

### Your Server

Zeta

### Your Expectation

You can use a creeper egg instead of a dragon egg to generate power for free.

### The Reality

![2021-11-24_17 51 56](https://user-images.githubusercontent.com/57275066/143311603-40e782ea-1632-4160-aa0e-011cf30fc799.png)
![2021-11-24_17 51 53](https://user-images.githubusercontent.com/57275066/143311606-b033ce56-2ecf-4b19-b902-96aefb862e9b.png)

### Your Proposal

keep it, it's a really good feature

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
What power do you get from it with the creeper egg?

**Comment by bombcar** [comment]
Looks like it’s 1 amp EV. Suggest we make 🐉 🥚 1 amp ev and creeper egg 1 amp HV. It’s a bit too easy to bounce around ross and grab some gens. 

Alternatively we remove grandmaster egg gens from the list of things that spawn on ross.
