### ISSUE TITLE
Enable gtnewhorizons.github.io for hosting crops.zip and friends

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8918]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.5pre

### Mod Name

crops.zip

### The Mod to Add

We can create GitHub pages and like https://bombcar.github.io/ (example) end up with a repository that we can add/update as necessary. I would propose /crops/ be one of the sub directories, and the main page could be some reference links, etc.

Other similar "calculators" could be added in the future if people want to code them.

### Your Reason

This isn't exactly a mod but I don't want to just create the GitHub pages without some discussion

### Preliminary Investigation

See https://bombcar.github.io/ - it works pretty well but could use some translation/addition - and having it in the repository makes it easy

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by bombcar** [comment]
Normally content like this would be on the wiki, but crops.zip has javascript and other things that make it not really wiki-able.

**Comment by boubou19** [comment]
gtnewhorizons.github.io is currently in a process of being revived, but as our new website (see http://boubou-19.fr:8080/gtnh_website/index.html for a preview) But i agree, on the long term, we might need to host some stuff on a "Misc" category.

**Comment by bombcar** [comment]
very nice and yes, someplace that's git-reachable that can handle things like crops.zip would be perfect

**Comment by bombcar** [comment]
https://github.com/GTNewHorizons/crop-breeding-simulator created to hold crops.zip (and accept updates/changes) which can be pushed to the GitHub pages when created.
