### ISSUE TITLE
harmonize branches on github

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8920]
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack: master
- [x] https://github.com/GTNewHorizons/NewHorizonsCoreMod: master
- [x] https://github.com/GTNewHorizons/Minetweaker-Gregtech-5-Addon: master
- [x] https://github.com/GTNewHorizons/AngerMod: master
- [x] https://github.com/GTNewHorizons/BlockLimiter: master
- [x] https://github.com/GTNewHorizons/Yamcl: master
- [x] https://github.com/GTNewHorizons/GalacticGregGT5: master
- [x] https://github.com/GTNewHorizons/GTSU: master
- [x] https://github.com/GTNewHorizons/GT5-Unofficial: master
- [x] https://github.com/GTNewHorizons/Nodal-Mechanics: master
- [x] https://github.com/GTNewHorizons/EnhancedLootBags: master
- [x] https://github.com/GTNewHorizons/TinkersConstruct: master
- [x] https://github.com/GTNewHorizons/OpenCC-3D-printer-models: master
- [x] https://github.com/GTNewHorizons/IguanaTweaksTConstruct: master
- [x] https://github.com/GTNewHorizons/ThaumicTinkerer: master
- [x] https://github.com/GTNewHorizons/CustomGTCapeHook-Cape-List: master
- [x] https://github.com/GTNewHorizons/NewHorizonsServerCore: master
- [x] https://github.com/GTNewHorizons/BloodMagic: master
- [x] https://github.com/GTNewHorizons/Draconic-Evolution: master
- [x] https://github.com/GTNewHorizons/ModTweaks: master
- [x] https://github.com/GTNewHorizons/Thaumic_Exploration: master
- [x] https://github.com/GTNewHorizons/RemoteIO: master
- [x] https://github.com/GTNewHorizons/Electro-Magic-Tools: master
- [x] https://github.com/GTNewHorizons/ArchitectureCraft: mc1.7
- [x] https://github.com/GTNewHorizons/AMDI: master
- [x] https://github.com/GTNewHorizons/AMDIForge: master
- [x] https://github.com/GTNewHorizons/BloodArsenal: master
- [x] https://github.com/GTNewHorizons/StorageDrawers: master
- [x] https://github.com/GTNewHorizons/EnderIO: master
- [x] https://github.com/GTNewHorizons/SpecialMobs: master
- [x] https://github.com/GTNewHorizons/Avaritia: master
- [x] https://github.com/GTNewHorizons/Universal-Singularities: master
- [x] https://github.com/GTNewHorizons/NewHorizonsTweaker: master
- [x] https://github.com/GTNewHorizons/Baubles: master
- [x] https://github.com/GTNewHorizons/TooMuchLoot: master
- [x] https://github.com/GTNewHorizons/Jabba: master
- [x] https://github.com/GTNewHorizons/WirelessCraftingTerminal: master
- [x] https://github.com/GTNewHorizons/DetravScannerMod: master
- [x] https://github.com/GTNewHorizons/Infernal-Mobs: master
- [x] https://github.com/GTNewHorizons/Galacticraft: master
- [x] https://github.com/GTNewHorizons/BetterQuesting: master
- [x] https://github.com/GTNewHorizons/StandardQuestingPack: master
- [x] https://github.com/GTNewHorizons/LavaMonsters: master
- [x] https://github.com/GTNewHorizons/AdventureBackpack2: master
- [x] https://github.com/GTNewHorizons/GTNH-GuideBook-i18n: master
- [x] https://github.com/GTNewHorizons/QuestBook: master
- [x] https://github.com/GTNewHorizons/Crops-plus-plus: master
- [x] https://github.com/GTNewHorizons/GTNEIOrePlugin: master
- [x] https://github.com/GTNewHorizons/ThaumicBases: master
- [x] https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial: master
- [x] https://github.com/GTNewHorizons/ThaumicHorizons: master
- [x] https://github.com/GTNewHorizons/CropLoadCore: master
- [x] https://github.com/GTNewHorizons/IFU: master
- [x] https://github.com/GTNewHorizons/ForestryMC: master
- [x] https://github.com/GTNewHorizons/Gadomancy: master
- [x] https://github.com/GTNewHorizons/WitchingGadgets: master
- [ ] https://github.com/GTNewHorizons/TravellersGear: GTNH
- [x] https://github.com/GTNewHorizons/ExtraCells2: master
- [x] https://github.com/GTNewHorizons/SGCraft: master
- [x] https://github.com/GTNewHorizons/HungerOverhaul: master
- [x] https://github.com/GTNewHorizons/GTNH-TC-Wands: master
- [x] https://github.com/GTNewHorizons/HoloInventory: master
- [ ] https://github.com/GTNewHorizons/RFExpansion: 1.7.10
- [x] https://github.com/GTNewHorizons/MagicBees: master
- [x] https://github.com/GTNewHorizons/ProjectRed: master
- [x] https://github.com/GTNewHorizons/AdvancedSystemsManager: master
- [x] https://github.com/GTNewHorizons/StevesAddons: master
- [x] https://github.com/GTNewHorizons/WailaHarvestability: master
- [x] https://github.com/GTNewHorizons/WAILAPlugins: master
- [x] https://github.com/GTNewHorizons/WarpTheory: master
- [x] https://github.com/GTNewHorizons/MyTown2-Client: master
- [x] https://github.com/GTNewHorizons/OpenComputers: master
- [x] https://github.com/GTNewHorizons/SpiceOfLife: master
- [x] https://github.com/GTNewHorizons/BloodyQuests: master
- [ ] https://github.com/GTNewHorizons/TickProfiler: 1.7.10
- [x] https://github.com/GTNewHorizons/NotEnoughItems: master
- [x] https://github.com/GTNewHorizons/OpenBlocks: master
- [x] https://github.com/GTNewHorizons/Super-TiC: master
- [x] https://github.com/GTNewHorizons/Steve-s-Factory-Manager: master
- [x] https://github.com/GTNewHorizons/TinkersMechworks: master
- [x] https://github.com/GTNewHorizons/WitcheryExtras: master
- [x] https://github.com/GTNewHorizons/WitcheryModifier: master
- [x] https://github.com/GTNewHorizons/Tainted-Magic: master
- [x] https://github.com/GTNewHorizons/Binnie: master
- [x] https://github.com/GTNewHorizons/SC2: master
- [x] https://github.com/GTNewHorizons/Hardcore-Ender-Expansion: master
- [x] https://github.com/GTNewHorizons/WirelessRedstone-CBE: master
- [x] https://github.com/GTNewHorizons/ForgePatcher: master
- [x] https://github.com/GTNewHorizons/FTB-Utilities: master
- [x] https://github.com/GTNewHorizons/FTB-Library: master
- [x] https://github.com/GTNewHorizons/twilightforest: master
- [x] https://github.com/GTNewHorizons/Battlegear2: master
- [x] https://github.com/GTNewHorizons/Chisel: master
- [x] https://github.com/GTNewHorizons/TCNEIAdditions: master
- [x] https://github.com/GTNewHorizons/EnderZoo: master
- [x] https://github.com/GTNewHorizons/Obama: master
- [x] https://github.com/GTNewHorizons/Hodgepodge: master
- [x] https://github.com/GTNewHorizons/SpongePoweredMixin: master
- [x] https://github.com/GTNewHorizons/NotEnoughThaumcraftTabs: master
- [x] https://github.com/GTNewHorizons/InGame-Info-XML: master
- [x] https://github.com/GTNewHorizons/ThaumicEnergistics: master
- [x] https://github.com/GTNewHorizons/BQ3-Thermos-patch: master
- [x] https://github.com/GTNewHorizons/SpongeMixins: master
- [ ] https://github.com/GTNewHorizons/Thermos: 1.7.10
- [x] https://github.com/GTNewHorizons/Natura: master
- [x] https://github.com/GTNewHorizons/OverloadedArmorBar: master
- [x] https://github.com/GTNewHorizons/ToroHealth: master
- [x] https://github.com/GTNewHorizons/waila: master
- [x] https://github.com/GTNewHorizons/DefaultWorldGenerator: master
- [x] https://github.com/GTNewHorizons/FastLeafDecay: master
- [x] https://github.com/GTNewHorizons/CraftTweaker: master
- [x] https://github.com/GTNewHorizons/AppleCore: master
- [x] https://github.com/GTNewHorizons/Irontanks: master
- [x] https://github.com/GTNewHorizons/harvestcraft: master
- [x] https://github.com/GTNewHorizons/ForestryAPI: master
- [x] https://github.com/GTNewHorizons/Realistic-World-Gen: master
- [x] https://github.com/GTNewHorizons/Roguelike-Dungeons: master
- [ ] https://github.com/GTNewHorizons/ASMHelper: 1.7.10
- [x] https://github.com/GTNewHorizons/BetterLoadingScreen: master
- [x] https://github.com/GTNewHorizons/GTNH-Soartex-Overrides: master
- [x] https://github.com/GTNewHorizons/MicdoodleCore: master
- [x] https://github.com/GTNewHorizons/Forgelin: master
- [x] https://github.com/GTNewHorizons/BugTorch: master
- [x] https://github.com/GTNewHorizons/CompactKineticGenerators: master
- [x] https://github.com/GTNewHorizons/SpecialAI: master
- [x] https://github.com/GTNewHorizons/ModMixins: master
- [x] https://github.com/GTNewHorizons/MyEssentials-Core: master
- [x] https://github.com/GTNewHorizons/MyPermissions: master
- [x] https://github.com/GTNewHorizons/MyTown2: master
- [x] https://github.com/GTNewHorizons/KekzTech: master
- [x] https://github.com/GTNewHorizons/Mods-Get-Gregged: master
- [x] https://github.com/GTNewHorizons/Botania: master
- [x] https://github.com/GTNewHorizons/Gregtania: master
- [x] https://github.com/GTNewHorizons/Galaxy-Space-GTNH: master
- [x] https://github.com/GTNewHorizons/bartworks: master
- [x] https://github.com/GTNewHorizons/Computronics: master
- [x] https://github.com/GTNewHorizons/NotEnoughProduction: master
- [x] https://github.com/GTNewHorizons/Forestry-Localization: master
- [x] https://github.com/GTNewHorizons/OCGlasses: master
- [x] https://github.com/GTNewHorizons/RecEx: master
- [x] https://github.com/GTNewHorizons/EnderStorage: master
- [x] https://github.com/GTNewHorizons/CookingForBlockheads: master
- [x] https://github.com/GTNewHorizons/Opis: master
- [x] https://github.com/GTNewHorizons/LogisticsPipes: master
- [ ] https://github.com/GTNewHorizons/Scripts: GTNH-Master
- [ ] https://github.com/GTNewHorizons/supersolarpanels: dev-1.7.10-1.4.1
- [x] https://github.com/GTNewHorizons/LootGames: master
- [x] https://github.com/GTNewHorizons/The-Aether-GTNH: master
- [x] https://github.com/GTNewHorizons/TinkersGregworks: master
- [x] https://github.com/GTNewHorizons/NEI-Integration: master
- [x] https://github.com/GTNewHorizons/MBPSPatcher: master
- [x] https://github.com/GTNewHorizons/Prism: master
- [x] https://github.com/GTNewHorizons/TC4Tweaks: master
- [x] https://github.com/GTNewHorizons/Botdustries: master
- [x] https://github.com/GTNewHorizons/TecTech: master
- [x] https://github.com/GTNewHorizons/ae2stuff: rv3
- [x] https://github.com/GTNewHorizons/CodeChickenLib: master
- [x] https://github.com/GTNewHorizons/TiC-Tooltips: master
- [x] https://github.com/GTNewHorizons/ForgeMultipart: master
- [x] https://github.com/GTNewHorizons/gendustry: master
- [x] https://github.com/GTNewHorizons/HydroEnergy: master
- [x] https://github.com/GTNewHorizons/WAWLA: master
- [x] https://github.com/GTNewHorizons/GoodGenerator: master
- [x] https://github.com/GTNewHorizons/FernFlowerLegacy: master
- [x] https://github.com/GTNewHorizons/FernFlower: master
- [x] https://github.com/GTNewHorizons/ForbiddenMagic: master
- [x] https://github.com/GTNewHorizons/GTplusplus: master
- [x] https://github.com/GTNewHorizons/Sanguimancy: master
- [x] https://github.com/GTNewHorizons/LittleTiles: master
- [x] https://github.com/GTNewHorizons/ForgeGradle: master
- [x] https://github.com/GTNewHorizons/BuildCraft: master
- [x] https://github.com/GTNewHorizons/BuildCraftCompat: master
- [x] https://github.com/GTNewHorizons/QmunityLib: master
- [x] https://github.com/GTNewHorizons/Hbm-s-Nuclear-Tech-GIT: master
- [x] https://github.com/GTNewHorizons/Avaritiaddons: master
- [x] https://github.com/GTNewHorizons/ZenScript: master
- [x] https://github.com/GTNewHorizons/AVRcore: master
- [x] https://github.com/GTNewHorizons/NotEnoughEnergistics: master
- [x] https://github.com/GTNewHorizons/FindIt: master
- [x] https://github.com/GTNewHorizons/inventory-tweaks: master
- [x] https://github.com/GTNewHorizons/ThaumcraftMobAspects: master
- [ ] https://github.com/GTNewHorizons/NetherPortalFix: mc1710
- [x] https://github.com/GTNewHorizons/RedstoneFlux-API: master
- [x] https://github.com/GTNewHorizons/bdlib: master
- [x] https://github.com/GTNewHorizons/neiaddons: master
- [ ] https://github.com/GTNewHorizons/Tinkers-Defense: 1.7.10
- [x] https://github.com/GTNewHorizons/nei-custom-diagram: master
- [x] https://github.com/GTNewHorizons/Railcraft: master
- [x] https://github.com/GTNewHorizons/ProjectBlue: master
- [x] https://github.com/GTNewHorizons/StructureLib: master
- [x] https://github.com/GTNewHorizons/oauth: master
- [x] https://github.com/GTNewHorizons/D3Log: master
- [x] https://github.com/GTNewHorizons/OpenModsLib: master
- [x] https://github.com/GTNewHorizons/thaumcraft-research-tweaks: master
- [x] https://github.com/GTNewHorizons/VisualProspecting: master
- [x] https://github.com/GTNewHorizons/Nuclear-Control: master
- [x] https://github.com/GTNewHorizons/TCNodeTracker: master
- [x] https://github.com/GTNewHorizons/Schematica: master
- [x] https://github.com/GTNewHorizons/EnderCore: master
- [x] https://github.com/GTNewHorizons/ironchest: master
- [x] https://github.com/GTNewHorizons/CodeChickenCore: master
- [ ] https://github.com/GTNewHorizons/RedstoneFlux-1.12-Legacy: 1.7.10
- [ ] https://github.com/GTNewHorizons/thaumcraft-api: 1.7.10
- [x] https://github.com/GTNewHorizons/Mantle: master
- [x] https://github.com/GTNewHorizons/CraftGuide: master
- [x] https://github.com/GTNewHorizons/LunatriusCore: master
- [x] https://github.com/GTNewHorizons/Netty-Patcher: master
- [x] https://github.com/GTNewHorizons/ExampleMod1.7.10: master
- [x] https://github.com/GTNewHorizons/Translocators: master
- [x] https://github.com/GTNewHorizons/StorageDrawers-BiomesOPlenty: master
- [x] https://github.com/GTNewHorizons/StorageDrawers-Erebus: master
- [x] https://github.com/GTNewHorizons/StorageDrawers-Forestry: master
- [x] https://github.com/GTNewHorizons/StorageDrawers-Misc: master
- [x] https://github.com/GTNewHorizons/StorageDrawers-Natura: master
- [x] https://github.com/GTNewHorizons/build-system-updater: master
- [x] https://github.com/GTNewHorizons/AsieLib: master
- [x] https://github.com/GTNewHorizons/CoFHCore: master
- [x] https://github.com/GTNewHorizons/CTMLib: master
- [x] https://github.com/GTNewHorizons/ModTweaker: master
- [x] https://github.com/GTNewHorizons/WanionLib: master

**Comment by SinTh0r4s** [comment]
Is this list exhaustive? Are all mods used in the pack that we can compile ourself in this list?

**Comment by bombcar** [comment]
It was exhaustive at the time created. New mods have been added
