### ISSUE TITLE
Conflict in recipe Sapphire dust

### ISSUE THREAD

**Issue by berta24** [GTNewHorizons/GT-New-Horizons-Modpack#8921]
### Your GTNH Discord Username

Berta24

### Your Pack Version

2.1.1.4Q-F2

### Your Server

Private Online Server

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://user-images.githubusercontent.com/25983005/143498417-506541fb-83d9-4119-a92d-1246495cdd16.png)
Sapphire dust (green or blue) + carbon and liquid nitrogen = 2 aluminium nitrade dust 

### The Reality

![alum](https://user-images.githubusercontent.com/25983005/143498436-a8360cf7-3d77-4a73-8319-e3bc07b40aad.png)
in reality only gives alumina

### Your Proposal

Add a circuit to the aluminium nitrade dust

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
so we need more slots in EBF

**Comment by Glease** [comment]
We can probably just change the aluminium nitride to use alumina instead.

**Comment by berta24** [comment]
cant you simply add circuit 1 for alumina and 11 for nitride? like every other recipe?

**Comment by berta24** [comment]
> 
Alumina can still use carbon in ebf to make aluminium so that's not a solution

**Comment by GlodBlock** [comment]
the aluminum nitrade is using coal dust now.
