### ISSUE TITLE
Fluix Bee wont show up in GenePool after sequencing

### ISSUE THREAD

**Issue by MoDAX78** [GTNewHorizons/GT-New-Horizons-Modpack#8923]
### Your Pack Version

2.1.0.0

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

i try to sequence the fluix species gene 3 times and it wont show up in gene pool 

### The Reality

nothing happens the species wont show up and i cant fill a serum array with this species

### Your Proposal

i have no idea...

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
can you try on latest (2.1.1.0) please?

**Comment by MoDAX78** [comment]
hi, ive tried this on 2.1.1.0 and got the same issue
