### ISSUE TITLE
BQ text issues

### ISSUE THREAD

**Issue by draknyte1** [GTNewHorizons/GT-New-Horizons-Modpack#8925]
### Your Pack Version

2.1.1.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

Text to appear correctly in BQ tooltips and quest descriptions.
![2021-11-26_16 25 48](https://user-images.githubusercontent.com/3060479/143609487-f226960b-1234-4a69-8e62-bad588e195d0.png)

### The Reality

When using SmoothFont and having text scaled > 0%, BQ breaks.
![2021-11-26_15 58 59](https://user-images.githubusercontent.com/3060479/143609525-78b97d33-31e2-4bdd-af12-56e565da42b8.png)

### Your Proposal

Investigate BQ using some kind of hardcoded text size, as every other GUI/Interface works as expected with scaled font. (30%)
https://www.curseforge.com/minecraft/mc-mods/smooth-font

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Possibly related to #8766
