### ISSUE TITLE
one shuriken blade cant be replaced

### ISSUE THREAD

**Issue by jesuseduardo90** [GTNewHorizons/GT-New-Horizons-Modpack#8926]
### Your GTNH Discord Username

jes_eduardo90#6931

### Your Pack Version

2.1.1.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Shurikens are made of 4 Shuriken blades, after that you can replaces the blades with other types but only 3 seems to be capable of changing it.

manly its seems that the toolforge only has 3 slots for swaping pieces and the shurikens are made of 4 same pieces.

### The Reality

I am suppons to be able to change every sigle blade of it.

### Your Proposal

fix it:v idunno if its possible its alittle complicate i guess (not enought programing knowledges:v)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
https://old.reddit.com/r/feedthebeast/comments/3sqejg/tc_shurikens_and_iguana_tweaks_part_replacement

> Yup, but iirc you need a Tinker Station for it since a tool forge doesn't have enough slots for all combinations.

**Comment by jesuseduardo90** [comment]
yeah i see that the "crafting station" can change any blade tks:v
