### ISSUE TITLE
Mega Distillation Tower doesn't output items

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#8928]
### Your GTNH Discord Username

Piky

### Your Pack Version

2.1.1.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Mega DT should output items in the output bus

### The Reality

It does not output items in the output bus

### Your Proposal

Not sure why the Bartworks multi doesn't output items but it sucks if you're trying to use the Fermented Biomass recipe or other recipes that output items.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Might have been fixed as a side effect of https://github.com/GTNewHorizons/bartworks/pull/51/. Needs more checking.
