### ISSUE TITLE
BQ: Updated saves and changed PC and now quests arent working

### ISSUE THREAD

**Issue by Penguibird** [GTNewHorizons/GT-New-Horizons-Modpack#8931]
### Your GTNH Discord Username

LoskotVojtech#3058

### Your Pack Version

2.1.1.4QF-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to complete any quest after moving save file to a new PC and updating.

### The Reality

Quest doesn't complete/update/take items from inventory.

Not even checkbox quests work.

### Your Proposal

Quests should work as expected

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
Do you own a minecraft premium account?

**Comment by Penguibird** [comment]
I have realized now that the issue is in the NameCache.json file. 
Notice duplicate uuids for Penguibird.
`{
  "nameCache:9": {
    "0:10": {
      "name:8": "Penguibrd",
      "isOP:1": 0,
      "uuid:8": "000a289b-a0c6-144c-43cc-6011ddbd4a5b"
    },
    "1:10": {
      "name:8": "Penguibird",
      "isOP:1": 0,
      "uuid:8": "84a38730-b1c1-09d9-5ad0-6704406e9fd2"
    },
    "2:10": {
      "name:8": "Penguibird",
      "isOP:1": 0,
      "uuid:8": "e660ae6d-de8d-4ec7-b9f0-a8e2a3a1566c"
    },
    "3:10": {
      "name:8": "Pengubird",
      "isOP:1": 0,
      "uuid:8": "120c7ee7-d7da-9f7a-9efe-71b3771e3416"
    }
  }
}`

Both ids appear in the QuestProgress. My hypothesis is that this is what is causing the bug.

**Comment by Penguibird** [comment]
> Do you own a minecraft premium account?

I'm playing in offline mode.

**Comment by Penguibird** [comment]
Okay I was correct. I think somewhere between the new PC and GTNH update my uuid changed and this caused two different uuids for my usernames, each with different progress in the questbook and BQ freaked out about it.

### How to fix
Find your betterquesting folder in your savefolder.
Back it up.
Open up the NameCache.json and QuestProgress.json located in betterquesting in your editor of choice.
You need to find the duplicates and replace the new one. The old one is gonna appear a lot more in QuestProgress.json
If, like me, you played a bit and generated some save progress for the new one you might have to delete all duplicate occurences from the QuestProgress.json.
