### ISSUE TITLE
It would be nice to list pump rates in ticks instead of seconds

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#8932]
### Your GTNH Discord Username

0lafe#3719

### Your Pack Version

2.1.1.4QF2

### Your Proposal

I would recommend switching the tooltip on pump parts from L/s to L/t. Imo L/s implies that the cycle time on them is per second, like how conveyors are displayed. Rather they seem to pull per tick, and the displayed value is their tick speed * 20. 

### Your Goal

Kind of confusing atm, their tooltip imo insinuates that they will only pull fluid every second, rather than every tick. 

### Your Vision

Would increase readability on them, and clear up their function a little imo

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
How about adding both to the tooltip?

**Comment by bombcar** [comment]
So this is strange. https://github.com/GTNewHorizons/GT5-Unofficial/blob/b011ea297d8d63afcb34824e5f7a5cce9422c2e5/src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java#L544 defines the tooltip, and https://github.com/GTNewHorizons/GT5-Unofficial/blob/b011ea297d8d63afcb34824e5f7a5cce9422c2e5/src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java#L560 defines the speed.

I can fix the tooltip, but I think those should be tied together more directly, otherwise the tooltip could just be utterly wrong.

**Comment by 0lafe** [comment]
> How about adding both to the tooltip?

thats not a bad idea. Maybe something like `HV Fluid pump, pumps 10L/t ( 200L/s )` ?

@bombcar that's interesting. It looks like `new GT_Cover_Pump(32)` defines the speed based on voltage tier? looking at the pump cover definitions, it somehow turns that voltage tier into a speed? I couldn't exactly find where it transforms that value, but if it's a fairly simple process I could see adding it to the tooltip. I'm also realizing the tooltip uses GT_Utility.formatNumbers(val) which I'm assuming does things like separating thousands, which leads me to believe that `PartCoverText` is what sets L/s at the end? Not sure where this is defined though so I'm not sure how to fix. Could see the updated line in the tooltip definition looking something like this?

`ItemList.Electric_Pump_LV.set(addItem(610, "Electric Pump (LV)", GT_Utility.formatNumbers(GT.VOLTAGE_ENUMS(1) * (pumpSpeedLogic)) + PartCoverText)`

 https://github.com/GTNewHorizons/GT5-Unofficial/blob/b011ea297d8d63afcb34824e5f7a5cce9422c2e5/src/main/java/gregtech/common/covers/GT_Cover_Pump.java
this I believe is what gets a L/s or L/t value from the voltage of the pump?

**Comment by bombcar** [comment]
I can push a temp fix, but yeah, this should be refactored. The speed is `tier voltage/L/t` heh - which in theory can be refactored out entirely.

There's also some adjustable one with ` L/sec (as Cover)/n Rightclick/Screwdriver-rightclick/Shift-screwdriver-rightclick/n to adjust the pump speed by 1/16/256 L/sec per click` which may be more problematic to adjust per tic

**Comment by bombcar** [comment]
![image](https://user-images.githubusercontent.com/533931/143901743-a0610859-020a-423d-b60d-d95b2710c1b0.png)

This does L/t only for now.

**Comment by bombcar** [comment]
![image](https://user-images.githubusercontent.com/533931/143909225-4a03d72e-07e5-4b0e-95d5-b7ff4ef18637.png)
