### ISSUE TITLE
GT Tanks and Chests give 10 mins of debuff no matter the tier of the tank/chest

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8934]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.5-pre2

### Your Proposal

![image](https://user-images.githubusercontent.com/12850933/143776217-e15f2e9e-79ce-4d83-a377-02d067bcbf3a.png)
![image](https://user-images.githubusercontent.com/12850933/143776240-2c5f7b22-8068-4d64-8be8-0f3e4d18260b.png)
![image](https://user-images.githubusercontent.com/12850933/143776293-63e10d5e-64cb-4a99-a9ef-5e0ed669690b.png)
![image](https://user-images.githubusercontent.com/12850933/143776404-7c9564f1-22ca-4020-ac74-dfc904a102b2.png)

I suggest to add a specific duration of the debuffs per tier of tank/chest 

### Your Goal

This makes no sense as it is right now.

### Your Vision

This will be less of a pain at lower tiers, otherwise no one will use that feature.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Milk removes but … in that case a “supertank” debuff with a tooltip would be appropriate. 

Honestly much more than a minute at st1 is too much, cells are easy.

**Comment by repo-alt** [comment]
Why not just have debuff while you carry it? Like, feels more logical.

**Comment by Dream-Master** [comment]
Yes but with a longer decay otherwise it is very op

**Comment by GlodBlock** [comment]
i think we can set the lasting time according to the amount of left liquid. the more is the tank holding the longer the debuff lasting

**Comment by bombcar** [comment]
I like that idea. If the tank (total tanks? Most full tank?) is less than <diamond buildcraft tank> no lasting debuff after you put it down, otherwise a lasting debuff that scales up to the ten minute max at … full supertank? Full supertank III? Much longer and people would just commit die.
