### ISSUE TITLE
Air intake hatch can't be stopped

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8936]
### Your GTNH Discord Username

Maniifestantes

### Your Pack Version

2.1.1.4QF2

### Your Server

Zeta

### Your Expectation

I want to stop my air intake hatch.

### The Reality

It keeps generating air even disabled
![2021-11-28_17 19 23](https://user-images.githubusercontent.com/57275066/143784542-f64f0987-f9e3-4e2a-964e-ca8ceb797d25.png)
![2021-11-28_17 19 19](https://user-images.githubusercontent.com/57275066/143784544-c657f404-c2d4-47f0-940b-43c10f51ae6b.png)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
While engaged, the air intake hatch does not feel pity or remorse or fear and it cannot be stopped unless killed.

**Comment by draknyte1** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/50.
