### ISSUE TITLE
let the input bus be placed on both sides of the assembly line again.

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#8940]
### Your GTNH Discord Username

iouter

### Your Pack Version

2.1.1.4

### Your Proposal

the input bus cannot be placed on both sides of the assembly line after the structurelib.

### Your Goal

let the input bus can be placed on both sides of the assembly line again.

### Your Vision

you can do this before, and can check the input bus without breaking sfm or other things.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
tooltip always said to place at the middle of the first layer of each slice an input bus (output bus for the last slice). The fact it was not properly checked before is a bug that got fixed with the structure lib rework.

**Comment by iouter** [comment]
anyway, it should be made convenient. i don't want break the sfm every time i check my automation settings (even need to remark these input buses). so the original is pretty good.
