### ISSUE TITLE
small tumbaga dust is missing recipes

### ISSUE THREAD

**Issue by MrJakobLaich** [GTNewHorizons/GT-New-Horizons-Modpack#8941]
### Your GTNH Discord Username

MrJakobLaich#6170

### Your Pack Version

2.1.1.0 (also apparently in current dev 29.11.2021)

### Your Server

On my Server and Singleplayer, everywhere I guess

### Your Expectation

I want to make one normal tumbaga dust from the small dust I get when making rods in the LV lathe.

### The Reality

Only this recipe exists so now I'm stuck with small tumbaga dust until I make a packager.

![image](https://user-images.githubusercontent.com/40965742/143806125-23f7e4eb-99a1-4ae0-b67f-de85240b2a95.png)

### Your Proposal

Add the recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Fixed in my latest PR alongside all the other related issues for tiny and small dusts.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GTplusplus/pull/50/commits/d415f96bcee9ad41042f02c4d6d6b954c51f2024
