### ISSUE TITLE
Make the prospector scanner work on the toxic everglades

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8944]
### Your GTNH Discord Username

Maniifestantes

### Your Pack Version

2.1.1.4QF2

### Your Proposal

The other players on zeta said the prospector scanner doesn't work, and alk said it's because it doesn't have a support, it would be nice to see where the ores there are.

### Your Goal

I have an interest in going to this dimension.

### Your Vision

I won't have much vision of the ores there.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Is this the MV scanner, the seismic, or the LuV?

**Comment by maniifestantes** [comment]
According to Cino, it's the LuV
