### ISSUE TITLE
Balancing GoodGenerators for GTNH

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8945]
### Your GTNH Discord Username

Maniifestantes

### Your Pack Version

2.1.1.4QF2

### Your Proposal

I'm not here to ask for changes or anything, i just wanted to say my experience with this new mod.

### Your Goal

I feel like it is unbalanced in some way. First off, this mod adds new generators, along with some other stuffs here and there like a new multiblock that can store stupidly high amounts of one type of liquid.
I just feel like it's a bit unbalanced yet (i know, that's why it's on dev). For example, we have new fuel powers like the dense uranium, which gives 2x more eu/t than the normal Uranium cell and lasts as much as the thorium cell. We also have the mox equivalent, the high density plutonium(HDP), which generates more energy the hotter the generator is. with this Mox setup that can generate up to 6k EU, i simply replaced the mox with tthe HDP, and itt made 42~46k (i don't remember the exact number). And it lasts twice as much as MOX.
![shot-2021-11-29_11-07-52](https://user-images.githubusercontent.com/57275066/143882431-32e00e64-9894-4dd7-b365-8656819e8f8f.png)
Now, onto the next generator, this one i'm actually using. The Large Essentia Generator (LEG). It's a really nice generator that can turn any type of essentia into EU, according to this table
![2021-11-29_11 09 52](https://user-images.githubusercontent.com/57275066/143882717-102abae7-de47-46b1-b289-4c4800fca6ec.png)
(Any unlisted aspect gives 8192 EU/essentia)

you can make it in HV with most parts being mv, some requiring HV components.
The controller
![2021-11-29_11 14 24](https://user-images.githubusercontent.com/57275066/143883477-d62da0ab-701a-4e29-997c-7b545c50ccb1.png)
The essentia input hatch( can store unlimited amounts of essentia) and the novice diffusion cell
![2021-11-29_11 15 21](https://user-images.githubusercontent.com/57275066/143883570-a5850598-069c-4a5e-af5d-abd82f0d78e5.png)

You can upgrade it twice to generate 2x and 5x more eu/essentia (ie auram generating 120000EU per essentia with the novice diffusion cell, 240000 with the adept diffusion cell, and 600000 with the master diffusion cell(recipes of each below)
novice diffusion cell shown above
adept diffusion cell (2x more eu)
![2021-11-29_11 16 38](https://user-images.githubusercontent.com/57275066/143883800-f40cc49b-34f8-49ad-aecb-089cb702b306.png)
The bottle neck of this cell is the platinum gear
mastter diffusion cell(5x more eu)
![2021-11-29_11 16 41](https://user-images.githubusercontent.com/57275066/143883859-30e81034-fda2-461d-b75e-264af15ddcbb.png)
The bottleneck of this cell is the iridium reinforced plate
you'll need 25 of these diffusion cells for the generator.
There are more generators like the hydro dam which you can make in late LV, which relies on turning water into pressurized water, and sending to the hydro dam, which will output EU and normal water; and another later in the game which i haven't reached far to talk about it sadly( Naquadah fuel refinery), along with the neutron activator, which seems to be a good way to generate lutetium from liquid thorium.
Now, onto some things i'd say it's... a bit too strong.
The recipes seem too cheap IMO, with the HDP's bottleneck being HSS-S. Also it was said you can now move super and quantum tanks like you move dollies, giving you three big debuffs for 10 minutes. But that can be easily circumvented, like using the talisman of remedium, or eating terra wart.

Well i guess that's it, maybe there were more stuff but i don't remember. Thanks for listening to my ted talk

### Your Vision

what i wrote above.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GlodBlock** [comment]
i have been reworking on the whole LEG system since a month ago, including making the essentia fuel value more reasonable, modifying related recipe, adding a more complex running condition/restriction and more side effects like flux to it. the currently version of LEG is still very *half completed*.
as to HDP/HDU fuel rod, i think i have nerfed it. The HDP rod only has 1/3 max output power of you just said and lasting less time. The HDU rod cost 6 times more uranium than normal uranium rod and returns fewer uranium after centrifuged, it should already been balanced.
anyway, thanks for you suggestions and i will try to finish the rework of LEG wthin this year.

**Comment by repo-alt** [comment]
Is there any information about hydro energy generator?

**Comment by bombcar** [comment]
Doesn't the dam just store energy @SinTh0r4s - so it's just a battery? If the hydro generator can get power from something other than stored energy it may need to be looked at.

**Comment by GlodBlock** [comment]
it can generate power when raining, and the ouput power is it is its area*1EU/t

**Comment by repo-alt** [comment]
@GlodBlock Essentia input hatch not working with ThE essentia provider or even export bus is a conscious decision, or just lack of interoperability?

**Comment by repo-alt** [comment]
Also what is the purpose of the usual input hatch in LEG?

**Comment by GlodBlock** [comment]
you need to lock the essentia hatch with essentia so it can accept ThE's stuff. as to the normal input hatch, they are unfinished parts of LEG which i am working on.

**Comment by repo-alt** [comment]
Lock with what?

**Comment by GlodBlock** [comment]
![image](https://user-images.githubusercontent.com/60341015/144026295-c7aee885-8d33-4152-9d38-9fe582f6f04f.png)
the essentia filter

**Comment by repo-alt** [comment]
doesn't work. Tried jars or phials

**Comment by repo-alt** [comment]
Oh, provider works, export bus doesn't. That's ok I guess.
