### ISSUE TITLE
Drops from mobs are not the same (player kills v.s. Spike/KillerJoe)

### ISSUE THREAD

**Issue by KaffyCat** [GTNewHorizons/GT-New-Horizons-Modpack#8949]
### Your GTNH Discord Username

KaffyCat#3873

### Your Pack Version

2.1.1.0

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

I randomly killed some redcap from twilight forest (with my tinkers' construct weapon, no lucky enchantment), and somehow they dropped Ga and some vis shards, so I wonder if I can put it into the powered spawner, so I can have certain amount of these kinds of stuff.

### The Reality

I used enchanted spike from Extra Utilities and Killer Joe. None of them were working, the redcap only dropped something normal, like "Coal+ damaged iron gear/tools". I wonder if this is the problem of drop rate, so I enchanted the sword and the spike to get looting X. But unfortunately, still, nothing changes.

### Your Proposal

I don't know if this is intentional, if yes, please do tell me, there are different drops from manual killing and auto-killing, so I don't need to bother things like this anymore. If no, please tell me, is there any other mobs would have such circumstances or just mobs from twilight forest. Since I want to find another mobs to have same drops as player's kills, which will make my mobs farming tower  theoretically work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can you confirm this happens in Single Player (not Open To LAN)? Open to LAN has all sorts of fun impossible to fix errors.

**Comment by boubou19** [comment]
there are some mob loot categories if i remember right:
- Permanent loots
- Chance based loots
- Player only loots

Diamond spikes from ExU should drop player only loots. And i know for sure that Dream added player only loots to TF mobs to help the player a bit during early game.

**Comment by KaffyCat** [comment]
> Can you confirm this happens in Single Player (not Open To LAN)? Open to LAN has all sorts of fun impossible to fix errors.

Actually I am using private server (was LAN version before)

**Comment by KaffyCat** [comment]
> there are some mob loot categories if i remember right:
> 
> * Permanent loots
> * Chance based loots
> * Player only loots
> 
> Diamond spikes from ExU should drop player only loots. And i know for sure that Dream added player only loots to TF mobs to help the player a bit during early game.

Is it the same as the drops from Killer Joe?

**Comment by boubou19** [comment]
i don't know what loottables the kiler joe is looking into so i can't say

**Comment by KaffyCat** [comment]
> i don't know what loottables the kiler joe is looking into so i can't say

oh, so perhaps the things I saw were chance based loots

**Comment by boubou19** [comment]
Gallium is definitely player based, or no one would have gallium shortage

**Comment by KaffyCat** [comment]
well, this is quite frustrating. I wasted half day to test this thing T_T

**Comment by bombcar** [comment]
But does "player based" mean not on diamond spikes even though they say "as player"?

If so quest/tooltip needs update.

**Comment by draknyte1** [comment]
Some things intentionally check for fake players.

**Comment by KaffyCat** [comment]
> But does "player based" mean not on diamond spikes even though they say "as player"?
> 
> If so quest/tooltip needs update.

indeed, I was told to use Killer Joe,'coz it's said to be "as player", and then I worked all these things out, still didn't get what I expect.

**Comment by draknyte1** [comment]
> > But does "player based" mean not on diamond spikes even though they say "as player"?
> > If so quest/tooltip needs update.
> 
> indeed, I was told to use Killer Joe,'coz it's said to be "as player", and then I worked all these things out, still didn't get what I expect.

KJ and Diamond spike have a fake player attached and will drop player loot as intended, so long as things don’t check for fake players. 

Normal spikes work like a cactus iirc and just so damage, so they don’t trigger player loot at all. 

The quest isn’t wrong.

**Comment by bombcar** [comment]
So to be more precise, the Diamond Spike quest says it will drop *xp* but not necessarily anything about items.

Given mob farms in general being a bit laggy, perhaps text should be added to that and Killer Joe hinting that they may not get the exact same loot table?

**Comment by Cata-bre** [comment]
How did you enchant with Looting X? I cannot get enchantments above the vanilla levels to apply.

**Comment by boubou19** [comment]
go in NEI cheat mode, press X to open the enchant menu, then select looting X

**Comment by Cata-bre** [comment]
Ah, so there is no legitimate in-pack way to go past the Vanilla maximum (excepting the Overchanting table)?

**Comment by bombcar** [comment]
There are some ways InGame, ask in discord, but whether they're legitimate or not is ....

**Comment by Gateswong** [comment]
So what is the conclusion here? I'm seeing the topic changed to how to get a looting X enchant and the ticket was closed without get solved or further discussion.

---

I do observed some mobs have loots from "real player" but not from "fake player" (diamond spike for example).

A good example are some twilight forest mobs only gives some item if you are killing them, but not giving loot if killed by diamond spikes.

* Goblin: aluminium ingots/dust, Asenic dusts
* Sticky Beetles: Congealed purple/blue slime ...
* Redcap: Thaumcraft shards (Aer, Earth, Aqua, Ignite, Order, Entophy)

**Comment by boubou19** [comment]
all the tf mobs have custom loots added by the mod custom loots. It's intended that those loots aren't automatable because it would cause some balance issues with mob farms. Dream added those loots to give a little boost to tho who explore the tf early game.

**Comment by MuXiu1997** [comment]
But there are still ways to automate

**Comment by morganwf00** [comment]
> But there are still ways to automate

And what ways are those?
