### ISSUE TITLE
Hydroenergy introduces GL error

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8954]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.5pre2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I should live my life happily without OpenGL errors

### The Reality

If I have hydro energy mod enabled I see very frequently in the logs:

```
[10:38:39] [Client thread/ERROR]: ########## GL ERROR ##########
[10:38:39] [Client thread/ERROR]: @ Post render
[10:38:39] [Client thread/ERROR]: 1282: Invalid operation
```

The frequency goes absolutely insane if I pull up the menu (the one with "Back to Game").

It also chatspams with a similar error if Optifine is enabled.

```
[CHAT] §eOpenGL Error§f: 1282 (Invalid operation)
```

If I disable it - it goes away. Optfine enabled or disabled, D6 or E7, has no effect on this.

I am on a Mac with GraalVM.

```
Java is version 1.8.0_282, using 64-bit architecture, from GraalVM Community.

Java Arguments:
[-d64, -XX:+DisableExplicitGC, -XX:+UseConcMarkSweepGC, -XX:MaxGCPauseMillis=120, -XX:+UseStringDeduplication, -XX:+UseCompressedOops, -XX:+UseCodeCacheFlushing, -XX:ParallelGCThreads=4, -Xdock:icon=icon.png, -Xdock:name="MultiMC: dev gtnh 2.1.1.5pre", -Xms6144m, -Xmx6144m, -Duser.language=en]
```

I also get a bunch of 

```
[11:23:09] [Client thread/WARN] [FML]: A mod has attempted to assign Block com.sinthoras.hydroenergy.blocks.HEWaterStill@6783da89 to the Fluid 'water' but this Fluid has already been linked to the Block cofh.asmhooks.block.BlockWater@7323dce7. You may have duplicate Fluid Blocks as a result. It *may* be possible to configure your mods to avoid this.
```

but those seem unrelated and harmless.

### Your Proposal

Fix the error or suppress it if harmless.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dan-Ross** [comment]
Another user with the same issues here, seems to be Optifine related, same java version and on MacOS as well.

**Comment by bombcar** [comment]
Try this custom JAR http://jenkins.usrv.eu:8080/job/HydroEnergy/lastSuccessfulBuild/artifact/build/libs/hydroenergy-1.7.10-1.0.8-7-gf0a8cf3.jar 

```
    # [CLIENT] Activate this to disable the OpenGL 3.2 check; it will assume you have OpenGL 3.2 or greater. But be warned: it may crash! Some Macs may always report 2.1.
    B:forceOpenGL=false
```

You'll want to add that to the config with it set to `true` (after running once that should appear in the config file, just change it to true).

Let us know if that 1. fixes the issue 2. if you use the dam, does it render correctly.

**Comment by Dan-Ross** [comment]
getting a 404 back on that URL at the moment.

**Comment by bombcar** [comment]
Ah it rebuilt : http://jenkins.usrv.eu:8080/job/HydroEnergy/lastSuccessfulBuild/artifact/build/libs/hydroenergy-1.7.10-1.0.8-8-gb133e17.jar

**Comment by Dan-Ross** [comment]
That seems to have slain the GL error on my end, no longer having it flood chat. We're not far enough along to have dams setup yet, but I'll report back when we get there. 

Thanks @bombcar!
