### ISSUE TITLE
PSS can display negative values

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8961]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Server

MMCC

### Type of Server

Thermos

### Your Expectation

PSS shouldn't flicker negative

### The Reality

It does

![image](https://user-images.githubusercontent.com/533931/143952514-f7454f6a-d582-4743-b6c9-aff5f6f6c6b4.png)

### Your Proposal

Fix, possibly the same as https://github.com/GTNewHorizons/GT5-Unofficial/pull/705 can be applied to this display, too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Already fixed as part of https://github.com/GTNewHorizons/GT5-Unofficial/pull/706.
