### ISSUE TITLE
EnderIO conduit puts in output slot

### ISSUE THREAD

**Issue by raptorggi** [GTNewHorizons/GT-New-Horizons-Modpack#8962]
### Your GTNH Discord Username

raptorggi#0491

### Your Pack Version

2.1.1.4QF

### Your Server

private server

### Type of Server

Vanilla Forge and solo creative

### Your Expectation

EnderIO item conduit  does not place cells in output slot.

### The Reality

EnderIO item conduit placed cells in output slot.
![Screenshot from 2021-11-30 21-50-54](https://user-images.githubusercontent.com/6436615/144042399-f3ddc04e-e1e0-4f90-a4e0-a12201da1bf7.png)
![Screenshot from 2021-11-30 21-50-02](https://user-images.githubusercontent.com/6436615/144042412-0c55db24-6155-488b-a797-901e160bdb91.png)
![Screenshot from 2021-11-30 21-49-38](https://user-images.githubusercontent.com/6436615/144042431-f4997970-b89a-4b58-b36c-ea7d380ca9de.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Can you replicate the issue using other logistic options, e.g. GT pipes, hoppers?

**Comment by raptorggi** [comment]
Can repeat this with hoppe
![Screenshot from 2021-11-30 22-19-54](https://user-images.githubusercontent.com/6436615/144046381-e46dbe99-1bdd-4699-a38d-3d2530869467.png)
r
