### ISSUE TITLE
Rubber sheet gives more glue in smeltry than rubber ingot

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8963]
### Your GTNH Discord Username

bombcar 

### Your Pack Version

2.1.1.0

### Your Server

mMCC

### Type of Server

Thermos

### Your Expectation

Melt rubber sheet giving same as rubber ingot in smeltry. 

### The Reality

Sheet gives 288 glue, ingot 144. 

### Your Proposal

Both should be 144. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Confirmed happens in 2.1.1.5pre2

**Comment by Glease** [comment]
Not sure if this is intentional. At steam age every rubber sheet is worth 2 rubber bar due to stupidness of alloy smelter. It does get back to 1 later though

**Comment by bombcar** [comment]
It's not a dupe as you can't loop around, @Dream-Master - confirm it's intentional?

**Comment by Dream-Master** [comment]
we could change that to avoid issues

**Comment by Meegooo** [comment]
To add, is Refined Glue <-> Glue supposed to have ratio of 1:2? Looking at distillery recipe, when distilling glue to refined glue, the output is halved, which makes sense looking at other recipes. 

But you can convert it via fluid solidifier, fluid extractor and glue balls in ratio of 1:1. Two TiC glue balls are 288L of glue, converted into one glue "ball" from Electro-Magic tools, which melts to 288L of refined glue.

Combined with the original issue, you can convert rubber bars into refined glue in ratio of 1:4, which is a bit too much.

**Comment by riking** [comment]
The first half of that @Meegooo is definitely intentional - it's signifying that the "glue refining" process is lossy. There's no dupe because you're straight up losing material.
