### ISSUE TITLE
Making changes to the operation of the ME tunnels.

### ISSUE THREAD

**Issue by bamik69** [GTNewHorizons/GT-New-Horizons-Modpack#8965]
### Your GTNH Discord Username

bamik

### Your Pack Version

2.1.1.0

### Your Proposal

I propose to introduce the nesting of ME tunnels.
![2021-11-30_16 56 41](https://user-images.githubusercontent.com/22926983/144060398-060c4370-3bac-4a48-b654-4784d7d6e238.png)
As you can see, the channels are not transmitted through a nested tunnel. But other types of tunnels work fine. Nested tunnels must belong to another transport network. Tunnel recursion can lead to negative consequences.

### Your Goal

This feature will reduce the number of cables on the base. Simplify the perception of the network. Allows you to structure the network.

### Your Vision

Our bases are becoming more and more extensive. Connecting all the mechanisms into one well-established system is a significant problem. An alternative to this proposal may be the appearance of cables with 128 channels or more. It would be possible to connect to them via conventional 32-channel cables. Or as a development of thought, add ME controllers with 128 channels on the side.
Let this tangle unravel.
![2021-11-30_17 15 51](https://user-images.githubusercontent.com/22926983/144063699-3aa1eff9-1a18-4a36-bc59-217314ec0fe1.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
One dense cable can carry 32*32=1024 channels, how is that not enough?

**Comment by bamik69** [comment]
I have a base of 27*27 chunks. This is 729 chunks. Each requires 3 branches from different networks. This results in 2187 channels of the transport network. In total, it is required to lay at least 69 dense cables from the controller. Now imagine what a tangle it will be.

**Comment by bamik69** [comment]
Now, if it were possible to drag these 1024 channels of the transport network with one cable, which becomes possible with my proposal, it would greatly simplify the task. Or there were cables capable of this.

**Comment by bamik69** [comment]
You have to pay for convenience. Maybe tunnels can be entered at different levels. The usual one has no attachments, and the second level can have an attachment of a normal tunnel. Etc.

**Comment by styopa1** [comment]
super duper dense 128 channels cable as a solution it is a good idea, i guess

**Comment by boubou19** [comment]
Reducing the amount of tiles could be good i guess, but you can already use the wireless connectors from AE2stuff, it even got a buff on its energy consumption in dev.

@repo-alt computation wise, what's better between multiple cable lines and a single one, for the same amount of used channels? because if it can reduce the amount of channel lines and the lag produced by it, that would be convenient both for players and server in MP.

**Comment by repo-alt** [comment]
More channels per cable is of course easier to compute. I'm not sure if that has any impact though, except when connecting new nodes.

**Comment by boubou19** [comment]
Could it reduce initial timeout of the server when a base is first load then? if yes, then i support the change because it's always a pain for the others to get a DC when an endgame player come.

But i remember you said somewhere a lot of stuff was hardcoded to be 32 channels, so if it's a pain to do no big deal.

**Comment by bamik69** [comment]
> wireless connectors from AE2stuff

It's too painful this thing eats energy depending on the distance. After 14 chunks, it will be a very huge loss of energy.

**Comment by greesyB** [comment]
> It's too painful this thing eats energy depending on the distance. After 14 chunks, it will be a very huge loss of energy.

By the time an AE system grows to such a size where 2-4 dense cables of p2p tunnels is not enough you should be able to make the neutronium energy cell, no? At which point the energy cost of wireless connectors is meaningless.

**Comment by GTNH-Afx237v7** [comment]
Use quantum tunnels instead, they eat much less energy and it’s Independent of distance. But for sure I’d like to hear how a let’s say 128 channel dense cable behaves - let’s see what repo says.

**Comment by repo-alt** [comment]
Well, if they will be just dumb cables, not accepting parts, not rendering channels, that should be not too hard. They would not connect to anything but cables, because indeed 32 channel capacity is somewhat hardcoded.

**Comment by repo-alt** [comment]
(Not this week though)

**Comment by boubou19** [comment]
well it seems kinda ok to me, maybe render the channels too but it's very optional

**Comment by repo-alt** [comment]
I have no idea how to legibly render such amount of channels tbh. Also Waila exists.

**Comment by boubou19** [comment]
yeah waila exists this why it's very optional. For the rendering, maybe recycle the code of the dense cable, but with ratio 4:1

**Comment by repo-alt** [comment]
If that is enough, ok.

**Comment by bamik69** [comment]
Super! If it turns out with 128 channels, then you can not stop and hook up with 512. And instead of 16 lines of the transport highway, only 1 will stretch. It will be quite normal if only dense cables can be docked to these cables. And through the tunnel, it is enough to leave the transmission of only 32 channels. This is more than enough for local wiring.
