### ISSUE TITLE
even if the energy hatch of the Tree Growth Simulator is short circuited, oak logs will be output.

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#8970]
### Your GTNH Discord Username

iouter

### Your Pack Version

2.1.1.5

### Your Server

SP

### Your Expectation

test the Tree Growth Simulator

### The Reality

1. even if the energy hatch is short circuited, oak logs will be output.
2. can work without a saw.

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by iouter** [comment]
it seems that no saw will produce an effect similar to a short circuit.

**Comment by Glease** [comment]
What even is a short circuited energy hatch? Do you mean it runs without power or something?

**Comment by Glease** [comment]
Seems like a bug in structure checking code.

**Comment by iouter** [comment]
> What even is a short circuited energy hatch? Do you mean it runs without power or something?

even if the multiblock stops running because of no power or no saw, it will immediately output oak logs.

**Comment by Glease** [comment]
Should be fixed by https://github.com/GTNewHorizons/GTplusplus/pull/60
