### ISSUE TITLE
the recipe of smash the cryolite ore is not unified.

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#8971]
### Your GTNH Discord Username

iouter

### Your Pack Version

2.1.1.5

### Your Server

SP

### Your Expectation

smash the cryolite ore

### The Reality

the cryolite ore in stone will get 2 crushed cryolite ore and no by-products, need 7eu/t. but the cryolite ore in basalt (or other rock) will get 8 crushed cryolite ore and have by-products, need 2eu/t.

### Your Proposal

unify these recipes. all the recipes of smash ores should need 2eu/t and have by-products.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@iouter what you mean unify the recipe?

**Comment by iouter** [comment]
this recipe's output is 2 crushed cryolite ores, need 7eu/t, no byproducts.
![image](https://user-images.githubusercontent.com/62897714/144203360-0142f8ab-8c09-49c3-8e79-c88ec0f93a5e.png)
these recipes's output is 8(16) crushed cryolite ores, need 2eu/t, have byproducts.
![image](https://user-images.githubusercontent.com/62897714/144203321-99d15f70-806d-4e47-808d-b02dd3ba1dd6.png)

these recipes need be unified. in general, gt ores's output is 2 crushed ores, need 2eu/t, have byproducts. but there are also some ores that produce more, such as redstone, electrotine.
![image](https://user-images.githubusercontent.com/62897714/144204465-4947ed15-3907-4c27-9c43-40940741f0d7.png)
![image](https://user-images.githubusercontent.com/62897714/144204398-d1ac3956-7d06-46e2-ab78-b46ee64c8cf9.png)

**Comment by PolkageistHS** [comment]
Here's a bit more info, with the oredicts for each ore, their tooltip mod, and their macerator outputs in 2.1.2.0Pre2:
oreBasaltCryolite (GregTech5-Unofficial) - 8 Crushed Cryolite Ore, 40% chance of one Alumina dust, 50% chance of one Basalt dust
oreRedgraniteCryolite (GregTech5-Unofficial) - 8 Crushed Cryolite Ore, 40% chance of one Alumina dust, 50% chance of one Red Granite dust
oreCryolite (GT++) - 8 Crushed Cryolite Ore, 40% chance of one Alumina dust, 50% chance of one Stone dust
oreMarbleCryolite (GregTech5-Unofficial) - 8 Crushed Cryolite Ore, 40% chance of one Alumina dust, 50% chance of one Marbledust
oreBlackgraniteCryolite (GregTech5-Unofficial) - 8 Crushed Cryolite Ore, 40% chance of one Alumina dust, 50% chance of one Black Granite dust
oreEndstoneCryolite (GregTech5-Unofficial) - 16 Crushed Cryolite Ore, 80% chance of one Alumina dust, 50% chance of one Endstone dust
oreNetherrackCryolite (GregTech5-Unofficial) - 16 Crushed Cryolite Ore, 80% chance of one Alumina dust, 50% chance of one Netherrack dust
oreCryolite (GregTech5-Unofficial) - 2 Crushed Cryolite Ore, no other byproducts possible

Given that the GT++ and GT5U Cryolite ores share the same oredict, that might be where the recipe generator thingy is getting confused?  I don't think we've ever added a new ore that was already a part of GT++ before.

**Comment by PolkageistHS** [comment]
Confirmed fixed with the new GT++, Alk's cryolite has a different oredict now.  Cryolite from TF gives 8 crushed ore as expected.
