### ISSUE TITLE
Identify libraries that are used by mods but open source and fork

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8972]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.1.1.5pre2

### Your Proposal

GT5 stopped building last night for those without translocators alread cached. Even if it’s just a transient maven issue - supporting libraries that can be brought “in house” should. 

```
./gradlew build
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve codechicken:Translocator:1.7.10-1.1.2.16.
     Required by:
         project :
      > Could not resolve codechicken:Translocator:1.7.10-1.1.2.16.
         > Could not get resource 'https://nexus.covers1624.net/repository/maven-hosted/codechicken/Translocator/1.7.10-1.1.2.16/Translocator-1.7.10-1.1.2.16.pom'.
            > Could not GET 'https://nexus.covers1624.net/repository/maven-hosted/codechicken/Translocator/1.7.10-1.1.2.16/Translocator-1.7.10-1.1.2.16.pom'.
               > Connect to nexus.covers1624.net:443 [nexus.covers1624.net/81.25.68.254] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
3 actionable tasks: 2 executed, 1 up-to-date
```

This one is just an example - and maybe https://github.com/Chicken-Bones/Translocators is the code 

### Your Goal

I will add notes to this issue for each library/dependency I find that is 1. Used by GTNH or a supporting mod and 2. Available to fork under an open source license 

### Your Vision

1.7.10 modding support seems to be sunsetting in some places, stability in the builds whilst we can is good. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SinTh0r4s** [comment]
Awesome! I fully support your idea!

It would be utterly amazing if you would go the extra mile and verify which commit of those repositories is currently used in GTNH. This takes up the most time when migrating the build script and does not require any gradle changes. Feel free to hit me with any questions.

**Comment by bombcar** [comment]
Will do - and when possible will try to identify if we can "move on up" but that requires more testing. Luckily many of these are untouched since years ago.

**Comment by bombcar** [comment]
- [x]  https://github.com/GTNewHorizons/Translocators has been added, and a PR created to update it so it builds. It looks to be 100% the same code as we've been using.
