### ISSUE TITLE
Bentonite chem formula change

### ISSUE THREAD

**Issue by GalaxyDragon** [GTNewHorizons/GT-New-Horizons-Modpack#8973]
### Your GTNH Discord Username

Бердовский АА#0989 

### Your Pack Version

2.1.1.0

### Your Proposal

Remove oxygen or water from bentonite formula 

### Your Goal

currently there is 30 'stuffs'+36 oxygen
![Снимок экрана от 2021-12-01 23-04-04](https://user-images.githubusercontent.com/22980159/144308085-c3cb6d61-055d-4a8b-b637-79d53f719148.png)
But electrolyzer recipe ignore oxygen
![Снимок экрана от 2021-12-01 23-20-47](https://user-images.githubusercontent.com/22980159/144308092-ced7d1a9-b6df-43ab-83b0-3281a7a39b7d.png)
 There should be removed water from formula to be less than 64 'stuffs' in chem formula and recipe changed to 61 bentonite ->Na + 6Mg + 12Si + 6H + 36O
Or just removed oxygen and not change the recipe

### Your Vision

Fix inaccuracies in the description of things is always cool

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
must be fixed/changed in 2.1.2.3. Please test
