### ISSUE TITLE
AE2 Fluid Crafting/or a recreation of such features.

### ISSUE THREAD

**Issue by amHunter98** [GTNewHorizons/GT-New-Horizons-Modpack#8974]
### Your GTNH Discord Username

amHunter#1637

### Your Pack Version

2.1.1.0

### Mod Name

AE2 Fluid Crafting

### The Mod to Add

The mod enables you to directly move fluids from Fluid Storage (either in the ME system itself or in containers like tanks) to the interface a pattern is calling for, the interface as normal injects the items and fluids into the machine to use.  The mod works by converting every mb of fluid into a "drop" item, like 1mb "drop of Cryotheum".  This allows it to send however much of the item is needed.  The main attraction of this mod is that it skips the steps of needing to use flasks.  If one needs to make a circuit with 144 tin, you can make a series of patterns to do this:
1. Fluid Extractor : 1 Tin Ingot = 144 mb of tin
2. Circuit Assembling Machine = 6 physical items + 144 mb of tin (fluid) = 1 circuit

The simplist way to put it is that this mod allows you to make patterns which can read amounts of fluid, and to allow items and fluids to go into machines, uses a new interface called "Dual Interfaces" which can have both fluid and items.  There are also buffer blocks that can hold both fluid and over 9 items for recipes that may require more than 9 physical items.

Unfortunately, the mod is only for 1.12.2 and the author is not willing to port it down to 1.7.10, which means the mod would need to be downported or recreated.

The only important thing from the mod is enabling patterns to use fluids directly in their crafting and the dual interface which accepts/sends/holds both physical items and fluids.

### Your Reason

I find that using flasks is not only tedious, but exhausting to an extent.  So many recipes require different types of fluid and it is not optimal to have to make machines to displace fluids from the flasks, and the flasks themselves can't be used directly with AE2 in crafting of circuits since the flask is a physical item and not a fluid item.  This will allow fluids to be directly used from fluid storage.

### Preliminary Investigation

I haven't.  This mod is only for 1.12.2 and I can't downport it myself.  The mod author does have the source code on Github, so I believe that counts as open source license.  I do think this mod would work better for more simple autocrafting as I don't find using the flasks conventional and rather complex.

This is the link to source code via the author on his CurseForge page.

https://github.com/phantamanta44/ae2-fluid-crafting

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by boubou19** [comment]
did you tried to play with ExtraCells2? Because from what i understand it's what you are looking for and it's already in the pack. But it's buggy and laggy so becareful when you use it.

**Comment by PolkageistHS** [comment]
Extra Cells 2 bad.  I would much rather see if this other mod handles fluids better than EC2 does, because EC2 fluid crafting is a laggy terrible mess that should be eaten by drowning creepers.

**Comment by amHunter98** [comment]
If need be, I can make a video of the mod in action.  It simplifies crafting items with fluids very nicely.  I don't believe EC2 allows you to make patterns involving fluids, just storing them, which was later implemented into AE2 directly.

**Comment by bombcar** [comment]
Does anyone have a (preferably smallish) world save that shows ec2 being it’s laggy self?

**Comment by yukieiji** [comment]
First of all, who will backport this mod from 1.12 to 1.7.10?

**Comment by bombcar** [comment]
IF it can be shown to work well in 1.12 AND it would be a good replacement / accompaniment for ec2 AND they have time, it could certainly happen. 

Or something similar implemented. But that first part is key. I don’t know if an ae2 / ec2 setup can be made in 1.12 and shown to lag, and then compare it to this. 

Anything works in small amounts - it needs to work at scale.

**Comment by bombcar** [comment]
So ec2 and ae2 exist for 1.12. If you can build a fluid setup in 1.12 that lags with ec2 but not with this it could be a winner

**Comment by repo-alt** [comment]
Fluid support in AE2 was much improved in 1.12 but it was still buggy. It is really being fixed only in the current version (for 1.18)
To presumably support this suggested mod one would need to backport a lot of stuff from 1.12. I don't really object to that only if someone else will do it.

**Comment by boubou19** [comment]
> If need be, I can make a video of the mod in action. It simplifies crafting items with fluids very nicely. I don't believe EC2 allows you to make patterns involving fluids, just storing them, which was later implemented into AE2 directly.

You can make patterns involving fluids with EC2: simply make the pattern normally, then specify the fluid via a fluid container in the craft (add a cell/flask/drum/whatever that holds a liquid). Then place your pattern in a fluid interface.

**Comment by miozune** [comment]
Added to the pack: https://github.com/GTNewHorizons/AE2FluidCraft-Rework
