### ISSUE TITLE
Standardize recipes in chemistry.

### ISSUE THREAD

**Issue by bamik69** [GTNewHorizons/GT-New-Horizons-Modpack#8975]
### Your GTNH Discord Username

bamik

### Your Pack Version

2.1.1.0

### Your Proposal

At the moment there are 4 variants of recipes in chemistry: with mass conservation, molecular, unsystematic, with a catalyst.
Examples:
Mass conservation
![image](https://user-images.githubusercontent.com/22926983/144418792-01dc3ada-8f5e-41cc-984e-912df33b0bfc.png)
Molecular
![image](https://user-images.githubusercontent.com/22926983/144419953-89763d7f-481e-4e15-bd46-119eae02b73a.png)
With a catalyst
![image](https://user-images.githubusercontent.com/22926983/144420507-e34dbe4e-a0f3-4ce1-bdd3-34b2dd04f6f7.png)
Unsystematic
![image](https://user-images.githubusercontent.com/22926983/144420846-493ddcc2-c084-4b2d-8381-67567830ca3b.png)
I propose to bring everything to the same type. Maybe with Haphazard not everything will be able to be corrected. In addition, there are discrepancies with reality. For example, the last example uses zinc, although the WiKi suggests that there should be copper. The catalyst is not consumed in reality, it degrades. Therefore, it should also be present at the output, but with some probability, for example, 99%.

### Your Goal

Make all recipes more convenient to calculate. Now we have to clarify how much and what will come out. Compilers of recipes find it difficult to navigate. We have to compromise in order to maintain at least some balance. As a result, formula curves that are far from reality, the inability to calculate the necessary costs of components, unreasonable consumption of materials, irreversibility of recipes (the inability to get the original ingredients from the result in the initial amount).

### Your Vision

I am ready to help implement these changes in the form of compiling a list of changes. I understand that it will be hard work. There are a lot of recipes that require changes. But in the end, it must be done. In the future, it will be easier for the developers themselves.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bamik69** [comment]
In addition, it will immediately catch your eye whether the recipe is correct or not. I suggest preserving the mass when 1 + 1 = 2. In the meantime , it turns out the following:
![image](https://user-images.githubusercontent.com/22926983/144425363-085f855e-f947-42e5-ac91-518ae9bac8ec.png)
![image](https://user-images.githubusercontent.com/22926983/144425418-4314fd66-412a-4b90-b8e6-c7cbc48fd887.png)
Back:
![image](https://user-images.githubusercontent.com/22926983/144425572-82ecd76e-49b5-41fe-9b9b-6ff5449c7339.png)
Water is not a pity, but this is not a rare case. I.e. we get that it is impossible to get the original back in the same amount. Either in the first recipe there should be 1000 water, or in the second 3000 at the outlet. I suggest the second option as a standard.

**Comment by miozune** [comment]
In progress: https://github.com/GTNewHorizons/GT5-Unofficial/pull/1062
