### ISSUE TITLE
Crash with new Buildscript

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#8976]
<s>Galacticraft crash with new Buildscript
https://gist.github.com/Dream-Master/d7ff3c3192dfdcae0093372759b0619d
Mine and Blade also
https://gist.github.com/Dream-Master/0c67c1286ae57be9857fedb3546324f4
Ender Core
https://gist.github.com/Dream-Master/ae065fe286fbe9bc5ebf1af26ec758fb
Code Chicken Core/LIB
https://gist.github.com/Dream-Master/1aeeac3cf873e7496a860978f816aa38</s>

found out it was a duplication

now ender io crash
https://gist.github.com/Dream-Master/54a4fd75687b4f8ef6bcd9935e2d4910

new crash
https://gist.github.com/Dream-Master/eacee114946c5783169868e0b8c0f5a9

**Comment by bombcar** [comment]
Looks like it might be a tag thing. If the kids calm down I can take a look

**Comment by bombcar** [comment]
Galacticraft runClient worked fine - trying against 2.1.1.5pre2

**Comment by Dream-Master** [comment]
@bombcar is wasnt Galacticraft

**Comment by Glease** [comment]
what's still broken? if none maybe we can close this
