### ISSUE TITLE
Change inf chest slot size 2^31->2^63

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#8977]
### Your Proposal

Change the max slot size from 2^31 to 2^63, the real limitation with inf chests is types not storage. This is the ultimate, final storage medium effectively. I don't see why I shouldn't be able to store the items I want. I have over 11 billion items currently and am running into overflows on simple shit like stone dust and it's lame.

Afaik this is relatively easy from what I've been told but I could be wrong.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
That’s INTMAX, right? What interfaces with it that could die at the 32 bit limit?

**Comment by johnch18** [comment]
Please tell me you mean number of items per slot not number of slots because that's way too much RAM

**Comment by GlodBlock** [comment]
it may cause some unexpected results. as bombcar said, most interfaces only support int as valid type. now the inf chest already can start a new stack when the old stack is over intmax. it is unnecesssary to enlarge its per slot holding size.

**Comment by repo-alt** [comment]
Int is vanilla item stack limitation, also standard forge interfaces like ISidedInventory and IInventory deal with standard ItemStack.
Now, if we forbid all external automation access and treat infinity chest as a fancy ME drive (as I suggested earlier), then this would not be an issue.

**Comment by bombcar** [comment]
In that case why not add a new ME drive?

**Comment by GTNH-Colen** [comment]
> Please tell me you mean number of items per slot not number of slots because that's way too much RAM

Obviously... Read my post clearly, I want item stack size increased, not total types.

**Comment by GTNH-Colen** [comment]
> Int is vanilla item stack limitation, also standard forge interfaces like ISidedInventory and IInventory deal with standard ItemStack. Now, if we forbid all external automation access and treat infinity chest as a fancy ME drive (as I suggested earlier), then this would not be an issue.

Sure this would be ideal but idk how hard it would be to achieve.

**Comment by boubou19** [comment]
now that you can fill multiple slots with the same item in the infi chest, i consider this solved.
