### ISSUE TITLE
Alveary does not produce second "primary" comb per cycle even with correct frames - intentional?

### ISSUE THREAD

**Issue by dieselfuelonly** [GTNewHorizons/GT-New-Horizons-Modpack#8978]
### Your Pack Version

2.1.1.0

### Your Server

SSP

### Your Expectation

WIth the right bee and the correct number of frames in an Alveary, it should have a chance at producing two of the primary product comb per 27.5s bee tick.  Even though production is limited to 100%, 

From FTB Wiki page on Alveary:

========

"Note that the maximum amount of Combs produced every Bee Tick ( 27.5s ) is 2 for the Regular Combs and 1 for the Special Comb.

So now we can multiply 42% (0.42) chance by 1600% (16), resulting in a 672% (6.72). That means in theory we should be producing 6 Honey Combs every 27.5 Seconds along with a 72% (0.72) chance of producing 7. However, you're only able to produce 2 of Regular Combs every 27.5s because of the 100% limit. So in this case we only would have needed 3 Frames to maximize our production. You might think we would only have needed 2 since with 1 Frame we would have had 0.84 and then with the second a 1.68 total, thus surpassing the 100% production limit but since we're producing normal combs we also have a chance to produce a second comb. To find out how likely you're to produce a second comb you simply cut your current number in half, We have a 1.68 or 100% chance of producing the first comb and then a 0.84 to produce the second. "

========

For example, I believe the base Imperial bee has a 20% chance of producing a Dripping Comb.  My bee has the fast trait.

20% comb chance * 1.2 speed modifier * 1600 frame modifier (4 frames) = 384% Chance.  So chance of first comb is 384%, which means a comb every cycle since max is 100%.  Chance of second comb is 192% (half of initial) which should mean a second comb is always produced every cycle.  

Not sure if this is intentional or not, but considering the expense of producing an Alveary with those first sets of bees it would be nice to have fixed.

### The Reality

Only 1 comb is produced.

### Your Proposal

Fix Alveary production so there is a chance of a second primary comb chance.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
are the bees in their prefered range of temperature and humidity?

**Comment by dieselfuelonly** [comment]
> are the bees in their prefered range of temperature and humidity?

Yep

**Comment by Glease** [comment]
Upper bound of 100% output is what it supposed to do. This is working as intended. 

We can however code this extra output into our fork of forestry though. Marking this as a suggestion instead of bug for now.
