### ISSUE TITLE
Adjust stack size on some items from 16 to 64

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8981]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

We made ic2 seeds stack in https://github.com/GTNewHorizons/Hodgepodge/pull/33

We made ingots stack to 64 in #8613

We should make the following items stack to 64 also:

- Snowballs
- Ender pearls
- Eyes of Ender
- Eggs

### Your Goal

As far as I can tell there's no gameplay reason to limit these (unlike say the TC hearts where the stack size of 10 limits how many hearts you can get from them).

It's just vanilla things.

### Your Vision

Hodgepodge these to 64

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
Eggs

**Comment by bombcar** [comment]
Eyes were already 64

**Comment by bombcar** [comment]
Unless there are others these are fixedindev

**Comment by bombcar** [comment]
There are some others found, but they're more in GT so I'd like some discussion before updating them:

* rotors (like used in pumps)

There are also the double/triple/etc ingots and friends, but those aren't used that much and the stack size isn't annoying. But batch crafting pumps is because of the 16 on rotors.

**Comment by PolkageistHS** [comment]
TiCo hearts (not heart canisters) only stack to 16, and while they can be eaten to restore 20/30 hearts, you can also get a stack of max tomatoes that heals all health, and those stack to 64.  Any balance issues with changing the TiCo hearts to stack to 64?  

Definitely keep the heart canisters stacking to 10.  Otherwise we're gonna run out of colors for hearts on the HUD.

**Comment by GTNH-Afx237v7** [comment]
Seems we forgot volumetric flasks? Or would that break setups in any way?
