### ISSUE TITLE
remove tiny piles from combs

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8985]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Proposal

to be inline with our policy of removing the tiny pile generation, we should remove the tiny piles from some combs to make them looting the full dusts. (energetic alloy comb for exemple)

### Your Goal

Packaging the tiny piles make some severe lag on the servers.

### Your Vision

Players will be happy to remove tedium of packaging the dusts, and it might remove some lag from the game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by D-Cysteine** [comment]
I happen to have a text file containing all bee comb centrifuge outputs, which might be useful to anyone working on this. Let me know if I should attach it here. It is a VERY large text file though: 100's of KB

Also, looks like the Fertilizer bee produces tiny piles directly (ashes and dark ashes, 20% chance each). Do we want to fix that as well? I think it's the only bee species that produces tiny piles.

**Comment by bombcar** [comment]
Can’t hurt to post it. Microsoft can pay to store it for all eternity.

**Comment by D-Cysteine** [comment]
Alright, here it is:
[BEES.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7656941/BEES.txt)

Search for `BEGIN COMBS` to find the comb section. The first section is bee species.
