### ISSUE TITLE
Superbuffer not so super

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#8991]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.1.4.QF2

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

The Super Buffer should just work as described. It is not only needed for tinys, but also for stuff like Bulk ore processing.

### The Reality

The Super Buffer sometimes just stops working, and in different ways. I had it on several occasions that it just collected items inside and stopped pushing them out. This was only fixed by replacing it. Weirdly, sometimes even replacing it did not help, and that specific super buffer was broken for all eternity and i had to craft a new one. That was still in 2.1.1.2.
Then, at other times (also now in 2.1.1.4QF2), the super buffer stops to accept any items, even though it has space. Like, i have a me storage bus connected to it, but it could no longer store any items inside the super buffer, even though it had space. This was fixed by wrenching it and placing it again.

### Your Proposal

I know it is hard to fix when it is not clearly reproducible, but in fact it happens quite regularly. There must be some flaw in the code for it causing it to bug out occasionally.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
Addidionally, the super buffer sometimes fails to output the "last" stacks... see this one
![2021-12-04_15 35 27](https://user-images.githubusercontent.com/10967188/144713383-fd236880-187d-4626-9176-249b366b6e04.png)
:
It should output into the quantium pipe, and is set to 56 Items... still it does not do anything, and has been like this for a minute or so. It will work if more items come in, but still... there are even some stacks with over 100.

**Comment by bombcar** [comment]
IIRC internally the super buffer has stacks and they sometimes do NOT get combined (and there is a screwdriver mode you can set for them to combine but it then lags).

**Comment by Savallator** [comment]
Isn't that only the chest buffer? At least, i have never seen that screwdriver mode for the super.

**Comment by boubou19** [comment]
you aren't using the sorting mode, so internally the buffer keeps stacks without merging them. if in one slot you have a stack of 35 and another stack of 45, we expect the buffer to output 56 items, butbecause it only does stack slot comparison and not sum of all the same stack slots, it does some weird behavior

**Comment by Savallator** [comment]
How do i activate it then? Also, the second issue of it not accepting items seems to be a different one...

**Comment by boubou19** [comment]
sorting mode can be set via the srewdriver iirc, but you shouldn't use it on high I/O, as it's extremely laggy (this is one of the reasons we decided to slowly get rid of the tiny piles in the game)

**Comment by Savallator** [comment]
I tried everything with the screwdriver, it does not do anything.

**Comment by boubou19** [comment]
oh my bad, it's the soldering iron

**Comment by bombcar** [comment]
does infinity chest have same stack combining problem

**Comment by Savallator** [comment]
Why does it even use stacks internally, and not just a list of items, and when a new item is added it checks if it exists in the list? This can be done very efficient, like at least linear runtime, with tricks even better...

**Comment by repo-alt** [comment]
Because minecraft IInventory is essentially an array of ItemStack, and it is standard interface for interoperability. We might probably provide some fake inventory but it is less trivial than just changing internal container.

**Comment by boubou19** [comment]
Also, the Super Buffer is a child class of the chest buffer. So basically it's just a bigger chest buffer with the ability of taking items via the gui removed. If you want to fully understand how a super buffer works, just toy with the chest buffer

**Comment by Savallator** [comment]
> 

But that is no problem at all... just, when adding items, iterate the array and see if there is already a stack of that item? should be really trivial?

**Comment by Savallator** [comment]
Or are you saying, internally there are still stacks of 64 only? So, when adding 65 items, it will split them anyways? That is quite bad design then imho.

**Comment by Savallator** [comment]
okay, i looked at the source and it is much clearer now...

**Comment by repo-alt** [comment]
Technically there is no need to kep stacksize 64 inside of the superbuffer, but someone needs to rewrite it.

**Comment by Savallator** [comment]
I will look into it.

**Comment by Savallator** [comment]
By the way, is it intendet that the super buffer and chest buffer turns opposite when wrenching? Feels quite Counter-intuitive...

**Comment by bombcar** [comment]
> By the way, is it intendet that the super buffer and chest buffer turns opposite when wrenching? Feels quite counterintuitive...

iirc there's a bug on that, or something else that has a inverse wrenching ...

**Comment by Savallator** [comment]
It is done [here](https://github.com/GTNewHorizons/GT5-Unofficial/blob/92c78f346995f7140902f9719daa89d427f61a04/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java#L266)

**Comment by bombcar** [comment]
#4667

**Comment by repo-alt** [comment]
It is fixed at that line, you probably use version that is older than the source

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3166

**Comment by repo-alt** [comment]
"fixed", meaning "hidden from the user"

**Comment by Savallator** [comment]
Yeah, okay, i see...

**Comment by johnch18** [comment]
Is the stack compression not working?

**Comment by boubou19** [comment]
there is no stack compression when the sorting mode is set to false, as it's used to keep the stacks with order.

**Comment by Glease** [comment]
Closing as user error.

**Comment by Skiftcha** [comment]
if nothing changed since 2.1.1.0 then they are still broken and only sort in random moments

**Comment by Skiftcha** [comment]
it fills first slots here
https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_ChestBuffer.java#L73

so you need aTimer % tickRate[mTier] == 0 and hasInventoryBeenModified() at the same tick
otherwise contents remains unsorted

**Comment by GTNH-Afx237v7** [comment]
Does work fine for me in 2.1.1.4QF2. As boubou said you need to enable sort mode with soldering iron, which was not present in 2.1.1.0.

**Comment by Skiftcha** [comment]
> As boubou said you need to enable sort mode with soldering iron, which was not present in 2.1.1.0.

yes. in 2.1.1.0 there is no way to disable sorting. it should work by default

**Comment by repo-alt** [comment]
Actually that does look like a bug. You don't often see it with super buffers because they usually have high throughput
