### ISSUE TITLE
incorrect localization entries for galacticraft mobs

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8993]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

i saw a player die from an evolved zombie, was expecting to see the localized name of the evolved zombie in the chat

### The Reality

i saw this `xxxx was slain by entity.GalacticraftCore.EvolvedZombie.name`

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
![image](https://user-images.githubusercontent.com/533931/145081281-3a504e27-61bd-4206-8a8c-9ffc4fde5391.png)

they're there, so this is in the whatever reports deaths to chat ...

**Comment by boubou19** [comment]
yeah, but they do have the wrong prefixe: your screen shows that they availiable under the prefixe `entity` while the game actually asks for `entity.GalacticraftCore`

**Comment by draknyte1** [comment]
Probably changed when buildscript did.

**Comment by bombcar** [comment]
```
    public static void registerGalacticraftNonMobEntity(Class<? extends Entity> var0, String var1, int trackingDistance, int updateFreq, boolean sendVel)
    {
    	if (FMLCommonHandler.instance().getEffectiveSide() == Side.CLIENT)
		{
    		LanguageRegistry.instance().addStringLocalization("entity.GalacticraftCore." + var1 + ".name", GCCoreUtil.translate("entity." + var1 + ".name"));
		}
        EntityRegistry.registerModEntity(var0, var1, nextInternalID(), GalacticraftCore.instance, trackingDistance, updateFreq, sendVel);
    }
```

this looks suspicious
