### ISSUE TITLE
add the ability for railcraft anchors to be interacted with redstone / OC

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8994]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Proposal

because the pack has the anchor interaction with pipes set to false in the railcraft config (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/f2580d99bb9a826d47de078cb4816a2d4f71b9a5/config/railcraft/railcraft.cfg#L19), players must check regularly their anchors. But with last tiers of coins and/or with the fuel consumption reduction that comes from the anchor sentinel usage, it can take a very long time before it lacks of fuel again.

What i suggest is:
-  to add a way to get an anolog signal from the current fuel decay progress in the anchor (the RC tanks have a way to extract a redstone signal representing the capacity via a comparator)
- add a way to grab various data from the anchor via OC, such as its type, its owner, its remaining time, and the number of items inside it (even if this information is technically already obtainable with an inventory controller).
- reenable the anchor automation?

### Your Goal

The goal is to make monitoring of the anchors more easy.

### Your Vision

That will improve the pack as it sucks when crafts fail to complete in multi because of a chunk reload, so it missed for a couple of tick to convey power to the machines.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/144750372-6df35796-f7a1-4eb6-8dd9-4bcfc0040c54.png)

**Comment by boubou19** [comment]
@Dream-Master What do you think about reenabling this:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/f2580d99bb9a826d47de078cb4816a2d4f71b9a5/config/railcraft/railcraft.cfg#L19

**Comment by Dream-Master** [comment]
sure why not. Not sure why i disable it ?

**Comment by Dream-Master** [comment]
we disable it because to prevent people put ender coins or ender stuff into anchors automaticly and load thier bases for month even if they not online anymore.

**Comment by Dream-Master** [comment]
@boubou19 a better option would be a cfg wich device can interact with pipes. We have the source now and can add it

**Comment by repo-alt** [comment]
This is no longer an issue, since world anchors are disabled on officials?

**Comment by boubou19** [comment]
world anchors are disabled on the officials indeed. But automating the pipes based on each anchor type sounds easy to do, i'll see what i can do after i'm back home

**Comment by bombcar** [comment]
Do railcraft anchors load after restart? Or do they require player to login at least once? It’s only world that does it automatically right?

**Comment by repo-alt** [comment]
>  It’s only world that does it automatically right?
yes
