### ISSUE TITLE
Implement a multiblock boiler for solid fuels that is useful for EV/IV

### ISSUE THREAD

**Issue by Steelux8** [GTNewHorizons/GT-New-Horizons-Modpack#8995]
### Your GTNH Discord Username

Steelux#1934

### Your Pack Version

2.1.1.4 QF2

### Your Proposal

Add a better boiler that is powerful enough to avoid steel boiler spam when using solid fuels, for EV/IV tiers.

### Your Goal

Enable an option to use solid fuels, like the super solid fuels, in mid-game without the need to spam boiler multis, and the lag that comes from doing so.

### Your Vision

There are several tiered large boilers, but they don't scale up in power output nearly well enough to be worth building. The steel boiler outputs 600 EU/t worth of steam at 100% turbine efficiency, while the tungstensteel version only does 1000 EU/t, which means that the progession comes from more than 1 amp to less than 1/8 of the amp of the respective tier. This forces spamming lower tier boilers because the titanium and tungstensteel ones are useless. Either change the values for these, or make a new multi to replace them.

This change would probably push for a nerf to diamonds' burn time, but I have no issues with that.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by 0lafe** [comment]
What about fluid nukes

**Comment by 0lafe** [comment]
I think it could be cool to make a mega boiler that can use combustable fuels for a better efficiency at IV. Things like charcoal though seem odd as an EV/IV fuel source though

**Comment by bombcar** [comment]
Coal power is a thing for sure - but charcoal not working could be reasonable. 

Would be interesting to have it be mostly coal but also consume some liquid fuel as an enhancer

ore maybe make it take compressed/refined coal
