### ISSUE TITLE
Current OPIS on this machine crashes hard after load

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#8999]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Server

MMCC

### Type of Server

Thermos

### Your Actions

I added http://jenkins.usrv.eu:8080/job/Opis/lastSuccessfulBuild/artifact/build/libs/Opis-1.3.2-MAPLESS_1.7.10-dev.jar (from 6 days ago or so) to my mudpack and now I can't even load it. 

I tried with or without optifine - it loads all the way and then crashes hard to desktop with an error I've never seen before.

But I'm using this OPIS downstairs on my other machine on 2.1.1.0 and it works fine .... the only thing different I can think of is this is a fresh download of 2.1.1.0 so I don't have the latest NEI hotness.

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7656195/fml-client-latest.log)
[crash-2021-12-05_08.26.59-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7656197/crash-2021-12-05_08.26.59-client.txt)
[crash-2021-12-05_08.40.56-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7656198/crash-2021-12-05_08.40.56-client.txt)
[crash-2021-12-05_09.08.07-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7656199/crash-2021-12-05_09.08.07-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
`	UCHIE	Opis{1.3.2-MAPLESS_1.7.10} [Opis] (Opis-1.3.2-MAPLESS_1.7.10-dev.jar)` looks like someone took the dev jar instead of the normal jar 😄
