### ISSUE TITLE
Unable to solidify unstable ingots once smelted with the smeltery

### ISSUE THREAD

**Issue by Runakai1** [GTNewHorizons/GT-New-Horizons-Modpack#9000]
### Your GTNH Discord Username

Runakai ~ Docsyᵇᵒᵗ#7676

### Your Pack Version

2.1.1.0

### Your Server

gtnh-2.myftb.de

### Type of Server

Don't know

### Your Expectation

Once I smelt unstable ingots in the smeltery, I am unable to cast it back into an ingot or build a part with it. 
I tried casting with the form in the basin and the normal table as usual.

Ingot form didn't work to get my ingots back. Also worth mentioning is that I got less MB of fluids than I put ingots in the smeltery. 64 unstable nuggets, crafted into 7 ingots and x nuggets, smelted, gave me around 520MB of fluid.
 
I expected to be able to get my ingots back from the smeltery after I realized I need to craft the unstable parts using an extruder

### The Reality

I expected to be able to get my ingots back from the smeltery after I realized I need to craft the unstable parts using an extruder

### Your Proposal

Be able to put the fluid in the fluid solidifier or cast within the smeltery, not extruder. Maybe a tooltip that unstable ingots can only be crafted with the nuggets, not the iron ingots. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Maybe make it not smeltable in the first place instead.
