### ISSUE TITLE
Add a pollution detection cover

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9002]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0pre2

### Your Proposal

Add a pollution detection cover that would detect pollution In a chunk and emit a red stone signal or optionally also be a machine controller too

### Your Goal

Make it so you can turn off a machine when pollution reaches a level, or turn a scrubber on, etc. 

### Your Vision

With pollution returning being able to automate mitigation would be nice

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
We have this as a block but a cover would be nice - or add a quest reminding it’s a block and not a cover

**Comment by Florexiz** [comment]
Block is way more suitable for this

**Comment by Glease** [comment]
Yeah. Use the gt++ block.

**Comment by GTNH-Afx237v7** [comment]
A cover would have the benefit of being able to face a machine controller cover on the control block of the air filter directly, much like when doing fluid automation with LCRs or similar.

**Comment by Florexiz** [comment]
Just piece block below controller?..

**Comment by Glease** [comment]
Air filter is supposed to shut itself down upon low pollution, and reenable itself upon high.

**Comment by GTNH-Afx237v7** [comment]
So it has an internal detection method already, didn’t know that. Very nice.
