### ISSUE TITLE
2.1.2.0 Pre 3 Fresh install crash on start

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/GT-New-Horizons-Modpack#9006]
### Your GTNH Discord Username

ZodiacK256B

### Your Pack Version

2.1.2.0 Pre 3

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Installed 2.1.2.0 Pre 3 that was posted on Discord. Did fresh install on Curseforge via custom profile for 1.7.10.

Got the attached crash on start.

Looks to be related to Thaumcraft Mob Aspects.

### Crash Report

[crash-2021-12-05_17.53.25-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7657057/crash-2021-12-05_17.53.25-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Loading in MMCC did not crash on an existing world (I had taken a previous install and replaced all the directories).

Did a config folder get missed?

**Comment by Zodiack256b** [comment]
Confirmed that it works fine on MultiMC as well for me. I will continue to tinker with Curseforge to see if I can get it going on that platform.

**Comment by bombcar** [comment]
Curse has all sorts of bad things, so maybe it's downloading an outdated mod or something.

IF you wanted you could compare the modfile names between the two installs.

**Comment by mitchej123** [comment]
This looks like the config file was missing/corrupt.

**Comment by Zodiack256b** [comment]
Confirmed. I replaced the Thaumcraft mob aspects folder and was able to start the pack on Curseforge. Looks to have just been a case of corruption on my first unzip. (used same zip for Curseforge and MultiMC install).

**Comment by crimsonblod** [comment]
I just want to bump that I just had the exact same error.

Lines 7-10 in the crash log were IDENTICAL, and the fix was the same. Just in case this is helpful for anyone who encounters this issue in the future, or that there is some recurring config corruption going on.

`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1
	at com.google.gson.Gson.fromJson(Gson.java:815)
	at com.google.gson.Gson.fromJson(Gson.java:741)
	at iguanaman.thaumcraftmobaspects.ThaumcraftMobAspects.readFromFile(ThaumcraftMobAspects.java:149)`
