### ISSUE TITLE
tips overwrite GTNH version number

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9008]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0pre3

### Your Server

SP

### Your Expectation

The tips shouldn't overwrite the version

### The Reality

They do:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/533931/144770510-b76106a2-c131-4fd4-a539-fcf5d268178d.png">

even at pretty large sizes it still happens

### Your Proposal

I can move the tips up to the "center" of the box perhaps, or the version number could be moved under the logo or into the upper right or ...

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Use a bigger screen resolution.

**Comment by bombcar** [comment]
Even at very large the long tips overlap

**Comment by Glease** [comment]
It doesn't overlap when I asked Dream the same question.

**Comment by bombcar** [comment]
<img width="204" alt="image" src="https://user-images.githubusercontent.com/533931/144787360-f5ad2da3-46b2- 4bef-abe5-760048cbbf78.png">
I guess it misses :)
