### ISSUE TITLE
Bee for production of Cryolite

### ISSUE THREAD

**Issue by dieselfuelonly** [GTNewHorizons/GT-New-Horizons-Modpack#9009]
### Your Pack Version

2.1.2.0-pre3

### Your Proposal

In the current stable version, it appears possible to progress without actually visiting the Twilight Forest.  I upgraded to the current dev version due to the bee breeding biome bug in stable.  I noticed that with the new aluminum line, cryolite is a requirement and there seems to be no way to get it without mining it in the TF.  Hoping to see it possible to produce with both bees and for those that want, crops.  I'm doing a play-through to see how far I can get while staying in only the vanilla dimensions using alternate production methods.  If the bee is added a requires a block underneath, there also needs to be some way to craft that block without initially mining the ores, perhaps finding it as loot in chests in the overworld.

### Your Goal

See how far I can get in vanilla-only dimensions.

### Your Vision

There should be alternate ways of sourcing the material besides just mining in the TF dimension.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
It would be weird to have an ore be required for progression, and at the same time not available through crops or bees. Crops are easier to work with early, so I would suggest a cryolite crop.
