### ISSUE TITLE
No recipe for Railcraft Osmium Tank

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#9010]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.0pre3

### Your Server

Single

### Type of Server

Single Player

### Your Expectation

Check Railcraft Osmium Tank recipes.

### The Reality

Railcraft Osmium Tank recipes missing.
![2021-12-06_20 39 39](https://user-images.githubusercontent.com/40425798/144844298-423aa143-e171-431e-805c-5dd9c479c840.png)

### Your Proposal

Add recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@yukieiji did you try with 2.1.2.0pre3 ?

**Comment by yukieiji** [comment]
I'm using v2.1.2.0Pre3 installed from GTNewHorizonsClient-1.7.10-2.1.2.0-pre3.zip(Railcraft-1.7.10-9.12.6-6-g9e24a09.jar)

**Comment by Dream-Master** [comment]
ok will check
