### ISSUE TITLE
Can't input EU in GC Machine

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#9011]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.0pre3

### Your Server

Single

### Type of Server

Single Player

### Your Expectation

I tried to input the EU to the GC machine.

### The Reality

Can't inputs the EU(I put the battery directly in and it didn't input.).
![2021-12-06_20 55 09](https://user-images.githubusercontent.com/40425798/144845357-d1412e99-3aad-4d5c-8385-29137e521058.png)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
did you try a GC battery? also it should support EU from cables directly

**Comment by yukieiji** [comment]
It worked with GC batteries. but, didn't work correctly with the cable.

**Comment by boubou19** [comment]
remember: new enet behavior is here, so you need to attach another GT consumer like a machine hull to make it work

**Comment by Glease** [comment]
Seems like *someone* forget to migrate over all GC asm stuff. Some annotations are not properly processed and it blowed up.

**Comment by boubou19** [comment]
looks like it's still not fixed: i had to put a MFSU because the trick of the GT EU consummer on the enet grid didn't worked.
