### ISSUE TITLE
YOTTank and GT++ number formatting

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#9012]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.0pre3

### Your Server

Single

### Type of Server

Single Player

### Your Expectation

I saw the GT++ recipe and YOTTank GUI.

### The Reality

It was different from GregTech's number format.
![2021-12-06_21 26 00](https://user-images.githubusercontent.com/40425798/144846314-9dcfa05f-7413-4501-8c17-e29a175c3645.png)
![2021-12-06_21 32 09](https://user-images.githubusercontent.com/40425798/144846646-90338ec3-e7b6-4f1e-b849-84e1ed65e9ba.png)

### Your Proposal

Should be the same as GregTech's number format.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Fixed in https://github.com/GTNewHorizons/GTplusplus/commit/d1cc99522c3add58f3830ae3b04e874600b1d40a.

**Comment by yukieiji** [comment]
Wait, I don't think we've fixed YOTTank number formatting yet.
