### ISSUE TITLE
GT++ achievement locale error

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#9013]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.0Pre3

### Your Server

Single

### Type of Server

Single Player

### Your Expectation

I picked up the Debug Scanner again.

### The Reality

GT++ achievement locale error
![2021-12-06_16 58 21](https://user-images.githubusercontent.com/40425798/144849411-d1fae40d-6ff3-4352-a151-7cba9d526d58.png)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Fixed in https://github.com/GTNewHorizons/GTplusplus/commit/b010508097905261e62aec3487896e0192178d0c.
