### ISSUE TITLE
items in the input slot of me processing pattern terminal (4->16 mode) will not be doubled using free slots.

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#9014]
### Your GTNH Discord Username

iouter

### Your Pack Version

2.1.1.5

### Your Server

SP

### Your Expectation

try to double pattern in 4 ->16 mode of me processing pattern terminal.

### The Reality

items in the input slot will not be doubled using free slots.

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Florexiz** [comment]
Its feature request rather than bug I believe

**Comment by vovaksenov** [comment]
The expected behavior you described is, while convenient, not how it was implemented, as the doubling is only meant to work for the non-empty slots under 64. Therefore, it is not a bug, but a feature request: you provided your view on what the expected behavior should be changed to.

**Comment by iouter** [comment]
> The expected behavior you described is, while convenient, not how it was implemented, as the doubling is only meant to work for the non-empty slots under 64. Therefore, it is not a bug, but a feature request: you provided your view on what the expected behavior should be changed to.

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/72

**Comment by vovaksenov** [comment]
Haven't seen that one. Sorry👌

**Comment by repo-alt** [comment]
huh, somebody actually uses 4->16 mode

**Comment by boubou19** [comment]
> huh, somebody actually uses 4->16 mode

4 -> 16 mode is handy when you encode recipes like plates into foils.
