### ISSUE TITLE
Overworld gravity bugged

### ISSUE THREAD

**Issue by ronw23** [GTNewHorizons/GT-New-Horizons-Modpack#9015]
### Your GTNH Discord Username

DiscordiaXXIII#6392

### Your Pack Version

2.1.2.0-pre4

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Gravity is messed up for items in the Overworld, haven't checked any other dimensions. 

### The Reality

Items fall very slowly, thrown items much farther but slowly. This seems to be a low gravity effect. Tested this on a brand new world. Character jumps normal height.

### Your Proposal

Items fall/travel as they should.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
confirmed on pre4 on zeta

**Comment by Glease** [comment]
Sounds like a GC problem.
