### ISSUE TITLE
GT++ scrubbers can still be craft

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#9018]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.0Pre3

### Your Server

Single

### Type of Server

Single Player

### Your Expectation

I checked the recipe for GT++ scrubbers.

### The Reality

GT++ scrubbers can still be craft,

### Your Proposal

I think I should delete the recipes because new electric air filters have also been added.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
They may serve different purposes?

**Comment by yukieiji** [comment]
Dream has previously stated that they will remove these recipes.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7656#issuecomment-810029618

As has been said in the comments on that issue, GT++ scrubber is an easy way to remove contamination. So if you want to keep it, I think you need to adjust the recipe.

**Comment by PolkageistHS** [comment]
Do the GT++ scrubbers actually work?  I couldn't get the LV one to remove any pollution.

**Comment by yukieiji** [comment]
If it doesn't actually work, I think it's even more strange that there is a recipe and we can craft it.

**Comment by bombcar** [comment]
These have been fixed and nerfed by half. https://github.com/GTNewHorizons/GTplusplus/pull/68

**Comment by Rubix2048** [comment]
Also, the GT++ scrubbers are used to craft advanced muffler hatches, which *do* work (mostly, they don't consume air filters rn)
