### ISSUE TITLE
Chunks generating without proper vegetation

### ISSUE THREAD

**Issue by ronw23** [GTNewHorizons/GT-New-Horizons-Modpack#9022]
### Your GTNH Discord Username

DiscordiaXXIII#6392

### Your Pack Version

2.1.2.0-pre4

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Picture of dev 3 spawn seed -1, Cherry Blossom Grove biome.
![2021-12-07_12 52 04](https://user-images.githubusercontent.com/918381/145096991-ec48653e-4e8d-49ba-b48a-18c58e57595c.png)

### The Reality

Proper trees, ground vegetation do no generate in new chucks. Harvestcraft gardens, BOP wild crops do. Same seed -1 as previous screenshot

![2021-12-07_12 06 38](https://user-images.githubusercontent.com/918381/145097136-eca7aca6-1dac-4e01-b9e3-1dd06b8284ef.png)

### Your Proposal

Fix chunk generation

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Confirmed happens on latest GC.

Reverted GC and mcdoodle to stable and .... trees are back.

**Comment by bombcar** [comment]
https://github.com/GTNewHorizons/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/mixins/minecraft/ChunkProviderServerMixin.java

It is caused here.

**Comment by bombcar** [comment]
Came from here: https://github.com/GTNewHorizons/MicdoodleCore/blob/8f50086f47d693ea3f88cf762c89d9d4860f1aa0/src/main/java/micdoodle8/mods/miccore/MicdoodleTransformer.java#L516 apparently

**Comment by SinTh0r4s** [comment]
Gonna take care of it tomorrow morning

**Comment by bombcar** [comment]
https://cdn.discordapp.com/attachments/603348502637969419/917937335834914836/Galacticraft-1.7.10-3.0.32-GTNH-7-gc5c3daa.jar this jar should fix this
