### ISSUE TITLE
Рroposal: GT_FluidDislpayItem implementing IFluidContainerItem

### ISSUE THREAD

**Issue by slprime** [GTNewHorizons/GT-New-Horizons-Modpack#9025]
### Your GTNH Discord Username

slprime

### Your Pack Version

latest

### Your Proposal

Transform GT_FluidDislpayItem into a fluid container by implementing IFluidContainerItem, like so:

![code](https://user-images.githubusercontent.com/31038811/145178160-32c9d333-0192-4b50-8772-a2f43b9bed09.png)

Example of getting fluid from GT_FluidDislpayItem:
![code-2](https://user-images.githubusercontent.com/31038811/145178385-a917337e-0e63-4a78-a883-6ec9cf836a58.png)

### Your Goal

If we implement IFluidContainerItem  in GT_FluidDisplayItem then NEI will be able to detect the item as fluid and save it correctly.

Pardon my persistence, I am still willing to fix fluids in NEI bookmarks. 

### Your Vision

This fixes GT++ fluids in NEI bookmarks and allows for future usage of the fake GT_FluidDisplayItem to configure filters.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by slprime** [comment]
issue: https://github.com/GTNewHorizons/NotEnoughItems/issues/18

**Comment by slprime** [comment]
An example of other mods accepting an item as a fluid container

![fluid-container](https://user-images.githubusercontent.com/31038811/145181239-01fa9c08-ffae-43ce-8613-f6b868f8b9ae.gif)
I understand what it isn't fake item.

**Comment by draknyte1** [comment]
Silly proposal. GT_FluidStackDisplay just needs to not use Fluid IDs. It’s simple to do and the added feature of using them to set filters isn’t needed when literally everything else exists. They’re fake *display* items, nothing more.

**Comment by Glease** [comment]
Would be a nice thing to have. You will be able to directly set the amount of fluid instead of using a volumetric flask.

gregtech does register this item to item registry, otherwise it cannot be sent over network to client.

**Comment by GlodBlock** [comment]
why sudden close it?
