### ISSUE TITLE
New railcraft tanks recipe conflicts

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#9026]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.0-pre4

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Craft wireless receiver and transmitter (circuit 1, stainless steel plate and ev sensor/emitter()

### The Reality

Got
![image](https://user-images.githubusercontent.com/29033773/145193795-bdb28a85-23e8-41a0-b5b6-19b4600912f1.png)

### Your Proposal

Change circuits of railcraft tanks

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
will change the tank circuit to 20, 21, 22 or so
