### ISSUE TITLE
GT covers limited to 1 plate

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#9028]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.0-pre4

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Craft gt cover

### The Reality

Most of gt covers now only craftable from wrought iron plate. Was iron, wrought iron and aluminum before. Not sure this was done intentionally
![image](https://user-images.githubusercontent.com/29033773/145194568-a5b5b70f-e696-4b59-8c8f-42a19fdf0252.png)

### Your Proposal

Return missing recipes if this wasn't intentional.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Sounds like a conflict with something. Probably related to #9026.

**Comment by Dream-Master** [comment]
yea will check

**Comment by Glease** [comment]
Should be fixed now.
