### ISSUE TITLE
Hidden Hot Hot Hot quest

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#9029]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.0-pre4

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Claim reward for accidentally completed quest in multiblocks tab, but there was none, only tab showing unclaimed reward

### The Reality

Questbook have hidden quest that you can complete, but can't see or claim reward
![image](https://user-images.githubusercontent.com/29033773/145195333-0261a409-8d18-4341-a28a-634b2f182d6c.png)

### Your Proposal

Make quest visible

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
This quest probably should have SECRET visibility instead.

**Comment by Dream-Master** [comment]
yea i will go over the quest again.
