### ISSUE TITLE
Recipe collision on grinding ball from EnderIO

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9030]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0pre4

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Don't collide

### The Reality

Collision

![image](https://user-images.githubusercontent.com/533931/145230425-dbb333b6-dcfb-4b45-b1c0-3edff8451567.png)

![image](https://user-images.githubusercontent.com/533931/145230468-fbfa52d8-2f4c-4970-8565-6190be7eeb8c.png)

### Your Proposal

This appears to be on grinding balls made out of some GT++ alloys, but I didn't check all of them. 

Found using https://github.com/D-Cysteine/nei-custom-diagram/wiki/Diagrams#gregtech-recipe-debugger

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
use another circuit config on grind balls

**Comment by bombcar** [comment]
found 'em, testing 5
