### ISSUE TITLE
Long distance item pipes not working

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#9031]
### Your GTNH Discord Username

Hyperic88#3351

### Your Pack Version

2.1.2.0-pre4

### Your Server

Zeta

### Your Expectation

When using LDIP they do not connect with GT item pipes nor EIO conduits no more. So if conveyor is set on input side and set to import stuff it should send stuff.

### The Reality

Although conveyor is set, it doesnt send items through. Cinobi checked that with same "success"

### Your Proposal

Check upon the LDIPs, they were working fine before the update to 2.1.2.0-pre4

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Hyperic88 it must be a min distance about 64 Blocks. Shorter Distances not work anymore

**Comment by Hyperic88** [comment]
> @Hyperic88 it must be a min distance about 64 Blocks. Shorter Distances not work anymore

ah, was using it to lower lags. Ok then

**Comment by Dream-Master** [comment]
i think to avoid using this pipes for short distances i suggest change to 128 Blocks but i am not sure

**Comment by Glease** [comment]
16 chunks is too far. oil field is 8x8 and ore vein is 3x3, both of which significantly smaller than 16 chunks.

**Comment by Dream-Master** [comment]
ok

**Comment by bombcar** [comment]
Can we tooltip this or something? It will affect many people.

**Comment by Dream-Master** [comment]
sure lets do a tooltip
