### ISSUE TITLE
make ender quarry and ender pumps placeable in world

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9032]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0-pre4

### Original Request

make ender quarry and ender pumps placeable in world

### Responding developer

@boubou19

### Context

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/71879199f271f1bad49e215186c7e6c80eacf687/config/GTNewHorizons/blocklimiter.cfg#L10-L14

### Developer's Promise

Change it so non OP players can place the EQ and EP in at least a dim.

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
in comparison, we have this on the officials to avoid players depletting the OW and destroying the main island on the officials:
```
    # Define your Blocks here. Syntax is: [modID]:[BlockID];[DimID];... if you don't add a Dimension (e.g. minecraft:dirt) it will be denied in every dimension [default: ]
    S:BlockList <
        ExtraUtilities:enderThermicPump;0;0;1;
        ExtraUtilities:enderQuarry;0;0;1;
     >
```

**Comment by Dream-Master** [comment]
@boubou19 we can use enforced configs on servers so the setting will be change on us server every time we upload another file. But wha we should enable this in ow?

**Comment by bombcar** [comment]
Right now by default the config denies it in every dimension

**Comment by Dream-Master** [comment]
then the cfg is wrong

**Comment by boubou19** [comment]
> @boubou19 we can use enforced configs on servers so the setting will be change on us server every time we upload another file. But wha we should enable this in ow?

My point is to remove them from blacklist, or add actual dimensions if you want them to be in the blacklist, because right now they can't be used anywhere.
