### ISSUE TITLE
Bonemeal to white dye recipe collides with bonemeal to tiny pile

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9033]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Server

MMCC

### Type of Server

Thermos

### Your Expectation

![image](https://user-images.githubusercontent.com/533931/145250695-f999b5ad-fb8c-40d1-8526-1033196bdcda.png)

### The Reality

![image](https://user-images.githubusercontent.com/533931/145250658-c97944e7-81ea-4932-ac04-a0171fc739ce.png)

It became nine dust as soon as it hit my inventory.

### Your Proposal

Make it so they don't overlap, or turn the dye one into shaped?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
if I put the bonemeal in lower left it works

**Comment by YannickMG** [comment]
Bonemeal to white dye doesn't appear to be a recipe  anymore.

**Comment by lonevox** [comment]
It's still a recipe, just that tiny pile is prioritized. I tried crafting white dye from bonemeal because it says you can in NEI, but in reality you can't. The bonemeal to white dye recipe should be removed.
