### ISSUE TITLE
Investigate source of hidden recipe duplications

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#9034]
### Your GTNH Discord Username

glee8e#7174

### Your Pack Version

2.1.1.4-pre4

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Not adding duplicates to GT recipe map

### The Reality

GregTech has built in checks against recipe duplication. [I added some code](https://github.com/GTNewHorizons/GT5-Unofficial/tree/do-not-merge/detect-conflicts) to make it log this instead of silently ignore.

Here is a sample dump (CSV format) from current dev pack, but you can just produce one on your own using instructions listed in that branch.

[GTRecipes.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7678232/GTRecipes_2.zip)

### Your Proposal

Investigate why these conflicts show up, and remove the source of conflicts if it makes sense.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
In addition to this, I am finding that a lot of recipes are still in .zs scripts, of mods we now have source for.

Those should probably be merged into the source where possible.

**Comment by draknyte1** [comment]
![gtrecipedupes](https://user-images.githubusercontent.com/3060479/145255082-2533e52b-c6a1-4ed8-a178-f045175a06ec.png)


heh, open office also fails x]

**Comment by Glease** [comment]
Updated, now with headers and a properly ending quote. [GTRecipes_2.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7678232/GTRecipes_2.zip)

**Comment by bombcar** [comment]
[recipes.db.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7678374/recipes.db.zip)

Here's an SQLite database from the import (some lines didn't import but only like maybe 40-80).
