### ISSUE TITLE
Recipe collision on tiny-dust removal change

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9038]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0pre4

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

We apparently have a number of colliding recipes in the thermal centrifuge now - for example purified crushed fluoride ore:

![image](https://user-images.githubusercontent.com/533931/145267381-7f1f2458-34ab-45f8-ade9-34b0286fd5fc.png)

second is 11.11% change of Fluorite dust.

### The Reality

Also happens for:

 - cryolite (crushed and purified)
 - fluorite (crushed and purified)

### Your Proposal

Fix - if someone can point me to where they are I can track them down.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
cryolite has an issue and i dont know why

**Comment by bombcar** [comment]
> cryolite has an issue and i dont know why

because there's a gt++ cryolite before we added ours

**Comment by Dream-Master** [comment]
ok we should remove this from gt++

**Comment by D-Cysteine** [comment]
This is most likely due to the same cause as:
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8986
 * (well, aside from pig iron being broken too)

Note that the tiny dust change did not cause this issue: prior to it, we still had two distinct recipes. They both returned tiny piles, but the tiny piles were different materials (and post-tiny dust change, the tiny pile and large pile are probably still different materials).

**Comment by bombcar** [comment]
I'm not sure this is GT++'s fault, I completely removed ORES.CRYOLITE from gt++ and ran that version and still got the dupe

**Comment by bombcar** [comment]
I take that back .... let me try a more dramatic removal.

**Comment by bombcar** [comment]
Ok a very hard removal of cryolite fixes this - however I won't do it for fluorite because GT++ apparently actually uses that.

cc: @draknyte1

**Comment by bombcar** [comment]
Dupe of #8986
