### ISSUE TITLE
add OC robot interaction with maintenance hatches

### ISSUE THREAD

**Issue by PoroCoco** [GTNewHorizons/GT-New-Horizons-Modpack#9044]
### Your GTNH Discord Username

PoroCoco#4636

### Your Pack Version

2.1.1.0

### Your Proposal

Add a way for OpenComputer robots to interact with maintenance hatches, one way could be by allowing the maintenance hatch to get fixed by just right clicking on it with the upcoming toolbox without having to use the GUI.

### Your Goal

Right now it's impossible to have OpenComputer robots build a working gt multiblock machine (unless you have auto-maintenance hatch) as when the structure is complete, you need to fix the maintenance hatch problems and the only way to fix these problems is by right clicking the maintenance hatch and use the GUI. As OC robot can't interact with GUI's you can't have robot build working multiblock stuctures.

### Your Vision

Allowing robot to fix maintenance hatch could open some opportunities for new OC programs in lower power tiers but as a downside it would also make the auto maintenance hatch less usefull. I don't think that this would make the auto maintenance hatch 100% useless as writing and automating a program to handle repairs would come with it's own set of problems.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Do we just want to build it or also maintain it afterwards? A new hatch could be added more expensive than the normal but cheaper than the auto that would start out “repaired” (as if you duct taped it) but would then live like a normal one and need maintained later.

**Comment by PoroCoco** [comment]
A hatch that would start as repaired would also work, and limits the interaction only to build new mutiblock and not maintain them. If it's possible I think it's a good comprise.

**Comment by repo-alt** [comment]
That hatch should also "remember" current problems in item form, othewise robot would just wrench it and place back.

**Comment by bombcar** [comment]
> That hatch should also "remember" current problems in item form, othewise robot would just wrench it and place back.

Heh I was thinking it becomes a normal “when used” but don’t know how hard that is to code  

OC robot is what tier vs auto maintenance?

**Comment by PoroCoco** [comment]
OC robot are HV, even maybe MV. But for the auto maintenance hatch I'm not sure but it's at least LUV and I think it may be using ZPM parts. I can't check the recipe right now I'll confirm it when I can.

**Comment by PoroCoco** [comment]
To confirm : OC robots are HV and auto maintenance hatches are LuV.

**Comment by bombcar** [comment]
If letting people tierskip a bit on automaintenace hatches gets them using OC, I think it's worth it tbh. It's not like these things going into maintenance that often.
