### ISSUE TITLE
upgrade tainted magic after 2.1.2.0

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9048]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0pre5

### Your Proposal

We should upgrade tainted magic to latest, but it has changes we'd have to work through.

https://github.com/bombcar/Tainted-Magic has pulled in upstream and merged most of our changes (save the Chinese lang file)

### Your Goal

We should be on the latest and greatest, it has some nice stuff.

### Your Vision

For reference: 

![image](https://user-images.githubusercontent.com/533931/145436505-a4023025-70c5-459b-99ad-02a430f16fcf.png)

is removed

and

![image](https://user-images.githubusercontent.com/533931/145436560-bb969a76-86e4-47af-99fb-51ca58fb9275.png)

is added, see https://discord.com/channels/181078474394566657/603348502637969419/918357410232537139 for some experimentation what leads us to push this until after 2.1.2.0

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
@bombcar is still relevant?

**Comment by Dream-Master** [comment]
yes we need to update tainted magic to the last available version

**Comment by Chaoschaot232** [comment]
Nice that this is already on your side :)

Any feedback how far you are and what problems are currently encountered?

Is it possible, on own risk, to update TM at my own while fixing stuff on my own? Would be for private play only as long as there are no other breaks maybe?

Can't wait until any release, could also deal with an EA/Testversion and provide feedback later 😊

**Comment by bombcar** [comment]
I think the upstream is merged now

**Comment by Dream-Master** [comment]
but not in the Pack. Scripts need to be done first
