### ISSUE TITLE
Mega EBF not running recipes correctly

### ISSUE THREAD

**Issue by TheBrochacho** [GTNewHorizons/GT-New-Horizons-Modpack#9053]
### Your Pack Version

2.1.2.0-pre4

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Mega EBF was working fine in the previous version.

### The Reality

Mega EBF recipes are not running correctly. I frequently see stuff like this:
![image](https://user-images.githubusercontent.com/16054364/145479611-89ebfb2a-935a-4c1c-bd77-24025dfe802f.png)
Sometimes the progress will be `0s / 1s` instead. This is happening with an input bus full of rhodium-plated palladium dust, but it's happened with other dusts as well. 
Pollution is also not being output into the chunk even though the mufflers on top are producing smoke particles. Sometimes I can get the recipe to run properly by changing the MEBF circuit prioritization from 11 to 1 and vice versa. 

### Your Proposal

please take a look as to why this is happening.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
If digging around in the code perhaps this could be refactored:

https://github.com/GTNewHorizons/bartworks/blob/768c63bde49b22c58f97a53a8b9d25698a82460b/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java#L297

To do it once on startup and then just apply from then on

**Comment by Glease** [comment]
@GlodBlock You might be interested in this.

**Comment by GlodBlock** [comment]
cuz i mistaken the fluid with item id in fluid check, so the ciruit 11 will have wired behavior but 1 is correct. alreadly fixed in https://github.com/GTNewHorizons/bartworks/pull/70
