### ISSUE TITLE
charcoal pile igniter skips processing time + autodetect structure/autostart not working

### ISSUE THREAD

**Issue by ken-long** [GTNewHorizons/GT-New-Horizons-Modpack#9055]
### Your GTNH Discord Username

madman678#2714

### Your Pack Version

2120 pre5

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

try to do?
operate charcoal pile igniter

expect to happen?
at least 250 seconds of processing time, based on size of the pile (this was working before I upgraded to dev)

### The Reality

- build structure, charcoal pile unresponsive
- rClick controller with soft mallet
- receive processing enabled message in chat
- dig dirt blocks
- brittle charcoal has arrived 🎉

### Your Proposal

charcoal goes brrr but it's supposed to take at least a few minutes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
this is almost certainly a side effect of pollution handling

**Comment by ken-long** [comment]
also, I still have pollution turned off, if relevant at all

**Comment by bombcar** [comment]
If you could, can you save your world (copy it if needed) and try it with pollution on?

**Comment by ken-long** [comment]
seems to be same behavior w/ EnablePollution=true
![Inked2021-12-10_12 18 08_LI](https://user-images.githubusercontent.com/6040204/145615333-6aa2c870-e647-4bd3-9126-52aa9da8ea23.jpg)
![Inked2021-12-10_12 18 15_LI](https://user-images.githubusercontent.com/6040204/145615334-89573103-f963-4069-8bac-90f3a0a3db03.jpg)

**Comment by bombcar** [comment]
Thank you! I'll take a look and see if It's something obvious.

**Comment by ken-long** [comment]
![2021-12-11_19 21 27](https://user-images.githubusercontent.com/6040204/145695890-7d8313ca-f9bd-4a64-a00f-7f87085f7c52.png)

wrenching and replacing made it work again, whoops (thought I'd already done that but guess not)

**Comment by ken-long** [comment]
hello, tad bit more followup here:

the "Progress: ## s / ### s" indicator finished... so I dug out the doorway, only to find the logs still there!

then, replaced dirt, r-clicked with soft hammer -- that nudged it into working instantly again.

presumably, if I fill with logs and activate, this would happen again?

**Comment by YannickMG** [comment]
Fixed by GTNewHorizons/GT5-Unofficial#859

**Comment by YannickMG** [comment]
Or at least the 100 seconds problem is fixed and hopefully the other broken behavior was a consequence of that unintended state.
