### ISSUE TITLE
Filter in NEI by energy tier

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9056]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.20pre5

### Your Proposal

Allow NEI to filter by energy tier. 

The simple way would be a slider I assume with ULV and MAX on the ends and you can pick a minimum and a maximum. 

### Your Goal

When in LV you could set LV max and ignore the other recipes you can’t make yet (maybe you’d have to go to MV to reveal EBF recipes) and when you got to MV you could set min and max to MV and it would show everything 33-128 volts so you could easily see the new recipes. 

### Your Vision

This would greatly reduce the number of recipes to scroll through at each new tier 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by YannickMG** [comment]
NEI already includes code for a dropdown multiselection. It might be nice to add such a dropdown to the GT default handler to select whatever energy tiers one is interested in, ideally without having to enter a config screen.
