### ISSUE TITLE
Stencil Table and NEI overlap when Fullscreen is on

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/GT-New-Horizons-Modpack#9057]
### Your GTNH Discord Username

N4M3_T1TL3_P3R20N#3173

### Your Pack Version

2.1.1.0 & pre5

### Your Server

Zeta, SP

### Type of Server

Don't know

### Your Expectation

I opened the stencil table up and some of the stencils are covered by the NEI and they shouldn't be.

### The Reality

The stencils closest to the stenciling area are covered by the NEI,
When I have Fullscreen on and open up the Stencil table it overlaps with NEI. 
(Screen size 1920x1080)

Fullscreen off (zeta)
![GT_ New Horizons 12_10_2021 9_02_26 PM](https://user-images.githubusercontent.com/95777939/145661646-f9df3764-d401-481d-8d13-b9d4d6f5bab5.png)
Fullscreen on (zeta)
![2021-12-10_21 03 17](https://user-images.githubusercontent.com/95777939/145661663-cc1b569a-e096-43cb-a0dd-1b1903e16c06.png)
Fullscreen on (SP 2.1.1.0)
![2021-12-10_20 51 19](https://user-images.githubusercontent.com/95777939/145661715-0b7d5eb1-ed8c-4a07-af3e-c097c9747e28.png)
Fullscreen off (SP 2.1.1.0)
![GT_ New Horizons 12_10_2021 9_13_06 PM](https://user-images.githubusercontent.com/95777939/145661874-f3c2fde8-a58d-4d99-bb0d-c6d127454156.png)

### Your Proposal

Make it so the NEI and Stencil table don't overlap when Fullscreen is on.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Looks like the region it claimed is not big enough for certain GUI scale or resolution.
