### ISSUE TITLE
Add more Slots for Backpacks (1 is not enough)

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#9064]
### Your GTNH Discord Username

TrainerSnow#5086

### Your Pack Version

any

### Your Proposal

Even tho there are multiple Tiers of Backpacks, i found myself to carry around multiple max tier Backpacks around. This is annoying, because the slot, which allows me toopen a backpack through a keybind only stores one Backpack. More Slots are needed.

### Your Goal

Add maybe 3 or 5 more Backpack slots, with corresponding keybind to open the Backpack thats laid into it.

### Your Vision

Would make it easier to carry around all the tools that are needed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
As a note - there is also the Adventure Backpack (smaller) which has its own slot. I believe thaumcraft also has a few things.

At some point too many backpacks becomes a danger - too much NBT information on your player character can corrupt the save (compressed chest of AE2 drives is the most famous).

When you get to that point, things like ender chests are safer.
