### ISSUE TITLE
Add Earthquake to the Server List

### ISSUE THREAD

**Issue by FlandreS** [GTNewHorizons/GT-New-Horizons-Modpack#9065]
### IP

aragil.ddns.net

### Whitelist Status

No Whitelist

### Server Name

Earthquake GTNH (USA West)

### Primary Language(s)

English

### Region(s) of Service

West Coast USA

**Comment by Dream-Master** [comment]
@FlandreS is the server off. Can see it anymore.

**Comment by FlandreS** [comment]
It's intended to go up with a fresh world once added to a numbered release (2.1.2.1?) that way the initial players who join aren't co-existing with others on LuV+ tech.

Plugins and configs are ready to go once 2.1.2.1 is out, then I'll open it up again.

**Comment by Dream-Master** [comment]
ok. 2.1.2.1 will be available soon.
