### ISSUE TITLE
Dupe 1080k Sp Coolant Cell in Mega Vacuum Freezer

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#9066]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.2.0-pre5

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

Tried to cool a 1080k Sp Coolant Cell in Mega Vacuum Freezer 

### The Reality

do not disappear from the input bus.
I put only 6 and get 16 every 260 seconds (endlessly)

### Your Proposal

Multiply the dupe and add a way, to disassemble 1080k into component parts

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Does this happen before? say, on 2.1.1.4?

**Comment by Sphyix** [comment]
Doesn't happen on 2.1.1.0, tested

**Comment by Glease** [comment]
@GlodBlock could this be somehow related to your recipe optimization?

**Comment by GlodBlock** [comment]
i will check it soon
