### ISSUE TITLE
No pollution mitigation is available until MV

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#9071]
### Your GTNH Discord Username

Pao

### Your Pack Version

2.1.2.0Pre3

### Your Proposal

The new Electric Air Filter can be crafted in early/mid LV but it requires a small turbine to work, which can't be crafted until you get an MV assembler and extruder.  Alk didn't get the GT++ scrubbers working with the latest update, so now MV is the earliest you can mitigate pollution. 

### Your Goal

Either allow the Electric Air Filter to use the Basic Iron/Bronze Turbines from GT++ or get the GT++ scrubbers working.  Or make (some of) the small turbines craftable at LV?  

### Your Vision

Pollution mitigation plz

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
> ### Your GTNH Discord Username
> Pao
> 
> ### Your Pack Version
> 2.1.2.0Pre3
> 
> ### Your Proposal
> The new Electric Air Filter can be crafted in early/mid LV but it requires a small turbine to work, which can't be crafted until you get an MV assembler and extruder. Alk didn't get the GT++ scrubbers working with the latest update, so now MV is the earliest you can mitigate pollution.
> 
> ### Your Goal
> Either allow the Electric Air Filter to use the Basic Iron/Bronze Turbines from GT++ or get the GT++ scrubbers working. Or make (some of) the small turbines craftable at LV?
> 
> ### Your Vision
> Pollution mitigation plz
> 
> ### Final Checklist
> * [x]  I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying _I like this change please reconsider adding it_ will prompt us to investigate and reopen it once we confirm your report.
> * [x]  I understand this change request may not attract enough attention and thus not be implemented.
> * [x]  I understand this change request may be rejected due to other community members think it's inappropriate.
> * [x]  I believe this feature would make the pack better.

nope you can make turbines in lv. I add some

**Comment by PolkageistHS** [comment]
Which ones?  I'm using 2.1.2.0 from a couple hours ago and they all still take MV.  Even Small Iron still needs 100 EU/t.

**Comment by boubou19** [comment]
the current 2.1.2.0 version has the NHCoreMod 1.7.10-1.9.07, turbine got reworked in 1.7.10-1.9.08

**Comment by PolkageistHS** [comment]
Alrighty. To the Jenkins I go!

**Comment by PolkageistHS** [comment]
Yup, Steel, Iron, and Wrought Iron are craftable at LV with 1.9.08.  Thanks!
