### ISSUE TITLE
WIldcard Meta & furnace fix don't mix

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#9073]
### Your Pack Version

dev

### Your Server

all

### Problem

Potatoes won't smelt because they're registered with the wildcard meta, and don't compare equals to actual potatoes in the game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
yeet potatoes 🥔 way too op anyway. You can make six different foods with them.
