### ISSUE TITLE
Revert the SiO2 removal

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9074]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.1.0

### Your Proposal

Revert the SiO2 removal.
Reasons:
If the plan was to reduce the use of electrolyzer like someone said on the discord channel, this change did nothing as oxygen still needs to be obtained by electrolyzing dusts and silicon needs to be obtained by electrolyzing dusts, but in smaller quantities.

If the plan was to reduce the amount of silicon, this change did nothing aswell as there's an EBF recipe for silicon ingots using 1 silicon dioxide and 2 carbon, giving 1 silicon ingot.
There's a big issue with this alternative recipe, as this is the easiest way to get silicon, but in the ingot form.
A lot of recipes require silicon dust for the alloys, or silicon dust to make silicon boules in an EBF
This means smelting silicon -> macerating it -> smelting it again, that looks pretty bad.

If the plan was to reduce the amount of oxygen at lower tiers, why not make the process more expensive to run and reduce by 2x or 4x the amount of oxygen?

Another issue I'm personally facing now, I use a TON of silicon dust for the octuple solars, Colen mentioned something around the 16 million silicon, and a good part of it is for wafers, so that means smelting and macerating, let's say, 10 million silicon.
This adds an unnecessary load to the server, as it adds 2 more steps to get silicon dust from silicon dioxide.

At the end, I don't see why this change was made.
Please revert it or explain better why this removal is necessary.
Thanks.

### Your Goal

Yes

### Your Vision

Yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
#9072
