### ISSUE TITLE
Assist server hosts in mitigating Log4Shell

### ISSUE THREAD

**Issue by YannickMG** [GTNewHorizons/GT-New-Horizons-Modpack#9076]
### Your GTNH Discord Username

Yannick#5937

### Your Pack Version

n/a

### Your Proposal

Please either distribute a Log4Shell fix with the server pack releases or add explicit instructions to the wiki's  [Server Setup](https://gtnh.miraheze.org/wiki/Server_Setup) page.

### Your Goal

Log4Shell will soon stop being novel and people will need to be told about it.  Creating this issue in case this hasn't already been taken care of.

### Your Vision

Secure and informed players are happy players.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
If Healer is not in 2.1.2.0 serverpack I’ll add a note to the wiki.

**Comment by YannickMG** [comment]
I see Healer-1.1.0.jar in http://downloads.gtnewhorizons.com/ServerPacks/GTNewHorizonsServer-1.7.10-2.1.2.0.zip so I assume this can be closed.
