### ISSUE TITLE
start server Injection plugin DreamCoreMod fail

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#9080]
### Your Pack Version

2.1.2.0

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Actions

start server

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7702788/fml-server-latest.log)

Injection plugin DreamCoreMod fail

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
server archive isn't ready yet, it's a known bug, please wait for an official announcement saying the update is ready
