### ISSUE TITLE
Crash when starting the game 

### ISSUE THREAD

**Issue by Dragonsoule** [GTNewHorizons/GT-New-Horizons-Modpack#9084]
### Your Pack Version

2.1.1.0

### Your Server

private 

### Your Actions

When i try to start up the game it just crashes. 
I put optifine in the Modsfolder and updated fastcraft to 1.25 

works fine for my fiancé it just doesn't for me

Exitcode -1

### Crash Report

[crash-2021-12-13_16.38.43-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7705195/crash-2021-12-13_16.38.43-client.txt)
[crash-2021-12-13_16.51.23-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7705196/crash-2021-12-13_16.51.23-client.txt)
[crash-2021-12-13_17.04.58-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7705197/crash-2021-12-13_17.04.58-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Hit up discord and use the bot command !tesselating

**Comment by boubou19** [comment]
make sure your chunkloading mode is set to default:
![image](https://user-images.githubusercontent.com/12850933/145848974-d130a08e-8f1e-4f61-b8cd-9b58ab821ffa.png)

**Comment by bombcar** [comment]
To be precise for those finding this in search, default chunkloading must be set. If you cannot get into game to fix, edit `optionsof.txt` and set:

`ofChunkLoading:0`
