### ISSUE TITLE
Add a real-world hydrogen production process

### ISSUE THREAD

**Issue by kenken244** [GTNewHorizons/GT-New-Horizons-Modpack#9087]
### Your GTNH Discord Username

Kenken244#9849

### Your Pack Version

2.1.1.4

### Your Proposal

many people have been complaining about the production of hydrogen and I noticed that the pack is missing the most common way industrial hydrogen is produced in real life. the process would be as follows:

instead of producing carbon dust. distilling cracked fuels should produce "oil residuals" which can be separated (centrifuged?) into Hydrogen and Carbon Monoxide in a 1:1 ratio. then, the  [water gas shift reaction](https://en.wikipedia.org/wiki/Water%E2%80%93gas_shift_reaction) should be added to the game, my suggestion is that in the chemical reactor, 1B of CO and 12B of steam can quickly be converted into 1B of CO2 and 1B H2. if this is too powerful, then perhaps it should require a chemical plant and a catalyst

### Your Goal

it adds some realism into the pack in a way that will make the game more interesting.

### Your Vision

add an interesting Real-life way of producing hydrogen, and also give some more utility to distillation tower based setups which currently are a bit weak. it also would add some use to recycling CO from EBF and pollution filters, which currently most people just void

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
Definitely a good idea to quickly get a lot of hydrogen while also being realistic. 

Also, helium is one of the possible byproducts of oil processing, and IRL getting it from underground sources is the main way we have of obtaining it, but it's worse than getting it from liquid air or, even better than that, yellow stonelillies. I've considered making a ticket about this.

**Comment by kenken244** [comment]
Helium is already available as a byproduct from refinery gas, and irl most of our hellion is sourced from rare underground deposits, so if it is needed you could add helium as a rare underground fluid deposit in the overworld.

**Comment by Pxx500** [comment]
I don't see any reason for adding this to the game since we already have methane+water -> a lot of hydrogen and some carbon monoxide

As much as I like realism I'm not sure why would oil residuals which are very big molecules be centrifuged into two light gasses, reaction like that definitely shouldn't take place in a centrifuge.
WGSR could be added but it would just buff methane+water even more and it's pretty good already so I'd say there's no need
