### ISSUE TITLE
Steam Grinder broken in 2.1.2.0

### ISSUE THREAD

**Issue by YannickMG** [GTNewHorizons/GT-New-Horizons-Modpack#9091]
### Your GTNH Discord Username

Yannick#5937

### Your Pack Version

2.1.2.0

### Your Server

private server

### Type of Server

Open To LAN

### Your Expectation

The Steam Grinder should require and accept Steam Hatch, Input Bus (Steam) and Output Bus (Steam) to fully form.

### The Reality

At the present time, the Steam Grinder only appears to accept and require Bronze Plated Bricks. It can form, but only in an entirely useless manner.

![does-not-form](https://user-images.githubusercontent.com/5321549/145932392-b185b51a-e0a0-42e3-815c-1861c4876142.png)
![requirements](https://user-images.githubusercontent.com/5321549/145932396-d7da9e6a-31fb-4f2a-aece-03cdc713c376.png)
![nothing-but-bricks](https://user-images.githubusercontent.com/5321549/145932386-f30d99d5-545e-409b-b507-495e2888f12a.png)

### Your Proposal

Please restore it's functionality.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
cuz alk forced to cast `GT_MetaTileEntity_Hatch_InputBus` to the steam input bus and breaks shit, let her fix her own stuff

**Comment by Dream-Master** [comment]
Who needs a steam grinder ? 😎

**Comment by Kiyanox** [comment]
Steam grinder is such a nice machine in early game. I'd like to see it being functional again 😄

**Comment by draknyte1** [comment]
> cuz alk forced to cast `GT_MetaTileEntity_Hatch_InputBus` to the steam input bus and breaks shit, let her fix her own stuff

Very polite reply, but honestly I’d rather you didn’t try fix it anyway.

**Comment by draknyte1** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/68.

**Comment by Dream-Master** [comment]
yes forms now
