### ISSUE TITLE
Change voltage required to fluid extract redstone alloy nuggets.

### ISSUE THREAD

**Issue by QQLazors** [GTNewHorizons/GT-New-Horizons-Modpack#9092]
### Your GTNH Discord Username

QQLazors#1845

### Your Pack Version

2.1.2.0

### Your Proposal

Change voltage required for redstone alloy nugget in fluid extractor from 4 EU/t to 36 EU/t.

### Your Goal

Change to match recent change to redstone alloy ingots.
Redstone alloy ingots now take 36 EU/t, so that it requires a MV fluid extractor, however it can be circumvented by cutting the ingot into nuggets and extracting those.

### Your Vision

Removes a circumvention of voltage tiers.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by QQLazors** [comment]
![2021-12-13_23 30 27](https://user-images.githubusercontent.com/10213974/145935050-ef10275a-d83b-4645-b4a0-12d3439c8fe3.png)

**Comment by Dream-Master** [comment]
yes this make no sense . Stupid autogenerated recipes :)

**Comment by TwoTailedFox** [comment]
This has yet to be corrected as of 2.2.0.0-RC2
