### ISSUE TITLE
GT fluid filters completely broken and unusable

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#9096]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

Having a usable server after updates

### The Reality

- Fluid filter covers do not actually allow fluids to pass regardless of settings
- Fluid filter covers reset all their settings after being broken

As a result, all fluid management in my base is completely unusable, and I'm forced from UHV all the way back into early MV methods to be able to start making replacements

### Your Proposal

Roll back Delta, *then* fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
@Glease does it relate to the nbt change of covers you make? in fact someone has found it broken in 2115 or earlier in qq group

**Comment by Glease** [comment]
1. Fluid filter works just fine, at least in my local tests. Not sure what you mean by "do not actually allow fluids to pass regardless of settings". 
2. If you put covers on machines itself instead of pipes, then it used to always corrupt whenever fluid registry do an reindex. Previously only covers on pipes would be migrated over. This change fixed this.
    There *are* ways to fix this it, but it's largely untested. Server operator need to boot the server with backup with a specially built gregtech (2.1.1.0 GT + my NBT changes), and load your base once, then save the world, then replace the chunks in current save. I have produced a jar for boubou to test, but there is no guarantee on whether it would completely secure your stuff.

**Comment by combusterf** [comment]
![2021-12-15_00 42 31](https://user-images.githubusercontent.com/8459776/146096964-d2699ec6-1011-4f3c-86c6-f46027010283.png)
![2021-12-15_00 41 55](https://user-images.githubusercontent.com/8459776/146096973-4a206391-b250-47fb-b814-4febab886898.png)
![2021-12-15_00 41 59](https://user-images.githubusercontent.com/8459776/146096977-def8e2f1-20cd-4ffa-8618-41f6ff24142f.png)

**Comment by combusterf** [comment]
Screenshot of the UI as per requested:
![2021-12-15_15 14 02](https://user-images.githubusercontent.com/8459776/146202566-e404fdba-76b6-4801-9c38-5fa1f69d6ce2.png)

**Comment by combusterf** [comment]
> Fluid filter covers reset all their settings after being broken

This part didn't make the test yet, and it's also being weird about it, based on the patched version on Delta at the time of writing.

Quad pipe with two fluid filters on it, on the east (right of image) and south (left of image) side
![image](https://user-images.githubusercontent.com/8459776/146225320-36739041-74ad-4c60-b4cd-6b9458ccacda.png)


Before settings (east facing):
![image](https://user-images.githubusercontent.com/8459776/146224847-84bd5774-0416-43c1-93bf-af9af570fc62.png)
Before settings (south facing):
![image](https://user-images.githubusercontent.com/8459776/146226237-a6588957-f27a-43ac-af68-b081e8c6722a.png)

After breaking and replacing, east side:
![image](https://user-images.githubusercontent.com/8459776/146226380-6edd8ba6-863d-4213-b789-8a9280d1bbfc.png)
Filter direction and filter fluid have not been preserved

South side:
![image](https://user-images.githubusercontent.com/8459776/146225635-f59e4d8b-2bbe-42f9-841e-806a442cac27.png)
Filter direction and black/whitelist have been reset, but strangely enough *not* the filter fluid

I've tried changing the block flow setting, which also gets cleared on either side. 

Given the above, and the fact that all fluid filters that I have clicking access to in my base have had all their settings reset, I also want to make sure that if I do fix my base, any changes I make are stable across reboots or not, but that's something I can't test without being intrusive to other players

**Comment by Glease** [comment]
Bruh another oversight.

**Comment by Glease** [comment]
To be clear, the data WILL survive a reboot. It just wasn't saving properly when you harvest the block. The linked PR will fix this.

**Comment by combusterf** [comment]
> To be clear, the data WILL survive a reboot. 
It did not.

So I fixed a good chunk of my existing filters yesterday, and they've all reverted after server restart - including breaking the attached pipes into missing textures again:
![image](https://user-images.githubusercontent.com/8459776/146641585-c7678bad-38b6-47c5-a958-33fb986bcf89.png)

**Comment by Glease** [comment]
This is literally impossible. Just test it in single player. Does leaving the save and reentering it remove anything?

**Comment by Glease** [comment]
OK it appears it's only bugged on pipes and not machines. F my life.

**Comment by mhirche** [comment]
> 

Same thing is happening in my base. But not only on server restart. When I fix the pipes and come back a while later it's broken again. Happens also with a chunkloader.

**Comment by bombcar** [comment]
> Same thing is happening in my base. But not only on server restart. When I fix the pipes and come back a while later it's broken again. Happens also with a chunkloader.

yeah is not loading correctly, so world load or chunk load would do it

**Comment by riking** [comment]
#824 fixes this crash, right? When crowbaring a fluid filter on a pipe

```
java.lang.ClassCastException: Cannot cast gregtech.common.covers.GT_Cover_Fluidfilter$FluidFilterData to gregtech.api.util.ISerializableObject$LegacyCoverData
```

**Comment by bombcar** [comment]
> #824 fixes this crash, right? When crowbaring a fluid filter on a pipe
> 
> ```
> java.lang.ClassCastException: Cannot cast gregtech.common.covers.GT_Cover_Fluidfilter$FluidFilterData to gregtech.api.util.ISerializableObject$LegacyCoverData
> ```

yes that is fixed. You can grab the jar from jenkins to confirm if it’s your server.

**Comment by bombcar** [comment]
Using the 2.1.2.1 client zip, I opened my world.

I added a fluid filter cover:

![image](https://user-images.githubusercontent.com/533931/146997387-14280e29-fc9b-44ce-9405-f43d7b5e250a.png)

after reload it was set to:

![image](https://user-images.githubusercontent.com/533931/146997362-1c5cd622-07ca-4d5f-9561-ae6b847d7a64.png)

**Comment by bombcar** [comment]
To be precise this was a Fluid Filter Cover on an LV Output Hatch and it just did it again.
