### ISSUE TITLE
Update 2.1.2.1

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9097]
Issues to be fixed next update:
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9096
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6560
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7176

**Comment by GTNH-Afx237v7** [comment]
Definitely #9053. The Mebf sometimes won’t process items properly, though currently I can’t really describe when and when not. Needs more observation.

**Comment by GTNH-Afx237v7** [comment]
My bad I am on an outdated version of bartworks. Will test again tomorrow and let you know.

**Comment by bombcar** [comment]
The following mods are outdated in the 2.1.2.0 zip:

- [ ] [NEI-Integration](https://github.com/GTNewHorizons/NEI-Integration) (has code fixes)
- [ ] GTNH-o-Plenty
- [ ] [StorageDrawers](https://github.com/GTNewHorizons/StorageDrawers) (got split into five, but the "original" unuqdated one is still there so code is duplicated (seems harmless?)
- [ ] [WitcheryExtras](https://github.com/GTNewHorizons/WitcheryExtras) (has code changes)
- [ ] [BloodMagic](https://github.com/GTNewHorizons/BloodMagic) (has code changes, renamed master)

**Comment by bombcar** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9098

**Comment by bombcar** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9091

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9100
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9101

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9102

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9105
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9106

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9111

**Comment by boubou19** [comment]
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9113

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9110

**Comment by Dream-Master** [comment]
- [ ] Un-hide Air Filter Quest

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9122

**Comment by bombcar** [comment]
- [ ] https://github.com/GTNewHorizons/GT5-Unofficial/pull/802

**Comment by yukieiji** [comment]
- [ ]  #9018

**Comment by GTNH-Afx237v7** [comment]
So I updated to latest bartworks (bartworks 1.7.10-0.5.31) from jenkins which includes the fix mentioned by Glodblock but the mebf still behaves the same. I tried to process aluminium dust to ingots with circuit 11 prioritized but as soon as the oxygen level in the input hatch goes too low the mebf will run at 1eu/t and not process anything.

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9143

**Comment by glowredman** [comment]
- https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8577
- https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/7 (buildscript review already done)
- "Dyson Sphere Ground Unit" component recipes

**Comment by Dream-Master** [comment]
> * [ ]  [[RFC] Dyson Swarm Ground Unit Balance & Recipes #8577](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8577)
> * [ ]  [Feature: Dyson Swarm (No Recipes / Balance yet!) Galaxy-Space-GTNH#7](https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/7) (buildscript review already done)
> * [ ]  "Dyson Sphere Ground Unit" component recipes

guess this one is not the goal for 2.1.2.1 more for 2.1.2.x or i am wrong. I want to release 2.1.2.1 very soon

**Comment by glowredman** [comment]
You're right, thought this was for 2.1.3.0...

**Comment by bombcar** [comment]
- [ ] [Changelog-2.1.1.0.txt ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/Changelog-2.1.1.0.txt) Update or remove outdated changelog

**Comment by bombcar** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9128

**Comment by GlodBlock** [comment]
> Re: #9053 So I updated to latest bartworks (bartworks 1.7.10-0.5.31) from jenkins which includes the fix mentioned by Glodblock but the mebf still behaves the same. I tried to process aluminium dust to ingots with circuit 11 prioritized but as soon as the oxygen level in the input hatch goes too low the mebf will run at 1eu/t and not process anything.

could try it again with the lastest gregtech?

**Comment by bombcar** [comment]
- [ ] https://github.com/GTNewHorizons/AppleCore/pull/8 Make sure we have the latest AppleCore

**Comment by boubou19** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9161

**Comment by bombcar** [comment]
- [ ] Update version number to 2.1.2.1 (menu screen had 2.1.2.0-rc1)

**Comment by bombcar** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9065

**Comment by draknyte1** [comment]
- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9173

**Comment by Dream-Master** [comment]
- [ ] Fix adv coke oven recipes

**Comment by bombcar** [comment]
> [x] [Fixinmixin AppleCore#8](https://github.com/GTNewHorizons/AppleCore/pull/8) Make sure we have the latest AppleCore

My fix for this got lost, but it's back in https://github.com/GTNewHorizons/harvestcraft/pull/15

**Comment by Dream-Master** [comment]
> * [ ]  [Advanced Coke Oven Making Coal Coke from Charcoal #9093](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9093)

maybe i can try to remove all recipes from this block in code

**Comment by GTNH-Afx237v7** [comment]
With regards to removing tiny piles there is still a platline recipe that does not have a full-dust alternative:
![grafik](https://user-images.githubusercontent.com/64365566/148364686-e0fe2664-25f9-4e4e-8b0f-998af8659993.png)
This is Rhodium Sulfate outputting 10 tiny piles of Leach Residue dust.
