### ISSUE TITLE
Data Sticks corrupted/not working after the Update

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/GT-New-Horizons-Modpack#9098]
### Your GTNH Discord Username

Shadii#2898

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

.

### The Reality

Certain Data Sticks are not working since the update, even tho the assline recipe wasnt changed. 
Probably the new auto update feature.
After rescanning the thing and inserting the new datastick, the recipe worked with the same items and fluids

Broken Datastick:
![javaw_2021-12-14_14-28-05](https://user-images.githubusercontent.com/46688121/146008186-6e9b9f33-e083-410d-a32a-b3608c1615ac.png)

Rescanned working Datastick:
![javaw_2021-12-14_14-28-14](https://user-images.githubusercontent.com/46688121/146008238-7e6be7d3-0df1-4e9a-85ea-ec1c1649681b.png)

Again, the recipe didnt change at all

### Your Proposal

Fix it pwetty pwease uwu, i dont like broken assembly lines after every update

EDIT: Affected Data Sticks I discovered so far are UHV Motor, Wetware Mainframe, UHV Energy Hatch and UHV Pump. will most likely find more
### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
the output of the `/mt hand`
```
<gregtech:gt.metaitem.01:32708>.withTag({"a9:0": {id: 6544 as short, Count: 64 as byte, Damage: 29471 as short}, "a9:1": {id: 6544 as short, Count: 64 as byte, Damage: 29635 as short}, author: "Assembling Line Recipe Generator", f0: {FluidName: "molten.solderingalloy", Amount: 2880}, f1: {FluidName: "ic2coolant", Amount: 10000}, title: "Wetware Mainframe Construction Data", f2: {FluidName: "radon", Amount: 2500}, output: {id: 6546 as short, Count: 1 as byte, Damage: 32095 as short}, eu: 300000, "0": {id: 1953 as short, Count: 2 as byte, Damage: 4425 as short}, "1": {id: 6546 as short, Count: 2 as byte, Damage: 32094 as short}, "2": {id: 6546 as short, Count: 16 as byte, Damage: 32147 as short}, "3": {id: 6546 as short, Count: 16 as byte, Damage: 32027 as short}, pages: ["Construction plan for 1 Wetware Mainframe. Needed EU/t: 300000 Production time: 100", "Input Bus 1: 2 Tritanium Frame Box", "Input Bus 2: 2 Wetware Supercomputer", "Input Bus 3: 16 ZPM Voltage Coil", "Input Bus 4: 16 Advanced SMD Capacitor", "Input Bus 5: 16 Advanced SMD Resistor", "Input Bus 6: 16 Advanced SMD Transistor", "Input Bus 7: 16 Advanced SMD Diode", "Input Bus 8: 48 Random Access Memory Chip", "Input Bus 9: 64 1x superconductorzpm Wire", "Input Bus 10: 64 Polysiloxane FoilOr 64 Thin Styrene-Butadiene Rubber Sheet", "Input Hatch 1: 2880L Molten Soldering Alloy", "Input Hatch 2: 10000L IC2 Coolant", "Input Hatch 3: 2500L Radon"], "4": {id: 6546 as short, Count: 16 as byte, Damage: 32024 as short}, "5": {id: 6546 as short, Count: 16 as byte, Damage: 32026 as short}, "6": {id: 6546 as short, Count: 16 as byte, Damage: 32025 as short}, "7": {id: 6546 as short, Count: 48 as byte, Damage: 32039 as short}, "Data.Recipe.Hash": "Hash.0", "8": {id: 1953 as short, Count: 64 as byte, Damage: 2420 as short}, a9: 2, "9": {id: 6544 as short, Count: 64 as byte, Damage: 29471 as short}, time: 2000})
```

**Comment by boubou19** [comment]
looks like tectech datasticks aren't properly checked, and the assline invalidate them even if you rescan them manually
