### ISSUE TITLE
Battlegear(?) and Railcraft Enchants lack descriptions when holding Sneak key

### ISSUE THREAD

**Issue by Sederien** [GTNewHorizons/GT-New-Horizons-Modpack#9099]
### Your GTNH Discord Username

Sederien#4540

### Your Pack Version

2.1.2.0

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://user-images.githubusercontent.com/66249229/146010176-9d26dc8c-210b-4efa-aace-353aefa57dbf.png)

When using sneak, read the enchantment description. Such as with the vanilla enchantment, Sharpness:

![image](https://user-images.githubusercontent.com/66249229/146010340-36056910-3f14-4588-9e32-14b555ed6b07.png)

### The Reality

![image](https://user-images.githubusercontent.com/66249229/146010387-407c00e2-46a1-4b77-9a74-42af5823720c.png)

No description shown. Also the case for another found book as seen here:

![image](https://user-images.githubusercontent.com/66249229/146010522-3f8e75cb-1e10-4d1e-afc1-9ab39206bc22.png)

### Your Proposal

See if there is a description area that these enchantments can be added to the text fields so they do describe when sneak key is pressed.

A list of known modded enchants: https://feed-the-beast.fandom.com/wiki/Enchantments

(Apologies for fandom link.)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Offhand do you know of a _working_ modded enchant?

**Comment by Sederien** [comment]
Not offhand, no.

**Comment by bombcar** [comment]
Something is adding that for enchants, it's not a normal vanilla thing. Now to figure out what is.

**Comment by Sederien** [comment]
When next at home, I can load up the creative mode and see if any modded enchant books are registering with descriptions, but likely a search for the line "hold the sneak key to view description" (of whatever is in the screenshot I made above will hint as to which mod or file is looking for descriptions. After that I assume it's attached to IDs of the enchants themselves.
________________________________

**Comment by bombcar** [comment]
Hmmmm https://github.com/GTNewHorizons/waila/commit/73cf13421285a87b6fb5c9dc690442e3474e3e4c

**Comment by bombcar** [comment]
Doesn't seem to be that. This is tricky to track down, could be one of the ARR mods.

**Comment by bombcar** [comment]
It's WAWLA, now to extend it 

https://github.com/GTNewHorizons/WAWLA/blob/master/src/main/resources/assets/wawla/lang/en_US.lang

**Comment by Sederien** [comment]
Cool! To my knowledge both railcraft and Battlegear enchants are in and enabled as they were found on books in the world, but probably worth scanning the wiki link above for any other mods  included in GTNH that are enabled.
________________________________

**Comment by Sederien** [comment]
A cursory scan of the wiki link and the mods I know to be in GTNH (whether enabled or not) review the following missing descriptions:

Name | Max Level | Item | Mod | Effects
-- | -- | -- | -- | --
Fiery Aura | II | Armour | Twilight Forest | Inflicts ongoing fire damage on mobs that attack a player wearing the armour.
-- | -- | -- | -- | --
Reading | I | Helmet | Bibliocraft | Grants the ability to read text just like the reading glasses, tinted  glasses, or monocle. This is a rare enchantment that can only be  created by enchanting a book or crafting.
-- | -- | -- | -- | --
Wrecking | V | Crowbar | Railcraft | Exclusively for crowbars. Increases damage (works the same as Sharpness).
-- | -- | -- | -- | --
Implosion | V | Crowbar | Railcraft | Exclusively for crowbars. Increases damage dealt to Creepers.
-- | -- | -- | -- | --
Destruction | III | Crowbar | Railcraft | Exclusively for crowbars. Deconstructs blocks in a wide area.
-- | -- | -- | -- | --
Consuming | I | Tools | Forbidden Magic | Deletes Stone and Dirt when mined
-- | -- | -- | -- | --
Corrupting |   | Pickaxe | Forbidden Magic | Drops Corrupted shards instead of Normal Shards
-- | -- | -- | -- | --
Last Stand | II | Armor | OpenBlocks | Will prevent the player from dying by using experience as the health  source. If the player has 0.5 hearts left, their future damage will use  Experience first. The first tier will use about 5-7 levels each hit,  while the second tier will use about 1 level each hit.
-- | -- | -- | -- | --
Unstable | III | Armor | OpenBlocks | Needs gunpowder in Inventory. On Boots: When you drop from 5 blocks or more (and use up 1, 2, or 4  gunpowder based on level) you will take no fall damage. Unstable III  will also cause Block damage. Any other armor: When attacked, the player  will explode (without getting damaged by it) and use 2, 4, and 8  gunpowder respectively.
-- | -- | -- | -- | --
Bash Weightless | Battlegear Shield | Mine & Blade Battlegear 2 | Reduce the stamina taken per shield bash
-- | -- | -- | -- | --
Bash Power | Battlegear Shield | Mine & Blade Battlegear 2 | Increase the push force on shield bash (repulse further the opponent)
-- | -- | -- | -- | --
Bash Damage| Battlegear Shield | Mine & Blade Battlegear 2 | Adds damage to a shield bash
-- | -- | -- | -- | --
Shield Efficiency | Battlegear Shield | Mine & Blade Battlegear 2 | Reduce the stamina taken on shield block
-- | -- | -- | -- | --
Shield Recovery | Battlegear Shield | Mine & Blade Battlegear 2 | Increase the stamina recovery rate when holding the shield, but not blocking
-- | -- | -- | -- | --
Bow Luck  | Bow | Mine & Blade Battlegear 2 | Adds a chance to increase loot on killing
-- | -- | -- | -- | --
Bow Drawnback | Bow | Mine & Blade Battlegear 2 | Lower charge time for the bow, without effecting the FOV

**Comment by bombcar** [comment]
Cool - I’ll take a look tomorrow (got it to build and ran some tests)

**Comment by Sederien** [comment]
![image](https://user-images.githubusercontent.com/66249229/146137245-32500409-66cc-4eeb-a093-d4c3a27ff902.png)

Found another not yet mentioned...

**Comment by bombcar** [comment]
Not all the books show in NEI in creative, so this may be an iterative process.

**Comment by Sederien** [comment]
> Not all the books show in NEI in creative, so this may be an iterative process.

Shouldn't be that bad anymore... I did a dump through NEI, so here's the full list:


<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ben/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ben/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



ID | Unlocalised name | Type | Min Level | Max Level | Class
-- | -- | -- | -- | -- | --
0 | enchantment.protect.all | armor | 1 | 4 | net.minecraft.enchantment.EnchantmentProtection
1 | enchantment.protect.fire | armor | 1 | 4 | net.minecraft.enchantment.EnchantmentProtection
2 | enchantment.protect.fall | armor_feet | 1 | 4 | net.minecraft.enchantment.EnchantmentProtection
3 | enchantment.protect.explosion | armor | 1 | 4 | net.minecraft.enchantment.EnchantmentProtection
4 | enchantment.protect.projectile | armor | 1 | 4 | net.minecraft.enchantment.EnchantmentProtection
5 | enchantment.oxygen | armor_head | 1 | 3 | net.minecraft.enchantment.EnchantmentOxygen
6 | enchantment.waterWorker | armor_head | 1 | 1 | net.minecraft.enchantment.EnchantmentWaterWorker
7 | enchantment.thorns | armor_torso | 1 | 3 | net.minecraft.enchantment.EnchantmentThorns
8 | enchantment.enderio.soulBound | all | 1 | 1 | crazypants.enderio.enchantment.EnchantmentSoulBound
9 | enchantment.enderzoo.witherArrow | bow | 1 | 1 | crazypants.enderzoo.enchantment.EnchantmentWitherArrow
10 | enchantment.enderzoo.witherWeapon | weapon | 1 | 1 | crazypants.enderzoo.enchantment.EnchantmentWitherWeapon
14 | enchantment.damage.radioactivity | weapon | 1 | 5 | gregtech.api.enchants.Enchantment_Radioactivity
15 | enchantment.damage.endermen | weapon | 1 | 5 | gregtech.api.enchants.Enchantment_EnderDamage
16 | enchantment.damage.all | weapon | 1 | 5 | net.minecraft.enchantment.EnchantmentDamage
17 | enchantment.damage.undead | weapon | 1 | 5 | net.minecraft.enchantment.EnchantmentDamage
18 | enchantment.damage.arthropods | weapon | 1 | 5 | net.minecraft.enchantment.EnchantmentDamage
19 | enchantment.knockback | weapon | 1 | 2 | net.minecraft.enchantment.EnchantmentKnockback
20 | enchantment.fire | weapon | 1 | 2 | net.minecraft.enchantment.EnchantmentFireAspect
21 | enchantment.lootBonus | weapon | 1 | 3 | net.minecraft.enchantment.EnchantmentLootBonus
32 | enchantment.digging | digger | 1 | 5 | net.minecraft.enchantment.EnchantmentDigging
33 | enchantment.untouching | digger | 1 | 1 | net.minecraft.enchantment.EnchantmentUntouching
34 | enchantment.durability | breakable | 1 | 3 | net.minecraft.enchantment.EnchantmentDurability
35 | enchantment.lootBonusDigger | digger | 1 | 3 | net.minecraft.enchantment.EnchantmentLootBonus
45 | enchantment.xpboost | breakable | 1 | 3 | com.enderio.core.common.enchant.EnchantXPBoost
46 | enchantment.autosmelt | breakable | 1 | 1 | com.enderio.core.common.enchant.EnchantAutoSmelt
48 | enchantment.arrowDamage | bow | 1 | 5 | net.minecraft.enchantment.EnchantmentArrowDamage
49 | enchantment.arrowKnockback | bow | 1 | 2 | net.minecraft.enchantment.EnchantmentArrowKnockback
50 | enchantment.arrowFire | bow | 1 | 1 | net.minecraft.enchantment.EnchantmentArrowFire
51 | enchantment.arrowInfinite | bow | 1 | 1 | net.minecraft.enchantment.EnchantmentArrowInfinite
61 | enchantment.lootBonusFishing | fishing_rod | 1 | 3 | net.minecraft.enchantment.EnchantmentLootBonus
62 | enchantment.fishingSpeed | fishing_rod | 1 | 3 | net.minecraft.enchantment.EnchantmentFishingSpeed
64 | enchantment.wg.gemstonePotency | all | 1 | 3 | witchinggadgets.common.magic.WGEnchantGemPotency
65 | enchantment.wg.gemstoneBrittle | all | 1 | 3 | witchinggadgets.common.magic.WGEnchantGemBrittle
66 | enchantment.cluster | digger | 1 | 4 | fox.spiteful.forbidden.enchantments.EnchantmentCluster
67 | enchantment.wrath | weapon | 1 | 5 | fox.spiteful.forbidden.enchantments.EnchantmentWrath
68 | enchantment.greedy | weapon | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentGreedy
69 | enchantment.consuming | digger | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentConsuming
70 | enchantment.educational | weapon | 1 | 5 | fox.spiteful.forbidden.enchantments.EnchantmentEducational
71 | enchantment.wg.invisibleGear | all | 1 | 2 | witchinggadgets.common.magic.WGEnchantInvisibleGear
72 | enchantment.voidtouched | digger | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentVoid
73 | enchantment.impact | digger | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentImpact
74 | enchantment.wg.unveiling | all | 1 | 1 | witchinggadgets.common.magic.WGEnchantUnveiling
75 | enchantment.wg.stealth | armor | 1 | 5 | witchinggadgets.common.magic.WGEnchantStealth
76 | enchantment.wg.backstab | weapon | 1 | 3 | witchinggadgets.common.magic.WGEnchantBackstab
77 | enchantment.binding | weapon | 1 | 2 | flaxbeard.thaumicexploration.enchantment.EnchantmentBinding
78 | enchantment.nightVision | armor_head | 1 | 1 | flaxbeard.thaumicexploration.enchantment.EnchantmentNightVision
79 | enchantment.disarm | weapon | 1 | 3 | flaxbeard.thaumicexploration.enchantment.EnchantmentDisarm
80 | enchantment.projectred.expansion.fuel_efficiency | armor_torso | 1 | 4 | mrtjp.projectred.expansion.EnchantmentFuelEfficiency
81 | enchantment.wg.rideProtect | armor_head | 1 | 1 | witchinggadgets.common.magic.WGEnchantRideProtect
82 | enchantment.wg.soulbound | all | 1 | 1 | witchinggadgets.common.magic.WGEnchantSoulbound
98 | enchantment.elderKnowledge | weapon | 1 | 5 | tb.common.enchantment.EnchantmentElderKnowledge
99 | enchantment.eldritchBane | weapon | 1 | 5 | tb.common.enchantment.EnchantmentEldritchBane
100 | enchantment.magicTouch | weapon | 1 | 3 | tb.common.enchantment.EnchantmentMagicTouch
101 | enchantment.tainted | weapon | 1 | 3 | tb.common.enchantment.EnchantmentTainted
102 | enchantment.vaporising | weapon | 1 | 3 | tb.common.enchantment.EnchantmentVaporising
103 | enchant.cofh.holding | all | 1 | 4 | cofh.core.enchantment.EnchantmentHolding
104 | enchant.cofh.multishot | bow | 1 | 4 | cofh.core.enchantment.EnchantmentMultishot
125 | enchantment.corrupting | digger | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentCorrupting
126 | enchantment.bash.weightless | all | 1 | 3 | mods.battlegear2.enchantments.BaseEnchantment
127 | enchantment.bash.power | all | 1 | 5 | mods.battlegear2.enchantments.BaseEnchantment
128 | enchantment.bash.damage | all | 1 | 3 | mods.battlegear2.enchantments.BaseEnchantment
129 | enchantment.shield.usage | all | 1 | 5 | mods.battlegear2.enchantments.BaseEnchantment
130 | enchantment.shield.recover | all | 1 | 4 | mods.battlegear2.enchantments.BaseEnchantment
131 | enchantment.bow.loot | bow | 1 | 1 | mods.battlegear2.enchantments.BaseEnchantment
132 | enchantment.bow.charge | bow | 1 | 1 | mods.battlegear2.enchantments.BaseEnchantment
153 | enchantment.haste | armor | 1 | 3 | thaumcraft.common.lib.enchantment.EnchantmentHaste
154 | enchantment.repair | all | 1 | 2 | thaumcraft.common.lib.enchantment.EnchantmentRepair
160 | enchantment.SpecialMobs.painBow | bow | 1 | 3 | toast.specialMobs.EnchantmentSpecial
161 | enchantment.SpecialMobs.painSword | weapon | 1 | 3 | toast.specialMobs.EnchantmentSpecial
162 | enchantment.SpecialMobs.plagueBow | bow | 1 | 3 | toast.specialMobs.EnchantmentSpecial
163 | enchantment.SpecialMobs.plagueSword | weapon | 1 | 3 | toast.specialMobs.EnchantmentSpecial
164 | enchantment.SpecialMobs.poisonBow | bow | 1 | 2 | toast.specialMobs.EnchantmentSpecial
165 | enchantment.SpecialMobs.poisonSword | weapon | 1 | 1 | toast.specialMobs.EnchantmentSpecial
166 | enchantment.ttinkerer:dispersedStrike | weapon | 1 | 5 | thaumic.tinkerer.common.enchantment.EnchantmentDispersedStrikes
167 | enchantment.ttinkerer:shatter | digger | 1 | 5 | thaumic.tinkerer.common.enchantment.EnchantmentShatter
168 | enchantment.ttinkerer:finalStrike | weapon | 1 | 5 | thaumic.tinkerer.common.enchantment.EnchantmentFinalStrike
169 | enchantment.ttinkerer:focusedStrike | weapon | 1 | 5 | thaumic.tinkerer.common.enchantment.EnchantmentFocusedStrikes
170 | enchantment.ttinkerer:pounce | armor_legs | 1 | 5 | thaumic.tinkerer.common.enchantment.EnchantmentPounce
171 | enchantment.ttinkerer:shockwave | armor_feet | 1 | 5 | thaumic.tinkerer.common.enchantment.EnchantmentShockwave
172 | enchantment.ttinkerer:tunnel | digger | 1 | 5 | thaumic.tinkerer.common.enchantment.EnchantmentTunnel
173 | enchantment.ttinkerer:valiance | weapon | 1 | 5 | thaumic.tinkerer.common.enchantment.EnchantmentValiance
180 | enchantment.draconicevolution.reaperEnchant | weapon | 1 | 5 | com.brandon3055.draconicevolution.common.magic.EnchantmentReaper
190 | enchantment.railcraft.crowbar.wrecking | digger | 1 | 5 | mods.railcraft.common.items.enchantment.EnchantmentDamageRailcraft
191 | enchantment.railcraft.crowbar.implosion | digger | 1 | 5 | mods.railcraft.common.items.enchantment.EnchantmentDamageRailcraft
192 | enchantment.railcraft.crowbar.destruction | digger | 1 | 3 | mods.railcraft.common.items.enchantment.EnchantmentDestruction
196 | Reading | armor_head | 1 | 1 | jds.bibliocraft.EnchantmentReading
197 | Eternal Compass | all | 1 | 1 | jds.bibliocraft.EnchantmentDeathCompass
200 | gadomancy.enchantment.revealer | armor_head | 1 | 1 | makeo.gadomancy.common.enchantments.EnchantmentRevealer
211 | enchantment.openblocks.explosive | armor | 1 | 3 | openblocks.enchantments.EnchantmentExplosive
212 | enchantment.openblocks.laststand | armor | 1 | 2 | openblocks.enchantments.EnchantmentLastStand
213 | enchantment.openblocks.flimflam | all | 1 | 4 | openblocks.enchantments.EnchantmentFlimFlam
220 | enchantment.ttinkerer:ascentBoost | armor_legs | 1 | 4 | thaumic.tinkerer.common.enchantment.EnchantmentAscentBoost
221 | enchantment.ttinkerer:slowFall | armor_feet | 1 | 3 | thaumic.tinkerer.common.enchantment.EnchantmentSlowFall
222 | enchantment.ttinkerer:autoSmelt | digger | 1 | 1 | thaumic.tinkerer.common.enchantment.EnchantmentAutoSmelt
223 | enchantment.ttinkerer:desintegrate | digger | 1 | 1 | thaumic.tinkerer.common.enchantment.EnchantmentDesintegrate
224 | enchantment.ttinkerer:quickDraw | bow | 1 | 2 | thaumic.tinkerer.common.enchantment.EnchantmentQuickDraw
225 | enchantment.ttinkerer:vampirism | weapon | 1 | 2 | thaumic.tinkerer.common.enchantment.EnchantmentVampirism



</body>

</html>

**Comment by Sederien** [comment]
I did some filtering. The following enchantments are the enchantment descriptions NOT in the WAWLA lang file (all others have a description):

ID | Unlocalised name | Type | Min Level | Max Level | Class | IN WAWLA
-- | -- | -- | -- | -- | -- | --
8 | enchantment.enderio.soulBound | all | 1 | 1 | crazypants.enderio.enchantment.EnchantmentSoulBound | 0
9 | enchantment.enderzoo.witherArrow | bow | 1 | 1 | crazypants.enderzoo.enchantment.EnchantmentWitherArrow | 0
10 | enchantment.enderzoo.witherWeapon | weapon | 1 | 1 | crazypants.enderzoo.enchantment.EnchantmentWitherWeapon | 0
14 | enchantment.damage.radioactivity | weapon | 1 | 5 | gregtech.api.enchants.Enchantment_Radioactivity | 0
15 | enchantment.damage.endermen | weapon | 1 | 5 | gregtech.api.enchants.Enchantment_EnderDamage | 0
45 | enchantment.xpboost | breakable | 1 | 3 | com.enderio.core.common.enchant.EnchantXPBoost | 0
46 | enchantment.autosmelt | breakable | 1 | 1 | com.enderio.core.common.enchant.EnchantAutoSmelt | 0
64 | enchantment.wg.gemstonePotency | all | 1 | 3 | witchinggadgets.common.magic.WGEnchantGemPotency | 0
65 | enchantment.wg.gemstoneBrittle | all | 1 | 3 | witchinggadgets.common.magic.WGEnchantGemBrittle | 0
66 | enchantment.cluster | digger | 1 | 4 | fox.spiteful.forbidden.enchantments.EnchantmentCluster | 0
67 | enchantment.wrath | weapon | 1 | 5 | fox.spiteful.forbidden.enchantments.EnchantmentWrath | 0
68 | enchantment.greedy | weapon | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentGreedy | 0
69 | enchantment.consuming | digger | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentConsuming | 0
70 | enchantment.educational | weapon | 1 | 5 | fox.spiteful.forbidden.enchantments.EnchantmentEducational | 0
71 | enchantment.wg.invisibleGear | all | 1 | 2 | witchinggadgets.common.magic.WGEnchantInvisibleGear | 0
72 | enchantment.voidtouched | digger | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentVoid | 0
73 | enchantment.impact | digger | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentImpact | 0
74 | enchantment.wg.unveiling | all | 1 | 1 | witchinggadgets.common.magic.WGEnchantUnveiling | 0
75 | enchantment.wg.stealth | armor | 1 | 5 | witchinggadgets.common.magic.WGEnchantStealth | 0
76 | enchantment.wg.backstab | weapon | 1 | 3 | witchinggadgets.common.magic.WGEnchantBackstab | 0
77 | enchantment.binding | weapon | 1 | 2 | flaxbeard.thaumicexploration.enchantment.EnchantmentBinding | 0
78 | enchantment.nightVision | armor_head | 1 | 1 | flaxbeard.thaumicexploration.enchantment.EnchantmentNightVision | 0
79 | enchantment.disarm | weapon | 1 | 3 | flaxbeard.thaumicexploration.enchantment.EnchantmentDisarm | 0
80 | enchantment.projectred.expansion.fuel_efficiency | armor_torso | 1 | 4 | mrtjp.projectred.expansion.EnchantmentFuelEfficiency | 0
81 | enchantment.wg.rideProtect | armor_head | 1 | 1 | witchinggadgets.common.magic.WGEnchantRideProtect | 0
82 | enchantment.wg.soulbound | all | 1 | 1 | witchinggadgets.common.magic.WGEnchantSoulbound | 0
98 | enchantment.elderKnowledge | weapon | 1 | 5 | tb.common.enchantment.EnchantmentElderKnowledge | 0
99 | enchantment.eldritchBane | weapon | 1 | 5 | tb.common.enchantment.EnchantmentEldritchBane | 0
100 | enchantment.magicTouch | weapon | 1 | 3 | tb.common.enchantment.EnchantmentMagicTouch | 0
101 | enchantment.tainted | weapon | 1 | 3 | tb.common.enchantment.EnchantmentTainted | 0
102 | enchantment.vaporising | weapon | 1 | 3 | tb.common.enchantment.EnchantmentVaporising | 0
103 | enchant.cofh.holding | all | 1 | 4 | cofh.core.enchantment.EnchantmentHolding | 0
104 | enchant.cofh.multishot | bow | 1 | 4 | cofh.core.enchantment.EnchantmentMultishot | 0
125 | enchantment.corrupting | digger | 1 | 1 | fox.spiteful.forbidden.enchantments.EnchantmentCorrupting | 0
126 | enchantment.bash.weightless | all | 1 | 3 | mods.battlegear2.enchantments.BaseEnchantment | 0
127 | enchantment.bash.power | all | 1 | 5 | mods.battlegear2.enchantments.BaseEnchantment | 0
128 | enchantment.bash.damage | all | 1 | 3 | mods.battlegear2.enchantments.BaseEnchantment | 0
129 | enchantment.shield.usage | all | 1 | 5 | mods.battlegear2.enchantments.BaseEnchantment | 0
130 | enchantment.shield.recover | all | 1 | 4 | mods.battlegear2.enchantments.BaseEnchantment | 0
131 | enchantment.bow.loot | bow | 1 | 1 | mods.battlegear2.enchantments.BaseEnchantment | 0
132 | enchantment.bow.charge | bow | 1 | 1 | mods.battlegear2.enchantments.BaseEnchantment | 0
180 | enchantment.draconicevolution.reaperEnchant | weapon | 1 | 5 | com.brandon3055.draconicevolution.common.magic.EnchantmentReaper | 0
190 | enchantment.railcraft.crowbar.wrecking | digger | 1 | 5 | mods.railcraft.common.items.enchantment.EnchantmentDamageRailcraft | 0
191 | enchantment.railcraft.crowbar.implosion | digger | 1 | 5 | mods.railcraft.common.items.enchantment.EnchantmentDamageRailcraft | 0
192 | enchantment.railcraft.crowbar.destruction | digger | 1 | 3 | mods.railcraft.common.items.enchantment.EnchantmentDestruction | 0
196 | Reading | armor_head | 1 | 1 | jds.bibliocraft.EnchantmentReading | 0
197 | Eternal Compass | all | 1 | 1 | jds.bibliocraft.EnchantmentDeathCompass | 0
200 | gadomancy.enchantment.revealer | armor_head | 1 | 1 | makeo.gadomancy.common.enchantments.EnchantmentRevealer | 0
211 | enchantment.openblocks.explosive | armor | 1 | 3 | openblocks.enchantments.EnchantmentExplosive | 0
212 | enchantment.openblocks.laststand | armor | 1 | 2 | openblocks.enchantments.EnchantmentLastStand | 0
213 | enchantment.openblocks.flimflam | all | 1 | 4 | openblocks.enchantments.EnchantmentFlimFlam | 0

**Comment by Sederien** [comment]
Updated file to use with missing descriptions all added.

[en_US.lang.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7720171/en_US.lang.txt)
