### ISSUE TITLE
Electric air filter tooltips miss localized block names

### ISSUE THREAD

**Issue by ZuOverture** [GTNewHorizons/GT-New-Horizons-Modpack#9106]
### Your GTNH Discord Username

AnCorp#8466

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

Shift-hover Electric Air Filters T1-T3, see multiblock structure description with proper block names

### The Reality

gt.blockcasingsNH.0.name (its actually "air filter turbine casing")
gt.blockcasingsNH.1.name ("air filter vent casing")
same for higher tiers

### Your Proposal

fix references in tooltip? casing names in NEI are correct.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
do you play on russian lang file?

**Comment by bombcar** [comment]
strange, they're in the code

```
        GT_LanguageManager.addStringLocalization(getUnlocalizedName() + ".0.name", "Air Filter Turbine Casing");//adding
        GT_LanguageManager.addStringLocalization(getUnlocalizedName() + ".1.name", "Air Filter Vent Casing");//adding
        GT_LanguageManager.addStringLocalization(getUnlocalizedName() + ".2.name", "Pyrolyse Oven Casing");//adding
        GT_LanguageManager.addStringLocalization(getUnlocalizedName() + ".3.name", "Advanced Air Filter Turbine Casing");//adding
        GT_LanguageManager.addStringLocalization(getUnlocalizedName() + ".4.name", "Advanced Air Filter Vent Casing");//adding
        GT_LanguageManager.addStringLocalization(getUnlocalizedName() + ".5.name", "Super Air Filter Turbine Casing");//adding
        GT_LanguageManager.addStringLocalization(getUnlocalizedName() + ".6.name", "Super Air Filter Vent Casing");//adding
```
