### ISSUE TITLE
Magnum Torch 971 from Extra Utilities is not working

### ISSUE THREAD

**Issue by JustBenji** [GTNewHorizons/GT-New-Horizons-Modpack#9108]
### Your GTNH Discord Username

Benji#0586

### Your Pack Version

2.1.2.0

### Your Server

Private Multiplayer

### Type of Server

Other MCPC+ fork

### Your Expectation

Item Magnum Torch
Item ID 971 
Mod Extra Utilities 
Function: Stop mob spawning is 64 block radius

Issue:
In version 2.1.2.0 mobs are spawning regardless of the Magnum Torch

Tested in;
Multiplayer
Private server
DIM0 (Overworld)
Tried breaking and placing again, didn't work.

### The Reality

In version 2.1.2.0 mobs are spawning regardless of the Magnum Torch

### Your Proposal

Fix issue

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
known bug, if you want to fix it, remove amdiforge from the server mods.
