### ISSUE TITLE
Can't load pre 2.1.2.0 worlds on singleplayer 

### ISSUE THREAD

**Issue by PoroCoco** [GTNewHorizons/GT-New-Horizons-Modpack#9109]
### Your GTNH Discord Username

PoroCoco#4636

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Using the technic launcher.
Tried to load my old world created in 2.1.1.0 and I just end up on the main menu after loading. Even by closing the game and the launcher, there still is a java program running in the background using a lot of memory. However I can generate new worlds without issues.
Tried with a clean install of 2.1.2.0 and I still have the problems. 
The bug is coming from Visual Prospecting version visualprospecting-1.7.10-1.0.24b.dirty and also with the version visualprospecting-1.7.10-1.0.24b.

### Crash Report

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7713617/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@PoroCoco try to remove vp folder and let them regenertae.

**Comment by boubou19** [comment]
When you load a map, it has a small delay where you normally see the main menu again. But when you load 2.1.2.0 for the first time, as i said in the announcement, VP must scan all the chunks of every dim. So it might take a while, be patient, and check for the progress through the console.

**Comment by RUMisthepower** [comment]
I had the same problem. I've deleted VisualProspecting mod and I could load my 2.1.1.0 world in this 2.1.2.0 update

**Comment by eigenraven** [comment]
The VP initial scan is much faster now and shows a proper progrss bar so this shouldn't happen anymore
