### ISSUE TITLE
Storage Bus Interaction with Jabba Barrels broken

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/GT-New-Horizons-Modpack#9110]
### Your GTNH Discord Username

Shadii#2898

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

.

### The Reality

Storage Busses dont display the actual amount of items stored in a barrel anymore. 

![javaw_2021-12-14_19-08-00](https://user-images.githubusercontent.com/46688121/146055572-680bfd3b-60cf-4a8f-aa24-c03c31616434.png)

![2021-12-14_19-08-16](https://user-images.githubusercontent.com/46688121/146055612-745d953a-bcaf-4a4c-8cb8-96e6b01f4d11.png)

as you can see, the storage bus can only display one stack of the stored item. This is extremely inconvenient as the autocrafting doesnt detect the actual available amount of items either.

### Your Proposal

Revert the interaction between storage busses and Jabba barrels to how it was in 2.1.1.0

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
JABBA got its AE2 integration via MFR2 deep storage unit api it included in its jar. Since it's now an optional dependency it is no longer recognized as a special container by AE2.

**Comment by boubou19** [comment]
crap, can we make it back?

**Comment by repo-alt** [comment]
Probably it would be trivial to add Jabba as dependency to AE2 and copy/paste DSU integration with some renaming
