### ISSUE TITLE
GT++ coke oven and extruder multis don't form after the update

### ISSUE THREAD

**Issue by crszpth** [GTNewHorizons/GT-New-Horizons-Modpack#9112]
### Your GTNH Discord Username

Crszpth#2445

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

On 2.1.1.0 the advanced coke oven and the industrial extruder were working and forming correctly 

### The Reality

After the 2.1.2.0 update the controllers give the "Incomplete structure" error

### Your Proposal

Tried the jar #139 fix on jenkins and the multis are still not forming. My guess is that the structure checkfix needs to be extended to the industrial coke oven and the extruder multis

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Check your casing count for extruder.

Coke oven needs 8 casings and only acceptd
```
if (aMetaTileEntity instanceof GT_MetaTileEntity_Hatch_InputBus){
				return addToMachineList(aTileEntity, aBaseCasingIndex);
			} else if (aMetaTileEntity instanceof GT_MetaTileEntity_Hatch_Maintenance){
				return addToMachineList(aTileEntity, aBaseCasingIndex);
			} else if (aMetaTileEntity instanceof GT_MetaTileEntity_Hatch_Energy){
				return addToMachineList(aTileEntity, aBaseCasingIndex);
			} else if (aMetaTileEntity instanceof GT_MetaTileEntity_Hatch_OutputBus) {
				return addToMachineList(aTileEntity, aBaseCasingIndex);
			} else if (aMetaTileEntity instanceof GT_MetaTileEntity_Hatch_Muffler) {
				return addToMachineList(aTileEntity, aBaseCasingIndex);
			} else if (aMetaTileEntity instanceof GT_MetaTileEntity_Hatch_Input) {
				return addToMachineList(aTileEntity, aBaseCasingIndex);
			} else if (aMetaTileEntity instanceof GT_MetaTileEntity_Hatch_Output) {
				return addToMachineList(aTileEntity, aBaseCasingIndex);
			}
```

**Comment by boubou19** [comment]
did you checked with the structurelib blueprints? they have stricter forming conditions now. Just managed to get one to form an industrial extruder and the industrial coke oven on 2120.

**Comment by draknyte1** [comment]
> did you checked with the structurelib blueprints? they have stricter forming conditions now. Just managed to get to form an industrial extruder and the industrial coke oven on 2120.

Some are genuinely broken though Boubs.

**Comment by boubou19** [comment]
![2021-12-14_20 56 18](https://user-images.githubusercontent.com/12850933/146070381-ce636aeb-e61b-4e91-b2ac-2466a016deb0.png)
![2021-12-14_20 57 11](https://user-images.githubusercontent.com/12850933/146070385-77a70273-d56f-4e89-b16c-c8c71fca3728.png)

not those ones at least.

**Comment by crszpth** [comment]
Managed to make the extruder form by moving the muffler off the top layer. Still no luck with the coke oven

**Comment by draknyte1** [comment]
Why is the extruder in the floor? lol

**Comment by boubou19** [comment]
i put the controller on the ground then shift rclicked on it with a stack of structurelib blueprints, i ended up with the blocks being replaced like that

**Comment by draknyte1** [comment]
ICO is definitely broken.
