### ISSUE TITLE
Power Station Control Node becomes incomplete structure

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#9113]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

I found my whole base lack of energy ,after servrial hours afk.
Please check the problems.

### The Reality

The multiblock check has problems.It works just in 2.1.1.4QF2.
After update this happens.I didn't change any setting.

### Your Proposal

I have even no energy to open my AE system now.I can't try to check what happens,for example replace something.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Move the hatches off the top layer, remove the maint. hatch.
Temporary fix.

Fixed in dev.
