### ISSUE TITLE
server.bat crashes after a while after updating to 2.1.2.0 

### ISSUE THREAD

**Issue by CharlieTuna8** [GTNewHorizons/GT-New-Horizons-Modpack#9117]
### Your GTNH Discord Username

Charlie Tuna#7949

### Your Pack Version

2.1.2.0 

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Actions

Update to 2.1.2.0

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7714669/fml-server-latest.log)
[crash-2021-12-14_21.46.54-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7714672/crash-2021-12-14_21.46.54-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by CharlieTuna8** [comment]
Update: removed craftpresence from server mods.

**Comment by bombcar** [comment]
Redownload server pack and try migrating again (clear out dirs)
