### ISSUE TITLE
Storage drawers - Drawer controller - Unable to increase range on drawer controller

### ISSUE THREAD

**Issue by earlbrownie** [GTNewHorizons/GT-New-Horizons-Modpack#9118]
### Your GTNH Discord Username

earlbrownie

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I have a drawer controller with drawers placed at 15 blocks distance away from the controller.
I have changed the config option to both increase the cap on the connected drawer number and the range of accepted drawers to accommodate for the number of drawers on this system.

### The Reality

Any drawer greater than 8 blocks away from the drawer controller are not considered part of the network hence I can't insert items into these drawers from the controller and can only add items to those drawers individually.
 

### Your Proposal

I have tried increasing both caps further (to 32 range and 150 drawer number).
I have tried breaking and replacing the drawer controller and I have tried breaking and replacing the individual drawers as well.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
it's not a bug :) if you want to make it work again, mess with this, but however it wasn't made purely to annoy you: the bigger a drawer cuboid attached to adrawer controller is, the bigger you create lag. AE2 cells are way cheaper than they used to, so consider migrating on AE2 cells instead, for less lags.

**Comment by bombcar** [comment]
For the record the previous values were 2048 total drawers and a radius of 12

**Comment by PolkageistHS** [comment]
from the ticket; 

Your Proposal
I have tried increasing both caps further (to 32 range and 150 drawer number).

**Comment by bombcar** [comment]
Try 2048 number and 12 radius. 150 isn’t that big for a 15 and I suspect it counts “possible” drawrs

**Comment by earlbrownie** [comment]
I've got 98 drawers connected (assuming the counter doesn't consider sub-drawers as their own drawers)
and the further drawer is 12 blocks away

**Comment by earlbrownie** [comment]
aha so figured it out
each time I made a change to the config I didn't break and replace the drawer controller
doing this updated the controller to the new config and fixed the issue
Thank you all for bearing with me on this

**Comment by bombcar** [comment]
Good to know
