### ISSUE TITLE
Soldering alloy needs higher tier versions

### ISSUE THREAD

**Issue by MrJakobLaich** [GTNewHorizons/GT-New-Horizons-Modpack#9119]
### Your GTNH Discord Username

MrJakobLaich#6170

### Your Pack Version

2.1.1.0 (I'm upgrading to 2.1.2.0 in like a day, but AFAIK this isn't in there anyways)

### Your Proposal

Using low grade soldering alloy (probably not very pure) for super complex cleanroom quantu, circuits feels weird, I'd say add some upgrades to soldering alloy.
We have LV, MV, HV, ... motors, circuits, etc

### Your Goal

My goal would be to make soldering alloy more realistic.
As stated above, using some impure, or even pure, soldering alloy in some extremely high tech circuit doesn't make sense to me and feels like it doesn't belong there.

### Your Vision

It would make the higher tier circuits more complex.
After all everything gets major upgrades in every tier, machines, components, ore processing, storage, even food (canned).

So, why do we still use some LV soldering alloy for stargate circuits?
Time to greggify things even more ;)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Basically the same as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8850

**Comment by MrJakobLaich** [comment]
Looks like I'm gonna write this code myself
Wish me luck LMAO

Also, anyone who wants to suggest weird ingredients, add them here as a comment!

**Comment by Elisis** [comment]
In14Sn3Pb2Cd1
Bi8PbInCd1Sn
In3Bi2Sn1
Sn11Pb3In2

**Comment by MrJakobLaich** [comment]
Currently higher tier soldering alloy would get a cost reduction and lower tier would get a cost increase

For now the curve would be like this
![image](https://user-images.githubusercontent.com/40965742/147165732-dcf29aed-6e72-4436-85af-a7f0711be9a1.png)
![image](https://user-images.githubusercontent.com/40965742/147165737-ac195885-e084-4884-9223-f049d0b38846.png)

Soldering alloy tier compared to needed tier:
![image](https://user-images.githubusercontent.com/40965742/147165760-a687cf06-3f1f-40af-a718-0df7631cfbbe.png)

After checking the recipes ingame the curve seems to need some changes but for now it's good enough to work with.

**Comment by DragonStorm25** [comment]
Would every tier of circuit require a new solder? Or would it be possible to use one solder for multiple tiers?

**Comment by bombcar** [comment]
I think the idea is generally to "overlap" so you go through them - if you jump ship early it's harder but more "rewarding" - if you jump at the last minute it's a lot more resources but you might be able to skip a "tier" of solder entirely.

**Comment by bombcar** [comment]
Blue alloy is available at LV and used in EV already / tiberium could also be considered.

**Comment by MrJakobLaich** [comment]
> Would every tier of circuit require a new solder? Or would it be possible to use one solder for multiple tiers?

Sorry, completely forgot about the fact that people ask questions xD
Yes, you could TECHNICALLY use lead for quantum circuits
It would cost you nearly infinite amounts but you COULD do that
It's gonna be so far from worth it that you will still use the necessary tier or max 2 below that ;)
Same goes the other way, you can use a higher tier alloy for lower tier circuits and you get a discount, because it's of higher quality and all that :D

**Comment by GTNH-Colen** [comment]
I think this should be similar to SMDs, not a soldering alloy for each tier but a soldering alloy for a few tiers.

Molten tin
Soldering alloy
Computronium

Perhaps? This could overlap with SMD upgrades as we will soon have 3 tiers of those as well.

**Comment by MrJakobLaich** [comment]
Could be done, would just have to adjust the cost calculation function a bit and tweak some stuff around, but shouldn't be as difficult as finding out that the bit flags are useless in the Materials.java in GT5U LMAO

Anyways, I'd still like it to be more like the circuits, we have so many tiers and a circuit for each tier and every circuit uses it's own soldering alloy
3 tiers feel like it's not that many variations and would probably be hard to balance as you can make one in steam but still use it in MV, so you either use too much early on and it feels too expensive or too little later on and it feels useless and weird that you're still using it

What if instead of one SA (soldering alloy) for each circuit tier we make one SA for each "kind" of circuit, so ULV, LV and MV use one SA, the LV, MV and HV use a different one, etc
That would imo make sense too, that's also what you're suggesting, same SA for multiple tiers but when you "upgrade" you gotta use a different one

I like that idea :D

**Comment by MrJakobLaich** [comment]
Soldering alloy MK3+ will be radioactive

Making tiberium&uranium SA should be dangerous

Low tier SA is grey, high tier SA has colors! :D

**Comment by chochem** [comment]
with the 2 new high tier soldering alloys I am gonna call this fixed in dev.
