### ISSUE TITLE
WarpTheory NullPointerDeref getting player skin

### ISSUE THREAD

**Issue by MMunier** [GTNewHorizons/GT-New-Horizons-Modpack#9120]
### Your GTNH Discord Username

MMunier#1337

### Your Pack Version

2.1.2.0

### Your Server

private

### Your Actions

Nothing

### Crash Report
Not really a crash -- seems to get suck in an infinite exception loop
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7715372/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@D-Cysteine

**Comment by bombcar** [comment]
According to discord this is a custom skin

**Comment by bombcar** [comment]
As a workaroudn you can edit warptheory.cfg and change this line to impossibly high

i:minWarpDoppelgangerEffect=75

**Comment by D-Cysteine** [comment]
Thanks for the stack trace, and sorry for the crashes! The linked PR should fix the NPE, though player skins will probably continue to not work since I don't know of a way to get them without the server.

I am curious if the Openblocks mini-me renders correctly for you? It should be using the same method of getting player skins.

**Comment by MMunier** [comment]
it's fine -- for now we had completely disabled the doppelgänger in Warptheory.cfg using
` B:allowDoppelgangerEffect=false `

And yeah you caught me -- I'm using a 10 year old custom skin ^^.

**Comment by bombcar** [comment]
Can you give us a copy of the skin?

**Comment by D-Cysteine** [comment]
Skin should be completely irrelevant - I think it's just that `MinecraftServer.getServer()` is returning `null` for some reason

**Comment by MMunier** [comment]
Mini-Me seems to work (kinda)
![2021-12-15_03 18 08](https://user-images.githubusercontent.com/43609314/146110937-627fb2e2-a3a8-4344-a2ea-6103893c317c.png)

Mini-Me just suffers from the usual issue that my head is using the second layer so it doesn't get mapped correctly

**Comment by D-Cysteine** [comment]
Thanks for testing that! That's good info - Openblocks might be doing something that I missed that makes it work. Will look more closely.

**Comment by MMunier** [comment]
btw. I've cheated the egg -- what's the correct way of obtaining one?

**Comment by D-Cysteine** [comment]
Default Openblocks has a crafting recipe I think. I'm pretty sure I saw it in the Thaumonomicon so I think GTNH locked it behind some research.

**Comment by D-Cysteine** [comment]
Okay, I think I figured out what OpenBlocks did that I missed, and fixed the issue properly in my PR:
 * https://github.com/GTNewHorizons/WarpTheory/pull/19

I also found out why my testing didn't catch this issue: I'd always test in single-player first, then connect to my dedicated server to test there. But the single-player testing would cache the `GameProfile` in the client and cause it to seem to work on the server =S
The lesson I learned is to always restart the client before testing on a dedicated server.
