### ISSUE TITLE
VisualProspecting Not Prospecting

### ISSUE THREAD

**Issue by TealSeer** [GTNewHorizons/GT-New-Horizons-Modpack#9125]
### Your GTNH Discord Username

gallowsCalibrator#0413

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When right clicking an ore that's part of a vein or I break it with a pick it'd add it to my journeymap. Also, using an ore finding wand and discovering a vein would add it to my map.

### The Reality

Nothing happens, nothing added to journeymap and no feedback in chat or anywhere. Using an ore finder wand won't add it to my map even if I do find a vein

### Your Proposal

Add these veins to my map when they're found. Log is attached
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7716122/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Are you using the default Journeymap gui/theme?

**Comment by TealSeer** [comment]
yes

**Comment by TealSeer** [comment]
....Just fixed it by deleting my visualprospecting folder in .minecraft and loading the world again. Gonna close this.

**Comment by bombcar** [comment]
Let’s leave open until @SinTh0r4s has a chance to take a look. Even if we have a workaround we shouldn’t crash
