### ISSUE TITLE
Change New Graphene Recipe

### ISSUE THREAD

**Issue by Elisis** [GTNewHorizons/GT-New-Horizons-Modpack#9126]
### Your Pack Version

2.1.2.0

### Your Proposal

Either revert or alter the new graphene recipe (involving glowstone wafers) to be less resource heavy.

### Your Goal

 To have them be less of a tax on your EBFing capabilities, and wafers in general.

### Your Vision

IV is already hard enough as it is.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
EBF recipe will be never added back. I had a recipe before use normal wafers but this was changed again.

**Comment by Savallator** [comment]
For balance reasons, may i suggest 2 things:
1. Maybe add a % chance to return the wafer(s)
2. Remove the MT recipe
Otherwise, it is just stupid to have an intricate recipe using wafers and shit, when it is just "Put Carbon into MT lol"...
Imho the energy cost is not really an issue, not when there are strong power options available in EV/IV to completely offset this.

**Comment by Dream-Master** [comment]
> For balance reasons, may i suggest 2 things:
> 
> 1. Maybe add a % chance to return the wafer(s)
> 2. Remove the MT recipe
>    Otherwise, it is just stupid to have an intricate recipe using wafers and shit, when it is just "Put Carbon into MT lol"...
>    Imho the energy cost is not really an issue, not when there are strong power options available in EV/IV to completely offset this.

Mt recipes was removed if not you don’t load the lastest version correct.
Sure make the wafer return at a small change is a good idea .

**Comment by Savallator** [comment]
The 2.1.2.0 release still has it...

**Comment by Sphyix** [comment]
Chances are annoying for the automation, you'd always end up with leftover wafers if you automate it with ae.
Reducing the cost for what the percent chance would give back is better

**Comment by Savallator** [comment]
It is no problem for automation, just need to account for it. Set up a level emitter with "emit to craft item" and start crafting for it.

**Comment by boubou19** [comment]
i'd like to avoid normalizing setups with level emitters, as under specific conditions they are terrible for lag

**Comment by Savallator** [comment]
Then just make a normal recipe and ignore the leftover wafer... no problem with having a few more wafers in your system

**Comment by Sphyix** [comment]
if you want a 50% chance of having the wafer back, reducing the cost by 50% is doing exactly the same thing

**Comment by Sphyix** [comment]
> Mt recipes was removed if not you don’t load the lastest version correct. Sure make the wafer return at a small change is a good idea .

Mt recipe was not removed on latest. This is on delta.
![javaw_QU7slDSMdX](https://user-images.githubusercontent.com/17811922/146255221-d15052e7-2f9a-47cd-8a2d-782c1ad2837b.png)

**Comment by Savallator** [comment]
Every kind of level emitter?
Level emitter causing lag is something people claim sometimes, yet i have never seen any proof, and i have also found some people how should know tell otherwise, like [here](https://www.reddit.com/r/omnifactory/comments/huchia/does_keeping_a_stock_of_items_with_me_level/)... But maybe this should be discussed in a seperate issue...

**Comment by Sphyix** [comment]
> Every kind of level emitter? Level emitter causing lag is something people claim sometimes, yet i have never seen any proof, and i have also found some people how should know tell otherwise, like [here](https://www.reddit.com/r/omnifactory/comments/huchia/does_keeping_a_stock_of_items_with_me_level/)... But maybe this should be discussed in a seperate issue...

It really depends on how big the ME system is, what type of storage is used, etc...
On my ME system, with 80 disks and 2+ infinity chests, it causes so much lag that it's impossible to use

**Comment by Dream-Master** [comment]
> > Mt recipes was removed if not you don’t load the lastest version correct. Sure make the wafer return at a small change is a good idea .
> 
> Mt recipe was not removed on latest. This is on delta. ![javaw_QU7slDSMdX](https://user-images.githubusercontent.com/17811922/146255221-d15052e7-2f9a-47cd-8a2d-782c1ad2837b.png)
> 
> Thing is is so stupidly expensive that even if it stays it's not an issue Making a stack of graphene with americium wafers costs around 15mil eu (counting the cost of smelting and cutting wafers) Compared to MT, 640mil eu for a stack

MT is Minetweaker not Molecular Transformer so you need to adress it :)

**Comment by Savallator** [comment]
Imho 10 million eu is not much in IV.... just dump 1A if IV into it and let it output one graphene per minute, if that runs over night you will have more than enough. Don't forget EV/IV is the Tier with many solid power options like FLuid reactors, lava etc...

**Comment by Dream-Master** [comment]
100 Mio ?  If we remove this i remove plantinuma as well

**Comment by Savallator** [comment]
i would be in favor of just removing it, since it is impossible to balance with the other recipe...
In my opinion Platinum should have been removed as well, since there is already a cheap Platinum recipe by putting the PMP into the EBF.

**Comment by Sphyix** [comment]
> Imho 10 million eu is not much in IV.... just dump 1A if IV into it and let it output one graphene per minute, if that runs over night you will have more than enough. Don't forget EV/IV is the Tier with many solid power options like Fluid reactors, lava etc...

If you want to play afk, yea, and that's a good alternative then i guess
It takes 92 seconds to make power at IV for a stack of graphene, around 1 hour with the Molecular transformer
Power at IV is not free even tho it's easy to get, running a nuke means you have to go mine for uranium and process it

**Comment by Savallator** [comment]
Go mine for uranium lol.... the amount of uranium a high-efficiency nuke uses is so incredible small...

**Comment by Elisis** [comment]
Can we at least get rid of the glue and use PE/PTFE/PBI like you would for, say, circuits?

**Comment by Dream-Master** [comment]
guess the glue is more realistic. Its not a circuit it a complete different process.

**Comment by Savallator** [comment]
To be honest, the glue process (actually, it should use duct-tape), is more of a meme anyways. it was the first method to obtain Graphene, but in reality there have been way better options available for quite some time.

**Comment by Elisis** [comment]
But it vaguely follows in line with the rest of the components we have. And how assemblers seem to work on e.g. Machine Hulls.

**Comment by Dream-Master** [comment]
> To be honest, the glue process (actually, it should use duct-tape), is more of a meme anyways. it was the first method to obtain Graphene, but in reality there have been way better options available for quite some time.

feel free to add more recipes or at least some suggestions.

**Comment by Savallator** [comment]
I have long dreamed of having a more intricate Wafer production, like having a Silicon processing chain for purification, then making the doped wafers, then cutting to single wafers, a multi for doing Molecular Beam Epitaxy to produce the various wafers, then needing to coat them (chem bath maybe) before shoving them into the laser engraver, and then finally needing to etch them, using HF and other, more intricate chemicals. (From a real world perspective, there would be an additional step here to make the contacts e.g. using Chemical Vapor Deposition). I do have quite some Ideas about a redesigned circuit production (that also account for not needing to make stupid amounts of stuff, so the more difficult higher-tier recipes should actually yield more), but i am not sure if there is demand for that.

Anyways, then Graphene could then be produced by Epitaxy, using Carbon, Wafers and some kind of getter metal for stabilizing the vacuum.

**Comment by Elisis** [comment]
> but i am not sure if there is demand for that.

It's been considered a few times but ended up going nowhere. Circuits probably are going to stay quite similar to how they already exist so as to not awfully break balance.

**Comment by Savallator** [comment]
The circuit recipes itself would not change - just how to make the wafers. And the normal wafers and easy circuits should stay as well to not overcomplicate early game.

**Comment by Elisis** [comment]
> feel free to add more recipes or at least some suggestions.

![image](https://user-images.githubusercontent.com/28530295/146272905-17a202c4-c455-4b45-8bb3-a9edf4e82d8d.png)
?

**Comment by Elisis** [comment]
> just how to make the wafers

If you change wafer balance, you change circuit balance.

**Comment by Savallator** [comment]
But wafers are incredibly boring imho... it is just "shove silicon + x into ebf, then into cutter, then into laser engraver with some lens" all the way up to the endgame (with just very few exceptions).
Also, i don't intend on _nerfing_ it, just changing it. The recipes could actually give way more output imho, as a reward for the more complex processing needed.

**Comment by Dream-Master** [comment]
> But wafers are incredibly boring imho... it is just "shove silicon + x into ebf, then into cutter, then into laser engraver with some lens" all the way up to the endgame (with just very few exceptions). Also, i don't intend on _nerfing_ it, just changing it. The recipes could actually give way more output imho, as a reward for the more complex processing needed.

new recipes and mechanics suggestions are welcome.

**Comment by Savallator** [comment]
I can work it out in detail with a some flow diagramm and then make a seperate issue for it.

**Comment by Elisis** [comment]
Issue is, there's always the risk of making it not feel Greg enough. Maybe if it were specifically later tier for tiers where there's so little content anyway.

**Comment by Savallator** [comment]
It should of course be more complex for the high-tier circuits. The starting recipes for the simple wafers should not change much.

**Comment by Pxx500** [comment]
![image](https://user-images.githubusercontent.com/81298696/146743352-c8d2e77c-7589-451a-b53c-2761d68f1ba2.png)
Graphene line incoming?
