### ISSUE TITLE
Prospecting data wrote cursed books

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#9127]
### Your GTNH Discord Username

Logos#2981

### Your Pack Version

2.1.2.0

### Your Server

Eta

### Type of Server

Thermos

### Your Actions

Using a HV advanced seismic prospector on the moon, I went through the normal process of prospecting, scanning the data sticks, printing the data to paper, and then binding the paper stack to a book in an assembler. For two of the five data sets, this went as expected, resulting in a book of prospecting data. For three of the five, this resulted in a seemingly blank written book entitled "Written Book", which stacked, and appeared to have no test. When opening these books, the client disconnected from the server citing "Internal Server Error" as the reason.

The exact steps to reliably replicate this issue are unknown at this time.

### Crash Report

As "Internal Server Error" was cited as a reason, it's possible that server-side logs might contain information. The timestamp is between 02:18:37 and 02:19:18 UTC (not sure of server's timezone) for the first disconnecting incident, with the books in question being crafted in the minutes before the crash.

The latest log is attached, with the crash occurring between 20:18:37 and 20:19:18 in the log. Unfortunately, not much useful here.
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7716348/latest.log)

Colen was asked to take a look at the book and see if any additional information could be gleaned, and reported that mt-hand yielded this:
![mt-hand](https://user-images.githubusercontent.com/23437451/146119910-e24714a6-6f43-4f80-a7c7-0fb59108d3c5.png)
 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
I have had this happen on 2.1.1.0 also; its seems to be mostly when the server is lagging and I try to "print too fast"

I've taken to doing one book at a time.

**Comment by Logos-Askrson** [comment]
That... would match up. I did pile all of the papers into the assembler at once, and there was a bit of a lag spike at the time. Not sure if that's enough to consistently replicate the issue, since it relies on server lag, but it's more information.

Thank you for sharing.

**Comment by bombcar** [comment]
Not sure if visualprospecting needs the book or can run direct off the data stick ... hmmm @SinTh0r4s ?

**Comment by Florexiz** [comment]
From my experience this is caused by shift clicking printed papers (and maybe leather?) in assembler. When you drag & drop them inside it prints fine

**Comment by SinTh0r4s** [comment]
> Not sure if visualprospecting needs the book or can run direct off the data stick ... hmmm @SinTh0r4s ?

I need to get into the process from the prospector itself onwards. So that might be on me. Could someone get me the server logs for that event? That would be awesome. Then I can check where that issue happened and guard against it. The exception is likely to be printed in logs/GregTech.log only.
