### ISSUE TITLE
Lubricant quest text is not adjusted properly

### ISSUE THREAD

**Issue by million09** [GTNewHorizons/GT-New-Horizons-Modpack#9129]
### Your GTNH Discord Username

million09#9392

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Lubricant quest (No.1084) says I can make Lubricant out of Oil (and other three) and I can't process Oil in Brewery.

### The Reality

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6765/commits/463618feb77437bdc1577c9e659efc1d3797c403 says original issue #6704 is closed, but that description is still not correct.

### Your Proposal

"~ You can make lubricant out of seed oil, fish oil or creosote in a distillery (or distillation tower later on), but you can't use oil yet. If you're able to craft a brewery you can use oil (and other options) to get much more lubricant each cycle. ~"

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
In 2.1.2.3qf, Oil -> Lubricant in Distillery recipe is present. Not sure when it disappeared and got re-added
