### ISSUE TITLE
Adjust Really Ultimate Battery soldering alloy amount

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#9131]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.0

### Your Proposal

Currently the really ultimate battery requires 3760L of soldering iron. This is however not possible to automate properly with flasks of 144,288,576 L etc.

### Your Goal

Propose to change the required amount to 4608L, which is 32x144 or 16x288 or 8x576 and can easily be automated with the current flask sizes that are used in many other assembly line recipes.

### Your Vision

Easier automation

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Sphyix** [comment]
It can be automated with 940 flasks for now
Just make some of them by hand and set them as a result of the craft

**Comment by GTNH-Afx237v7** [comment]
Can also be done with other sizes, but the point is that it does not fall in line with the other automation tools and processes we have. May just make a PR myself....

**Comment by Sphyix** [comment]
Yea my point was just to give a suggestion to automate it until it's fixed.
It's obviously wrong like this

**Comment by GTNH-Afx237v7** [comment]
Fixed with: https://github.com/GTNewHorizons/TecTech/pull/22
