### ISSUE TITLE
Soul Sand missing multiblock recipe

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9132]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

Singleblock doesn't work on gt++ multiblock anymore
![javaw_lfndwWnM6I](https://user-images.githubusercontent.com/17811922/146170484-27c24530-4c8b-4187-9dc0-3db19fdd18d3.png)

### The Reality

+

### Your Proposal

+

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
It has its own recipe map now and if it’s added by minetweaker there’s no way to ever grab the recipes.

**Comment by boubou19** [comment]
yeah, a lot of recipes are doomed to be single block/PA only, unless we port all the scripts in code.

**Comment by bombcar** [comment]
> yeah, a lot of recipes are doomed to be single block/PA only, unless we port all the scripts in code.

This is (slowly) in progress - if specific scripts are identified we can prioritize them. Speeds up loading, too.
