### ISSUE TITLE
Lapis dust circuit 2 mixer conflict

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9133]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

Conflict with circuit 2, IC2 coolant and Lapotron Dust
Shouldn't be an issue since water is not needed on the Lapotron Dust, but a lot of recipes need water so in my multiblock I always have water, distilled, and oxygen, I bet I'm not the only one. This covers all the possible recipes without the need to send flasks to the multiblock on request, makes the crafting faster and it's less load on the server
![javaw_Q7Wy2dG2Iz](https://user-images.githubusercontent.com/17811922/146171533-c5c06543-1832-4665-85aa-b9b688d8480b.png)
![javaw_oBpV4Sm67Q](https://user-images.githubusercontent.com/17811922/146171541-179f55f8-74d9-4e4d-ae30-606a657aafbf.png)
 

### The Reality

+

### Your Proposal

+

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
recipe with water should probably be circuit 4 , like fluix dust

**Comment by KiloJoel** [comment]
Isn't this fix the wrong way round? Should be coolant recipe moved to circuit 4 rather than lapotron dust
