### ISSUE TITLE
Make content of Ultra Low to High Voltage tanks clearable

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9134]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Proposal

Add a shapeless recipe to clear contents of those tanks.
Right now they can't be cleared after they are picked up, only way is to place them back down and pull out fluid.

### Your Goal

+

### Your Vision

+

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Can you try the NBT wiper? Probably does nothing ….

**Comment by Sphyix** [comment]
> Can you try the NBT wiper? Probably does nothing ….

Doesn't do anything
