### ISSUE TITLE
Changes to a multiblock are not detected until controller is replaced

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9135]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

After building a processing array I removed a casing and replaced it with an input bus while machine was running.
Change was never detected and the stuff inside the input bus is not getting detected or used for the recipe.
This hot swap was possible on 2.1.1.0
![javaw_LbKWI9QYmR](https://user-images.githubusercontent.com/17811922/146175155-fe778a2f-2694-43ef-bb74-0d899b8f7281.png)

After removing the input bus that was not being detected I was able to make the machine run with a missing block
![javaw_heD7wjLPK6](https://user-images.githubusercontent.com/17811922/146175309-c1d82c11-6762-411d-b5fe-fd7430e3a143.png)

I believe mutliblocks are not checking their structure anymore after being built.
To make my PA detect the change I had to replace the controller. Turning it on and off did nothing, it was able to keep doing recipes even after a while with a missing block.
This can be a big issue with stuff like PSS or LSC if they don't detect the hotswaps of energy hatches/dynamos

### The Reality

+

### Your Proposal

+

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Sphyix** [comment]
This stopped happening, delta is a wierd place

**Comment by Sphyix** [comment]
This is happening intermittently
I can't find a way to reproduce it, but it happened with a mega DT, a PA and a nine in one (gt++)
If the multiblock is not formed, it'll never form unless the controller is replaced-
If it is already formed, it'll keep working no matter what you remove. Stuff that gets replaced is not recognized until the controller is replaced.

**Comment by draknyte1** [comment]
I can confirm that base GT and GT++ multis work as expected. I’ve rebuilt XL turbines maybe 150 times and even changing a block in a turbine at one end is detected by the controller at the other. 

![70CDE81E-5DAE-4EDC-97B8-C885557B9EF2](https://user-images.githubusercontent.com/3060479/147395515-e057d0e9-6731-43f0-8e03-e63a35b15528.png)

**Comment by Glease** [comment]
There might be some kind of race condition or memory visibility problem if your base is stupidly big (>10k blocks interconnected) We probably can't do much about this without removing the parallelizing optimization.

**Comment by boubou19** [comment]
Still tho, if it impacts one dim it's bearable if the dim is for one player. If the dim is the overworld, then that will become an issue.

**Comment by Glease** [comment]
If it happens again, tell your server admin to run `/gt toggle debugMulti`, break one of the blocks in that multi and place it back, and ask server admin to look at server console for lines like `Multi [xx, xx, xx] failed @ [x, y, z] [x, y, z]`. It's probably not going to be very helpful, but nontheless we would get to know which block exactly is failing.

**Comment by boubou19** [comment]
quick question tho (because i am the server admin in question :D ) is that command persistant to reboots?

**Comment by Sphyix** [comment]
> I can confirm that base GT and GT++ multis work as expected. I’ve rebuilt XL turbines maybe 150 times and even changing a block in a turbine at one end is detected by the controller at the other.

As you can probably see by reading the issue, I actually closed it after believing it was just delta acting up.
I reopened it cause it happened again, if you think I'm here just to waste your time idk what to tell you.

**Comment by Sphyix** [comment]
> There might be some kind of race condition or memory visibility problem if your base is stupidly big (>10k blocks interconnected) We probably can't do much about this without removing the parallelizing optimization.

This is my base glease
![javaw_l7Q1QbVMf6](https://user-images.githubusercontent.com/17811922/147395963-43209732-b267-497c-996f-0bdfd6bd81e4.png)
![javaw_85Mwt1pjon](https://user-images.githubusercontent.com/17811922/147395964-8726d3c7-19b3-45ac-88fb-7f84f13aa36a.png)

**Comment by bombcar** [comment]
That’s about 💯k blocks in size - is it all chunkloaded?

**Comment by Sphyix** [comment]
> That’s about 💯k blocks in size - is it all chunkloaded?

5k blocks, chunkloaded.
It happened on my old base as well, 9x9 chunks chunkloaded

**Comment by bombcar** [comment]
Again over the 10k proposed threshold so it’s likely that’s involved hmmm

**Comment by Glease** [comment]
> quick question tho (because i am the server admin in question :D ) is that command persistant to reboots?

No.

**Comment by Sphyix** [comment]
> If it happens again, tell your server admin to run `/gt toggle debugMulti`, break one of the blocks in that multi and place it back, and ask server admin to look at server console for lines like `Multi [xx, xx, xx] failed @ [x, y, z] [x, y, z]`. It's probably not going to be very helpful, but nontheless we would get to know which block exactly is failing. Be sure to run `/gt toggle debugMulti` again to not let it !a2

Command doesn't give any output when the bug occurs.
![javaw_6zz3YH20Of](https://user-images.githubusercontent.com/17811922/150104307-ced5ccb3-9d66-4271-a76f-fbe3307cd77c.png)

**Comment by boubou19** [comment]
the debug command works well because i get some other multi failing to form being reported. Seems like it's just the multis in the dimension themselves that stop the structurecheck updates.

**Comment by Glease** [comment]
Try [structurelib 1.0.15](https://github.com/GTNewHorizons/StructureLib/releases/download/1.0.15/structurelib-1.7.10-1.0.15.jar)[1]. It will now log check success alongside check failures. If it logs nothing, try apply [this patch](https://paste.ee/p/I8yQp)[2] to gregtech and see if it solves the problem. If it logs a success... welp we are in Very Big Trouble™.

[1]: Structurelib is safe to update without client updating.
[2]: I do not suggest using this patch as a long term solution. It introduce breaking changes in the API and needs to be propogated to all addons we have (e.g. tectech) to ensure addon multis detects changes in structure in time. 

I honestly don't believe this would solve anything though. I cannot think of a situation that would cause `mUpdate` to either skip 0 or get a corrupted value, as there is only one thread ever ticking down the value and others just reset it back to a constant. However this is the only location that may contain a heisenbug, so I'll just give it a try anyway.

**Comment by Sphyix** [comment]
Well at least now I kind of know how to reproduce it.
It looks like the bug goes away after a while by itself aswell, like now that a few hours have passed, all the multis are working like normal again.

**Comment by boubou19** [comment]
looks like some piece of code is overloaded, and because it's not flagged on the server thread (to my knowledge) maybe some thread is going wild? assuming it's using a thread to do the check
