### ISSUE TITLE
Reversed centrifuge chances on GT singleblock vs GT++ multiblock

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#9137]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.0

### Your Server

SSP

### Type of Server

Single Player

### Your Expectation

Noticed that centrifuging sticky resin in a GT singleblock has 100% chance for raw rubber dust and 10% chance for plantball.
Looking at GT++ multiblock centrifuge the chances are reversed, i.e. 10% chance for rubber dust and 100% chance for plantball.
Looked at other recipes, e.g. centrifuging impure dusts and it is identical - the %chances are opposite depending on GT singleblock or GT++ multiblock 

### The Reality

GT++ multiblock should have the same behavior as GT singleblock

### Your Proposal

Check recipe map generation? Not sure where the mistake is but the error is within GT++

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
It’ll be from my changes to the NEI handling. Recipes will behave as expected.

**Comment by XETARa** [comment]
But I found the output chance doesn't match the single one.
![](https://user-images.githubusercontent.com/92867295/146230013-4c8c0c26-9e51-4185-bab5-5ee1ae0bacee.png)
![](https://user-images.githubusercontent.com/92867295/146230204-f8241ad4-975b-463f-b801-4d8d2363552b.png)
That's a huge buff for bees lol.

**Comment by draknyte1** [comment]
> But I found the output chance doesn't match the single one.
> ![](https://user-images.githubusercontent.com/92867295/146230013-4c8c0c26-9e51-4185-bab5-5ee1ae0bacee.png)
> ![](https://user-images.githubusercontent.com/92867295/146230204-f8241ad4-975b-463f-b801-4d8d2363552b.png)
> That's a huge buff for bees lol.

It’s a visual issue for NEI, the recipes will behave the same on both multis and singles.

**Comment by GTNH-Afx237v7** [comment]
Any chance of it being fixed though?
