### ISSUE TITLE
change the recipe of the stone dust to give full dust in output

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9138]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

x9 the time and the input to give the full dusts instead of small dusts, to keep it inline with our tiny pile removal policy.

### Your Goal

-

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Also all the planetary dusts, moonstone, Endstone, etc

**Comment by Eldrinn-Elantey** [comment]
But the dust does not turn out with a 100% chance

**Comment by bombcar** [comment]
> But the dust does not turn out with a 100% chance

They can math it so that the percentage chance for full dust _over time_ works out to the same as it was before
