### ISSUE TITLE
Combined Large Steam Turbine multiblock (x3) doesn't form a complete structure

### ISSUE THREAD

**Issue by SwisVII** [GTNewHorizons/GT-New-Horizons-Modpack#9141]
### Your GTNH Discord Username

Swis#9755

### Your Pack Version

2.1.2.0

### Your Server

private server

### Type of Server

Open To LAN

### Your Expectation

I've updated to the latest version of GTNH recently. I had a combined Large Steam Turbine multiblock (x3) and it worked properly and I hoped that it would work properly after update, but reality is different...

### The Reality

After I had updated to 2.1.2.0 it stopped working with a letter "Incomplete structure", so it doesn't form a complete structure.

### Your Proposal

x3 combined Large Steam Turbine multiblock form a complete structure and work properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eldrinn-Elantey** [comment]
I confirm the presence of this problem

![image](https://user-images.githubusercontent.com/46845681/146221594-5a07ccd4-8e12-43b9-9b06-533a4feedadc.png)


![image](https://user-images.githubusercontent.com/46845681/146221608-bd83a98b-5561-4e25-ba06-4c08e2a9eec4.png)


With this structure, the turbines do not work

**Comment by boubou19** [comment]
are you able to form them normally without any wall sharing at least?

**Comment by SwisVII** [comment]
> are you able to form them normally without any wall sharing at least?

Yes, but that's a little bit expensive.

**Comment by Eldrinn-Elantey** [comment]
> are you able to form them normally without any wall sharing at least?

We have redesigned the turbines. Now they are put like this

![image](https://user-images.githubusercontent.com/46845681/146260334-8328863b-4083-4dcc-90d8-8e66edfd22d3.png)

**Comment by boubou19** [comment]
but do they work? because it might just be structurelib enforcing stricter checks, as explained in number 2 of this message: https://discord.com/channels/181078474394566657/295669878222880769/865582877067968532

**Comment by Eldrinn-Elantey** [comment]
> but do they work? because it might just be structurelib enforcing stricter checks, as explained in number 2 of this message: https://discord.com/channels/181078474394566657/295669878222880769/865582877067968532

Prior to the upgrade to version 2.1.2.0, the turbines operated with common walls. Do you want to say that it stopped working because of the introduction of the multiblock rotation function?

**Comment by bombcar** [comment]
>2. You will most likely be unable to do wall sharing with turbines, if you previously were. some degree of sharing is still allowed, but !feature style sharing should be a relic of past.

They fixed turbine sharing by fixing the code that was allowing them to overlap

![image](https://user-images.githubusercontent.com/533931/146264369-c7a9ff2f-3bc4-421b-b7c4-4101ecd82e3f.png)
