### ISSUE TITLE
Pollution Graphic still renders

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9145]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.0

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

When pollution in a chunk clears, the effects should stop.

### The Reality

When coming into some chunks that had pollution in the past (but it was removed by the air filter), they still have the effects even after half an hour.
![2021-12-15_20 20 28](https://user-images.githubusercontent.com/10967188/146258632-69c4ce64-015b-437a-b4b2-23922d4812b2.png)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
looks like the pollution map client side isn't correctly updated

**Comment by Dream-Master** [comment]
Yea hat issue s with it in sp as well yesterday

**Comment by Savallator** [comment]
Is there something done about this already? Because the graphics will not even reset after a relog, i need to restart the client, and it is quite annoying to restart the client everytime a rocket is launched.
