### ISSUE TITLE
Opis enabled by default in the Server - eating significant tick times

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9147]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.0

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

.

### The Reality

Opis is enabled by default in the Server files, and i randomly noticed while profiling that just one Method from it draws about 11%
tick time.
![opis_](https://user-images.githubusercontent.com/10967188/146269160-69030257-a7d5-452e-ba15-3a457b9089d8.PNG)
 

### Your Proposal

Disable the opis jar by default.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
More detailed information:
![opis2](https://user-images.githubusercontent.com/10967188/146269813-4b3eeb68-68cb-4006-bab1-190986ebd6ed.PNG)

**Comment by boubou19** [comment]
can you unfold the nodes a bit more? because opis never got any performances issues, so looks like it's hooking on something laggy, making it being flagged as the lag source

**Comment by Savallator** [comment]
It is literally [this](https://github.com/GTNewHorizons/MobiusCore/blob/modless/src/main/java/mcp/mobius/mobiuscore/monitors/MonitoredList.java) code here, and that is calling removeAll on a java array List containing a lot of stuff once per tick... no wonder it draws performance

**Comment by Savallator** [comment]
You can clearly see it is part of Opis itself.

**Comment by boubou19** [comment]
mhm, what version is in the pack? also, we don't get it on the officials so this is weird, as if you were running an edge case or something.

**Comment by Savallator** [comment]
it is literally the internal List that opis keeps... you see it quite clear from the code and the screenshot. It is running 2.1.2.0.

**Comment by boubou19** [comment]
yeah i got it thanks, opis is lagging your server. The question is what are you making different than the officials. http://playdelta.gtnewhorizons.com:23000/stack

**Comment by bombcar** [comment]
![image](https://user-images.githubusercontent.com/533931/146276018-fdea2836-390a-4436-8dc5-8234b76b1313.png)

Officials are thermos - what if vanilla forge doesn't have that hashmap?

Only time in history thermos saves the day?

**Comment by boubou19** [comment]
![image](https://user-images.githubusercontent.com/12850933/146277251-a700972f-de72-4aa6-865b-e59b71d45435.png)

it's suprising but i think bombcar is right wtf

**Comment by Savallator** [comment]
So Thermos replaced that List with a Hashmap, and Forge not?

**Comment by boubou19** [comment]
more like forge didn't touched vanilla code while thermos messed with it

**Comment by Savallator** [comment]
But habing a Hashmap there instead of a ArrayList sounds very reasonable.

**Comment by mitchej123** [comment]
This actually isn't introducing any more lag than running without it.  It just looks different because Opis is ASMing the `loadedEntityList` with it's own MonitoredList subclass of ArrayList instead of the default ArrayList, so it'll show up differently on the profiler but it's doing the same work.  The offending (badly performing) line is `this.loadedEntityList.removeAll(this.unloadedEntityList);` in updateEntities in World, which ultimately calls `.contains()`, and is terribly non performant on a large arrayList.

The thermos compatible mobius core that the servers are running, further patches this to use a ArrayHashList, which delgates things like `.contains` to a HashSet, dramatically speeding the function up, but also showing up differently on the profiler.


All that being said, it looks like the Thermos implementation of the ArrayHashList is actually pretty performant and wouldn't hurt being patched into MobiusCore.  MobiusCore, however, is CC-NC (non commercial), so isn't compatible with GPL code.  Fortunately the idea is pretty simple and could be reimplemented.  I'll give it a shot for you to run on your server and provide a warmroast of.

**Comment by mitchej123** [comment]
Note: We can't directly swap out the list with a HashSet because this is how it's declared `public List loadedEntityList = new ArrayList();`  It needs to be something that implements the List interface.

**Comment by mitchej123** [comment]
It also doesn't look like you're running FastCraft.  Looking at my local profile, fastcraft may already be patching this, although it's hard to say as I don't have many tiles unloading 
![image](https://user-images.githubusercontent.com/1894689/146295701-d36e12f0-362f-4148-b95a-fd7e936c237a.png)

**Comment by bombcar** [comment]
Fastcraft on server is highly recommended and perhaps this is why

**Comment by mitchej123** [comment]
I'd suggest try out fastcraft and report back with an updated profile.

**Comment by Savallator** [comment]
Fastcraft seems to fix it. It really should be in the Server pack by default again.

**Comment by Savallator** [comment]
I am still surprised who thought it was a good idea to have a plain ArrayList of Thousands (maybe Millions) of Entities and doing a O(n^2) Operation over it every tick...

**Comment by Glease** [comment]
Why reopen? Adding fastcraft does solve the issue.

**Comment by boubou19** [comment]
Because with @mitchej123 we thought about adding a similar fix if fastcraft is not present for whatever reason: it's not guaranteed that we will keep fastcraft forever, nor the fact that the player removes it because it does more damage than good.

**Comment by mitchej123** [comment]
We're not shipping fastcraft on the server side, and people on the RC were complaining about lag.  Probably going to reimplement the thermos hashset backed list and patch it in when thermos/fastcraft aren't detected. :-/

```patch
-    public List loadedEntityList = new ArrayList();
-    protected List unloadedEntityList = new ArrayList();
-    public List loadedTileEntityList = new ArrayList();
-    private List addedTileEntityList = new ArrayList();
+    public List loadedEntityList = new HashedArrayList();
+    public List unloadedEntityList = new HashedArrayList(); // Cauldron
+    public List loadedTileEntityList = new HashedArrayList();
+    private List addedTileEntityList = new HashedArrayList();
```
