### ISSUE TITLE
Fluids appearing in item form

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9148]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.0

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

Fluids should not appear in item form.

### The Reality

I found that inside my AE2 system, there are some weird items in fluid form. This has been in 2.1.1.4QF2 already, maybe even earlier.
Now, after patching, i am quite sure the number increased, and i also found them in tanks slots. i can even move them around just like items.

![2021-12-15_23 07 48](https://user-images.githubusercontent.com/10967188/146272560-c612f886-730d-48e3-ad49-dccfc68da7b1.png)
![2021-12-15_23 07 50](https://user-images.githubusercontent.com/10967188/146272562-cb2b0679-d2ee-4fbc-915d-55e63fbd1794.png)
![2021-12-15_23 08 04](https://user-images.githubusercontent.com/10967188/146272563-e334fa38-0cf4-443b-8ad3-dc2a5b0c2e0f.png)
:

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
This happens anytime a machine has a new slot added, which forces the old slot to be non-fluid anymore.

It happens once on world update and then doesn't occur again.

There's code that is supposed to be used when adding a slot to a machine but it's never run.

For now you can place the fluid on a wall with P to remember it.

**Comment by Savallator** [comment]
What slot was added to the MV fluid tank?

**Comment by bombcar** [comment]
Iirc it was ... the autoclave? Not in game, but once the fluid has escaped the machine it was in, it can get put in weird places by AE2, dropped in the world, etc.

**Comment by Savallator** [comment]
There is no autoclave next to it, and no connections to the tank that could insert something.

**Comment by Savallator** [comment]
i have found some more places where it happened, but i guess it really only happened at patch-time, i think there were no new occurences. I guess this here can be closed then, as i guess it is not worth fixing/impossible to fix anyways.
