### ISSUE TITLE
Correction of decomposition recipes taking into account the appearance of alumina

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9149]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

I looked through the recipes for obtaining aluminum after the appearance of alumina and found that they contain excess oxygen

### The Reality

The recipes for obtaining alumina still give out oxygen, which should be in alumina with the possibility of its further decomposition

### Your Proposal

It is necessary to adjust the recipes taking into account the combination of oxygen and aluminum into alumina. Somewhere oxygen can be simply removed, but somewhere it may be necessary to adjust the amount taking into account the modpack policy as it was done [here](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9139)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eldrinn-Elantey** [comment]
Kyanite Dust
Red Granite Dust
Ruby Dust (6954:2512)
Ruby Dust (6954:2502)
Spodumene Dust
Kaolinite Dust
Spessartine Dust
Pyrope Dust
Grossular Dust
Almadine Dust
Emerald Dust
Bauxite Dust
Topaz Dust
Blue Topaz Dust
Pollucite Dust
Alunite Dust
Mica Dust
Lepidolite Dust
Tanzanite Dust
Biotite Dust
Lazurite Dust
Glaucinite Dust (6954:2933)
Glaucinite Dust (6954:2949)
Green Fuchsite Dust
Vermiculite
Fluor-Buergerite Dust
Olenite Dust
Zeolite Dust

**Comment by bombcar** [comment]
Note that some may also exist where Silicon was changed into SiO2
