### ISSUE TITLE
server crashes on startup with Visualprospecting enabled

### ISSUE THREAD

**Issue by YanFett** [GTNewHorizons/GT-New-Horizons-Modpack#9150]
### Your GTNH Discord Username

reverse71

### Your Pack Version

2.1.2.0

### Your Server

private server

### Type of Server

Don't know

### Your Actions

i renamed all files that could collide from the old server
i uploaded all 2.1.2 files
i started the server
--> crash at 35% of visualprospect processing
removed visualprospect and it runs fine
added it again, crash happens during startup. Startup takes AGES

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7723347/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Also https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9109 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9128 are probably the same

**Comment by YanFett** [comment]
I just got more ram for the server. I was running on 10 gigs, now it runs on 20. This fixed the issue.

**Comment by bombcar** [comment]
> I just got more ram for the server. I was running on 10 gigs, now it runs on 20. This fixed the issue.

That’s a workaround but we shouldn’t use 20gb of ram just to process ores

**Comment by SinTh0r4s** [comment]
> I just got more ram for the server. I was running on 10 gigs, now it runs on 20. This fixed the issue.

You may reduce the RAM back down to 10 after the process ran once.

**Comment by bombcar** [comment]
The latest VP has ability to limit dimension size when running in fast mode.
