### ISSUE TITLE
L.E.S.U broken in several ways

### ISSUE THREAD

**Issue by Nate-Luscomb** [GTNewHorizons/GT-New-Horizons-Modpack#9151]
### Your GTNH Discord Username

Mr.Professor#0910

### Your Pack Version

2.1.1.0

### Your Server

Private linux multiplayer server

### Type of Server

Don't know

### Your Expectation

I expected the L.E.S.U to work as a modular battery where the more units you add to it the larger the output all the way up to LuV and beyond.

### The Reality

As the object has more and more casings added to it; it becomes more and more "unstable" of the ~6 attempts I have had at making it the unit has done 1 thing 5 times and another the last time (both were not as expected). 

1. Adding casings to the multiblock no longer were recognized by the structure even when built in the same chunk. Attempts to resolve this, such as removing the controller caused a "dead state" where the controller reported another controller was detected in the same multiblock and that wall sharing was not allowed. This effectively bricked the multiblock and caused every single casing to be hand mined and replaced to function again.
2.  The current "working state" I have connected it to my power grid and used transformers to lower and up the voltage on the input and output respectively. This worked for some time but then after a few days (server is up 24/7) the GUI stopped tracking input output and looks to be supplying infinite power.

### Your Proposal

I propose that it be looked at for conflicts as from what I can tell by querying the discord help chat with this problem it could be exclusive to my current build. Please let me know if I can help I respond to discord DMs fairly quickly if I didn't give enough information.

Thanks for the amazing mod pack I love it!!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
why not if we make it a bit cheaper and fix it it might be an alternative battery.

**Comment by chochem** [comment]
yea a rebalance is totally valid. Except that up to now nobody wanted to touch it.

**Comment by iouter** [comment]
we have enough batteries: pss, lsc, even the dam
