### ISSUE TITLE
Quest Lines Disappearing When Not Hovering

### ISSUE THREAD

**Issue by Elisis** [GTNewHorizons/GT-New-Horizons-Modpack#9153]
### Your Pack Version

2.1.2.0

### Your Server

Eta

### Type of Server

Thermos

### Your Expectation

Have the questbook look similar to how it did before the update.

### The Reality

It now looks like this, having detached quests.
![image](https://user-images.githubusercontent.com/28530295/146304772-d27d07e7-23b4-4cf1-9c28-65426c17b0af.png)

### Your Proposal

Fix it. Or, if it's intentional, make it a config option.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
This not a bug this is a feature to un-spaghetti all this quest lines a bit.

**Comment by Dream-Master** [comment]
Feel free to re add lines if you like spaghetti 🍝

**Comment by bombcar** [comment]
The option to force them always on would be nice.

Also poor wire mill all alone in the corner there. :D

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/BetterQuesting/pull/49
