### ISSUE TITLE
Advanced Monster repeller II not working?

### ISSUE THREAD

**Issue by ChrisLua** [GTNewHorizons/GT-New-Horizons-Modpack#9155]
### Your GTNH Discord Username

ChrisLua

### Your Pack Version

2.1.2.0

### Your Server

Selfhosted dedicated server

### Type of Server

Vanilla Forge

### Your Expectation

in 2.1.1.0 the repeller prevented any hostile mobspawn in my base.

### The Reality

in 2.1.2.0 now there are monster spawning everywhere. repeller did not change. still powered.

### Your Proposal

bug? is this pullution caused? i have low level. below 200.000.
just updated, everything is on stop. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Look for a amdiforge mod in the server pack and disable it iirc.

**Comment by ChrisLua** [comment]
and That mod does stop the repellers from working?
is it intentional or bug? 
will it be fixed in 2.1.2.**1**?

**Comment by bombcar** [comment]
IIRC it’s a known issue unlikely to be fixed. That mod can be removed - afaik it’s for the officials only.
