### ISSUE TITLE
Refinement of mass fabricator recipes for more flexible customization

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9157]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Proposal

To change the recipes of mass fabricator, namely, to add the need for a configuration circuit. For example, configuration 1 runs purely on energy, and configuration 2 runs on energy and UU Amplifier

### Your Goal

These changes will allow you to set up a production chain that will work only if there is a UU Amplifier, which is more economical in terms of energy and time

### Your Vision

These changes will allow for more precise adjustment of the matter production chain

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
We already plan to rework uua and uum

**Comment by Eldrinn-Elantey** [comment]
> We already plan to rework uua and uum

Understood, thanks for the prompt response

**Comment by Dream-Master** [comment]
Let it open for me as a reminder

**Comment by Eldrinn-Elantey** [comment]
> Let it open for me as a reminder

Ok

**Comment by Eldrinn-Elantey** [comment]
I think it's still needed right? @Dream-Master

**Comment by Dream-Master** [comment]
let it open

**Comment by Eldrinn-Elantey** [comment]
@Dream-Master What's up with that question?
