### ISSUE TITLE
No longer get hunger on peaceful

### ISSUE THREAD

**Issue by blattgoldowo** [GTNewHorizons/GT-New-Horizons-Modpack#9158]
### Your GTNH Discord Username

Эшли#1917

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

Used to get hungry on Peaceful.

### The Reality

No longer get hungry on latest stable version

### Your Proposal

Make hungry on peaceful again

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can confirm hunger happens in peaceful on 2.1.1.0 - perhaps a mixin is supplying this and is no longer being applied?

**Comment by Dream-Master** [comment]
but why no hunger in peaceful? Maybe less hunger .

**Comment by bombcar** [comment]
Vanilla minecraft turns off hunger in peaceful. Something we had in 2.1.1.0 turned it back on - whatever it is isn't working. 

I suspect https://github.com/GTNewHorizons/AppleCore/pull/8 fixes it OR .... another mixin is failing.

**Comment by Dream-Master** [comment]
ok if it was working in 2.1.1.0 sure we need to set it back

**Comment by bombcar** [comment]
Confirmed the apple core update fixes it. 

http://jenkins.usrv.eu:8080/job/Apple-Core/ if you want to patch your setup for now until 2.1.2.1

**Comment by TwoTailedFox** [comment]
Not getting hungry on peaceful on 2.1.2.2, issue remains unresolved.

**Comment by bombcar** [comment]
Appears to be happening on a new world on 2.1.2.2; also said new world defaulted to peaceful ...

**Comment by bombcar** [comment]
Still happening and needs to be investigated. Likely something is preventing a mixin/ASM from loading ...
