### ISSUE TITLE
ME interface not pushing same items with durability into machine slots 

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#9159]
### Your GTNH Discord Username

CatsLeftEar#3300

### Your Pack Version

latest stable official

### Your Server

Epsilon

### Your Expectation

Create a advanced heat exchanger
![image](https://user-images.githubusercontent.com/67397297/146444994-66b6c7c7-bccf-4af4-8d9f-5d7ecfef341c.png)

### The Reality

I have 2 component heat exchanger for recipe, but interface only pushes one.
![image](https://user-images.githubusercontent.com/67397297/146445026-b343530b-2370-4553-9196-fb5322ed2760.png)

### Your Proposal

Let interface push two same items into a machine

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Heat exchangers aren't stackable, this recipe might hmmmm

**Comment by repo-alt** [comment]
It might work iwith input filter turned off probably, but yes, the recipe is not good

**Comment by boubou19** [comment]
might be fixed with https://github.com/GTNewHorizons/GT5-Unofficial/pull/808

**Comment by Glease** [comment]
Turn on multiple stack input.
