### ISSUE TITLE
Automatic wakeup of anchors not working

### ISSUE THREAD

**Issue by dr-flop** [GTNewHorizons/GT-New-Horizons-Modpack#9160]
### Your GTNH Discord Username

drflipflop

### Your Pack Version

2.1.2.0

### Your Server

eta

### Type of Server

Don't know

### Your Expectation

Prior to the 2.1.2.0, personal (and passive?) anchors would automatically wake up after a server restart when their owning player logged back in. This seems to be broken now, at least on eta.

### The Reality

When I log in after a server restart, I now have to visit each personal anchor to wake it up.

### Your Proposal

I looked at the source code for the feature and did not see any recent changes. The last one I can see is https://github.com/GTNewHorizons/Hodgepodge/pull/17 which adds some debugging support which may be useful in tracking this down.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
@boubou19 can you run `hp anchor list` when that user is logged on Eta?

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/Hodgepodge/pull/43
