### ISSUE TITLE
GT combs have shifted metadata

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#9161]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

A working setup after pack upgrade.

### The Reality

GT Combs metadata IDs have been shifted by +1, replacing all such existing items with a different version, e.g. all lithium combs before the update have become osmium combs (ID 10437:73).

Gendustry recipes have also been affected:
![image](https://user-images.githubusercontent.com/8459776/146460918-18a25475-1d99-4e95-b583-53882fc01a79.png)

Bees themselves still work as intended, and now produce the combs with the updated metadata.

### Your Proposal

If a bugfix release can be rolled out quickly, it's probably best to fix the metadata mapping so everyone gets his actual stock back.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
yea will move cryolite comb to the end

**Comment by boubou19** [comment]
fixed with https://github.com/GTNewHorizons/GT5-Unofficial/pull/817 Should be dropped on the officials by this weekend
