### ISSUE TITLE
Pressing "?" for automatically getting a recipe in ME pattern terminal ignores ore substitution

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#9162]
### Your GTNH Discord Username

CatsLeftEar#3300

### Your Pack Version

latest stable official

### Your Server

Epsilon

### Your Expectation

Be able to get a recipe with substitutions allowed, and not with only default items. 
![image](https://user-images.githubusercontent.com/67397297/146463260-305cd349-2429-48f6-926b-3fa7880745e5.png)

### The Reality

After getting a recipe through NEI into a pattern terminal, it uses only default item. 
Example: only ic2 lead dense plates and only this HV circuit can be used for this recipe.
![image](https://user-images.githubusercontent.com/67397297/146462951-2fcc6e9f-a8fc-4627-b457-4378acaa7840.png)

### Your Proposal

This is a new feature, i guess it needs some fixes. It should allow substitutions, and extra "ic2 dense lead plates" shouldnt be in the game at all

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by iouter** [comment]
try to update nee, the version of nee in gtnh is still 1.0.
https://www.curseforge.com/minecraft/mc-mods/not-enough-energistics

**Comment by vfyjxf** [comment]
In the latest version of NEE, you can use shift + mouse wheel to select the circuit board (place the mouse on the item after the transfer)

**Comment by Dream-Master** [comment]
i add it to us repo and make a version on Jenkins
http://jenkins.usrv.eu:8080/job/NotEnoughEnergistics/3

**Comment by Dream-Master** [comment]
@vfyjxf if you add new code maybe you can make a pr on my GTNH repo as well ?

**Comment by vfyjxf** [comment]
> @vfyjxf if you add new code maybe you can make a pr on my GTNH repo as well ?

I'll try, if I'm not busy

**Comment by Dream-Master** [comment]
kk just need to check why it is not building

**Comment by repo-alt** [comment]
Why even make a fork, if the mod is actively maintained?

**Comment by Dream-Master** [comment]
because i need all stuff in my Organisation. If some mod gets deleted by acident or not longer developed we get in trouble.
And i need it for the new build system.
