### ISSUE TITLE
Unequipping infinity chestplate while flying and dying from it generates infinite infinity chestplates as ghost items

### ISSUE THREAD

**Issue by Rubijox** [GTNewHorizons/GT-New-Horizons-Modpack#9166]
### Your GTNH Discord Username

Rubijox#7659

### Your Pack Version

2.1.2.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

1. Equip full set of infinity armor
2. fly up enough blocks so that falling will kill you
3. fly back down near the ground without landing
4. unequip infinity chestplate but keep it on the cursor
5. you die
6. there is an infinity chestplate on the ground and a grave nearby with the rest of your stuff

### The Reality

1. Equip full set of infinity armor
2. fly up enough blocks so that falling will kill you
3. fly back down near the ground without landing
4. unequip infinity chestplate but keep it on the cursor
5. you die
6. There is a grave nearby but no infinity chestplate on the ground(7 might only happen if the chunk isnt loaded when you click respawn)
7. Infinite infinity chestplates start appearing out of nowhere as ghost items that can't be interracted with except moving them(ie vaccum chest(doesnt pick them up, only moves them))
8. Rip framerate and tps as tens of thousands of infinity chestplates flood the world forever and lag everything.

### Your Proposal

no idea, I don't even know how this is happening.
Note: I wasn't able to reproduce this exactly is a singleplayer environment, but on a server this happens 100% of the time so far.
In singleplayer the infinity chestplate does vanish though. but it doesnt generate the infinite infinity chestplate bug.
It might also have something to do with the chunk you die in not being loaded when you click respawn, but i have no idea in reality.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Forever - does this persist after a world restart?

**Comment by Rubijox** [comment]
This does not persist after logging out of the server and logging back in, or after a restart.
https://www.youtube.com/watch?v=HRCCZDeF3u0 <vod showcasing the bug.

**Comment by bombcar** [comment]
Thank you - that's very weird, client side only. Something set it dead on server but that never got synced to the client.

@mitchej123 could this be similar to that thing we had with the XP orbs and infinite XP and draconic magnet?
