### ISSUE TITLE
Rare Earth Centrifuging

### ISSUE THREAD

**Issue by BigKeanerBigWeaner** [GTNewHorizons/GT-New-Horizons-Modpack#9168]
### Your GTNH Discord Username

EpicNinjaCrafter

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

Before updating to the newest release, rare earth was able to be centrifuged, and yielded some of the lanthanide series of metals, Upon updating to 2.1.2.0 rare earth is only processable through chemical bathing in other fluids through gt++. i would expect that rare earth is still processible through a centrifuge, unless this was nerfed in this update.

### The Reality

![image](https://user-images.githubusercontent.com/68492310/146478265-8de41871-d561-4c5e-9f31-e7b7861c121a.png)

rare earth can now only be processed through the gt++ methods. 

### Your Proposal

If this was intended ignore this, as it doesn't need to be fixed. However, if this wasn't intended add rare earth centrifuging back into the pack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Dream re-removed it in favour of the GT++ methods, which can yield all the same materials and more, just requires further processing.

**Comment by combusterf** [comment]
I would recommend updating the LV cadmium (battery) quests to remove rare earth references if this is indeed intended.
