### ISSUE TITLE
Both machine slots getting filled with same item

### ISSUE THREAD

**Issue by fourk** [GTNewHorizons/GT-New-Horizons-Modpack#9169]
### Your GTNH Discord Username

fourk#5436

### Your Pack Version

2.1.2.1-dev

### Your Server

sp

### Your Expectation

Both item slots in a machine should not be taken by the same item.

Ex: bio-diesel
NaOH dust, seed oil cell, methanol -> Bio-Diesel/Glycerol

This process requires all sides of the machine including a single side for accepting both NaOH dust and seed oil cells.
(1x fluid in, 1x fluid out, 1x both non-fluid inputs, 1x non-fluid output, 1x energy, 1x machine-face)

Before updating, this never resulted in 2 stacks of NaOH dust or 2 stacks of seed oil cells sitting in the reactor and shutting down all automation.
![image](https://user-images.githubusercontent.com/101964/146494098-721101ee-f022-4205-a1e8-8d4cd7a24c2d.png)

### The Reality

![image](https://user-images.githubusercontent.com/101964/146494124-46879467-085f-4aaf-8732-3a11841f4773.png)

### Your Proposal

Pipes and hoppers shouldn't push a second stack into a machine that already has a full stack of that item.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by iouter** [comment]
try to shift+rmb on the machine with a screwdriver. goldbrick sets the default mode to disable filter, and able multistack.
https://github.com/GTNewHorizons/GT5-Unofficial/pull/808

**Comment by GlodBlock** [comment]
shift+rmb the machine face with screwdriver.
![image](https://user-images.githubusercontent.com/60341015/146536973-0ff76642-716d-4917-9c44-f99cd0af0eac.png)

**Comment by Hachuurui** [comment]
This is happening again in version 2.1.2.3 despite shift right clicking with a screwdriver. It says filter on, but my mixer still fills with just one type of item in all slots. I have not tested other GT machines yet.

**Comment by Hachuurui** [comment]
This is happening again in version 2.1.2.3qf despite shift right clicking with a screwdriver. It says filter on, but my mixer still fills with just one type of item in all slots. I have not tested other GT machines yet.

The setup in my scenario is light fuel coming in on one side of the mixer, heavy fuel from the other, and output on bottom. Chemical reactors are directly inputting into the mixer. In 2.1.2.0, they limited to one item type per slot. Now that does not seem to be the case. I tried shift right clicking to set the filter to on but its still filling all slots
