### ISSUE TITLE
Recipe detection for valid item input from pipes to SB machines broken

### ISSUE THREAD

**Issue by fourk** [GTNewHorizons/GT-New-Horizons-Modpack#9171]
### Your GTNH Discord Username

fourk#5436

### Your Pack Version

2.1.2.1-dev

### Your Server

SP

### Your Expectation

![image](https://user-images.githubusercontent.com/101964/146595055-23cda324-28c6-43a0-bdc2-4a38e148ea75.png)

Ex: bio-diesel recipe. The chemical reactor should accept both NaOH dust and seed oil cells. When chemical reactor is in recipe-detection mode (since having it off is a non-option or it will fill both slots with NaOH dust), it should allow input of both non-fluid inputs.

### The Reality

The chemical reactor does not consider the seed oil cells to be valid input, so they sit in the pipe indefinitely when using gt pipes. When using eio item conduits, the extraction of seed oil cells from the canner never occurs.

If I manually insert a single seed oil cell into the chemical reactor, both pipe types change their mind about whether seed oil cells are valid input and will send seed oil into the chemical reactor until the chemical reactor goes back to a state in which there are zero seed oil cells inside the machine, at which point the process becomes indefinitely stuck.

### Your Proposal

Fix recipe detection mode

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Someone turned check stack size's default value to off without any second thought or search for usage.
