### ISSUE TITLE
Chem Plant not working correctly.

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#9173]
### Your GTNH Discord Username

Hyperic88 #3351

### Your Pack Version

2.1.1.0

### Your Server

Zeta

### Your Expectation

Ive tried to make Pine sapling in Exxon plant, have higher machine tier than required, same with power. It is formed and fluids/circuit is in place.

### The Reality

Machine won't start processing. 

![2021-12-18_01 53 21](https://user-images.githubusercontent.com/14223368/146623475-3cd5ccb4-cfbb-4072-98a6-073fb0118654.png)
![2021-12-18_01 53 07](https://user-images.githubusercontent.com/14223368/146623476-a8091acc-e330-41ff-b955-58f35a108051.png)
![2021-12-18_01 53 11](https://user-images.githubusercontent.com/14223368/146623477-df295dba-454d-412c-a55f-605277244eed.png)
![2021-12-18_01 53 17](https://user-images.githubusercontent.com/14223368/146623478-94dc9a2e-553b-4d30-90d7-ab6cc4fef8f7.png)
![2021-12-18_01 53 19](https://user-images.githubusercontent.com/14223368/146623480-f0a3edbb-b94f-4fd2-8053-2abbda14fc3c.png)

### Your Proposal

.Please check the recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Can you confirm any recipe works?

**Comment by Hyperic88** [comment]
it does, for example pinecone+ c14 works

**Comment by Hyperic88** [comment]
ok, this is weirder - after it went ok with that pinecone recipe, now it works even with this recipe... but it didnt before first runned with different recipe

**Comment by Hyperic88** [comment]
down the chain -> when processing pine wood to crushed pine materials, it does need a catalyst but it doesnt matter what type, tested two both worked and get used, even there is no catalyst needed in the recip
![2021-12-18_02 22 00](https://user-images.githubusercontent.com/14223368/146624227-0aad4709-429d-4f3a-8813-4c318d197fbf.png)
e

**Comment by bombcar** [comment]
Did it refuse to work UNTIL one catalyst recipe was done? Its there a catalyst now sitting in it?

Maybe my fix refuses to run if there is no catalyst, even if it doesn't use it ...

**Comment by Hyperic88** [comment]
no, it didnt worked UNTIL there was catalyst even its not mentioned (any type is valid i guess, tested two and both of them were used and decreased durability)

> Did it refuse to work UNTIL one catalyst recipe was done? Its there a catalyst now sitting in it?
> 
> Maybe my fix refuses to run if there is no catalyst, even if it doesn't use it ...

**Comment by Hyperic88** [comment]
@bombcar  Looks like machine wont work unless there is ANY catalyst :) tested another recipe that doesn't require catalyst and it didn't worked. When catalyst placed, it does.

**Comment by CharlieTuna8** [comment]
If for a recipe that doesn't use a catalyst, try removing the catalyst housing block.
My nitrobenzene started functioning after I did that.
