### ISSUE TITLE
[Railcraft] Liquid fueled boiler firebox voids Creosote from cells when is full

### ISSUE THREAD

**Issue by gabrielnoguerales** [GTNewHorizons/GT-New-Horizons-Modpack#9177]
### Your GTNH Discord Username

Gabr0#8004

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Liquid fueled boiler firebox should not consume GregTech or Industrialcraft Creosote cells when its internal tank is filled

### The Reality

It keeps consuming filled universal fluid cells or gregtech cells of creosote even when its internal tank is full. This behaviour doesnt happen when using bottles or cans from forestry

### Your Proposal

Only consume cells when its internal tank isn't full

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
In general railcraft and cells have a troubled history. But we now have the code maybe we can finally fix thsi

**Comment by YannickMG** [comment]
I believe GTNewHorizons/Railcraft#19  fixed this one.

**Comment by gabrielnoguerales** [comment]
Cool, thanks @YannickMG!
