### ISSUE TITLE
[NEI-CD]Make NEI-custom-diagram only show one recipe when click the tool

### ISSUE THREAD

**Issue by ArtherCasan** [GTNewHorizons/GT-New-Horizons-Modpack#9178]
### Your GTNH Discord Username

ArtherSnow#6574

### Your Pack Version

2.1.2.0

### Your Proposal

Make NEI-custom-diagram show **only one recipe** when click the tool by NCD interface, or make this function optional.
When I click the File and want to search this recipe.
![select_item](https://user-images.githubusercontent.com/45914538/146645155-7d1a6c83-7dba-41c5-a4cc-b5dc03572c90.png)
I get so many recipes about different material Files.
![recipes](https://user-images.githubusercontent.com/45914538/146645223-36b8b41e-3057-4f36-87a1-44b3b7a82377.png)
And then I find the Iron File which is the quest book tells me in page 82.
![82](https://user-images.githubusercontent.com/45914538/146645271-2c01aea8-9b3b-42ae-a459-b7aa1e070357.png)
I know the NCD can show the different material requirement about the tool, but it's not obvious for newbie.

### Your Goal

Show the only one recipe about tool part had been existed, and make the function for tool will make the NEI more frequent.

### Your Vision

Make NEI less jumbled and more direct.
especially for new gregtech player

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
one way would be to allow the devs to mark a certain recipe as "show first in NEI" - the quest related one.

Or add an NEI handler for the "autogenerated" recipes where the first shows the "generic" design "plate plate stick" or something.
