### ISSUE TITLE
Talisman of remedium procs repeatedly on things like warp blindness, dolly weakness, pollution debuffs, etc

### ISSUE THREAD

**Issue by dr-flop** [GTNewHorizons/GT-New-Horizons-Modpack#9179]
### Your GTNH Discord Username

drflipflop

### Your Pack Version

2.1.2.0

### Your Server

eta

### Type of Server

Don't know

### Your Expectation

The new (?) 2.1.2.0 blindness warp effect from warp theory gives the user 1s blindness multiple times when the warp effect is chosen. I believe this is indended to be a minor warp effect and I believe it starts happening at 5 warp which is very early on.

### The Reality

When wearing a Talisman of Remedium the talisman will proc every time the 1s blindness is added i.e. multiple times, and will lose durability every time. After a couple of hours (or less?) the talisman will be destroyed. This is a significant nerf to the talisman, especially considering it's very useful for removing other, more dangerous warp effects.

### Your Proposal

The best solution may be to make the talisman ignore blindness that lasts for ~2s or less - not sure how difficult that would be to implement.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
What does the talisman do if you dolly a chest? Does it ignore those effects somehow?

If so we should modify the talisman to ignore short-term blindness. I wonder what it does on blindness from nightvision in 2.1.1.0

**Comment by dr-flop** [comment]
Just tried it, it procs continuously when holding a chest with a dolly. I believe it would also proc continuously for nightvision blindness.

**Comment by bombcar** [comment]
So this is more of a talisman thing than a warp thing, really. Mind if I change the title?

**Comment by dr-flop** [comment]
Yeah go ahead. It's been brought by the change of the warp effect but the fix should be to the talisman if possible yes

**Comment by dr-flop** [comment]
I looked at the source for TT and it seems like an easy fix. I can give it a go, just need to figure out how to set up the environment for building the mod.

**Comment by Ethryan** [comment]
This isn't fixed by the linked pull, that only changes blindness effect to something else, 

The root cause "**Talisman of Remedium**" is unchanged.
