### ISSUE TITLE
Colour of text near invisible for railcraft solid fuel steam boiler after UI change

### ISSUE THREAD

**Issue by Volumetric-Nanometre** [GTNewHorizons/GT-New-Horizons-Modpack#9180]
### Your GTNH Discord Username

Alienableglove

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

1. Build railcraft steam boiler, 2x2 solid fuel base, 2x2x3 iron boiler.
2. Bring up the UI
3. Name of the machine is readable

### The Reality

The name of the machine is unreadable.
This happened after the move from 2.1.1.0 to 2.1.2.0 as the background changed from standard white-grey to black-grey brick. 

![image](https://user-images.githubusercontent.com/19982916/146653820-cfdc82ef-3c3d-4d72-8610-eb05e4d2e87e.png)

### Your Proposal

Change font colour to not clash with new background.

Sorry if not a bug, but as the change occured with the latest update I thought it best fit here. 
### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I _think_ this is fixed in dev, but NEIIntegrataions wasn't pulled into the build.

http://jenkins.usrv.eu:8080/job/NEI-Integration/lastSuccessfulBuild/artifact/build/libs/NEIIntegration-1.7.10-latest-packages-2-ga9bf709.jar

(delete your existing)

**Comment by Volumetric-Nanometre** [comment]
Ok, so I downloaded the .jar and copied it into the mod directory (replacing the existing) in the technic launcher.

This seemed to force a technic launcher relog (hu weird). 

Unfortunately this did not seem to change the UI 
![image](https://user-images.githubusercontent.com/19982916/146675293-cfe76876-fe2c-4fe7-b777-de9ade3d4440.png)

**Comment by leagris** [comment]
Blame https://github.com/GTNewHorizons/Railcraft/commit/9672e6b84a29d2ea7e2376e7531973cb4b085ce4?short_path=67c55d8#diff-67c55d8e203a9a9b73810ce1c627d8f7443b936761f0d09161a9122f81d888db

**Comment by Dream-Master** [comment]
can we not change the color of the text ?

**Comment by bombcar** [comment]
Ah this is not in the NEI screen. Yes text color needs to be changed with this background.

**Comment by DrParadox7** [comment]
Names are easy fixes and can be done through the lang files:
GTNewHorizons/Railcraft#12

![image](https://user-images.githubusercontent.com/47131096/147034112-8023cbaa-ff2d-46d2-914f-6dbb0b5f1f61.png)
![image](https://user-images.githubusercontent.com/47131096/147034126-802c0930-c8fb-44f3-b43a-83efaa030513.png)
![image](https://user-images.githubusercontent.com/47131096/147034140-87f3f6f0-10cf-4a92-b0be-d0daf421f1e9.png)

**Comment by leagris** [comment]
1. Changing the lang file will only "fix" `en_US` language, then issue will persist for other languages.
2. This text colour change breaks resources packs not using the new darker background texture.

**Comment by DrParadox7** [comment]
While I can easily address point 1, I cannot foresee whatever colour is used in backgrounds on your last point.

As I pointed out in my Pull Request, black will work fine and is visible in both the original _(and any TP that adheres to the original GUI)_ and the newer dark GUI.

![image](https://user-images.githubusercontent.com/47131096/147112547-eb354121-0ae6-4ec8-b231-e6421de86cfd.png)


However the same issue could occur if a black GUI is used, rendering the title illegible when it could have otherwise worked on grey.

The question I pose is:
To what lengths will GT:NH go to support texture pack compatibility?

I can change the colour of all text in question just as fast as you can revert my PR but ultimately a consensus needs to be reached first.

**Comment by bombcar** [comment]
I believe the correct long-term plan is to handle "Dark mode" in code somewhere deep in the UI generator.

For now, since the fix for en_US is merged, can you make a PR "fixing" the other languages? At least what we ship should be working.
