### ISSUE TITLE
Fluid detector cover

### ISSUE THREAD

**Issue by berta24** [GTNewHorizons/GT-New-Horizons-Modpack#9181]
### Your GTNH Discord Username

Bert24

### Your Pack Version

2.1.2.0

### Your Server

Private Online Server

### Type of Server

Vanilla Forge

### Your Actions

Removing a Fluid detector cover will 100% crash the client... 
Placing it it's pretty random, sometime it crash sometime it doest... 

Other ppl on discord had that problem too with 2.1.2.0

### Crash Report

https://paste.ee/p/Gejnp

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by berta24** [comment]
After a brief talk with Bombcar he suggested me to swap the Gregtech.jar with the newer version and  that indeed solved the problem, idk if it will break other things, gonna check tomorrow if i find something non working

**Comment by bombcar** [comment]
It may only happen on a client/server setup and not client only.

**Comment by bombcar** [comment]
@Glease it seems to be doing something with legacyCover on removal

**Comment by bombcar** [comment]
Apparently one player removing a cover can crash all players in the chunk/vicinity

**Comment by bombcar** [comment]
Apparently latest jar fixes it for both reporters

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/824 already.
