### ISSUE TITLE
Make the bot autoclose rotten draft/PRs from more than 2 monthes old

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9182]
If they got in the pending room that long, we can safely assume they'll stay here forever, therefore, we should close them. Owners of the drafts/PRs can always reopen them if needed.

**Comment by Dream-Master** [comment]
nah some old pr we need to re check and maybe add.

**Comment by boubou19** [comment]
yeah but we can always reopen them if needed, like the stalled issues. Like this PR is more than a year: https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/17 We should close it and maybe reopen it when needed and if it is needed

**Comment by Dream-Master** [comment]
yea but we remove the branh an the stuff is gone i guess

**Comment by boubou19** [comment]
Cant we restore the branches if needed with git?

**Comment by bombcar** [comment]
At least for awhile yes, but I don't know if they eventually get pruned.

**Comment by boubou19** [comment]
if it's from one of our branches to another, then as long as we don't touch the commit tree, it's fine. If it's from a fork, then they might delete the branch/stuff from it, and it might be a pain in the ass for us to recover, but i guess that if they deleted it, they thought it wasn't worth keeping anymore, therefore, it wasn't worth for us keeping too.

**Comment by repo-alt** [comment]
Not like we have overwhelming amount of abandoned draft PRs, I think they may be dealt with individually from time to time.
