### ISSUE TITLE
Let the minimap show the ore prospecting stuff

### ISSUE THREAD

**Issue by MrJakobLaich** [GTNewHorizons/GT-New-Horizons-Modpack#9184]
### Your GTNH Discord Username

MrJakobLaich#6170

### Your Pack Version

2.1.2.0

### Your Proposal

The minimap doesn't show what ores a chunk has prospected, as seen in the following image:
![image](https://user-images.githubusercontent.com/40965742/146660779-47d817f3-2f00-423c-af38-b87c9ff9bae3.png)

### Your Goal

Should show the ores:
![image](https://user-images.githubusercontent.com/40965742/146660798-59cafd18-7095-4594-a004-42d51bfc63ba.png)

### Your Vision

Would make sense and I wouldn't have to open the map every 5 seconds just to see what chunks have ores

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SinTh0r4s** [comment]
But you can open the map once and select the ore you are interested in. You may double click it to activate it. It will show like an active waypoint. Does that help you?
