### ISSUE TITLE
Steel chest showing as silver chest

### ISSUE THREAD

**Issue by CharlieTuna8** [GTNewHorizons/GT-New-Horizons-Modpack#9196]
### Your GTNH Discord Username

Charlie Tuna#7949

### Your Pack Version

2.1.2.0 

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Make a pattern for a steel chest in assembler.
![image](https://user-images.githubusercontent.com/38141544/146689704-a0f47f56-17a2-41f4-b0f4-5ed7e02d0f47.png)

### The Reality

Pattern says it's making a silver chest.
![image](https://user-images.githubusercontent.com/38141544/146689721-4f279321-3682-4ecd-880b-604c8433e7ca.png)

### Your Proposal

Make steel not poof into silver.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I am checking but it looks like we take the silverChest in IronChests and override it to be steel: 

```
src/main/java/cpw/mods/ironchest/IronChestType.java:    SILVER(72, 9, false, "Silver Chest", "silverchest.png", 4, Arrays.asList("ingotSilver"), TileEntitySilverChest.class, "mmmm3mmmm", "mGmG0GmGm"),
```

Iron-Chests.zs:

```
val SteelChest = <IronChest:BlockIronChest:4>;

// --- All Chests
recipes.remove(<IronChest:BlockIronChest:*>);

// --- Silver to Steel Chest
oreDict.chestSilver.remove(SteelChest);
// -
oreDict.chestSteel.add(SteelChest);
```

It should be possible to fix this by migrating the script into Ironchests itself.

**Comment by Dream-Master** [comment]
we should rename it in the mod itself

**Comment by bombcar** [comment]
I have a partial solution but getting permission for https://github.com/ganymedes01/IronChestMinecarts would help

**Comment by Dream-Master** [comment]
send him a Mail

**Comment by Dream-Master** [comment]
Ok we can fork the project

**Comment by Glease** [comment]
Should be fixed by https://github.com/GTNewHorizons/ironchest/pull/3
