### ISSUE TITLE
A mixin to stop recipes from bibliocraft from registering to the game

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9198]
The class `jds.bibliocraft.BiblioCraft` registers in its preinit the recipes from `jds.bibliocraft.blocks.BlockLoader#addRecipies` and `jds.bibliocraft.items.ItemLoader#addRecipies` but in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/scripts/BiblioCraft.zs we remove them anyways, before registering new ones. So it would be cool if we could get a  mixins in HodgePodge or anyother mod that does mixins to remove the calls of those `addRecipies` in the preInit.

**Comment by bombcar** [comment]
Reopening to remind me to remove the zscript remove

**Comment by boubou19** [comment]
@bombcar i'll work on the full migration of the bibliocraft script, so this can be closed
