### ISSUE TITLE
Server Crash upon removing Quantum Tank (Client Side Code in Server?)

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9199]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.0

### Your Server

private

### Your Actions

Removing a Quantum tank (iirc with a ~~Vajra~~ Wrench) crashed the Server.

### Crash Report

[crash-2021-12-20_03.49.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7742291/crash-2021-12-20_03.49.20-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by MMunier** [comment]
s/Vajra/wrench/
