### ISSUE TITLE
Unknown Crystal Shard Autoclave Recipe uses wrong amount of fluid

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9201]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

When crafting Unknown Crystal Shard with Mysterious Crystal Dust in an autoclave (in my case i'm using a 9 in 1 GT++) it should use 1000mb of distilled water

![javaw_bX7RBDgUbP](https://user-images.githubusercontent.com/17811922/146751478-8b03e14e-ee69-4a8a-ac7e-077696e9a6b9.png)
 

### The Reality

Sometimes it uses 800mb of distilled water instead of 1000mb
This is not happening everytime, but can change after a restart.
So sometimes it uses 800, sometimes 1000. NEI always shows 1000

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
sounds like two recipes for the same item fighting for being loaded first

**Comment by Dream-Master** [comment]
we have a circuit slot now and can add more than one recipe per input type
