### ISSUE TITLE
Genetics sequence not smeltable

### ISSUE THREAD

**Issue by maskota** [GTNewHorizons/GT-New-Horizons-Modpack#9203]
### Your GTNH Discord Username

Maskot#3548

### Your Pack Version

2.1.2.0

### Your Server

Private

### Type of Server

Single Player

### Your Expectation

Sequence is smelted to blank sequence

### The Reality

Sequence does not smelt.

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
There was a problem with hodgepodge. Try replace the one inside your `mods/` with [this jar](http://jenkins.usrv.eu:8080/job/Hodgepodge/64/artifact/build/libs/hodgepodge-1.7.10-1.6.18-5-ged853bf.jar)  and see if it solves your problem.

**Comment by maskota** [comment]
I had to upgrade Spongemixins to 1.4.0 but still it doesn't fix the problem.

**Comment by KamenriderZO** [comment]
Yes the same problem.I have to through away the useless scaned sequence

**Comment by KamenriderZO** [comment]
version 2.1.2,1 release too

**Comment by Glease** [comment]
The new ItemStackMap is too strict in NBT checking. Will fix later.
