### ISSUE TITLE
Add WAILA informations to the OpenComputer geolyzer

### ISSUE THREAD

**Issue by PoroCoco** [GTNewHorizons/GT-New-Horizons-Modpack#9204]
### Your GTNH Discord Username

PoroCoco#4636

### Your Pack Version

2.1.2.0

### Your Proposal

Add the WAILA informations to the OpenComputer geolyzer component.

### Your Goal

Right now with OC we cannot get the facing information of a placed GT block.

### Your Vision

This would allow OC robots to get more informations about the blocks around them and with these informations we could make new and better OC programs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I believe the discussion in Discord pointed out that WAILA knows the "facing" of a machine block somehow.

**Comment by boubou19** [comment]
when you look at a GT machine, waila displays the orientation of the machine

**Comment by repo-alt** [comment]
Getting WAILA information on server is really not trivial.

**Comment by PoroCoco** [comment]
Scanner information could also work for the facing direction if it's easier to do.

**Comment by bombcar** [comment]
Doesn't the block itself know which way it's facing?

**Comment by repo-alt** [comment]
It does, but looks like this information is not included in scanner output. Probably I'll just add this field to `analyze` output

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/146819568-34f90d77-a1c6-460e-8c37-dc1c61ffb347.png)
like this

**Comment by PoroCoco** [comment]
That would be really good ! 👍

**Comment by slprime** [comment]
![image](https://user-images.githubusercontent.com/31038811/147155600-f657b0fa-7c57-410a-b807-104346b54392.png)
analyze crops not works

**Comment by Retster** [comment]
Probably bloks without info about side cannot to return correct data after this change.

**Comment by repo-alt** [comment]
Yea I broke that, fixed in https://github.com/GTNewHorizons/OpenComputers/pull/44
