### ISSUE TITLE
What do we do to enhanced portals?

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9208]
As you might all have noticed, we have a mod called Enhanced Portals in the pack. It was litterally added to the pack just for Delta, before we had thermos plugins to the server (yes, it's more than 5 years ago 😂).

So should we remove it? or should we keep it and add recipes like we did with the stargate? It's basically the mystcraft portals, without mystcraft worldgen.

**Comment by MrJakobLaich** [comment]
Didn't know that mod existed lol
Read about it now, looks interesting, maybe it could be a precursor for the stargate tech?

(I don't know what people use for tp-ing, I use ftbutils and /home but that honestly feels like cheating)
Maybe it could be some early game waypoint teleport stuff? just some idea I came up with right now :D

**Comment by bombcar** [comment]
According to https://ftb.fandom.com/wiki/Portal_(Mystcraft) they will teleport ANYTHING which could be interesting (or lag inducing)

**Comment by joshaup1999** [comment]
Dont see how its anything like Mystcraft? I dont think it should be as far gated as the stargate, wouldnt make any sense. Should be around LuV/ZPM. Would be nice to have a mod that allows for interdim transport without being a stupid punishment

**Comment by boubou19** [comment]
> Dont see how its anything like Mystcraft?

it's basically the same mecanics as the mystcraft portals, but slightly better. Honestly, the mod is already covered by the dislocator receptacle.

**Comment by boubou19** [comment]
yeet hammer has spoken! https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/71ebc14d722042a7cd6c314157e722189b2e8b95
