### ISSUE TITLE
new cape types for the pack

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9209]
I thought about it and we should add more capes to the pack.
Right now the availiable capes through GT are:
- the GT cape
- the GTNH donator cape
- the GTNH dev cape
- the Tec cape
- some random capes added by greg to some players

I want to add more diversity for the donators, so we can make them have a different cape based on their donations.
Like capes for small donations, medium donations, extreme donations, and maybe also one for regular donators.

Maybe we could also add some meme ones too?

Code editing is trivial, main issue is to design the capes. Any input on that?

**Comment by bombcar** [comment]
Do you have an example of a cape texture file?

Also the "real deal" would be rocket capes heh - custom-looking rockets in game.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/tree/master/src/main/resources/assets/gregtech/textures
look for the cape textures
