### ISSUE TITLE
Mega Vac Freezer Should have minimum requirement for frost proof casing

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#9211]
### Your GTNH Discord Username

Hebi#2752 

### Your Pack Version

2.1.2.0

### Your Proposal

Mega Vac doesn't have any min requirements for frost proof casing, meaning
![unknown-29](https://user-images.githubusercontent.com/49487505/146861043-7b3de192-73b9-42bc-ac0d-4740ea11d1c3.png)
is an valid structure using only maint hatches and other hatches required. 

Another point is mega vac does not work with blueprints while mega ebf works, might be a good idea to integrate that too
![33ef086b9a28bd2e](https://user-images.githubusercontent.com/49487505/146861730-540a93d9-079e-4eeb-b5a1-6a75bab3db70.jpg)

### Your Goal

Mega Maint Vac is such a meme kek
And blueprint should work with mega vac as well

### Your Vision

no more ridiculous structure like this lmfao
and add bp support 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
With the upcoming extreme air intake hatch from GT++, I kindly ask to leave room for 256 of these as you can then 1-tick the air to liquid air recipe with max. parallels of the mega vac.
