### ISSUE TITLE
Travel Anchors can't be seen in some chunks

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#9214]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.0

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Use Travel Anchors to teleport from another anchor or with staff of travel

### The Reality

I cant say at what moment (happened on eta year+ ago also), but in this case after last update travel anchors in some chunks cant be seen from some other chunks. As example anchor isn't showing when you hold staff of travel in one chunk, but if you cross chunk border and try it from even further distance anchor can be seen again. Same happen with cross anchor movement. I cant teleport between 2 nearby anchors and have to teleport on third anchor far away to be be able move between first two. Can't see any noticeable correlation between distance or something else except that its based on chunks.
https://discord.com/channels/181078474394566657/522098956491030558/922803863688470538

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by nala2624** [comment]
This is still a persistant problem in 2.2.0.0. No solution found. No correlation found between chunks and when the anchors are visible.
