### ISSUE TITLE
Kinetic Wind Power HV (Quest Information Change)

### ISSUE THREAD

**Issue by Sederien** [GTNewHorizons/GT-New-Horizons-Modpack#9215]
### Your GTNH Discord Username

Sederien#4540

### Your Pack Version

2.1.2.0

### Your Server

Private Server

### Your Expectation

For the text below to be correct when referencing Windmills:

![image](https://user-images.githubusercontent.com/66249229/146950209-1764678a-be98-480f-8097-4d2402b601ea.png)

### The Reality

Windmills do use up rotors. So no need for the line, "Unlike the Windmill,"

### Your Proposal

As above. Small adjustment to the text.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Perhaps this indicates the windmill should _not_ use up rotors ....

**Comment by Sederien** [comment]
That would solve two in one: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9216

Rotors already have a chance to break (I think) in strong winds, so you can't just ignore them completely. But would need to ensure the box in the windmill doesn't get used for anything else before making it not degrade rotors.
