### ISSUE TITLE
Fluid filters forget their configurations upon restarting game

### ISSUE THREAD

**Issue by jonanlsh** [GTNewHorizons/GT-New-Horizons-Modpack#9217]
### Your GTNH Discord Username

jonanlsh#2693

### Your Pack Version

2.1.2.1-dev-test2

### Your Server

SP

### Your Expectation

Set my fluid filters to the following configurations
- Filter output, Whitelist fluid, Block output
- Filter output, Blacklist fluid, Block output

### The Reality

Upon closing the game and reloading, all fluid filters default back to
- Filter input, Whitelist fluid, Block output
This results in my quadruple and nonuple pipelines clogging up with fluid because the fluid filters aren't working as intended.

### Your Proposal

Have the fluid filter covers remember their last set configuration.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can you show a screenshot of your setup? I'm going to try to reproduce it.

**Comment by boubou19** [comment]
let me know if #9096 is not actually fixed, i'll reopen it instead, because it has more data.
