### ISSUE TITLE
Reimplement Multiblock Power Button

### ISSUE THREAD

**Issue by Aurastorm** [GTNewHorizons/GT-New-Horizons-Modpack#9219]
### Your GTNH Discord Username

Aura#0696

### Your Pack Version

2.1.2.0

### Your Proposal

Add TecTech's multiblock power button/indicator to StructureLib's multiblock GUI. 

### Your Goal

As a player, the utility of the power button existing on a majority of the multiblocks in one's base made me use and value it more than the added flexibility and meme potential of screnching them. Put simply, it was a good feature that did not detract from the GTNH experience.

Also who in their right mind makes an industrial-grade machine without a power switch? :p

### Your Vision

 - It is arguably easier (and certainly more consistent) to press a machine's power button than to scramble around to try and find your soft mallet because _why is this the only way I can turn off this thing I'm in a hurry_ **_I need to turn this O F F_**
 - Adding to the above point, it lessens the need to reserve an inventory/hotbar slot for your soft mallet for such occasions. It would still be a necessary tool for singleblock machines, but singleblocks don't void things when they don't get their way. 
 - It acts as a power state indicator as well, making the task of seeing whether your EBF is off due to power failure or simply inactive better than wasting 1-2 uses of your soft mallet, a method that really shouldn't need to exist, if you ask me. Cycling the power state of a machine simply to check said power state could also potentially end up voiding items, a harsh and unnecessary punishment when the machine probably already voided stuff by that point. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by YannickMG** [comment]
As an add-on point: Why would any machine past steam-tier not have an off switch? Why not add a power button to single-block machines as well?

**Comment by draknyte1** [comment]
What use does it have?

Only time I've ever seen the use is when I change coils and it needs a mallet whack. If you're turning multis off, you're doing it wrong. x]

**Comment by YannickMG** [comment]
There's a lot of doing-it-wrong in learning Gregtech isn't there? Inconsistent power supply to multiblocks is a common occurrence in low tiers (in my noob experience), leading to the multi shutting itself off and needing to be restarted.

**Comment by Aurastorm** [comment]
> As an add-on point: Why would any machine past steam-tier not have an off switch? Why not add a power button to single-block machines as well?

Possibly to give the soft mallet more of a use than just a crafting tool (like the file). It's still less of an issue compared to multiblocks as, again, singleblocks don't void. Also I assume that adding it to singleblocks would be more of a challenge since it's not just one mod to change. Idk exactly tho.

**Comment by GlodBlock** [comment]
soft mallet is an ass obviously, and there is no bad to add a button to control the machine.

**Comment by draknyte1** [comment]
It's a feature that wouldn't be in 90% of multis though. Beyond the EBF, you should know by the time you're making every other multi how to handle issues properly to not even need it.

**Comment by Aurastorm** [comment]
> What use does it have?
> 
> Only time I've ever seen the use is when I change coils and it needs a mallet whack. If you're turning multis off, you're doing it wrong. x]

Multiblocks are where some of your biggest early-in-the-tier power sinks are. You could easily use more power than you generate (even if it's just with the EBF on) until you upgrade powergen, meaning that unless you restrict the activity of said EBF by witholding inputs, your main way of toggling whether you drain or charge your batteries is by turning it on/off.

Also, we all make mistakes. Why is this multi in X processing chain not working? Oops, I voided M O R E...
Things like that.

**Comment by Glease** [comment]
It still serves a purpose doesn't it? It won't hurt to have it.
