### ISSUE TITLE
Assembler recipe conflict with garden soil and compressed dirt / sand

### ISSUE THREAD

**Issue by blattgoldowo** [GTNewHorizons/GT-New-Horizons-Modpack#9221]
### Your GTNH Discord Username

Эшли#1917

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I tried to craft garden soil in the assembler

### The Reality

since both compressed dirt / compressed sand and garden soil require the '1' circuit, it seems like it will only make the compressed dirt / sand no matter what.

### Your Proposal

change recipe to use a different circuit number, I guess.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Gateswong** [comment]
There is a work around you can do with item translocator right now, attached diamond nugget to the receiving one, to let it only transfer 4 for each to avoid compressing it.
