### ISSUE TITLE
AE Patterns shouldn't need to be made by players 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#9222]
### Your GTNH Discord Username

0lafe#3719

### Your Pack Version

2.1.1.4QF2

### Your Proposal

I think it would be nice if Opencomputers could be more dynamic with their AE pattern creation. At the moment it seems as though you either need to already have the items, or place ghost items in the database yourself. I think it would be nice if you could set items more dynamically without needing a copy of them. 

Another issue I'm noticing is that it seems like you cannot place patterns into an interface, and you need an already constructed pattern to edit. This drags the player into 2-3 manual tasks to even be able to use AE for pattern creation. It would be neat if there was a way to edit a blank pattern with OC, and or automatically place/remove patterns from interfaces. 

Alternatively I could see the questbook dealing with this in some way. Something like a quest that consumes 64 blank patterns and gives you every pattern needed for a given tier. Like all singleblocks, components, wires, plates, etc. This would be a lot less helpful, and couldn't cover many processes, but I think would still be a big help. 

### Your Goal

I think AE recipe creation sucks, and doesn't benefit the game in any way. It's basically required to do, but it's not something I would consider to be fun. This would allow players to entirely avoid creating any recipes by hand, as they could use a prebuilt list of patterns. This would allow a player to reach endgame without ever touching a pattern terminal, something that I think would be a net positive. 

### Your Vision

Imo this would remove something I personally find to be very tedious. I don't think it adds much to the game, and rather slows the player down with monotonous tasks. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
IIRC creating itemstack instance out of think air does not align with OC's design philosophy.

**Comment by 0lafe** [comment]
> IIRC creating itemstack instance out of think air does not align with OC's design philosophy.

Would there be another way to do it? Like a special API for patterns that takes an ID/metadata instead of an item stack?

**Comment by repo-alt** [comment]
> IIRC creating itemstack instance out of think air does not align with OC's design philosophy.

That was my first reaction too, but after thinkig a bit and some discussion, I now think that a database component method to create "item stack" (actually just fill database slot) is not really unthinkable. After all, database component was created exactly to abstract raw Java item stacks. I'm not yet sure about NBT representantion (LUA types don't really match NBT supported types), but a lot of the use cases don't even require NBT on the item stack

**Comment by repo-alt** [comment]
I added a function to set a database slot from item description in https://github.com/GTNewHorizons/OpenComputers/pull/45, but I have no idea where to add some functionality to create a new pattern from scratch. Theoretically it may look ok in the interface driver, requiring adapter with an inventory controller, and some inventory with blank patterns, but that would suck from usability point of view.
