### ISSUE TITLE
Oil distillation recipe conflict

### ISSUE THREAD

**Issue by Masztufa** [GTNewHorizons/GT-New-Horizons-Modpack#9224]
### Your GTNH Discord Username

Masztufa#7816

### Your Pack Version

2.1.2.0-dev1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Key: R = Raw oil, L = Light oil, H = Heavy oil, O = oil
number is the circuit in the machine

To get refinery gas you'd use R4, L4, H4 or O4,
for naphtha it should be a "*3" recipe,
for light oil a "*2"
for heavy oil a "*1" 

### The Reality

these recipes exist, however there's also recipes for:
R2, L2 making naphtha
R1, L1, O1 making refinery gas

For me this made heavy oil impossible to get from regular oil without a distillation tower

### Your Proposal

Remove the duplicate recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Masztufa** [comment]
edit: added discord number next to name

**Comment by Glease** [comment]
Please try again in 2.1.2.1. It should have been fixed by then. 

---

Sounds like a duplicate of #9172
