### ISSUE TITLE
disable view mode by default

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9226]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

make the view mode default off.

### Your Goal

Avoid drowning players with too much informations, especially when they are beginners. I was in voice chat with a players having difficulties to speak english, he was lost because of all the tabs being unlocked by default. 

### Your Vision

Making the view mode default off will make the guiding more explicit, so less confusion will happen

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I agree. A quest early on can mention it for those who want it.

**Comment by Dream-Master** [comment]
I turn it on because I thought people want it.

**Comment by mitchej123** [comment]
Make it optional, and a quest to tell people about it.

**Comment by Sederien** [comment]
The feature/button being available is AWESOME (and appreciated).

Apparently, being default on vs. default off (and then switchable to on by button) is confusing some newbies. Note that if there is no way to default off and keep the switching feature, then I would certainly prefer the feature stick around.

**Comment by Dream-Master** [comment]
It can only be on or off in settings ? What did you mean with optional ?

**Comment by Glease** [comment]
Set `View mode` to false and set `View mode button` to true.

**Comment by mitchej123** [comment]
hah, disabled by default.

**Comment by mitchej123** [comment]
What glease said.

**Comment by Dream-Master** [comment]
Hehe ok will try

**Comment by Dream-Master** [comment]
# If true, user can view most quests (not hidden or secret) [default: false]
    B:"View mode"=false

    # If true, show view mode button [default: false]
    B:"View mode button"=true


this it rn. So what i need to change ?

**Comment by boubou19** [comment]
hehe, looks like it's default to true in the server archive of the 2.1.2.0, need to check in later archive. But that highlights once more that some configs got mixed up between the archives.

But the quest is missing anyways, so still needs to be added right?

**Comment by boubou19** [comment]
a side quest with checkbox explaining the view mode for the curious players wondering what's after the quests they can see

**Comment by bombcar** [comment]
View mode persists on restart - is it stored in default quest.json like edit mode can be?

**Comment by Glease** [comment]
Config option. Button will save it to config. Presuambly it's also why dream now see false in his config file.

**Comment by YannickMG** [comment]
Has this been changed?
