### ISSUE TITLE
Required enchantment not listed for lootbag enchantment recipes

### ISSUE THREAD

**Issue by YannickMG** [GTNewHorizons/GT-New-Horizons-Modpack#9227]
### Your GTNH Discord Username

Yannick#5937

### Your Pack Version

2.1.2.0

### Your Server

private server

### Your Expectation

I expected NEI to tell me how to upgrade my lootbags, but it just tells me it needs to be any enchanted book. I'm told it specifically needs to be a Fortune III book but this isn't clear from the interface at this time.

### The Reality

The book's required enchantments are not listed.
![image](https://user-images.githubusercontent.com/5321549/147015976-b8386da4-93f6-4522-9455-dc4d97c48b3b.png)

### Your Proposal

Please have the recipe state precisely which enchantments must be on the book.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Mh i need to check nbt date in my script.
