### ISSUE TITLE
Pollution after Explosion

### ISSUE THREAD

**Issue by YanFett** [GTNewHorizons/GT-New-Horizons-Modpack#9228]
### Your GTNH Discord Username

reverse71

### Your Pack Version

2.1.2.0

### Your Proposal

After my Cleanroom exploded in my Base a chunk of it is completely unusable.
Could the amount of pollution created by explosions be reduced, so that it does not feel like a nuclear reactor exploded?

### Your Goal

Explosions create too much pollution.

### Your Vision

A world where Pollution is a manageable threat.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Do you have a scanner? Can you read pollution in chunk if you haven’t rolled back yet?

**Comment by YannickMG** [comment]
On the same version placing down a LV combustion generator and MV Miner under rain resulted in 4 million gibbl.

![image](https://user-images.githubusercontent.com/5321549/147024423-a25e6cca-3593-47d2-8de2-f3b36542d140.png)

LV combustion and HV disassembler also resulted in 4 million gibbl.

![image](https://user-images.githubusercontent.com/5321549/147026571-5a65f4a6-9eb4-4152-ad2a-5a6e102faaae.png)

So looks like current value is 2 million per machine?

**Comment by YanFett** [comment]
I tried recreating it with 3 HV and 1 EV machine and i get around 16 million gibbls.

**Comment by bombcar** [comment]
2-4m for an “explosion event” doesn’t seem unreasonable- but each event usually is multiple machines going off - causing it to skyrocket quickly.

**Comment by YannickMG** [comment]
I guess part of the problem here is that it's deemed unreasonable to plan for any number of your machines exploding, so there's never any incentive to use explosion resistant blocks to shield them?

**Comment by Dream-Master** [comment]
Yes explosion emit a lot of pollution. So better build a roof top to protect your stuff. The air filter works now btw and clean up the mess. Same for the scrubber.
