### ISSUE TITLE
New Lag Removal Tool.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#9229]
### Your GTNH Discord Username

StoneLegion#9999

### Your Pack Version

Newest

### Your Proposal

https://www.reddit.com/r/feedthebeast/comments/rlgk7i/i_made_a_16_round_semi_automatic_nuclear_cannon/

### Your Goal

Clean up bases that lag the server

### Your Vision

High TPS low Player Count 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Please refrain from using issue tracker from trolling people.
