### ISSUE TITLE
Apiarist's Pipe UI is not visible

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#9230]
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.1.2.0

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Tried to open apiarists pipe by right clicking on it.
![2021-12-21_19 48 58](https://user-images.githubusercontent.com/88752681/147032582-ab0b609a-b3c2-4c17-a1ec-c90f449b9017.png)

In previous versions, I would expect something like this...
![image](https://user-images.githubusercontent.com/88752681/147032731-ce9fdff8-fe10-42a0-b21c-c63fa538bebe.png)

### The Reality

No UI is shown when there normally would be one.
![image](https://user-images.githubusercontent.com/88752681/147032866-82d523bd-55fc-4096-bf13-cc3b29c7f7f6.png)

### Your Proposal

Revert UI functionality to how it was previously.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leagris** [comment]
Please tag this `bugMajor` because it makes this pipe unusable if you cannot configure it.

**Comment by bombcar** [comment]
Dammit GitHub

**Comment by OrderedSet86** [comment]
Just to be clear - the interface is still there. You can click on it if you do so very carefully, and the tooltip overlays will show up. Just completely invisible which makes it hard to gauge what bee species are currently being filtered.
![image](https://user-images.githubusercontent.com/88752681/147303180-9bacc415-6688-43ca-a669-6f3be148db65.png)

**Comment by bombcar** [comment]
Can you try with optifine and texture packs disabled

**Comment by OrderedSet86** [comment]
Optifine is already disabled (or at least the settings don't show up in the menu). Taking texture pack off didn't do anything
