### ISSUE TITLE
[Railcraft] Bore cannot be placed on rails

### ISSUE THREAD

**Issue by DrParadox7** [GTNewHorizons/GT-New-Horizons-Modpack#9231]
### Your GTNH Discord Username

TechnoParadox#6840

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

Tried placing a Bore on a rail anywhere in the world.

### The Reality

Bore popped off the rail everytime.

### Your Proposal

Bore gets summoned at 0,0,0 before updating its position and if liquid is at that location, in that dimension that coincides with its large hitbox then the bore becomes unplaceable.

Only occurs there's a pool of liquid (usually lava) near 0,0,0:
https://github.com/GTNewHorizons/Railcraft/blob/007f191fe53e6c39688fd9c414fd3123c5f1cc61/src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java#L195

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can the bore be summoned elsewhere or even at buildheight

**Comment by DrParadox7** [comment]
It will always be summoned at 0,0,0 no matter where you place it

**Comment by bombcar** [comment]
I mean if we Change the 0,0,0

**Comment by DrParadox7** [comment]
That could lead to unwanted consequences since nothing but bedrock is at 0,0,0 hence why it was working fine

**Comment by bombcar** [comment]
sounds like I need to build a bore hmmmm

if it's 0,0,0 we could place a cube of bedrock there on worldgen ...
