### ISSUE TITLE
The coin quest "Wood for Sheep" has a typo

### ISSUE THREAD

**Issue by FOOTMILK** [GTNewHorizons/GT-New-Horizons-Modpack#9232]
### Your GTNH Discord Username

N4M3_T1TL3_P3R20N#3173

### Your Pack Version

2.1.2.1

### Your Server

Zeta

### Your Expectation

I expected there not to be a typo.

### The Reality

There is a typo it says "crop sticks for coins and logs?" but only asks for a log.
![2021-12-21_23 38 27](https://user-images.githubusercontent.com/95777939/147041585-74c65377-dd48-4d12-a22a-55e324c54953.png)

### Your Proposal

Make it say "crop sticks for coins and a log?" instead of "crop sticks for coins and logs?" or make it ask for more than one log.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FOOTMILK** [comment]
This is VERY important by the why.

**Comment by bombcar** [comment]
🪵 4️⃣ 🐑 

l’ll grab this in the morning if nobody has fixed
