### ISSUE TITLE
Let players see Space Stations and Spaceships on the galaxy map

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/GT-New-Horizons-Modpack#9233]
### Your GTNH Discord Username

N4M3_T1TL3_P3R20N#3173

### Your Pack Version

2.1.2.1

### Your Proposal

Make players see each other's space stations and/or spaceships on the galaxy map. Maybe even let players request to "dock" at each other's space stations (aka letting people visit each other's space stations I don't mean adding a docking mechanic useless someone really wants to code that).

### Your Goal

It would add more life to severs and would help with emersion, it could also be a sort of bragging right to say, "hey I have a space station orbiting Venus" and then people could look to see if you had a space station.

### Your Vision

I have not seen any other pack do this so it could be a GTNH original feature, plus adding more stuff to space is always good due to the large amount of people who love space.
If you want me to explain more on the feature, I'd be more than happy to.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by glowredman** [comment]
This is a base Galacticraft feature. You can invite other people to your station by executing the command `/ssinvite <player>`. Regardless of that, space stations are always visible to other players.
The Mars and Venus space stations were disabled for a few updates now, *if* this was the cause, they are enabled again as of GalaxySpace version 1.1.9-GTNH.

Also, there are no space ships. There is [a mod](https://github.com/praecipitator/amunra) which lets you create space ships but it is not included in GTNH.

If this is still an issue with the latest versions of Galacticraft and GalaxySpace, we'll reopen this ticket.
