### ISSUE TITLE
Strange "save and exit" issue/rollback on client in singleplayer

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9238]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.1test

### Your Server

Single Player

### Type of Server

Single Player

### Your Expectation

Saving the world and reloading shouldn't roll you back at all.

### The Reality

I was testing the fluid covers, and found that if I loaded a world, throw something on the ground, change the cover, and save and exit, and then reload the world, the item will be back in my hands (and not duped on the ground) and the cover reverted.

It is apparently not saving the ... last second? Few seconds? Haven't dug into it tremendously deeply, but it happened multiple times and @jonanlsh had the same thing.

Waiting some time before save and exit makes sure your changes were saved.

### Your Proposal

Determine what isn't being synced/flushed on save and exit in single player, or make it pause long enough that it IS saved.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Confirmed that it is NOT aroma backup doing it - waited until it had finished and tested.

Apparently an "nbt change" on the cover isn't enough to be noticed, but if I place a block right after and save, this doesn't happen (block update marks the chunk "dirty" ?) or maybe the time to place the block just makes it take long enough.

**Comment by miozune** [comment]
Assume fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1001
