### ISSUE TITLE
VisualProspecting not working partly

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#9239]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

I want to find Bauxite ore vein on the moon

### The Reality

I put a Bauxite ore in the ore finder wand, put it doesn't react to the new Bauxite ore vein.
But if you left click on the ore
point has been set to the journey map.
But not automaticly add points when use it for scanning (Ore in wand doesn't work on the moon,maybe other non-vanilla demensions ?)
Nether and Overworld works very well!

### Your Proposal

if it can be developed?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Ore wand doesn’t work on moon and beyond on purpose.

**Comment by Dream-Master** [comment]
There are more issues with VP Beta25

You need to re-scann your underground oil stuff if join in sp
