### ISSUE TITLE
Server doesn't boot in v2.1.2.0

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#9240]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.0

### Your Server

private server

### Type of Server

Crucible

### Your Expectation

I updated the server with the following steps
1. Server backup
2. Delete config, mods, scrips folder
3. Copy v2.1.2.0 config, mods. scrips folder
4. libraries folder reinstall
5. server boot

### The Reality

server crash
I tried with crucible v4.1 and v5.3, but no luck.(v2.1.1.0 work well both)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7763857/latest.log)

### Your Proposal

fix it?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
try with 2.1.2.1

**Comment by Glease** [comment]
Quoting boubou's comment on a similar crash:
> disable opis
also make sure you don't have mobiuscore anymore in the mod folder if you use the old opis

**Comment by yukieiji** [comment]
I removed the Opis and it started. Sorry for the inconvenience.
