### ISSUE TITLE
Strange behavior of Projekt: Red

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9243]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

I want to request 8 medium lithium batteries from the warehouse

### The Reality

![ANDHJaP3Ge](https://user-images.githubusercontent.com/46845681/147142794-28fcdd47-4121-4c43-9467-dfaa07705c9f.gif)

### Your Proposal

Very strange behavior of the system

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eldrinn-Elantey** [comment]
The problem is that the system shows 8 medium lithium batteries and with multiple requests in the chat, a message is written about a successful request, but nothing comes and the number does not change in the interest

**Comment by OrderedSet86** [comment]
What is the unexpected behavior here? You started with 0. The PR system will not show more than 0 until said items have been crafted. You likely have a zero input crafting card which "outputs" medium lithium batteries, hence nothing happening when you request.

**Comment by Eldrinn-Elantey** [comment]
> What is the unexpected behavior here? You started with 0. The PR system will not show more than 0 until said items have been crafted. You likely have a zero input crafting card which "outputs" medium lithium batteries, hence nothing happening when you request.

Crafting medium lithium batteries (especially charged ones) is nowhere to be found. There were about 12 such batteries in the chests, but the system showed a much larger number and when I tried to call 1, nothing came, after I started spamming a lot, 12 batteries arrived, the number dropped to 8 and remained hanging. I went to check all the connected chests, found 4 batteries, took them myself from the chest and after that the number 8 disappeared in the request pipe

**Comment by Eldrinn-Elantey** [comment]
Today I noticed another moment. It turned out that when she requests items and their number does not change, in fact, the items are in the chest, but for some reason she cannot pull them out

**Comment by Eldrinn-Elantey** [comment]
At some point, the projekt red pipes simply stop pulling out items on request, even though they record their presence. If you break the pipe and put it in place (with the same chips), then everything works again
