### ISSUE TITLE
Auto Maintenance hatch stack limit

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9247]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.0

### Your Proposal

Auto Maintenance hatches do require 4 items, and have 4 slots. However, if inserting into them, they can become clogged with just one item unless you regulate that somehow. It would be nice if they automatically limit input items to one stack each, or if the slots even just take one specifiv item each, maybe shown as background texture (So, top left only circuits, top right only lube etc...).

### Your Goal

Make it less of an hassle to set up.

### Your Vision

It would be a nice QoL feature.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
Wasn’t recently a feature added to input busses to keep a max of one stack of an item inside? Try using screwdriver on the bus, there should be a message and it should keep 64 of a given item.

**Comment by Glease** [comment]
Maintenance hatch is not an input bus.

**Comment by GTNH-Afx237v7** [comment]
True, it is not. Didn’t have coffee before my reply :/

**Comment by Savallator** [comment]
Nice work...
