### ISSUE TITLE
Glowshroom Stew tooltip does not update when eaten

### ISSUE THREAD

**Issue by LucentFlame** [GTNewHorizons/GT-New-Horizons-Modpack#9248]
### Your GTNH Discord Username

Lucent#6884

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

Tooltip for item should say "Eaten: Assisted in Adding Hearts" once eaten.

### The Reality

Eating it does not update the tooltip.

### Your Proposal

Fix it pls bombcar

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can you do /mt hand on some stew and show results

**Comment by LucentFlame** [comment]
Epsilon has that command turned off. Also, I checked the food book and it counted, so the bug is purely visual at the moment.
