### ISSUE TITLE
Liquids stored in different containers do not show up in NEI

### ISSUE THREAD

**Issue by LucentFlame** [GTNewHorizons/GT-New-Horizons-Modpack#9249]
### Your GTNH Discord Username

Lucent#6884

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

Searching up a liquid should have all the container variations appear. This should include: buckets, bottles, cells, cans, refractory capsules, wax capsules, and glass cylinders.

### The Reality

Only a few appear in NEI, and which ones is seemingly arbitrary.

### Your Proposal

reminder requested by bombcar

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
The others are intentionally hidden for compactness reasons - but since many are actually eatable perhaps we should have a button or something that indicates more exist

**Comment by LucentFlame** [comment]
If it's intentionally hidden, then I'd consider the inconsistency of what is or isn't hidden a bug too. For example, Acid has the Bucket, Wax Capsule, Refractory Wax Capsule, and Can forms visible in NEI, but not the Glass Cylinder. Resin only has Bucket, Wax Capsule, and Can showing up. A bunch of liquids only have one of the variations visible.

**Comment by Glease** [comment]
Some are not hidden because they are not from a mod we actively maintain, e.g. GT, BW.

**Comment by D-Cysteine** [comment]
As a kind of work-around, you could enable the [Forge Fluid Containers](https://github.com/D-Cysteine/nei-custom-diagram/wiki/Diagrams#forge-fluid-containers) diagram (it's disabled by default), and it will show all registered Forge fluid containers for a liquid. Invoke it on a fluid by looking up either the block form of the fluid, the GregTech fluid display item, or any Forge fluid container containing that fluid.

Note that this does not work for fluid containers that aren't registered in Forge! This includes universal fluid cells, large fluid cells, the Witching Gadgets capsules, and most likely anything else that stores its contained fluids in NBT.

**Comment by KiloJoel** [comment]
I believe that the removal of witching gadgets capsules from NEI should be reverted. They are currently the cleanest way to look up recipes for fluids due to the low number of unrelated tabs that are generated.

Universal fluid cell - 9 unnecessary tabs
Regular cell - up to 4 unnecessary tabs (material parts, material tools, bottler, fluid canning machine)
Witching gadgets capsule - 1 unnecessary tab (fluid canning machine)
All others - don't exist for all fluids
