### ISSUE TITLE
Fishing Trap 2.0 Quest rewards silver chests

### ISSUE THREAD

**Issue by LucentFlame** [GTNewHorizons/GT-New-Horizons-Modpack#9250]
### Your GTNH Discord Username

Lucent#6884

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

Apparently it's supposed to be a Steel Chest?

### The Reality

It gives you Silver Chests.

### Your Proposal

reminder requested by bombcar

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I am working on this but it’ll be post 2.1.2.1 as it involves a tileetity remap
