### ISSUE TITLE
Biomes o Plenty Turnips are unobtainable

### ISSUE THREAD

**Issue by LucentFlame** [GTNewHorizons/GT-New-Horizons-Modpack#9251]
### Your GTNH Discord Username

Lucent#6884

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

Breaking a Koru has a 1/64 chance of dropping a Turnip seed from Biomes o Plenty.

### The Reality

It drops the Pam's Harvestcraft version of a Turnip Seed instead.

### Your Proposal

Allow it to drop the BoP version, or allow IC2 or Pam turnips to be converted to BoP's.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Just curious, why do you want the BoP version anyway?

**Comment by bombcar** [comment]
He’s on a quest to eat everything that can be eaten.

**Comment by Dream-Master** [comment]
yes we can add a recipe maybe.

**Comment by qunYp3dZSyLjoEoEg** [comment]
please reconsider. Even just a recipe turning a Pams Seed into a BoP seed in the crafting grid would be fine imo
