### ISSUE TITLE
Skeleton Trophy's quiver visually broken

### ISSUE THREAD

**Issue by LucentFlame** [GTNewHorizons/GT-New-Horizons-Modpack#9261]
### Your GTNH Discord Username

Lucent#6884

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

For the quiver to be attached to the Skeleton's back

### The Reality

Quiver disconnects from trophy model's hitbox while held or placced, and moves inversely relative to the player.
![image](https://user-images.githubusercontent.com/89005133/147285956-c66b4717-ce8e-4241-9194-c19d56279f85.png)
![image](https://user-images.githubusercontent.com/89005133/147285975-5d0353e5-7e79-4a7d-b038-d354b961cc9c.png)

### Your Proposal

make it not do that

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HeavenOfAngels** [comment]
![2023-04-19_00 55 00](https://user-images.githubusercontent.com/131214549/232925723-77f7402b-69b3-405b-a2e7-00743aa0f853.png)

I have this issue when placing the skeleton trophy. Removing the trophy removes the quiver, replacing the trophy brings the quiver back. It moves funny (almost inverted to my movement) when I move, but never up or down.
