### ISSUE TITLE
Crash upon leaving Twighlight forest and entering Overwold.

### ISSUE THREAD

**Issue by OlegLyakh** [GTNewHorizons/GT-New-Horizons-Modpack#9262]
### Your GTNH Discord Username

Lemon_Cake#2301

### Your Pack Version

2.1.1.0

### Your Server

Lan Server, but crash happens without opening to Lan too.

### Type of Server

Single Player

### Your Actions

Going into a new dimension, 4 times now, but typing / also triggered a crash.
I am in an AFK twighlight forest box and if I go back to overworld, crash time. 4 crashes, a fifth if you count my opening chat to / which also caused one.

### Crash Report

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7771370/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
looks like a memory issue? How muh ram your game is using ?

**Comment by OlegLyakh** [comment]
16G

**Comment by Dream-Master** [comment]
mora than enough

**Comment by OlegLyakh** [comment]
16Gb* and 64GB total on PC sorry

**Comment by Dream-Master** [comment]
1. Update to 2.1.2.0 or 2.1.2.1 and see if it still exist
2. we add a mod maybe this helps  http://jenkins.usrv.eu:8080/job/Netty-Patcher/

**Comment by OlegLyakh** [comment]
sorry report is wrong, it is current patch
either way how would I go about adding this mod and furthermore would the 3 others I play with need it too?

**Comment by bombcar** [comment]
If you’re on latest you have it

**Comment by draknyte1** [comment]
> 1. Update to 2.1.2.0 or 2.1.2.1 and see if it still exist
> 
>     2. we add a mod maybe this helps  http://jenkins.usrv.eu:8080/job/Netty-Patcher/

NettyPatcher only fixes crashes on server list menu. TickingMemory has nothing to do with Netty.

> 16Gb

Too much, allocate 6-8.

**Comment by bombcar** [comment]
```
[20:56:38] [Client thread/INFO]: Mapping halted in C:\Users\lyakh\AppData\Roaming\.technic\modpacks\mcnewhorizons\journeymap\data\sp\World\DIM7
[20:56:39] [Server thread/ERROR]: Chunk file at -26,82 is in the wrong location; relocating. (Expected -26, 82, got -27, 83)
[20:56:39] [Server thread/ERROR]: Encountered an unexpected exception
```
I *think* that's just journeyman being journeyman but ... 

`Java Version: 1.8.0_51, Oracle Corporation`

You have a very old version of Java - if possible upgrade to a more recent version of Java 8 - something like https://adoptium.net/?variant=openjdk8&jvmVariant=hotspot is not 100% going to help but can't hurt.

**Comment by draknyte1** [comment]
> 1.8.0_51

This is bundled with curse and other launchers. They can’t update it.

**Comment by OlegLyakh** [comment]
> > 1. Update to 2.1.2.0 or 2.1.2.1 and see if it still exist
> >    
> >    2. we add a mod maybe this helps  http://jenkins.usrv.eu:8080/job/Netty-Patcher/
> 
> NettyPatcher only fixes crashes on server list menu. TickingMemory has nothing to do with Netty.
> 
> > 16Gb
> 
> Too much, allocate 6-8.

will try 6 then

**Comment by bombcar** [comment]
As a note - with 64 GB of RAM you could easily run a "server" on your PC and connect to that instead of Open to Lan - the end result is the same but it may be more stable. You don't need to forward ports from "outside" or anything for it to work.

**Comment by OlegLyakh** [comment]
> As a note - with 64 GB of RAM you could easily run a "server" on your PC and connect to that instead of Open to Lan - the end result is the same but it may be more stable. You don't need to forward ports from "outside" or anything for it to work.

That was my old setup I actually plan to return to I did upgrade my PC for this. However I am on uni internet and for some reason my uni doesn't want me to open up ports willy nilly I do wonder why. Also don't exactly have access to the uni router since its kinda building.

**Comment by OlegLyakh** [comment]
8GB ram, crashed.

**Comment by OlegLyakh** [comment]
2.1.2.0 is the patch.

**Comment by bombcar** [comment]
> my uni doesn't want me to open up ports willy nilly I do wonder why. Also don't exactly have access to the uni router

Open-to-LAN opens a port on your machine, just as running a server on your machine would do. People on your LAN could connect to it directly.

If you want you can try 2.1.2.1 but you have some corruption - do you have a place you can upload a zip of the worldsave?

**Comment by OlegLyakh** [comment]
> > my uni doesn't want me to open up ports willy nilly I do wonder why. Also don't exactly have access to the uni router
> 
> Open-to-LAN opens a port on your machine, just as running a server on your machine would do. People on your LAN could connect to it directly.
> 
> If you want you can try 2.1.2.1 but you have some corruption - do you have a place you can upload a zip of the worldsave?

fair enough. Well open to lan worked on uni internet, but I did ask my uni about port forwarding and they said no. Regardless I do have a zip of the world save, best bet for uploading it?

**Comment by draknyte1** [comment]
LAN is broken and unsupported.

**Comment by OlegLyakh** [comment]
this is currenty happening without open to lan, in a singleplayer world.

**Comment by bombcar** [comment]
Google Drive might take a file that big, dunno.

**Comment by OlegLyakh** [comment]
https://drive.google.com/file/d/1okagvyOV-gu5uDS2CbDiyutTl9y1VY7B/view?usp=sharing

**Comment by OlegLyakh** [comment]
world save

**Comment by OlegLyakh** [comment]
Am in Twighlight forest, crash on loading overworld

**Comment by bombcar** [comment]
Finally got this downloaded, let's take a look

**Comment by bombcar** [comment]
https://github.com/Fenixin/Minecraft-Region-Fixer/wiki/Usage may help on something like this.

There is a corrupt region file r.-1.2.mca

Restoring from backup is likely the easiest solution, but if desired a region fixer may be able to recover.

As a reminder for those watching at home, backups are good, open to lan is scary. Incremental backups using something like https://en.wikipedia.org/wiki/Duplicity_(software) (Linux) or something similar can save a ton of space, and you can restore a single region file if needed.

**Comment by OlegLyakh** [comment]
Used a backup with a functioninig region. Slight setback but the every 30 min backup system was really handy here so I real example of use backups please. With that, problem solved at least temporarily, thanks for all the help everyone!
