### ISSUE TITLE
Implement the Chloroalkali Processing Line

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#9264]
### Your GTNH Discord Username

Hebi#2752 

### Your Pack Version

2.1.2.1

### Your Proposal

IRL, Chlorine, Hydrogen and Sodium Hydroxide are obtained in large quantities from Sea water
by electrolysis using Mercury and Graphite. 
The Sodium obtained forms an amalgam with mercury and reacts with water to form NaOH and H2. With chlorine releasing directly as a gas. 
A new multiblock unlockable at hv can be designed to consume the cathode and anode, using a small random amounts of graphite electrode and mercury fluid to mass produce the three outputs from salt water with a bigger input and output amount. 
Instead of the two step electrolysis we have right now, and a multi block that's before the large electrolyzer for this line specifically. to solve the hv chlorine or that most players face, without having to always rely on single block electrolyzers or tearstalks
There's also an suggestion to the NaOH processing, instead of having sodium being a loss that's handwaved away for balancing water electrolysis, change it so that it needs molten salt to be electrolyzed and make it lossless. 
It doesn't have to be explicitly a new liquid, just ramp up the power cost to make sense thematically and the baseline is to make mass conserve,not handwaving it away for balance issues that can be addressed in other ways. 

### Your Goal

HV requires a lot of chlorine for Titanium, and often moon salt water drilling or tearstalk is suggested. And salt water production is often lacking in large amounts, this can also be used as an endgame solution for producing large amounts of chlorine, H2 and NaOH 

### Your Vision

it'll make hv chlorine production faster, and end game production doesn't rely on the large electrolyzer that much

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
Player is supposed to have problems when first encountering something, I'd expect something like that to be added at EV/IV or even later so the chlorine isn't abundant that early.
Another problem is that chlorine is supposed to be limited (moon makes it much more accessible but it's still used in quantities that encourage player to do recycling) and making it from seawater makes things just too easy, especially because only graphite and mercury are used since both of them are plentiful. Possible solutions to this problem are for example high cost of electricity and more expensive anode materials.

imo this is a very good idea but requires some changes

**Comment by tommy307507** [comment]
Oh and as to clarify, I am NOT suggesting seawater to be added in the ow and allowing players to use it to produce chlorine.
But make moon's salt water able to be processed in this new method. So it'll automatically be limited to be used effectively after moon, but will make chlorine plentiful once player start drilling the salt water and using this method.

**Comment by Pxx500** [comment]
> Oh and as to clarify, I am NOT suggesting seawater to be added in the ow and allowing players to use it to produce chlorine. But make moon's salt water able to be processed in this new method. So it'll automatically be limited to be used effectively after moon, but will make chlorine plentiful once player start drilling the salt water and using this method.

I misunderstood, that solves the problem. Maybe different anodes could be used to make the process more efficient the better material is used?
