### ISSUE TITLE
Custom Quest preserving on pack update

### ISSUE THREAD

**Issue by ducanh2002123** [GTNewHorizons/GT-New-Horizons-Modpack#9265]
### Your GTNH Discord Username

Xx__THK__xX#2744

### Your Pack Version

2.1.2.0, but updating to 2.1.2.1 soon

### Your Proposal

Add the ability to preserve custom quest that the server admins/owners created when updating to a new pack version and running /bq_admin default load

### Your Goal

Well, for some servers, esp private ones, there are some custom quests that are made to either make player life less painful or to just overall make the coins a bit more useful, but whenever the server do an update, then all of the quests just disappears, forcing owners/admins to recreate the quests all over again, currently, there are 2 ways to preserve it, which is 
1. copying the quest database file, and then adding the relevant quests back into the main DB after the update. but It's very time consuming and is not always guaranteed that nothing will go wrong when you do so, such as quest id being taken by another quest
2.  Recreating each quest from scratch, which again is a PITA, and will take a very long time to do, esp if the server have a lot of custom quests

### Your Vision

it'll make updating the pack on servers with custom quests much less painful, because as of right now it's already a PITA for me to recreate all of the quests (and I only have like 12 quests, imagine it with a server with more than 50 or 100 quests)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Why not share you quests with us or they so server specific we can’t add ?

**Comment by Dream-Master** [comment]
Use quest ids >5000 to prevent Id overrides

**Comment by Dream-Master** [comment]
And no there is no easy way to add own quests after an update.

**Comment by bombcar** [comment]
> Why not share you quests with us or they so server specific we can’t add ?

They’re for things you may not want like repeatable quest for 🪙 to brewstand. Other examples could be quest describing MyTown or chunkloader coin policies, etc. 

If high quest numbers are available something might be able to be worked out. 

Let me see how hard it might be to add instructions on how to do this. 

Alternatively zscript can add server specific recipes.

**Comment by ducanh2002123** [comment]
> Why not share you quests with us or they so server specific we can’t add ?

they're server specific and is.. ungreg-like so adding it to the main game is a big no no, for my exact case it's quests to buy the first circuit for each voltage (as in Basic circuit for LV, Good Circuit for MV, Advanced Circuit for HV, etc etc), it helps to make some stuff less painful, while also giving more uses to the coins that you gets from other quests or grinded from the Kill All The Thing tab. 

(and also some quests to convert from a coin type to another, some coins are just very much unused so i allowed exchange to another type, of course at a cost too, and those takes  a long time to add.. because a lot of coin type)

**Comment by bombcar** [comment]
The biggest thing custom quests vs a recipe gives you is time gating - a recipe can give you X for Y but a quest can do the same and only once a day

**Comment by ducanh2002123** [comment]
and commands, but i do have time gating on my custom quests as well, although not having time gating at all would probably be fine.. i think, plus i'm still thinking on how the hell am i going to put 1000 coins in a crafting recipe so

**Comment by boubou19** [comment]
If you modify the quests to add various custom quests, then you update, be sure to merge manually your quests in the questfile, as updating the pack without doing this will just overwrite your work. I don't really see what we can do, as we don't really support this case, because you bring your own modifications to the modpack. It is expected that you know what you do.

**Comment by ducanh2002123** [comment]
> If you modify the quests to add various custom quests, then you update, be sure to merge manually your quests in the questfile, as updating the pack without doing this will just overwrite your work. I don't really see what we can do, as we don't really support this case, because you bring your own modifications to the modpack. It is expected that you know what you do.

yeah... i know.. already been though there when updating from 2.1.1.0 to 2.1.2.0, so i know what i'm doing, i'm just making this suggestion because i really think something to aid with that process would really be helpful

**Comment by bombcar** [comment]
The main thing that I can see that would "help" is a way to say that new quests added in start at >5000 or similar, so they don't collide and can be re-merged.
