### ISSUE TITLE
Add recipe conflict test machine

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9266]
### Your GTNH Discord Username

Bombcar

### Your Pack Version

2.1.2.1

### Your Proposal

We should add a machine (possibly no recipe for it as it would be for debug) that you can put a potential recipe into and it tells you of any conflicts. 

### Your Goal

Reduce things like https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8601 using strange number circuits by allowing pack developer to test a recipe in game without the add/compile/run/conflict test. 

### Your Vision

The machine or mutliblock would have a grid (possibly large enough to imitate the assline) and a slot for a machine. You’d put in random items into the grid, add your circuit and fluids if needed, and put the machine you want tested in the machine slot. 

Then the code would check if that theoretical “recipe” would conflict with anything. If not - greed light. If it would conflict with an existing recipe - red light (and potentially what it conflicts with). 

If we got real fancy it could dump the recipe code to the log, but that’s probably unnecessary. 

Said machine would make it easier for players to “do the grunt work” of working out what a new recipe would look like, and help devs avoid recipe conflicts. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by YannickMG** [comment]
Why would this need to be a machine rather than a scripted test as part of CI?
