### ISSUE TITLE
Make the OpenBlocks sprinkler placeable on top of GT pipes

### ISSUE THREAD

**Issue by blattgoldowo** [GTNewHorizons/GT-New-Horizons-Modpack#9267]
### Your GTNH Discord Username

Эшли#1917

### Your Pack Version

2.1.2.1

### Your Proposal

change to allow the OpenBlocks sprinkler to be placed on top of GT pipes so that you can pump in water from the bottom instead of having to pump it in from the top.

### Your Goal

It looks stupid to have to pump in the water from the top and makes no sense.

### Your Vision

sprinkler would be more convenient to use and farms would look slightly less hideous when using it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Florexiz** [comment]
Have you tried placing cover on pipe and allowing fluid throughput with screwdriver? You can place things on cakes and puppies then

**Comment by blattgoldowo** [comment]
yeah, that does seem to work afterall

**Comment by blattgoldowo** [comment]
I guess I should close the issue now that I know that it does work and doesn't really need any changes
