### ISSUE TITLE
if the last step of a quest is completed, the quest should be completed

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9268]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

My suggestion is that if a player manage to craft the last step of a quest without doing the intermediate steps, then it should be still completed, as the intermediate steps are here to guide the player. So if he managed to go through all the steps alone, we shouldn't punish him. A player managing to use NEI on his own should be encouraged IMO

### Your Goal

This remove all the issues of "crap, i did the last step without seeing those intermediate steps" and all the issues of "fuck this chemical quest, i made all my line use multiblocks so it only use fluids, but the quest asks for cells of each intermediate step".

### Your Vision

This would add a QoL addition to the pack, as the quests are mainly here for the informations given through them, not here to piss players.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Is this on the higher quests or more in the crafting quests areas?

I agree cell holding is annoying once you’re past the LCR though if you automated the line grabbing some cells isn’t insanely hard.

**Comment by Volkoff96** [comment]
@bombcar I came across this already at the very beginning, in the quest "Blast Furnace", where you first need to accumulate 400+ bricks, only then melt them, it slows down progress, I really didn't like it, then I just got used to it, but I've encountered it more than once, it will be very cool if it is implemented.

**Comment by Dream-Master** [comment]
> ### Your GTNH Discord Username
> boubou_19#2706
> 
> ### Your Pack Version
> 2.1.2.0
> 
> ### Your Proposal
> My suggestion is that if a player manage to craft the last step of a quest without doing the intermediate steps, then it should be still completed, as the intermediate steps are here to guide the player. So if he managed to go through all the steps alone, we shouldn't punish him. A player managing to use NEI on his own should be encouraged IMO
> 
> ### Your Goal
> This remove all the issues of "crap, i did the last step without seeing those intermediate steps" and all the issues of "fuck this chemical quest, i made all my line use multiblocks so it only use fluids, but the quest asks for cells of each intermediate step".
> 
> ### Your Vision
> This would add a QoL addition to the pack, as the quests are mainly here for the informations given through them, not here to piss players.
> 
> ### Final Checklist
> * [x]  I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying _I like this change please reconsider adding it_ will prompt us to investigate and reopen it once we confirm your report.
> * [x]  I understand this change request may not attract enough attention and thus not be implemented.
> * [x]  I understand this change request may be rejected due to other community members think it's inappropriate.
> * [x]  I believe this feature would make the pack better.

Not every lastest task is the main quest task. I am against it. There are other ways to rework quests

**Comment by boubou19** [comment]
> Is this on the higher quests or more in the crafting quests areas?

It's a general though. In my case, because i am in UHV since a couple of years now on delta, i had 3 questbook resets, so i had a lot of stuff already. It was really painful to redo the quests again, because draconic cores are still gated behing the T8 rocket quest. I cursed a lot when doing it.

> Not every lastest task is the main quest task. I am against it. There are other ways to rework quests

Yeah sure maybe not every quest, but i think chemical quests and side quests should have it tho.

**Comment by boubou19** [comment]
at least every quest that doesn't have the crown icon should get that imo

**Comment by Sphyix** [comment]
Some quests with crown should get it as well.
I remember having issues with rockets, you need to hold every part of it in your inventory to complete it.
If I know how to craft it i don't want the quest to not complete.
This is the same for every quest that has middle steps, and require the final item aswell.

I know for the chemical lines is "not a big deal" but why does it need to be so annoying anyway?
It makes it feel like the quest book is something that is just annoying to do and tedious.

Since the questbook is used as a sort of wiki to make players understand the game, why does it need to be so difficult and annoying to complete?

**Comment by bombcar** [comment]
Perhaps some quest should be split. One quest to gather rocket parts (no reward, not mandatory) followed by the quest to have the 🚀. 

Either way people in a group can cheese it but nobody cares

**Comment by Sphyix** [comment]
> Perhaps some quest should be split. One quest to gather rocket parts (no reward, not mandatory) followed by the quest to have the 🚀.
> 
> Either way people in a group can cheese it but nobody cares

People in a group, if they play on their own server, they can just cheat it.
I don't think the pack should even consider stopping players from cheesing stuff when playing as a group. Blocking something can just make them cheat it in cause otherwise it's just annoying

**Comment by bombcar** [comment]
Yeah the case where you have admin can be disregarded (in fact as admin on our server we can and will resolve quest book errors in favor of the player usually under supervision). 

I think specific annoying quests can be marked for discussion and review (or the “type”) - like rocket quests after a certain tier. 

I know I was annoyed by the requirement to hold a tier 1 lander for … Mars? When I had got a tier two somehow already heh.  But I do feel we shouldn’t encourage “handmedowns” on public/official servers.

**Comment by bombcar** [comment]
A better questing feature that would *help* with these would be the ability to mark a quest as “fuzzy” with a percentage - if complete=80 say it would let you complete the quest if you have finished the final (last) objective AND have finished 80% or more of the other objectives (and that could count 8/10 as 80% in a objective itself - and let you complete. 

Default to off/100% and allow override on specific quests that should be bypassable.  Don’t advertise it but people replaying would know heh.

**Comment by YannickMG** [comment]
Could specific objectives of a quest be marked as optional?

For example, any quest which required you to 1) get the materials for a craft and 2) have the item resulting from that craft could be made to have only the last step needed for quest completion.

The other objectives could be called "hint" objectives and be fully optional, and that would reflect the way they've been used in the questbook, to give you hints as to what materials you should gather.

**Comment by boubou19** [comment]
On the topic of player groups cheesing the questbook, there is nothing preventing them from doing it: the last thing implemented to only make one quest loot per quest party is 100% bypassable, and it's so easy it's ridiculous.

**Comment by bombcar** [comment]
Yeah honestly the bigger one (for me anyway) is the temptation to help new players by giving them things. :D
