### ISSUE TITLE
Crash when browsing NEI while inside compressed chest GUI

### ISSUE THREAD

**Issue by blattgoldowo** [GTNewHorizons/GT-New-Horizons-Modpack#9272]
### Your GTNH Discord Username

Эшли#1917

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Actions

sometimes when browsing NEI while inside a compressed chest the game will crash. This happened multiple times to me so I decided to post about it here.

### Crash Report

https://pastebin.com/ZLQVdhUg

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Can you take a screenshot of what it looks like before crash? Maybe some of the code used to move NEI out of the way can get confused

**Comment by blattgoldowo** [comment]
what do you mean by what it looks like before it crashes? It just kinda freezes the game and 3 seconds later closes it. Or if you mean in the logs then there seems to be nothing as far as I can tell.

**Comment by bombcar** [comment]
You mean how big your screen is, how much of NEI is showing, things like that. 

Doesn’t need to be f before a crash just want to see ui size and how NEI and the chest look like

**Comment by blattgoldowo** [comment]
Here is a screenshot: https://imgur.com/a/TBHz3CO
Here is relevant info from fml-client-log: https://pastebin.com/pTHgPQ3x
Here is my GregTech.log file: https://pastebin.com/QcJCyEHZ

**Comment by Glease** [comment]
I'm not sure why there is no stacktrace. Without it it's impossible to debug. If you have another crash report with stacktrace (i.e. some lines like `at com.mojang.foo.Bar` after ClassCastException) it'd be very helpful, but the one you attached here is not very useful.
