### ISSUE TITLE
Charcoal Pile Igniter turns off on 100sec

### ISSUE THREAD

**Issue by sethdark** [GTNewHorizons/GT-New-Horizons-Modpack#9273]
### Your GTNH Discord Username

SethDark

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The CPI should work for 424sec to finish the cycle, and create charcoal from the logs

### The Reality

everytime it stops at exactly 100sec.
I've tried:
- using bricks on top (doesn't even start)
- using bricks around the edge of the pile so there would be no spread ticks (doesn't even start)
- letting all the dirt spread to grassblocks first, still stops at 100sec
- removing all the grass/plants around the pile
- wacking /replacing it

### Your Proposal

make it work? :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by sethdark** [comment]
- Update
When I wack it with a Rubber mallet (instead of wooden one) it instantly turns all the blocks in to brittle charcoal

**Comment by GlodBlock** [comment]
seems similar to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9055

**Comment by YannickMG** [comment]
Fixed by GTNewHorizons/GT5-Unofficial#859
