### ISSUE TITLE
Add ME input bus

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#9274]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.0

### Your Proposal

Adding an ME input bus

### Your Goal

With the addition of the ME output bus, we got rid of the output bus + conveyor + interface combo and reduced cpu usage on high throughput applications, most prominently ore processing.
However for inputting items into an input bus, we are still using techniques such as conveyor + item pipe + enderio item conduit or interface plus conveyor into input bus.
I therefore suggest an ME input bus that allows direct access to AE inventory to reduce cpu usage for item transfer even further.

### Your Vision

Implementation wise I can currently only think of ore processing and give this input bus a single slot (? - or more ?) in which you can define what item in the ae inventory to access. Surely open for more suggestions.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Florexiz** [comment]
Ore dict card support would be great also
And maybe 16 slots like regular hv bus?

**Comment by repo-alt** [comment]
Not sure I understand, do you mean, like, input bus plus export bus combined? Oredictionary support has unavoidable performance penalty.
That can be done for some machines, but it requires changing `checkRecipe` for each of them. Alternatively that hatch may keep cached item stacks inside, resupplied each tick.

**Comment by repo-alt** [comment]
In general that looks a lot like a faster export bus, and of course will cause the same performance problems, there is no magic.

**Comment by GTNH-Afx237v7** [comment]
> Alternatively that hatch may keep cached item stacks inside, resupplied each tick.

That sounds like the solution. I don’t see the need for oredict though.

**Comment by Florexiz** [comment]
I think you can override getStackInSlot in this input bus, so it only make request to AE when multi tries to get it contents?

**Comment by GTNH-Afx237v7** [comment]
> In general that looks a lot like a faster export bus, and of course will cause the same performance problems, there is no magic.

Any alternative suggestions for both tps friendly and rapid item insertion into multiblocks? It does not have to be an ME Input Bus if there is a different way; this comes from the idea that the fewer participants in item handling, the better it is tps-wise.

**Comment by GTNHAfx237v7** [comment]
Then we are looking at two different concepts.

1. An input bus that allows a GT multiblock to see the content of AE and provide it (simple)
2. An input bus that allows a GT multiblock to use the content of AE via patterns (complex)

For 1. I suggest to keep this bus simple - single slot GUI that sets what item stored in the AE network to use
For 2. I am honestly not sure...

**Comment by minecraft7771** [comment]
> Then we are looking at two different concepts.
> 
> 1. An input bus that allows a GT multiblock to see the content of AE and provide it (simple)
> 2. An input bus that allows a GT multiblock to use the content of AE via patterns (complex)
> 
> For 1. I suggest to keep this bus simple - single slot GUI that sets what item stored in the AE network to use For 2. I am honestly not sure...

For 2. I would just suggest that this input bus behaves like a mini me storage (Infinite or expandable idk) and the crafting CPU just pushes everything it has into it (maybe with a blocking mode that allows the same recipe multiple times but not two recipes)
