### ISSUE TITLE
Server crash with railcraft anchors after long runtime

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9275]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Server

Personal server

### Type of Server

Vanilla Forge

### Your Actions

In recent days, the server has started to crash at about the same time, while there is no one on the server.

![image](https://user-images.githubusercontent.com/46845681/147384531-fc0c54e6-f7bb-43ba-a445-09df51b2118f.png)

I tried to figure out what the problem was on my own, but I couldn't. On the recommendation of bombcar, I changed the server startup arguments, but the next day the server crashed again

### Crash Report

[crash-2021-12-25_10.23.37-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7775812/crash-2021-12-25_10.23.37-server.txt)
[2021-12-25-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7775813/2021-12-25-3.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
It's running out of memory somehow - after about 24 hours running straight.

Many servers automatically restart at 4-12 hours or so - but we may be able to track it down. I assume you're chunk loading?

**Comment by Eldrinn-Elantey** [comment]
> It's running out of memory somehow - after about 24 hours running straight.
> 
> Many servers automatically restart at 4-12 hours or so - but we may be able to track it down. I assume you're chunk loading?

There is a chunk loader on the base and when the drill is working. Recently, the oil platform has been operating

**Comment by bombcar** [comment]
Can you check how many chunks are loaded periodically? Another player is reporting the number of chunks continually climbing in single player. If that’s the case eventually it will crash out. 

I think ingame info will show this

**Comment by Eldrinn-Elantey** [comment]
> Can you check how many chunks are loaded periodically? Another player is reporting the number of chunks continually climbing in single player. If that’s the case eventually it will crash out.
> 
> I think ingame info will show this

Is that what you mean?

![image](https://user-images.githubusercontent.com/46845681/147394791-bced2073-87b3-4119-94e9-8cc047b26328.png)

**Comment by ElNounch** [comment]
An heap dump at crash or after long running times might help.
[https://www.baeldung.com/java-heap-dump-capture](https://www.baeldung.com/java-heap-dump-capture)

**Comment by Eldrinn-Elantey** [comment]
> An heap dump at crash or after long running times might help. https://www.baeldung.com/java-heap-dump-capture

I don't understand anything about this

**Comment by bombcar** [comment]
I meant the ingame info like this:

https://discord.com/channels/181078474394566657/234936569360809996/924357035691233321


![](https://media.discordapp.net/attachments/234936569360809996/924357035120803930/unknown.png)

**Comment by Eldrinn-Elantey** [comment]
On some previous versions, we used FTB Utilities as chunk loaders. At the same time, such a situation did not arise

**Comment by Eldrinn-Elantey** [comment]
> Can you check how many chunks are loaded periodically? Another player is reporting the number of chunks continually climbing in single player. If that’s the case eventually it will crash out.
> 
> I think ingame info will show this

![image](https://user-images.githubusercontent.com/46845681/147402626-84e0d0a1-5601-495f-a25c-48f62e4cead6.png)

**Comment by Eldrinn-Elantey** [comment]
As far as I remember, it started after placing a passive anchor with a guardian on the base. We temporarily removed the anchors and use the chunks upload from FTB Utilities

**Comment by Eldrinn-Elantey** [comment]
It took more than a day of continuous server operation after removing all railcraft anchors and installing chunks from FTB Utilities. The server is running the roof did not happen

**Comment by Eldrinn-Elantey** [comment]
The crashes began after the anchor and sentinel were installed on the base

**Comment by bombcar** [comment]
This is apparently caused by railcraft anchors - perhaps some timer is overflowing?

Are you using admin anchors and can you take a picture of the setup?

**Comment by Eldrinn-Elantey** [comment]
> This is apparently caused by railcraft anchors - perhaps some timer is overflowing?
> 
> Are you using admin anchors and can you take a picture of the setup?

Only passive and personal anchors were used. As far as we understand, the world anchor is off. The admin anchor was not used. What exactly are the settings? If the mod's configuration files have not been changed.

**Comment by bombcar** [comment]
Just wondering how to replicate it. Are you loading the anchors with more than 16 ender pearls?

**Comment by Eldrinn-Elantey** [comment]
> Just wondering how to replicate it. Are you loading the anchors with more than 16 ender pearls?

In the last update, the size of the pearl stack was increased to 64, so yes, we put more than 16, namely 64

**Comment by bombcar** [comment]
I’m wondering if that is breaking it - can you try running with only 16 and see if it happens

**Comment by Eldrinn-Elantey** [comment]
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7793249/fml-server-latest.log)
[console content.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7793256/console.content.log)

**Comment by Eldrinn-Elantey** [comment]
After the last shutdown , I didn 't have time to go in and remove the anchor and crash again
[crash-2021-12-31_13.46.04-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7795926/crash-2021-12-31_13.46.04-server.txt)
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7795930/GregTech.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7795932/latest.log)
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7795933/fml-server-latest.log)
