### ISSUE TITLE
Electrotine dust composition doesn't make sense

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#9282]
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.1.2.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

I expected the centrifuge/mixer recipes for electrotine dust to be balanced.

### The Reality

![image](https://user-images.githubusercontent.com/88752681/147397650-3035dde6-2e12-4619-b5db-09f6f26cd5b1.png)

![image](https://user-images.githubusercontent.com/88752681/147397651-848cca45-2c45-4407-b9a2-6741bdb48a68.png)

### Your Proposal

Balance the electrotine dust recipe. Probably easiest to do by setting the centrifuge recipe from 8 -> 2.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
You can easily mine electrotine and it has a high yield when processed. On the opposite hand, few recipes use electrotine dust as ingredient. For the former reason, the recipe is OK, as a better output would yield too much electrum and redstone. For the latter reason, I believe the mixer recipe should be deleted.

**Comment by Elisis** [comment]
Neither electrum nor redstone are hard to come by already. Imo it's more important to have the decomposition be logically consistent

**Comment by Pxx500** [comment]
imo the best solution would be to remove both recipes or remove the one that makes electrotine so the player can assume there is someting more in it that can't be retrieved by centrifuging, from my experience neither gold nor silver was plentiful early game (until it was)

**Comment by GTNH-Afx237v7** [comment]
Removing the first will make electrotine useless, at least in higher tiers.

**Comment by OrderedSet86** [comment]
Removing the second will kill any runs that don't go to the nether, as electrotine is unobtainable other than in-world and the mixer recipe. Electrotine is used in the making of blue alloy for first EV circuits. If it is removed, an electrotine bee should be added, similar to cryolite.

**Comment by Elisis** [comment]
In my opinion the best thing to do, to preserve current balance, is to make the centrifuge recipe HV+. Hopefully that's enough of a compromise.

**Comment by kenken244** [comment]
Glowstone is already gold and redstone. Maybe it should have a different composition all together?
