### ISSUE TITLE
Minesweeper Causes Crash

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/GT-New-Horizons-Modpack#9283]
### Your GTNH Discord Username

N4M3_T1TL3_P3R20N#3173

### Your Pack Version

2.1.2.1

### Your Server

Zeta

### Your Actions

I found a loot game dungeon and the game happened to be minesweeper; I started the game fine and then tried to place the marker/flag by shift right clicking this caused me to be instantly kicked from the sever, I'm assuming this is a crash.

### Crash Report

[crash loot game.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7776670/crash.loot.game.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by vovaksenov** [comment]
Same issue as #9040
