### ISSUE TITLE
Log GT exceptions to console

### ISSUE THREAD

**Issue by SinTh0r4s** [GTNewHorizons/GT-New-Horizons-Modpack#9287]
### Your GTNH Discord Username

SinTh0r4s

### Your Pack Version

Wayne

### Your Proposal

When GT catches an exception: log it to console as well. Not every debug print if possible, but often people don't know that Greg hides exceptions and have a hard time finding the issue.

### Your Goal

Much easier debugging.

### Your Vision

Same.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
also make the file append the date/hour of the creation of the file to its name so it doesn't get erased at each reboot

**Comment by mitchej123** [comment]
Swap uses that we want logged of `GT_Log` out with `GT_FML_LOGGER`.  There's a lot of stuff that doesn't need to go in the main log file!
