### ISSUE TITLE
Ultramine issues with Tinker's Defense(?)

### ISSUE THREAD

**Issue by Kaspario** [GTNewHorizons/GT-New-Horizons-Modpack#9288]
### Your GTNH Discord Username

Kaspario#2928

### Your Pack Version

2.1.2.0

### Your Server

Private Server

### Type of Server

Other MCPC+ fork

### Your Actions

So I run Ultramine core server. I've decided to update to the newest version, however, I got lots of issues with hydroenergy and people from discord helped me fix it with downloading http://jenkins.usrv.eu:8080/job/HydroEnergy/lastSuccessfulBuild/artifact/build/libs/hydroenergy-1.7.10-1.0.8-8-gb133e17.jar . Server stopped crashing at the beginning, but now it crashes later because of tinker's defense for somereason. Those crashreports I left are the latest.

### Crash Report

[crash-2021-12-28_01.34.12-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7781376/crash-2021-12-28_01.34.12-server.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7781379/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Try removing amdiforge ?

**Comment by Kaspario** [comment]
Same [Uploading crash-2021-12-28_02.06.39-server.txt…]()

**Comment by Glease** [comment]
Also grab an updated Natura from jenkins: http://jenkins.usrv.eu:8080/job/Natura/lastSuccessfulBuild/artifact/build/libs/Natura-1.7.10-2.4.6.jar

**Comment by Kaspario** [comment]
No idea how, but it worked. Thanks.![image](https://user-images.githubusercontent.com/46453218/147504728-74ca8700-43ae-4203-85cd-bae7079df17c.png)
