### ISSUE TITLE
AE storge bus is no longer able to read barrels

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#9289]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Server

delta

### Type of Server

Don't know

### Your Expectation

connect AE storge bus to barrel
In the previous version, the item in the barrel can be read normally

### The Reality

it will show 64 item only if connect AE storge bus to barrel

### Your Proposal

is that a bug? or a nerf ? if it is a bug piece fix it thanks :D

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
it's fixed in dev: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9110 and it will be soon hacked into the officials when i'll have time for it.
