### ISSUE TITLE
wireless Crafting terminal eat item

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#9293]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Server

delta

### Type of Server

Don't know

### Your Expectation

https://youtu.be/QQxxlkfJCiA
if you use JEI auto put item in the crafting terminal then you manually put in more items like this and you close the ui and open it again it eat your item 

### The Reality

wireless Crafting terminal eat item

### Your Proposal

Please fix it. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
looks like there is a scenario not covered by the nbt syncing

**Comment by repo-alt** [comment]
> if you use JEI auto put item in the crafting terminal

You mean - using `Shift+?` ?

**Comment by Eason134HK** [comment]
> > if you use JEI auto put item in the crafting terminal
> 
> You mean - using `Shift+?` ?

yes
