### ISSUE TITLE
Illumar recipes in gt++mixer

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#9297]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.1

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Craft illumars in large mixer from gt++

### The Reality

Multiblock mixer don't have recipes for them
![image](https://user-images.githubusercontent.com/29033773/147684093-4178d22e-f491-43e5-8000-2672b5863044.png)
![image](https://user-images.githubusercontent.com/29033773/147684110-0156d438-f451-4355-816a-48a125cf48d9.png)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
If the recipe is in code (and not in a script) it might be available in gt++ devices as well.
