### ISSUE TITLE
Lapotronic Supercapacitor energy loss above normal

### ISSUE THREAD

**Issue by s9hysky** [GTNewHorizons/GT-New-Horizons-Modpack#9298]
### Your GTNH Discord Username

s9hy_sky

### Your Pack Version

2.1.1.4qf-2

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Lapotronic Supercapacitor loss 1% power in 24 hours.
A LSC with 9 IV capacitors has 900Meu capacity and loss 900M*1%/24/60/60/20≈5eu/t,voiding 20% more power per maintenance issues

### The Reality

It lost 22eu/t
If it have maintenance issues,energy loss sometimes decreases and sometimes increases
fix maintenance issues will increase energy loss again.It will lead to higher and higher energy loss
![1](https://user-images.githubusercontent.com/73462892/147684039-b19ee5aa-7564-4fab-b500-e92e38d310ef.png)
![2](https://user-images.githubusercontent.com/73462892/147683977-3ae64dab-3d4b-4a6c-ae00-d756a31d9fdb.png)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Presumably a rounding issue.

**Comment by GTNH-Afx237v7** [comment]
Update: after some time the passive loss went back to normal without actually doing anything...

**Comment by s9hysky** [comment]
> Update: after some time the passive loss went back to normal without actually doing anything...

Sometimes it returns to normal after a few hours, and sometimes it won't return for a long time

**Comment by GTNH-Afx237v7** [comment]
So I just had another maintenance issue on an LSC.
Passive loss with issue: 52 Eu/t
Passive loss immediately after fixing issue: 114eu/t.
After about 5 minutes the passive loss reduced itself to now 57eu/t.

There were no changes to the structure of the LSC in any way.
