### ISSUE TITLE
Farming Barnard-C Trees

### ISSUE THREAD

**Issue by MMunier** [GTNewHorizons/GT-New-Horizons-Modpack#9300]
### Your GTNH Discord Username

MMunier#1337

### Your Pack Version

2.1.2.1

### Your Proposal

Some Treefarm should be modified to accommodate Barnard-C Trees.
And the sapling droprate is currently below 1 -- making them impossible to farm it in any form, so it would need to be increased

### Your Goal

These trees are needed in lategame for the largest Busses and Hatches (Radox Polymer).
Aditionally they are needed continually when going for the final Naquadah Fuel.

### Your Vision

Probably not at all, 
since this is way into endgame territory and is so for the most part irrelevant.
It's just wierd that there's basically nothing to farm these trees apart from autoclicking with TCs "Axe of the Stream".

### Final Checklist

- [ ] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
Similar to #9819
