### ISSUE TITLE
GT_ADVANCEDENTROPICPROCESSING creates 13k unused crucible recipes

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#9301]
### Your GTNH Discord Username

Pao

### Your Pack Version

2.1.2.1

### Your Proposal

https://github.com/GTNewHorizons/GT5-Unofficial/blob/92c78f346995f7140902f9719daa89d427f61a04/src/main/java/gregtech/api/util/GT_RecipeRegistrator.java#L275-L276

Apparently this line adds a crucible recipe for every pulverization recipe, allowing it to be broken back down into their base component for some perditio.  However, the research referenced in the function is never registered with Thaumcraft so it's unobtainable.  This causes the Thaumcraft recipe hashmap to contain 13k recipes that can never be obtained and (most likely) slow down the recipe searching in NEI and whatnot, if it has to iterate over 3x as many recipes as it normally would (if you remove the 13,616 unused crucible recipes, there's only 5,772 recipes in the Gregtech API).  Should we remove the GT_ADVANCEDENTROPICPROCESSING lines or add the research to the thaumnomnomicon?  

[new 16.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7791385/new.16.txt)

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I say remove them - nobody has noticed until now and the crucible recipes sound kinda crappy anyway.

**Comment by Ethryan** [comment]
I vote for removal, 

13 thousand ways to turn material into Perditio sounds a bit excessive, especially since you can get it from cobblestone.

**Comment by bombcar** [comment]
If I read that right you could also get a bit of something else sometimes. Still not worth it for 13k recipes.

**Comment by PolkageistHS** [comment]
It doesn't create Perditio; it uses Perditio to pulverize them, basically.  Like if you throw in an HSS-S turbine, it'll return 6 HSS-S dusts at the cost of 4 Perditio.

**Comment by Ethryan** [comment]
Great even more useless, and they can’t even be used since they are locked.

**Comment by bombcar** [comment]
If we wanted to include this better a thaumatic machine that just used the macerator recipes without needing a conversion of each one

**Comment by Alastors** [comment]
I think this poses a really interesting idea, considering how it could mean having to use less resources on making macerators, which sure aren't a huge deal, but just never having to make higher tiered ones is pretty cool, and it gives an interesting new way to use thaumcraft, and I personally feel like anything TC can do to integrate better into the pack, by better integrating into new production lines, I do however agree with bombcar's idea though, that we should add a thaumic machine that uses the same recipes as a macerator, though I would like to add, maybe it should either take perditio essentia to run, or maybe it should take perditio centivis, since that would be more inline with thaumic machinery in general?

**Comment by bombcar** [comment]
Let’s remove them for now, and if desired create a feature request for a new thaumcraft machine that does this

**Comment by miozune** [comment]
I agree with removal. With my latest change to Thaumcraft NEI Additions, player will be informed that there are secret recipes for GT dusts, which is very confusing.
![2022-04-03_15 40 42](https://user-images.githubusercontent.com/40035906/161415421-fcc95d98-0b2c-40a2-9c11-dad3adecce5d.png)
