### ISSUE TITLE
Sticky ME Level Emitters

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9302]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

Set a level emitter to turn off when reaching 1.000.000 items in an infinity chest connected to the AE system

### The Reality

Level emitter turns on when items go under the set limit, sometimes doesn't turn back off.
![javaw_oSnjLUBr9a](https://user-images.githubusercontent.com/17811922/147736072-4e59fa17-6b9f-4684-af86-961f5d17876e.png)
![javaw_oZ1f1QI5Lr](https://user-images.githubusercontent.com/17811922/147736087-e6fc3bc7-4c91-419a-8407-523939b6e427.png)

### Your Proposal

No idea what's causing this, fix if possible.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
idk, couldn't reproduce that.

**Comment by Sphyix** [comment]
Is it possible that this is happening because the chest is connected to 2 different AE systems?
I have 2 storage buses connected to the same chest, 1 is for the AE system taking care of switching on/off the level emitter and do a bit of autocrafting, the other is the main AE system that can extract from the chest.

^ Doing this since connecting the main AE system to the level emitters was causing massive lag in 2.1.1.0 (Main AE is 2 infi chests, 60+ 16384k disks). I haven't tried in 2.1.2.0, idk if anything changed but it seemed like it was not fixable, I can't remember.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/147749713-eebed68d-b4ac-41d8-bb1c-befc14c38d17.png)
idk, tested with 2 networkd too
![image](https://user-images.githubusercontent.com/23512002/147749776-1baecba4-df37-4812-890b-617014b09c36.png)

**Comment by Sphyix** [comment]
Idk...
It's happening on 1 or 2 level emitters at random.
If I find any additional info, or how to reproduce this, I'll add to this ticket.
For now I have no idea what's triggering this, but it's happening on multiple items, in different chunks, and on different item number limits.
My AE just for reference
![javaw_uIdBKCsyf0](https://user-images.githubusercontent.com/17811922/147750700-e39c7061-c8f9-4a78-8ad1-0ff81c00e68e.png)

**Comment by Sphyix** [comment]
I probably know what's happening here.
I'm inserting into an infinity chest from 1 AE system, then extracting the items from another AE connected to the same chest.
When extracting items from the other AE, the one with level emitters doesn't get updated since it believes items are still there?
![mspaint_n6ZKnvKmVW](https://user-images.githubusercontent.com/17811922/152645084-7a1f5eba-060a-40e1-9eb5-9b87b778c014.png)

This is done since some machines require different items in the same input bus that are in different AE systems.
AE with level emitters and its own storage is to avoid lag from emitters, and that was fixed in new version.

Not sure if something can be done about this anyway, it would mean both AE need to get refreshed everytime an item is pulled, but that could cause lag?

**Comment by Sphyix** [comment]
I still can't reproduce it outside of delta >:(

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.

**Comment by Sphyix** [comment]
This is still an issue on 2.2.0.0 but can't be reproduced outside delta, or even outside my base.
I still have no idea what's causing this
