### ISSUE TITLE
Threshold on level emitters

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9303]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Proposal

Add a minimum and maximum amount for the level emitters instead of just a single value to switch it on/off

Original user interface:
![javaw_oZ1f1QI5Lr](https://user-images.githubusercontent.com/17811922/147837708-f1b74949-3cac-45e6-a8d1-e3efd74cd236.png)

Idea for the interface could be removing the + and - numbers and adding a minimum value
![javaw_0ljW4DNpXg](https://user-images.githubusercontent.com/17811922/147739513-60c87e23-c8ad-4ce9-a363-35e3ff8593d1.png)

Or maybe a card can be added to have this functionality.

### Your Goal

Idea is to have it reach minimum, turn on, and stay on for a while instead of switching on/off fast everytime it reaches the limit if items that are being produced keep getting used.

### Your Vision

+

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Savallator** [comment]
While we are at it: can we have level emitters be slow, like updating once every few seconds, and then add a second card slot and have them revert back to current speed with an accelleration card? It might help a lot with lag, and in most applications it would be no problem even if they took 10 seconds to update...

**Comment by repo-alt** [comment]
> While we are at it: can we have level emitters be slow, like updating once every few seconds, and then add a second card slot and have them revert back to current speed with an accelleration card? It might help a lot with lag, and in most applications it would be no problem even if they took 10 seconds to update...

Level emitter is not ticking, it is a passive transparent monitor, receiving updates. Theoretically it can remember, idk, system time, or get server tick somehow, to ignore frequest updates

**Comment by Savallator** [comment]
Okay, then it is actually implemented better than i thought. Then the only lag from rapid flicker would be lighting (i think the emitter itself does not emit light, but connected redstone might, although that can be easily removed) or flicker of the state of the connected machine. But these stuff would also be fixed with a threshold anyways, so probably not that important to change timings at all.

**Comment by repo-alt** [comment]
Well, handling updates is not exactly free and doing that too often is indeed unnecessary, so I added a configurable delay https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/92

**Comment by Savallator** [comment]
In fact, Level emitters are actually a really big lag source, but that is because they apparently get notified by every change. Not sure how easy that could be changed though...

**Comment by repo-alt** [comment]
Looking at the original suggestion, I think I don't understand how it should work or what is the intended purpose. (Unless RS-latch like behaviour is implied)

**Comment by Sphyix** [comment]
Rs-latch like behaviour was the initial idea
