### ISSUE TITLE
Creosote oil to lubricant distillation recipe busted

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#9306]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Server

delta

### Type of Server

Don't know

### Your Expectation

Creosote oil to lubricant distillation recipe busted
![image](https://user-images.githubusercontent.com/59776356/147767788-18968c8f-7bfb-4e45-864a-77e2a8779a48.png)

### The Reality

the recipe is not working after 2.1.2.0 update

### Your Proposal

fix it. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Said recipe does not exist in 2.1.2.1. Presumably fixed already.
