### ISSUE TITLE
Visual Prospecting not cataloging ore veins in chunks generated during world load.

### ISSUE THREAD

**Issue by sinergistic** [GTNewHorizons/GT-New-Horizons-Modpack#9307]
### Your GTNH Discord Username

Yukiko / Sinergistic#6159

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

Visual Prospecting should catalog ore veins that haven't been significantly messed with by things like caves, dungeons, etc.

### The Reality

Visual prospecting appears to struggle with cataloging ore veins located near spawn in a fresh world. 

![javaw_2021-12-30_12-10-36](https://user-images.githubusercontent.com/96602041/147789933-a44e53df-b0d0-47d9-8c97-cace37e57ae2.png)
Freshly generated world in a 2.1.2.1 (updated from 2.1.2.0 MMC install) client with some config options changed (AE2 meteors = false, pollution = false, biome size = 5), and running visualprospecting-1.7.10-1.0.25b-3-g232b08a.jar from jenkins. 

![javaw_2021-12-30_13-24-04](https://user-images.githubusercontent.com/96602041/147789960-dce4f572-ecb8-49cb-80e7-3f9882f35623.png)
Freshly generated world in 2.1.2.1 client (updated from 2.1.2.0 MMC install) in a fresh instance, zero config changes. Running visualprospecting-1.7.10-1.0.25b.jar. 

I also tried with visualprospecting-1.7.10-1.0.26b.jar downloaded from the VP github and experienced the same issues, but don't have pictures.

### Your Proposal

A '/vp add blah' to manually add something to the overlay would be very welcome to fix issues like this on the fly. Wouldn't even need to have the fancy ore types for the vein, just a name and a generic ore picture that shows up in the overlay. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

https://discord.com/channels/181078474394566657/181078474394566657/926228008111591476 Just confirming I'm not the only person with this issue.

**Comment by Ambaire** [comment]
I have also noticed this problem.

**Comment by Ambaire** [comment]
Seems to be similar to / might be the cause of this report: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9285

**Comment by bombcar** [comment]
It may be that the spawn chunks are somehow generated before VP gets a chance to run hmmm - I wonder if they fail if the world is made in 2.1.1.0 and then immediately upgraded.

**Comment by pavel-belous** [comment]
Setting up B:recacheVeins=true (visualprospecting.cfg) was solved this problem for me. Local cache have missing info about some ore veins after first cache generation.  So after finding this workaround I was stopped to debug, too much lazy :)

**Comment by sinergistic** [comment]
recacheVeins and re-opening the world seems to resolve the problem for me as well.
