### ISSUE TITLE
Y'all way over nerfed the LDP

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9308]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

Bruh, I was using the LDP, I've been using it to move pressurized water for a hot minute, and it helps keep my power grid alive

### The Reality

Because the route it transported was 41 blocks away, instead of flipping 64, my entire power grid broke and now I have to use laggy as piping. 

### Your Proposal

Change it to like 32 or some shit, idfk, 64 horizontally and 96 vertically is way overkill

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
This is a config option https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/19110df7c5958532c63932b1c903c579fe969e3a/config/GregTech/GregTech.cfg#L89 but perhaps something serving a similar purpose for shorter distances (and perhaps with other limitations to not completely blow gt pipes away) could be useful

sdfp
