### ISSUE TITLE
Client crash when clicking the search button on a server with custom quest

### ISSUE THREAD

**Issue by ducanh2002123** [GTNewHorizons/GT-New-Horizons-Modpack#9310]
### Your GTNH Discord Username

Xx__THK__xX#2744

### Your Pack Version

2.1.2.1

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

My server have custom quests, and I've verified that my custom quests are all working fine, with no issue whatsoever, however, when we tries to press the Search button on the quests menu, then it crashes the game

### Crash Report

[QuestDB.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7796522/QuestDB.zip)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ducanh2002123** [comment]
Wait , sorry, i didn't post all the files
let me attach the real crash report
[crash-2021-12-31_21.59.16-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7796526/crash-2021-12-31_21.59.16-client.txt)

**Comment by Glease** [comment]
Sounds like a corrupted quest database than anything else

**Comment by bombcar** [comment]
The QuestDB posted is valid JSON but causes the same crash here.

@ducanh2002123 can you provide DefaultQuests.json from the config directory?

**Comment by Glease** [comment]
By corrupt I mean its foreign key constraint is broken. A QuestLineEntry is a relationship between Quest and QuestLine. Obviously their is a QuestLineEntry whose Quest field is null or no longer valid. This is usually caused by hand editing of the quest database...

**Comment by ducanh2002123** [comment]
> The QuestDB posted is valid JSON but causes the same crash here.
> 
> @ducanh2002123 can you provide DefaultQuests.json from the config directory?

here's the file that you requested
[Uploading DefaultQuests.zip…]()

**Comment by ducanh2002123** [comment]
okay.. that.. didn't work.. trying again
[DefaultQuests.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7796900/DefaultQuests.zip)

**Comment by ducanh2002123** [comment]
> By corrupt I mean its foreign key constraint is broken. A QuestLineEntry is a relationship between Quest and QuestLine. Obviously their is a QuestLineEntry whose Quest field is null or no longer valid. This is usually caused by hand editing of the quest database...

can you instruct me on how to find out what is causing it? I did do hand editing of the quest db so that might be the case, although I did not edit existing quests, just adding new ones in, it might still be the case

**Comment by bombcar** [comment]
Easiest would probably be a binary search but depends on how many new quests you added

**Comment by bombcar** [comment]
Still we shouldn’t crash - I may take a
Look and see if we can error reasonably

**Comment by Glease** [comment]
In "questLines" section you should see a datastructure like this

```json
	"questLines:9": {
		"0:10": {
			"quests:9": {
				"0:10": {
					"sizeX:3": 24,
					"x:3": -108,
					"y:3": -60,
					"id:3": 5, // (*)
					"sizeY:3": 24
				},
				"1:10": {
					"sizeX:3": 24,
					"x:3": 60,
					"y:3": -48,
					"id:3": 6, // (*)
					"sizeY:3": 24
				},
				"2:10": {
					"sizeX:3": 24,
					"x:3": -48,
					"y:3": 48,
					"id:3": 7, // (*)
					"sizeY:3": 24
				}
			},
			"lineID:3": 0,
            // other unimportant stuff
		}
	},
```

see the lines marked with  `// (*)`? The value of id field is the quest ID (in this case, 5, 6 and 7 respectively). The body depicts where and how this quest should be displayed in a given questline. Somewhere in this multi megabyte file there is such an entry that point to a nonexistent quest (presumably a custom quest you hand removed) Remove this entry and search should recover.

---

QuestLineEntry QuestLineEntry{sizeX=24, sizeY=24, posX=648, posY=0} in QuestLine 16 pointing into nonexistent quest 2991
QuestLineEntry QuestLineEntry{sizeX=24, sizeY=24, posX=0, posY=180} in QuestLine 42 pointing into nonexistent quest 2992
QuestLineEntry QuestLineEntry{sizeX=24, sizeY=24, posX=48, posY=180} in QuestLine 42 pointing into nonexistent quest 2993

In the meanwhile I'll prepared a PR to solve any such problems in the future

**Comment by ducanh2002123** [comment]
> 

that's.. odd, i never removed a quest, in fact I only adds them on the server's config file... So I really don't get why it's going on like this, but it's nice that you guys made a fix for it though, thank you guys a lot, and happy new year, hope y'all will have an amazing 2022

**Comment by bombcar** [comment]
> that's.. odd, i never removed a quest

Likely you didn't - but we may have :)

If you had put the new quests "behind" something, that quest may have been renumbered or moved.

**Comment by ducanh2002123** [comment]
> > that's.. odd, I never removed a quest
> 
> Likely you didn't - but we may have :)
> 
> If you had put the new quests "behind" something, that quest may have been renumbered or moved.
Behind as in... having it as a requirement to unlock the custom quest?
Like for example, I have the requirement set as "Make the circuit yourself once (as in completing the quest for that circuit once) then you can buy it"
Maybe those quests id changed

**Comment by bombcar** [comment]
Yes - that’s the kind of requirement that may have reshuffled
