### ISSUE TITLE
Multistack input is by default on instead of off

### ISSUE THREAD

**Issue by Bubunator** [GTNewHorizons/GT-New-Horizons-Modpack#9311]
### Your GTNH Discord Username

Bubu#0872

### Your Pack Version

latest

### Your Server

Epsilon

### Your Expectation

Since the last update which was fixing;
_- the covers,
- assline stick not working if they weren't from tectech,
- the random getBlock crashes
-  the chunk ban if you used a wrench on hoppers
-  the barrels not being properly detected by AE
- the bug where one couldn't use a resource if > 2^32 in AE
- small optimizations as well_

Multistack input is by default on

### The Reality

Multistack input is by default on

### Your Proposal

Multistack input by default OFF

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
This is a new “feature” of the machine and can be disabled with screwdriver on the machine

**Comment by Bubunator** [comment]
i suggest then to have this "feature" disabled by default

**Comment by bombcar** [comment]
I believe it is … in dev not in any release yet

**Comment by Bubunator** [comment]
with the update on epsilon that was just released a few hours ago Multistack input is ON by default

**Comment by mitchej123** [comment]
Fixed in dev, will be in the next release
