### ISSUE TITLE
Heat sink recipe

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9312]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Server

Personal server

### Type of Server

Vanilla Forge

### Your Expectation

I came to the creation of a nuclear reactor and discovered a strange thing

### The Reality

![image](https://user-images.githubusercontent.com/46845681/147832800-d6e2f433-596d-40da-acea-1a1424414c5b.png)
![image](https://user-images.githubusercontent.com/46845681/147832808-c0c566ca-6983-4560-a458-9f5728d12a7d.png)

### Your Proposal

Manually creating a heat sink is cheaper than using an assembler. You need 4 iron bars through the workbench and 4 steel bars through the assembler

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Seems like an oversight. Component vent should use steel bar but is currently using iron bar. Probably someone mistaken one for another.

**Comment by bombcar** [comment]
wait which is broken the ass or the crafting table?

**Comment by Eldrinn-Elantey** [comment]
> wait which is broken the ass or the crafting table?

crafting table?
