### ISSUE TITLE
Changes to the rules of wearing Dolly from Jabba

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9313]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Proposal

Allow you to carry an empty Dolly in backpacks and other similar personal storage. Prohibition on putting Dolly in a backpack only if it has a chest and other compatible objects

### Your Goal

The ability to have at hand (carry with you in a Dolly backpack for use if necessary

### Your Vision

Sometimes there are cases when there is a need to move a chest or a bar from place to place, but there is no Dolly with you, and it is constantly inconvenient to carry it with you in the inventory because it occupies a slot. Therefore, I propose to allow the transfer of Dolly in a backpack while there is nothing in it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
If this cannot be done for code reasons we could add a “collapsed dolly” that can be shapeless changed to a dolly and back, and allow that in the backpack (and stack even!) 


![](https://wel-fab.com/pub/media/catalog/product/cache/0f01b57647dd84fd0a5b186c3585454b/w/f/wf089-collapsable_dolly_1.jpg)

**Comment by Eldrinn-Elantey** [comment]
Is this idea still needed?

**Comment by Ethryan** [comment]
I think it’s still needed. 
Haven’t seen anything that makes it possible to carry an empty dolly in a backpack yet.

**Comment by Dream-Master** [comment]
> I think it’s still needed.
> Haven’t seen anything that makes it possible to carry an empty dolly in a backpack yet.

The dolly is fine. I never seen someone put 20 dollys in a bag even if you can pack it like in the picture. I wouldn’t change anything.
