### ISSUE TITLE
Visual Prospecting cataloging wrong vein

### ISSUE THREAD

**Issue by Ambaire** [GTNewHorizons/GT-New-Horizons-Modpack#9315]
### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

If I touch an ore in a vein, I expect that vein to be cataloged. I first found the chalcopyrite vein touching the wall of my staircase, and it catalogued it adjacent as expected. I then found a magnetite vein a bit further down, but after touching it, the diagonal one was cataloged instead.
![vein bug](https://user-images.githubusercontent.com/8532233/147837354-c39676f8-deee-4a32-803d-d72d0d628da8.PNG)
.

### The Reality

I touched an ore in a vein and a vein 3 chunks away diagonally was cataloged.

### Your Proposal

Catalog the correct vein.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can you save world, make a copy, spawn in the electric prospector and scan your area and show the results?

**Comment by Ambaire** [comment]
> Can you save world, make a copy, spawn in the electric prospector and scan your area and show the results?

I'd rather not spoil myself on what veins are available where. [I uploaded the world as a zip to my dropbox.](https://www.dropbox.com/s/e62pr0aeehoimb7/Ever%20Onwards.zip?dl=0)

**Comment by bombcar** [comment]
Your prospector worked correctly, you're at the apex of a overlapping vein that is spawned from that corner:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/533931/147839124-3cf4a4b5-d541-477f-827a-a0cfb8478945.png">
