### ISSUE TITLE
Jumping a horse into a beehive causes a crash

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/GT-New-Horizons-Modpack#9316]
### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Actions

I'm exploring the world, and tried to do a 2 block jump here to get over the tree. I caught a glimpse of the inside of the beehive and then the game crashed. I replicated this twice, and the third crash report is just after trying to jump after the screenshot. The crashes occurred while in first person.
![javaw_yc7debgTod](https://user-images.githubusercontent.com/8532233/147840414-3567a17b-ca05-414d-8c18-8ab74d802940.png)

### Crash Report

[crash-2021-12-31_16.25.05-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7797171/crash-2021-12-31_16.25.05-client.txt)
[crash-2021-12-31_16.30.24-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7797172/crash-2021-12-31_16.30.24-client.txt)
[crash-2021-12-31_16.36.18-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7797173/crash-2021-12-31_16.36.18-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ambaire** [comment]
It seems that merely running a horse into a beehive at player eye level causes this crash. Fourth crash log attached.
[crash-2021-12-31_16.49.54-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7797186/crash-2021-12-31_16.49.54-client.txt)

**Comment by bombcar** [comment]
I recall seeing another ticket about head inside beehive crashing

**Comment by Ambaire** [comment]
> I recall seeing another ticket about head inside beehive crashing

Sorry, didn't see it. .. It seems that after the latest crash, I crash when trying to load the game. Last backup is from 20 minutes ago. Any alternatives to restoring that?

**Comment by bombcar** [comment]
> > I recall seeing another ticket about head inside beehive crashing
> 
> Sorry, didn't see it. .. It seems that after the latest crash, I crash when trying to load the game. Last backup is from 20 minutes ago. Any alternatives to restoring that? Edit: Reloaded the backup.

You could throw your playerdata into an nbt editor and move yourself away
