### ISSUE TITLE
Passive Anchor not loading on login at Makemake

### ISSUE THREAD

**Issue by Bubunator** [GTNewHorizons/GT-New-Horizons-Modpack#9319]
### Your GTNH Discord Username

Bubu#0872

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

Passive Anchor at Makemake (Dim 25) should load upon login at Epsilon which is not the case while others in other dimensions do.

### The Reality

Passive Anchor on Makemake Dimension is not loading upon login

### Your Proposal

Let Passive Anchors on Makemake become active upon login.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
break them and replace them, there was a detection issue with hodgepodge from 2.1.2.0, now it should be fixed. let me know if it is still broken. But it worked for me on delta

**Comment by Bubunator** [comment]
I replaced it yesterday evening and after the scheduled server restart this morning it was not loaded

**Comment by Bubunator** [comment]
Now its loading again, thanks!
