### ISSUE TITLE
Journeymap don't show any mobs after open to Lan

### ISSUE THREAD

**Issue by lacleman** [GTNewHorizons/GT-New-Horizons-Modpack#9320]
### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

Clicking "open to Lan"

### The Reality

All the entities on journeymap ( both minimap and fullscreen map) disappeared. And some icons are missing too.
![屏幕截图(22)](https://user-images.githubusercontent.com/61073606/147848541-17ae3bfa-33dc-4a12-81b7-9d67e4d9491c.png)
. 

### Your Proposal

Show all the mobs

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
If you using fair play version of Jouneymap it not show the mobs. Its not a bug.

**Comment by lacleman** [comment]
Does the client pack come with the fair play version of Journeymap? If so, can I replace it with a normal version and keep the VisualProspecting function? @Dream-Master

**Comment by bombcar** [comment]
Yes. You can also replace journeymap it’s xaero if you wanted

Reminder that open to lan will have other bugs - many backups or consider running a server on the same computer if you have the RAM
