### ISSUE TITLE
Botania+Forbidden magic integration

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#9322]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.1.2.0 + Botanic Horizons

### Original Request

Dream asked to check FM wand caps

### Responding developer

@combusterf

### Context

Context: #9314

![image](https://user-images.githubusercontent.com/8459776/147850610-29c9cdc5-df85-436e-b213-118a08448178.png)
These recipes should look more like the other caps.

Inert manasteel caps should probably be bumped into an infusion recipe, since they have the same stats as Thaumium caps but are available earlier and much cheaper.

![image](https://user-images.githubusercontent.com/8459776/147850683-d4ddf8c9-294d-4f60-a9b6-06f6521d2997.png)
There is a pair of recipes for the wand cores that don't actually use livingwood/dreamwood, and they should be retired or merged with the inert recipes wand core recipes.

The actual wand tiering has not been harmed, the total mana cost/TF ingredients/screw material tier still apply.

### Developer's Promise

Reminder ticket if Botania gets approved.

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
If neede i add all materials to gt material list. So we can use all kind of screws, rings plates etc

**Comment by combusterf** [comment]
Having the GT materials is a good idea for all recipes involved.

**Comment by Dream-Master** [comment]
make a list for me i will add them.
We need to discuss about values like mining speed hardness. EBF etc.

**Comment by combusterf** [comment]
The obvious materials are:
- Manasteel (suggestion to copy stats from cobalt)
- Terrasteel (as per oriharukon)
- Elementium (as per draconium)
Botania generates these three directly in ingot form, so they can have regular recipes like any other metal. These tiers have tier+1 EBF recipes so the early developer can't directly recycle byproduct dusts back into ingots.

The odd one is:
- Gaia ingot
Which have a special recipe from gaia spirit items, so they behave a bit more like mysterious crystal. GT Ingots and plates etc can be added, but shouldn't be dictionaried to the gaia spirit item. Giving them stats like naquadah alloy would be roughly ok. 

Apart from that it might be an idea to add an autoclave recipe to have a lossy cycle back into spirit drops

**Comment by combusterf** [comment]
The following MR should address the blocking concerns: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9508

**Comment by combusterf** [comment]
I've forked out the materials discussion into https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9635
