### ISSUE TITLE
Many Bibliocraft items missing recipes

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#9323]
### Your GTNH Discord Username

querns#3785

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Many items in Bibliocraft are missing recipes.

* All Fancy Signs
* Fancy Workbenches (all except forestry ones)
* Bookcases (all except forestry ones)
* Potion Shelves using vanilla woods (all except forestry ones)
* All Shelves (`____ Shelf`) (all except forestry ones)
* All Tool Racks (all except forestry ones)
* All Cases (`____ Case`) (all except forestry ones)
* All Desks (all except forestry ones)
* All Tables (all except forestry ones)
* All Map Frames (all except forestry ones)
* Disc Rack
* All Seats (all except forestry ones)
* Stockroom Catalog (Has quest!)
* Big Writing Book
* All Seat Backs (Various styles) (all except forestry ones)

### The Reality

Some of these items have non-vanilla-wood variants, and are craftable. 

### Your Proposal

n/a

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
These existed in 2.1.1.0 for sure

**Comment by bombcar** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/86be0e463886e51576669a8131306384d2764572#diff-8c5967fd8486f34493710cc39b240aad46536cf4ee421ffd0479e6542db03e36 may be related, that's when it was merged into code.

If you are NOT running the latest coremod/gt5u it could be that they're in there ....

**Comment by bombcar** [comment]
We took a sledgehammer to all bibliocraft recipes and maybe the vanilla ones got lost in the shuffle.

**Comment by Dream-Master** [comment]
This is fixed in dev.

**Comment by Dream-Master** [comment]
yea @boubou19 need to put those recipes back. The recipes be vanilla so they missed.
