### ISSUE TITLE
Return Opencomputers possibility to interact with Drawers controller

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#9324]
### Your GTNH Discord Username

John S#7565

### Your Pack Version

2.1.2.1

### Your Proposal

Return Opencomputers possibility to interact with Drawers controller. To make possible move items in and out drawers storage with Opencomputers.

### Your Goal

Want to make people have chioce between making smart things one time(with OC) or go in more boring and laggy comon way of automation setup.

### Your Vision

In past stable wersion of the game 2.1.1.0 i try to make the OC program to make automation craft recipes before Apllied energistics tier. It`s early - midle HV age for OC automation instead of late EV for Apllied energistics. And in that wersion( 2.1.1.0) OC perdectly worked with Drawers, but now that is broken and OC cannot to see  Drawers controllers content.  Plese fix that. 
Thank you wery much.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Rikenbacker** [comment]
This is an necessary feature for automation with Open Computers!

**Comment by repo-alt** [comment]
This is weird. Storage drawers never had direct OC integration, drawer controller was exposing ISidedInventory, and that did not change...

**Comment by Retster** [comment]
> This is weird. Storage drawers never had direct OC integration, drawer controller was exposing ISidedInventory, and that did not change...

If i understand correctly that was not direct integration. But in 2.1.1.0 was possible to ittearct with drawers controller by hand(and OC correctly see all drawers massive from single controller point), but now it`s changed with drawers logic optimisation(or something around that).

**Comment by bombcar** [comment]
Break and rebuild the drawer controller see if that fixes it

**Comment by Rikenbacker** [comment]
No it is not fixing it.

**Comment by Retster** [comment]
> Break and rebuild the drawer controller see if that fixes it

I try to test that beheviator seweral times with single controller connected to single(or more) drawer, in 2.1.1.2, 2.1.2.1 wersion. And that not work not only for me.

**Comment by Retster** [comment]
I loaded 2.1.1.0 version from here: http://downloads.gtnewhorizons.com/ClientPacks/old/
And try again to interact with drawers with OC transposer again and looks like i cannot to do it. Now i dont sure that it was even posible before. (Tested recently only in new wersions)
But if that posible to make some integration to make Opencomputers to interact with Drawers controller that would be definitely great.
I apologize for misleading.

**Comment by repo-alt** [comment]
Ok, OC integration for the storage drawers is _not_ trivial. (Just exposing drawer controller internal inventory cache is useless).
Simplest workaround is to slap a storage bus on the controller, put an interface on the same cable and place an adapter next to the interface (also don't forget to power that tiny adhoc network). AE integration will do the heavy lifting then.

**Comment by Retster** [comment]
> Ok, OC integration for the storage drawers is _not_ trivial. (Just exposing drawer controller internal inventory cache is useless). Simplest workaround is to slap a storage bus on the controller, put an interface on the same cable and place an adapter next to the interface (also don't forget to power that tiny adhoc network). AE integration will do the heavy lifting then.

I understand that there is no simple solutions, as i hope before. And we will work with thing what we already have. Thank you for investigating.
