### ISSUE TITLE
Collapsible Dolly

### ISSUE THREAD

**Issue by Solotov0** [GTNewHorizons/GT-New-Horizons-Modpack#9325]
### Your GTNH Discord Username

Solotov#5546

### Your Pack Version

2.1.2.0

### Your Proposal

Allow the dolly to be stored in backpacks when not holding an object

### Your Goal

QOL upgrade to keep the dolly more accessible when not in use. 

### Your Vision

Would still not allow nesting to bypass the dolly debuff, just lets you keep dolly nearby without an inventory space

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
If necessary we can make a shapeless recipe to turn an empty dolly into a collapsed one (or make a new layer dolly that can collapse)

**Comment by Ambaire** [comment]
Same (almost) suggestion as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9313
