### ISSUE TITLE
Crafting did not register after tool breaking

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/GT-New-Horizons-Modpack#9327]
### Your GTNH Discord Username

Unreality#4654

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

I crafted 26 water tank sidings with a shift-click, and expected The Water Dilemma quest to complete.

### The Reality

The hammer apparently only had durability for exactly 26, and it broke after the shift-click. I have 26 water tank sidings, but the quest says only 25 were crafted.

### Your Proposal

Register crafting correctly if a tool has exactly enough durability for the multi craft.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Shift click has issues in other cases, but I suspect the tool beak handler broke this. Maybe 🤔
