### ISSUE TITLE
Change Plutonium 238 vein height so it can spawn properly

### ISSUE THREAD

**Issue by fourk** [GTNewHorizons/GT-New-Horizons-Modpack#9331]
### Your GTNH Discord Username

fourk#5436

### Your Pack Version

2.1.2.1

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

![image](https://user-images.githubusercontent.com/101964/147866743-9575bcd9-62e2-4227-a0aa-c396f3ea0033.png)
![image](https://user-images.githubusercontent.com/101964/147866775-e842ccf8-1f29-4622-97c0-8b5fa6a17d04.png)

When visual prospector shows a vein as 'Plutonium' it should contain ores. 

### The Reality

I have found 4 of these so far on Callisto, all of them have no ores, not even the small ores that should be associated with the vein type.

### Your Proposal

Either don't show plutonium as the ore type in visual prospector when those ores don't exist in the marked ore chunk, or spawn the appropriate ores for that vein type.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Colen** [comment]
Annoyingly I don't think this is actually a bug, the vein would've spawned there but the map wasn't high enough so it couldn't do so. Plutonium spawns at 55-120, so you can see how this easily occurs.

The vein should be moved down but I'm not sure how to do that.

**Comment by Dream-Master** [comment]
sure i can do that. Which high you suggest? It can interfear with other mixes.

**Comment by bombcar** [comment]
@SinTh0r4s could visual prospector “realize” a vein failed and not show it?

**Comment by Dream-Master** [comment]
yes if the vein is to small it not shown or if you digg out most if it it vanished /not shown.

**Comment by fourk** [comment]
> but the map wasn't high enough so it couldn't do so.

This makes sense. I ended up exploring further on Ceres and found 2 more failed veins and then 2 that spawned plutonium. Turns out that there aren't actually any small ores of u238/p239/thorium that spawn even on the successful veins, so the scenario of height failure causing both zero ores and zero small ores may be somewhat unique to this ore type. It sounds like Visual Prospector's detection for the failed u238/p239 veins may not be working as intended/expected

**Comment by Dream-Master** [comment]
@fourk ok which high should be good?  35-65 ?

**Comment by fourk** [comment]
Yeah, that would cause far fewer failed oregen instances, which seems reasonable given the very low spawn weight of the vein.

**Comment by bombcar** [comment]
Too bad it can’t try to spawn high as a rich vein, and failing that try low as a poor vein
