### ISSUE TITLE
Can't login with microsoft account.

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/GT-New-Horizons-Modpack#9334]
### Your GTNH Discord Username

Gates_ice#4537

### Your Pack Version

2.1.2.1

### Your Server

Self Hosted/Verified on other server

### Type of Server

Vanilla Forge

### Your Expectation

Logging in through microsoft account should work as majong account.

### The Reality

1. Logged in with microsoft account.
2. Client stucked at "Logging in" screen:
![image](https://user-images.githubusercontent.com/2586057/147872304-76459434-a50d-4910-a2de-56f32863a359.png)
3. On server side log, everytime I tried to login, I see the following log: 
```
minecraft_1  | [09:55:38] [Server thread/INFO]: /10.1.10.5:14050 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: The received string length is longer than maximum allowed (21 > 16)
```

P.S:
Tried this on an some public server and got the same result

### Your Proposal

N/a

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
the login with microsoft account must be set up once by manually logging in in your web browser on the minecraft.net website. It's not a bug.
