### ISSUE TITLE
Tinkers repair bug

### ISSUE THREAD

**Issue by donsofgaming** [GTNewHorizons/GT-New-Horizons-Modpack#9337]
### Your GTNH Discord Username

DonsOfGaming

### Your Pack Version

2.12.0

### Your Server

Epsilon

### Type of Server

Don't know

### Your Expectation

Expect item to be repaired more

### The Reality

item was showed to be repaired less by using more.

### Your Proposal

make the tinkers tool repair more with more ingots and not less

### Final Checklist

- [ ] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
![](https://media.discordapp.net/attachments/234936569360809996/927205662927237160/unknown.png)

vs


![](https://media.discordapp.net/attachments/234936569360809996/927205663225020496/unknown.png)

**Comment by YannickMG** [comment]
Is it a display bug or does it actually drop the durability?

**Comment by bombcar** [comment]
It’s not showing a drop - it’s showing that three ingots repairs less than two ingots.

**Comment by YannickMG** [comment]
Right I can see that, I was just wondering if it just told you it would repair less or if it actually repairs less. I'll assume it's the latter.

**Comment by donsofgaming** [comment]
It repairs the amount it shows nei

**Comment by boubou19** [comment]
iguana tinker tweaks is making your tool repairing less and less the more you use it.

**Comment by donsofgaming** [comment]
Thats fine but it still doesnt add up why using 1 more ingot would repair the tool less than before

**Comment by bombcar** [comment]
It must be at a threshold and three pushed it over but it applies to all three

**Comment by mitchej123** [comment]
Except if you do it with the Lower number and then repair it with one more item it'll do the full repair.  It's annoying

**Comment by bombcar** [comment]
Yeah the repair should be per ingot even if grouped together
