### ISSUE TITLE
Assembly Line Formation Bug

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9342]
### Your GTNH Discord Username

Colen UwU

### Your Pack Version

2.1.2.0

### Issue

Assembly line used to be able to form as 17 long total, this is required because some recipes are 16 inputs and 1 output. This can no longer be done and now the assline must be 15 + 1 long. Needs fixing.

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Does this not force the assline to cross chunk boundaries since it can't go vertical?

**Comment by GTNH-Colen** [comment]
I think the assline can go vertical now but yes it does if you want it horizontal. This has always been the case in GT as otherwise any 16 input recipes are uncraftable.

**Comment by GTNH-Colen** [comment]
See #9350.
