### ISSUE TITLE
A strange recipe for electrolyzing Kyanite Dust

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9344]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Proposal

Remove the configuration circuit from the Kyanite Dust electrolysis recipe

![image](https://user-images.githubusercontent.com/46845681/147890628-324b086a-03ba-4a05-806c-f6e8fa40c707.png)

### Your Goal

Reduce the required minimum of processing mechanisms in the production chain

### Your Vision

In my opinion, the configuration scheme is superfluous here, since this dust has no other application.

If I miss some fact or mechanics, please clarify

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
Should remove the circuit for all dust electrolyzing as there are no conflicts at all iirc. Will leave an additional slot in the input bus of electrolyzer PAs.

**Comment by Dream-Master** [comment]
will recheck but i add circuits for a reason

**Comment by Eldrinn-Elantey** [comment]
I hope you haven't forgotten

**Comment by Dream-Master** [comment]
Recipes is changed after silicon change is added

**Comment by Eldrinn-Elantey** [comment]
> Recipes is changed after silicon change is added

At the time of the creation of this ticket, this substance had no other applications, therefore I was surprised by the need for an electrical circuit. There is no recipe and using just this dust

**Comment by Dream-Master** [comment]
Nope much recipes had circuits. Auto generated recipes don't have it

**Comment by Eldrinn-Elantey** [comment]
> Nope much recipes had circuits. Auto generated recipes don't have it 

If you are sure that everything is fine with this recipe and no changes are required, you can close this ticket
