### ISSUE TITLE
Schematic arc furnace recipe

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#9345]
### Your GTNH Discord Username

Pao

### Your Pack Version

2.1.2.1

### Your Server

Private

### Your Expectation

With schematics being moved to LV, it appears there's a way to get stainless steel in LV now.  

1) Craft a schematic with 4 steel plates + 4 LV circuits

2) Throw the schematic in an arc furnace

3) Get 2 stainless steel

### The Reality

.

### Your Proposal

Might need to adjust the auto-arc-furnace-generator-thingy to not eat schematics?  I dunno

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
ok that need to be changed.
