### ISSUE TITLE
Change Assline Structure

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9350]
### Your GTNH Discord Username

Colen UwU

### Your Pack Version

2.1.2.0

### Your Proposal

Prior to 2.1.2.0 the assline had 16 input and 1 output slot, this has now be changed (bug 🥰) to 15 input and 1 output. This means the current GUI is now wrong as it does not have 16 input slots.

I therefore propose that the assline output be moved to another casing (perhaps the top) and the bottom solely reserved for input casings (16 of them).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Colen** [comment]
Related to the discussion in [#844](https://github.com/GTNewHorizons/GT5-Unofficial/pull/844)

**Comment by bombcar** [comment]
Perhaps allowing the rear middle makes sense (with the option of the top - and bottom as it is now for lines less than max)

top does preserve the “stay in one chunk”

**Comment by iouter** [comment]
just #8940
