### ISSUE TITLE
Improve Air Distillation

### ISSUE THREAD

**Issue by Opyrobe** [GTNewHorizons/GT-New-Horizons-Modpack#9353]
### Your GTNH Discord Username

Opyrbone#2332

### Your Pack Version

2.1.2.0

### Your Proposal

I created a new Air distillation process tree with 3 tiers, 2 new multiblocks and remplace helium from superconductor wire with differently noble gases.

### Your Goal

People spam air compressor to have high quantity or air, Air distillation centrifuge process must be nerfed (too many Helium)
Endgame players aren't use all noble gases in end game tier.

### Your Vision

Please read this text with my Google sheet : https://docs.google.com/spreadsheets/d/1eFzcTxQbc8ibs5tQAqsjujcwBT5zY4PTh3De34ACKDc/edit?usp=sharing

First I compared actual air distillation recipes with value of Reality [see Air Proportion GTNH/Reality]
And I conclude => Centrifuge process are'nt reflect the reality and the Air Proportion of the Reality has more gas than N2,O2,Ar,CO2,Ne,He,Kr and Xe

Second, I create a Air distillation process tree [See update] with 3 tier of distillation. Every tier you unlocked rarer noble gas.
You have 2 new fluids : the Dried Liquid Air and the Pure Liquid Air.

You must put Liquid Air in the new Air dehydrator multiblock [see Air dehydrator craft and math] to have Dried Liquid Air.
You must put  Dried Liquid Air in a Electric Air filter Multiblock to have Pure Liquid Air.

In MK I you have N2,O2 and Ar.
In MK II you have Rare gases fluid that can be distilled to have Ne,He,NO and CH4.
In MK III you have Perfect Rare gases fuid than can be distilled to have Kr,H2,N2O and Xe

Majority of proportion are compliant with the Reallity.

But if we want produce more noble gases, we wee more air. It time to create the new multiblock the Athmosphere Pump [see Athmosphere pump craft and math]

Third,  I see endgame players aren't use all noble gas in end tier game. So I want to change le recipe of all superconductor, and scale them with the rarity of gases.

For me it's not grindy beacause I added a multiblock and a system who we can grind a big amount of air and have noble gases easily.

But I don't know if my recipe are cheap or grindy, maybe I need help to find the best difficulty for GTNH.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I want the first step to fail or require more power (?) if pollution is too high in the chunk.

**Comment by Opyrobe** [comment]
Yes it's a great idea with the pollution update

**Comment by Alastors** [comment]
yeah, if pollution ever does get fixed that is, but overall I like it

**Comment by MrJakobLaich** [comment]
> yeah, if pollution ever does get fixed that is, but overall I like it

I'm working on fixing it ;)

**Comment by Opyrobe** [comment]
Maybe @MrJakobLaich  prevent me when you fixed the pollution and I will start to codding (the only problem is : I don't know codding and I think I finish this project in 4 month if I start :S) so if someone love this project (like me) please prevent me and start co-working on.

**Comment by POPlol333** [comment]
This would require some work, and probably for next-next update, but this looks really interesting
