### ISSUE TITLE
OpenComputer placeDown Bug

### ISSUE THREAD

**Issue by slprime** [GTNewHorizons/GT-New-Horizons-Modpack#9354]
### Your GTNH Discord Username

slprime

### Your Pack Version

2.1.2.0 / 2.1.2.1

### Your Server

SP

### Your Expectation

`Tries to place the block in the currently selected inventory slot `

### The Reality

https://user-images.githubusercontent.com/31038811/148078804-abea63c3-6bfd-43b7-912e-cafce006b6f0.mp4

I took OpenComputers from jenkins.

### Your Proposal

fix?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Florexiz** [comment]
#5657
Strikes again?

**Comment by slprime** [comment]
It is very strange, plants seeds, but takes a shovel
I took OpenComputers from jenkins.

**Comment by repo-alt** [comment]
`place` is bugged for ic2 crops, use `use` atm. It is a bug on ic2 side and can be fixed only via asm/mixin. Unfortunately I didn't  find a way to make work both `place` and `use` (not that I spent much time, maybe some day)

**Comment by slprime** [comment]
Before updates it work
