### ISSUE TITLE
Bookmarks Clipping Through UI

### ISSUE THREAD

**Issue by Erneest** [GTNewHorizons/GT-New-Horizons-Modpack#9355]
### Your GTNH Discord Username

Ernest#1424

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expect it to be normal

### The Reality

Bookmarks overlap items in chest 

### Your Proposal

Fix it I dunno, I gueeess it's just bad wrapping but I'm not a dev so... Here's the bug in action.
![TheProblem](https://user-images.githubusercontent.com/96063310/148107884-4710a06b-6229-491f-b97f-652b966872be.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
Fixed by https://github.com/GTNewHorizons/TinkersConstruct/pull/35
