### ISSUE TITLE
LV disassembler and/or lootgames OP

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#9358]
### Your GTNH Discord Username

Pao

### Your Pack Version

2.1.2.1

### Your Proposal

As part of my perpetual LV run, I'm doing loot games to get gear to get things I'm not supposed to be able to get.  Everyone knows about getting stainless, but I've found some things that probably shouldn't be able to be disassembled in the LV disassembler:

HV Emitters, Sensors, and Robot Arms (gives chrome rods, HV circuits, ender eyes)
Lock Upgrade cover (gives iridium plate)
ULV Solar Panels (gives silicon wafers, MV circuits, reinforced glass, carbon plates; all technically obtainable at LV though)
Player Detector cover (gives titanium and EV sensor, which can also be disassembled for 4 more titanium plates, an EV circuit, and a quantum eye)

These are all items I've received from loot games, and they can all be disassembled in the LV disassembler, which only needs LV robot arms.  

### Your Goal

As much fun as it is having a tricorder at LV, I'm guessing it's not intended.  I don't know what populates the "chest4" loot table but it might need to be tweaked a bit, or look at why the HV+ parts can be disassembled in the LV disassembler.  

### Your Vision

I don't want to live in LV forever!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I suspect all of those can either be made in an LV assembler or via crafting table

**Comment by PolkageistHS** [comment]
Player Detector cover can only be crafted in an MV assembler, but that is true for the rest of the items I've tested so far.  The Lock Upgrade is Iridium + Iron or Aluminium in an LV assembler for 320 seconds, that can probably be adjusted to HV without much complaint from anyone (does anyone even use it? I didn't even know it existed)

For crafting table things that can be disassembled, you can't do that with machines that are higher tier than the disassembler even though they're also crafting table recipes, so maybe that should be extended to the HV components?

**Comment by bombcar** [comment]
Yeah the assembler ones are automatic but the crafting table ones have to be handled by hand (and fixed accordingly iirc!

**Comment by PolkageistHS** [comment]
Still doesn't explain the player detector, since it can only be made with an MV assembler but can be disassembled in an LV disassembler.
