### ISSUE TITLE
Disable VM rotation

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9359]
### Your GTNH Discord Username

Colen

### Your Pack Version

2.1.2.0

### Bug

It can mine through itself

![image](https://user-images.githubusercontent.com/54497873/148146252-136edeb3-33cc-455a-b6bb-30197e82c30d.png)

Need I really add more? Lmao

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Weird, I thought the default for all GT_MetaTileEntity_DrillerBase is straight up only?

**Comment by Glease** [comment]
There must be something wrong with your server/client. Cannot reproduce in any pack version.

**Comment by GTNH-Colen** [comment]
> There must be something wrong with your server/client. Cannot reproduce in any pack version.

It's 2.1.2.0, live on the official server Eta.

**Comment by boubou19** [comment]
cannot reproduce that in dev, so it'll be magically fixed when we will update it.
