### ISSUE TITLE
Input bus variation missing / GUI recommendation

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9360]
### Your GTNH Discord Username

Colen

### Your Pack Version

2.1.2.0

### Your Server

Eta

### Your Expectation

I've noticed that there is no ability to have a "Sorting mode: OFF   Limiting mode: ON" as the variations only loop around the other options when you shift click with the screwdriver.

<img width="409" alt="Screenshot 2022-01-05 at 06 01 24" src="https://user-images.githubusercontent.com/54497873/148168303-232295b9-1559-4121-823e-789c09e7792e.png">

Really we need a new tool for these options to be independent of each other or even better a new GUI inside hatches to document these mostly unknown features?

### The Reality

-

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Is limiting mode dependent on sorting mode being on?

**Comment by GTNH-Colen** [comment]
Don't see why it would be, limiting mode ON prevents any item having more than one stack and sorting mode OFF stops it from sorting the inventory by whatever weird sorting system GT uses.

**Comment by Florexiz** [comment]
It was intended to be dependent on sorting
But new tool will be a good addition

**Comment by GTNH-Colen** [comment]
GUI best, would rather integrate that than have another tool to add to the pile but appreciate that's a bit of a pain.
