### ISSUE TITLE
New multiblock furnace for smelting items into essentia

### ISSUE THREAD

**Issue by berta24** [GTNewHorizons/GT-New-Horizons-Modpack#9361]
### Your GTNH Discord Username

Berta24

### Your Pack Version

2.1.2.1

### Your Proposal

Adding a new multiblock machine, that doesnt require items to be dropped in as an entity, faster than alchemical furnace and in parallel

### Your Goal

In end-game way too much essentia is needed (136M of each aspect for octuple compresser solar panel) and the already existing multiblock are too slow and make the world lag a lot because of all those items inside them... Had some of them with over 100k items and was making 3fps watching that part of the screen.

### Your Vision

it would make essentia in end-game less of a problem, and the existing solutions are too slow/inefficient for the amounts required right now

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by berta24** [comment]
Maybe the new multiblock could require both energy and centivis, to keep the TC theme

**Comment by GTNH-Afx237v7** [comment]
I’m not a thaumcraft expert but maybe we can piggyback off of the already existing essentia power Generator Code-wise? Don’t think it’s necessary to reinvent the wheel. 
A more „professional“ solution to essentia creation is definitely welcome.

**Comment by GTNH-Colen** [comment]
If we had thaumic energistics integration we could have an essentia output bus (ME) directly in the multi. Would make life less of a hassle.

**Comment by berta24** [comment]
that would be perfect, because current Essentia Import Bus even with 2 accel card (2 is max) they cant import more than 10 essentia, and only 1 type per time

**Comment by bombcar** [comment]
![image](https://user-images.githubusercontent.com/533931/148248056-d2a9a92c-bee8-4d2e-a959-375b3e22a3cd.png)

maybe we could reuse the textures for the alembics or similar and make something that kinda looks like a giant engine

**Comment by berta24** [comment]
![alch](https://user-images.githubusercontent.com/25983005/148252477-952e52e0-ebb0-4509-8cbe-ace8a403faef.png)
i was thinking something like this,a bigger version of a real alembic with multi chamber just for aesthetics

**Comment by Jimbno** [comment]
I made a model of what I think this multi could look like, if anyone wants to use it you can find it here https://github.com/Jimbno/Eldritch-elemental-splittter,
3D model and textures all done by me so there shouldn't be any copywrite issues with Thaumcraft.

**Comment by Dream-Master** [comment]
Looks cool now we need somone to make the machine in code
