### ISSUE TITLE
Allow robot arms to grab from input slots

### ISSUE THREAD

**Issue by christianvdstap** [GTNewHorizons/GT-New-Horizons-Modpack#9363]
### Your GTNH Discord Username

Lalaru

### Your Pack Version

2.1.2.0

### Your Proposal

Currently robot arms can not take from an input slot (at least I was not able to make that work, taking from output slots work just fine as taking from "any" slot in a machine hull). For more interesting automation of machines that need a circuit or mold it would be great to allow the robot arm to take from an input slot as well. Bonus points if the robot arm can also be controlled with a machine control cover.

### Your Goal

More gt automation, mainly for swapping recipes that have a non consumable item.

### Your Vision

Since the robot arm is already configured for a specific slot, it should be allowed to access any item in the machine (in my opinion even the battery slot). This allows is to use even more imagination when building machines.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by YannickMG** [comment]
I thought it might also be interesting to allow grabbing from and to the same inventory, for example if you want to store a spare circuit there.

Also robot arms are supposed to be fancy. You should be able to give them multiple simultaneous active configurations. Potentially each could be toggled with a specific redstone signal

**Comment by bombcar** [comment]
The battery slot is intentionally *not* allowed to prevent people using LDIP and batteries for power distribution, but the other slots could possibly be enabled.

**Comment by bombcar** [comment]
On single blocks there is now a "ghost circuit" slot for configuring the circuit, robot arm or OC should be made to be able to interact with that.

**Comment by YannickMG** [comment]
OC definitely. It's not supposed to be a real item though so probably not robot arms.
