### ISSUE TITLE
Rebalance biomass production in brewing machines

### ISSUE THREAD

**Issue by Solotov0** [GTNewHorizons/GT-New-Horizons-Modpack#9364]
### Your GTNH Discord Username

Solotov#5546

### Your Pack Version

2.1.2.1

### Your Proposal

Rebalance the output of Forestry Biomass from the brewing machine produced from honey and Fruit Juice(?)
There is already a bonus in the forestry machine, but currently the brewing machine has no bonus from using honey vs water.  Would be nice to have a bonus amount produced, or a shorter processing time, or some value to justify using a less abundant more bio-dense fluid instead just hooking it up to an infinite water source

### Your Goal

I want a more enriching biomass-production experience, currently water is best/tied for best and water isnt fun.

### Your Vision

This would make more infrastructure=more value for this recipe.  Also need a reason to process honey drops and not void them

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by leagris** [comment]
The GT Brewer is also incapable of applying the Sappiness multiplier that is stored as NBT genome data in the saplings.
