### ISSUE TITLE
Processing pattern terminal doesn't correctly write some recipes

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#9370]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

Being able to autocraft UHV energy hatches

### The Reality

The processing pattern terminal doesn't write the recipe in a form that matches AE2 expectations, instead some items are ignored. Observe the number of coolant cells:
![image](https://user-images.githubusercontent.com/8459776/148301913-0b8e5e30-b13a-4e46-8f02-ba6562524b09.png)
Clearing the terminal and putting the pattern back in does reveal the correct recipe.

The resulting pattern also gets stuck in crafting:
![image](https://user-images.githubusercontent.com/8459776/148301612-7542eaf1-2346-443e-81b4-413d4344d5b1.png)

### Your Proposal

Make AE2 autocrafting compatible with the terminal.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/148365789-31f1f5f9-7fbe-42c0-bd0e-15f06b81bb92.png)
Can't reproduce that in 2.1.2.1, can you check dev pack in single player?

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
