### ISSUE TITLE
Directional Elevator Doesnt work in Cleanroom Floor

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#9371]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

 2.1.2.1

### Your Server

Private Server 

### Type of Server

Crucible

### Your Expectation

As the patch note said, elevators work in cleanroom floors
I went and made one and it works!
but then I want the elevator to be directional for reasons 
I made a rotating elevator and put it in place, and it doesnt form

### The Reality

There's no way I can screenshot them together as the FOV only go so far..

### Your Proposal

Make rotating elevator work in cleanroom floor as there's no reason why it isnt
Also maybe the traveling anchor can be added? pretty please?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
In config/gregtech/gregtech.cfg in the section

cleanroom_allowed_blocks {

add a section for the rotating elevator and it should work

**Comment by bombcar** [comment]
```
    elevator_rotating {
        I:Count=1
        S:Name=tile.openblocks.elevator_rotating
    }
```
