### ISSUE TITLE
木炭堆点火器

### ISSUE THREAD

**Issue by herolaser** [GTNewHorizons/GT-New-Horizons-Modpack#9374]
### Your Pack Version

2.1.2.1

### Your Server

sp

### Your Expectation

修复木炭堆点火器的问题

### The Reality

木炭堆点火器在100S的时候自动停止

### Your Proposal

木炭堆点火器运行到100S 的时候会自动停止

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by YannickMG** [comment]
Might be the same as #9055 and #9273.

**Comment by GTNH-Colen** [comment]
For future reference tickets should be submitted in English when possible as this is the language that all of the team has in common.

**Comment by YannickMG** [comment]
GTNewHorizons/GT5-Unofficial#859
