### ISSUE TITLE
Sugar composition complete Bogus

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9375]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.1

### Your Server

private

### Your Expectation

Sugar should not mysteriously be >90% oxygen.

### The Reality

Sugar has the very weird (and wrong) composition of C2(H2O)5O25:
![sugar](https://user-images.githubusercontent.com/10967188/148327318-b93fe5d1-bd0d-46c6-80c8-8f760f7ceb72.PNG)

It is not only the molten one, but also the electrolyzer recipes.

### Your Proposal

If we assume Sucrose (the sugar people usually refer to when just saying "Sugar"), it should be something like C12H22O11. The molten sugar as well as the electrolyzer recipes should be changed accordingly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
Any ideas on this?

**Comment by cubic-chariot** [comment]
We had a brief discussion on Discord about this. Summary:
- Given that a lot of GT chemical recipes follow real-world chemistry, and real-world "sugar" typically means "sucrose" (whose chemical formula is C12H22O11), having the GT version of sugar be more than 90% oxygen is counterintuitive
- However a chemically correct electrolysis recipe would either overshadow water electrolysis, or its cost would be nerfed to be as expensive as water electrolysis
- Nerfing this recipe is not entirely bad, as it pushes players towards other renewable oxygen sources, like the cobblestone->oxygen line (which is more complex and requires more logistics planning and problem solving from players)
- Alternatively, another chemical process could be created to get some oxygen from sugar, and sugar electrolysis could be added to later tiers without affecting neither the chemical balance nor the viability of producing oxygen from sugar

**Comment by boubou19** [comment]
![warn-overthinking-011-1](https://user-images.githubusercontent.com/12850933/226156059-af118728-109f-4a5e-90ab-887a7502e4fb.png)
