### ISSUE TITLE
Add OC method to cancel AE crafting

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9379]
### Your GTNH Discord Username

Colen

### Your Pack Version

2.1.2.0

### Your Proposal

Pretty simple, see title. Not sure how hard this would be to add but at present AE crafting automation sometimes gets stuck after a restart, having a method to cancel it would mitigate this and be something handy to have overall.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
You are not worried that some random stuff may get stuck in in input buses?
I think it is possible to enumerate running jobs and return the same callback you get when ordering from OC

**Comment by GTNH-Colen** [comment]
> You are not worried that some random stuff may get stuck in in input buses? I think it is possible to enumerate running jobs and return the same callback you get when ordering from OC

For my use case this won't happen, the real issue is that the arcane assembler gets stuck after a server restart and I want to use OC to get around this issue. Ideally the assembler could be fixed. You'll hate this but I even tried using a block breaker on the crafting unit and then a block placer to put it back. This cancels the craft but also instantly crashes the server.

**Comment by bombcar** [comment]
Player initiated crash of server sounds like soemthing we should fix …

**Comment by GTNH-Colen** [comment]
Yea, that is an odd bug. Guess I could spin it off into a separate ticket unless it's something super obvious and quick that @repo-alt can address.

**Comment by repo-alt** [comment]
ffs, block breaker on the crafting unit, that's what you get for your sins...

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/148461318-bcff3854-e6ad-48ec-9443-8b28e13ed83b.png)

**Comment by GTNH-Colen** [comment]
Love you @repo-alt 🥰🥰🥰
