### ISSUE TITLE
Some materials take way more time to be fluid extracted from ingot than any other version(plate, frame...)

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9382]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

unify the recipe times, because right now i feel like some are manually set, others are auto generated. This result in pointless recipe cheesing because why one would spend 360s to fluid extract an ingot while it can be made much faster from a plate?

this actually takes 22.5s to be fluid extracted at LuV
![image](https://user-images.githubusercontent.com/12850933/148414262-dc93f965-cd17-4dd3-92c9-f0ea2047d7d9.png)

meanwhile:
![image](https://user-images.githubusercontent.com/12850933/148414384-70aab78f-91ff-49ce-9506-ff893bee4354.png)

### Your Goal

remove some weirdness in the recipes

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Isn't this because the plate is an LuV recipe (wtf) and the other is MV? We'd expect an MV recipe to not overclock cleanly to LuV speeds.

**Comment by Sphyix** [comment]
.

**Comment by boubou19** [comment]
i encountered some weird code in gt++ where the time of the recipes are encoded to be X * material tier, where X is a constant in the code. We might want to rework those constants.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/commit/e22098960103fc7de708301134de20859ddc1a7f#diff-9058f9f2d9187c911a1e8db2aea38c06d2e8ad88addb64de35193a404f0a7de4
