### ISSUE TITLE
Replacing ardite and cobalt dust from TiC with their analog and GregTech

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9384]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Proposal

To make it so that in the recipe for crushing ardite and bovalt ore Tinkers’ Construct in macerator, with a 10% chance, a speck of dust fell out from gregtech and not from Tinkers’ Construct

![image](https://user-images.githubusercontent.com/46845681/148443623-4cebdf57-1bed-494f-b521-810815877baf.png)

![image](https://user-images.githubusercontent.com/46845681/148443652-88d67571-6f22-46d2-bce8-081a2ccf39bb.png)

### Your Goal

Dust from Tinkers’ fashion Construct does not fit into the "dust" type in the type filter of GregTech, which is why additional actions are required for the processing of these ores during automation

### Your Vision

Unification of ardite and cobalt dust will make it easier to set up automatic ore processing using type filter. This modpack is built mainly around GregTech, so the transfer of all (as far as possible) dust, ingots and plates from other mods to such analogues that are already available in GregTech is a logical step

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by schneid3306** [comment]
I would also appreciate this happening. It would help my ore processing setup.

**Comment by Eldrinn-Elantey** [comment]
?

**Comment by Alastors** [comment]
> How are things going with this question?

Why would we "unify" cobalt and ardite in this sense, when as you have confirmed yourself, these recipes do not give the TiC versions of the dusts, but actually the intended GT versions of the dusts? I'm not entirely sure of the point of all of that?

**Comment by Alastors** [comment]
> How are things going with this question?

Can you confirm that this recipe is current in the latest dev? I might be able to get skewer to just change the recipe with that recipe tweaker thing, I mean, they shouldn't be producing TiC dusts anyway, so I'm assuming this must be an auto-generate recipe?

**Comment by Eldrinn-Elantey** [comment]
> > How are things going with this question?
> 
> Can you confirm that this recipe is current in the latest dev? I might be able to get skewer to just change the recipe with that recipe tweaker thing, I mean, they shouldn't be producing TiC dusts anyway, so I'm assuming this must be an auto-generate recipe?

Launched the latest available version (2.2.0.0-RC-2) of the client and checked the recipes for processing ardite and cobalt ore TiC in Pulverization. At the output we still get dust from TiC and not from GT

![image](https://user-images.githubusercontent.com/46845681/190109127-7cdb48ce-4826-4587-a5a1-07207ef66ee9.png)
![image](https://user-images.githubusercontent.com/46845681/190109143-3125b63f-72d0-409d-a04e-1bc958ca1043.png)
![image](https://user-images.githubusercontent.com/46845681/190109148-f5270e65-e348-432c-9090-8fb884fa2eb6.png)
