### ISSUE TITLE
Lower combustion generator efficiency past HV

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#9390]
### Your GTNH Discord Username

0lafe#3719

### Your Pack Version

Newest

### Your Proposal

Right now there seems to be singleblock EV and IV combustion generators. This makes the LCE kind of useless. My suggestion is to treat these the same way alk treats the singleblock rocket gens. Lower their efficiency so the LCE is more viable for power generation. 

I'd recommend values around 60% efficiency for EV and 50% for IV

This makes them very useless for power generation, but very powerful for running offsite machines. Similar to rocket generators. Unless I'm missing something here, it's pretty easy to run a ton of these and reach fusion on only diesel. 

### Your Goal

Singleblock generators are pretty OP in EV+. Diesel gens even more so, as the bottleneck is almost always the generators. A quick example is how you can make ~500k eu/t worth of fuel in ~7 multis, but running that much fuel would take over a hundred LCEs. Reducing the efficiency would make them useless for main power generation, but still give them a ton of utility in remote power gen. You won't be able to run your base on them, but you can run a few miners and drilling rigs. 

### Your Vision

This would keep the multiblock as the dominant combustion fuel generator, as well as keeping combustion fuels in tiers that fit their complexity. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by draknyte1** [comment]
Glod added them as a meme, they should just be removed.

**Comment by GlodBlock** [comment]
i will give them 10% and 5% efficiency. uwu

**Comment by bombcar** [comment]
Nah, work out how much energy they make, and require roughly that in pollution mitigation. Nobody will care if using it for a drill on mars, but it becomes untenable as a base gen. 🥇

**Comment by Hikari1nVoid** [comment]
I'll suggest EV@72% and IV@65%.These blocks should not be main power source instead a portable power source for drills and quarries.

**Comment by leagris** [comment]
What does it fix? Are people actually abusing these single-block generators instead of progressing, even if these EV and IV already consume stupid amount of fuel per tick?

**Comment by bombcar** [comment]
> What does it fix? Are people actually abusing these single-block generators instead of progressing, even if these EV and IV already consume stupid amount of fuel per tick?

at some point we can't protect users from their own silliness, if they want to ride CBD into LuV on single blocks let them eat cake I say.

We provide steam turbines all the way up and always recommend against their use. Unless these are proven to be "stupid good, better than the LCE" then leave them alone lol

**Comment by 0lafe** [comment]
@leagris yeah, strictly speaking these generators are a lot better than the multiblock version. It would be one thing if it was another multi, but single blocks being better than multiblocks is a bit cheesy for EV/IV. In my last play through I didn't touch the LCE multi at all, because the EV gens are so good.

**Comment by leagris** [comment]
Maybe, have a check if the LCE multi can be improved, because running the Multi in Turbo mode with Oxygen input is quite an annoyance.

**Comment by draknyte1** [comment]
They were snuck in in an unrelated PR without any input from anyone. They shouldn’t even exist.
