### ISSUE TITLE
analyzing prospection data book bug 

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#9393]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

![image](https://user-images.githubusercontent.com/59776356/148591530-1000dd8d-a706-4d70-bed8-1d5c2752f683.png)
if you put multiple (difference) printed page of analyzing prospection data in a assembler at once you will get the same book

I am using an IV assembler with the leather recipes

How to place multiple print pages at the same time: Can run other a longer recipe first , Use the time when the machine is running the previous recipe put everything in (leather& multiple printed page) 

### The Reality

I think the assembler likely ignored the data in printed page and considered all printed page the are the same 

### Your Proposal

I don't think this should happen

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by thibaut-fagart** [comment]
I (Finndibaenn on discord) just hit the same bug, and samsonsin on discord reported the same too when i mentioned it
https://discord.com/channels/181078474394566657/234936569360809996/933095433490800681
