### ISSUE TITLE
Zoom in Galaxy Map broken

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9397]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.1

### Your Server

private

### Your Expectation

Since 2.1.2.1, zooming in the Galaxymap is broken, which makes it very annoying to fly to the other systems. Finding Banard or Vega is quite hard because you need to scroll several screens in the precise direction.

### The Reality

it is broken.

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
I've tested the latest Galacticraft (3.0.36-GTNH) and latest GalaxySpace (1.1.10-GTNH) versions against 2.1.2.0 and it works fine, meaning this bug is likely introduced by another updated mod.

**Comment by 4gname** [comment]
Fixed this problem https://github.com/GT-IMPACT/NotEnoughEnergistics/commit/f3bb27cf7a6e685f3bc5b60936e75616fff99f83 

Sorry I don't have a computer nearby to make a PR.

**Comment by glowredman** [comment]
Fixed as of https://github.com/GTNewHorizons/NotEnoughEnergistics/commit/958f853c0f63e072c7b29153653954d18cf4ccaa
