### ISSUE TITLE
AE voiding stuff 

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#9399]
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.2.0 (latest)

### Your Server

Delta

### Type of Server

Don't know

### Your Expectation

Using AE and everything fine

### The Reality

So actually, due to electricity problem I plugged my ME to my PSS via aluminium cable
![image](https://user-images.githubusercontent.com/76914762/148629804-a2e2b09b-c16f-40f5-b363-70a9efd0e29c.png)

when I change dim and come back the AE turn off, but meanwhile, if I've putted stuff recently before changing dim the AE just rollback itself and void everything I've done with it, including new patterns, what is in the craft interface and even the item I've recently putted into storage

### Your Proposal

I guess fix the energy problem between PSS and AE

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment]
It seem that just switching dim rollback the AE from time to time, even without the energy problem

**Comment by repo-alt** [comment]
Is it garden dimension or something? Has nothing to do with AE, may happen to any machine

**Comment by POPlol333** [comment]
It is void dim
