### ISSUE TITLE
"Wooden Bolts" quest bug

### ISSUE THREAD

**Issue by Relvl** [GTNewHorizons/GT-New-Horizons-Modpack#9400]
### Your GTNH Discord Username

Johnson1893#1084

### Your Pack Version

2.1.2.0

### Your Server

Official EU #2 (epsilon)

### Type of Server

Don't know

### Your Expectation

Correct and logical quest requirements

### The Reality

"Wooden Bolts" quest requires a fletching pattern. But every fletchings in the game crafts via the extruder, and dont need it.
![image](https://user-images.githubusercontent.com/4003026/148643749-eb565fea-21d8-456c-969b-e9f9daa31305.png)
![image](https://user-images.githubusercontent.com/4003026/148643771-5d2747d4-b6dd-4bc5-8516-d9166c07a12d.png)

### Your Proposal

Fix the bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
You can also craft them by Part Builder.

**Comment by ApexPredaturr** [comment]
Am I wrong in thinking that the wooden stencil IS NEEDED to create the original mold that you then cast onto aluminium brass to get the extruder cast? Meaning that part of the quest is actually relevant?

**Comment by chochem** [comment]
as miozune already pointed out, the quest is correct.
