### ISSUE TITLE
Concentrated Enriched-Naquadah Sludge Dust not possible in Autoclave?

### ISSUE THREAD

**Issue by Blade8895** [GTNewHorizons/GT-New-Horizons-Modpack#9402]
### Your GTNH Discord Username

Blade8895#6067

### Your Pack Version

2.1.2.1

### Your Proposal

The recipe from 
Sodium Hydroxide Dust with Enriched-Naquadah-Rich Solution 
to 
Concentrated Enriched-Naquadah Sludge Dust and P-507 
in the Autoclave wont work.
Because an Autoclave can only accept 8k of an Fluid as in input.
![javaw_XR9m5Mcvte](https://user-images.githubusercontent.com/76847661/148647573-467ec8ab-1f9c-4340-b968-040d9339d369.png)
 

### Your Goal

Make the Recipe possible without an PA or LPF

### Your Vision

probaly increasing the internal Tank size in Steps like the other machines (i think about the Assembler)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Can you check if the EV autoclave has a bigger tank

**Comment by Blade8895** [comment]
LuV aswell ZPM had 8k internal tank.

**Comment by Blade8895** [comment]
![javaw_zzcIndnzHq](https://user-images.githubusercontent.com/76847661/148648450-7e5c2766-e260-45f9-a490-6b644ccfee4e.png)

**Comment by bombcar** [comment]
Tank sizes were rebalanced but obviously not enough or didn't touch autoclave. Unless this is supposed to force you to use a multi block autoclave (does it even exist).

**Comment by Blade8895** [comment]
the LPF had an Autoclave mode but its a bit oversized in my opinion.

**Comment by GlodBlock** [comment]
well it's my fault and i will adjust the recipe to make it fit the single block autoclave. a temporary solution is to use a PA or LPF to make it

**Comment by GlodBlock** [comment]
added a new recipe:
![image](https://user-images.githubusercontent.com/60341015/148743705-0dc0cb76-70e5-48a1-bf6b-af90d6f8a016.png)
the white dust is KOH
