### ISSUE TITLE
Update 2.1.2.2

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9404]
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9323
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9405
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9345

**Comment by Savallator** [comment]
This (#8806  would be nice, and i think a rather small change.

**Comment by bombcar** [comment]
[ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9441

**Comment by riking** [comment]
- [x] #9096 fixed for real this time
