### ISSUE TITLE
add assembler recipe for the solar panel

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9405]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

add an assembler recipe for this recipe:
![image](https://user-images.githubusercontent.com/12850933/148649055-286ada0c-4776-40c7-a580-4ffbfea2b408.png)

### Your Goal

obliterate lag induced by other means of spamming this recipe, as it's used a lot in the octuple compressed solar panel recipe.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
On some of these, does it make sense to also remove the crafting table recipe ... ? Would break auto crafting setups but if they're laggy that's a price I'm willing to have others pay. 🥇

**Comment by boubou19** [comment]
it's up to server owners to dictate what shouldn't be abused. The recipe itself isn't harmful, the 32 molecular assemblers with 5 acceleration cards are (hello @Sphyix @GTNH-Colen). Also a lot of recipes have their counterpart in the assembler, sometimes cheaper, sometimes equal in cost. So this totally makes sense to add it, the removal doesn't tho.

**Comment by GTNH-Colen** [comment]
Don't remove the recipe, if you add this it's a no brainer transition as I can craft them faster and easier this way. Molecular assemblers were a dirty hack because of the limited options.
