### ISSUE TITLE
Changing Recipes in Rock Breaker

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9406]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Proposal

Please change the working principle of rock breaker. Namely, to add the need to use configuration circuits to select its products. For example, the configuration circuit 1 for the output of a cobblestone, 2 for a stone (if I remember correctly, this changes the position of water and lava, if so, then you can also use the configuration circuit 1), and redstone to obtain obsidian

### Your Goal

This is necessary for a more flexible configuration of the operation of this machine

### Your Vision

There are cases when obsidian is needed, say two stacks, put this machine, gave it two stacks of red stone, took the products and so that it does not start producing cobblestones, you need to either turn it off with a mallet or de-energize it, which adds unnecessary fuss with it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
If it's submerged by lava, i.e. below a lava block, it will produce stone. If it's next to lava block, it will produce cobble. No need to add config circuits.
