### ISSUE TITLE
If the warp tumor actually gets fixed, up the warp removal, 50 is absolutely nothing now

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9407]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.1

### Your Proposal

Well, I'm absolutely fine with the warp tumor as it is, but in the current state of thaumcraft, 50 warp is absolutely nothing, and the only reason people still use the tumor, as is known, is because it removes more than that.

So if we actually fix that, we should up the removal from 50 to around 100-200, since 50 used to be a lot, to the point of like base degradation. 

So I propose that we should shift it up to at least the same point that base degradation happens in the current fork of warp theory. 

### Your Goal

To make the warp tumor not useless if it gets fixed.

### Your Vision

Well, if the infinite warp removal gets fixed, then the tumor will actually be useless since 50 warp is nothing. So I just want to increase it's limit in respect to the new warp theory fixes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
I think it is balanced against impure tear removing permanent warp down to 50
