### ISSUE TITLE
Wrong Quest (Tier 0.5 - Steam - I Know His Name!)

### ISSUE THREAD

**Issue by DakronHunter** [GTNewHorizons/GT-New-Horizons-Modpack#9408]
### Your GTNH Discord Username

Dakron

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

I wanted to craft a **Name Remover**.
![Снимок экрана 2022-01-08 201221](https://user-images.githubusercontent.com/97313691/148654620-e5acdc40-b307-4d81-b997-eaf8eb4d0811.png)
![Снимок экрана 2022-01-08 201255](https://user-images.githubusercontent.com/97313691/148654624-e58b669e-f3ba-410b-bdb5-9de13e940487.png)

### The Reality

**Wrought Iron** is required to craft a Name Remover. **Wrought Iron** is not yet available.
![Снимок экрана 2022-01-08 201350](https://user-images.githubusercontent.com/97313691/148654676-e4394401-0242-4384-8cbc-7df569c33a97.png)
![Снимок экрана 2022-01-08 201721](https://user-images.githubusercontent.com/97313691/148654682-e35757ff-46f6-41d6-9954-d19996e88b66.png)

### Your Proposal

Do not open the quest (**I Know His Name**!) for the Name Remover until the quest (**Better Than Iron**) for Wrought Iron has been completed
![Снимок экрана 2022-01-08 201142](https://user-images.githubusercontent.com/97313691/148654738-daa750de-a11b-4a6f-98a3-dd7ab9e7e69c.png)
.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by YannickMG** [comment]
Should probably be handled along with #9396

**Comment by bombcar** [comment]
We have the “dotted line” to show further dependencies if needed

**Comment by DakronHunter** [comment]
> We have the “dotted line” to show further dependencies if needed

Do you mean so?)))
![148654738-daa750de-a11b-4a6f-98a3-dd7ab9e7e69c](https://user-images.githubusercontent.com/97313691/148655577-dd06530c-c801-47ec-9ca7-ad37f21606fe.png)

**Comment by DakronHunter** [comment]
Type: Quest Change

**Comment by YannickMG** [comment]
Yes, would only appear on mouse-over.

**Comment by DakronHunter** [comment]
> Yes, would only appear on mouse-over.

how can i add the Labels? like **Type: Quest Change**

**Comment by YannickMG** [comment]
What, wait do you mean by " Wrought Iron is not yet available."? If you have a compressor than you can make wrought iron, even though you don't yet have a quest to do it.

Part of the solution here should be to link wrought iron to the compressor.

**Comment by DakronHunter** [comment]
> What, wait do you mean by " Wrought Iron is not yet available."? If you have a compressor than you can make wrought iron, even though you don't yet have a quest to do it.
> 
> Part of the solution here should be to link wrought iron to the compressor.

I just suggest linking these quests. After all, all improved machines are made of this iron, and they open after the quest (Better Than Iron).
