### ISSUE TITLE
Add tooltip to railcraft tanks indicating their capacity per block

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#9409]
### Your GTNH Discord Username

Lord_Anarack#2705

### Your Pack Version

2.1.2.1 

### Your Proposal

Railcraft tanks should follow all other tanks and state what their capacity is, especially after new tiers of tank was added

### Your Goal

It is not documented anywhere in game how large theses tanks are.

### Your Vision

Giving people the information to make informed discussion isn't a bad idea.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LewisSaber** [comment]
its already done
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9778

**Comment by Dream-Master** [comment]
ok good to know
