### ISSUE TITLE
Essentia Diffusion Cells are awkwardly tiered and too steep in cost.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9413]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.1

### Your Proposal

<img width="587" alt="Screen Shot 2022-01-08 at 1 32 11 PM" src="https://user-images.githubusercontent.com/78517796/148657278-e09d4ee8-2b59-45dd-ad23-5a0d3eaef2fb.png">
<img width="591" alt="Screen Shot 2022-01-08 at 1 32 17 PM" src="https://user-images.githubusercontent.com/78517796/148657283-2606f85b-fbd5-4a31-b8b9-ae9631162a60.png">
<img width="667" alt="Screen Shot 2022-01-08 at 1 32 22 PM" src="https://user-images.githubusercontent.com/78517796/148657285-7e5ae68c-be48-450f-9a59-5285dd284b22.png">
<img width="731" alt="Screen Shot 2022-01-08 at 1 32 26 PM" src="https://user-images.githubusercontent.com/78517796/148657290-0333f7b7-21c7-42de-ae71-51994145b035.png">

I propose, that instead of having each diffusion cell gating one tier, they each gate 2 tiers, novice = hv + ev, etc.

Also I propose that the cost for EDCs be reduced just a tad

The first (novice) tier is gated perfectly, sure it's a harsh an' expensive recipe, and so it's fine. It uses HV materials which makes sense for an HV tiered multi.

HOWEVER:

The EV tiered one is tiered with materials that are highly late EV tiered for ev tiered power, and at that is kind of extreme compared to what it is, though, I will note, if each diffusion cell was useful for two tiers, this would solve the issue entirely, and give the LEG a little more usability within the pack as a whole.

<img width="440" alt="Screen Shot 2022-01-08 at 1 43 13 PM" src="https://user-images.githubusercontent.com/78517796/148657586-e40bea8e-dbe5-40a0-a3a6-4e7ab229dc40.png">
not only does it use 25 quantum stars per multi, 
<img width="425" alt="Screen Shot 2022-01-08 at 1 43 31 PM" src="https://user-images.githubusercontent.com/78517796/148657594-93c6346a-c17d-41f1-9fc7-20a0389fad8b.png">
it also uses 25 desh gears, the plat springs are whatever, but still.

it also uses tungstensteel, which is kind of strange but whatever.
<img width="459" alt="Screen Shot 2022-01-08 at 1 44 13 PM" src="https://user-images.githubusercontent.com/78517796/148657614-d2093aac-2493-445e-98b6-32c0a73ee3d9.png">
on top of that, it breaks continuity, by using fluid regulators, where the previous tiered ones used pumps
<img width="514" alt="Screen Shot 2022-01-08 at 1 44 53 PM" src="https://user-images.githubusercontent.com/78517796/148657636-f6bc8aaf-97a0-4834-ab3d-1507b5c387f2.png">

### Your Goal

I think it would do the cells some good to give them a slight buff, that would offset their extreme cost.

### Your Vision

The LEG is rather new and hasn't been fully tuned yet, and a buff like this would help it get toward a proper tiering like it should have.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
if anyone has anything else to say, please do. I lost motivation mid writing this so it kinda drops off a cliff...

**Comment by Alastors** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9414

**Comment by bombcar** [comment]
desh is EV but it's "late EV" vs "early EV"

which its a big difference tbh
