### ISSUE TITLE
A change for how a couple of parts of the  new Large Essentia Generator work.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9414]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.1

### Your Proposal

I thought of a better way to do it, after writing the last one.

Instead of using the coils to gate each tier of hatch... why not just gate efficiency based off the essentia diffusion cells tier.

Lets take the EBF for example, you don't gate the ebf's energy hatches based off it's coils. 
You can just keep upgrading the hatches and ports, and it'll keep getting faster and better overall, you upgrade the coils to unlock the ability to smelt new tiers of metals and such.

Likewise, how about instead of gating the dynamos on the LEG by the diffusion cells, how about we use the diffusion cells to add a multiplier instead? 

Perhaps the novice ones would add a 0.5x multiplier to the eu per essentia point, it already does this with with the essentia generator upgrades such as thermal, which can make custom1 go from being worth 300,000 Eu per point (or whatever it is), to around 18.9 mil Eu per point (or wahtever) with it's coefficients and all that!

Why not apply a similar factor to the diffusion cells then! So that you can keep using it no matter what tier you're in, it just might be more or less efficient per tier!

Say Novice was gated at MV and was 0.5x

Adept was gated at Ev and was either 0.75x or 1x

Master was gated at LuV and was either 1x or 1.5x or even 2x

and Grandmaster being gated at UV and being between 2x and 4x or something!

### Your Goal

The LEG is a rather new multi, and I feel that it could use a little boosting, and I feel that the current method of gating each power tier using it by it's diffusion cells is a rather lame and poor execution for what it could be! I don't think the diffusion cells should gate it's power production, that kind of makes it fall behind compared to other power producing multis, and we need to remember, this isn't an infinite eu generating machine like the MEA, this is a finite machine like any other, so as such, should be treated like that!

### Your Vision

I think that by giving this multi a boost in this way, it will be fine tuned a lot more to what it was meant to be, and even give people a reason to use thaumcraft more than it is! Because as it currently is, it's only really useful for HV tiers rn as the rest of it's parts are getting in the late tiers of their respective power outputs, and with that, makes it sort of useless for it's tier, since 4x EV power by the end of EV for a fuck ton of desh is kind of piss in output!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GlodBlock** [comment]
yeah let EDC give a addition multiplier to the power is a good idea. but the problem is here if i revert gating hatch: it supports mulit amps hatch. it means you can actually get 64a iv in iv-tier. (manii used few fields of terrawart for Auram to feed the LEG and got 64a iv output stablely before). it is too OP. the adept cell's recipe is actually shitty and deserve modifying but the left are ok imo, the master cell can give you 1a uv if you run with a 64a iv hatch.

**Comment by repo-alt** [comment]
As a result you overnerfed Aer upgrade I think. Now it requires some high tier noble gas that is really hard to obtain. Other upgrades are expensive but not even close to that.

**Comment by GlodBlock** [comment]
not really, the tained and thermal upgrade is obtainable in HV/EV and also unlock some powerful essetain. the noble gas that gates air upgrade are Ne and Kr and gt++ added another way to get them easier(distill 100m liquid air isn't necessary),

**Comment by repo-alt** [comment]
Tainted looks a bit OP tbh. Thermal is maybe too weak in comparison, not sure, needs testing.

**Comment by Alastors** [comment]
> Tainted looks a bit OP tbh. Thermal is maybe too weak in comparison, not sure, needs testing.

Thermal with Custom1 is actually not that bad ngl

but that is the exception

**Comment by Alastors** [comment]
> yeah let EDC give a addition multiplier to the power is a good idea. but the problem is here if i revert gating hatch: it supports mulit amps hatch. it means you can actually get 64a iv in iv-tier. (manii used few fields of terrawart for Auram to feed the LEG and got 64a iv output stablely before). it is too OP. the adept cell's recipe is actually shitty and deserve modifying but the left are ok imo, the master cell can give you 1a uv if you run with a 64a iv hatch.

then limit it somehow if you can, idk man, I did mention in my other post that one change that could be good for this would be to make each diffusion cell gate 2 tiers instead of just one

**Comment by Alastors** [comment]
> yeah let EDC give a addition multiplier to the power is a good idea. but the problem is here if i revert gating hatch: it supports mulit amps hatch. it means you can actually get 64a iv in iv-tier. (manii used few fields of terrawart for Auram to feed the LEG and got 64a iv output stablely before). it is too OP. the adept cell's recipe is actually shitty and deserve modifying but the left are ok imo, the master cell can give you 1a uv if you run with a 64a iv hatch.

or perhaps you could even go so far as to make a variant of the energy hatches, that look the exact same, and have the same function, but are specifically only used for this multi, and gate it at like 16x or whatever. You know? Or honestly even just remove Auram's compatibility with it, since it is one of the most common aspects you can get with various thaumic farms, though I personally don't think a single case scenario should be a factor for what feels like a bit of an overnerf with gating electricity by an extremely expensive upgrade, you know? Especially when it make the earlier tiers suffer since neither hv, nor EV have higher tiers of those, being capped at 4x dynamos themselves, since dynamos that are above that start at IV. Which in itself would give a good example of maybe why diffusion cells maybe should gate energy tiers in pairs of 2 instead of just a single level each?

**Comment by GlodBlock** [comment]
if the cell gates hatch 2 tiers, you will be able to use UEV hatch with grandmaster cell. it is bit scary and you actually can't reach that high output cuz the max essentia input speed is 1 essentia/t, which makes the grandmaster cell useless. i perfer to raise one tier gate on the hatch and their recipe needs to be rebalanced.
novice cell: EV tier, don't change recipe
adept cell: IV tier, should be unlocked in mid IV(cuz you can use mutil amps hatch at this tier).
![image](https://user-images.githubusercontent.com/60341015/148914035-5f3794fb-c6ad-4239-b1f9-3ea718bc9e82.png)
master cell: LuV tier, unlocked in early LuV
![image](https://user-images.githubusercontent.com/60341015/148915532-2a4764a2-fd61-404c-a061-d83f9ce4e7ec.png)
grandmaster cell: ZPM tier, unlocked in late LuV
![image](https://user-images.githubusercontent.com/60341015/148918007-9fb02c35-1557-4d40-9e25-344e0b1b9863.png)

**Comment by Alastors** [comment]
> if the cell gates hatch 2 tiers, you will be able to use UEV hatch with grandmaster cell. it is bit scary and you actually can't reach that high output cuz the max essentia input speed is 1 essentia/t, which makes the grandmaster cell useless. i perfer to raise one tier gate on the hatch and their recipe needs to be rebalanced. novice cell: EV tier, don't change recipe adept cell: IV tier, should be unlocked in mid IV(cuz you can use mutil amps hatch at this tier). ![image](https://user-images.githubusercontent.com/60341015/148914035-5f3794fb-c6ad-4239-b1f9-3ea718bc9e82.png) master cell: LuV tier, unlocked in early LuV ![image](https://user-images.githubusercontent.com/60341015/148915532-2a4764a2-fd61-404c-a061-d83f9ce4e7ec.png) grandmaster cell: ZPM tier, unlocked in late LuV ![image](https://user-images.githubusercontent.com/60341015/148918007-9fb02c35-1557-4d40-9e25-344e0b1b9863.png)

I completely agree with this change, and I am glad that you were willing to work with me on this! I think this will be a much needed change for the better for this multi, especially since the higher tier hatches aren't unlocked until IV!

Thank you so much! I really appreciate it!!! <3
