### ISSUE TITLE
Chandeliers not stopping mob spawns

### ISSUE THREAD

**Issue by pariator** [GTNewHorizons/GT-New-Horizons-Modpack#9416]
### Your GTNH Discord Username

Randy#4245

### Your Pack Version

2.1.2.1

### Your Server

private server with ftb utils installed and HC darkness removed

### Type of Server

Don't know

### Your Expectation

Placing a chandelier should prevent mobs from spawning even when the light level is below the level required to prevent mob spawning. (Extant chandeliers were placed prior to the upgrade that no longer function)

### The Reality

Chandeliers no longer prevent mobs from spawning.

### Your Proposal

Fix/disable chandeliers.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Does the server have AMDIforge in the mods folder?
Remove it if so.

**Comment by bombcar** [comment]
delete AMDIforge from the server and reload.

**Comment by pariator** [comment]
Huh. Thanks for that. It does have AMDIForge, and I will give that a try. I should have probably checked the closed issues in retrospect. I had assumed this was a bug of some kind.

**Comment by bombcar** [comment]
It was and finally fixed but after 2.1.2.1 - AMDIForge is mainly for the officials (it does some tracking and mob spawn limiting but it broke the torch and chandelier).
