### ISSUE TITLE
Basic assembling machine doesn't make circuit board as well as resistor and garden soil

### ISSUE THREAD

**Issue by zhookevil** [GTNewHorizons/GT-New-Horizons-Modpack#9417]
### Your GTNH Discord Username

Max#1269

### Your Pack Version

2.1.2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Well, I put all the stuff in the machine according to the recipe and expect it assemble for me. I use MultiMC.

### The Reality

I put all the things inside and nothing happened. If I add more glue Agon produced instead.
Same thing with garden soil.

### Your Proposal

It looks like these recipes are broken. Please check it. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Did you put circuit correctly? Plus check your machine's ghost circuit, which is in the lower right.

**Comment by CatsLeftEar** [comment]
This is a recipe conflict, 
![image](https://user-images.githubusercontent.com/67397297/149621077-4e395f2a-9667-41dd-897a-d7f739432d6b.png)
![image](https://user-images.githubusercontent.com/67397297/149621080-91991375-4710-4537-bfb4-1ca292262a08.png)

**Comment by miozune** [comment]
As a workaround, you can use following steps:
1. molten Glue -> Ball of Glue (Solidifier or Casting Table)
2. 2x Ball of Glue -> EMT Glue (Crafting)
3. Glue -> Refined Glue (Fluid Extractor)

Neither coremod nor MT script seem to add those recipes. I commented out https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/ba658528798ea5d5e9ed73a18a97e259a9b02366/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L2588-L2605 and issue remained.
