### ISSUE TITLE
Tank makes NEI blocks darker

### ISSUE THREAD

**Issue by T0mmen** [GTNewHorizons/GT-New-Horizons-Modpack#9418]
### Your GTNH Discord Username

Floof#7806

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

When I search "tank" in NEI I expect it to show tanks normally.

### The Reality

When I search the word "tank" in NEI the blocks displayed by NEI get shaded darker
![image](https://user-images.githubusercontent.com/70544861/148659379-ff7e362f-a157-4927-962e-4b3c8c4c560e.png)

### Your Proposal

If it's deemed a problem, then fix it, but it's not game-breaking by any means and just an oddity.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
It's one of these: 
<img width="231" alt="image" src="https://user-images.githubusercontent.com/533931/148660031-5eda70b4-7da3-4c21-93a2-1fda3bd35f0f.png">

and doesn't seem to be railcraft causing it. Haven't been able to narrow it down further (tank shows it, tank*r does not)

**Comment by Savallator** [comment]
Compressed chests in inventory also makes other stuff darker for me...

**Comment by bombcar** [comment]
> Compressed chests in inventory also makes other stuff darker for me...

That one is known, avataria addons is full of rendering bugs 😫

**Comment by Savallator** [comment]
And while we are talking about rendering bugs: Endertank with some fluids like Helium plasma makes the texture it stands on invisible, allowing Xray:
![2022-01-09_03 37 19](https://user-images.githubusercontent.com/10967188/148667025-9f94292a-7f86-47f7-9397-a64bf4384e36.png)

**Comment by bombcar** [comment]
Ender tank is also in the NEI list - could be the same problem hmmmk

**Comment by GTNH-Afx237v7** [comment]
The compressed chest visual bug has been fixed for a while, need to update avaritiaaddons.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/240
