### ISSUE TITLE
NAND Array Recipe not reflected in questbook

### ISSUE THREAD

**Issue by snidelycapon** [GTNewHorizons/GT-New-Horizons-Modpack#9420]
### Your GTNH Discord Username

Snidely#8630

### Your Pack Version

2.1.2.1

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Questbook for "Cheaper Simple Circuit" in HV tier has the player collect 32 Fine Tin Wire in the lead-up to crafting an NAND Array. 

![image](https://user-images.githubusercontent.com/669548/148661064-a2f03fd4-54a0-43be-9c0a-3f8463789332.png)

### The Reality

The NAND Array requires Fine Copper wire, not Fine Tin Wire. 

### Your Proposal

Change item required by questbook to Fine Copper Wire x32.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tyler799** [comment]
Actually, there's another issue here. This recipe makes 8 NAND chips from every 1 board. So this makes 128 NAND chips, not 64. Either the requirement should be raised to 128, or the recipe requirements should be cut in half.

**Comment by patrick-hill** [comment]
Came to report the same in build 2.1.2.1 (2021-12-19)

**Comment by TwoTailedFox** [comment]
Can report similar in 2.1.2.3qf. Quest calls for 8 Good Circuit Boards, 8 Simple SoC, 8 Red Alloy Bolts and 8 Fine Tin Wires. However, the crafting recipes for the NAND Chip Array call for either Fine Copper Wire or Fine Annealed Copper Wire.
