### ISSUE TITLE
Cryolite Dust recipe for Large Chemical Reactor not usable in HV

### ISSUE THREAD

**Issue by kehnneh** [GTNewHorizons/GT-New-Horizons-Modpack#9422]
### Your GTNH Discord Username

<º((((><#4757

### Your Pack Version

2.1.2.1

### Your Server

private server

### Your Expectation

Tried to craft cryolite dust in a large chemical reactor using the recipe
![LCR_cryolite_dust](https://user-images.githubusercontent.com/1490064/148665149-a39c67fc-468c-4c50-be56-5a440aa13a90.PNG)

LCR has sufficient salt water in an MV input hatch and has 128k hydrofluoric acid distributed between two MV input hatches (64k in each hatch), as well as the correct circuit (24) and sufficient aluminium hydroxide in the input bus. The LCR is connected using an HV energy input hatch.

LCR indicates that there are no structural or maintenance issues, and is enabled via the soft mallet.

### The Reality

The LCR does not craft the recipe.

### Your Proposal

The LCR should craft the recipe.

The recipe uses 16x the resources that are required by the regular chemical reactor, as shown here:
![cryolite_dust_regular_reactor](https://user-images.githubusercontent.com/1490064/148665268-fd79802b-b6ae-4341-9c0c-5a0407674dd5.PNG)

This means that two HV input hatches are required to create cryolite dust in a LCR. I suspect the issue is that the reactor is not combining the inputs from both hatches, which means the LCR recipe is gated behind the acquisition of an EV input hatch. Considering the regular chemical reactor's recipe does not require any EV components, gating the LCR recipe behind EV does not make sense.

To avoid the issue of combining inputs from multiple input hatches, the recipe ingredients and outputs should be reduced by a factor of 16 to make it similar to the LCR reactor, like other chemical reactor recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
There should be a second recipe with a smaller batch size
