### ISSUE TITLE
Yttriaite ore processing still has Tiny dust results.

### ISSUE THREAD

**Issue by mesandridge** [GTNewHorizons/GT-New-Horizons-Modpack#9423]
### Your GTNH Discord Username

Mac#8884

### Your Pack Version

2.1.2.0

### Your Server

Craftersland

### Type of Server

Don't know

### Your Expectation

I was looking for how to get a material and ran into this, was told on discord all tiny dusts need to be ticketed.

### The Reality

GT Ore processing shows tiny dust results

### Your Proposal

replace tiny dusts with full size dusts at 11.11% rate

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
Radioactive sludge dust centrifugation gives tinys as well.

**Comment by draknyte1** [comment]
GT++ recipes have yet to be overhauled.
