### ISSUE TITLE
Field Restriction Glass is a ZPM Tiered Glass ( but it doesn't say so )

### ISSUE THREAD

**Issue by MMunier** [GTNewHorizons/GT-New-Horizons-Modpack#9424]
### Your GTNH Discord Username

MMunier#1337

### Your Pack Version

2.1.2.1

### Your Server

private

### Your Expectation

We had Field Restiction Glass lying around in the Storage system and expected it to stay there.

### The Reality

It got accidentally used in some ZPM-Recipe since it counts as a ZPM-Tiered Glass (it has the `blockGlassZPM`-Tag).

### Your Proposal

I would completely strip that oredict entry completely and treat these blocks sparately.
However at least the tooltip should be updated with the ususal `Glass-Tier: ZPM`, so these surprises can be avoided.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
now the `blockGlassZPM` tag is removed. https://github.com/GTNewHorizons/GoodGenerator/commit/ba4ef7e1534e5c909b4d1b366503112010454ca1
