### ISSUE TITLE
Make the Interface blocking mode ignore programmed circuits

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9429]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Proposal

As title says, make the Interface blocking mode ignore programmed circuits.
When using some 1 or 2 tick multiblocks, enabling blocking mode avoids the shutdown of the multiblock, since AE is a lot faster at refilling items in the input bus.
Basically blocking mode is able to refill the input bus once a tick (if necessary) and avoid leaving the machine without items to process. This saves a lot of downtime of the multiblock, since it takes some seconds to restart after it stopped cause it was out of items to process.
Issue is, blocking mode, obviously, doesn't work when there's a programmed circuit into the input bus.
Only solution I found to keep it going was to use an additional storage (chest, item pipe, whatever) and add a conveyor to push items into the input bus.
Screenshot as an example
![javaw_VWSqMuC3Gz](https://user-images.githubusercontent.com/17811922/148696462-99aec5d5-80f1-483d-a7dd-b1663eec907c.png)

This adds unnecessary lag, since conveyors are pretty bad for TPS.
So, if the blocking mode could ignore the presence of programmed circuits, this workaround could be avoided.

### Your Goal

Avoid usage of conveyors on 1 or 2 ticks multiblock to avoid them shutting off.

### Your Vision

yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
But blocking mode does ignore circuits...

**Comment by Sphyix** [comment]
> But blocking mode does ignore circuits...

Uhh.. Idk why I never noticed it was ignoring circuits and assumed it didn't...
Nevermind then.
