### ISSUE TITLE
Dimensionally Transcendent Plasma Forge (Post MEBF)

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9431]
### Your GTNH Discord Username

Colen UwU

### Your Pack Version

2.1.2.1

### Your Proposal

This would be an extremely lategame furnace to provide smelting in excess of what a MEBF can handle. Its abilities would depend on the # of plasmas utilised at once as well as the EU/t provided.

I am modelling this on how GT++ multis currently operate, with a speed % and EU usage %. Firstly we present the calculations for the speed:

### The maths:

Two config variables, ```min_speed_eff=1``` and ```max_speed_eff=5```.

```speed_percentage = min_speed_eff + ((max_speed_eff - min_speed_eff) / total_plasma_eu) * used_plasma_eu```

Where ```total_plasma_eu``` is the sum of all craftable plasmas EU per 1L (I list these later). E.g. helium is 81,920EU and Americium 501,760EU. In total for GTNH 2.1.2.1 this value is 3,891,627.

The variable ```used_plasma_eu``` denotes the sum of all plasmas EU per 1L that are currently in available input hatches. This will vary setup to setup, if there is 0 plasma the furnace should not start at all. E.g. we have three hatches with Helium (81,920 EU), Americium (501,760 EU) and Iron (206,438 EU) plasmas. This would result in ```used_plasma_eu = 790118```

Now we move onto EU usage %. This is a tad complex mathematically but I have tried to write it out simply. The idea is that the user provides the furnace with 1/16th of the energy and the plasma provides the other 15/16th.

### An example case:

We create a furnace with Helium (81,920 EU), Americium (501,760 EU) and Iron (206,438 EU) plasmas as their input. We also provide the furnace with a UV energy hatch. This gives a speed of 181%. The plasma usage depends on the type of plasma, given Americium is more EU dense it is consumed much slower. The idea is the load is spread between all of the plasmas.

In our case we have 3 plasmas and 15 * UV EU to be supplied, this means each must provide 5A UV. Lets calculate it,

For Americium we know it has 501,760 EU per L, hence per tick to keep up it must consume ```(5 * UV) / 501,760 EU/L=5L```. Recall that ```UV = 2^19 EU```. To reduce lag and keep things more simple we multiply this value by 20 and make the multiblock consume this much plasma per second. I suggest we round up here to the nearest L (only after * 20).

Similarly we can do this for iron, ```(5 * UV) / 206,438 =12.69L/t```. Helium is equally as simple, ```(5 * UV) / 81,920 =32L/t```

### Parallel:

```max_parallel = total_plasmas_used * 128```

### Structure & Recipes:

I've not pinned down an exact structure yet but I have a few ideas including the following,

![image](https://user-images.githubusercontent.com/54497873/148701528-bb3315c9-4512-418a-aa3f-3570369ea18b.png)

so if this is a popular idea and gets implemented I'm happy to flesh this aspect out further. Same with the recipes, this multi would probably be the most endgame multi to date if added and should be tiered as such. Additionally it should ideally support laser hatches to keep it competitive with other options.

### Theoretical limits:

At it's absolute limits we would use all 16 available plasmas  and get a perfect 500% speed bonus. If we used the highest possible EU/t currently accepted without lasers in GTNH (2 UMV hatches = 1A UXV) we would yield the following usage case:

500m "real" EU/t used + 8B EU/t in plasmas used, that being:

Plasma Used | L/s required
-- | --
Helium | 122880
Boron | 89368
Calcium | 53427
Titanium | 51200
Oxygen | 76800
Zinc | 44482
Nitrogen | 78020
Niobium | 37350
Sulfur | 59078
Tin | 33059
Silver | 35610
Bismuth | 23631
Iron | 48762
Radon | 22342
Nickel | 47081
Americium | 20063

This would be capable of smelting 2048 neutronium in parallel taking a total of ```(16 * UXV / 2048) / (1 + max_speed_eff)= 13 ticks``` or 0.66 seconds.

### Balance considerations:

All these values are open to adjustment and can turn this furnace from worthless to god tier, so balancing shouldn't be too hard. The one thing I am wanting feedback on is the ratio of EU to plasma EU, as the total plasma used becomes extremely large otherwise at the theoretical limits. 

### Bonus:

To sweeten the deal I also propose this furnace require no gases for smelting purposes. Given the large resource investment you'd have to do to actually run this beast on a continuous basis this seems fair. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
I like the idea of using plasmas as fuel, though the structure looks weird.
 I'd say it should look more like a single chamber with many injection mechanisms whitch would have plasma input hatches on them.
 Also mixing all plasmas seems a bit excessive, maybe add traits to all of them (e.g. Americium 3% EU cost reduction or Radon +4% speed).
The structure would have predetermined amount of plasma hatches (maybe 6,12,18,24) and the bonuses from all of them would combine[or maybe even multiply] (even when the same plasma is in multiple hatches).
