### ISSUE TITLE
Slapping a machine with a hammer allows you to enable / disable "auto-input". But i cant seem to get such a feature to work?

### ISSUE THREAD

**Issue by samsonsin** [GTNewHorizons/GT-New-Horizons-Modpack#9433]
### Your GTNH Discord Username

samsonsin#6035

### Your Pack Version

2.1.2.0

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Id expect something to change, but i cant seem to get it to work at all. Users in discord said that such a feature doesnt exist

![image](https://user-images.githubusercontent.com/23201902/148718969-a787c415-7fee-490a-b657-b54806828d20.png)

### The Reality

See "Your Expectation"

### Your Proposal

Remove whatever this might be, as the pack seems to be balanced in such a way that said feature is unintentional. If it is intentional, make it work

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
![java_P0m7umysjN](https://user-images.githubusercontent.com/23512002/155524388-10a3387e-842d-4a38-9402-58676baf83d6.gif)
