### ISSUE TITLE
Calcium Proliferation 2.0

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#9436]
### Your Pack Version

2.1.2.1

### Your Proposal

![1](https://user-images.githubusercontent.com/22012110/148780112-bc9b1bdf-9499-48c7-b4bc-aba56d59edd0.png)
![2](https://user-images.githubusercontent.com/22012110/148780113-285bae35-22c1-4d3f-9e62-0551c194669c.png)
![3](https://user-images.githubusercontent.com/22012110/148780123-1e1fd344-3bb8-4162-af3c-577f49af5474.png)
Calcium from the Void

### Your Goal

fix this recipes

### Your Vision

2 hydrochloric acid + 5 calcite → 3 calcium chloride + carbon dioxide + water

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
Deleting the Calcite + HCl recipe would solve the problem, isn't CaCl2 a byproduct anyway? Is there a recipe that uses it?
Adding Ca+HCl recipe would be a good alternative if CaCl is indeed needed somewhere.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1062
