### ISSUE TITLE
Swapping the head of a Tier 0 Pickaxe breaks tool leveling.

### ISSUE THREAD

**Issue by FavoritoHJS** [GTNewHorizons/GT-New-Horizons-Modpack#9437]
### Your GTNH Discord Username

FavoritoHJS#5580

### Your Pack Version

2.1.2.0 RC1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

If you have a Tier 0 tool (such as the wooden Starter tools from a bonus chest or a tool with a Netherrack head) and swap its head, Mining Level XP works normally.

### The Reality

Mining Level XP doesn't work with that tool.

### Your Proposal

Make Mining XP work in this case.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can you check if this DOES work with a *non-quest reward* tool (built by hand)?

**Comment by FavoritoHJS** [comment]
Confirmed with a Netherrack Pickaxe Head

**Comment by chochem** [comment]
I am trying to reproduce or fix this but I dont even know where to start. Which quest gives a netherrack pickaxe head reward?

And what is 'wooden Starter tools from a bonus chest? we dont have anything like that as far as I am aware.

**Comment by FavoritoHJS** [comment]
> Which quest gives a netherrack pickaxe head reward?
None, that I know of, but back when I made this issue you could craft them.

> And what is 'wooden Starter tools from a bonus chest?
Those added by TiCon in the starter chest.

The important thing about the tool is that it has a mining level of Stone, and _only_ Stone.

**Comment by chochem** [comment]
so that above was just a misunderstanding? gottcha

**Comment by Ethryan** [comment]
Hmm, last time i tried, a Magical Wood Pickaxe head has the same problem.

**Comment by epic-coder-2976** [comment]
This issue persists. Tools that began with netherrack head cannot upgrade their mining level.
