### ISSUE TITLE
Make the interface terminal report coordinates

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9439]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.1

### Your Proposal

When using the interface pattern to look for a specific pattern, it would be very nice to somehow see the coordinates of the interface it is in. Like, if a recipe failed due recipe changes, not only do i need to modify the pattern (can be done with the interface terminal), but i also need to access the machine and remove the incorrect materials so they are not blocked. So when it is about stuff i set up long ago, it means searching through like 100 assemblers to see which one it is.

### Your Goal

Make it easy to locate where something is crafted

### Your Vision

It would help with debugging ME network problems and failed crafts.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
[Applied Energistics 2: Trousers Edition](https://github.com/PrototypeTrousers/Applied-Energistics-2) added this feature, we may backport it.
Relevant commit: https://github.com/PrototypeTrousers/Applied-Energistics-2/commit/22cf913708f1a92213be8fd47ec718db3790cdcf

**Comment by repo-alt** [comment]
> 

Looks like there are some other nice changes to the interface terminal that should be borrowed
