### ISSUE TITLE
Changing the existing Stargate mod to a newer one with More options

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#9440]
### Your GTNH Discord Username

Lord Peverell#3125

### Your Pack Version

2.1.2.1

### Mod Name

SGCraft Ultimate

### The Mod to Add

I've been following an offshot to a 1.7 Stargate mod that adds all 5 gate varients with this DHDs and they now added the transporter rings just recently. Was wondering the chances of this getting added over the version we have. 

https://www.planetminecraft.com/mod/sgcraft-ultimate-1-7-10/

Mod is a fork of this, license is MIT;
https://github.com/gcewing/SGCraft

### Your Reason

Cooler and different stargate options!

### Preliminary Investigation

Havent tried adding it and dont see it being an issue as we have something similar already

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by GTNH-Colen** [comment]
<img width="762" alt="Screenshot 2022-01-11 at 05 24 34" src="https://user-images.githubusercontent.com/54497873/148886115-1eabe74a-ecca-4b91-96da-f0ff22140807.png">

**Comment by Dream-Master** [comment]
funny we already forked the mod.
https://github.com/GTNewHorizons/SGCraft/

**Comment by bombcar** [comment]
I couldn't find the source for SG Ultimate

**Comment by GTNH-Colen** [comment]
Could we move the old mod into this mod so old stargates remain functional? Removing all stargates would be disastrous for the officials as we have a massive stargate network to every planet. Not to mention it would destroy the achievement that many have now accomplished.

**Comment by bombcar** [comment]
I believe SG ultimate is basically sg++ and so the original sg can be made to continue working, unless the underlying OC integration were completely gone.

It *would* however be amusing to grandfather in existing SGs and from then on require different "tiers" for different distances.

**Comment by Dream-Master** [comment]
we dont know if the mod works and can easy replaced. More tests are needed. And maybe let both mods in that old stargates can transfered.

**Comment by bombcar** [comment]
I can't find the source even after browsing all the forks of the upstream mod. If we can't find source this isn't going to go very far.

**Comment by glowredman** [comment]
If I understand the [Planet Minecraft page](https://www.planetminecraft.com/mod/sgcraft-ultimate-1-7-10/) correctly, it is a modified version of the mod by Greg Ewing (we use a modifed version aswell), it even has the same [mcmod.info](https://github.com/GTNewHorizons/SGCraft/blob/mc1.7/src/resources/mcmod.info) file:
```json
[
{
  "modid": "SGCraft",
  "name": "Greg's SG Craft",
  "description": "SG-1 stargates and other stuff.",
  "version": "2.46.2-mc1.7.10",
  "mcversion": "1.7.10",
  "url": "http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/SGCraft/",
  "updateUrl": "",
  "authors": ["Greg Ewing"],
  "credits": "",
  "logoFile": "",
  "screenshots": [],
  "dependencies": []
}
]
```
The devs seem to be active on Planet Minecraft, we could ask them to upload on GH and provide a license. In the comments they also stated where the got the assets from (we should take care that the use of them is legal too if we want to use it).

**Comment by MrJakobLaich** [comment]
I want this!
Gimme stargate!
