### ISSUE TITLE
Soul brazier change prevents server start

### ISSUE THREAD

**Issue by ahmetsad** [GTNewHorizons/GT-New-Horizons-Modpack#9441]
### Your GTNH Discord Username

Ahmetsa#1741

### Your Pack Version

2.1.2.1 with new thaumic exploration

### Your Server

SP

### Type of Server

Vanilla Forge

### Your Actions

https://github.com/GTNewHorizons/Thaumic_Exploration/pull/9 installed latest thaumic exploration launched server. server logs stop doesn't let player join.

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7845168/fml-server-latest.log)
file too big for pastebin

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alastors** [comment]
@draknyte1
