### ISSUE TITLE
Make the Ice Solifier actually produce Ice Instead of snowballs, it literally has ice in the name

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9444]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.1

### Your Proposal

Make it produce ice, why the hell does it make snowballs? It is literally called the ICE solifer (LMFAO TYPOS BE WACK)

Seriously though, it should make ice, snowballs are essentially useless.

### Your Goal

Make this thing solify ice

### Your Vision

I WANT SOLIFIED ICE

Yes I am making typos on purpose

<img width="473" alt="Screen Shot 2022-01-11 at 10 56 04 AM" src="https://user-images.githubusercontent.com/78517796/148986831-119423a1-72c6-4eed-ad93-f6d4691ebeeb.png">

it also needs a name change
 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
So I can do this - or I could try *adding* and ice machine equivalent. Not sure if anyone cares about snowballs at all

**Comment by Cata-bre** [comment]
I don't think it is worth adding another Thaumic extruder, unless it is unlocked with the same research. Is it easy/feasible to be able to switch the output by shift+right+clicking or wrenching the Thaumic Ice Solidifier?

**Comment by bombcar** [comment]
![image](https://user-images.githubusercontent.com/533931/149375318-a0ed1121-767a-4322-8c43-84cb9288aaaa.png)

I got both there, but the ice one makes ice once then stops (until you empty the container) and doesn't render fully. Fun.

**Comment by Cata-bre** [comment]
I'm pretty code ignorant with respect to Minecraft, so I'm not much use. :/

If you go with two machines, you could call the snow producer "Thaumic Snow Baller" and the ice producer "Thaumic Ice Solidifier."

**Comment by bombcar** [comment]
Way ahead of you on that one!

![image](https://user-images.githubusercontent.com/533931/149376731-cd6d8fad-a2ec-4908-bc3a-a6b1973957ee.png)

Figured out why it stops, should have copied the cobblegen instead:

Next to figure out why it's skipping a render step.

**Comment by Cata-bre** [comment]
Something something great minds

**Comment by YannickMG** [comment]
Something that just dumps items on the ground feels a bit like an antipattern, compared to dumping snowball items.

Completely different direction suggestion: Apply the Ice Solidifier to a water surface such as a lake and watch it freeze the whole thing, 1 block at a time.

**Comment by YannickMG** [comment]
You could even make it mildly useful by making it follow flowing water up to it's source and freeze that too. That could make for some fun interactions.

**Comment by bombcar** [comment]
That would require someone who can do more than cut and paste code 🍡
