### ISSUE TITLE
Missing localization on Infinite Oil/Gas/Fluid Drilling Rig achievement

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9445]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

![javaw_6qlqMTXAL8](https://user-images.githubusercontent.com/17811922/148990891-6984f65e-1ec3-4816-b325-a3611c82792c.png)

### The Reality

+

### Your Proposal

+

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by combusterf** [comment]
Ran into this as well, should be a straightforward fix.
