### ISSUE TITLE
TCetieE world gen causes too much light updates and lag the server to death when exploring

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9446]
![image](https://user-images.githubusercontent.com/12850933/148991386-fcca721f-7b9c-4809-b891-37b70d198d4c.png)
![image](https://user-images.githubusercontent.com/12850933/148991400-d3718c00-0191-4f9d-be97-fa7e426e78ff.png)

**Comment by bombcar** [comment]
setBlock calls a lighting update - perhaps there is a setBlockFast somewhere in the code we could use instead?
