### ISSUE TITLE
Make a lategame farm that does not actually plants/harvests

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9449]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.1

### Your Proposal

Inspired from discussion in the Discord, how about implementing a lategame farm that does not actually needs the crops to grow.
You would place it down, plant crops around, supply power and then it would generate the drops according to the number of fully grown crops in range and their speed bonus. Instead of WA'ing the crops, the farm block itself could scale it's output with power. That way more drops would not need more TE's updating, which could help a lot with lag-free ressource generation. This is just a rought idea, would need some balancing of course. I would place this at UV Tier maybe.

### Your Goal

Add an endgame lag free farm.

### Your Vision

It could decrease WA spam for crops and massively increase TPS. A WA on the crop has actually double tps impact - the crop grows faster, and the harvest needs to be done faster as well.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Conceptually similar to the GT++ Tree Spawner Multiblock?

**Comment by Savallator** [comment]
Yes, kind of, just that my suggestion would still have the crops in world. Think of it as kind of a multi block where grown crops are part of the multi and dictate what and how fast it outputs, but without harvesting them (so WA'ing them is useless), and the WA feature already included into it (scaling drops with power).

**Comment by bombcar** [comment]
What about a "greenhouse" multiblock similar to the cleanroom, but made of glass of the appropriate tier and the plants live inside it?

**Comment by Savallator** [comment]
Could be... this is not really urgent for me personally, i don't even use crops. I just had the idea on this mechanic and wanted to share it for discussion. Greenhouse would look really nice though.

**Comment by bombcar** [comment]
I wonder if WA usage shows up anywhere - but something like a high-tier programmable greenhouse could even tie into more quantum computer usage, for those who skipped crops entirely and want to throw computing power at it.

**Comment by Savallator** [comment]
WA usage is hard to profile because it is not only the actuall WA using time, but the entity it accelerates. But a x256 WA can not be that good on performance, especially when having multiple. Maybe someone has some insight on it?

**Comment by boubou19** [comment]
first why do you need a WA for? it can only do 5 crops per WA (6 if you use the microwave energy transmitters). And i have honestly no idea why you need to spam it.

But i'd like to have a multiblock like the cleanroom but with BW/reinforced glass ceiling that works only if it sees directly the sun, and would turbo boost the crops in it.

**Comment by 0lafe** [comment]
They can be a lot more useful in non TE mode for non IC2 crops. Pretty large range, and goes a lot faster than other crop speed options

**Comment by bombcar** [comment]
> But i'd like to have a multiblock like the cleanroom but with BW/reinforced glass ceiling that works only if it sees directly the sun, and would turbo boost the crops in it.

I wonder if structure lib can be made to allow a greenhouse to form "as long as there is a glass block above and can see sky" so that you wouldn't have to specify the roof exactly, and people could make them curved, architecture, etc.

**Comment by Steelux8** [comment]
> first why do you need a WA for? it can only do 5 crops per WA (6 if you use the microwave energy transmitters). And i have honestly no idea why you need to spam it.

Crops in lategame without WAs are really slow for most purposes, and this inefficiency is the main reason why bees are more used in late game. A multi that accelerated crop output speed without accelerating tick speed would reduce lag, make crops more usable later in progression and avoid situations like Sampsa's multifarm stack crashing other people's games when they got the world download.

**Comment by leagris** [comment]
Late game crop growth could be a multi without even crop-stick. Just an off-ground aeroponics closed box simulating environments with power and supply of nutriments, robotic harvest. No need to have it seen from outside or a rendering of a single crop-stick instance behind a glass window and an incorporated light-source.

Something looking like this: 
![image](https://user-images.githubusercontent.com/1111474/149021127-30e57128-0e1b-4cf8-b217-27d3e6fed183.png)

**Comment by Steelux8** [comment]
That looks similar to what I think Alkalus was going to make, but she's not going to develop much anymore from what she said of having started working again yesterday.
