### ISSUE TITLE
Implement a whitelist filter for Void miners

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9450]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.1

### Your Proposal

At later Tiers, void miner outputs are like 90% useless. Like digging for Infinity Catalyst on Vega B will generate 95% crap. It would be nice to have some sort of filter/card/whatever to add to the void miner to just not generate the trash ores, like a whitelist of what i actually want. This should not change the chances, if it would generate something not on the filter, just output nothing for that cycle.

This is how i solved it right now, 2 item filters, one inverted into thrash can and one to processing, but i think it would be better to just not generate the ore at all.
![2022-01-11_19 16 30](https://user-images.githubusercontent.com/10967188/148998950-b8aaa946-dc71-4d25-baa8-0a491e9f01ce.png)

### Your Goal

Make Void miners more performant.

### Your Vision

It would help with getting just the ressources i want.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
i'd say make it compare the ores that are inside an input bus. that shouldn't be too hard to implement

**Comment by bombcar** [comment]
We could do this "simply" by having you put an example of the ore(s) you want in the void miner itself, but I think it would be perhaps more interesting if you had to:

1. Somehow scan the world to get a "raw data stick" of what is there (siesmic? electric prospector?)
2. Process this data stick with the quantum computer (appropriate tier) so you know can see all the ores
3. Select the ores you want
4. Load stick into the void miner.

Once you have step 3 the data stick should be duplicatable.

**Comment by Savallator** [comment]
> i'd say make it compare the ores that are inside an input bus. that shouldn't be too hard to implement

That would be an nice and easy solution, although i can see bombcars way to be usefull...

Maybe make it so that it works 3 ways:
1. like it is now
2. with an input bus and filters or
3. With the data stick, and to compensate for the effort it gets a small (like 50% or something to not make it OP) bonus to actually generating the ores you want. Then make the research recipe actually challenging, we need more high-calculation stuff anyways

**Comment by riking** [comment]
Reading an input bus filters sounds like mega jank to me.

The data stick approach could have tiering for the number of different ores you're allowed to filter in/out

**Comment by Savallator** [comment]
> Reading an input bus filters sounds like mega jank to me.

Why? I think it would be a nice approach?

**Comment by boubou19** [comment]
> Reading an input bus filters sounds like mega jank to me.
> 
> The data stick approach could have tiering for the number of different ores you're allowed to filter in/out

datastick approach sounds more cool, but the voidminers are already tiered by the energy hatch. I don't see the point to tier them more?

**Comment by Sphyix** [comment]
I don't think I'd want to use that if it's this complicated. It's easier to just trash the ores that I don't need when a drawer is full, like a void upgrade. This way I have storage of it aswell...

**Comment by Savallator** [comment]
The point of it is to not generate them to reduce lag when setting up e.g.
8 oganesson boosted vm on vegab just for one single ore. This is way out of
scope for drawers... I mean who even uses them at that stage? I have 10
million iron already, I certainly don't need additional 14 stacks owr
second of it... and if you feel like you don't need it just don't use it...

Sphyix ***@***.***> schrieb am Di., 11. Jan. 2022, 19:58:

**Comment by boubou19** [comment]
> The point of it is to not generate them to reduce lag when setting up e.g.
8 oganesson boosted vm on vegab just for one single ore

do you actually have lag profiling to support that claim?

**Comment by Savallator** [comment]
I have lag profiling to clearly show that processing >1 stack of ores per second, or even importing them into AE is causing troubles.
I switched to having Trashcans directly at the miners, like in the screen, and that is fine, i just think that there could be an easier solution.

**Comment by boubou19** [comment]
how do you import them into AE? me output buses or normal interface/conveyor?
Anyways if you have profiling reports, don't hesitate to share them, it's super helpful to tackle the lag sources in code

**Comment by Savallator** [comment]
I basically have Conveyor into Quantium Pipe into interfaces, and then a storage bus on a super buffer, and it had horrible lag as soon as it had actually high throughput (like 1 stack/tick).
I don't have the profiling data any more, but the function that took the time was the updating of the interface.
