### ISSUE TITLE
Remove LCR rocket fuels

### ISSUE THREAD

**Issue by draknyte1** [GTNewHorizons/GT-New-Horizons-Modpack#9451]
### Your GTNH Discord Username

Alkalus

### Your Pack Version

Chemical Plant

### Your Proposal

Remove lcr rocket fuels which were added to replace harder GT++ rocket fuels. 

### Your Goal

Remove easier rocket fuels. 

### Your Vision

Hard pack should be hard. 
space fuel should be hard. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
LCR rocket fuels are more complex to make. chem plant fuels are more expensive to make (due to chemplant). Neither is easier than the other.

**Comment by draknyte1** [comment]
> LCR rocket fuels are more complex to make. chem plant fuels are more expensive to make (due to chemplant). Neither is easier than the other.

LCR fuels are based on the exact same fuels as mine. CBD is easy. T3/4 fuel is basically the same production method. LCR fuels aren’t accurate, GT++ ones are moreso.

**Comment by Savallator** [comment]
I disagree on them being too easy... All you see here is just for one Rocket fuel:
![2022-01-11_22 47 11](https://user-images.githubusercontent.com/10967188/149026588-a8f6843a-b9e9-480c-8a0b-cb0f30f288db.png)
Looks quite complex to me...

**Comment by bombcar** [comment]
LCR too OP and boring, but I don't know if this is the proper solution long-term.

Rather, I'd like to see more of the 24 recipes *NOT* be in the already OP LCR.

**Comment by draknyte1** [comment]
LCR cheap (free) and boring.

**Comment by boubou19** [comment]
LCR are too used in the pack. Having arrays of them is boring: always the same thing: you compute the perfect OCs needed, you plug the right energy hatch, you plug the inputs on the LCRs and move on. If the steps are already perfectly balanced difficulty wise in my opinion, adding some multiblock diversity is good. I vote for the removal of the rocket fuel lcr recipes as well.

**Comment by Alastors** [comment]
I like the LCR recipes, even if I don't use them, why should we regress to a change to get away from something that was already ass? 

I will say, while Im usually all for realism in the pack, I would prefer we don't regress back to obsessive chemplant usage myself.

Why don't we just make a new multiblock if thats the problem?

**Comment by Alastors** [comment]
The chemplant isn't exactly multiblock diversity

**Comment by bombcar** [comment]
Negative Kelvin should now be gone, report any you find

**Comment by redmage17** [comment]
Wasn't GT++ getting removed?

**Comment by Dream-Master** [comment]
no no plans so far

**Comment by Elisis** [comment]
Can we not humour Alk's hate for anything that's not her mod? Chem plant isn't really more of an interesting mechanic in its own right, and is generally an abject horror to deal with. We have to remember that there are still people who want to avoid the use of GT++ as well.

**Comment by Savallator** [comment]
But to be fair, the GT++ multis are way more interesting than just blue Cubes all the time. Also, what is the horror with the chemplant? But imho the rocket fuel just needs interesting recipes, and it could be in a chem plant, but also use other machines (Oil cracker, mixer, fluid heater, distillation etc...)

**Comment by mitchej123** [comment]
> We have to remember that there are still people who want to avoid the use of GT++ as well.

I don't think we should balance the pack around people not liking mods.  Especially now that it's OSS

**Comment by Elisis** [comment]
> But to be fair, the GT++ multis are way more interesting than just blue Cubes all the time.
Uh, GT++ fuels are literally just replacing LCR with Chem Plant

**Comment by GTNH-Colen** [comment]
I agree LCR recipes for the fuels should go, this provides a much needed diversity to the current LCR spam.

**Comment by Savallator** [comment]
Hate to quote myself, but:

> But imho the rocket fuel just needs interesting recipes, and it could be in a chem plant, but also use other machines (Oil cracker, mixer, fluid heater, distillation etc...)

**Comment by mitchej123** [comment]
And it's not a perfect over clock and not as easily upgradable.  The LCR is
boring.

**Comment by Elisis** [comment]
> The LCR is boring.

So make the fuels require more diversity in their multis?

**Comment by GTNH-Colen** [comment]
> > The LCR is boring.
> 
> So make the fuels require more diversity in their multis?

Which GT++ accomplishes here.

**Comment by Elisis** [comment]
> > > The LCR is boring.
> > 
> > 
> > So make the fuels require more diversity in their multis?
> 
> Which GT++ accomplishes here.

Again, GT++ is literally just replacing LCR with chem plant. What's diverse about that?

**Comment by GTNH-Colen** [comment]
> > > > The LCR is boring.
> > > 
> > > 
> > > So make the fuels require more diversity in their multis?
> > 
> > 
> > Which GT++ accomplishes here.
> 
> Again, GT++ is literally just replacing LCR with chem plant. What's diverse about that?

You edited your message after I responded to add the second part but every other chain uses LCRs to death. This provides a chain which uses a non cuboid multi and adds diversity to the look of a base.

**Comment by Elisis** [comment]
> adds diversity to the look of a base.

This is completely subjective and so is supported by the optioned fuel types.

**Comment by Savallator** [comment]
Objectively, having two different multis is more diverse than just one LCR everywhere.

**Comment by bombcar** [comment]
The oil cracker recently got majorly buffed. A non gt++ rocket fuel recipe that ends in the same rp-1 but goes through various machines would be interesting. A long chemical reactor isn’t. Not really.

**Comment by GTNH-Colen** [comment]
LCR = LCR
LCR + Chem plant != LCR

*Diversity*

**Comment by Savallator** [comment]
I mean, that argument is just like saying "I don't like the Quantum Computer, and the Uncertainty Resolver is buggy anyways, please make it optional and add scanner recipes for everything"

**Comment by yukieiji** [comment]
My personal opinion is also in favor of removing the LCR recipe for rocket fuel.
I think we should take this opportunity to stop using CR(LCR) for chemical processing of anything(should be more variations, such as thermochemical reactors, like in GT6)

**Comment by redmage17** [comment]
Outside the LCR is boring and OP argument. I am not a fan of the over convoluted recipes created by Bot that just takes up chunk space. However from my crackpot view point it's easier to automate since it doesn't require a massive multiblock at several steps.

**Comment by Steelux8** [comment]
The chem plant is incredibly expensive as a multiblock compared to the LCR, but aside from that I agree with this change. The chem plant is much more versatile and could very much be a dedicated multi for several processing chains, in order to move away from the LCR spam.
