### ISSUE TITLE
Tinker´s construct modifier ,,modifiable,,

### ISSUE THREAD

**Issue by Slendooo** [GTNewHorizons/GT-New-Horizons-Modpack#9452]
### Your GTNH Discord Username

Slendooo

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I tried to replace parts on tinkers construct tools/weapons with magical wood parts and i was hoping that i would get a modifier slots.

### The Reality

I replaced parts but i didnt get the modifier slots (the modifiable modifier was on weapons/tools). Not even that i didnt get the modifier slots it also consumed one modifier slot from my weapon (it isnt possible to replace part with magical wood part without having one modifier slot already on weapon/tool). 

You can craft weapons/tools with magical wood and you will get your modifier slots but if you replace part you wont get your modfier slot.

And if you craft full magical wood weapon/tool and get 8 modifier slots as you should you can then replace all magical wood parts from weapon/tool  by different ones and the weapon/tool will still keep those 8 modifier slots even though there is 0 magical wood parts  right now.

### Your Proposal

Get modifier slots when replacing parts for magical wood parts.
Not being able to have 8 free modifier slots on weapon/tool while i replace all parts that gave those 8 modifier slots.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ahmetsad** [comment]
this will allow you to get modifiers every time you replace parts. you can continuosly change parts and get infinite modifiers. modifier should only added when you first craft the tool.

**Comment by Slendooo** [comment]
What i have in mind is that it should work like paper parts, you take paper part away you also take away the modifier slot and if you have already used the modifier slot paper part gave you, you cant replace it until you add another new modifier slot to your weapon/tool. 

Right now when you craft full magical wood weapons/tools and then replace all parts on them for example for steel parts you will have steel weapon/tool with 8 free modifier slots just bcs it didnt delete the modifier slots when you took magical wood parts away.

**Comment by jesuseduardo90** [comment]
I actually found that to, yes you craft your magical wood pick with 8 modifiers and then you can replace them and still have the 8 free modifiers.

You can also replace it with thaumium or paper and get more modifiers, i craft an unbreakcable pickaxe with 2 thaumium 3 obsidian and still have 3 modifiers to spare with 0 xp.

I think that unbalance idunno.

**Comment by jesuseduardo90** [comment]
In summary:
crafting with magical wood give permanent modifider, and crafting a complete tool with that gives 8 perm modifiers.

Is that intended in the pack?
