### ISSUE TITLE
Forestry multifarms are spamming getBlock calls under the hood

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9453]
https://github.com/GTNewHorizons/ForestryMC/blob/master/src/main/java/forestry/farming/logic/FarmLogicOrchard.java#L170-L211

for exemple, `VectUtil.isAirBlock`, `VectUtil.isWoodBlock` and `isBlockTraversable` are all calling `getBlock` under the hood, and i think some caching of the block being returned by `getBlock` and doing manual check instead of using those convenient methods would improve a bit the lag from the forestry farms.

i didn't bother to check other places where those are used tho.

**Comment by leagris** [comment]
Caching getBlock might turn very bad when dealing with grown trees and leaf decay.

**Comment by bombcar** [comment]
The new GT++ farming blocks have done wonders for sampsa's tictime perhaps some of the code could be applied to forestry as well ....

**Comment by YannickMG** [comment]
So not only in the same tick, but also always guaranteed to be either before or after any leaf/log/crop updates that could change the result of getBlock during that same tick?

**Comment by Glease** [comment]
CPU cache is supposed to do the caching for you. Not sure if you would get any improvement. This is a memory bound task. It would probably have gone better if it batches its getBlock calls instead, though I don't quite have a good idea on how.

**Comment by Savallator** [comment]
The point is that this whole "Iterate over all the crops" is a huge overhead and not needed once per tick. This whole function performs very badly. The point of it is that it iterates over all blocks that are connected to the farm, to check for "connected crops" (like fruits on trees), and does that for every farm block. This is a side effect of it being an "orchard" mode that is also able to handle fruit trees and stuff. I am not even sure if anyone ever used this mode for fruit, but maybe we schould split them somehow, because 99% of applications just use them for crops and the check is not needed at all, because the initial "crop" block is also the block that should get harvested. Anyways, i have worked on some caching (and only iterating the blocks every second), as soon as i fixed the last bugs i will make a PR.

**Comment by leagris** [comment]
> The point is that this whole "Iterate over all the crops" is a huge overhead and not needed once per tick. This whole function performs very badly. The point of it is that it iterates over all blocks that are connected to the farm, to check for "connected crops" (like fruits on trees), and does that for every farm block. This is a side effect of it being an "orchard" mode that is also able to handle fruit trees and stuff. I am not even sure if anyone ever used this mode for fruit, but maybe we schould split them somehow, because 99% of applications just use them for crops and the check is not needed at all, because the initial "crop" block is also the block that should get harvested. Anyways, i have worked on some caching (and only iterating the blocks every second), as soon as i fixed the last bugs i will make a PR.

Do not make a generalisation as ppl use it for crops. Now crops has its own mode that is not Orchard but a specific crop mode.

I have used the orchard mode extensively to harvest fruit trees like forestry Papayas, extra-trees grapefruit that gives high fuit juice amount, and forestry plum that gives high mulch amount, all very suitable for the production of forestry biomass and ethanol.

**Comment by Savallator** [comment]
Crops is literally just orchard mode renamed and with other tubes:

```
public class FarmLogicIC2Crops extends FarmLogicOrchard {
    public FarmLogicIC2Crops(IFarmHousing housing) {
        super(housing);
        this.farmables = Farmables.farmables.get(FarmableReference.IC2Crops.get());
    }
}
```

And i mean, would you really have that much of a problem if orchard mode was split up to "true orchard" and general crops? I did not propose to remvoe orchard, but to make it less of a "catch-all" mode.

**Comment by Savallator** [comment]
> So not only in the same tick, but also always guaranteed to be either before or after any leaf/log/crop updates that could change the result of getBlock during that same tick?

Yes, of course. It is just a few lines apart in code, in the same function.

**Comment by Ngar1** [comment]
If changes planed, please look if integration of Botany flowers would be possible [#8618](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8618)
It would be very nice ;-)
