### ISSUE TITLE
Expanding the display capabilities of AE2 terminals

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9454]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Proposal

It would be nice to add the ability to customize the display of items in the AE2 terminal by category, such as tools, building materials, ores, food, alchemical ingredients, and the like

### Your Goal

This will increase the usability of AE2 terminals

### Your Vision

This feature will be useful both in the early stages of using AE2 and in the later stages of the game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
Viewcells exist. They do support oredictionary cards iirc.

**Comment by Eldrinn-Elantey** [comment]
> Viewcells exist. They do support oredictionary cards iirc.

That is, with their help, you can configure the display of pure ore or food in the interface without long settings of these cards?

**Comment by repo-alt** [comment]
Well, it would be nice to have some block to encode oredictionary filter card, like GT Type filter e.g., but with an ability to combine filters, because textual repersentation of a filter is ugly. But it would take quite some work and I don't have much time, maybe someone will be interested.

**Comment by Eldrinn-Elantey** [comment]
Apparently no one is interested in this idea
