### ISSUE TITLE
Adding a B3M mod

### ISSUE THREAD

**Issue by kellixon** [GTNewHorizons/GT-New-Horizons-Modpack#9455]
### Your Pack Version

2.1.2.1

### Mod Name

B3M (https://www.curseforge.com/minecraft/mc-mods/time-speed-mod)

### The Mod to Add

The mod increases the duration of the day and night. The nights will get darker (you can remove HardcoreDarkness from the modpack). 

### Your Reason

No need to sleep every 10 minutes. By default, you can leave the value "TimeMultiplier: 1" in the configuration file. You can also remove the display of the clock "ShowClock: no", leave the rest of the settings as default. Everyone who wants to increase the duration of the day and night at their discretion (I always set the value 4-6, this is enough).

### Preliminary Investigation

When adding a mod to an assembly, there is no change in the length of the day and night. Something is preventing it from working normally.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by bombcar** [comment]
Unfortunately this one is ARR but perhaps the desired effect can be obtained in some other way. Galacticraft already has alternate time cycles on various planets

**Comment by Dream-Master** [comment]
we dont add ARR mods
