### ISSUE TITLE
Add User-Friendly Response if Long Distance Pipe is Too Short

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#9456]
### Your GTNH Discord Username

TimeConqueror#5294

### Your Pack Version

2.1.2.1

### Your Proposal

Notify the player if Long Distance Pipe is Too Short
Also add the info about it in Scanner.

Upd:
1) Add unequivocal tooltip about how it checks its distance (`longer than 64 blocks` is not unequivocal).
2) Add the notification so player could understance the pipe is too short

### Your Goal

Player will know why it doesn't work

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Perhaps we could generalize this to a "other end" part of the tooltip: either red "too close", yellow "cannot find" blue/green "distance" or something

**Comment by dimondmine2** [comment]
Maybe just have flow rate of long distance fluid pipe inversely related to distance, so the shorter the pipe, the lower the flow. That way we don't need to have multiple redundant fluid teleporting blocks

**Comment by Dream-Master** [comment]
the 64 min pipe distance isn't bad at all. if you ask me this number must be bigger. Add a shorter long distance pipe is useless and i don't add.

**Comment by TimeConqueror** [comment]
Dream, you misinterpret the aim of adding these pipes. The main aim was to make the stuff transfering less cpu heavy. So we definitely need a version for all distances.
The shorter version could have another craft (but it should still be easier to get than enderio pipes (because the second one is more cpu heavy and more comfortable to use).

**Comment by Dream-Master** [comment]
I think not that i missunderstand it. The long distance pipe are very cheap and should be used for long distances. A new version of pipes maybe make people more confused. But sure if there are some ideas go ahead and make a pr.

**Comment by dimondmine2** [comment]
I agree with dream that the 64 distance is too small. If you make a single long distance fluid pipe (LDFP), and it's flow rate is inversely proportional to the latitude and longitude of the start and end pipe, you can nullify the case for short distance fluid pipes at the same time that you nerf using the LDFP for short ranges. Plus, by using only latitude and longitude to calculate distance (not taking vertical into account) you prevent people from just building fluid pipe straight into the air to get extra distance.

**Comment by bombcar** [comment]
Ldfp does take vertical distance into account (at a discount) - a 96 distance straight up works

**Comment by dimondmine2** [comment]
Part of my point is that it shouldn't, to prevent cheesing in by doing exactly what you mentioned.

**Comment by Glease** [comment]
vertical offset has a 50% discount, so 96 does not work. You need to cover 128 blocks vertically (most common for ic2 crop farms) so I sort of allowed this. It's probably high enough that a long distance pipeline make sense, but whatever, you might have different opinions.

**Comment by bombcar** [comment]
@mitchej123 wanted a bump

**Comment by mitchej123** [comment]
This is meant for long distance fluid transfers without needing to load chunks.  It's a lag reducer for servers, if you're only going 16 blocks - use normal pipes.
