### ISSUE TITLE
jcenter is down and/or going away

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9457]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.2dev

### Your Server

sp

### Type of Server

Single Player

### Your Actions

All GitHub "tests" are now failing on our repositories/PRs:

```
* What went wrong:
A problem occurred configuring root project 'GT5-Unofficial'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.eclipse.jdt:org.eclipse.jdt.core:3.10.0+.
     Required by:
         project : > com.github.GTNewHorizons:ForgeGradle:1.2.5
      > Failed to list versions for org.eclipse.jdt:org.eclipse.jdt.core.
         > Unable to load Maven meta-data from https://plugins.gradle.org/m2/org/eclipse/jdt/org.eclipse.jdt.core/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/eclipse/jdt/org.eclipse.jdt.core/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
   > Could not resolve org.eclipse.jdt:org.eclipse.jdt.core:3.10.0.v20131029-1755.
     Required by:
         project : > com.github.GTNewHorizons:ForgeGradle:1.2.5 > net.minecraftforge.srg2source:Srg2Source:3.2-SNAPSHOT:20150109.190932-47
      > Skipped due to earlier error
```

### Crash Report

As above. TimeConqueror reported that SizeableShrimp found a workaround (but for which version of Forge was unclear):

```
Ok so I have found a workaround:
1) Add systemProp.org.gradle.internal.plugins.portal.url.override=https://repo.maven.apache.org/maven2/ to gradle.properties
This will redirect checks to the plugin portal to instead check maven central.

Optionally, if you are using plugins from the Plugin Portal:
In the plugins {} block:
You need to add this to the TOP of settings.gradle (or make it if it doesn't exist):
pluginManagement {
    repositories {
        maven {
            url = 'https://plugins.gradle.org/m2'
            content {
                includeGroup 'com.github.johnrengelman.shadow'
            }
        }
    }
}

Then you add every plugin ID you're using in includeGroup (demo here is shadow plugin)

Otherwise, you can do the same thing in buildscript { repositories {} } if you're using classpath to get a gradle plugin from the plugin portal
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
After some testing, I've determined there are at least three issues.

1. SpecialSource can't be found (but it is available on GitHub here: https://github.com/md-5/SpecialSource with an OSS license ) - all that was necessary here is use Jitpack later
2. Srg2Source uses a version of org.eclipse.jdt that isn't available. It's available in source here: https://github.com/MinecraftForge/Srg2Source and I forked the [95b5927](https://github.com/MinecraftForge/Srg2Source/tree/95b5927e6b6aadfc5e981db6ae5a72fc500e42fc) commit that corresponds to what we use. At that time it was BSD 3.0 Clause, now it is LGPL
3. ForgeGradle needs the above to run

I forked the listed above, and modified the build scripts until they ran.  It is *likely* that the only changes needed are to particular versions, but I updated lots of libraries to see what would happen, and my notes are:

1. Line 515 in MergeJarsTask.java in ForgeGradle doesn't like upgrading guava unless you change it to MoreObjects
2. Srg2Source was trying to use gradle 1.8 which didn't work, but replacing the gradle directory with our 6.9.1 worked
2. The main fix for Srg2Source is likely changing `org.eclipse.jdt:org.eclipse.jdt.core:3.10.0.v20131029-1755` to `org.eclipse.jdt:org.eclipse.jdt.core:3.18+` but going higher than 3.18 apparently doesn't work because those are for Java 11.
3. Srg2Source javadoc was broke so I just commented it out.

**Comment by bombcar** [comment]
With the above done (see https://github.com/bombcar/Srg2Source/pull/1 for the changes to Srg2Source) and https://github.com/GTNewHorizons/ForgeGradle/compare/master...bombcar:master for ForgeGradle it was able to run and build a complete copy of GT5u on a fresh new system never used (with the build script pointing to `com.github.bombcar:ForgeGradle:master-SNAPSHOT`

**Comment by glowredman** [comment]
I think we can close this as long as Jcenter is up
