### ISSUE TITLE
Add Antique Atlas insted of Journey map

### ISSUE THREAD

**Issue by Kairi-lol** [GTNewHorizons/GT-New-Horizons-Modpack#946]
Great looking mod that adds a great map.

https://mods.curse.com/mc-mods/minecraft/227795-antique-atlas

**Comment by Dream-Master** [comment]
Already suggested but this mod will lag the server/client as hell so far I remember. @Mylez look inside the closed issues.

**Comment by Mylezz** [comment]
Ahh
