### ISSUE TITLE
Change the eu requirement, or oil production of the soulsand to oil recipe.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9462]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.1

### Your Proposal

Currently the soul sand to oil recipe is an extremely net negative source of oil, it's fine for if you just need oil, but if you are trying to make oil out of soulsand, you actually lose a lot of energy compared to what you gain!

Someone did a calculation, it wasn't me so I can't report on this exact accuracy, I'll get back to you later when I have time to go through every step but, in their model, it was showing that with the conversion all the way to cetane-diesel would only net a max +5000 eu at all, not just compared to oil, literally at all, because of how little oil the centrifuge recipe produces (80 mb) compared to the amount of eu it takes to get that 80 mb of oil (16,000 eu)

<img width="501" alt="Screen Shot 2022-01-12 at 7 47 58 PM" src="https://user-images.githubusercontent.com/78517796/149251186-f6bcd0f6-fcbc-4526-ab22-7a9ecdf7addf.png">

I mean just look at that!!! For 80 mb of oil, you are almost consuming the same amount of energy 1 bucket of oil produces when burnt! (I know you don't typically burn straight oil, but jesus, even a full bucket only gives 20k EU!)

So I propose, that either the recipe is changed so that it takes up a lot more oil, for the same EU, perhaps at the cost of a lot more soul sand at once, (I propose 800 mb per operation or more for 10 soul sand)

 

### Your Goal

Why should soul sand to oil be such a net negative? Sure, it's not exactly a bitch to get in mass quantities, but it is kind of a bitch to use for oil, and isn't viable at all! And really... who is going to use this recipe for a 20% chance for a tiny pile of coal (which should be converted to a 25% chance of a normal pile of coal if y'all accept my change from 1 to 10 soul sand btw), and do y'all really think people are going to go through this for a 80% chance for a small pile of saltpeter?? (which should be converted to a 80% chance for 2 piles of saltpeter if you accept my proposed change)

I really think 800 mbs+ for at most 16k eu is more than reasonable! I mean, it's a direct 1:1 with how much EU 800 mbs of oil is worth! So I think this would be a more than worthy change to the recipe!

### Your Vision

I think it would make a recipe that is almost useless as is, at least have some use. Sure I believe that it should get an even bigger buff than this, but I think my proposal is more than acceptable to make this recipe actually usable! And maybe even give people a reason to strip mine soul sand if they couldn't find an oil spout or just really needed a top off really quick and didn't have time to go out and find a new oil spout!

Clearly this is more a recipe for earlier game, since hv+ has that oil multi, but what's the point of this recipe existing at all if it is so EU negative that it would only give 5k EU if you converted it all the way to cetane?!?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
There isn't a reliable source of soul sand (except bees perhaps), so I don't see why you'd like to make power out of soul sand, except for the sake of it.

**Comment by Elisis** [comment]
Alastor you seemed to be very aware of the ridiculousness of your manner of playthrough. You can't just make a fuss whenever you choose an obviously unfeasible option.

**Comment by Alastors** [comment]
> There isn't a reliable source of soul sand (except bees perhaps), so I don't see why you'd like to make power out of soul sand, except for the sake of it.

yes there is, thaumic replicators make soul sand, likewise, botania has a soul sand duplication recipe!

**Comment by Alastors** [comment]
> Alastor you seemed to be very aware of the ridiculousness of your manner of playthrough. You can't just make a fuss whenever you choose an obviously unfeasible option.

I'm very aware, but my point is more, why have a recipe that does something specific like make oil, if you don't intend for it to be used? It's the exact same issue as I am trying to fix in my ticket covering sodium persulfate! https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9909

**Comment by Glease** [comment]
quoting myself on discord:

IMO the spirit of that recipe is to always have a backup plan that offers some oil if you just cannot find any other alt source of oil, so that you can make the required chemicals like plastics. not for power obviously. we already have many power production alts for those tiers. as a backup plan it doesn't have to be efficient. I don't see a problem with how it's implemented now, but I also won't oppose someone to tweak it a little better. My bottom line is it cannot be better than oilsand which is not renewable, must be mined, and is supposed to be a viable oil source.

**Comment by Alastors** [comment]
> There isn't a reliable source of soul sand (except bees perhaps), so I don't see why you'd like to make power out of soul sand, except for the sake of it.

First up, I'd like to mention the thaumic replicator, it makes soul sand out of the 3 base aspects soul sand is made of, it takes the exact amount of essentia that melting soul sand down would make, it can also make wooden boards for some reason, but it has very limited amounts of makable items for whatever reason
<img width="1440" alt="Screen Shot 2022-04-23 at 10 36 04 PM" src="https://user-images.githubusercontent.com/78517796/164955367-27d43522-21e9-4805-9e11-4aebf45fd81e.png">
<img width="1440" alt="Screen Shot 2022-04-23 at 10 35 27 PM" src="https://user-images.githubusercontent.com/78517796/164955363-f51b7c26-fc12-422b-a058-3f3c6b0795da.png">
<img width="659" alt="Screen Shot 2022-04-23 at 10 41 18 PM" src="https://user-images.githubusercontent.com/78517796/164955505-e0afcdf9-6407-4190-8c88-17f07475f898.png">
<img width="973" alt="Screen Shot 2022-04-23 at 10 41 29 PM" src="https://user-images.githubusercontent.com/78517796/164955514-311b40d2-e380-4026-bf6b-e5bb17b79bd8.png">


Secondly, a slightly worse option exists from botania and the mana pool, which given mana is relatively inexpensive, means that soul sand is too.
<img width="738" alt="Screen Shot 2022-04-23 at 10 03 42 PM" src="https://user-images.githubusercontent.com/78517796/164954419-80baacb9-4585-4f8c-8410-06bd0deee745.png">

Finally, I'd like to mention the worst renewable option, the nether sapling, it has a passive conversion system, where the leaves change the first block directly under them into one of a few nether blocks, including soul sand.
<img width="1440" alt="Screen Shot 2022-04-23 at 10 38 59 PM" src="https://user-images.githubusercontent.com/78517796/164955446-ebbad32d-e669-4bb8-ba11-c58a990f16ac.png">
<img width="364" alt="Screen Shot 2022-04-23 at 10 40 01 PM" src="https://user-images.githubusercontent.com/78517796/164955473-183da834-6f3c-4619-b276-39ccf4c9537d.png">
this one also has an ender sapling variant that I use to get tungsten now because it makes almost exclusively endstone. even if I have to mine it from the overworld using block miners, and have to output blocks to it. 

There is very clearly no shortage of passive soul sand generation options

**Comment by Alastors** [comment]
> quoting myself on discord:
> 
> IMO the spirit of that recipe is to always have a backup plan that offers some oil if you just cannot find any other alt source of oil, so that you can make the required chemicals like plastics. not for power obviously. we already have many power production alts for those tiers. as a backup plan it doesn't have to be efficient. I don't see a problem with how it's implemented now, but I also won't oppose someone to tweak it a little better. My bottom line is it cannot be better than oilsand which is not renewable, must be mined, and is supposed to be a viable oil source.

the probelm is that the backup plan is so inefficient that it is so energy negative that you get like 5-8k by converting it to cetane diesel! A 5-8k net positive of a fuel that makes 1 mil eu per cell! Doesn't that sound fucking redundant? At the **very least** soul sand should be a net positive at the 480k eu base diesel makes per cell from a DT, I'm not saying it should be better than oil sand, which quite frankly sounds like a waste of an ore to me, if finding ore sand is about the same as finding an oil spout, so why not just find and cell up an oil spout if long distance transportation is the issue, but it should be a net positive eu for enough power production to at the **very least** to make it into oil, not that horrifically eu inefficient, especially if the methods to obtain the resources used for the recipe are considered less viable than oil sand!

**Comment by Steelux8** [comment]
The situation is that Soul Sand is a very poor source of Oil, and hard to make renewable. Oilberries already produce it renewably without having to do anything beyond crossbreeding crops as you would for any other crop, and those aren't as good as Refined Bees, which in turn aren't nearly as good as an oil rig. 

I like more oil sources when they aren't powerful enough to replace everything else. I'll do some quick math and improve the oil output.

**Comment by Runakai1** [comment]
I think this can be closed with the pr being merged. If not, reopen.
