### ISSUE TITLE
Hydro Dam causes crash on startup

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#9465]
### Your GTNH Discord Username

Logos#2981

### Your Pack Version

2.1.2.0

### Your Server

Eta

### Type of Server

Thermos

### Your Actions

Started a hydro dam's lake generation, on a moat-like structure. Twice now, a short time after starting the generation and doing a quick patrol of the moat to see that it generated properly, the server crashed and required a command line restart.

Exact reproduction details are uncertain, as I don't wish to keep crashing eta while testing, but the setup that seems to have produced these crashes (assuming not a coincidence) can be observed at my base on Eta.

### Crash Report

Crash 1 occurred at approximately 1609 UTC, 2022/01/12
Crash 2 occurred at approximately 0838 UTC, 2022/01/13

Hopefully that's enough to locate the event in the server's logfiles.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
@boubou19 any chance the logs above could be recovered (or this triggered again)?

**Comment by Logos-Askrson** [comment]
An attempt to trigger it again was made, and failed to crash the server. The main difference was fewer people being on, and the server thus being less strained. If reproduction is server-lag dependant, this might not be consistently reproducible.

**Comment by Logos-Askrson** [comment]
An attempt at demonstrating the hydro dam's construction and fill area was made on eta, resulting in another server crashed at about 2 minutes before the timestamp of this message.

Differences from the attempt at controlled replication are mostly in server load, as the server was populated this time.

A crash report was generated this time, and is attached: 
[crash-2022-02-09_00.02.33-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8028154/crash-2022-02-09_00.02.33-server.txt)
