### ISSUE TITLE
Visual prospecting fluid overlay bug

### ISSUE THREAD

**Issue by Masztufa** [GTNewHorizons/GT-New-Horizons-Modpack#9467]
### Your GTNH Discord Username

Masztufa#7816

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

visual prospecting jank doesn't happen

### The Reality

[molten nickel as underground fluid on overworld](https://i.imgur.com/gz1s1BQ.png) previously there was [good data](https://i.imgur.com/ZlsaHOK.png) on there 

it happened after prospecting on the moon and reading the books that came from it
Maybe it had to do with accidentally copying the data stick in the owerworld before processing it in the scanner

if this is interesting i'm alright with experimenting further (or sharing a save)

### Your Proposal

VP underground fluid is less jank

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Masztufa** [comment]
update: the moon minimap shows no discovered underground fluid, while there are a handful of helium3 deposits listed in the created books

**Comment by Masztufa** [comment]
re-prospected the area, now without accidental copying and it seems to work this way

**Comment by AlbertoPirillo** [comment]
I'm having the same problem, what do you mean by "accidental copying"?

**Comment by BritishCynic** [comment]
From my understanding, this issue is now fixed, and I've noticed that dimensions with previously-incorrect fluids will now correctly update when rescanned.
