### ISSUE TITLE
Visual Prospecting does not dimension-lock oil fields

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#9468]
### Your GTNH Discord Username

Riking#6902

### Your Pack Version

2.1.2.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

When opening a Seismic Prospector book, ore veins and oil fields are revealed and updated for the dimension that the seismic prospector was run in.

### The Reality

Ore veins are properly dimension-locked, but oil fields are revealed at the corresponding coordinates in the dimension you read the book.

Reproduction steps:

 - `/dimensiontp @p`, select Moon
 - Run Seismic Prospector, collect data stick
 - Process data stick (Scanner, Printer, Assembler)
 - Read book - reveals ore veins and oil fields
 - `/dimensiontp`, select Overworld
 - Read book - reveals oil fields. Overworld oil fields are updated and revealed, while moon ores are NOT put on the overworld map

### Your Proposal

Read the dimension info when updating oil field information.

Extra:

- Display dimension info in the book tooltip
- Journeymap dimension selection

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlbertoPirillo** [comment]
It's fine that you don't want to invest time on this, but players must be aware of the issue. 

I suggest that every single "Analyzed Prospection Data" printed book has in the description just below the coordinates (not inside the book, in the item description that you see by hovering on it) a warning like: 
"In order to correctly synchronize data with your map, open the book in the dimension in which the prospector was placed ".
