### ISSUE TITLE
Multiple controller covers on controller block override each other

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#9469]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.2

### Your Server

SSP

### Type of Server

Single Player

### Your Expectation

Following setup used to work but is now broken (gregtech version gregtech-1.7.10-5.09.40.16-35-g825ecd1 from jenkins, now including the cover GUI access from the parent block).

Build LCR, put machine controller covers on all of the sides of the controller block, set to "disable with redstone".
Place output hatches with fluid detector covers around the controller, set to "normal" mode, threshold to "0".
(this is my current use-case to handle sulfuric gas/light fuel/heavy fuel/naphtha in a single LCR).

![grafik](https://user-images.githubusercontent.com/64365566/149521972-f24ef7d1-4229-46f2-bcb5-4d9b34a97d55.png)

### The Reality

Noticed that the output hatch on the left had heavy fuel in it which should stop the LCR from operating until the hatch is empty, as no redstone signal is transferred to the controller. However the LCR kept operating, eventually voiding the heavy fuel. Removing the controller covers one after another revealed that, once the cover on the opposite side of the controller block (i.e. on the right side) is removed, the LCR operates as expected.
Seems that covers on the opposite side of each other have a mutual influence

### Your Proposal

It should work independent of covers being opposite.
Question: Do covers operate as AND logic or OR logic?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
It is just not intended to use more than one machine controller cover anyways...
For the lcr, just put the hatches in the middle of each face, with fluid detectors facing inwards (towards the ptfe pipe casing), set them to strong signal with soldering iron, and put the machine controller at the back of the controller block. works fine.

**Comment by Glease** [comment]
If you put multiple machine controller cover on it, only one will ever be effective. IIRC this has always been the case. Which of them would be the one effective is an implementation detail that we prefer to not disclose, as they are subject to change without notice.

**Comment by Savallator** [comment]
I mean, it would certainly be nice to have consistent behavior (either AND or OR), but i guess it is not that easy, and most likely not worth implementing, as every possible usecase could be solved easily without.

**Comment by bombcar** [comment]
Then perhaps we should refuse to allow multiple controllers on a single block, so people don't try it and think they have a working setup.
