### ISSUE TITLE
Error in loading screen tips.

### ISSUE THREAD

**Issue by YanFett** [GTNewHorizons/GT-New-Horizons-Modpack#9474]
### Your GTNH Discord Username

reverse71

### Your Pack Version

2.1.2.1

### Your Server

private server

### Your Expectation

Mathematical correctness. sqrt(-1) is not defined. i^2 = -1 does **not** imply i = sqrt(-1).

### The Reality

sqrt(-1) loves you.

### Your Proposal

remove this bringer of shame from the loading screen tips.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
![477DF566-83E5-44C5-8222-30DB57FCDC04](https://user-images.githubusercontent.com/533931/149624640-a9855773-30b4-41cc-a493-c2ec3f706483.jpeg)

**Comment by bombcar** [comment]
gtnh is the number such that when squared it is equal to negative fun
