### ISSUE TITLE
In quest "divine rod of the goods" quest book doesnt show rod recipe in nei after clicking on it

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9475]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

Started "divine rod of the goods" quest, found all the things which are required for crafting rod, clicked on rod in the recipe book to see its recipe. Expected the NEI to show craft recipe like it always does when clicked on the recipes in the quest book.

### The Reality

NEI window did not open after clicking on the rod in the quest book. Nothing happened.

### Your Proposal

Show rod recipe in NEI after clicking on the rod in the "divine rod of the goods" quest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Is it a Thaumcraft item and do you have the research for it? Thaumcraft items don't show recipes in NEI until researched.

**Comment by MadRatSRP** [comment]
> Is it a Thaumcraft item and do you have the research for it? Thaumcraft items don't show recipes in NEI until researched.

Nope, its an item that could be acquired in the Stone Age quest, its not an Thaumcraft item
