### ISSUE TITLE
NEI's hint position in recipes sometimes broken

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9476]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I opened Vein Stats tab and i wanted to see in which worlds Chalcopyrite is generated, so i scrolled my cursor on the Ow text, red line on the screenshots is the cursor position. However, Overwold hint did not show near or slightly above the Ow text and to see it i needed to scroll it way below how its shown on the second screenshot, the problem with that that its not something that comes into your mind :D and it also hides the information about the vein.
![ore pos bug1](https://user-images.githubusercontent.com/29717217/149629177-d157c8fd-6c2e-4fe5-aef6-36964c250c85.png)
![ore pos bug 2](https://user-images.githubusercontent.com/29717217/149629179-796c3106-d4ae-4c73-8d36-462a26a132bc.png)
this problem exists with the other recipes too, screenshots linked below
![image](https://user-images.githubusercontent.com/29717217/149629333-4e0eb543-8560-4dec-9e89-b823a6c0e6fa.png)
![image](https://user-images.githubusercontent.com/29717217/149629350-0535c6c4-a743-4676-9996-029a60e9d05d.png)

### The Reality

Described in the Expectations text

### Your Proposal

Fix the NEI's hint position so users wont panic about it :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Gateswong** [comment]
+1 on this. The Thaumcraft "aspect A + aspect B = aspect C" recipe interface breaks as well.

**Comment by bombcar** [comment]
There has been a major tooltip rework that I believe fixes some of these. You’d need to install various mods from jenkins tho
