### ISSUE TITLE
remove the first time we use the secondary loading bar as it goes so fast now

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9478]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.2

### Your Proposal

This loading bar (the second one) gets to 3% and then goes away:

![Uploading image.png…]()

### Your Goal

remove it as it is gone in a flash anyway now

### Your Vision

faster pack loading

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Your image link is broken. Try more patience next time.

**Comment by bombcar** [comment]
![](https://media.discordapp.net/attachments/603348502637969419/932150437866528808/unknown.png)

**Comment by Dream-Master** [comment]
your screen or your solution is to small

**Comment by bombcar** [comment]
> your screen or your solution is to small

not the position, but the bar itself doesn't show anything useful because we sped everything up so much, it just goes from 0% to 3% and then it's done

**Comment by YannickMG** [comment]
On 2.1.2.0 I can see the secondary bar several times, the first time it disappears at 3% but 2-3 other times it stays a few seconds on screen  and completes.

It's true that it's not a very meaningful indicator. Is it a nuisance though?

**Comment by bombcar** [comment]
I have no problem with the second two usages, but the first time it appears can be bypassed imo
