### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9479]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Clicked R on a block, cant remember which one, minecraft crashed immediately after that

### Crash Report

[crash-2022-01-16_13.53.55-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7876804/crash-2022-01-16_13.53.55-client.txt)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7876805/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by draknyte1** [comment]
@D-Cysteine

**Comment by D-Cysteine** [comment]
This should have already been fixed by [v1.4.3](https://github.com/D-Cysteine/nei-custom-diagram/releases/tag/v1.4.3); please let me know if that does not fix it for you
