### ISSUE TITLE
Shiftclicking Questionmark Crafting Failure

### ISSUE THREAD

**Issue by Erneest** [GTNewHorizons/GT-New-Horizons-Modpack#9481]
### Your GTNH Discord Username

Ernest#1424

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expect to craft a chest, no lie
![Step 1](https://user-images.githubusercontent.com/96063310/149663367-e12b18f7-e5a1-42c9-82a0-269209f03562.png)

### The Reality

My crafting grid is wrecked
![Step 2](https://user-images.githubusercontent.com/96063310/149663405-a7d6e312-9e1b-495f-aaab-ecd88b5bfb20.png)

### Your Proposal

Fix it fix it fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
This is from pressing the ? from NEI with the tinkers table that works with DIAMOND chest

**Comment by Erneest** [comment]
> This is from pressing the ? from NEI with the tinkers table that works with DIAMOND chest

Yeah "works"

**Comment by mitchej123** [comment]
Fixed already.
