### ISSUE TITLE
Cant mine any blocks with fist after death after opening to LAN.

### ISSUE THREAD

**Issue by Bl0f3lt** [GTNewHorizons/GT-New-Horizons-Modpack#9482]
### Your GTNH Discord Username

CATAK#7264

### Your Pack Version

2.1.2.0-RC1

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

![image](https://user-images.githubusercontent.com/93886321/149663963-bb841557-e311-4e7a-a7ea-39c9a7b6beb3.png)
Can Mine Dirt with fist in this case after death and opening to LAN changing game mode and back again.

### The Reality

![image](https://user-images.githubusercontent.com/93886321/149664064-1ed66890-d20a-4a41-a4ee-7087dd257e39.png)
Cant mine dirt with fist after death, for context, i died was back at spawn so opened to LAN with cheats on, went into game mode C and flew back to death location before changing back to game mode S and not being able to even mine my grave. Somehow mining blocks with retrospective tool does work, e.g. dirt with a shovel.

### Your Proposal

Still being able to play without having to use tools for every block. Possibility for getting stuck if run out of gravel too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Open2lan makes all sorts of weird bugs but this is strange. Did you add any mods? Does a restart fix it? Did /back not work to take you to your grave (maybe an add on for that)

**Comment by mitchej123** [comment]
You're probably on adventure mode.

**Comment by Dream-Master** [comment]
> You're probably on adventure mode.

hehe make adventure mod standart in GTNH :P

**Comment by Bl0f3lt** [comment]
> You're probably on adventure mode.  

Yeah that's the likely case, I opened to lan again and /gamemode s and that seemed to fix the issue

**Comment by Bl0f3lt** [comment]
> Open2lan makes all sorts of weird bugs but this is strange. Did you add any mods? Does a restart fix it? Did /back not work to take you to your grave (maybe an add on for that)

I somehow ended up in adventure mode and a /gamemode s fixed the issue, I'll keep in mind that /back brings you back to a grave for the future though:)
