### ISSUE TITLE
EnderIO machines cannot draw GT power from pre-connected cables

### ISSUE THREAD

**Issue by Loreili** [GTNewHorizons/GT-New-Horizons-Modpack#9483]
### Your GTNH Discord Username

Loreili#5457

### Your Pack Version

2.1.2.0

### Your Server

Private Server

### Type of Server

Don't know

### Your Expectation

Place an EnderIO machine on a GT cable which has already been faced to the placement side using a wire cutter. The machine should charge.

### The Reality

The machine does not charge.

Placing the machine and _then_ connecting it to the power cable with the Wire Cutter causes the machine to charge correctly. I assume this is related to the Enet changes..

### Your Proposal

Machine should charge when placed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can you try the one that doesn’t work - and then restart and load and see if it fixes itself

**Comment by Loreili** [comment]
Restarting the server does seem to fix this.

To test:
 - Set up a GT wire with the output already set
 - Place the EnderIO machine (I used a Slice'n'Splice)
 - Machine is not powered
 - Restart server
 - Machine is powered
