### ISSUE TITLE
Bug in the "You are not prepared" quest

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9484]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Was doing "You are not prepared!" quest, crafted Seared Faucet using saw and casting channel. Expected quest to count these seared faucets as required.

### The Reality

Seared Faucets crafted from the saw and casting channel were not counted as required, only searing faucets crafted from searing brick are counted as required.

### Your Proposal

Instead of counting seared faucets crafted from the searing brick let the quest require any searing faucet - no matter how it was crafted

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by b0rah** [comment]
Encountered in my own run, super annoying

**Comment by boathouse2112** [comment]
Had this bug yesterday on the Epsilon server. Book lists it as a retrieval task, but the sawed faucet didn't count.

**Comment by chochem** [comment]
works just fine for me.

**Comment by chochem** [comment]
retrieval doesnt care how you crafted it anyway.

**Comment by boathouse2112** [comment]
Reproduced it. If you craft it with the saw on the left side, it makes `Seared Faucet (#1052/1) -- TConstruct:SearedBlock`, and completes the quest, but if you cast it with the saw on the right side, it makes `Seared Faucet (#1053/1) -- TConstruct:SearedBlockNether`, and doesn't count.

**Comment by chochem** [comment]
uh ok, thats a recipe bug then, not a questbook bug.

**Comment by chochem** [comment]
Specifically: that nether one shouldnt exist.
