### ISSUE TITLE
Purple "I'm Invalid" block can cause loss of what it used to be

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#9488]
### Your GTNH Discord Username

Shadows#4865

### Your Pack Version

2.1.2.1

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

I was breaking a machine, and it turned into the purple "Don't mind me, I'm Invalid!" block, which was maybe due to server lag (maybe? A bit difficult to tell). This should've just been a visual thing and then dropped afterwards, but...

### The Reality

Then after being in that state for a second it disappeared and **didn't** drop the source block. This has now happened twice: Steel Pipe and HV Extruder. Interestingly, the Extruder occurrence still dropped the pattern I had inside it. But no machine

### Your Proposal

It should drop whatever "spawned" it, or some similar fix to ensure that machines don't just disappear into the ether.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
If you’re lagging try not to change tool during one of these - if you stay on the tool it seems to work better.

**Comment by Shadowsoftime99** [comment]
Do you think what's happening is that it checks what tool I'm holding when the purple block disappears, and acts as if I broke the machine with that? Thus acting as if I broke it with the fist.

**Comment by bombcar** [comment]
It could be - not certain what causes it but that's as likely as anything. The key is if you change tools before it gets back in sync it disappears.
