### ISSUE TITLE
Switch to GTMEGA fork of RandomThings

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#9491]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

2.1.1.2

### Your Proposal

GTMEGA folks ported RandomThings from ASM to mixins to avoid conflicts when mixins won't apply to ASM transformed class
https://github.com/GTMEGA/Random-Things/tree/2.2.4-mixin

(e,g, both RandomThings and new Galacticraft change World and RenderGlobal classes)

### Your Goal

.

### Your Vision

I believe it would help avoiding obscure problems.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
@repo-alt 
https://github.com/GTNewHorizons/Random-Things
