### ISSUE TITLE
Would be nice to have a method of refactoring p2p "heads"

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#9498]
### Your GTNH Discord Username

0lafe#3719

### Your Pack Version

Newest

### Your Proposal

It would be nice if there was a way to copy the "head" of a p2p network onto a new p2p bus. Doing so would probably unlink the original head, and set the new ones frequency to the old frequency. Not sure on the specifics, but I assume you can't have 2 "heads" with the same frequency. 

I may be way off here with fluid p2p being bidirectional, but other users have confirmed this is still an issue

### Your Goal

It's annoying af if you have a large p2p network and need to change the head. It seems like at the moment in that case, you need to rewrite all of the receivers with the new frequency. This would allow you to simply apply the old head frequency to a new head, while keeping all the receivers connected. 

### Your Vision

This should allow players to refactor setups a little easier. Would help with channel p2p when making new controllers, fluids when moving fluid storage/production, and power when uptiering LSCs and such. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
An alternative, more feasible proposal from discord: "When you break the input (either accidentally or intentionally), you have to physically visit all outputs and update. Would be nice if you could choose one of those existing outputs and make it the new input and all of the same frequency connect"

**Comment by repo-alt** [comment]
Proposed way to switch "input":  if you right-click a configured p2p output with a memory card, and the card has the same frequency as this p2p, then transfer input here.

**Comment by 0lafe** [comment]
if that works, that sounds like a very good solution. my only worry is that i thought breaking the head node sets all the connections to "unlinked". if im wrong though i like this idea very much.

**Comment by repo-alt** [comment]
Breaking the input does indeed destroy p2p, but here we don't break anything, input is "hotswaped"

**Comment by GlodBlock** [comment]
in fact there has already been a mod that has such function in 1.12
https://www.curseforge.com/minecraft/mc-mods/betterp2p
it is under GPLv3, so i ported it back to 1.7.10
https://github.com/GlodBlock/BetterP2P
![2022-01-30_15 12 18](https://user-images.githubusercontent.com/60341015/151690549-e0947fcb-b3af-4fcd-8f55-a179c8ee94b4.png)
![2022-01-30_15 12 22](https://user-images.githubusercontent.com/60341015/151690553-dff739ec-3e18-461a-9c29-724e9aa3890b.png)

**Comment by Dream-Master** [comment]
@GlodBlock is a backport possible ?

**Comment by GlodBlock** [comment]
the backport is done now
