### ISSUE TITLE
Add the ability to "search" for a specific ore vein / underground fluid in Visual Prospecting

### ISSUE THREAD

**Issue by ducanh2002123** [GTNewHorizons/GT-New-Horizons-Modpack#9503]
### Your GTNH Discord Username

Crippling depression#2744

### Your Pack Version

2.1.2.1

### Your Proposal

Adding the ability to  search for a type of ore vein or underground fluid in a list of veins that you've discovered in Visual Prospecting

### Your Goal

well, at the moment, Visual Prospecting allows you to have a nice layer on your map that displays what's in which ore chunks, but there's just one small problem, is that once you start to have a lot of veins tagged in, then finding a specific type of vein will start to take time because there's nothing actually sort through the veins that you've found, and in turn, just doing waypoint spamming would actually save more time, as you can actually search for a vein using that

### Your Vision

This would help to make Visual Prospecting a lot more useful and would save a lot of time searching through stuff that you've discovered in the world given that GTNH worlds have a very large amount of ore vein types, so the amount of ore vein a player will have on their map will of course be very high, having something to sort them out (such as waypoint spam from before VP was in the pack) will be very useful

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Florexiz** [comment]
You can enter ore name in NEI and double click search bar. This will highlight veins that contain this ore
![image](https://user-images.githubusercontent.com/29033773/150213045-8b7bba65-c76b-4b7b-9a13-d3689b954d22.png)
