### ISSUE TITLE
GT++ machines Void protection not working with non-stackable items

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9504]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.1

### Your Server

private

### Your Expectation

When using a Multiblock assembler to make Lapotrons, it should not void stuff if the paralell is larger than what would fit the output bus.

### The Reality

When having an assembler multi doing Lapotrons with an HV output bus (16 slots) and UEV Power (20 Paralell), it voids 4 lapotrons per craft.

### Your Proposal

Add a check to handle non-stackables and high paralell.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
I suspect there is something wrong on a deeper level with the Assembler Multi... i switched it to an ME output bus, and just had it made 164 Coil blocks, and it ate the Ingredients all fine but did not make any coils. The Output bus has a channel, and there is free storage. it also did not shut down due to power loss...

**Comment by draknyte1** [comment]
ME bus cannot have void protection.

**Comment by Savallator** [comment]
But since it has infinite buffer, it should not void

**Comment by Savallator** [comment]
I am not sure how I can debug the issue further, at least I will watch out for future appearances... after that for the next recipe it worked fine...
