### ISSUE TITLE
MFSU not give EU

### ISSUE THREAD

**Issue by abitaredomdepo** [GTNewHorizons/GT-New-Horizons-Modpack#9506]
### Your GTNH Discord Username

angeldust23#2076

### Your Pack Version

2121

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

РАБОТАЮЩИЕ КАБЕЛЯ. СКАЖИТЕ ПОЖАЛУЙСТА КОМУ ДАТЬ КОМПЛИМЕНТЫ ЗА СЛОМАННЫЕ МФСУ И КАБЕЛЯ.

WORKING CABLES. PLEASE TELL WHO TO GIVE COMPLIMENTS FOR BROKEN MFSU AND CABLES.

### The Reality

https://drive.google.com/file/d/1U_4og_B6DvCZ84n_aluEc2k4_Yr5nHpw/view?usp=sharing

### Your Proposal

ПОЧИНИТЕ

FIX IT
![обэме-козенахуй](https://user-images.githubusercontent.com/51705777/150018131-7a5ea177-80fa-4fc5-8483-fbefab005af5.gif)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by abitaredomdepo** [comment]
https://drive.google.com/file/d/1Q2lobyG4QHB22QlSuw_umtNp1fLm5704/view?usp=sharing

это нормально что нужно использовать любой потребитель GT чтобы кабель передавал энергию?

is it normal to use any GT consumer for the cable to transmit power?
![picard-facepalm](https://user-images.githubusercontent.com/51705777/150020079-fffcc5fa-0403-4317-b88c-87babd7f9b47.jpg)

**Comment by Dream-Master** [comment]
@abitaredomdepo this is not a meme channel. Text to explain the issue is enough.
