### ISSUE TITLE
make the monitoring of crafting jobs through a terminal not moving the focus to last job triggered

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9510]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Proposal

make the monitoring of crafting jobs through a terminal not moving the focus to last job triggered

### Your Goal

Right now, each time a crafting job is triggered in AE, it gets pushed 1st in the job list. That's shifting all the indexes of the crafting jobs, but looks like the focus isn't shifted with it. So when you have many small and quick crafts regularly triggering, it's a pain to monitor it through the terminal, and i always end up checking it in the crafting monitor instead.

### Your Vision

Remove the pain of monitoring the crafts through a terminal, especially if you own an infinity card so you can properly watch your crafts from everywhere.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
It is a bit different (with the same effect), when there are several equal free CPU clusters, last one is selected to execute a job.

**Comment by repo-alt** [comment]
Actually, it turns out that crafts issued by the user and crafts issued by the crafting cards use opposite sorting of available CPUs. User request are executed on more powerful CPUs first, and crafting cards are executed on least powerful first. Here "power" is first number of processors, then amount of memory. And as far as I can tell this is intentional and "correct" behaviour.

**Comment by boubou19** [comment]
Well yeah the issue is that it keeps shifting the tasks in the monitor. What i request is to somehow force the monitor to stick to the craft it's displaying unless the craft ends or unless the player clicked on the button to look at next job.

**Comment by repo-alt** [comment]
ah, I see

**Comment by repo-alt** [comment]
Well, I can try to stick to the name, but CPU clusters have to be renamed for this to be consistent, because those "CPU: #0" names are autogenerated and will shift with the active CPU changes

**Comment by boubou19** [comment]
that's ok, as long as there is a way to achieve this it's fine. i think most players rename their interfaces already anyways, so what's a couple more renaming to do?
