### ISSUE TITLE
Wireless redstone covers "null" tag

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9511]
### Your GTNH Discord Username

Colen

### Your Pack Version

2.1.2.0

### Your Expectation

![image](https://user-images.githubusercontent.com/54497873/150128514-9265414b-6a9e-47ba-84e3-a47f38f3cf35.png)

![image](https://user-images.githubusercontent.com/54497873/150128547-62922e11-e5a8-4a70-92c6-c497c4eaee77.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Colen** [comment]
![image](https://user-images.githubusercontent.com/54497873/150128915-f605efb6-c30d-4b09-9d7f-3acb1bfcf9af.png)

Just spotted this on another cover as well, not sure what the issue is tbh but doesn't seem to impact funtionality.

**Comment by YannickMG** [comment]
Do you have an updated GT5U version or just whatever shipped with 2.1.2.0?

**Comment by GTNH-Colen** [comment]
Base 2.1.2.0 GT, playing on Eta with a slightly updated server side jar but this seems client side anyway.
