### ISSUE TITLE
Botany glass and ceramics

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#9512]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.1

### Your Server

Zeta

### Your Expectation

Complete quests 1959 and 1960

### The Reality

Botany ceramics and glass doesn't count by questbook
They can also stack with different colors loosing their own color

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Waisse** [comment]
It's not working on Eta, pigmented glass doesn't count for the quest and merges with other pigmented glasses of a different color in player's inventory or any kind of inventory. Botany as a whole is a broken mod that clearly wasn't playtested. Seriously, where is my floralyzer? Field kit sucks and block analyzer is sloooooooooooow, and maintaining hydration by placing sand and water every few minutes ahhhhh

**Comment by ArcadiaBlues** [comment]
Still observing the item combining issue present in 2.9.0 beta-1, requesting this issue be re-opened.

Further details:

Picking up multiple variations of most decorative Botany/Extra Trees blocks will make them combine into one stack, the second block collected becomes the same variant as the first block. The same occurs when affected items are dropped into the same space.

https://youtu.be/RS3Iwv-s97c

I suspect this is related to the implementation of metadata in Binnie, as it has specific classes for IBlockMetadata and BlockMetadata where Chisel and ZTones do not.

Referenced classes:
https://github.com/GTNewHorizons/Binnie/blob/master/src/main/java/binnie/core/block/BlockMetadata.java
https://github.com/GTNewHorizons/Binnie/blob/master/src/main/java/binnie/core/block/IBlockMetadata.java
