### ISSUE TITLE
Stargate-Crystal Dust can't be crafted

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9518]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

Tested on multiblock mixer, won't start
Singleblock doesn't have enough slots since exquisite stack up to 16, not 64.

### The Reality

+

### Your Proposal

Change stacking of exquisite to 64, or change recipe to use less

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Usernm0** [comment]
Confirm bug on 2.1.2.1.
As workaround I use processing array with one UV+ mixer inside. It works well with exquisite gems stacks.
