### ISSUE TITLE
Twilight Forest Portal needing doDaylightCycle

### ISSUE THREAD

**Issue by Nenluen** [GTNewHorizons/GT-New-Horizons-Modpack#9522]
### Your GTNH Discord Username

Nenluen#9513

### Your Pack Version

2.1.2.1

### Your Server

<private server>

### Type of Server

Vanilla Forge

### Your Expectation

On my 'Eternal Daylight' server (with doDaylight Cycle turned off at near noon) I tossed the Quick and Dirty Portal Generator into a correctly built twilight portal structure, expecting lightning and a portal to open

### The Reality

The Generator went into the water, and just sat there in the normal, blue water, occasionally bobbing, but just sitting there.
![2022-01-20_11 55 09](https://user-images.githubusercontent.com/10765948/150395842-962cd151-7153-407f-88c2-5cc879ffea43.png)

(Creative mode temporarily used as I went to many, many different locations to try to get the portal to open after several nearby failed attempts)

### Your Proposal

Not much to do, but others playing on an 'Eternal Daylight' or 'Eternal Night' servers might need to have doDaylightCycle turned on for a brief moment for the portal to open, as once I turned doDaylightCycle back on, the portal opened (note the time is now 12:34pm)
![2022-01-20_11 55 19](https://user-images.githubusercontent.com/10765948/150395988-6e0f0e29-1574-4b64-a462-12a7763138a8.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@GlodBlock did this happens because your change ?

**Comment by GlodBlock** [comment]
no, i have tried some older version of TF like 2.3.8.7 but all failed when disable the day cycle. maybe the eternal daylight mess up the tick thing.

**Comment by bombcar** [comment]
@Nenluen can you try http://jenkins.usrv.eu:8080/job/TwilightForest/lastSuccessfulBuild/artifact/build/libs/TwilightForest-1.7.10-2.3.8.11-1-g5558513.jar and report if it now works

**Comment by Nenluen** [comment]
uploaded the new file to my server and client, flipped to creative, broke my portal (refilled in the water)

![2022-01-22_11 46 21](https://user-images.githubusercontent.com/10765948/150649827-b71ce009-f87e-47eb-bb03-49e37bcfd70d.png)

Chucked a Q&D Portal Generator into the water, and it worked!  doDaylightCycle is still set to false (as shown by the time still being 12:34p on both screenshots)

![2022-01-22_11 49 11](https://user-images.githubusercontent.com/10765948/150649833-ac7a1c21-3438-483b-aa1e-5f18d25aeb59.png)

popped in and out of the portal, and it linked up to my previously made on in the Twilight Forest

**Comment by draknyte1** [comment]
ez fix.
