### ISSUE TITLE
Item detector cover not working with superchests/quantum chests

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9527]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.1

### Your Server

private

### Your Expectation

Item detector cover should work on Superchests.

### The Reality

When attaching an item detector cover to a super chest (or quantum chests), it does not work, since it apparently sees only the 2 exposed slots (threshold can not be set over 128 as well).

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Well it does work as it always worked (giving restone signal proportional to the fullness), but new stuff (GUI and threshold) are indeed broken
