### ISSUE TITLE
Java8 u321 causes GTNH to explode

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9532]
### Your GTNH Discord Username

💣 🚙 #1042

### Your Pack Version

2.1.2.0

### Your Server

sp

### Type of Server

Single Player

### Your Actions

Run GTNH on Java8 321 which auto updated 

### Crash Report

https://cdn.discordapp.com/attachments/401118216228831252/934341729560170536/latest.log

This appears to be related to https://github.com/McModLauncher/modlauncher/issues/91

Client reverted to a different jvm (graalvm) and issue went away. 

Not sure if we can ASM around this one, may have to add a “bad jvm” check. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by draknyte1** [comment]
Just have to wait for launches to propagate some variation of https://github.com/McModLauncher/modlauncher/pull/92/files I guess.

**Comment by draknyte1** [comment]
The former I believe.

**Comment by bombcar** [comment]
Heh MultiMC says it has to be fixed in forge which I'm sure will happen any day now. So I guess it's time to code up a java version detector or ASM forge itself.

**Comment by Alastors** [comment]
eyyyyyy @bombcar this is what happened to me a few days ago! and I had to revert back to 8u281 which is sadly slower than whatever version I was using before smh

**Comment by bombcar** [comment]
320 and earlier will work, or try graalvm https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.2.0

**Comment by Glease** [comment]
Aren't having any issue here with b322 on client side - which exact line of code is accessing that stuff in GTNH? You do realize we are still on legacy launch right?
>E:\>java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
