### ISSUE TITLE
Add a recipe for Cloud In A Bottle

### ISSUE THREAD

**Issue by Bauntilein** [GTNewHorizons/GT-New-Horizons-Modpack#9533]
### Your GTNH Discord Username

Baunti#1259

### Your Pack Version

2.1.1.0

### Your Proposal

As the title suggests, I would like to have a Cloud In A Bottle recipe added to the game.

### Your Goal

It isn't anything lifechanging, I admit that, but I recently found out that it has a pretty good use in builds, so I'd love to be able to use it outside of creative mode. I've also seen this promt before in issue #1051 but only a cloud recipe has been added to the game.

### Your Vision

Overall, I could imagine making this item by bottling steam, which seems to be the most realistic take on this.
And on the matter of improving the pack, I'm sure other people could use it for aesthetic reasons or whatever other reason there may be as well.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
See also https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8589 - apparently there's some griefing issues - could decorative clouds be made in another way?

**Comment by Bauntilein** [comment]
I'm mainly for adding to this because of the way the bottle actually generates the clouds. Of course I could just place them myself but I've noticed them being very handy when building custom trees, especially the leafs.

**Comment by Bauntilein** [comment]
> See also #8589 - apparently there's some griefing issues - could decorative clouds be made in another way?

I'm mainly for adding to this because of the way the bottle actually generates the clouds. Of course I could just place them myself but I've noticed them being very handy when building custom trees, especially the leafs. But of course the griefing factor is somewhat of an issue :/

**Comment by Dream-Master** [comment]
@bombcar @Bauntilein we can add it in the zzclient file so it is not present on servers

**Comment by Bauntilein** [comment]
> @bombcar @Bauntilein we can add it in the zzclient file so it is not present on servers

That'd be one way to do it, problem is just that I wanted to use it on a server lol

**Comment by Dream-Master** [comment]
if you the server owner you can do what you want but this recipe can only be placed in the client file from my side. Feel free to fix the bug in the cloude code.

**Comment by draknyte1** [comment]
What exactly is the issue with the code?
I'll fix it.

**Comment by mitchej123** [comment]
My recollection is that natura clouds indiscriminately overwrite other blocks.

**Comment by draknyte1** [comment]
> My recollection is that natura clouds indiscriminately overwrite other blocks.

Code seems to check if it's air... 🤷🏻‍♀️

**Comment by Bauntilein** [comment]
> if you the server owner you can do what you want but this recipe can only be placed in the client file from my side. Feel free to fix the bug in the cloude code.

Quite frankly it's a public server but if this is the only way to add some kinda recipe to it then I guess I'll take it.

**Comment by Bauntilein** [comment]
> > My recollection is that natura clouds indiscriminately overwrite other blocks.
> 
> Code seems to check if it's air... 🤷🏻‍♀️

When I used it in creative while building it didn't replace any blocks for me that weren't air so I'm not sure what would trigger that griefing aspect
