### ISSUE TITLE
Blockheads kitchen cabinets have broken collision leading to suffocation

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#9537]
### Your GTNH Discord Username

Riking#6902

### Your Pack Version

2.1.2.2

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

Block collision works properly with Cooking for Blockheads kitchens and you don't randomly suffocate

### The Reality

Hold W to take damage

![2022-01-22_14 46 20](https://user-images.githubusercontent.com/627891/150657824-17428bcd-fe86-4d69-b4b2-ee6829fbb76b.png)

### Your Proposal

fix the collision?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
Please actually search next time before blindly clicking that you did.  https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8039

![image](https://user-images.githubusercontent.com/1894689/150657898-6943b45e-0ad3-4082-a42d-8a6d3e5e8f1b.png)
