### ISSUE TITLE
GTNH won't fully exit on crash now

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9539]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Actions

In the current SP version available, there's a bug with minetweaker. So do the following (from multimc)

1. start pack, join zeta
2. leave zeta and immediately try to open a world
3. triggers https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9538
4. try to exit GTNH

### Crash Report

At this point the game will "hang" because a thread somewhere isn't exiting correctly, and you have to force quit java.

Not sure what thread is hanging open but I suspect visualprospecting.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Sphyix** [comment]
I helped players figure out the ram issues with visualprospecting on the first launch, and noticed one of them reported the game not fully closing when it was crashing because of that. He had to close by terminating java in that case aswell.

**Comment by Glease** [comment]
Should be fixed by now.
