### ISSUE TITLE
AE2 Crafting Terminal "Request Missing" is sticky in edge cases

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#9540]
### Your GTNH Discord Username

Riking#6902

### Your Pack Version

2.1.2.2

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

There is a new feature. When you open an AE2 Crafting Terminal, and view the recipe of an item you want to build, there are three options with the NEI question mark:

 - Normal click: Ghost items into the crafting table.
 - Shift-click: Place items into the crafting table. Draw from your inventory first, and then from the AE2 network.
 - LControl-click: Place all available items into the crafting table, and issue AE2 crafting requests for any missing items.

These crafting orders are presented to the player one by one after ctrl-clicking.

### The Reality

In some race condition, the crafting orders aren't cleared out correctly. The next time you finish issuing a crafting order without using this feature, it will proceed to present the crafting orders from the glitched use of the feature one after another.

When the glitch was triggered, there was a flash of GUIs and I just hit cancel a lot.

This glitch can be cleared by using the feature again.

FAILED TO REPRODUCE. If you remember what you did to get this, please post below...

### Your Proposal

Investigate the code for any race conditions, and ensure the extra crafting orders are only ever presented once each. Low priority.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vfyjxf** [comment]
I've tried to fix this problem several times, but apparently I failed and I'm not sure how to fix it. I hope I can fix it in the next version of the update. 
Regarding the new features, I will take some of your suggestions, but it will not be exactly the same
