### ISSUE TITLE
AE2 Terminal not updating

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9541]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.2

### Your Server

private

### Your Expectation

When taking stuff out of a terminal (wireless or normal), it should not be shown as still there, despite being in my inventory. The amount only updates when i close the terminal and open it again. Quite annoying when i want to take all and craft more.
The same happens when inserting, items will not show. I mean, the Terminal does not have to update every tick, but at least every second or so...
It was working fine in AE beta-66, but already broken in beta-71, and still broken in 72.

### The Reality

it is buggy.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by riking** [comment]
I have also seen minor rubberbanding of item quantities. If I wait for a while, it fixes itself.

**Comment by repo-alt** [comment]
Probably some optimization consequence.

**Comment by repo-alt** [comment]
Can't reproduce that on Zeta

**Comment by Savallator** [comment]
Okay, so just to make sure, this is what i do to reproduce: I open the terminal, search for an item. There are like 3 energy hatches available. I put them into my inventory, the terminal still shows 3 energy hatches that can not be extracted. This persists until the Terminal GUI is closed.

**Comment by vovaksenov** [comment]
How do you store items in the network? Delays could appear if you do it through subnetworks and/or many storage buses.

**Comment by Savallator** [comment]
I have subnetworks attached, but the item storage and the terminals are on the main network.
