### ISSUE TITLE
Ctrl + ? in AE

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#9545]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.2

### Your Server

Zeta

### Your Expectation

Open crafting orders for only missing items

### The Reality

It opens crafting task for every item in recipe, even if it exist in ae or player inventory
#9540 maybe related

### Your Proposal

Fix (worked in 2.1.2.1)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vfyjxf** [comment]
If you mean opening a gui to set the number of item to craft, it will be replaced in the next update, and the original function from RS will be modified in some way.(The previous feature is a big failure)You can also set NotEnoughEnergistics.cfg enableCraftAmountSettingGui to false to use a feature similar to rs, which will only ask for missing items.

**Comment by vfyjxf** [comment]
> If you mean opening a gui to set the number of item to craft, it will be replaced in the next update, and the original function from RS will be modified in some way.(The previous feature is a big failure)You can also set NotEnoughEnergistics.cfg enableCraftAmountSettingGui to false to use a feature similar to rs, which will only ask for missing items.

Right now I'm testing new features in 1.12.2, the 1.7.10 update may take a while
