### ISSUE TITLE
Some GT++ Multi can't work

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#9548]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.2

### Your Server

Single

### Type of Server

Single Player

### Your Expectation

1. I put in Redstone and Alumina Milling Ball, ProgrammedCircuit(10), and tried to work IsaMill Grinding Machine.
2. I assembled the Solar Tower and inputted the Solar Salt(Cold). 

### The Reality

1. Can't work
2. Solar Salt(Hot) was not produced.

* There are no recipes that use Flotation Cell at all.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/290
