### ISSUE TITLE
charcoal pile ignitor stops working at 100th second

### ISSUE THREAD

**Issue by bnm1986** [GTNewHorizons/GT-New-Horizons-Modpack#9550]
### Your GTNH Discord Username

bnm1986

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

make 11x11x6 charcoal pile ignitor. machine should finished in 602 sec (as it said)

### The Reality

make 11x11x6 charcoal pile ignitor. machine starts work but stops at 100-th sec,

### Your Proposal

machine should finish work correct

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Fixed in latest

**Comment by miozune** [comment]
duplicate of #9273
