### ISSUE TITLE
Unable to launch 2.1.2.2 with MultiMC

### ISSUE THREAD

**Issue by Tyler799** [GTNewHorizons/GT-New-Horizons-Modpack#9553]
### Your GTNH Discord Username

Night Thastus#6641

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I attempted to the game with MultiMC after updating to 2.1.2.2.

### Crash Report

The log is here: https://paste.ee/p/SkZ4J

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
You have duplicated everything. Just look at your mods folder.

**Comment by Tyler799** [comment]
> You have duplicated everything. Just look at your mods folder.

But I ensured I deleted the relevant folders as described by the migrating steps.
