### ISSUE TITLE
Super Bus (I) ignores Input Filter settings

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9556]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

Right clicked a Super Bus (I) with a screwdriver, expected to disable the input filter

### The Reality

Message in chat appears, filter is not actually disabled

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Given that PR is not merged yet, I'm reopening this.
