### ISSUE TITLE
Overflow valve void output based on input volumes

### ISSUE THREAD

**Issue by Loreili** [GTNewHorizons/GT-New-Horizons-Modpack#9561]
### Your GTNH Discord Username

Loreili#5457

### Your Pack Version

2.1.2.0

### Your Server

Private Server

### Type of Server

Don't know

### Your Expectation

When adding an overflow cover to a machine, the output fluid should be voided if it exceeds the set threshold.

### The Reality

When adding an overflow cover to a machine, if the input fluid exceeds the configured threshold, the output fluid is voided.

This can be demonstrated using an LV Electrolyser filled with water as an input to create oxygen cells and hydrogen fluid (Circ 1). If the overflow cover is set to 64000, no fluids are voided. If the cover is set to any value below 64000, any hydrogen which is created is immediately voided.

### Your Proposal

Fluid voiding in machines should only occur based on the volume of output liquid, not the input.

Tanks should continue to void based on the only liquid inserted.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
still an ongoing issues

**Comment by chochem** [comment]
should be fixed now
