### ISSUE TITLE
galaxy space version retrograded (and 2.1.2.2qf2 shipped a broken one)

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9575]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.2qf2

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

Version numbers shouldn't go backwards.

### The Reality

GalaxySpace is no 1.1.11-GTNH but before it was 1.2.2

The one included in 2.1.2.2qf2 had the potion fix but NOT the single player fix.

### Your Proposal

When merged, Galaxy-space should be tagged 1.2.3-GTNH or maybe 1.3.0-GTNH to be safe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
GalaxySpace should never be tagged 1.2 or higher, these versions are already used by the original GS and BlesseNTumble exlplicitly said we should stick to 1.1.x

**Comment by bombcar** [comment]
we should clear out the 1.2.* tags then if at all possible

**Comment by glowredman** [comment]
I already did, there should be none left

**Comment by bombcar** [comment]
<img width="221" alt="image" src="https://user-images.githubusercontent.com/533931/150891489-c7b84ca6-ea9c-423c-83d5-a5268a9a82cc.png">
 maybe I have the power ...

**Comment by bombcar** [comment]
stupid dumb screenshot program

<img width="443" alt="image" src="https://user-images.githubusercontent.com/533931/150891546-bc9786be-697b-40e0-863d-a0100887b547.png">

**Comment by bombcar** [comment]
I did, they now gone.

**Comment by glowredman** [comment]
Okay interresting...
![Screenshot_20220125-021324.png](https://user-images.githubusercontent.com/35727266/150892203-ecf1ddca-cfd9-4a58-9f63-4c5296c881fe.png)

**Comment by bombcar** [comment]
no u 

<img width="514" alt="image" src="https://user-images.githubusercontent.com/533931/150892847-b519958e-a214-4cc1-afef-2da9377b9755.png">

**Comment by glowredman** [comment]
Let's just hope they are really gone now and don't pop up again the moment someone looks at GS from a weird angle

**Comment by bombcar** [comment]
I assume GitHub just caches tags and doesn’t care as long as they’re eventually in sync …

**Comment by repo-alt** [comment]
perhaps someone had them locally and pushed to the server
