### ISSUE TITLE
Fatal error joining world second time

### ISSUE THREAD

**Issue by Maxhy21** [GTNewHorizons/GT-New-Horizons-Modpack#9577]
### Your GTNH Discord Username

Largerthan2

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Actions

join any world, SP or MP
quit
join any world, SP or MP, not needed to be the same world
crash to menu

### Crash Report

no crash report
no info about second logging events in log
log:https://pastebin.com/pBpr2yR5

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Known issue with 2.1.2.2 - upgrade to 2.1.2.2qf2 or replace mod tweaks: http://jenkins.usrv.eu:8080/job/ModTweaker/lastSuccessfulBuild/artifact/build/libs/ModTweaker2-1.7.10-0.9.6-5-g58975c4.jar

Note that 2.1.2.2qf2 has a crash in galaxy space use http://jenkins.usrv.eu:8080/job/Galaxy-Space/129/artifact/build/libs/GalaxySpace-1.7.10-1.1.10-GTNH-3-gab44d27.jar to fix
