### ISSUE TITLE
Ethereal Shard breaks GUI

### ISSUE THREAD

**Issue by Maxhy21** [GTNewHorizons/GT-New-Horizons-Modpack#9581]
### Your GTNH Discord Username

Largerthan2#3231

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Many ways to trigger:
Search Ethereal Shard in NEI
Have Ethereal Shard in inventory(by magic grandmaster loot bags)
Looking at players with Ethereal Shard in their hand

Optfine is not installed

### The Reality

![%8RJ)4D{J%(LU74{M9~ 8(M](https://user-images.githubusercontent.com/35527077/151089258-44fdeca5-8771-4bbc-8612-b63d37443a12.png)
GUI broken there is an invisible Ethereal Shard item in quick bar

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Closed by https://github.com/GTNewHorizons/ThaumicHorizons/pull/28
