### ISSUE TITLE
Add a item lock to GT machine

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#9584]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Proposal

Add a item lock to GT machine just like the farming station in EIO or Output hatch
![image](https://user-images.githubusercontent.com/59776356/151143224-0d2569dc-0522-4fd4-9b90-703c1278bcf6.png)
![image](https://user-images.githubusercontent.com/59776356/151144230-50097f7d-ee38-4c74-8da1-181ded58dedf.png)

### Your Goal

sometimes machine will run out of resources especially or processing line or plat line after that the other slot will filled with wrong item and jam the line. 
adding a lock can prevent this from happening. 
 ![image](https://user-images.githubusercontent.com/59776356/151143183-96085bd0-c28f-4a5e-bbc5-8903bbc25b1e.png)

### Your Vision

Reduced repetitive automated line maintenance
Improve quality of life

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Just turn off multistack input mode in singles (shift right click with screwdriver in 2.1.2.0 or right click with soldering iron in 2.1.2.2) and enable limiting mode in input bus (shift right click with screwdriver).

The default value for Multi stack can be configured in `.minecraft/config/GregTech/Client.cfg` or via the config gui (e.g. https://discord.com/channels/181078474394566657/401118216228831252/928432605718802472)

**Comment by miozune** [comment]
Duplicate of #9169
