### ISSUE TITLE
This set of region files can cause visual prospecting to hang forever on first world load

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9586]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0

### Your Server

mmcc

### Type of Server

Thermos

### Your Expectation

We attempted to update to 2.1.2.0, server hung at VP 99% on overworld, and sat there using 99% CPU but doing nothing.

Trying the latest VP and adding some debug tracked down this:

[openfiles.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7942436/openfiles.txt)

Eventually every single thread would get locked on some `mca` files (though notice that it was doing dim1 and yet somehow loaded region files from other dimensions?)

### The Reality

The threads would eventually end up like this:

![image](https://user-images.githubusercontent.com/533931/151180160-c76be635-5da7-4f0b-a40c-7ce9e67de3d8.png)

and the java memory profile would finally show this:

![image](https://user-images.githubusercontent.com/533931/151180215-717fe27b-90e4-4cd3-bd6d-ed1df905e9d5.png)

I can reproduce it by dropping these region files into world/region (remove what's there, remove visualprospecting folder): 

http://schnecke.bombcar.com/random/badregion.zip (90M, if URL is broke yell at me, stupid VPS keeps commit die)

It recognizes some as "bad" but others it ends up locking on: 

```
Encountered corrupt/malformed/modified save file: /root/gtnh/server-runtime/./World/region/r.13.-40.mca
Encountered corrupt/malformed/modified save file: /root/gtnh/server-runtime/./World/region/r.-21.-40.mca
Encountered corrupt/malformed/modified save file: /root/gtnh/server-runtime/./World/region/r.-47.8.mca
Encountered corrupt/malformed/modified save file: /root/gtnh/server-runtime/./World/region/r.-15.-9.mca
Encountered corrupt/malformed/modified save file: /root/gtnh/server-runtime/./World/region/r.-22.-40.mca
Encountered corrupt/malformed/modified save file: /root/gtnh/server-runtime/./World/region/r.12.-40.mca
Encountered corrupt/malformed/modified save file: /root/gtnh/server-runtime/./World/region/r.-45.7.mca
```

### Your Proposal

My theory is it gets effectively "zip bombed" somehow and stuck in a loop forever - and we should somehow detect that situation and bomb out.

Or somehow detect "too much time on this chunk/region, assuming empty, log error, continue"

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
I've gotten it down to a 54MB zip: http://schnecke.bombcar.com/random/badregion2.zip

**Comment by hallucinogender** [comment]
Assuming this is the same as #11238:

Some testing has revealed that it is required to copy over the visualprospecting folder (contained within .minecraft) when moving a world to a new install. This information should probably be written somewhere, like the quest book, so that players are aware it is necessary.

That said, I have no idea what might fix the problem if the world is moved from a game version _without_ visualprospecting to a game version _with_ visualprospecting.
