### ISSUE TITLE
Circuit recipes in NEI showing wrong circuit

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#9587]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.1.2.2

### Your Server

private

### Your Expectation

When looking up the recipes for e.g. Processor Assemblies, it should show only recipes for them and not for the advanced circuits first.
![2022-01-26_16 46 11](https://user-images.githubusercontent.com/10967188/151196597-23634896-445a-4950-9e87-70943d2cc3d3.png)

The same happens for lv and mv circuits.

### The Reality

it is broken.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
I _think_ this was intended, to show oredicted same-tier circuits, but now that we have custom diagram, this can be removed or disabled.
Another weird behavior:
1. bookmark Advanced Circuit (HV) when opening Assembler recipe
2. bookmark Processor Assembly (also HV) when ditto
3. click bookmarked Processor Assembly, and diagram shows up (meaning recipe id lookup failed)
4. unbookmark Advanced Circuit
5. click again Processor Assembly, now desired recipe shows up

**Comment by Savallator** [comment]
I don't think it is intended, because it does not show oredicted same-tier circuits, just that specific one.

**Comment by miozune** [comment]
You have 18 pages. 10-18 pages show Processor Assembly, don't it?

**Comment by Savallator** [comment]
Yes. But the other HV-options are not in there, so it does not show all the oredicted ones. Just the original one from vanilla gt, and i think that is where the bug is coming from, because that has some kind of special code.

**Comment by miozune** [comment]
yeah, I meant not all but some
