### ISSUE TITLE
GalaxySpace and Galacticraft Licensing/Redistribution 

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#9588]
### Your GTNH Discord Username
Houston#1447
Hello developers of modpack Gregtech: New Horizons! (Expert Kitchensink Modpack)

Today I am reaching out to ask permission to use the GTNH forks of Galaxyspace and Galacticraft in my modpack
forked from GTNH: GTMEGA.

The current plans we have with the mods outside of legally using them are removing weird dependencies and changing how the galacticraft inventories work, and  worldgen upgrades for the planets themselves.

I need permission from most if not all of these users to be able to continue using GS/GC in my fork.
Glowredman, Dream, Prometheus, Kiwi, bombcar, Mitch, Glease, Spluff, AceMuffins.
Bot and I have done some contributions in the past too,  but we can't just give ourselves permission :)

**Comment by Savallator** [comment]
Really? Does the license enforce you to seek permission from each of the contributors? What license is it anyways?

**Comment by Houstonruss** [comment]
> Really? Does the license enforce you to seek permission from each of the contributors? What license is it anyways?

ARR.

GTNH was given explicit permission to use, modify, and distribute a modified version under the condition that any issues get sent to THIS git.

I'm not entirely sure *who* needs to give permissions, but this is us trying to be considerate to anyone who might object.

**Comment by boubou19** [comment]
<details>

<summary>gtnh permission</summary>

```
DreamMasterXXL08/05/2020 Hi. I am the Pack Maker of GTNH a modpack for Minecraft 1.7.10. We are using Galaxy space 1.13 version. Are you still developing on 1.7.10 version or you quit allready?
Are we allowed to continued 1.7.10 support of your mod fork it and make bugfixes? My Discord ~2000 Members https://discord.gg/EXshrPV.
My Pack https://www.technicpack.net/modpack/mcnewhorizons.677387 / https://www.curseforge.com/minecraft/modpacks/gt-new-horizons
my webpage https://www.gtnewhorizons.com/ Hope for a answer from you. Thanks DreamMasterXXL

we can do development in a private repo if this is better
DreamMasterXXLYesterday at 7:05 PM
Would be very nice to hear from you. Thanks
DreamMasterXXLYesterday at 7:32 PM
https://github.com/BlesseNtumble/GalaxySpace/issues/485

BlesseNtumbleToday at 3:05 AM
1.7.10 still developing, but not fast
You can send me bug list
And update GS, many bugfix in 1.2.14 version
DreamMasterXXLToday at 12:44 PM
Thanks for your answer. We stick with Version 1.13 because after that version you removed rocket tiers and i desinged my pack with this 8 Tiers
so i cant update realy because it isnt backwards compatible. Are there any other way we can bug fixing version 1.13 ?
BlesseNtumbleToday at 12:49 PM
1.1.x not supported and no have source code
DreamMasterXXLToday at 12:50 PM
you mean you not have you own source code anymore on this old version ?
BlesseNtumbleToday at 12:51 PM
Yes, after 1.2.0 addon have new source
DreamMasterXXLToday at 12:56 PM
are we allowed to decompile the code and work on it. I can do a private Git repo but i want to ask you for first for permission.
Wold be very nice if we can do it :slight_smile:
We allready got permission to change galacticraft by mod devs
BlesseNtumbleToday at 12:57 PM
Try it
DreamMasterXXLToday at 12:58 PM
so permission granted?
BlesseNtumbleToday at 12:58 PM
But i dont support modification version
DreamMasterXXLToday at 12:58 PM
issues goes in my issue tracker
so we responsible for the repo
Thanks for Permission.
BlesseNtumbleToday at 12:59 PM
Permission only for your pack
DreamMasterXXLToday at 1:00 PM
ok thanks and sure only for my pack
Git repo must be private or public ?
BlesseNtumbleToday at 1:00 PM
And yes, use private please
DreamMasterXXLToday at 1:01 PM
sure
```

</details>

**Comment by glowredman** [comment]
Permission granted for all modifications I made, undet the condition that we are able to use your modifications to GC/GS aswell.

**Comment by mitchej123** [comment]
> GTNH should license their changes if possible...

We can't.  We're bound by the license and permission grants by the upstream author and need to respect their wishes.  We've changed licenses to LGPL for everything we legally can :)

**Comment by mitchej123** [comment]
> Permission granted for all modifications I made, under the condition that we are able to use your modifications to GC/GS aswell.

Same here.  As discussed this is only for our modifications, you would still need permissions from upstream to use the base.

**Comment by bombcar** [comment]
> Permission granted for all modifications I made, under the condition that we are able to use your modifications to GC/GS aswell.

Same here as above.

**Comment by Houstonruss** [comment]
https://github.com/BlesseNtumble/GalaxySpace/issues/565

Waiting on Galaxyspace devs to respond now.
