### ISSUE TITLE
singleblock miner (HV) not working on Mars

### ISSUE THREAD

**Issue by Masztufa** [GTNewHorizons/GT-New-Horizons-Modpack#9592]
### Your GTNH Discord Username

Masztufa#7816

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The miner works as expected

### The Reality

The miner has power, mining pipes and an empty output slot (also set to output on the top side into an empty compressed chest), yet it fails to do an operation

video:
https://user-images.githubusercontent.com/55253786/151235256-c60e422c-3b88-4703-ac39-f9dc7ff0b427.mp4

Also tried: break+replacing the miner; quit+rejoin; HV gen feeding it; removing the chest above
none of these worked

Not sure if it actually has to do with Mars or not though; the same setup worked fine in the nether in 2.1.2.1

### Your Proposal

the singleblock miners would work on other planets

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9549 - may be fixed in 2.1.2.2qf2
