### ISSUE TITLE
Gregtech ignores use_machine_metal_tint config

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#9599]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

GTNH 2.1.2.2QF2

### Your Server

solo

### Your Expectation

I don't like the look of machines with the metal tint on, so I disable it on the config : 
in config\GregTech\GregTech.cfg line 163 `B:use_machine_metal_tint=false`

I expect my machines to not have the metal tint

### The Reality

They do have the metal tint

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Jimbno** [comment]
still doesn't work in version 2.1.2.4-25-pre

**Comment by YannickMG** [comment]
Is there a reason why setting the Machine Metal color to white isn't good enough?

What's happening right now is that this config is being overridden by the machine color config, so the simplest fix is to remove the use_machine_metal_tint config entirely in favor of the color modulator.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/5321549/183265567-5e91e3d0-4b79-4ebd-8478-30238651c279.png">

<img width="405" alt="image" src="https://user-images.githubusercontent.com/5321549/183265557-e3f4ac73-c172-41a2-80d0-a9cde931ce1e.png">
