### ISSUE TITLE
Make OpenComputers Condit API

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#9600]
### Your GTNH Discord Username

John S#7565

### Your Pack Version

2.1.2.1

### Your Proposal

I suggest to implement Api to make possible robots to interact with conduits.

### Your Goal

It's important when you need setup something like another one Circuit Assembly line which is have absolutely identical pattern, but you need to set separate settings for all inputs individually.

### Your Vision

Api should contain acces to "buttons" in conduit interface to set all settings. And if that possible to have acess filter slot in item conduit interface, and set fluid filter for liquid conduit. 
ps: if that possible also to set up a item filter even wit use of the database.

That would be absolutelly great because conduits is the best option for things transportation.
Thanks in advance.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
Well, Robot API is kind of non-extensible, so the only proper way to do that is to add yet another upgrade. Something like "Configurator Upgrade". (Generic enough name, so that it's API might logically be extended to deal with other similar tasks, where player is using a GUI.)

**Comment by repo-alt** [comment]
> ...to have acess filter slot in item conduit interface

You mean - to add/remove filter item from the robot inventory, not just read/change filered items in the filter itself?

**Comment by Retster** [comment]
As always requested features implementation are the best of the best. Thank you very much!
