### ISSUE TITLE
Inaccurate Cadmium quest book text.

### ISSUE THREAD

**Issue by lordclips** [GTNewHorizons/GT-New-Horizons-Modpack#9601]
### Your GTNH Discord Username

LordClips#3173

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Cadmium's LV quest (ID: 623) inaccurately displays text implying you can centrifuge Rare Earth to get Cadmium at that stage of the quest book. This is not possible, as Rare Earth's recipes were changed and the quest book was not changed to reflect this.

This also affects newer versions of 2.1.2.2, as noted by others in the GTNH discord server. Discussion starts here:

https://canary.discord.com/channels/181078474394566657/234936569360809996/935778556062081054

### The Reality

This isn't exactly game breaking, nor really a bug (though it is misleading and made me waste a solid 30-40 minutes confused) but while it is still very possible to get Cadmium via other means, the inaccuracy could still cause confusion.

### Your Proposal

Change the Cadmium quest (ID: 623) to reflect the Rare Earth changes. This had already been proposed in an issue, however it was closed and subsequently ignored. See: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9168

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordclips** [comment]
Also quick note, the issue was closed and then the reply made, which may have been why it was ignored. Did not want to imply the issue itself was ignored altogether. Wording mistake on my end.

**Comment by lordclips** [comment]
Closing. Corrected in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9756

**Comment by Dream-Master** [comment]
@lordclips this pr was not merged. The Author remove the branch or/and the repo

**Comment by lordclips** [comment]
_Now_ it is merged as of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9759
