### ISSUE TITLE
Assembly line constantly updates TecTech data sticks

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#9606]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Inserted datasticks of items that were researched in a TecTech research station into the data hatch of the assembly line. Sticks should update only if recipe has changed.

### The Reality

Datasticks are constantly being updated (about every 5 seconds), you can see the tooltip changing. This happens for sticks that contain recipes with oredict entries, such as UHV conveyor which accepts both styrene-butadiene rubber plates and silicone rubber sheets in its recipe.

### Your Proposal

Have it update once but not cycle constantly due to oredicted items.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
This is so annoying. Let's hope this is the last of these 🤦‍♂️

**Comment by GTNH-Afx237v7** [comment]
I’ll let you know if I find sth else ;)
