### ISSUE TITLE
Different recipes for creating a Heat Vent

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9608]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Proposal

The recipes for creating Heat Vent have different components in the workbench and in the assembler. Iron bars are needed in the workbench, and steel bars are needed in the assembler.

![image](https://user-images.githubusercontent.com/46845681/151599811-5bf21c08-0c1b-4d74-8b28-098001717fd8.png)
![image](https://user-images.githubusercontent.com/46845681/151599833-48768209-41de-4efc-a92a-7a324cb09df9.png)

### Your Goal

Make the recipes the same. For example, both the workbench and the assembler use steel rods

### Your Vision

In my opinion it is better if there are the same recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I believe this was fixed in 2.1.2.2

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/151619630-2384b529-309b-4b97-8c4a-c663f0bb863d.png)

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/259
