### ISSUE TITLE
Different recipes for creating a Advanced Heat Vent

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#9609]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.1.2.0

### Your Proposal

Recipes for creating Advanced Heat Vent in the workbench and in the assembler are different. In a workbench, it can be made only from industrial diamond, and in an assembler from ordinary or industrial.

![image](https://user-images.githubusercontent.com/46845681/151600726-18d7ec41-71fa-4a4a-8a0b-7b7dc49ed9fd.png)
![image](https://user-images.githubusercontent.com/46845681/151600751-4f601a84-77b1-445d-9796-03f15a71f4e6.png)

### Your Goal

Make the recipes the same. For example, both in the workbench and in the assembler, both conventional and industrial diamond can be used to create an Advanced Heat Vent

### Your Vision

In my opinion it is better if there are the same recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/259
