### ISSUE TITLE
Change Wings Slow Fall So That It Stops Fall Damage

### ISSUE THREAD

**Issue by BlueTRaven** [GTNewHorizons/GT-New-Horizons-Modpack#9613]
### Your GTNH Discord Username

BlueRaven#6969

### Your Pack Version

2.1.2.1

### Your Proposal

Change all wings so that slow fall immediately nullifies any fall damage you may have taken.

### Your Goal

Currently, the slow fall feature of wings (holding crouch while falling) does not stop fall damage. Fall damage appears to be based off the highest point in your entire flight path or maybe the duration the player has spent flying.
To verify:
- Equip wings. I haven't tested with any aside from nanosuit wings, but they likely exhibit the same behavior.
- Jump into the air.
- while falling and before hitting the ground, hold crouch. Hold the slow fall until you touch the ground.
- Verify that you take damage.
Unfortunately, this makes the wings rather useless; it's very hard to jump up to somewhere without going flying high into the air. You might think this wouldn't be a problem with something that nullifies fall damage, such as the nanosuit boots of the traveler, however and this is partially true; the nanosuit boots of the traveler do nullify the fall damage. However, they also take an exorbitant amount of energy damage from even short flights into the air. In particular I had a lot of trouble with the end because I would fly to one island and suddenly my boots were at half durability from full.

### Your Vision

Currently, the wings are very useless. This would make them slightly more useful. And would reduce the amount of times I have to charge my boots.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
This would be nice and add a bit of *skill* - if you just fall down you take the damage, but if you carefully *land* you do not.

I have a wireless charger in my base *solely* for this reason, as the boots discharged way too fast.

**Comment by staticvariablejames** [comment]
This is still an issue from 2.1.2.3qf. Of the four wings provided by Electro-Magic Tools, only the Quantum Wings seems to negate fall damage, and the damage negation happens in any instance. For comparison, the Thaumostatic Harness, craftable at MV, negate fall damage, thus behaving better than the nanosuit wings in this regard.

**Comment by Oculatus** [comment]
Wings still do not stop fall damage. It is based on through testing the highest Y value achieved and then damage is calculated on the block you touch the ground on, not the one taken off from, regardless of if you slowed your fall or not. The wings also are supposed to reduce fall damage, which in turn should reduce the amount of power nano boots need to use to negate the rest, this is also not working. You receive the same amount of damage with wings on or off.
