### ISSUE TITLE
Divide by Zero Exception when scrolling on NEI materials page

### ISSUE THREAD

**Issue by Joekeen03** [GTNewHorizons/GT-New-Horizons-Modpack#9617]
### Your GTNH Discord Username

Joekeen#4621

### Your Pack Version

GT New Horizons-2.1.2.0-1.7.10

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Was looking up ingredients for Stargate, ended up doing a lookup for Chromium Dioxide.
It opened up the new materials NEI tab (where it shows all the different processing for it), I tried to drag the scroll bar down, and it crashed with a divide by zero error.

### Crash Report

[crash-2022-01-28_23.08.59-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7963169/crash-2022-01-28_23.08.59-client.txt)
[crash-2022-01-28_23.27.38-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7963175/crash-2022-01-28_23.27.38-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@D-Cysteine can you check this issue? maybe its fixed already in a newer version

**Comment by D-Cysteine** [comment]
Thanks for reporting this! Seems like a corner case issue that only happens if your Minecraft window is exactly the right size. Should be fixed by [v1.4.4](https://github.com/D-Cysteine/nei-custom-diagram/releases/tag/v1.4.4).
