### ISSUE TITLE
Suggestion to add Glenn's Gases Mod

### ISSUE THREAD

**Issue by PlasmaFox256** [GTNewHorizons/GT-New-Horizons-Modpack#9619]
### Your GTNH Discord Username

PlasmaFox#3622

### Your Pack Version

2.1.2.2QF2

### Mod Name

Glenn's Gases

### The Mod to Add

Glenn's Gases is a mod that adds several gases to the game. Some of them are useful and some of them are dangerous. Gases can generate naturally in cave pockets or can come out of broken ores such as coal ect.
The mod adds:
the ability to transport gases,
use some gases for RF generation,
makes caving more dangerous so players will have to be more careful not to get poisoned or blown up,
adds some protective items and gear against gases.
Here is the official website for this mod:
https://jamieswhiteshirt.com/minecraft/mods/gases/

### Your Reason

This mod adds a bit of variety to caving and mining. It makes ore digging a bit more fun and strategic. The nether will be cooler as well thanks to some nether exclusive gases like the electric clouds. The ability to generate RF from some gases and well designed piping that this mod adds, will add more tech progression and opportunity. I talked to Dream about this and he is ok with it, even experimented with the addition of this mod a long time ago.

### Preliminary Investigation

This mod loads up into GTNH with no problem.
This mod has a nice config file so we can add gases to some gt5 ores ect.
We can freely modify this mod as the author allows it.
Some recipes and features will need to be configured for balanced (THERE IS NO ESCAPE FROM GREG).

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Steelux8** [comment]
The oregen in this pack is very different from vanilla, and auto miners are given incentive from early tiers. Additionally, we already have plenty of gases that can be used for power, there are long processing chains for this sort of thing. I don't see a good reason to add this, personally.

**Comment by bombcar** [comment]
If the mod works “out of the box” we can certainly add it to the additional mods page with a note for now.

**Comment by YannickMG** [comment]
The main interest I see for gases is pollution related stuff, potentially.

**Comment by PlasmaFox256** [comment]
I don't think we NEED this mod but it could be cool, i'm totally fine without it.

**Comment by Ethryan** [comment]
I'm against this, unless an implementation like the Gases simliarly to how GT6 does it can be found.

In my opinion this would only add more confusion and hard to merge fluid conflicts than what it's worth.
