### ISSUE TITLE
Request Feature: Searching "Complete" in the questbook gives a list of completed quests with rewards unclaimed

### ISSUE THREAD

**Issue by Koalacards** [GTNewHorizons/GT-New-Horizons-Modpack#9624]
### Your GTNH Discord Username

Koalacards#4126

### Your Pack Version

2.1.2.0

### Your Proposal

The addition of the search feature in the questbook is amazing, but it would be super cool if there were some keywords that gave easier access to a list of some quests. One idea I had was the keyword "complete", where the book would then show all of the "blue" quests (the quests that you completed but did not get the rewards from)

### Your Goal

It would just be a nice QOL, as finding all of the blue tasks that I have completed randomly (especially in a tier like LV which is almost all green) for every tier is quite annoying.

### Your Vision

It would make it easier to bulk-accept rewards after a while, and opens the door for a lot of possible keyword searches to make the questing experience better/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
There's a "claim all rewards" button on the left but I don't think it works with quests with reward choice.
