### ISSUE TITLE
Remove extraneous ore spam from NEI

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9632]
### Your GTNH Discord Username

Colen UwU

### Your Pack Version

2.1.2.1

### Your Proposal

Remove variant ores from NEI, these serve no real purpose and take up a shit load of pages eg,

<img width="551" alt="Screenshot 2022-01-30 at 04 24 44" src="https://user-images.githubusercontent.com/54497873/151686583-5675c6f3-ada6-4c36-8b88-598b100d1da8.png">

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
lets do that inside gt code
