### ISSUE TITLE
Every recipe from "Floral Cultivation" makes Mystical White Flower regardless of the dye used

### ISSUE THREAD

**Issue by ZorbaHerbalist** [GTNewHorizons/GT-New-Horizons-Modpack#9636]
### Your GTNH Discord Username

ZH#7279

### Your Pack Version

2.1.2.2QF2

### Your Server

private

### Type of Server

Single Player

### Your Expectation

Trying to craft Botania flowers in Infusion Altair.

### The Reality

Every recipe from "Floral Cultivation" makes Mystical White Flower regardless of the dye used

### Your Proposal

Recipes needs fixing?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by combusterf** [comment]
Note to self: the Thaumcraft API does weird things. https://github.com/GTNewHorizons/Botanic-horizons/pull/4
