### ISSUE TITLE
Circuit Oredict is broken as HELL

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#9640]
Circuits have every time a problem to be oredicted in recipes. (Tier like Basic, Good, Advanced etc.)
In Assemblers, Circuit Assemblers recipes for example.
We need to fix that very urgent.

**Comment by boubou19** [comment]
it seems like when there is more than one oredicted circuit in a recipe, it doesn't generate all the permutations.

**Comment by YannickMG** [comment]
When did this start happening?

**Comment by Dream-Master** [comment]
guess it was never working 100%. But as we start to add tiers after Luv so i guess more than 5 years ago.

**Comment by draknyte1** [comment]
The way it’s implemented is super hacky cause machines don’t actually support OD…

**Comment by Dream-Master** [comment]
Any idea how to code this less hacky that it can be used? Otherwise we can remove oredict on circuits.

**Comment by bombcar** [comment]
The real solution is fixing machines not allowing oredict on recipes, as it is now we have hacks that try to generate "all possibilities" but when you have more than one oredict thing it's going to go sideways.
