### ISSUE TITLE
NEI might have a memory leak

### ISSUE THREAD

**Issue by YannickMG** [GTNewHorizons/GT-New-Horizons-Modpack#9641]
### Your GTNH Discord Username

Yannick#5937

### Your Pack Version

2.1.2.2QF2

### Your Server

SP

### Type of Server

Vanilla Forge

### Your Expectation

No performance impact to using catalysts.

### The Reality

After using the Usage Recipes feature a number of times in NEI in the full pack with `NotEnoughItems-1.7.10-2.2.0-GTNH.jar`, I start getting frequent GC cycles freezing the game which quickly becomes unplayable.

### Your Proposal

Reproduce, profile & fix as appropriate.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Should be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/909

**Comment by YannickMG** [comment]
That's a change to be made very carefully, as it's very easy to come to depend on the existing behavior in handlers.
