### ISSUE TITLE
Keep ghost items when creating AE2 patterns

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#9642]
### Your GTNH Discord Username

KiloJoel#3044

### Your Pack Version

2.1.1.2

### Your Proposal

There should be an option for left click to not "lose" the ghost item when left clicking it in the grid of a pattern terminal.

In GTNH 2.1.2.0 and earlier (NotEnoughEnergistics 1.0.0), adding items in the grid with left click will keep the ghost item in hand. I like this

In GTNH 2.1.2.1 (NEE 1.3.4)+, left click "drops" the item and middle click must be used instead to place multiple. I don't like this

I would like the functionality to be either reverted or an option to use it the other way, since NEE version is forced by the server.

(I am aware there is also a bug of placing only 1 item rather than the stack size provided by nei, this is not what I'm talking about)

### Your Goal

For me and I'm sure others, repeatedly middle clicking to add multiple of an item to a pattern is uncomfortable. It's also not intuitive for me at least.

### Your Vision

Retains user-friendliness from previous versions

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vfyjxf** [comment]
For the stack size issue, you can set useStackSizeFromNEI to true in NotEnoughEnergistics.cfg, and i added an option to set whether to keep ghost items after a click. See [here](https://github.com/vfyjxf/NotEnoughEnergistics/blob/main/src/main/java/com/github/vfyjxf/nee/config/NEEConfig.java#L79).

**Comment by slprime** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9547

**Comment by slprime** [comment]
https://github.com/GTNewHorizons/neiaddons/pull/2

This PR shows how I intended it to work

**Comment by vfyjxf** [comment]
> [GTNewHorizons/neiaddons#2](https://github.com/GTNewHorizons/neiaddons/pull/2)
> 
> 这个PR显示了我打算如何工作，它在更改之前工作 NotEnoughEnergistics 它这个提交（[GTNewHorizons/NotEnoughEnergistics@a7919fe](https://github.com/GTNewHorizons/NotEnoughEnergistics/commit/a7919fe70760028ff7264b2e973de011dfc23747))

I provide a configuration to turn off nee's nei drap support. and give it to NEIAddons when they are available. See [this](https://github.com/vfyjxf/NotEnoughEnergistics/commit/8e481998399acb859174cd35f1815eaa52a3632a)

**Comment by slprime** [comment]
![image](https://user-images.githubusercontent.com/31038811/151788420-e0532df7-2fa5-4044-888a-68b9d5b825a6.png)

It always `true` if `NEIAddons` exists. maybe you wanted to write `!Loader.isModLoaded("NEIAddons")` or did I miss something?

**Comment by vfyjxf** [comment]
> ![image](https://user-images.githubusercontent.com/31038811/151788420-e0532df7-2fa5-4044-888a-68b9d5b825a6.png)
> 
> It always `true` if `NEIAddons` exists. maybe you wanted to write `!Loader.isModLoaded("NEIAddons")` or I miss something?

I mean to leave the NEI drag to NEI Addons when NEI Addons exist

**Comment by slprime** [comment]
If NEIAddons exists then you code always work, but need work only when `enableNEIDragNDrop == true` or NEIAddons dosn't exists

**Comment by vfyjxf** [comment]
> 如果NEIAddons存在，那么你的代码总是有效的，但只有当NEIAddons不存在时才需要工作`enableNEIDragNDrop == true`

Sorry, I did miss a "!"

**Comment by KiloJoel** [comment]
> For the stack size issue, you can set useStackSizeFromNEI to true in NotEnoughEnergistics.cfg, and i added an option to set whether to keep ghost items after a click. See [here](https://github.com/vfyjxf/NotEnoughEnergistics/blob/main/src/main/java/com/github/vfyjxf/nee/config/NEEConfig.java#L79).

I just tested the new version 1.3.9. The item is retained in hand - thank you! - There are some issues though.

Left click places twice the amount in hand and doesn't increase amount when clicking again
<a href="https://gyazo.com/91e2b1338546b366e1c58d0750078c03"><img src="https://i.gyazo.com/91e2b1338546b366e1c58d0750078c03.gif" alt="Image from Gyazo" width="278"/></a>

Middle click placed the correct amount and increases when clicking again. This is the functionality that I would like left click to have
<a href="https://gyazo.com/d51933fc25d08e1981b91341050a0492"><img src="https://i.gyazo.com/d51933fc25d08e1981b91341050a0492.gif" alt="Image from Gyazo" width="272"/></a>

Right click functionality seems identical to left click


My ideal functionality would be:
Left click - increase stack size by amount held
Right click - increase stack size by 1
Middle click - drop ghost item without placing it

This left/right click functionality would make it consistent with how real (not ghost) items are placed in the grid.

**Comment by vfyjxf** [comment]
> > For the stack size issue, you can set useStackSizeFromNEI to true in NotEnoughEnergistics.cfg, and i added an option to set whether to keep ghost items after a click. See [here](https://github.com/vfyjxf/NotEnoughEnergistics/blob/main/src/main/java/com/github/vfyjxf/nee/config/NEEConfig.java#L79).
> 
> I just tested the new version 1.3.9 (in GTNH 2.1.2.1). The item is retained in hand - thank you! - There are some issues though.
> 
> Left click places twice the amount in hand and doesn't increase amount when clicking again [<img alt="Image from Gyazo" width="278" src="https://camo.githubusercontent.com/ef542584ba8a18cda8c0969cf24dc40ddbffb927f269e8f701813b22889c5549/68747470733a2f2f692e6779617a6f2e636f6d2f39316532623133333835343662333636653163353864303735303037386330332e676966">](https://gyazo.com/91e2b1338546b366e1c58d0750078c03)
> 
> Middle click placed the correct amount and increases when clicking again. This is the functionality that I would like left click to have [<img alt="Image from Gyazo" width="272" src="https://camo.githubusercontent.com/8f875a1595f7323039a94d28262f6af1a47759478b48cce1a7a5403c9f29c657/68747470733a2f2f692e6779617a6f2e636f6d2f64353139333366633235643038653139383162393133343130353061303439322e676966">](https://gyazo.com/d51933fc25d08e1981b91341050a0492)
> 
> Right click functionality seems identical to left click
> 
> My ideal functionality would be: Left click - increase stack size by amount held Right click - increase stack size by 1 Middle click - drop ghost item without placing it
> 
> This left/right click functionality would make it consistent with how real (not ghost) items are placed in the grid.

Like this one?

![dev14](https://user-images.githubusercontent.com/42764413/151827979-d270bd83-0e06-4505-aeac-529dec974a13.gif)

**Comment by KiloJoel** [comment]
Yes that looks good to me
