### ISSUE TITLE
Machines will disappear during lag if you switch tools before server catches up

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9647]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0

### Your Server

mmcc

### Type of Server

Thermos

### Your Expectation

Wrenching a machine or tank shouldn't destroy said machine/tank/block.

### The Reality

If the server lags between when you start wrenching and after you finished, *and* you switch tools before the server checks, the machine/block gets destroyed, just as if you had "mined" it with the wrong tool.

Best way to reproduce it is start wrenching a block (something that will take some time) and then have someone trigger a server-save, and switch tools before the server comes back from the savelag.

### Your Proposal

Change the code to either check tool *before* and not check again, or just make it so the "wrong tools" take basically infinitely long or something. Too many super tanks have been lost.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
This happens on non-Thermos servers, and even different modpacks running 1.12 - I suspect this is an underlying Minecraft bug, not sure what can be done about it.

**Comment by YannickMG** [comment]
Same underlying problem as for explosions, if it can't be avoided the punishment should be less harsh.

Dented machines should drop when broken with the wrong tool.
