### ISSUE TITLE
Smelting recipe Apiarist DNA Sequence (Genetics)

### ISSUE THREAD

**Issue by JustBenji** [GTNewHorizons/GT-New-Horizons-Modpack#9648]
### Your GTNH Discord Username

Benji#0586

### Your Pack Version

2.1.2.0

### Your Server

Private Multiplayer

### Type of Server

Open To LAN

### Your Expectation

Put the Apiarist DNA Sequence in Furnace. Smelting recipe starts, Receive blank sequence.

### The Reality

Able to put the Apiarist DNA Sequence in the Furnace. Furnace does not start.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/96138378/151868559-f4102642-8ddf-4c18-898b-61136df6bbfb.png">

### Your Proposal

Make it work?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Duplicate of #9203
