### ISSUE TITLE
Holding items causes screen to become one solid color

### ISSUE THREAD

**Issue by Ixumi** [GTNewHorizons/GT-New-Horizons-Modpack#9653]
### Your GTNH Discord Username

Synz#3336

### Your Pack Version

2.1.2.0

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Trying to launch the pack with no extra mods installed. Expecting a properly running game.

### The Reality

Launch modpack and whenever an item is held, my screen turns into one solid color. Also, some textures are very bugged as well.

![Screenshot (16)](https://user-images.githubusercontent.com/43588215/151899423-4a8d3084-6d43-4e9a-bd15-4a1bb4d08a37.png)
![Screenshot (18)](https://user-images.githubusercontent.com/43588215/151899425-4ee51ab6-9c17-4994-be0f-c91ea08df9a2.png)
![Screenshot (15)](https://user-images.githubusercontent.com/43588215/151899427-5d0c20ab-56b9-4085-81aa-29e6731c4b02.png)

### Your Proposal

Attempt to fresh install modpack/Java/Launcher? Try new launcher? Updated drivers already and tried installing GraalVM Java 8.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
Please provide a fml-client-log to go with this.

**Comment by Ixumi** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7975773/fml-client-latest.log)

**Comment by mitchej123** [comment]
Have you tried w/o your resource pack?

**Comment by Ixumi** [comment]
Yea, I've tried without the resource pack installed, I've even tried using an entire new launcher (I usually use MultiMC, I tried using Technic and I get the same issue.)

**Comment by Ixumi** [comment]
With further testing, I've noticed it also happens in vanilla minecraft as well. I've tried uninstalling Java 8 and reinstalling and that hasn't fixed the issue.

**Comment by Ixumi** [comment]
Problem solved! I use a RTX 3060, but I guess my computer wanted to use the integrated graphics instead. So I went into my control panel and forced the computer to use the Nvidia graphics processor instead of the integrated graphics.
