### ISSUE TITLE
Coke Oven Deleting Cells

### ISSUE THREAD

**Issue by ottothielicke** [GTNewHorizons/GT-New-Horizons-Modpack#9654]
### Your Pack Version

2.1.2.0

### Your Server

private server

### Your Expectation

When placing any amount of empty GregTech Cells into a Railcraft Coke Oven the cells are filled and then deleted or dropped on the ground. When only one cell is used, more often than not the cell just disappears. When more than one cell is used, some are dropped but most are deleted.

### The Reality

GregTech Cells used in Railcraft Coke Ovens are deleted on use

### Your Proposal

Output Gregtech Cells filled and stacked into the output slot

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kythre** [comment]
I am also having this issue in single player with IC2 cells. I found this before creating a new issue
