### ISSUE TITLE
When I look at the sky, leaves or dirt, the whole screen will change to the corresponding color

### ISSUE THREAD

**Issue by SkyMoon4106** [GTNewHorizons/GT-New-Horizons-Modpack#9655]
### Your GTNH Discord Username

SkyMoon#7497

### Your Pack Version

2.1.2.1

### Your Server

single player

### Your Expectation

Expecting a properly running game.

### The Reality

After creating a map, I entered the game. As a result, my game screen was all solid colors. I could see other colors when I moved the viewing angle. I believe those colors are the colors of the sky, dirt, and leaves.
Sometimes it will change back to the normal screen (it doesn't last long, and when you change the angle of view, it will change back to the picture with only solid color
![unknown (33)](https://user-images.githubusercontent.com/67361456/151960786-d8b70d8c-a555-4a3e-b658-3c70fbe1c46e.png)
s

### Your Proposal

Hope there is a way to fix this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ixumi** [comment]
If you can, press Q to drop the item in your hand. I am currently having this issue and it fixes itself when I don't have an item in my hand.

**Comment by bombcar** [comment]
see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9653#issuecomment-1027356600
