### ISSUE TITLE
Alchemy Catalyst doesn't work with Prismarine

### ISSUE THREAD

**Issue by ZorbaHerbalist** [GTNewHorizons/GT-New-Horizons-Modpack#9656]
### Your GTNH Discord Username

ZH#7279

### Your Pack Version

2.1.2.2QF2

### Your Server

private

### Type of Server

Single Player

### Your Expectation

Trying to craft Prismarine in Mana Pool set above the Alchemy Catalyst

### The Reality

Mana Quartz is crafted.
![image](https://user-images.githubusercontent.com/22648885/151982996-cf898414-1e63-4f0d-9c66-39a7526bfd2f.png)

### Your Proposal

Fix recipe. Maybe related with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9636

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by OrderedSet86** [comment]
This completely blocks Botania progression at the moment and should be upgraded to bugMajor. Runic altar is uncraftable as long as prismarine shards are unobtainable, which means no recipes involving runes are possible.
![image](https://user-images.githubusercontent.com/88752681/154820958-43b7ff39-7aac-4985-8874-a782e84e533e.png)

**Comment by OrderedSet86** [comment]
Simple fix suggested by @PolkageistHS : make the prismarine craft use certus quartz instead. Then no recipe conflict to fix.

**Comment by LewisSaber** [comment]
Charged certus i would suggest

**Comment by PolkageistHS** [comment]
That doesn't solve the bigger issue of why it's not recognizing the alchemy catalyst, unless that's vanilla Botania behavior and there shouldn't be any shared components in the recipes like this?

**Comment by combusterf** [comment]
The affected recipes are actually vanilla botania:
- quartz -> mana quartz (no catalyst)
- quartz -> 2x quartz (conjuration catalyst)
- quartz -> prismarine (alchemy catalyst)
