### ISSUE TITLE
More advanced steel production post HV using Pig Iron.

### ISSUE THREAD

**Issue by lordclips** [GTNewHorizons/GT-New-Horizons-Modpack#9659]
### Your GTNH Discord Username

LordClips#3173

### Your Pack Version

2.1.2.1

### Your Proposal

Steel production using pig iron is common and also very efficient when done en masse. The goal here is to reward a slightly more complicated production line for steel post HV to aid in the production of products using steel as well as Tungstensteel for IV. There are a few ways to go about this which I'll cover, but earlier conversation made me feel it important to note:

The goal here is to not touch the early game. The point is to give an incentive to use a slightly more complicated production line later in the game to produce *more* steel *faster* and for less input products. Ultimately, this also give a normally useless product (pig iron) a genuine and reasonable goal as well as making it so that a basic steel setup isn't simply two machines in a row with some oxygen but instead a slightly larger line that give significantly more yield for the same amount of resources over time.

There are a few ways that this can be handled, of which I will propose below:

1. Blast furnace 1 iron (with oxygen) -> 4 Pig Iron -> Macerator -> Blast furnace (with oxygen) -> Steel

This give a yield of 4 steel for 1 iron and 2 buckets of oxygen. This costs more oxygen, but significantly less iron, and quadruples the amount given from the blast furnace in return for the slightly more complicated series.

2. Blast furnace 1 iron -> 1 bucket molten Pig Iron -> Fluid Solidifier (250 mb per ingot) -> Blast Furnace (with oxygen) -> Steel

This is slightly more complicated with the same amount of machines but with less oxygen and less iron, with the same yield.

3. Blast furnace 1 iron (with oxygen) -> 1 bucket molten Pig Iron -> Fluid Solidifier (250 mb per ingot) -> Macerator -> Blast Furnace with 1 charcoal (with oxygen) -> Steel

This is the most complicated line, requires Charcoal (realism), and also requires 4 machines instead of 3, and will probably hurt a lot of people's souls. To be fair, this one is the least likely to be even considered for implementation, even for me, as the charcoal requires extra infrastructure (though to go on a tangent, someone had mentioned how incentivizing charcoal requires extra infrastructure that induces lag, but on the other hand there are already steel blast furnace recipes that let you smelt steel en masse that also use charcoal, so either that was forgotten or ignored, but there is already incentive to do that regardless) but is the closest you'd get to a "Real" setup. I'll grant, though, that realism isn't fully the packs goal considering we'll have plant magic soon and also you become a schizo with TC, hence why none of the other potential lines have it.

### Your Goal

Incentive. Also, just as a side thing. Steel isn't nearly as required in other ages as it is in LV, nor is it as difficult to retrieve, but having an incentive to create a somewhat more complex line for significantly more yield not only lines up with how the pack is structured to begin with, it offers a way to make it even cheaper as you continue on your journey to higher and higher tier machines. Steel gets fairly cheap fairly quick, but I see no reason not to make it cheaper while also having the side effect of making a currently useless material actually somewhat useful in a reasonable manner. If put after completing or around the completion of HV going into EV, it actually becomes quite useful if you want to produce a ton of IV machines as well, since Tungstensteel also requires, well, Steel, and it will ultimately cost you significantly less iron to make IV machines as well.

### Your Vision

I think it would encourage people to think more about the infrastructure of older materials rather than passing the age and instantly letting 2 machines do the job for them. It gives and incentive to delve into the more complex mechanisms of making such a material, and thus creates somewhat more creative thinking in not only the setup but the supply for it as well. Ultimately, I think a slightly more realistic line for steel production a bit later into the game can really help with such an idea, and wouldn't really hurt much if at all any part of the game that is currently considered quite solidly defined (LV -> HV)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
So, maybe instead of adding it to the EBF, why not make a specialized blast furnace multi that specifically does this one thing? sort of like how the chemplant only makes a few things, but how they are pretty vital I guess?

**Comment by lordclips** [comment]
Pig Iron and Steel, from what I understand, are both actually made in blast furnaces, though you could argue that a specialized furnace for bulk producing pig iron could make some sense to lower the power and time cost

**Comment by Steelux8** [comment]
I think it'd be better in the EBF, we already have a lot of multis without much use to make a new one. Either put it in the EBF or something similar to it, although the EBF substitutes just take recipes from it.

**Comment by lordclips** [comment]
Yeah. Doing two EBFs might be a bit tedious but it negates the need for a multiblock dedicated to a single objective. It's also somewhat part of the extra layer of realism goal, granted some liberties can be taken in that affect.

I will note that another way you *could* do this and lower it down to 1 EBF is to instead use an alloy smelter with a pig mold to smelt iron into 4 pig iron as well. Takes away some realism but it makes it a bit easier to set up and manage, though I prefer the two EBF setup much more for numerous reasons.

**Comment by lordclips** [comment]
Im going to close this as I have done some more research and found inaccuracies in the original proposal. The current method for mass production is fairly close to the most modern way of producing steel aside from a few differences. I think it would made more sense were you to use pig iron directly into steel, as well as make a method of doing so (since Wrought Iron isnt normally turned into steel), itd almost certainly require touching a part of the early game I know doesnt want to be and really shouldnt be touched. Inaccuracy < gameplay, so this is kind of an obsolete proposal unless something comes up.
