### ISSUE TITLE
Arcane Assembler should take other scepter caps instead of just one type

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#9661]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.1.0

### Your Proposal

In other modpacks, the Arcane Assembler from Thaumic Energistics can accept different silverwood scepter caps, so instead of a thaumium capped scepter, you can use a ichorium capped silverwood scepter (not the 1000k storage though); change the recipe to use a wider range so that it actually use it.

### Your Goal

Felt kinda saddening to know that this feature is in other packs or supposedly is but isn't in GTNH, though not sure if it's a script issue or not.

### Your Vision

I'm sure many would love to minmax their Arcane Assemblers in the near end-game with ichorium wand caps or progression wise with other strong caps.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by dimondmine2** [comment]
Bump
