### ISSUE TITLE
BetterQuesting stores all quest progression info in a single JSON file - it should be per user

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9662]
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0

### Your Proposal

Currently on MMCC server we have `world/betterquesting/QuestProgress.json` which is a thirty-seven megabyte json file.

On each world-save, this entire file has to be written out, which noticeably contributes to world savelag.

### Your Goal

Reduce savelag by instead having a directory `world/betterquesting/QuestProgress/` that has UUID.json files for each player, so that only the files that apply to players who are online get saved during world save.

### Your Vision

Greatly simplify the large JSON file allowing for finer-grained backups and improved load/save times.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
It just doesn't work that way. Would take a lot of effort to refactor all these serialization code and add proper migration code.

**Comment by lordclips** [comment]
Wouldnt migration just be taking separate player jsons inside the grander progress json and sending them to their own file? It doesnt sound like that difficult a task, though it would kind of be just sitting there after some time (maybe have a migration script outside of the BQ code itself for manual migration?)

**Comment by MuXiu1997** [comment]
The player's progress is saved separately inside each quest, instead of saving it for each player

In this way, it doesn't matter if the player is online or offline

If you need to save each player's progress separately, you need to save his progress at least when he goes offline
And the serialization would need to be completely changed

This is a great idea, but it might require a lot of code changes, so I don't know if it's worth doing

**Comment by lordclips** [comment]
Im pretty sure someone already is doing exactly this and has posted images of their doing so

**Comment by MuXiu1997** [comment]
Any progress?
If not, I might want to get started

**Comment by Dream-Master** [comment]
@MuXiu1997 feel free to work on it. MAybe caht with @miozune about it. So you not work againts each other.

**Comment by MuXiu1997** [comment]
> If we mark the players whose progress has changed as dirty, wouldn't we be able to save only the progress of those players when we save?
