### ISSUE TITLE
quad fuel rod (depleted high density uranium) pops out

### ISSUE THREAD

**Issue by vveak** [GTNewHorizons/GT-New-Horizons-Modpack#9663]
### Your GTNH Discord Username

vvaster#0011

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

I put a quad fuel rod (high density uranium) into a nuclear reactor. When the fuel rod becomes depleted fuel rod, it should be in the nuclear reactor and waits for me to get it.

### The Reality

The depleted fuel rod popped out to the ground, and I didn't notice it until I lost the depleted fuel rod.
I have reproduce the bug using my backups
![1](https://user-images.githubusercontent.com/55662062/152228448-77147fbd-c1b7-4716-91c0-4db977912fb8.jpg)
![2](https://user-images.githubusercontent.com/55662062/152228462-12adb59c-9bfe-48d1-92c3-269069e4cc85.jpg)
![3](https://user-images.githubusercontent.com/55662062/152228467-69430113-49aa-419f-a5c4-f698415c0d90.jpg)
![4](https://user-images.githubusercontent.com/55662062/152228482-26ca7329-d7fb-44bf-a2dc-78a0f41d05f3.jpg)

### Your Proposal

Fix the bug above.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
@GlodBlock thoughts?

**Comment by GlodBlock** [comment]
already fixed by this https://github.com/GTNewHorizons/GoodGenerator/commit/c78e8ac6301f1e8b5ce9243eed19291fb0f20b1a
