### ISSUE TITLE
Add back Market from Harvestcraft or backport Farming for Blockheads

### ISSUE THREAD

**Issue by miozune** [GTNewHorizons/GT-New-Horizons-Modpack#9665]
### Your GTNH Discord Username

miozune#9742

### Your Pack Version

2.1.2.2-dev2

### Your Proposal

Since Market dupe was fixed in https://github.com/GTNewHorizons/harvestcraft/pull/10, we can safely add back it. Or backport [Farming for Blockheads](https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads), which has nice GUI.

### Your Goal

Gardens are relatively easy to find, but some fruits require specific biome and are hard to find. Providing ways to get desired seeds and saplings will give players incentives to make more food variation.

### Pros:
- easy to add back
### Cons:
- user-hostile GUI
![2022-02-03_14 05 52](https://user-images.githubusercontent.com/40035906/152286823-800f6ce1-37f2-4eff-8969-73b418ce5f6d.png)

### Pros:
- nice GUI to search for goods
![2022-02-03_14 06 45](https://user-images.githubusercontent.com/40035906/152286134-d7c7fbd9-8bec-449a-9ed3-7e5913197897.png)
### Cons:
- ~~All Rights Reserved~~ MIT as of 1.10
- need work for backporting

In both cases, recipe balancing is needed. Does anyone know how Market recipe used to be?

### Your Vision

Let players enjoy their daily lives.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by mitchej123** [comment]
Farming for Blockheads is MIT under 1.12 & 1.10; he switched it on the latest ports to ARR.

Interesting, I didn't realize that was a different mod and wasn't pam's market :rofl:  I'd rather have farming for blockheads

**Comment by k3nw4y** [comment]
> Gardens are relatively easy to find, but some fruits require specific biome and are hard to find. Providing ways to get desired seeds and saplings will give players incentives to make more food variation.

The coconut is hard to find early game for healing axe

**Comment by draknyte1** [comment]
Market was only removed due to a dupe which I fixed a while back. There’s no reason for it to be disabled.

**Comment by chochem** [comment]
I think there are a lot of people that would like this kind of feature. Even if it might have a 'challenging' recipe to allow for an initial exploration phase. I think the consensus might be that backport is very much preferable to the harestcraft one. I am gonna try with help wanted and see if we have any takers, I think this might be above my coding experience even though mitch says its 'not hard'. :P

**Comment by guigs4** [comment]
>I am gonna try with help wanted and see if we have any takers, I think this might be above my coding experience even though mitch says its 'not hard'. :P

I tried to tackle it but got stuck with maven dependencies/CI 

Tried following [this](https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/master/docs/porting.md#2-refining-the-fork) but I couldn't find gradle.yaml 

<sub>ps: I'm a C# dev not a Java dev so my apologies if it seems obvious</sub>

**Comment by Dream-Master** [comment]
@guigs4 can you make a pr to GTNh fork ?

**Comment by guigs4** [comment]
Sure thing!
Will do it when I get a working build if that's ok.

**Comment by Dream-Master** [comment]
@guigs4 any news on this?

**Comment by Dream-Master** [comment]
No problem just let me know when it is done. Thanks

**Comment by guigs4** [comment]
Due to both my inexperience with MC modding and some IRL stuff I'll be putting this project on hold for a while.
I have updated the [README.md](https://github.com/guigs4/FarmingForEngineers-1.7.10) to reflect the current state of the mod.

I apologize for the lack of communication.

**Comment by clarkf** [comment]
I'm not sure what the status of this is exactly, but I've filed some PR's against [guigs4's fork](https://github.com/guigs4/FarmingForEngineers-1.7.10). Hoping to get 

Is there a different/better fork I should be sending patches to? I was unable to find one under the GTNH org.

**Comment by mitchej123** [comment]
I can fork it to NH and you can redirect the PRs here.  I'd love to have this mod working, but also too many projects to handle myself :sunglasses:

**Comment by mitchej123** [comment]
@clarkf https://github.com/GTNewHorizons/FarmingForEngineers
