### ISSUE TITLE
Add crafting status button to arcane terminal

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#9667]
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.1.2.2QF2 

### Your Proposal

I mostly use the arcane crafting terminal to access my terminal, and it doesn't have any way to show how to check recipes. It would be nice to have that function on it

### Your Goal

I use a second terminal only to see how my crafting is coming along

### Your Vision

i can see, yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
If I woudn't be missing that feature myself, I would have a hard time translating that into "Add crafting status button to arcane terminal"

**Comment by maniifestantes** [comment]
english hard

**Comment by repo-alt** [comment]
I think it is possible to call crafting status GUI from the arcane terminal, but it is really hard to go back to arcane terminal GUI from the crafting status. (It is definitely impossible w/o modifying AE2 itself)
