### ISSUE TITLE
Dislocation focus turns an advanced filing cabinet into a normal one

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#9668]
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.1.2.2QF2 

### Your Server

zeta

### Your Expectation

I wanted to move my filing cabinet (advanced) with a dislocation wand focus

### The Reality

When i did so, it turned the advanced one into a normal filing cabinet.

### Your Proposal

![2022-02-03_08 55 24](https://user-images.githubusercontent.com/57275066/152338531-af372ba7-521c-449b-8727-df8207edfb78.png)
![2022-02-03_08 55 28](https://user-images.githubusercontent.com/57275066/152338537-472fe87d-b4a6-4756-8a72-a6a39f58b593.png)
![2022-02-03_08 55 31](https://user-images.githubusercontent.com/57275066/152338539-53637881-21b1-4c60-bf8f-f9f1477ddd4d.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
tbh picking up filing cabinet with a dislocation focus is dangerous (player NBT size-wise), so probably it is better to blacklist it in ThaumicTinkerer.cfg
