### ISSUE TITLE
Deny crafting EC2 components

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#9671]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.2.1

### Your Proposal

Disable craft of all liquid buses (export, import, storage) and etc.

### Your Goal

It's very bugy, but not evryone know it. Then it will be difficult to replace them on a developed base, which will only lead to a drop of the GTNH. 

Instead of storing through EC2, you need to direct players to the right path, which does not lag, does not dupe and does not drop tps - storing in cells

### Your Vision

TPS +1000%
player drops -1000%

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Colen** [comment]
Long term EC2 is going in the bin, it's a buggy mess and users have been warned ad nauseam not to use them.

**Comment by repo-alt** [comment]
Yet no one bothered to disable the recipes by default. (Single players have all the rights to shoot themselves in the foot)

**Comment by Retster** [comment]
Vote up from me. 
And main reason because it should be distabled by default because it's wery hard to explain new players all the reason why they SHOULD NOT use EC2 things to work with fluids. Despite the fact that EC2 already exist in pack and they are designed exactly for working with fluids.

**Comment by bombcar** [comment]
Could we disable the quests and hide the recipes from NEI? This would allow those who use it to still make it for awhile, but let people know they're EOL.

**Comment by GTNH-Colen** [comment]
> Yet no one bothered to disable the recipes by default. (Single players have all the rights to shoot themselves in the foot)

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9676
