### ISSUE TITLE
If there are EV/IV singleblock combustion gens, there should be EV/IV gas turbines

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#9673]
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.1.2.1

### Your Proposal

Why are there only EV/IV combustion generators and not EV/IV gas turbines? This makes benzene much worse comparatively for no reason.

### Your Goal

Add EV/IV gas turbine singleblocks.

### Your Vision

See above

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
If they do get added they’d be nerfed into the ground like the diesels got did

**Comment by OrderedSet86** [comment]
Good, high tier singleblocks shouldn't have good efficiencies. But oil users shouldn't be able to bootstrap while benzene players are forced to immediately build a gas turbine multi.

**Comment by Steelux8** [comment]
Why are the singleblocks still up, anyways?

**Comment by bombcar** [comment]
> Why are the singleblocks still up, anyways?

because they got nerfed into hilariously bad (40% iirc) - but even then they can be used to boot-strap.

Honestly I'd say change them to be *gas turbines* and otherwise leave them alone, diesel is too good as it is.

**Comment by Pxx500** [comment]
Why were EV singleblocks even added? There was already multi for EV combustion.

**Comment by draknyte1** [comment]
> Why were EV singleblocks even added? There was already multi for EV combustion.

@glodblock added them as a meme without actually consulting anyone. They should just be removed.

**Comment by Dream-Master** [comment]
we can add it. but i like to change the Efficiency a bit. Why high tier machines have a more bad way to use fuels than low tier machines?

**Comment by chochem** [comment]
the efficiency shouldn't be good as we want to push people to use the multiblocks I suppose.

**Comment by Dream-Master** [comment]
sure but why a lv machine habe 90% Efficiency (its a low tech machine with cheap components) and a hv have 60% ?

**Comment by chochem** [comment]
HV is still 85%. But I don't really have a strong opinion on the LV-HV efficiency.

Regarding EV/IV: Its more a balance argument for me than technological (maybe its tricky to handle that much fuel in a small engine?). If they have 80%+ efficiency then there will be people who use them as their main base power. If we want to incentivize the multiblock options and want people to centralize power, then the singleblock gens have to be bad (like 60% _at most_). They can then still be used for miners and stuff like that, so they would not be useless.

**Comment by Pxx500** [comment]
Large scale production always works better in terms of efficiency so multiblocks are better. I don't know if there is a reason why high tier singleblocks are less efficient but I wanted to point out that ALL singleblock machines are less efficient, they take 4x power for 2x speed so singleblock generators should be even worse then they are now.

**Comment by chochem** [comment]
looks like dream is working on this

**Comment by Dream-Master** [comment]
Oh i totaly forgot about it. But after Steel lux oil ratio changes i had tones of Naphta but no large gas turbines at ev so i decided to add it. I am now at iv and dont care anymore but the transition from HV erngy to ev is very hard.

**Comment by kuba6000** [comment]
Solved by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1511
