### ISSUE TITLE
Change recipe of wireless crafting terminal (AE2 wireless crafting terminal mod)

### ISSUE THREAD

**Issue by Runakai1** [GTNewHorizons/GT-New-Horizons-Modpack#9675]
### Your GTNH Discord Username

Runakai ~ Docsyᵇᵒᵗ#7676

### Your Pack Version

2.1.1.0

### Your Proposal

The normal wireless terminal (obviously without crafting) needs 2 LuV circuits. The better one, wireless crafting terminal, needs 64k as the most expensive ingredient. The whole thing can be crafted in HV while the normal worse one needs LuV

### Your Goal

nerf nerf nerf

### Your Vision

its gtnh come on

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
LuV circuits are EV-tier, not LuV-tier. That should match the 64k, do they not need titanium to craft?

**Comment by Runakai1** [comment]
> LuV circuits are EV-tier, not LuV-tier. That should match the 64k, do they not need titanium to craft?

Still, the highest circuit needed in the better wireless terminal is HV-Circuit. Also it needs like 2 titanium max

**Comment by Glease** [comment]
64k just got its price reduced drastically. Probably an oversight.
