### ISSUE TITLE
[RFC] Integrated Fluid Crafting Input Bus

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#9677]
### Your GTNH Discord Username

querns#3785

### Your Pack Version

2.1.2.1

### Your Proposal

Add a special input bus for handling fluid container items. The input bus would be able to receive both regular crafting items and fluid containers. The input bus, upon receiving a fluid container item, would decant the fluid in the fluid container into some sort of tank, then eject the empty fluid container item somewhere to be reused. The multiblock would then be able to craft items using both the non-fluid-container items and the fluid.

The design would work with common fluid containers like volumetric flasks and cells.

### Your Goal

The goal is to allow recipes containing both regular items and fluid container items to be inserted into the same bus, simplifying autocrafting with fluids for setups that eschew the use of ExtraCells2's buggy fluid crafting.

This would also allow for the ME interface's blocking mode to function properly with the recipe without some sort of item p2p hack (like the contemporary assline automation setup uses.)

The current EC2-free fluid crafting workflow looks like this:

* You have a bank of assemblers set to convert 1000mB flasks to various sizes.
* You have crafting recipes that are e.g. empty 144mB flask + 1 naquadria ingot = 144mB flask filled with 144mB molten naquadria.
* Then, when you encode the recipe for whatever, you include the filled flask in the recipe.
* The input interface dumps the items not directly into the machine, but into some type of intermediary setup designed to make the flask go to a GT tank, and the rest of the items go to an input bus or the machine. (I use subnetworks; ender IO works for this as well.)
* The GT tank uncans the flask, dumps the fluid into the input hatch or machine, and ejects the empty flask to the main network.
* The main network has a storage bus for any empty flask with no NBT, or any empty flask configured for an amount other than 1000mB going into an assembler that resets the configuration to 1000mB. 
* The crafting machine crafts the thing and ejects the finished item into the main network.

The problem with this setup is that it requires a lot of boilerplate infrastructure. Every interface has to have a subnetwork to split up the fluid containers and the other items. Multiply this by the number of input buses, and you end up with a big mess.

![javaw_jsSVp6RYfY](https://user-images.githubusercontent.com/33518699/152599071-abacc9e0-3d48-40a0-b093-2a15216d8ca6.png)

For instance, here's my automation setup for a GT++ Large Assembler. Each input bus has a subnetwork to split the regular items and volumetric flasks apart. The filled flasks output to a sub-subnetwork that buffers the flasks, uncans them, pumps the fluid into a fluid bus, and ejects the empty flask back to the main network.

### Your Vision

Some questions yet to be answered:

* Where does the fluid go? Would there be an integrated fluid tank in the input bus itself? Would it output to an adjacent input hatch?
* What happens to the empty fluid containers? Are they ejected to an output bus on the multiblock? Do they have a special output bus? Is there a second port on the integrated fluid crafting input bus for empties?
* Should the Integrated Fluid Crafting Input Bus be usable on asslines?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
It feels like what you really need is a fluid container filter block, just like type filter or machine recipe filter block.

**Comment by querns** [comment]
Not really. The act of separating fluid containers from the rest of the recipe isn't hard -- you use a subnetwork with an input interface and two storage buses. The storage bus for receiving the fluid containers has an empty flask whitelisted with a fuzzy card and a higher priority. The point of having the combined bus would be to eliminate that boilerplate and make low-lag fluid autocrafting more viable.

**Comment by querns** [comment]
Bump.

**Comment by querns** [comment]
With proper AE2FC support, this is probably no longer needed.
