### ISSUE TITLE
Add copy coords to clipboard button for journeymap 

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9678]
### Your GTNH Discord Username

Colen

### Your Pack Version

2.1.2.0

### Your Proposal

Add a button to the left that allows you to copy the coordinates to the clipboard, 

![image](https://user-images.githubusercontent.com/54497873/152608214-f882cdfa-e320-4563-998c-f6821251869c.png)

e.g. x: 4656 y: 43 z: 7282

This would be really useful for MP as trying to copy coords out is rather irritating otherwise.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
journeyman is ARR but perhaps some other way of interacting with it could be found, but a mixin could be done.

Does xaeros map have better copy support
