### ISSUE TITLE
AE2Stuff Wireless Connector Power Draw

### ISSUE THREAD

**Issue by OscarGreen03** [GTNewHorizons/GT-New-Horizons-Modpack#9679]
### Your GTNH Discord Username

Okka#2819

### Your Pack Version

2.1.2.0

### Your Server

ETA

### Your Expectation

Using Wireless Connectors report a power draw, this is incorrect and much much more powert is used. 

### The Reality

Uses much more than the reported power once connected 

### Your Proposal

Fix to proper power draw

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PolkageistHS** [comment]
I thought the power draw was in line with the 10x AE2 power cost in the config?

**Comment by GTNH-Colen** [comment]
> I thought the power draw was in line with the 10x AE2 power cost in the config?

After investigation it seems like this is the underlying issue. It's fixable but the tooltip is not taking into account the GTNH multiplier which I'm less certain how to fix.

**Comment by GTNH-Colen** [comment]
https://github.com/GTNewHorizons/ae2stuff/pull/7 both waila and the energy consumption fixed now.
