### ISSUE TITLE
Allow I/O and power on front faces of single-block machines

### ISSUE THREAD

**Issue by Tyler799** [GTNewHorizons/GT-New-Horizons-Modpack#9680]
### Your GTNH Discord Username

Night Thastus#6641

### Your Pack Version

2.1.2.2

### Your Proposal

Gregtech Blocks should allow I/O and power transfer through their front face, like they do the other 5.

### Your Goal

* For several machines it is not very clear which face is the front, nor will WAILA tell you. (It will only tell you the _output_ face)
* You can't rotate the front face, only the output face. (As far as I am aware)
* It's weirdly arbitrary. We can rotate an EBF onto its side, but can't IO into a face? What?
* It currently restricts to using 5 of the 6 available faces for no reason, making builds messier and less compact
* Give the complexity of the recipes this pack has, there are many situations where a single-block machine bumps up against this 6 faces in use, making the build less flexible in shape. (Example: A single-block water Distillery. It needs Power (1), Oxygen Cell Output (2), Hydrogen Fluid Output (3), Fluid Water Input (4), Empty Cell Input (5) and of course the blocked face (6)). 

* The current restriction doesn't make the pack better in any way.

### Your Vision

Building and automation will be slightly more flexible and definitely less arbitrary. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
> * You can't rotate the front face, only the output face. (As far as I am aware)

Shift right click on the side you want the front face on.

**Comment by boubou19** [comment]
If all the sides of a machine are "occupied" you can't access the machine anymore, even if the blocks aren't full blocks and you can click on it. also yeah, transvector interfaces are a thing to input/output fluids and items. energy still has to be linked directly to the machine (or wirelessly with a microwave energy transmitter)

**Comment by bombcar** [comment]
Hey! How about a "poor man's transvector" which is just a machine hull + pipe or something "at tier" and you stick it next to a machine and it makes it into a double-wide basically?

If super fancy you could have it borrow the texture of the machine it's stuck to.

**Comment by Steelux8** [comment]
The lack of available faces compared to a multiblock is one of the reasons upgrading to multis is a great improvement, I thought.

**Comment by LewisSaber** [comment]
Maybe just allow to rotate faces to top?

**Comment by bombcar** [comment]
> Maybe just allow to rotate faces to top?

This is allowed on some if not all - via the shift right click - and ones where you can’t face up could be fixed
