### ISSUE TITLE
Auto select the amount of item to craft in AE2

### ISSUE THREAD

**Issue by k3nw4y** [GTNewHorizons/GT-New-Horizons-Modpack#9682]
### Your GTNH Discord Username

k3nw4_y#7664

### Your Pack Version

2.1.2.0

### Your Proposal

Auto select the amount of item to craft in AE2 by default 
![image](https://user-images.githubusercontent.com/46229190/152638636-de9cabe9-2190-4897-9c71-9fa49802e584.png)

### Your Goal

When we select an item to craft from ME terminal, the default cursor is after the `1` which we have to clear before typing the new amount, so if we need 32 of an item we have to clear it first and then type the amount, but in latest versions of AE the amount value is selected by default, so we can just type in the amount without clearing it

### Your Vision

its a small Qol feature lets you type the amount without having to hit backspace everytime when you need something morethan 10

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Closed by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/103
