### ISSUE TITLE
VisualProspecting is not working on Thermos server

### ISSUE THREAD

**Issue by k3nw4y** [GTNewHorizons/GT-New-Horizons-Modpack#9683]
### Your GTNH Discord Username

k3nw4_y#7664 , Kaszanka_1234#1024

### Your Pack Version

2.1.2.0

### Your Server

CraftersLand

### Type of Server

Thermos

### Your Expectation

Visualprospecting should showup on the journeymap while finding ore veins

### The Reality

Visual Prospecting is not showing any oreveins in journeymap in Craftersland Server
log: https://gist.github.com/k3nw4y/a38b6f4d7c22240dd93ce77dfdb9e16f
its posted in the GTNH discord by the server admin before:  https://discord.com/channels/181078474394566657/603348502637969419/932379107252142110
plugins:
![image](https://user-images.githubusercontent.com/46229190/152640238-c7fd51ac-9aa7-438d-9c5a-d2186a301ef1.png)

### Your Proposal

Make visual prospector work as intended 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
we have thermos and it works on the officials so i don't know what to tell you. Try asking your admin if he did remove it serverside. Also, we don't have the same list of plugins so they might cause issues. If the plugins are at fault, a good old binary search will help your admin find out what's causing the mess.

**Comment by k3nw4y** [comment]
It isnt removed from server side, i will ask him to check if any plugin is causing it

**Comment by bombcar** [comment]
We also have it working on thermos. It took a bit of work to get the original scan to complete but it’s functional now. Try a brand new chunk somewhere?

**Comment by k3nw4y** [comment]
`i'm busy with other things and VP isn't something that is absolutely required to play the game so it's rather low on my priority list` -admin
 so im closing this, he can reopen if he wants to
