### ISSUE TITLE
irradiant reinforced iridium plate isn't searchable in AE

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9692]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

being able to see that item in my AE when i search it.

### The Reality

NEI finds it, but not AE:
![image](https://user-images.githubusercontent.com/12850933/152678113-4816998b-bf48-4563-a93e-8e3fb41f4a94.png)

Even tho it's actually here in my AE:
![image](https://user-images.githubusercontent.com/12850933/152678166-730da568-bd63-4d8c-9dcd-ab989b39a0a6.png)

![image](https://user-images.githubusercontent.com/12850933/152678278-c7bbaa72-72f0-41c8-9b11-d3bb8f278431.png)

it seems to respond to its former name, so looks like NEI and AE aren't searching the same way for item names.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
can't reproduce that in SSP
