### ISSUE TITLE
Crash Game  when I put up a facade

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#9695]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

2.1.2.2QF2

### Your Server

MP

### Your Expectation

Server crashes when I put AE2 cable facade (bricks) on a bronze liquid pipe.

Core Thermos. Attached is the crash report.

[crash-2022-02-06_22.09.49-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8011055/crash-2022-02-06_22.09.49-server.txt)

### The Reality

null

### Your Proposal

null

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
There is this "Report Crash" template without irrelevant fields that you have to fill in null.
