### ISSUE TITLE
Add StructureLib blueprint support for various multiblocks

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#9696]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

2.1.2.2QF2

### Your Proposal

Add StructureLib for multiblocks:

1) Solid-Oxide Fuel Cell MK I
2) Solid-Oxide Fuel Cell MK II
3) Сlean room
4) Lapotronic Supercapacitor
5) Manual Trafo
6) Windmil
7) Bacterial Vat
8) T.F.F.T.
9) L.E.S.U.
10) Mega Distillation Tower
11) Mega Freezer

### Your Goal

null

### Your Vision

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FoKuCNiK** [comment]
> Mega freezer and mega distillation tower already have structurelib support in 2.1.2.0

Description only, no visualization

**Comment by boubou19** [comment]
Yeah, for the MDT it says it cannot renders the hologram fully (understandable) but it displays nothing.
For the MVF, it doesn't even say it's too big, just renders nothing.

**Comment by FoKuCNiK** [comment]
> Yeah, for the MDT it says it cannot renders the hologram fully (understandable) but it displays nothing. For the MVF, it doesn't even say it's too big, just renders nothing.


Okay, these are the least needed in adding visualization support. Hope it will be added in the next updates.

**Comment by bombcar** [comment]
I wonder if for the megas a .... feature would make sense:

render the bottom X rows, then renderer ... pillars and render the top X rows 

might be confusing

**Comment by Glease** [comment]
How do you project a cleanroom blueprint? This multi is just too flexible for structurelib.

**Comment by GTNH-Colen** [comment]
Yea without something like a small GUI inside the blueprint that lets you pick the width, height and depth I don't see how blueprints can work for some multis (like the cleanroom). If it has variable length in 1 dimension then it can be done with a stack of blueprints just as the TT Q computer does I suppose.

**Comment by FoKuCNiK** [comment]
> How do you project a cleanroom blueprint? This multi is just too flexible for structurelib.

I used only a list of polyblocks of unplanned premature death. If some such as clean room and mega multiblocks are not needed, call a quick render.

**Comment by draknyte1** [comment]
> How do you project a cleanroom blueprint? This multi is just too flexible for structurelib.

It’s doable, but it wouldn’t be nice 😂

**Comment by Dream-Master** [comment]
maybe it show up different sizes each time you click. From small to large ?

**Comment by leagris** [comment]
Capture mouse-wheel direction to cycle through sizes

**Comment by bombcar** [comment]
Just show max size to troll people 😈. 

Mousewheel is an option - also could have it print into chat “other sizes will also work” or somesuch
