### ISSUE TITLE
8500 silverfish spawned (Duplicate)

### ISSUE THREAD

**Issue by JustBenji** [GTNewHorizons/GT-New-Horizons-Modpack#9698]
### Your GTNH Discord Username

Benji#0586

### Your Pack Version

2.1.2.0

### Your Server

Private Multiplayer

### Your Expectation

That maybe 20 silverfish spawned.

### The Reality

8500 spawned, kept spawning, server was not happy.
![unknown](https://user-images.githubusercontent.com/96138378/152869609-c9f097e6-429d-42c6-9bfd-be9f68d35c57.png)

### Your Proposal

Put a max on spawned entities

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
Why did they spawn in the first place?
