### ISSUE TITLE
LV Miner - Doesn't mine

### ISSUE THREAD

**Issue by sethdark** [GTNewHorizons/GT-New-Horizons-Modpack#9700]
### Your GTNH Discord Username

SethDark

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

LV miner to mine

### The Reality

LV miner turns on for 1 cycle, turns off, no items are produced, pipe is not used, pipe does not appear beneath the miner

Batteries are charged and are draining (4 Lithium ones) while the cycle runs, cycle doesn't produce item or use pipe.
Auto-output is on, pointing up in a empty chest.

### Your Proposal

if possible get it to work

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
See #9549, try updating GT5

**Comment by sethdark** [comment]
Updating worked
Thank you
