### ISSUE TITLE
BoundShears cause server crash

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#9701]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.1.0

### Your Server

private server

### Type of Server

Crucible

### Your Actions

I took TCeti E Seaweed at BoundShears

### Crash Report

crash report:[crash-2022-02-08_15.02.55-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8021919/crash-2022-02-08_15.02.55-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
Your crash report is totally unrelated to shears.
