### ISSUE TITLE
Awakened draconium singularity too cheap

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#9703]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.2

### Your Proposal

Awakened draconium singularity needs only one block to be made - too cheap. By the time you can get this material you will already have a void miner, plus it’s the only realistic way of obtaining this material in decent quantities.

### Your Goal

Don’t nerf it into the ground but a more reasonable number is appropriate for that tier. I suggest putting it at 760 blocks, equal to enderium.

Relevant code:

https://github.com/GTNewHorizons/Universal-Singularities/blob/master/src/main/java/wealthyturtle/uiesingularities/proxy/CommonProxy.java

### Your Vision

More appropriate challenge for this singularity.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LewisSaber** [comment]
maybe buff regular draconium singularity too?

**Comment by GTNH-Afx237v7** [comment]
Regular draconium you can get in masses, suggest to set it to 1296 blocks/singularity.
