### ISSUE TITLE
TecTech Fluid Cover

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#9707]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

2.1.2.2QF2

### Your Server

MP

### Your Expectation

Private mode doesn't work. Any other player (if they know the code) can enter the code for my Fluid Cover and pump out the liquid

### The Reality

Make private mode work well (take EnderIo tesseract with working private mode as an example) The bug is not critical, but prevents me from using Ender Fluid Cover on the server due to paranoia

### Your Proposal

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FoKuCNiK** [comment]
I don't think anyone cares...

**Comment by Dream-Master** [comment]
ask in Mod dev for it @FoKuCNiK
