### ISSUE TITLE
Something that could show everything you haven't eaten yet in NEI

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#9709]
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.2.0

### Your Proposal

Something to write in NEI that might show all the foods you haven't tasted yet.
I've seen in some modpacks you can just write "#yet" and NEI (or equivalent they have) shows all the foods they haven't eaten yet (in their modpack they have all the foods marked as "eaten" or "not yet eaten" in the lore, so I guess the "#yet" refers to that lore)

### Your Goal

The Healing axe is really easy to get in the early game, so if you were just an idiot who alternated between same food and suicide until the Healing axe you didn't earn a lot of hearts, for example , I'm LuV and I just got 11 extra hearts. (and now if I make this ticket, it's obviously because I would like to have more hearts lmao)

### Your Vision

It would make life so much easier when it comes to getting more health when you stopped farming it months ago or just at the end of this gameplay when you've already eaten 95% of what is proposed

Sorry for my lack of english skill, feel free to ask me questions if I was not clear enough.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
The search trick works here, I think "taste like" or other similar phrases should work (finds everything with the "Not Yet Eaten, what does it taste like" tooltip.

**Comment by POPlol333** [comment]
Oh you are completely right, I'm sorry for the inconvenance

**Comment by POPlol333** [comment]
I don't have any button to close the ticket, can someone do it? thanks
