### ISSUE TITLE
Nonuple Fluid Pipes are cheaper than Quadruple Fluid Pipes

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#9710]
### Your GTNH Discord Username

ALongStringOfNumbers#9024

### Your Pack Version

2.1.2.2QF2

### Your Proposal

Nonuple Fluid Pipes should not be cheaper to craft than Quadruple Fluid Pipes.

Once the Extruder is acquired, Regular Fluid Pipes can be made 3 ingots -> 1 pipe. 

The Quadruple Fluid Pipes require 4 of these Regular Fluid Pipes for a total cost of 12 ingots of material

However, Small Fluid Pipes can be made 1 ingot -> 1 pipe.

The Nonuple Fluid Pipes require 9 of these Small Fluid Pipes for a total cost of 9 ingots of material.

### Your Goal

Nonuple Fluid pipes have the advantage over the Quadruple Fluid Pipes in that they can transfer 5 more fluid types than the Quadruple Fluid pipes, therefore they should be more expensive.

### Your Vision

Fluid Pipe costs would be balanced based on the amount of fluid types that they can transfer at one time, with the pipe capable of transferring more being more expensive.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
If i make this pipe more expensive we need to change the fluids Liter per sec as well.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/153672541-1b94631e-5396-4049-ad7a-5dcc4f06eaee.png)
![image](https://user-images.githubusercontent.com/2970688/153672558-a63b5b9d-9031-4a11-8d75-69ebe8ae9f04.png)
Fluid capacity is more bad on Nonuple pipes

**Comment by Dream-Master** [comment]
Logic wise it wouldn't be a good idea to change the values because of the liquid trhoughput. Maybe a new fluid pipe need to be added
