### ISSUE TITLE
Newest version of GT++ makes the wireless charger not work

### ISSUE THREAD

**Issue by stlchase40** [GTNewHorizons/GT-New-Horizons-Modpack#9712]
### Your GTNH Discord Username

stlchase40

### Your Pack Version

2.1.2.2

### Your Server

SP

### Your Expectation

Using the newest version of GT++ (GT-PlusPlus-1.7.10-1.7.27-6-g3b7197a-dev) the wireless charger is broken. I don't know if I should be reporting this yet since this version of GT++ isn't even really released yet, but Alk gave it to me to test stuff and I found this.

.

### The Reality

Basically what happens is the screen gets [spammed with the notification of entering the charging range](https://imgur.com/gallery/M3a7DxI), but it doesn't charge, and causes the gravichestplate to not allow you to fly

### Your Proposal

Just reporting a bug I found with the newest version that I know will be annoying if it doesn't get found out about until too late.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Probably broke it when I implemented locking. 🙃
