### ISSUE TITLE
Remove EV/IV combustion generators

### ISSUE THREAD

**Issue by draknyte1** [GTNewHorizons/GT-New-Horizons-Modpack#9713]
### Your GTNH Discord Username

Hello

### Your Pack Version

It’s me

### Your Proposal

Remove the moderately pointless EV/IV combustion gems that got added in sneakily and also as a meme. They defeat the purpose of requiring multis even if they have terrible efficiency. 

### Your Goal

Remove pointless sneaky addition. Possibly require Glod to follow the same structure as every other mod instead of committing directly to master. 

### Your Vision

Doesn’t fit GTNH. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
The way is to add everything fun before the first fork 🥳😘

**Comment by bombcar** [comment]
In reality we have single rocket fuel gens, which are usable for single purposes. These should either be crashed to incredibly low efficiency, restricted to HOG, or recipe removed pending final removal

**Comment by draknyte1** [comment]
Rocket fuel singles exist leading up to the multi, same as naq gens. They don’t coexist with the multi at worse efficiency.

**Comment by GlodBlock** [comment]
they are not pointless as them can work as the ore miners and drilling rigs power source, but not suitable for main power cuz it's eff is too low and people can have nuke as more stable power sources.
also you have added a luv lava sb generator which more unreasonable than the sb ev/iv generator.
as to why i commit to my repo dircetly. bascially nobody will actually review a pr that has hundrends of changes, so final result is `merge and test in zeta`

**Comment by draknyte1** [comment]
> you have added a luv lava sb generator 

Been there for years. 

> bascially nobody will actually review a pr that has hundrends of changes

they can and do even if only glanced over so *features* aren’t snuck in. You should adhere to the development processes of everyone else. You’re treading into Bart territory if you think you’re above review processes.

**Comment by GlodBlock** [comment]
> > you have added a luv lava sb generator
> 
> Been there for years.

still doesn't justify it

**Comment by GlodBlock** [comment]
> > bascially nobody will actually review a pr that has hundrends of changes
> 
> they can and do even if only glanced over so _features_ aren’t snuck in. You should adhere to the development processes of everyone else. You’re treading into Bart territory if you think you’re above review processes.

then i am glad to follow this rule.

**Comment by Dream-Master** [comment]
i would let them in to just work on miners and small setup you set up elsewhere. (As mentioned before) Sure its not optimal for Power your Base
