### ISSUE TITLE
let the player reprogram his CAL

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9715]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

Let the player reprogram his CAL. I propose several ways to do that:
1. via the name remover: it can clean some nbts, why not the nbt related to the imprinted circuit? but that's not in line with the theme, as the name remover was introduced to solve some technical issues involved by NBTs themselves.
2. via a craft (programmed controller + LuV circuit = blank controller for exemple) That way we would "replace" the used memory by a new one
3. via a right click with a soldering iron to "remove" the imprint 

### Your Goal

Players shouldn't be punished for a mistake (they imprint twice the same circuit and program 2 CAL the same way) or because of a recipe change: for exemple, in 2.1.2.0, the nand chip recipe was moved from circuit assembler to a cutting recipe, made from a nand chip array, which is made in a circuit assembler with the same amount of materials as the previous nand chip array. As a result, the previously imprinted CAL with a nand chip imprint is now bricked as the recipe doesn't exist anymore. 

### Your Vision

it removes the tedium induced by the fact you cannot reprogram your CAL.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I lean toward 2 unless we add a reprogrammer multiblock 😈

**Comment by redmage17** [comment]
I've suggested something similar a few times. The fact that you had to make a new CAL for every circuit and the fact that the CAL did not save much in efficiency never made sense to me

**Comment by bombcar** [comment]
I could see an argument to try to prevent players from abusing a single CAL for all circuits by reprogramming it, but if that's a concern make it so you can only wipe ones *with invalid recipes*

**Comment by boubou19** [comment]
> I could see an argument to try to prevent players from abusing a single CAL for all circuits by reprogramming it, but if that's a concern make it so you can only wipe ones _with invalid recipes_

If a player wants to abuse it, if we suppose that method n°2 is used to reprogram the CAL, it'll cost you a LuV circuit per reprog. In addition of that, the player will force on himself additional tedium. The intended way to progress is by using multiple CALs. For me i see no problem with that.
