### ISSUE TITLE
Alloy smelting synthetic rubber bars into their plates

### ISSUE THREAD

**Issue by GTNHAfx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#9717]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.2

### Your Proposal

Fluid solidifying of 144L rubber / SB-Rubber / Silicone rubber will make a plate with the plate mold.
To make a plate of these rubbers with an alloy smelter you need two bars or pulps, i.e. 288ML.
Should be the same ratio, i.e. one bar to one plate in the alloy smelter.

### Your Goal

Make turning bars into plates cost the same in the alloy smelter as compared to fluid extracting/solidifying.

### Your Vision

Ease of automation / less machines involved

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
This is intended. Alloy smelter is the only way to get the plates in steam age. Makes it rewarding to get chem reactor + solidifier later.

**Comment by boubou19** [comment]
for regular rubber yes, for silicone rubber or styrene-butadiene it's dumb as they are unlucked way after steam age

**Comment by vovaksenov** [comment]
I don't see a reason for these recipes to exist at all to be honest. Why not just use a bending machine or solidify directly into plates and then use a multi smelter making ingots to keep both in stock?

**Comment by vovaksenov** [comment]
If someone feels this change is needed, sure, i guess. I only wanted to mention the early game so that normal rubber stays as it is.

**Comment by Pxx500** [comment]
I'd leave it for the sake of consistency, no one uses these recipes later but at least they are consistent throughout the game.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/153671300-01a4abd3-67eb-4f59-979c-97006400a26e.png)
![image](https://user-images.githubusercontent.com/2970688/153671347-66cf1795-ac22-4d5e-96a2-59c4bf984080.png)
