### ISSUE TITLE
Found a Diamond / graphite vein but it doesnt get registered on the minimap ore vein detection system

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [GTNewHorizons/GT-New-Horizons-Modpack#9718]
### Your GTNH Discord Username

Single Core#0827

### Your Pack Version

2.1.1.2QF2

### Your Server

private server

### Your Expectation

I found a Diamond / graphite vein but it doesn't get registered on the minimap ore vein detection system. I expect it to show up like all the other veins.

### The Reality

It doesnt register / discover the vein.

### Your Proposal

Make it register / discover the vein.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Are you near spawn? If so, set 

`B:recacheVeins=false` to true and restart, see if that fixes it.

If not, it's probably a known issue with graphite for some reason.

**Comment by bombcar** [comment]
Was it an old/new chunk? If you want to experiment, and it's far from base, calculate and *backup* and remove the appropriate region file (when you're not there of course) and then go back and see if it now finds it. Sometimes old-scanning just doesn't work at all.

https://dinnerbone.com/minecraft/tools/coordinates/
