### ISSUE TITLE
Create Toxic Everglades quest

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#9719]
### Your GTNH Discord Username

Riking#6902

### Your Pack Version

2.1.2.0

### Your Proposal

Add a LuV-tier quest to build the Toxic Everglades portal parts.

### Your Goal

Draw players who see Everglades ores to (1) instructions on making the portal, which is satisfied by directing them to the Containment Frame item, and (2) realizing what tier the dimension is available at, which is satisfied by placing it in the quest book.

### Your Vision

=== Toxic Everglades Portal ===

The Toxic Everglades are a dimension with many useful ores and maybe a few environmental hazards. Create the portal and check it out.

Retrieval Task: Containment Frame #2783 x10
Retrieval Task: Alkalus Disk [Activated] #9741 x1

Requirements: LuV Assembler #1722

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
![image](https://user-images.githubusercontent.com/81298696/153523682-5a71040c-4be5-4cb1-ae5a-5eae3ac2bd59.png)
Hmm...

**Comment by Pxx500** [comment]
> Requirements: LuV Assembler

![image](https://user-images.githubusercontent.com/81298696/153523773-03fd546c-edc9-4b0e-bed2-330289de4c74.png)
Yes

**Comment by Dream-Master** [comment]
yes quest is in ZPM chapter and need zpm voltage
