### ISSUE TITLE
Making thaumcraft research table

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#9722]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.2QF-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Tried to make TC research table with primal scribing tool

### The Reality

Table didnt form

### Your Proposal

Add ability to make TC research table with all scribing tools, i tested all scribing tools and it appears that only forbidden magic scribing tools cant form table

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Maybe possible but Thaumcraft is closed source and ARR.

**Comment by LewisSaber** [comment]
Some of scribing tools work and some not, maybe its not connected to tc or how some of them works
