### ISSUE TITLE
Pollution scrubber does not work (singleblock)

### ISSUE THREAD

**Issue by madmacf** [GTNewHorizons/GT-New-Horizons-Modpack#9723]
### Your Pack Version

2.1.1.0

### Your Server

Single player

### Your Expectation

Pollution scrubbers doesn't work.

### The Reality

The scrubber never starts. Added T1 filter in left slot. Turbine in left slots. Both normal turbines and gt++ ones.
Tried adding power on all sides. Tried directly to a transformer. Pollution above 300000 in chunk.
It's the singleblock HV one.
Smacked it with the soft mallet. 
Nothing works.
It looks whatever item is placed in lower right corner, and can't be removed again. 
Seems buggy.
![error](https://user-images.githubusercontent.com/22689175/153635269-dde7425e-8e45-49eb-be20-0c2af8cdb98f.jpg)

### Your Proposal

Fix it :-)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
2.1.1.0 has pollution off - did you turn pollution back on?

**Comment by draknyte1** [comment]
Update your game.

**Comment by madmacf** [comment]
> 2.1.1.0 has pollution off - did you turn pollution back on?

It's an old world I started playing again. Never turned it off or on.
It's the newest version. 2.1.1.0 It's updated. Do you mean it's a setting in af config file? Which one?
Please help.

**Comment by draknyte1** [comment]
2.1.1.0 is not the latest and did not have pollution enabled.

**Comment by madmacf** [comment]
Sorry. Wrote the wrong version. I'm on 2.1.2.0. Newest from curseforge.
Turned the pollution off. Never turned it on myself.

**Comment by bombcar** [comment]
2.1.2.0 has known issues with the GT++ scrubbers, but if you turned pollution back off, the scrubbers won't run at all.

**Comment by draknyte1** [comment]
I fixed scrubbers, I was sure that made it into 2.1.2.0. 🤷🏻‍♀️
