### ISSUE TITLE
Crops are broken and not usable anymore on official server

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#9728]
### Your GTNH Discord Username

CatsLeftEar#3300

### Your Pack Version

official

### Your Server

Epsilon

### Your Expectation

Plant crops

### The Reality

Can only place one crop, sometimes a bit more
(happens for every player on a  server)
https://gfycat.com/ru/ajarmellowduckbillcat

### Your Proposal

Help

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
We get the same thing on IM on mmcc but not GT. Maybe it’s thermos

**Comment by bombcar** [comment]
Maybe an ASM is failing - `Patching CropBlock to not pop off when neighbours change` is something from CroploadCore:

https://github.com/GTNewHorizons/CropLoadCore/blob/ef2f17c27ed9dead957bcd432cd709745eb7b0f0/src/main/java/com/github/bartimaeusnek/ASM/CropStickTransformer.java#L75
