### ISSUE TITLE
"Wooden Rail Variants" quest is broken

### ISSUE THREAD

**Issue by Meegooo** [GTNewHorizons/GT-New-Horizons-Modpack#9729]
### Your GTNH Discord Username

Meegoo#2430

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

"Wooden Rail Variants" quest should correctly detect Wooden Junction Track and Wooden Wye Track

### The Reality

Quest only detects "Wooden Switch Track"
![image](https://user-images.githubusercontent.com/3753828/153710683-18563df8-ef01-4f8c-ab5e-e33ed07c9f11.png)

### Your Proposal

It seems that metadata is at fault. Quest expects rails with meta 0, while actual meta is 736. I manually edited the values and quest works after that.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
maybe some nbt issue
