### ISSUE TITLE
Iron "dupe" with tracks

### ISSUE THREAD

**Issue by Meegooo** [GTNewHorizons/GT-New-Horizons-Modpack#9730]
### Your GTNH Discord Username

Meegoo#2430

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

No dupe

### The Reality

You need 4.5 iron rods to craft 6 standard rails and then craft 64 tracks from those 6 standard rails and a basically free wooden track. Then you can smelt a single track into 54 mb of iron, or 24 ingots per stack of tracks. 
![image](https://user-images.githubusercontent.com/3753828/153711028-9cd3b98b-ac8f-4a07-8634-e6a09ed35601.png)

Alternatively, you can convert 64 tracks into 8 standard rails, while needing only 6 to craft a new stack of tracks
![image](https://user-images.githubusercontent.com/3753828/153711023-ab8b3c44-d876-43bd-91ac-0deebecf105a.png)

### Your Proposal

Remove 8 tracks -> 1 standard rail recipe and recycling of tracks in the smeltery. They are cheap enough.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AnrDaemon** [comment]
This is a modpack issue and should be fixed by modpack, not by mod code.
The recipe is clearly designed for vanilla rail recipe, and should remain as that.

**Comment by boubou19** [comment]
> This is a modpack issue and should be fixed by modpack, not by mod code. The recipe is clearly designed for vanilla rail recipe, and should remain as that.

we dont make usage of minetweaker anymore, it's slower to load. Also since we control our railcraft fork, we can do what we want as its primary usage is for NH, not vanilla.

**Comment by AnrDaemon** [comment]
> we dont make usage of minetweaker anymore, 

I did not said anything about any specific way you could solve it.
But specifically for your modpack, you could use your main mod to amend interoperability issues.
