### ISSUE TITLE
Allow OP users to bypass ME security

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#9732]
### Your GTNH Discord Username

Colen

### Your Pack Version

2.1.2.1

### Your Proposal

See title, pretty self explanatory and useful for server admins trying to investigate. @repo-alt not sure how hard this would be?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7555

**Comment by GTNH-Colen** [comment]
> #7555

What kind of lunacy is this, this isn't the fucking NSA I just want easy access to do my job ffs. I don't give a shit about user privacy, they forfeit that by playing on servers which are not theirs.

**Comment by OscarGreen03** [comment]
Did you tick the box  "I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying I like this change please reconsider adding it will prompt us to investigate and reopen it once we confirm your report."?
Moreover, why do you distrust your users so much that you need constant access to the ME system, you have already demonstrated you can bypass it by removing the terminal using world edit.
I suggest closing this ticket

P.S. i find it quite ironic you suddenly want to do your "job"

**Comment by OscarGreen03** [comment]
![image](https://user-images.githubusercontent.com/89072407/154814681-0f629ea0-0a67-4c03-a253-f2c194703b46.png)

**Comment by repo-alt** [comment]
@boubou19 Do you remember why [#7555 ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7555) was closed? I remember something like it turned out to be working as is.

**Comment by boubou19** [comment]
it was closed because turns out i can read the items in the terminal, just not take them. But idk if it's due to the fact that default user has only read access or if it's a special perm for OP players. That was enough for my needs at the time so i didn't bothered much.

If you ask me, that protection is purely silly and operators should have full access to any stuff on the server. If the operator is doing questionable actions with his powers then that's on Dream and I because we trusted the wrong person to be staff. 

And if any player complains about this because we would gain full access to their AE, i want to say that we can by

**Comment by repo-alt** [comment]
Eh, I kind of agree, but also, read access seems to be quite enough. I mean if OP spots something illegal, he can take administrative measure and/or break security terminal.

**Comment by boubou19** [comment]
i agree too, but sometimes it's unfair to break the terminal or hijack the storage to remove something from it, because if one player is faulty we shouldn't bother the whole team.

**Comment by draknyte1** [comment]
I just hid my hacked items in a chest below my dirt floor.

**Comment by boubou19** [comment]
i just thought about it: why not deliver the full access to operators based on their OP level? iirc command blocks and default opped players are only level 2, and the top level is level 4. For exemple on the officials, only the admins are level 4. 

could be a command based tool, like /toggleAEfullAccess that would grant it temporarily (not persistant to reboot) the access of the trusted level 4 operator

**Comment by GTNH-Colen** [comment]
> Eh, I kind of agree, but also, read access seems to be quite enough. I mean if OP spots something illegal, he can take administrative measures and/or break security terminal. I don't see any reason for OP to take out stuff secretly.

Not always so simple, they can hide items inside bags, compressed chests or other storage items. Players are very creative and I've seen them cheat in more ways than I have words over the years.

**Comment by repo-alt** [comment]
ok, command based can be implemented somewhat naturally

**Comment by GTNH-Colen** [comment]
> ok, command based can be implemented somewhat naturally

Couldn't AE just cache a list of people on the OP txt list at startup and then add their names/UUID however it works to the security terminal as joint highest perms? Or yea a command that allows us to add individual users to the list
