### ISSUE TITLE
LV miner not retracting mining pipe

### ISSUE THREAD

**Issue by kenken244** [GTNewHorizons/GT-New-Horizons-Modpack#9733]
### Your GTNH Discord Username

Kenken244#9849

### Your Pack Version

2.1.2.2 QF2 

### Your Server

private server

### Type of Server

Single Player

### Your Expectation

LV miner placed in the nether should retract its mining pipes when hit with a soft mallet

### The Reality

the miner does not retract its mining pipes. this may have something to do with its placement in the nether, or the fact that the "head" of the miner was in the middle of a lava lake at the time. it had not reached bedrock either. 

### Your Proposal

hitting the miner with a soft mallet should retract mining pipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
Afaik miners don;'t retract pipes when hit with soft mallet since it just disables them, newly implemented feature should be added for that to work.

**Comment by bombcar** [comment]
Latest code does have retractable pipes so something there may not be working correctly
