### ISSUE TITLE
carbon dust chemical reactor recipe broken

### ISSUE THREAD

**Issue by Maxhy21** [GTNewHorizons/GT-New-Horizons-Modpack#9735]
### Your GTNH Discord Username

Largerthan2#3231

### Your Pack Version

2.1.2.2qf2 with galaxyspace and steveaddons replaced

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

carbon dust used in titanium line and other recipes(like carbon monoxide) in chemical reactor
![image](https://user-images.githubusercontent.com/35527077/153746309-6cc1d87c-e39f-4440-8d52-1affc238349d.png)
![image](https://user-images.githubusercontent.com/35527077/153746315-136e17ee-907e-4116-a38a-5abbb6932cce.png)

### The Reality

![image](https://user-images.githubusercontent.com/35527077/153745237-7141ffc4-fd83-4b20-b795-3e07f1aa014d.png)
the only use for carbon dust in reactor

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
@Elisis

**Comment by Elisis** [comment]
Shouldn't have anything to do with Lanthanides, especially because it's not being shipped in any version as far as I can't tell. HfC is a GalaxySpace thing afaik

**Comment by Glease** [comment]
ah sorry. thought it was your lanthanides line somehow creating trouble.

**Comment by glowredman** [comment]
I didn't add gtnhlanth as a dep because it is only needed for this single recipe and not having it installed creates no problems, @Maxhy21 simply download GTNH-Lanthanides from [Jenkins](http://jenkins.usrv.eu:8080/job/GTNH-Lanthanides/), add repalce the botdustries jar with it.

**Comment by Maxhy21** [comment]
> I didn't add gtnhlanth as a dep because it is only needed for this single recipe and not having it installed creates no problems, @Maxhy21 simply download GTNH-Lanthanides from [Jenkins](http://jenkins.usrv.eu:8080/job/GTNH-Lanthanides/), add repalce the botdustries jar with it.

with this replacement sodium nitrate is missing
![image](https://user-images.githubusercontent.com/35527077/153827556-6a8a5f69-5114-41d9-9fb8-ec5774fa0d77.png)
