### ISSUE TITLE
Wrong tooltip on Large Sifter Control Block 1753:540

### ISSUE THREAD

**Issue by SGrober** [GTNewHorizons/GT-New-Horizons-Modpack#9736]
### Your GTNH Discord Username

SGrober#9546

### Your Pack Version

2.1.2.0-RC1

### Your Server

Private server

### Your Expectation

Forming GT++ Sifter as indicated in the tooltip.

### The Reality

![1](https://user-images.githubusercontent.com/94621882/153754200-a80a406d-65b5-4d04-a3eb-b7844f6c2908.jpg)
Tooltip does not say how many output bus is needed.

### Your Proposal

A fragment of the old description from youtube says that you need 4 output bus
![2](https://user-images.githubusercontent.com/94621882/153754467-ad4cd4e8-c2a1-42ad-9b6e-7721e4eb240a.JPG)

Specify 4 output bus in tooltip
While the machine is formed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
was fixed at some point. picture in 2.1.2.4 dev29:
![image](https://user-images.githubusercontent.com/40274384/185688354-a031de29-8806-450e-8a29-6fca23e07a33.png)
