### ISSUE TITLE
quest 2521 making patterns quick is obsolete due to NEE

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9737]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

![image](https://user-images.githubusercontent.com/12850933/153760291-0a1bd076-ca2b-433e-946a-46ea592dc64e.png)
this is now useless as we have NEE that allows you to do that but way better, and for all the recipes that have a ? button.

### Your Goal

-

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Change it to a quest detailing how to use NEE to do it?
