### ISSUE TITLE
Diamond rods out of Diamonds in Lathe not show up in NEI

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#9738]
recipes are not shown up in nei but still working.

Diamond rods as an example
![image](https://user-images.githubusercontent.com/2970688/153766553-92552c0d-def3-4020-a322-25c516cdca2e.png)
show only industrial version and gt++ item
![image](https://user-images.githubusercontent.com/2970688/153766567-a1d5fafc-f823-422a-9f29-cf999132ef97.png)
but works with diamonds ingame (LV Lathe)

**Comment by Dream-Master** [comment]
Tested with 2.1.2.3 dev build

**Comment by bombcar** [comment]
Digging into this it appears to be an predict problem in NEI itself, but I can't figure out what causes it.

Multiple different cases of runClient can get it to happen or not happen seemingly randomly. (2.2.7 NEI without nei-custom-diagram saw it, but then again 2.2.7 NEI with new-custom-diagram also had it happen)

It its EVERY SINGLE oredict cycling, like fuel/wood in furnace or wood in lathe, etc.
