### ISSUE TITLE
Disassemblers don't work in the PA

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#9742]
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.1.2.2qf2

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Put 1x LV Muffler Hatch into a PA with 20x HV disassemblers inside of it. Expected disassembly into parts.

### The Reality

Nothing happened.

### Your Proposal

PAs should support diassembly machines.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Anyone who would PA disassemblers is not to be trusted.

**Comment by Glease** [comment]
Disassembler logic is too complex to fit in existing PA's framework codewise. Probably not going to happen within forseeable future.

**Comment by joshaup1999** [comment]
++ has their multi for it at LuV iirc, might be a bit later
