### ISSUE TITLE
put the import mode as the default mode for the conveyors

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9745]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

put the import mode as the default mode for the conveyors

### Your Goal

I realized that when you setup some input buses that can be accessed from only one side, well if you put items in it first (typically a circuit config) then you put a conveyor, it'll spit out the items stored in it, so you have to put them back either via the conveyor itself, or break a block and put the items back. That's tedious. Meanwhile putting the default mode to import would solve this issue completely, and it wouldn't impact existing setups.

### Your Vision

remove some automation tedium, because tedium is bad mkay?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNHAfx237v7** [comment]
Bump because this is relevant imho.
