### ISSUE TITLE
Make a funny fission process

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#9746]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.2QF

### Your Proposal

I want to see some new stuff about the Uranium and Thorium fission process.
As the Naquadah reworks has been done, I saw the creative idea of GTNH team.
What about rework the Uranium and Thorium?
Some people say they are useless in late game or end game.
Why not make some new multiblocks generators(etc special machines) for them to dance also in the late game?
(better fuel rod MK.III MK.IV)
Or make them just like fluid reactor to make new type of steam to generate more power?

### Your Goal

rework Uranium and Thorium to make more funny processes

### Your Vision

I love GTNH stuff creating new processing lines.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by KamenriderZO** [comment]
I mean jump out the frame of IC2 reactors, just make some GTNH team style fission!

**Comment by lordclips** [comment]
A funny fission process would be taking the mass of a cat and turning it into pure energy to run New York for a week

**Comment by Pxx500** [comment]
If you need energy THTR is the reactor you need.
