### ISSUE TITLE
Netherrack Dust Change [Suggestion]

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9748]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.2

### Your Proposal

Right now, Centriguing Netherrack Dust yields Small and Tiny dusts. These should output whole dusts using the following probabilities per dust.

Redstone: 6.25%
Sulfur: 24.75%
Coal: 6.25%
Gold: 0.69%

### Your Goal

Reduce the amount of tiny and small dusts in the world and reduce lag as a result.

### Your Vision

Bring Netherrack Dusts in line with other recipes to eliminate Small/Tiny dusts where applicable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
If we do this we would need to apply the same change to every stone dust. It's a bit of an undertaking, so that should also be considered

**Comment by KamenriderZO** [comment]
If this could be change , please also change the Platinum processing. Because it also generates anoying tiny dusts.Make them big dusts with certain possibility will be better
