### ISSUE TITLE
Buff Research completer

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#9752]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.2QF-2

### Your Proposal

Change how much essense research comoleter eats, atm it eats insane amount this node didnt last even 2 researches 
![image](https://user-images.githubusercontent.com/39595617/154232299-76edb8c2-c61b-4a3c-847a-422a04e6ccb6.png)
i used iv energy hatch and was researching Vis relay interface and vibration chamber in thaumic energistic tab

### Your Goal

I know he makes researches way smoother but its too insane cost

### Your Vision

make it use less node vis when upgraiing energy hatch

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
lol what are you really complaining? Is it too bad that you ask for a nerf or you want a buff instead?

**Comment by LewisSaber** [comment]
i mean buff lol

**Comment by KiloJoel** [comment]
I intentionally made this underpowered to start with, and I do agree a buff is probably warranted. Though I'm not sure exactly how much of a buff is needed.
