### ISSUE TITLE
Molten Metals in Tinker's Smeltery Do Not Display

### ISSUE THREAD

**Issue by Collosus2749** [GTNewHorizons/GT-New-Horizons-Modpack#9762]
### Your GTNH Discord Username

InvictusManeo#1292

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

Trying to smelt any Items in my Tinkers Smeltery and see visual liquid once it completes smelting and is in the smeltery.

### The Reality

Tinker's Smeltery functions properly but I can not visually see the molten metal in my smeltery
![2022-02-16_19 02 08](https://user-images.githubusercontent.com/64758564/154379128-07702812-f166-428c-ac6f-d73cd9aecd67.png)
![2022-02-16_19 01 50](https://user-images.githubusercontent.com/64758564/154379135-7c8197b9-2606-4fae-8ffc-8800c469d3e9.png)
.

### Your Proposal

Tinker's Smeltery functions properly but I would like to visually see the molten metal in my smeltery.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Collosus2749** [comment]
For clarification, I downloaded and am using Faithful 32x32 resource pack. However this issue has been present since I started the pack and existed before and after I installed the resource pack.

**Comment by bombcar** [comment]
Hmm moltens render in my smeltry - but it’s deeper than yours. Maybe add another full layer?

**Comment by Collosus2749** [comment]
mine is usually 3x3x2 so I can smelt 18 items at once. I broke the block above the controller to more easily display the contents for the screen shot. Do you mean an additional layer so I can smelt 27 at once?

**Comment by bombcar** [comment]
Yeah was trying to see what may be different between yours and mine. I know there’s at least one optifine setting that can break the fluid rendering, and that fluid disappears if I break my smeltry (but comes back if it wasn’t the controller)

**Comment by Collosus2749** [comment]
Okay I'm in the process of making it one layer deeper (27 blocks smelted at once) and will report back the results. Ive also tried breaking my controller and replacing it as well as breaking all of the bottom bricks (floor) and replacing those. I do have optifine D6 because E7 wrecks my FPS for some reason. Do you know which setting affects fluid rendering?

**Comment by bombcar** [comment]
I don’t offhand but try with optifine disabled - of the fluid comes back it’s certainly an optifine setting (iirc fastest vs faster causes it but not sure what setting that was on)

**Comment by Collosus2749** [comment]
Okay I will attempt that. By the way I did make it 27 blcoks and that did not help unfortunately :(

**Comment by Collosus2749** [comment]
Update: I did remove optifine and that did fix the problem :/ So I will reinstall optifine and try to find that setting you mentioned.

**Comment by bombcar** [comment]
I’m on e7 but I don’t see much different between the two.

**Comment by Collosus2749** [comment]
Okay i installed E7 and I can see the liquid now. So I will close the Issue and either try to mess with E7 to get stable FPS or go back to D6 and accept that I cant see molten liquid. Thank you for your help and advice man.
