### ISSUE TITLE
Tinker's Crafting Station Crashes while placed next to Arcane Worktable

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#9765]
### Your GTNH Discord Username

TimeConqueror#5294

### Your Pack Version

2.1.2.2FQ2

### Your Server

private

### Type of Server

Thermos

### Your Actions

Placed Crafting Station next to Arcane Worktable. Arcane Worktable was empty. Then placed the LV Machine Hull recipe ingredients inside the Crafting Station. Clicked on the result with Shift. Crashed.
![image](https://user-images.githubusercontent.com/25156941/154563900-8bd33cc4-26bf-4744-ad61-645017d66a24.png)

Upd:
If you try to LMB with Shift onto the item in the crafting grid of the Crafting Station, you will crash the game too.
### Crash Report

[crash-2022-02-17_23.10.51-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8091946/crash-2022-02-17_23.10.51-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by eigenraven** [comment]
Should be fixed by recent slot numbering logic rewrite in the crafting station
