### ISSUE TITLE
Quest #2409 contains deleted Item

### ISSUE THREAD

**Issue by ChrisLua** [GTNewHorizons/GT-New-Horizons-Modpack#9768]
### Your GTNH Discord Username

ChrisLua

### Your Pack Version

2.1.2.2

### Your Server

private dedicated server with friends

### Type of Server

Vanilla Forge

### Your Expectation

The quest request to have 7 Xenotine Dust #8618. But its not possible to aquiere some.
Quest is currently uncompletebale. The "Xenotine Dust" #8618 was deleted.

### The Reality

The "Xenotine Dust" #8618 was deleted....

### Your Proposal

Update Quest #2409 "Even Rarer Earths" to current outputs. 
Just remove Xenotine Dust from requested outputs. 
to be fair: maybe remove "acient granite dust" #7691 aswell. because its an output of Rare Earth 2 in HV Voltage.
(Its an MV Quest) but anyways its possible to aquirre sooner or later.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TwoTailedFox** [comment]
This has regressed since 2.1.2.4-dev18, and 2.1.2.4-dev25 once again includes the quest in its previous configuration.

**Comment by miozune** [comment]
Did you run `/bq_admin default load`?

**Comment by TwoTailedFox** [comment]
Ignore me, I forgot I needed to run that.
