### ISSUE TITLE
Reimplement Item Slot-Based Config Priority

### ISSUE THREAD

**Issue by Aurastorm** [GTNewHorizons/GT-New-Horizons-Modpack#9769]
### Your GTNH Discord Username

Aura#0696

### Your Pack Version

2.1.2.0

### Your Proposal

Allow GT machines to prioritize what config is used based on what item slot the configured circuit is located. In the case of single-blocks where the ghost circuit is used, I'd say have the ghost circuit take priority. 

### Your Goal

I have a (broken as of 2.1.2.0) setup on my EBF where the input bus has C1, then C11, then any dust, etc. that needs to be smelted. It works on the idea that the EBF (and any other GT machine afaik) looks for valid recipes in reverse order starting from the last slot. Therefore, by placing the C11 after the C1, it allows the EBF to first check to see if it can do a C11 recipe, and if it can't, then to fall back to the C1 recipe.

However, this is no longer the case. Currently, the same, unmodified EBF will _always_ prioritize the C1 recipe, regardless of if I have the fluid to speed up the process or not and regardless of the order of the config circuits in the input bus. This means that, for example, I can't speed up the 143s tungstensteel recipe if C1 is in the EBF, and I then can't process recipes that would fall back to C1 because I want to speed up the aforementioned tungstensteel. 

### Your Vision

The setup described above allows an EBF to be more flexible in its use. It can be supplied with a number of fluids (O, N, Rn, etc.) that can then be used to speed up recipes that have both C1 recipes that take no fluid and C11 recipes that do take a fluid. If some dust can be sped up, then it will. If it can't or the EBF isn't supplied with the right fluid, then it will fall back to the C1 recipe no problem.

This is no longer the case, so now my EBF either needs to be more limited in the scope of its use or it needs to be micromanaged.

Point is, it was useful and I could recommend the setup to others because it was good and added flexibility to one's EBF. Now I can't recommend it, because it doesn't work. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
There is no plan to add an built in mechanism to prioritize one recipe over another. It would make future refactor/optimization impossible.

Leaving this open in case someone found a nonintrusive way of implementing this.

**Comment by mitchej123** [comment]
This used to work because of the sorting of items in the input bus.  I believe that was (Recently?) changed as broke the old behavior.  There was no "priority" before, just that it'd find a certain circuit before the others, and if that had a valid recipe it'd use it.  If it didn't have a valid recipe it'd go to the next circuit.

I can't pinpoint off the top of my head which specific commit changed this, just remember hearing some rumblings about it.

**Comment by bombcar** [comment]
It happened *before* the recipe caching if I remember correctly, but not sure what it was that made it find C1 before C11 again - but maybe it was around that time.

**Comment by Aurastorm** [comment]
Furthermore, if the new system works as I would guess it would (prioritizing C1 and presumably then going up to C2, C3, etc.), then it would force genuinely better recipes like C11 EBF or C24 LCR recipes to be behind the others, instead of letting the player choose the priority by organizing their config circuits themselves. This _isn't adding a priority system_, either, rather quite the opposite, if I understand the new system correctly.

Now, is the use for what I want a bit niche? Yes, I suppose.

Could it be fixed by adding another input bus, ensuring the multi doesn't look across multiple input buses for recipes like how the MEBF or PA work, and having separate item streams for the two inputs? Or simply having 2 EBFs? Yes, _but why? Why_ should I have to do that when the old sorting system gave the player some agency on how recipes would be picked?

The old sorting system allowed the player (if they were careful) to lower the number of machines needed by condensing the functions of said machines. The current one doesn't change this per se, just disallows prioritizing certain configs over others unless you _want_ the lower ones first.

I just really want to know why the change was done. Hopefully someone knows.
