### ISSUE TITLE
double alumite dust whith different recipes

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#9773]
### Your GTNH Discord Username

tom#6482

### Your Pack Version

2.1.2.2qf2

### Your Proposal

when looking it up on nei, gt alumite dust doesn't seem to be craftable in the crafting table from dusts; that recipe is only shown for tcon dust version

![image](https://user-images.githubusercontent.com/8298646/154790932-70c3c8df-e8c3-4c85-ab96-b5d1891fa7db.png)

![image](https://user-images.githubusercontent.com/8298646/154790944-6fe8e95a-8cea-49dc-84f8-be4f4070012b.png)

also, when you craft it, you craft the tcon version that instantly transforms in gt version when you put it in your inventory

### Your Goal

decrease confusion

### Your Vision

i'm blind, so it might just be me being bad at using nei

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Colen** [comment]
<img width="539" alt="Screenshot 2022-02-19 at 07 45 08" src="https://user-images.githubusercontent.com/54497873/154791945-daedf17e-a062-4fbf-aa45-a52689b30697.png">

That said maybe we should remove the alumite from GT: New Horizons and keep the GT one given it seems redundant?

**Comment by Pxx500** [comment]
GT texture is so much better, GTNH dust should be removed imo

**Comment by aka13-404** [comment]
Also, the dust recipe is significantly better than the metallurgy recipe. 
This does not make sense balance-wise.
