### ISSUE TITLE
Open comuters don't load recepies.

### ISSUE THREAD

**Issue by XCCC12** [GTNewHorizons/GT-New-Horizons-Modpack#9774]
### Your Pack Version

2.1.2.2QF

### Your Server

SP

### Your Expectation

I did reinstal but still the same.

### The Reality

After loading the world in the chat I get an error that the open computers recipes were not loaded.

### Your Proposal

Please reapir this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
This is probably fixed in the later versions, you may try http://jenkins.usrv.eu:8080/job/OpenComputers/244/artifact/build/libs/OpenComputers-1.7.10-1.7.5.21-GTNH.jar, in any case those recipies are replaced in core mod.

**Comment by boubou19** [comment]
Quick question tho: is the pack modified with some other mods?

**Comment by XCCC12** [comment]
Optifine

**Comment by boubou19** [comment]
you sure you don't have project e?

**Comment by mitchej123** [comment]
Kacper: We do not support modified instances of GTNH; especially not ones that have added Project E, Thermal Expansion, and modified the included scripts.

**Comment by XCCC12** [comment]
?
You must have mistaken me for someone.
I only have Optifine installed.

**Comment by mitchej123** [comment]
Then post a full log

**Comment by XCCC12** [comment]
I installed opencomputer from the link and the problem is solved.
