### ISSUE TITLE
A Few Questbook Changes, +two TC staves changes

### ISSUE THREAD

**Issue by AcaMetis** [GTNewHorizons/GT-New-Horizons-Modpack#9775]
### Your Pack Version

2.1.2.1

### Your Proposal

Questbook:
- [X] 1: Magic Feather in Novice Thaumaturge requires crafting a Magic Map Focus through the questbook even though a regular recipe exists, but no regular recipe exists for the Magic Map, the quest for which is locked behind Magic Feather; changing Magic Feather to a retrieval task would prevent possible confusion and/or crafting another Magic Map Focus.
- [X] 2: Shake That Booty in HV still mentions the 13% bonus output, which I've been informed and have seen through (admittedly limited) testing no longer exists; changing this text to mention the multiblock needing 4 output buses would also clarify how to craft the multiblock. The quest also requires either the HV Sifter or the HV Macerator quest, when the machine requires an HV Sifter to craft.
- [X] 3: Cough Cough - Something Needs to Be Done About the Smell still claims that pollution is disabled by default.
- [X] 4: Long Distance Item/Fluid Pipeline in LV doesn't mention the newly introduced minimum distance; clarifying that in the quest text would clear possible confusion for people trying to use them around their base as the text suggests.
- [x] 5: A New Alloy - Cobalt Brass in LV has you craft two batches, but the following quest only has you use one and point out that cobalt brass has no other uses; changing the quest to only require one batch would reduce frustration with having to craft needless materials.
- [X] 6: Getting Ready for Tier 2, MV in LV has a typo in it's quest text: "probably be done most of the tab".
- [X] 7: Concentrated Darkness in Advanced Thaumaturgy claims you can get the Eldritch research from "any" type of warp, but my testing showed that temporary warp doesn't work; clarifying that might prevent people from running around needlessly with 50-odd temp warp.
- [X] 8: Even Rarer Earths in MV and Fetching Cubic Zirconia in LuV both reference being able to centrifuge Rare Earth, which was removed; changing the quest text avoids players looking for recipes that don't exist
- [X] 9: Hey DJ, Mix it! in LV suggests using the machine's battery and extra slot to store integrated circuits, but machines now have actual integrated circuits integrated; removing this text removes a reference to an outdated mechanic.
- [x] 10: Silicon in MV requires 36 Silicon Ingots, but the two quests it leads to require four silicon ingots and 32 silicon dust respectively; either changing the requirement to four silicon ingots or changing the text to mention that cooking silicon dioxide into ingots and macerating them afterwards is an efficient MV method of processing silicon dioxide into silicon dust would reduce frustration.
- [X] 11: Carbon Plates in MV mentions carbon plates being needed for the nano armor, but said armor requires multiple HV machines to craft; either moving the quest to HV or changing the quest text to reference solar panels primarily instead of nano armor makes the quest better placed.
- [X] 12: Cheaper Simple Circuit in HV requires the wrong items and in the wrong ratios; changing it to require 6× Good Circuit Board, Simple SoC, Red Alloy Bolt and Fine Copper Wire, and expect that to produce 48 NAND Chips, would make the quest accurate to current recipes and what was crafted in the prior quest.
- [X] 13: Metals from the Earth in Fishing, Farming, Cooking says you can convert the shown crop products directly into tiny dusts, but this is not true for all of them; changing that text would result in less looking for non-existent recipes.
- [X] 14: Endless Evolution in Legendary Quests says you'll only request cores in large batches of 64, but you're getting batches of 16.
- [X] 15: Time to Kill (Fire Golem) in Kill All the Things has a typo in the quest text: "felt out of this world".
- [X] 16: Better than Duct Tape in Multiblock Goals likewise, claiming that the maintenance issue for the screwdriver is "screws are missing" rather than "screws are loose".
- [X] 17: Tungstensteel Coil Upgrade in Multiblock Goals claims that Tungstensteel coils are needed to process Enriched Naquadah, but that requires HSS-G if not Naquadah (depending on the recipe).
- [X] 18: HSS-G Coil Upgrade in the same tab mentions being able to cook Draconium; this takes Naquadah coils.
- [X] 19: HSS-S Coil Upgrade quest text doesn't know what the coils are actually good for, but they are a cheap(er) way to craft LuV superconductors; changing the text would clarify that they're good for, especially since the quest for LuV superconductors was changed recently to require HSS-S Coil Upgrade instead of the Naquadah one.
- [X] 20: TNT in the same tab does not at all mention the possibility of extracting Wood tar from charcoal/building a Pyro oven to generate wood tar to process into Toluene, which is basically an MV method in addition to the LV and HV methods the questbook mentions; adding this text points out another solution to getting Toluene, and gives players another option to pursue.
- [X] 21: ITNT in the same tab mentions that it "doesn't destroy blocks", which is completely wrong; changing the text to mention that ITNT cannot be safely picked back up by hand (trying so just activates it) might prevent unnecessary explosions, as well as pointing out that an Equal Trade wand focus _can_ be used to pick it back up safely (though the focus needs Silk Touch to actually retrieve the block, otherwise it vanishes into thin air).
- [X] 22: Ethenone in MV has a redundant retrieval task of a MV Chemical Reactor, since unlocking the quest requires completing Chemical Lessons, Part Two, which is retrieving a MV Chemical Reactor; removing the retrieval might save a player from having to break/replace their only MV Chemical reactor depending on how early the quest is done. The quest text also mentions "saving" some Ethenone for HV, when it serves basically no purpose other than being turned into Cetane, which is an HV recipe.
- [X] 23: EV Battery Buffer in EV is gated behind the Molecular Transformer, when neither the battery buffer, the GT++ EV battery cluster or Lapotron crystals need the Molecular Transformer to craft.
- [X] 24: Making Sense of Spaghetti in Building a Better Base requires the LV Assembling Machine quest, but actually crafting the dye to fill spray cans requires an MV chemical reactor; changing the quest to _consume_ 3 empty cans and eight red, blue and yellow dye will make the quest consistent with other quests that provide useful tools early, and not leave the player with an empty spray can they can't fill with any dye until MV. In addition Paint-by-Numbers in ZPM points out that you can dye cables with a buildcraft paintbrush, which doesn't even require steam machines to craft. This information may be more timely to point out in the spray can quest rather than in the ZPM tab.

TC Staffs:
- [ ] 1: The Necromantic Staff Core can be crafted, but there's no recipe to turn it into a staff or staffter, making it useless; adding recipes would make the item usable.
- [ ] 2: The Primal Staff Core can only be crafted into staffters, not actual staves that are able to use wand foci, rendering one of the main benefits of crafting the Primal Staff Core (+1 Potency for wand foci) meaningless; adding staff recipes would give the item much greater use.

### Your Goal

To improve the questbook.

### Your Vision

Since I don't want to type another essay and I doubt people would want to read it, generally speaking: Better questbook, better experience for the player.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NoX-programer** [comment]
About step # 12: looks like recipe has changed, but the quest Cheaper Simple Circuit is requires Fine **Tin** Wire, but actually there is Fine **Copper** / **Annealed Copper** Wire in the recipe.
