### ISSUE TITLE
vivecraft optional support

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#9776]
### Your GTNH Discord Username

ngar

### Your Pack Version

2.1.1

### Mod Name

vivecraft

### The Mod to Add

I tried to add vivecraft to GTNH Modpack, but does not work.
It would be great to "be" in industrial halls, space stations,... by 3d as an option (for single player)

### Your Reason

try 3d at minecraft and feel how to climb mountains, dig in caves or hunting. It is impressive - but with GT it will be THE NEW REAL WORLD ;-)

### Preliminary Investigation

It conflicts why I ask to implement it by modding professionals GTNH has, as an option

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by mitchej123** [comment]
No intention to officially support it; but feel free to stop by the discord server and chat in #mod-dev  At the very least we need more info other than "it conflicts"  How does it conflict... does it drop any errors? Need some logs.

**Comment by Ngar1** [comment]
Main problem seems to be the "old" optifine version "OptiFine:1.7.10_HD_U_D1" - which do not work with serveral mods and vivecraft base on it.
