### ISSUE TITLE
AE2 backbone cables will not route more than 32 channels from wireless connector blocks

### ISSUE THREAD

**Issue by TNaud** [GTNewHorizons/GT-New-Horizons-Modpack#9779]
### Your GTNH Discord Username

Default#1462

### Your Pack Version

2.1.2.2QF2 with latest dev build of AE2 from github

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to route 86 channels from AE2 Stuff wireless connectors through a backbone cable to my ME controller. Backbone cable is hooked up to controller using 4 regular dense cables.

### The Reality

Backbone cable will route 32 channels max even though it should be all 86. Occasionally it will properly route the full amount, but reloading the world or editing the network in any way causes it to revert to 32. Removing the wireless connector blocks and connecting the backbone directly to the 86 channels works perfectly.

### Your Proposal

Make backbone cables properly recognize and route channels from wireless connectors.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Nt sure I understand the issue from your description. Maybe post a screenshot in creative or at least explain what is connected to what

**Comment by Kiwi233** [comment]
By default, the wireless connector can only transfer 32 channels

**Comment by TNaud** [comment]
![javaw_2022-02-20_01-46-51](https://user-images.githubusercontent.com/35411589/154831887-972921bb-8c46-4c0b-9709-4d324de55766.jpg)
 
This image shows the setup.

Both of these wireless transmitters should be putting 32 channels into the backbone. When I initially built this it worked as intended, and the backbone had 64 channels going through it. As soon as I removed an interface, the backbone went down to 32 channels, and enough interfaces turned off such that the wireless transmitters were only putting 32 channels into the backbone in total. It seems like when the network gets edited the backbone forgets it can handle 128 channels or something like that.

**Comment by repo-alt** [comment]
Ok, I see

**Comment by repo-alt** [comment]
Well, it is not trivial. For now let's postulate that the grid may have just one backbone line. Maybe I'll return to the problem later.

**Comment by repo-alt** [comment]
idk, the case you posted works fine for me, with adding and removing nodes. What does _not_ work is the case where there are 2 separate backbone lines connected with 2 or more wireless connectors, but that is somewhat hard to fix w/o chaging pathfinding even more.
