### ISSUE TITLE
Power Station bugged after updating from 2.1.2.1 to 2.1.2.2QF2

### ISSUE THREAD

**Issue by MrGrey7** [GTNewHorizons/GT-New-Horizons-Modpack#9781]
### Your GTNH Discord Username

MrGrey#8812

### Your Pack Version

2.1.2.2QF2

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

- Opening PSS GUI shows correct AVG in and stored energy values. 
- Stored energy value updates several times a second.
- Whacking the PSS with a soft mallet disables it.

### The Reality

1. "AVG in" always shows 20480 EU even when there are no cables attached. The PSS itself has 4 EV hatches.
![62c26-clip-13kb](https://user-images.githubusercontent.com/41752944/154838289-18cf7e0a-c1a4-45b6-9bce-b259960fe141.png)
2. Once every second stored energy value changes from real value with 100% capacity indicator (even though it's about 60% of total capacity)
![unknown](https://user-images.githubusercontent.com/41752944/154838248-df6d7ffb-ed48-4f62-bf09-ab23017c1146.png)
to no number with 200% capacity
![unknown](https://user-images.githubusercontent.com/41752944/154838265-01846b6c-8cf8-4e5c-b832-44c119536ae7.png)
 3. Trying to turn PSS off with a soft mallet has no effect on it. Whacking it produces in chat log "Machine disabled" but Waila, portable scanner and PSS GUI show that machine is active. Whacking it again declared "Machine enabled" while changing nothing. Waila always shows 0/10 sec progress on PSS. The only way I've found to disable it is to wrench part of the structure.
 4. Wrenching PSS control block and placing it again changes GUI bug from switching between "real number 100%" <-> "no number 200%" to "[fresh almost empty PSS 0%](https://cdn.discordapp.com/attachments/401118216228831252/944888077367775282/unknown.png)" <-> "[real number 100%](https://cdn.discordapp.com/attachments/401118216228831252/944888023785562132/unknown.png)".
 Turning on energy input seems to increase either the number currently showing or both numbers simultaneously. The same goes for PSS innate energy decay.
Getting the stored EU value using OC brings a completely different value:
![a835d-clip-1kb](https://user-images.githubusercontent.com/41752944/154841988-990f0216-cadd-44a6-a886-bf288dbac3ed.png)
.

### Your Proposal

Fix GUI and return the ability to turn PSS off.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole

**Comment by TrainerSnow** [comment]
Yo i have the same issue, here a vid if it helps:



https://user-images.githubusercontent.com/81151019/158806967-13e33e85-9f0a-4c3f-b444-c007f8bc5d33.mp4
