### ISSUE TITLE
Magic Absorber does not properly handle enchanted equipments.

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/GT-New-Horizons-Modpack#9783]
### Your GTNH Discord Username

Gates_ice#4537

### Your Pack Version

2.1.2.1

### Your Server

Self hosted

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://user-images.githubusercontent.com/2586057/154835069-b5336736-fcbe-48f1-9116-51a76564c6ae.png)

Similar to other turbine (Gas, Combustion), the GUI has two slots: IN and OUT. You put cells of fuel into IN slot and it generates power and leave empty cells in OUT slot.

The magic absorber is also expected to put enchanted equipments or enchanted books into IN slot, and have enchantments absorbed to generate EU, then leave the plain unenchanted equipments in OUT slot.

### The Reality

The generator generates 0 EU (no internal buffer w/ flaming fire icon) and the equipment remains IN slot, and have their enchantments removed.

Since it's still in IN slot, it can't be taken out by logistics system and clogged the entire automation system.

https://www.youtube.com/watch?v=taXhp-7SLpk

With some experiments, the issue happens when internal buffer is almost full. Seems like when the EU value of the enchanted item + internal EU buffer > machine's max EU storage, then this happens.

![image](https://user-images.githubusercontent.com/2586057/154841746-54bfb6b1-b89b-495e-b0bb-b1ab9902f016.png)

### Your Proposal

// Described in "Expectiation".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Presumably fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/946
