### ISSUE TITLE
Strange mobs and drops in the twilight forest

### ISSUE THREAD

**Issue by Alessandro404** [GTNewHorizons/GT-New-Horizons-Modpack#9788]
### Your GTNH Discord Username

Alex404#4038

### Your Pack Version

2.1.2.1

### Your Server

Private dedicated server

### Type of Server

Vanilla Forge

### Your Expectation

To have mobs I've tested drop normal things like strings, and to not be completely infested in enderminy (and I think modded witches also)

### The Reality

The Twilight forest is completely invaded by enderminy (enough to hear them everywhere you are and to have at least 2 of them in plain view everywhere you turn) and groups of witches in the uppermost layer. 

Also, Edge spiders drop stacks of potions of various genre (they should not be stackable also, so this is definitely something strange).

### Your Proposal

I would like to know If I'm the only one seeing this, and if its a working as intended situation. At least, if its something to not worry about. 
Oh also Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
first we need to find out if this is custom loot i add via cfg or tf loot

**Comment by CatsLeftEar** [comment]
It has been that way for a very long time, stacked negative effect potions. Mobs are mostly enderminys, concussion creepers and one type of witch
