### ISSUE TITLE
Ore Destruction TC research from Thaumic Bases doesn' work

### ISSUE THREAD

**Issue by dipo33** [GTNewHorizons/GT-New-Horizons-Modpack#9789]
### Your GTNH Discord Username

Dipo#3713

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

Trying to destruct `Ordo Infused Stone` and get 8x `Order Shard`.

### The Reality

When I put my `Ordo Infused Stone` into Thaumatorium, it doesn't even recognize the recipe and doesn't say what essentia it needs. Also tried this in cauldron, put all of the needed essentia in and then the catalyst and it just ate it and didn't produce anything.

Later I have noticed it requires the ThaumCraft version of `Order Infused Stone` and not the GT version.

Same thing applies for other types of infused stones.

Also i found this closed issue, not sure if it is relevant:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3117

### Your Proposal

Make it also work with the GT version of infused stones and produce 8x said shard.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/ThaumicBases/blob/master/src/main/java/tb/init/TBThaumonomicon.java#L224-L225

need to find a way add oredict or gt ores
