### ISSUE TITLE
The quest "Large Heat Exchanger - Fermat's Last" is OP

### ISSUE THREAD

**Issue by MrGrey7** [GTNewHorizons/GT-New-Horizons-Modpack#9795]
### Your GTNH Discord Username

MrGrey#8812

### Your Pack Version

2.1.2.2QF2

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

The quest only requires 30 titanium and 4 EV pumps, but the reward is 3x enchanted IV lootbags. 
It doesn't even require casings, hatches etc.
It's clearly not in line with other quests in EV/IV, some of which are much harder, but reward much less.

### The Reality

![b23c4-clip-83kb](https://user-images.githubusercontent.com/41752944/155149814-c30cb834-6c59-4371-9d5b-14ee760cbce5.png)

### Your Proposal

Tune down the reward or up the requirements.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TrainerSnow** [comment]
I'd rather have it ask for all the structure blocks its needs tbh

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/155813299-9cb7d7ef-59e1-4476-b694-5d7d56dbc288.png)
better

**Comment by Dream-Master** [comment]
btw the tooltip seems to be wrong. Input hatch need a output hatch and the way around when follow the bluish Tec Tech hint blocks
