### ISSUE TITLE
Allow Players to get clay via Hardened clay earlier 

### ISSUE THREAD

**Issue by KingPoisson** [GTNewHorizons/GT-New-Horizons-Modpack#9798]
### Your GTNH Discord Username

KingPoisson#4795

### Your Pack Version

2.1.2.0

### Your Proposal

With a mortar and pestle, you should be able to break down hardened clay into small piles of clay dust.

### Your Goal

It makes a good alternative for players to obtain clay earlier game and makes harden clay a more valued block early game.

### Your Vision

Harden clay would have a use earlier than tier 4 and would allow players an alternative way to get clay and clay dust.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Gateswong** [comment]
Digging clay in early stage is annoying but it probably only require around 20 stacks of clay before you can mass produce clay dust from hardened clay in steam mecerator.

But prior to Tier 4, hardened clay already being useful to produce clay dust in mass amount.

For alternative way to produce clay, I would thinking some hand work to produce clay from mud would be fine.

**Comment by miozune** [comment]
Now that we have optional tasks, you no longer need to collect 1008 clay balls for BBF quest.
