### ISSUE TITLE
Uranium and Plutonium isotopes should use superscript

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9805]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.2

### Your Proposal

Seeing as the modpack is using subscript very well for chemical formulae, it would be remiss if the two Uranium and two Plutonium isotopes didn't also get the same treatment.

Therefore, I propose items specifically tagged as being formed from these isotopes have their tooltips updated as follows:

a) Uranium 238 to show U²³⁸
b) Uranium 235 to show U²³⁵
c) Plutonium 239 to show Pu²³⁹
d) Plutonium 241 to show Pu²⁴¹

### Your Goal

To have Uranium be represented more accurately in its chemical notation. No change to recipes, cosmetic fix.

### Your Vision

More accuracy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
Is this feasible to implement?

**Comment by Ethryan** [comment]
Tested and the appearance of the superscript numbers look bad when added as a chemical tooltip.
