### ISSUE TITLE
Mushroom Stew should stack

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9807]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.2

### Your Proposal

Given that every other food item I've encountered can be stacked, it's weird that this can't be.

### Your Goal

Have Mushroom Stew stack like other food items.

### Your Vision

Making sure unnecessary space is not taken up by having this non-stackable food in inventories.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/952
