### ISSUE TITLE
Some circuit assemblers recipe are broken

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#9810]
### Your GTNH Discord Username

CatsLeftEar#3300

### Your Pack Version

official

### Your Server

Epsilon

### Your Expectation

Some circuit assembling machine recipes use circuits, that are not interchangable, but worse-tier circuits can be used in some variatons of the same recipe. I expect recipe to be able to use both "epoxy" circuits, like this
![image](https://user-images.githubusercontent.com/67397297/155526295-a8486725-43c7-49df-80be-bc148d2f151c.png)

### The Reality

Instead, recipe doesnt work, because there is no recipe with EV and IV epoxy circuits (Elite nanocomputer and Nanoprocessor assembly). There is one recipe with both better circuits (crystalprocessor and nanoprocessor)
![image](https://user-images.githubusercontent.com/67397297/155526508-d1f7ef7e-0e94-42ae-a69d-de0286cd027b.png)
And there are lots of recipes that use lower tier EV circuit (workstation) or lower tier IV circuit (mainframe).
Some recipes use Elite nanocomputer and some use Nanoprocessor assembly, but no recipe with both of them.

### Your Proposal

Make those recipes that allow use of lower tier circuits interchangeable

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Colen** [comment]
🥺 If only we had proper ore dict support.

**Comment by miozune** [comment]
#9611, #9640

**Comment by Dream-Master** [comment]
Who can add proper circuit ordict support to gt code ?
