### ISSUE TITLE
[Suggestion] - Stop Small Ores from dropping Impure Stone Dusts

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#9813]
### Your GTNH Discord Username

Ethryan

### Your Pack Version

All

### Your Proposal

Stop Small Ores from dropping Impure Stone Dusts.

I think the Small Ore Drops are defined [Here](https://github.com/GTNewHorizons/GT5-Unofficial/blob/92c78f346995f7140902f9719daa89d427f61a04/src/main/java/gregtech/common/blocks/GT_TileEntity_Ores.java#L255-#L278), but i'm not sure.

### Your Goal

Make it so that Stone dusts can only take up 1 inventory slot instead of 2, and also helps reduce the need for washing stone dust in a cauldron early game when making concrete.

### Your Vision

Less inventory clutter after mining small ores, IE all impure dusts got side products that are useful.

Stone, Netherrack, Granite, Marble and so on only drops a tiny pile of itself when cleaned in a washer.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
I dislike this change. If the option for centrifuging Stone Dusts wasn't enabled, this might make sense, but Stone Dusts being centrifuged into very useful metals and dusts actually now shifts Stone Dusts to being very desirable. Plus, storage options for these are plentiful.

**Comment by Ethryan** [comment]
You would still get Stone dusts, just not the Impure variant of them.

**Comment by TwoTailedFox** [comment]
But Impure means extra chance for more stone dusts.

**Comment by Ethryan** [comment]
Stick cobble in a macerator and you got stone dust too. Hook it up to a cobble gen and you got unlimited stone dust much easier.
