### ISSUE TITLE
Strange bug with NEI

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9814]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Opened MultiMC and started GT New Horizons (not the first time), loaded the world and the NEI doesnt show items at all. Deleting config files and recreating it on the start of minecraft helped me, but on the second load of modpack it shows again like that. 

My modpack is NewHorizons 2.1.2.1 plus FTB Utilities/FTB Library new horizons latest versions plus Somnia (mcmod.info doesnt have info about Somnia's version probably the latest)

Please fix this bug if possible

![horizons bug strange](https://user-images.githubusercontent.com/29717217/155731341-689012f2-17c6-41ac-87da-269836e96174.png)

### The Reality

Everything written in Expectations.

### Your Proposal

Everything written in Expectations.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Try right click the search box.

**Comment by bombcar** [comment]
Also, NEI will be blank if you "open it too fast" after load in, as it processes recipes in a separate thread.

**Comment by MadRatSRP** [comment]
I tried closing it and opening again by pressing "O", it stays the same, will try things above later

**Comment by slprime** [comment]
maybe disabled substes.

**Comment by MadRatSRP** [comment]
I started minecraft today and now it works, but i think that this bug may reappear in my instance next time. I didnt hide anything or disabled anything in settings of NEI for it to hide items yesterday

**Comment by MadRatSRP** [comment]
so after 18 days it happened again :D i dunno why
![bug again horizons](https://user-images.githubusercontent.com/29717217/158472141-79298a76-115b-44c1-9346-41d30e969773.png)

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
