### ISSUE TITLE
nuggets to ingot recipe in compressor only for wrought iron

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#9816]
### Your GTNH Discord Username

tom#6482

### Your Pack Version

2.1.2.2qf2

### Your Proposal

the compressor can turn wrought iron nuggets into ingots, but not normal iron nuggets or gold nuggets. make it so that either the compressor does all of the nugget->ingot recipes or none (or only the "soft metals" or whatever the alloy smleter does

### Your Goal

make stuff more coerent

### Your Vision

more uniformed recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ethryan** [comment]
Wrought iron is neede for Steel, And Steel is needed for Molds, that's the only reason the compressor can compress wrought nuggets to ingots.

**Comment by Dream-Master** [comment]
Yes i agree this isnt the reson. I planing to add the tinkers mold forms in alloy smelter to use for ingots and remove them from compressor
