### ISSUE TITLE
Change recipes using Circuit 0 in their recipes

### ISSUE THREAD

**Issue by lordclips** [GTNewHorizons/GT-New-Horizons-Modpack#9818]
### Your GTNH Discord Username

LordClips#3173

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

No circuit 0 recipes.

### The Reality

There are a handful of recipes that use Circuit 0 recipes (which I've been told is unintentional, also I checked and at least the Cyclotron recipes still exist in 2.1.2.2).

### Your Proposal

Change the recipes to not use Circuit 0.

List of recipes:

Cyclotron:
- Molten Plutonium 239 -> 90 SR pellet
- Molten Uranium 235 -> 90 SR pellet
- Molten Plutonium 238 -> 238 PU pellet
- Molten Uranium 233 -> 90 SR pellet
- Molten Americium -> 241 AM pellet
- Molten Bismuth -> 210 PO pellet

Centrifuge (Multi and Single):
- Seaweed Broth -> T Ceti E Seaweed

Assembler:
- 34 different ztones tile recipes that I am not manually listing
- Cobalt Dust + Molten Aluminium -> Hint 1 Dot

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
Cyclotron recipes using 0 is intentional.

**Comment by mitchej123** [comment]
> Cyclotron recipes using 0 is intentional.

Why?

**Comment by mitchej123** [comment]
Is there even a way to reset a circuit to code 0 without recrafting it?

**Comment by draknyte1** [comment]
Circuit programmer does. 
As to why, because I made the recipe and wanted to use 0. It’s a valid circuit, just cause nobody else uses it doesn’t make it anything less than that.

**Comment by Dream-Master** [comment]
Circuit 0 should be the default setting not used for any recipe

**Comment by Dream-Master** [comment]
going now through the other mods

**Comment by cainiaojun** [comment]
No circuit 0 in Component Assline.
Version 2.2.7
All Electric Motor after LuV need a circuit 0 to craft in Component Assline. Remove it plz.

**Comment by chochem** [comment]
> No circuit 0 in Component Assline. Version 2.2.7 All Electric Motor after LuV need a circuit 0 to craft in Component Assline. Remove it plz.

make a new ticket then please, don't comment on an old completed one.

**Comment by cainiaojun** [comment]
> > No circuit 0 in Component Assline. Version 2.2.7 All Electric Motor after LuV need a circuit 0 to craft in Component Assline. Remove it plz.
> 
> make a new ticket then please, don't comment on an old completed one.

get it
