### ISSUE TITLE
game crashed due to enderio not being compatible with ae2

### ISSUE THREAD

**Issue by BoostShoes** [GTNewHorizons/GT-New-Horizons-Modpack#9820]
### Your Pack Version

2.1.2.1

### Your Server

no server

### Your Actions

launched the game and got a crash report

### Crash Report

EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (@aeversion@ from appliedenergistics2-1.7.10-rv3-beta-66-GTNH.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by repo-alt** [comment]
There is still that warning in EIO? should remove that...
