### ISSUE TITLE
EBF not respecting Circuit Slot in Control Block 

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9823]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The Control Block includes a slot in the upper right used for a circuit to be placed in lieu of the Input Bus

### The Reality

The Multiblock is not recognising this circuit being inserted.

### Your Proposal

Either ensure the slot is checked correctly for a circuit, or replace it with the same self-configurable circuit option available on standard machine blocks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by riking** [comment]
The EBF and LCR use circuits in the input bus. This ends up being nicer for anyone attempting to switch out the circuit.
