### ISSUE TITLE
ME Interface doesnt have enough speed for inputting resources into ME

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#9826]
### Your GTNH Discord Username

CatsLeftEar#3300

### Your Pack Version

official

### Your Proposal

Now it is impossible to transfer items for patterns between ME Interface and mechanisms, because as soon as crafted item goes into ME interface, it gets transfered by conduit back into the mechanism. This can be fixed by filters, but sometimes it is almost impossible to implement. Basically now the mechanism has to be exactly near the interface to work properly.
Proposal is to make ME interfaces transfer items to ME immedeately or forbid conduits take items that are coming to connected interface from pattern recipes

### Your Goal

Make crafting items with ME Interfaces easier, let players have more possibilities with item conduits and ME interface

### Your Vision

It will be much more comfortable

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
![3FD789EA-FA5E-4D5B-8B59-9B0DF1DEA494](https://user-images.githubusercontent.com/64365566/155871207-abc67be8-59b6-4ab4-8a85-dac893ffd782.jpeg)

**Comment by repo-alt** [comment]
Output to the different interface? It's not like there is a shortage of channels. You can also use an ME output bus, which is designed exactly to handle unlimited throughput.

**Comment by boubou19** [comment]
honestly it seems you are doing something wrong. if the conduits catch the input of your interface, then simply change the channel color on the conduits.

**Comment by repo-alt** [comment]
It won't help if he unconditionally imports from the interface. In that case conduit may put stuff into interface and extract it within one tick.

**Comment by CatsLeftEar** [comment]
> It won't help if he unconditionally imports from the interface. In that case conduit may put stuff into interface and extract it within one tick.

Exactly. However, i completely forgot about import buses, so the issue can be closed
