### ISSUE TITLE
RFC: Dislocation focus blacklist

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#9827]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

2.1.1.4qf2

### Your Proposal

TT Dislocation focus breaks some stuff, and allows some expoilts while dislocating. So I propose to add to the blacklist:

- Aura Nodes (both nornal and energized)
- EIO conduits
- Filing cabinets

Add your candidates below.

### Your Goal

^

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by CatsLeftEar** [comment]
but it works fine with conduits?

**Comment by repo-alt** [comment]
@boubou19 why did you want to blacklist conduits?

**Comment by repo-alt** [comment]
(probably sometimes it breaks and there is no way to predict that)

**Comment by repo-alt** [comment]
Related issues:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9669
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9668

**Comment by yukieiji** [comment]
Matrix Frame(AE2)
ME Drive
ME Chest
ME IO Port
Spatial IO Port
ME Security Terminal
Blast resistant ME Drive
Ichor jar
Ichor Void jar
Thaumium Reinforced Jar
Thaumium Reinforced Void Jar

**Comment by yukieiji** [comment]
I think this issue also exists in BM Teleposer

**Comment by repo-alt** [comment]
```"teleposer blacklist" {
    # Stops specified blocks from being teleposed. Put entries on new lines. Valid syntax is: 
    # modid:blockname:meta
    S:Blacklist <
        minecraft:bedrock
        minecraft:end_portal
        minecraft:end_portal_frame
        HardcoreEnderExpansion:transport_beacon
        Thaumcraft:blockPortalEldritch
        Thaumcraft:blockEldritchNothing
        ThaumicHorizons:vortexTH
        appliedenergistics2:tile.BlockMatrixFrame
        avaritiaddons:CompressedChest
        avaritiaddons:InfinityChest
        gregtech:gt.blockmachines
     >
}
```
Teleposer is somewhat safer regarding large storage (I don't understand why compressed chest is blacklisted), because it doesn't write stuff to player NBT

**Comment by LewisSaber** [comment]
why not to blacklist entire ae

**Comment by boubou19** [comment]
@repo-alt i'd prefer not explain why here, if you know what i mean 😄
