### ISSUE TITLE
new nei, there is no mechanism where objects can be used (furnace)

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#9829]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.2.1 + NotEnoughItems-1.7.10-2.2.7-GTNH-2-g269b16a.jar

### Your Server

Server Zvezdolet

### Your Expectation

looked at where to remelt the ignot or any recipe that used in furnace

### The Reality

Nei does not show the nether furnace from natura 
![image](https://user-images.githubusercontent.com/17906427/155906181-3e8db99a-9817-4c0e-9f7c-a18f43ea4e12.png)
![image](https://user-images.githubusercontent.com/17906427/155906191-ac75fe14-dec5-48e5-b5bb-9ba33e959a8b.png)

### Your Proposal

add a furnace to Nei

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Nether furnace have no additional recipes they use the furnace map as well. Or i am wrong ?

**Comment by Dream-Master** [comment]
@miozune maybe you can add additional mod support.

**Comment by bombcar** [comment]
I think nether furnace is identical to normal furnace and therefore may not appear (or maybe only appears if on latest everything?)

**Comment by Zereff06** [comment]
Basically the furnace is the same, but it uses half as much fuel (x2 production with same fuel)
Personally, I do not care whether you add or not, decide for yourself, my duty to inform you was done :)
