### ISSUE TITLE
Crafting Iron Caps for ThaumCraft shows false recipie in Thaumonomicon

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#9830]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

~~2.1.1.0~~ -- correct Version: 2.1.2.0

### Your Server

private mp server

### Type of Server

Vanilla Forge

### Your Expectation

Refering to the following image it should be craftable like stated in the Thaumonomicon:

![image](https://user-images.githubusercontent.com/1703441/155908241-2f6e0f59-8b3c-4cab-bc15-5569f8561103.png)

### The Reality

Well, tbh I assumed that it wouldn't work out well and looking up NEI/JEI (what ever you prefer to name it) it cames out that the recipie is different:

![image](https://user-images.githubusercontent.com/1703441/155908297-f335be77-2806-4569-bc16-c8bd7f825a61.png)

### Your Proposal

I assume that the recipie in NEI should be used but then the recipie in the Thaumonocion should also be altered (incl. all other tweaked recipies so far).

It could confuse not only me if the check out the Thaumonomicon and thinks don't work ;)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Chaoschaot232** [comment]
This problem also applies to the Thaumometer to which has a totaly different recipie shown in NEI/JEI but not in the Thaumonomicon

**Comment by Dream-Master** [comment]
Wasn’t this fixed years ago ?

**Comment by bombcar** [comment]
Reported on 2.1.1.0, probably should be rechecked on 2.1.2.2+ but I think it was fixed.

**Comment by Chaoschaot232** [comment]
Well, I checked the version and mus correct that it is 2.1.2.0 (my bad).
I assumed that the example version given in the formular was the current stable ones ^^

But yes, also in 2.1.2.0 this happened.

**Comment by Chaoschaot232** [comment]
Update: ALso occours on 2.1.2.3qf

**Comment by BritishCynic** [comment]
Issue persists on 2.2.8

**Comment by dhasial** [comment]
Still occurring on 2.3.0

**Comment by dylanlanigansmith** [comment]
Iron Caps cannot be crafted on 2.3.3, the recipe for thaumcraft is removed in Thaumaturgy.zs script but not added back at all, same for the GTNH dreamcraft.itemIronWandCap equiv. Can't progress without them so a bit of a bummer.

**Comment by chochem** [comment]
thats fixed

**Comment by dylanlanigansmith** [comment]
> thats fixed

but there is no NEI recipes, and nothing in the scripts that adds a recipe? and I can't craft it? is it somehow my issue

**Comment by chochem** [comment]
you are on the wrong ticket https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13549

**Comment by dylanlanigansmith** [comment]
> you are on the wrong ticket #13549

thanks, did not show up in search must have been filtering by accident

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/62e78073-9ed8-46ec-beca-5d316a208bb1)
this is on 2.3.4 for example
