### ISSUE TITLE
Add a way to break sunnarium back to sunnarium pieces

### ISSUE THREAD

**Issue by dipo33** [GTNewHorizons/GT-New-Horizons-Modpack#9831]
### Your GTNH Discord Username

Dipo#3713

### Your Pack Version

2.1.2.2QF2

### Your Proposal

Add a way to break a whole sunnarium back to sunnarium pieces.

### Your Goal

As of change in 2.1.2.2QF2 where old Molecular Transformer was removed and replaced by a new LuV multi-block, a transformation recipe for transforming a glowstone dust to a sunnarium piece was moved to LuV as well, which is basically a big solar panel nerf, since crafting sunnarium pieces pre-LuV requires tons of glowstone blocks.

### Your Vision

Prevent a huge solar panel nerf.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
In the new dev version there is a pre Luv way. 
Alk add a recipe that was able to have sunnarium in hv. In 2.1.2.3 which will be out soon I add it to ev back.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/153 and https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/295
