### ISSUE TITLE
allow interaction when holding large cells 

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#9832]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.2.1

### Your Proposal

You can't do anything with the capsule in your hand. You can't open the chest etc., even this capsule can't be put into the jabba or drawers barrel

### Your Goal

It's very annoying that when you have capsules in your hand, you can't do anything. Also, the fact that you can not put in jabba and drawers barrel is a bug. 

There are analogs from other mods, which may contain a similar amount of liquid, but there is no such thing. Also, there is no such limitation with Voltage Fluid Tank and Quantum Tank

### Your Vision

dissable this messages and  allow the use of inventory and etc with capsules in your hand
![image](https://user-images.githubusercontent.com/17906427/155946975-38f3ef10-0e6a-457f-9315-9124f4896f88.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
This was disabled because of many duping bugs.
If the code will be fixed some day i can re enable the usage key

**Comment by Ethryan** [comment]
Maybe temporairly disable the usage in code instead, so that rightclicking with the cells do nothing.

**Comment by LewisSaber** [comment]
please, i used them a lot and not being able to open terminal while having them in hand is annoying

**Comment by Minepolz320** [comment]
Disable SOUND PLEASE!!!!

**Comment by Dream-Master** [comment]
> Disable SOUND PLEASE!!!!

Nope i like it :P

**Comment by Zereff06** [comment]
.

**Comment by Minepolz320** [comment]
What dupes?
