### ISSUE TITLE
Morpheus Mod not working?

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#9835]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.1.2.0

### Your Server

private mp server

### Type of Server

Vanilla Forge

### Your Expectation

When one person sleeps, the night should end.

### The Reality

Nothing happends. not even any kind of message is shown.

### Your Proposal

I changed within the config that only 25% of players need to sleep to vote for the next day but it seems not to work,

Testet it with normal day/night cycle and with fixed day (you can sleep while it rains and assumes that it's night time but doesn't triggers Morpheus too).

Unsure what is causing this so maybe taking a closer look into this would be nice :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Morpheus works here -are you sure the mod is even loading? Not named `.jars` or something? IF so, provide the most recent log (start server, load in two people, wait night, have one sleep).

**Comment by Chaoschaot232** [comment]
Ok, what ever it caused it vanshied. Maybe it has smth. todo that it doesn't likes it when "gamerule doDaylightCycle false" is active.

Switched twices back to normal Day/Night Cycle and it is now working smoothly :)
