### ISSUE TITLE
Single player duping via logging off and on

### ISSUE THREAD

**Issue by DigitalWino** [GTNewHorizons/GT-New-Horizons-Modpack#9838]
### Your GTNH Discord Username

digitalwino

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Pull items out of machine, log off, log back on, items in inventory and no items in the machine.

### The Reality

If I pull items out of a machine shortly before logging off, when I log back in they will be both in my inventory and still in the machine as well.

### Your Proposal

Find out why machine contents isn't properly saving so that items stop getting duped.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
Please provide a fml-client-latest.log for one such adventure.

**Comment by Glease** [comment]
I'll blame vanilla for now.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1001
