### ISSUE TITLE
Add "Empty" pattern recipe

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#9840]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.2QF-2

### Your Proposal

Add recipe to make pattern with either empty inputs/outputs or with something like bedrock in input and bedrock in output

### Your Goal

I need to place a lot of empty pattern in interface and i dont want to make them by cpattern terminal

### Your Vision

It will make my life easier (and maybe other players too), cuz u cant place totally empty patterns in interface 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LewisSaber** [comment]
As alternative/ add ability to put empty patterns into interface

**Comment by repo-alt** [comment]
Eh, ok, I probably can make it make a whole stack if you hold both shift and control
