### ISSUE TITLE
Update 2.1.2.3 has duplicate mods

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9846]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Client should boot

### The Reality

Client does not boot.

### Your Proposal

AFSU, BinnieMods and Sleeping Bag are affected by this

In client pack, AFSU has 1.2.3-Freeza and 1.2.6-GTNH, Binnie Mods has 2.0.33 and 2.0.34 and Sleeping Bag has 0.1.2 and 0.1.2GTNH.

In server pack, Binnie Mods has 2.0.33 and 2.0.34

A QF should be issued with replacement archives with the older versions of these three mods removed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
will be fixed in a few mins. Just re upload files
