### ISSUE TITLE
The Dyson Swarm is way too difficult to use

### ISSUE THREAD

**Issue by Milesman34** [GTNewHorizons/GT-New-Horizons-Modpack#9850]
### Your GTNH Discord Username

milesman34#2076

### Your Pack Version

2.1.2.3

### Your Proposal

The Dyson Swarm currently, according to calculations (assuming the random number matched the mean) and the tooltips, invariably uses 40%+ of its Dyson Swarm Modules per hour, which, when combined with the Dyson Swarm Module recipe being extremely overtuned and difficult to fully automate, makes it underpowered.

### Your Goal

Make the recipe for the Dyson Swarm Module significantly easier and/or greatly increase how long they last in the multiblock. The power generation could probably be increased too.

Nobody will seriously attempt to use the Dyson Swarm for power in its current state, since it would be _extremely_ difficult to set up passive production of Dyson Swarm Modules, especially when they could invest that effort into Naquadah-based power, or Fusion/Plasma spam, or Compressed Solars.

### Your Vision

This would make one of the endgame power options significantly more viable, as asking the player to passive such an incredibly complex crafting recipe and having 40% of the modules be used up per hour no matter what makes it extremely difficult to use in its current state.

For my calculations, I made a function that calculates the number of remaining modules based on the starting amount and time elapsed (in seconds).

f(16384, 3600)=9191.55
f(16384,7200)=5267.51
f(16384,10800)=3061.63
f(16384,14400)=1791.31

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by glowredman** [comment]
Hmm this is more or less what I feared the most :/
What changes would you suggest? Nearly everything which is mentioned in the controller's tooltip can be adjusted via config.

**Comment by Milesman34** [comment]
> Hmm this is more or less what I feared the most :/
> 
> What changes would you suggest? Nearly everything which is mentioned in the controller's tooltip can be adjusted via config.

I would suggest making it more clear how much power it actually produces in the tooltip. Additionally, the algorithm for module consumption should be changed so that it is actually beneficial to have more modules in at once, or so that you consume modules _much_ more slowly. It is unclear how much power it actually generates, but given the cost, it should probably be several billions at least, and potentially more.

**Comment by glowredman** [comment]
> I would suggest making it more clear how much power it actually produces in the tooltip.

I don't think I can make it much clearer than it is, e.g. I can't just put all the dimensions and their power factors there (they are in a quest, once #9882 is merged)

> Additionally, the algorithm for module consumption should be changed so that it is actually beneficial to have more modules in at once, or so that you consume modules much more slowly.

Having the destruction function "flatten" at the top is counterintuitive becuase more module in space have a higher chance of colliding, so the (imaginary) control software has a harder time controlling each module, while there more modules too.
Reducing the overall chance and/or making the function more linear is certainly possible.

> It is unclear how much power it actually generates, but given the cost, it should probably be several billions at least, and potentially more.

I agree, the EU/t one module is pretty low given how many you need. 
Changing the module recipe could be sensible too, this recipe would reduce the cost and complexity significantly:
![grafik](https://user-images.githubusercontent.com/35727266/157109380-f07551ed-7409-493c-aec5-058d8439d700.png)
Assembler (5s @ UHV):
- 4 Solar Light Splitter
- 4 Dense Silicon Plate
- 8 Ultra High Temperature Resistant Mesh
- 1 Drone Case (Tier 3)
- 1 Emitter (UV)
- 1 Sensor (UV)
- 1 Piko Power IC
- 1 4x Superconductor ZPM Wire
- 9216L Soldering Alloy

**Comment by Milesman34** [comment]
The new recipe seems a lot more reasonable to passive craft, especially since you no longer need to make LuV solars. That seems a lot better, even with the T3 Drone Cases being very challenging to make, since now that is the main hard part and the rest isn't as bad.

**Comment by Phineasor** [comment]
> The new recipe seems a lot more reasonable to passive craft, especially since you no longer need to make LuV solars. That seems a lot better, even with the T3 Drone Cases being very challenging to make, since now that is the main hard part and the rest isn't as bad.

now, all you need is a whole lot of UV circuits instead of biomainframes, its only 224640 UV wetware circuits per day at the best it can do.




> > I would suggest making it more clear how much power it actually produces in the tooltip.
> 
> I don't think I can make it much clearer than it is, e.g. I can't just put all the dimensions and their power factors there (they are in a quest, once #9882 is merged)
> 
> > Additionally, the algorithm for module consumption should be changed so that it is actually beneficial to have more modules in at once, or so that you consume modules much more slowly.
> 
> Having the destruction function "flatten" at the top is counterintuitive because more module in space have a higher chance of colliding, so the (imaginary) control software has a harder time controlling each module, while there more modules too. Reducing the overall chance and/or making the function more linear is certainly possible.
> 

They should basically never collide, the sun is huge, the satellites are small, and there are only 100K of them max, spacex is putting 43K sats in orbit of the Earth and each one is some 100K dollars you cant just build a new satellite array every few hours if it is 40 percent per hour loss like Milesian says, and the Earth is far far smaller

**Comment by glowredman** [comment]
Tbh the existing values are more or less pulled out of thin air as I not even properly entered HV myself. I think the best option is if you guys make suggestion(s) (within reason, e.g. a new module recipe should still take UHT resistant mesh and some sort of solar item) and I see what changes I can make.

**Comment by Phineasor** [comment]
> 

however they are not solar panels, they are reflector, thin giant sheets of foil that reflect light to bigger reflectors.

**Comment by Phineasor** [comment]
what if the solar components are replaced with a bunch of foil, NT perhaps, and the emitter/sensor becomes zpm, and a bunch of carbon nanotubes directly get added for structural support of this giant reflector satellite, along with the lowering of the rate of loss, because 
![image](https://user-images.githubusercontent.com/80113803/159128672-7d47a025-6de8-42f1-b6b3-b843bb54507a.png)
that craft every day is unreasonable

**Comment by glowredman** [comment]
Leaving the recipe the same is more or less the "easiest" way, as everything else can be changed via the config. @Milesman34 and you have not the same opinion regarding the energy/module, he wants to increase it, you want to deccrease it. Another thing to consider is the computation requirement: Currently you have to start supllying the multi with computation if there are more than 777 modules (`(baseComputation/computationFactor)^(1/computationExponent)`). IIrc these values were chosen under the assumption that the player would not have more than 10k unless the base is aimed at building a stargate. The computation requirement should (remain?) appropriate.

**Comment by Phineasor** [comment]
it seems we have come to an agreement that the power output be halved, recipes stay the same and sat destruction check changes form 1 second to 1 hour. :D
