### ISSUE TITLE
problem with the channel allocation of ME Backbone Cable

### ISSUE THREAD

**Issue by isxwzya** [GTNewHorizons/GT-New-Horizons-Modpack#9853]
### Your GTNH Discord Username

isxwzya#3634

### Your Pack Version

2.1.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to use the ME Backbone Cable and found there are something wrong with the allocation of channels in ME Backbone Cable.
when every node less than 28 channels, it works perfectly. when the Backbone Cable has already with more than 50 (about, or the final result more than 78) channels and the next node has extra 29+ channels, the channel allocation will be a mess.

### The Reality

every node less than 28 channels, it works perfectly
![20220304153029](https://user-images.githubusercontent.com/53187968/156719881-67c08743-9d0f-4d3e-be49-b25e0e619c5e.jpg)
![20220304153137](https://user-images.githubusercontent.com/53187968/156719633-ef73b801-d335-41b6-8476-982a38da548f.jpg)
more than 29 channels, the next cable can only get 78 channels)
![20220304153208](https://user-images.githubusercontent.com/53187968/156719824-eaeac191-29ee-4247-a5e0-7ae0c8b6d019.jpg)
![20220304153245](https://user-images.githubusercontent.com/53187968/156719897-c42504a7-9b9a-4d4e-9fce-b6cf5247fd08.jpg)

### Your Proposal

find out why and let it works well.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@repo-alt any idea ?
