### ISSUE TITLE
Most, if not all forms of flight are bugged and do not work

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#9854]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Try to fly by double tap spacing.

### The Reality

You fly for a single tick and drop down as if your flight is disabled.

### Your Proposal

What even caused this? Is this a "feature?"

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
It sounds like you turned off allow-flight in server.properties

**Comment by ScriptedPiky** [comment]
Does that actually arrive in the main build as default? Me and my friend updated and we honestly had no idea this was changed by default

**Comment by Glease** [comment]
You probably don't want to update the server.properties anyway.

**Comment by ScriptedPiky** [comment]
Heh, yeah. Though I have to ultimately wonder why in the end. I'll check back in the morning to see if it was the case, as my friend owns the server and will take some time for now.

**Comment by Elisis** [comment]
Can reproduce this with a clean client

**Comment by GTNH-Colen** [comment]
I just logged into zeta and can't even fly with infinity armour, seems like quite a major bug.

**Comment by Glease** [comment]
Can confirm some unknown mod is setting allowFlight to false unconditionally. For now IC2 jetpack based flight and thaumcraft harness still works.

**Comment by Draco1112** [comment]
for some reason when i use the gt++ in previous zeta version, flight works fine

**Comment by Glease** [comment]
Thanks for the pointer. This is indeed a bug in gtplusplus. I have found the source.

**Comment by Dream-Master** [comment]
@Glease if this is fixed i bring out a new version later.
