### ISSUE TITLE
2.1.2.3 HydroEnergy Crash when using visualizer on controller block

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/GT-New-Horizons-Modpack#9856]
### Your GTNH Discord Username

ZodiacK256B

### Your Pack Version

2.1.2.3 dev

### Your Server

single

### Type of Server

Single Player

### Your Actions

I installed the preview version of GTNH 2.1.2.3 from the discord.

I placed the hydro dam controller down and clicked the block with the multiblock visualizer item to see how to build the multiblock.
Doing so causes the client to crash.

I have attached the crash for review
[crash-2022-03-03_19.43.44-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8185160/crash-2022-03-03_19.43.44-client.txt)
.

### Crash Report

[crash-2022-03-03_19.43.44-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8185167/crash-2022-03-03_19.43.44-client.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8185171/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
This was tectech and is fixedindev (I will tag once https://github.com/GTNewHorizons/HydroEnergy/pull/14 is merged)
