### ISSUE TITLE
A Few Questbook Changes 2: Electric Boogaloo, +2 TC suggestions

### ISSUE THREAD

**Issue by AcaMetis** [GTNewHorizons/GT-New-Horizons-Modpack#9858]
### Your Pack Version

2.1.2.3

### Your Proposal

Questbook:
Tier 0 - Stone Age
- [X] Loot Games: Quest text is outdated, Loot Games now also blows players up with Minesweeper.

Tier 1 - 32 EU (LV)
- [X] Better Gallium and Arsenic Sources: Fails to mention that tiny piles of arsenic dust drops from Twilight Kobolds, and tiny piles of gallium dust drops from Twilight Redcaps/Redcap Sappers, making a mob farm a possible source of these dusts (spawners for either can be found in Hollow Hills, IIRC). Both metals can also be nugget duplicated though a Thaumcraft crucible recipe, the (Taboo) research for which is in Witching Gadgets.

Tier 4 - 2048 EU (EV)
- [X] EV Sunnarium Battery: "They're cheaper (maybe?) than Lapotrons, but cost less (in materials at least) to make" is redundant, and with the Sunnarium changes completely wrong besides.
- [X] Turning A Into B With C: Retrieval task is for an item that has been disabled, rendering this quest and all quests following it (EV Battery Buffer, EV GT++ Batteries, Blue Steel, EV Sunnarium Battery) impossible to complete.

Tier 5 - 8192 EU (IV)
- [X] Ceses Trip: The quest demands three stacks of crushed Quantium ore, but as far as I can find there's no real use for the material until later, so focussing on Naquadah and only mentioning Quantium as something you'll need later streamlines the quest progression.

Tier 7 - 131072 EU (ZPM)
- [X] Lasers Solve Everything: Quest text claims that "only 3 machines support them outside of the ever _wonderful_ TecTech", naming the LSC, MEBF and MVF, but the GT++ PSS can also use laser hatches.

Getting Around Without Dying
- [X] Advanced Heat Exchanger: Retrieval task is incorrect (HV circuits -> EV circuits), quest requirement is nonsensical (Stainless Steel EBF processing AND Integrated Circuit -> Workstations, Your First EV Circuit) for the same reason.
- [X] Armor 2.5: Does not have Blastoff! as a prerequisite like Fancy Armor does, meaning armor made of steel rings requires the quest for steel but armor made of steel plates apparently does not.
- [X] Electric Jetpack: Quest requirement is incomplete (add AND Compress All the Things), as Engine Boosters now require Industrial Diamonds specifically for Advanced Heat Vents.
- [X] Sensor Lens: Quest requirement is off (Integrated Circuit -> Advanced Circuits), as it takes HV circuits to craft, not better LV.

GT++
- [X] EU packets flowing everywhere...: Quest task includes a Maintenance Hatch, but the multiblock does not require such a hatch to form.

Legendary Quests
- [ ] ~~Hello There!: Quest requirement is off (Dimensional Goal: Moon -> On Your Way to Tier 4 DIMs), as the task requires turning in 10 IO Dungeon Bricks and reaching IO requires a T4 rocket.~~

Multiblock Goals
- [X] Compress All the Things: Quest requirement is off (Tier 2 (MV) -> Advanced Circuits), as the HV circuits the controller needs are a little bit into MV.
- [X] The Third Time's the Charm: Quest text is wrong in many places; on the listed benefits 2 should clarify that hatch tier is limited to glass tier+2, 4 is completely wrong and should be correct (this also applies to the LSC's tooltip, which has the same incorrect information), 6 fails to clarify that laser hatches requires UV tier glass at least. On the list of downsides 2 is redundant and should be removed. Finally the quest text mentions using laser hatch equivalents for a minimum LSC build, but for those to work you'd need UV glass, so this detail should be removed.

Novice Thaumaturgy
- [X] Flying Like a Eag - I Mean Raven: "in control settings and, having item, in hand send" -> and, having item in hand, send

Adept Thaumaturgy
- [x] More Durable Screws: Quest text and retrieval task should be changed to Energetic Alloy Screws, as the third tier of wands don't require Titanium anymore.
- [x] It Doesn't Work: The quest text mentions failing to craft third tier wands with Lich Bones, but those wands require Lich Bones. Either change the text to mention staff cores (those do require Hydra Blood) or Silverwood wand cores.
- [x] Magic Staff Core: Quest requirement is off, as the quest wants a Greatwood Staff which requires Energetic Alloy and Lich Bones, but it's gated behind Fiery Blood. I'd suggest either placing the quest behind the Primal Charm quest or changing the quest to require any of the six tier 3 staff cores that do require Fiery Blood, although in the latter case the staff and staffter quests would have to be changed to match.
- [x] A Wizard's Staff Has a Knob on the End/Magic "Staffter": Requires the wrong items (Fiery Blood -> Lich Bones, Titanium Screws -> Energetic Alloy Screws), and shouldn't require Iron Caps as the player likely is able to use better wand caps by that point (and should be encouraged to do so, if not).
- [x] An Awesome Magic Conductor: Quest text references finishing the silverwood wand, but the quest wants Fiery Tears and Tungstensteel Screws, which are required for a silverwood staff.
- [x] Reactor Material: Quest text suggesting using Carminite as a wand conductor, but the only wands that Carminite craft use Enderium or Oriharukon Screws, whereas the quest wants Chrome Screws.
- [x] Iridium Screws: Quest text suggests getting what it says on the tin for better wand shenanigans, but only the Primal Bracelet uses these screws, and they require Snow Queen blood while the quest is gated behind Carminite.
- [x] She Let Go: Quest task wants four Osmium Screws, but Ichor Woven wands require Osmiridium screws.

Space Race
- [ ] ~~RP-1 Rocket Fuel: "In order to properly fuel the T2 rocket, you'll need some RP-1 Rocket Fuel (or for now, just use CBD again)" -> "In order to properly fuel the T3 rocket you'll need some RP-1 Rocket Fuel."~~

Tips and Tricks
- [X] Digging Deeper: "Also look at" -> some kind of explanation as to where and why to look at...whatever?
- [X] Machine Interface Fluid I/O: The first 6) is no longer true; the second 6) can replace the first 6) instead of changing to 9) as a result.
- [X] Moron's Guide to Breeding Better Bees: "But it also a lot of dangerous and useful fun!" -> it's also
- [X] Obtaining Ender Pearls: Quest text fails to mention that Roguelike Dungeons (can?) spawn with an Enderman spawner room, which is a much easier to access source of (Regenerating) Enderman than the End. Relatively speaking.
- [X] Safety First: "or a superconductor (MV+)" is technically correct, but there is are lossless cables for ULV and LV; "any block that emits UE" -> EU

Working with Oil
- [X] Boiler and Super "Fuel: a new kind of generators" -> generator
- [ ] ~~Improved Oil Cracker: "but it caps at HSS-S" -> HSS-G~~
- [X] Generator Power: "the next step is the Large Chemical Engine" -> Large Combustion Engine
- [ ] ~~Generator Power: "There is an equivalent turbine for gases" -> gasses~~

TC changes:
Manasteel and Elementium wand caps are in a questionable and irredeemably awful position in terms of balance, respectively. I'd suggest removing the old infusion recipe for inert manasteel caps, and changing the Inert Manasteel Cap recipe in the Arcane Crafting Table from 5× manasteel nuggets and a token amount of Vis to a gold cap surrounded with Manaweave Cloth and 60 of each primal vis. For Inert Elementium Wand caps I'd suggest changing the Gaia Pylon infusion recipe to require Charged Thaumium caps instead of Charged Void caps, and preferably some kind of pre-T3 rocket plate instead of Naquadah plates. Note that I forgot to check the TC research requirements for Gaia Pylons, so if those require void wand caps that will have to be changed as well.

### Your Goal

The questbook changes are to improve the questbook, the wand cap changes are to make the various wand caps more balanced. As is Manasteel caps are OP as sin, and Elementium so underpowered they can join Terrasteel in the "functionally just clutter" tier of items.

### Your Vision

Manasteel wand caps have the same vis discount and crafting cost as Thaumium and Vinteum, but the current 5 nuggets+ token Vis recipe makes them by far the cheapest to craft. Changing the recipe to a require eight Manaweave Cloth greatly increases the mana investment to get each cap, and increasing the vis cost to 60 not only greatly increases the vis cost, but also gates them behind either Satin Entwined Greatwood Wands (a nice reward for someone who went looking for better wand caps, and accepted the Warp to get it), Infusion to get high enough vis discounts, or a Greatwood Scepter. If this is not enough setting the cost to 100 Vis means a gold banded greatwood scepter and most of the best pre-infusion discount gear is just barely able to craft one if completely filled with Vis, although 100 vis per wand cap would be slightly crazy. Either way the intent is to give all three wand caps their own niche - Manasteel caps are the cheapest to craft in terms of materials, but require investing into Botania to generate enough mana and a relative _ton_ of vis, as well as a bit of Warp; Vinteum is the simplest as it requires no TC infusion or Botania setup, but does require relatively advanced tech progression in the form of Titanium screws as well as some Warp; Thaumium requires no Warp, no Botania setups or advanced tech progression, but does require infusion and Twilight progression to obtain Knightmetal.

For Elementium likewise the idea to make the wand caps a viable option compared to it's two main competitors, Void and Crimson. Crimson has the benefit of being cheaper to craft wands with, to offset it's very high resource and Warp investment cost, and Void is delightfully cheap and simple once you've gotten the Eldritch Epiphany and all which that entails. Currently Elementium requires Gaia spirits to craft, but Gaia Pylons require two charged void caps each, meaning no matter what you're going to have access to a better alternative than Elementium. Changing the recipe for Gaia Pylons to make it not require void (and so much tech progression it makes getting the Pure Tear, and thus Void/Crimson, entirely without risk if not a foregone conclusion) allows for Elementium caps to act as a void-tier wand cap that requires Botania progression instead of Warp progression.

Whether either set of changes will have the results I intend I cannot say with absolute certainly, but I am confident that it'll result in no worse of a situation that there exists currently if nothing else.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by King65868** [comment]
T3 rocket doesn’t use RP1-rocket fuel

**Comment by Dream-Master** [comment]
If you ask me i would disable fuel complete for Rockets and using Rocket fuel since T1 rockets

**Comment by querns** [comment]
>Legendary Quests
>-Hello There!: Quest requirement is off (Dimensional Goal: Moon -> On Your Way to Tier 4 DIMs), as the task requires turning in 10 IO Dungeon Bricks and reaching IO requires a T4 rocket.

I think this is fine the way it is. By letting the player know that you'll eventually need the dungeon bricks early, an attentive player can remember to gather them when they go to the dungeon for the first time.

**Comment by TerraSleet** [comment]
> -Advanced Heat Exchanger: Retrieval task is incorrect (HV circuits -> EV circuits), quest requirement is nonsensical (Stainless Steel EBF processing AND Integrated Circuit -> Workstations, Your First EV Circuit) for the same reason.

Just ran into this issue ingame while trying to make nano armor in early HV. It seems at some point the Advanced Heat Exchanger recipe was changed without considering its use in Nightvision goggles, which is needed for the nano helmet, thus it's now locked behind EV circuits which is a fair bit further in progression than the rest of the nanosuit set. I suggest adjusting the NV goggles recipe to require Component Heat Exchangers instead of Advanced ones before updating the quest.

**Comment by Cleista** [comment]
Users on my server reported this as well. Nightvision Goggles quest instructions do not match actual recipe

Quest asks for HV circuits
![image](https://user-images.githubusercontent.com/67157844/167508907-4055fdb5-4112-4202-b57c-d07ee805d557.png)

Recipe requires EV circuits
![image](https://user-images.githubusercontent.com/67157844/167508798-5f4a6af1-e5e3-4e92-bbb3-ecbd9644e01f.png)

**Comment by Dream-Master** [comment]
yea recipe was changed but quests not so far.

**Comment by miozune** [comment]
> Improved Oil Cracker: "but it caps at HSS-S" -> HSS-G

This is not correct, if coil tier equals to 4 (HSS-S), EU/t multiplier equals to 0.5
https://github.com/GTNewHorizons/GT5-Unofficial/blob/ad7c01f2284c6b0d0fc9838d74321bce58eeb8ba/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OilCracker.java#L163-L169

**Comment by miozune** [comment]
> both gases and gasses are acceptable plural forms of gas.

https://www.dictionary.com/e/gases-or-gasses/
