### ISSUE TITLE
Add cyclopentadiene to wood tar distillation tower recipe

### ISSUE THREAD

**Issue by CharlieTuna8** [GTNewHorizons/GT-New-Horizons-Modpack#9859]
### Your GTNH Discord Username

Charlie Tuna#7949

### Your Pack Version

2.1.2.3

### Your Proposal

Wood tar can be distilled into: creosote oil, phenol, benzene, toluene, dimethylbenzene and cyclopentadiene. I'd imagine you would get all of these when processing wood tar in a distillation tower and not just the first 5.

### Your Goal

It feels like this was an oversight and this would make it more in-line with other distillation tower recipes since all recipes that I know of give all the possible distillation products.

### Your Vision

More in-line with other recipes, looks weird if one is different for no good reason.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
cyclopentadiene is used in which process ? I mean if i add it which use it can have in mc ?

**Comment by CharlieTuna8** [comment]
Required for making ferrocene which is required for several jet fuels.

**Comment by Dream-Master** [comment]
@CharlieTuna8 . If we need more recipes just add this here so i can add it later into gt code

**Comment by CharlieTuna8** [comment]
The problem is that currently the only way to get cyclopentadiene is by putting either coal tar oil or wood tar in a singleblock distillery. This makes no sense since wood tar can be put in a distillation tower to yield the other 5 products wood tar can be distilled into. Wood tar in a distillation tower should yield all products that a singleblock distillery can turn wood tar into separately.

**Comment by Dream-Master** [comment]
ok will check

**Comment by LazyFleshWasTaken** [comment]
Not sure if this was done, cuz bot says compelted, but I'm on 2.5.1, and cyclopentadiene is still a singleblock only recipe.
