### ISSUE TITLE
Maceration stack casing has no recipe

### ISSUE THREAD

**Issue by Sslimmm** [GTNewHorizons/GT-New-Horizons-Modpack#9860]
### Your GTNH Discord Username

Sslim#6478

### Your Pack Version

2.1.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Tried to check the Maceration stack casing recipe on NEI

### The Reality

There is no recipe  
### Your Proposal

add a recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/159

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/148
