### ISSUE TITLE
Can't Assemble EV Neutron Accelerator

### ISSUE THREAD

**Issue by noah12frost** [GTNewHorizons/GT-New-Horizons-Modpack#9863]
### Your GTNH Discord Username

noah12frost

### Your Pack Version

2.1.2.0

### Your Server

Private Server

### Type of Server

Don't know

### Your Expectation

We tried to make the ev neutron accelerator in an ev and iv assembly machine as per stated by the recipe.
![image](https://user-images.githubusercontent.com/60112498/156859713-e4a6ae45-c279-4765-be17-61cb33f2dc43.png)

### The Reality

The machine did not start running - double checked machine for power and made sure we had the correct rubber in.

### Your Proposal

I think the recipe is either broken or inactive for some reason.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
is only the ev one broken or all of them are uncraftable?
