### ISSUE TITLE
infusion claw depletes undepletable wands

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9873]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

When i put an orichalcum studded cosmic neutronium wand in an influsion claw, i expect it to be left undepleted, like in any other situation involving vis usage on this wand.

### The Reality

it depletes:
![2022-03-05_23 21 54](https://user-images.githubusercontent.com/12850933/156901739-fd2126e4-c355-4d01-a30e-00930b780f6d.png)

taking it back, closing the inventory, and putting again into the claw makes the wand instantly get back its vis storage. But this is annoying in infusion altars used constantly.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
It's because the recharge mechanic on the wand is gated to actual playerentities through some event, putting it in a dynamism tablet has a similar effect when using foci for example.

**Comment by Quetz4l** [comment]
Now you can charge the wand from a node, I think the issue can be closed
