### ISSUE TITLE
You can add more than one item in NEI bookmarks

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#9875]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Hey, there's meant to only be one, right?

### The Reality

![image](https://user-images.githubusercontent.com/41557212/156911102-c1fa8fbf-3064-485c-83e7-5b66c27effe2.png)
How to pull it off: Click a or whatever button that bookmarks it on recipe usage A. Find it have another recipe usage in B or C or D or G or something, you now have more than one unless you A/hotkey bookmark on the item again or in the original recipe output from usage A or the such

### Your Proposal

It's pretty wack but also a minor bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
This is a feature, not a bug. And can be disabled via config, `saveCurrentRecipeInBookmarksEnabled`.

**Comment by ScriptedPiky** [comment]
Ohhhh heh, ah whoops, didn't think that was on by default.

**Comment by repo-alt** [comment]
That is really usefiul stuff actually, it should be on by default
