### ISSUE TITLE
GT++ molecular transformer miss recipes

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#9879]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Recipes are not visible in NEI and Multiblock cant do any of the adv solar panel MT recipes

### The Reality

---

### Your Proposal

Fix it already bruh

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@miozune the recipe map seems to be bugged.

**Comment by GTNH-Afx237v7** [comment]
Not working with GT-PlusPlus-1.7.10-1.7.29-8-gd9bb8c4.jar
Machine can be built, but won't process glowstone dust (tried regular, Ceres, Enceladus and Io glowstone dust) when using ZPM energy hatch.
Using soft mallet gives chat message "machine enabled" or "machine disabled", but using tricorder on controller block always says: "Disabled".

![image](https://user-images.githubusercontent.com/64365566/160074046-1c9e5bfe-7741-4b82-bb2b-b0d92a0426a7.png)

No entries in fml-client-latest.log or Gregtech.log about this machine or it's recipes...

**Comment by GTNHAfx237v7** [comment]
And recipe time is off, too.
Using glowstone dust takes 256 seconds @EV level. When using ZPM voltage it should take 32 seconds, however it takes 16 seconds.

**Comment by GTNHAfx237v7** [comment]
That speed bonus and % indication always confuses me… why not `speed bonus x2` instead?
