### ISSUE TITLE
NEW wailaplugins functions

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#9881]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

2.1.2.3qf

### Your Proposal

add display:
1) crafting time in ticks.
(now when the craft is less than a second it just writes me <1s or 0s)
2) battery charge display.
3) the ability to see the filled capacity and the EU / t rate that enters the battery buffer.

Very handy little thing for the game with which I used WAILA Plugins from a third party project. Since the latest version it stopped working and I appeal to the GTNH volunteers to pay attention to the proposal.

### Your Goal

null

### Your Vision

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by mitchej123** [comment]
> Very handy little thing for the game with which I used WAILA Plugins from a third party project. 

Got a link to it?  

We moved the waila handler into GT5u itself instead of a separate mod.

**Comment by FoKuCNiK** [comment]
https://github.com/GT-IMPACT/WAILAPlugins

I took from the official archive. I didn’t download from github, there may be versions much lower and without these functions

**Comment by mitchej123** [comment]
Take a look through https://github.com/GT-IMPACT/WAILAPlugins/blob/a5e70787452a174e95b7e095f33641c5e4271020/src/main/java/tterrag/wailaplugins/plugins/PluginGregtech5U.java and identify what specifically you'd like added and we can consider it.

If you have a screenshot, feel free to post that with whatever you're interested in circled/highlighted.

**Comment by FoKuCNiK** [comment]
> 


I don't quite understand what you want from me? I have clearly described my suggestion above.

**Comment by mitchej123** [comment]
A screenshot showing what it looks like would be helpful.

**Comment by FoKuCNiK** [comment]
ok

**Comment by FoKuCNiK** [comment]
I'll post a video here after a while.

**Comment by FoKuCNiK** [comment]
https://drive.google.com/file/d/1Izvqac_kZJGF7hAd5K2WemV1ky4CWabQ/view?usp=sharing
