### ISSUE TITLE
 not comfortable enough (NEI OVERCLOCK)

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#9883]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

2.1.2.3qf

### Your Proposal

I want to make it easier to use the new feature that shows the crafting time / energy on different tirs

Let's say I have craft chips for 15 out of 30 pages
I want to look at the recipe in NEI and click on the mechanisms on the left SHIFT + RMB and not be thrown to other pages and I would re-look for the very diagram of the devil where.

I am attaching a video in which you can clearly see how much extra TIME I spend on this action, although I could do it in 1 click on the left

https://drive.google.com/file/d/1Ye6rz_6qsgt6wlFlenvcQZMfmEy7oyMD/view?usp=sharing

### Your Goal

null

### Your Vision

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/pull/240
