### ISSUE TITLE
Unable to craft drawers and upgrade templates

### ISSUE THREAD

**Issue by arbitrarystar** [GTNewHorizons/GT-New-Horizons-Modpack#9888]
### Your GTNH Discord Username

dxzfvzs#1259

### Your Pack Version

2.1.2.3.qf

### Your Server

Private server

### Your Expectation

Trying to craft a drawer according to the old recipe or in assembler resulting in materials being consumed and corresponding drawer or storage upgrade template to be crafted. + for those recipes to show in NEI. 

### The Reality

NEI does not show any crafting recipes for storage upgrade template, nor for any drawers. Only thing it shows is chisell for drawers. 
Putting materials into shaped crafting does not detect any recipe either, same as in assembler. 

-------
This happens both on server, and in the singleplayer world. 

### Your Proposal

Fix of the crafting recipe of vanilla wood drawers and storage upgrade templates. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Elisis** [comment]
Both drawers and upgrade templates seem to have recipes on my instance. Maybe redo your scripts folder?

**Comment by Dream-Master** [comment]
Storage Drawer recipes are inside the code there is no recipe file. Maybe the configs wrong.

**Comment by arbitrarystar** [comment]
I've deleted all old configs and scripts and replaced them by the ones downloaded from [http://downloads.gtnewhorizons.com/ClientPacks/](http://downloads.gtnewhorizons.com/ClientPacks/?fbclid=IwAR35ZPzrPnSmMI0_igyd6Lw79_P23FRVpW4LGSakuHK-Gh38yIEgaGJC5x4) and [http://downloads.gtnewhorizons.com/ServerPacks/](http://downloads.gtnewhorizons.com/ServerPacks/?fbclid=IwAR1ndNgJyNsChj-sXG6wfEZA-ICPSYdalKO7laaj-AfWk0J-Vpsr67aSFMw) (specifically version `2.1.2.3qf`) for both my client and server, neither did help.

Also, i've found this in the server log, i think it's related to this issue, but I have no clue what is causing this.

```
[22:46:14] [Server thread/INFO]: Could not load integration module: com.jaquadro.minecraft.storagedrawers.integration.NotEnoughItems
[22:46:14] [Server thread/INFO]: Could not load integration module: com.jaquadro.minecraft.storagedrawers.integration.GTNHIntegrationModule
```

This is an issue we had since `2.1.2.0`.
This screenshot is from version `2.1.2.2qf2`.
![image](https://user-images.githubusercontent.com/56274079/157311530-35d70e17-730a-49c9-a49f-7474324ea962.png)

The one selected is basic oak drawer, specifically this one:
![image](https://user-images.githubusercontent.com/56274079/157311890-9a6ed302-d184-4c80-b371-b98666b81a02.png)

And this is what it did with shaped crafting:
![image](https://user-images.githubusercontent.com/56274079/157311974-c7551ea2-38b6-40a9-9475-e660559dea39.png)


The exactly same thing happens in `2.1.2.3qf` as well.

**Comment by arbitrarystar** [comment]
In the `fml-client-latest.log` I've also found this, so it's some problem around the project red item:

```
[18:36:14] [Client thread/TRACE] [StorageDrawers/StorageDrawers]: Sending event FMLInitializationEvent to mod StorageDrawers
[18:36:14] [Client thread/TRACE] [FML/StorageDrawers]: Unable to find item with name ProjRed|Integration:projectred.integration.gate
[18:36:14] [Client thread/INFO] [StorageDrawers/StorageDrawers]: Could not load integration module:
```

**Comment by dipo33** [comment]
@arbitrarystar @Dream-Master 

I had the same issue, the problem was mod loading order. Mods with modid `ProjRed|Integration` and `ProjRed|Transmission` were getting loaded after storage drawers, therefore the GTNH integration module was failing, thus not loading the recipes. I've fixed this by changing the storage drawers mod dependencies from `dependencies = "after:waila;` to `dependencies = "after:waila;after:ProjRed|Integration;after:ProjRed|Transmission;"` and rebuilding the mod.

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
