### ISSUE TITLE
Skookum Choocher brake some machines instead of pick up

### ISSUE THREAD

**Issue by Quetz4l** [GTNewHorizons/GT-New-Horizons-Modpack#9890]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.2.1

### Your Server

Server Zvezdolet

### Your Expectation

Pick up Seismic Prospector by Skookum Choocher

### The Reality

i get some tier dust (mv = aluminium)

### Your Proposal

Fix all machines, who may macerate to dust in hammer machine

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Elisis** [comment]
I can replicate this in 2.1.2.3. Maybe it's intended?

**Comment by Zereff06** [comment]
![image](https://user-images.githubusercontent.com/17906427/157224982-9af78d32-81e0-47b8-b78c-c22f92c43289.png)

If you stay that, you need to add ToolTips about it

**Comment by Zereff06** [comment]
Also, this tool fixes the break in multiblocks like a wrench, but not like a hammer

**Comment by miozune** [comment]
It's removed now https://github.com/GTNewHorizons/GTplusplus/pull/729
