### ISSUE TITLE
Add a dim blacklist for the demon ritual

### ISSUE THREAD

**Issue by Mumberthrax** [GTNewHorizons/GT-New-Horizons-Modpack#9895]
### Your GTNH Discord Username

Mumberthrax#7662

### Your Pack Version

2.1.2.3qf

### Your Server

zeta

### Type of Server

Don't know

### Your Expectation

I was exploring on the Zeta server. I expected possibly for a structure such as I found to be more modest in size - maybe as big as a vanilla minecraft village, and for its loot chests not to be missing, and the loot to be in the chests and not on the ground.

### The Reality

While exploring I encountered a giant sprawling convoluted loot-filled stone brick structure, and many of its loot chests were missing and the loot spilled on the ground - but had not despawned yet (I observed some items despawn while I was in the area). I did not explore the entirety of it, and I discovered one unique netherbrick+gold structure, and one applied energistics meteor in the area.

When looking at the loot chests that were still intact, WAILA identified them as "Demon's Chest" from Alchemical Wizardry, rather than vanilla minecraft chests. I did not open any of the chests. I did place a lot of the loot I came across on the ground to prevent it despawning, but i am certain I missed most of it in the chunks my player character had loaded since navigating the area was difficult and lighting glitches meant powerful mobs were all about. It all appeared to be very high value loot.

The outer parts of the structure appeared less chaotic, more akin to a village in terms of spacing between buildings. Further in it was almost as if the structure was trying to generate multiple times, so some buildings would be overlapped.

![2022-03-08_01 20 23](https://user-images.githubusercontent.com/4822803/157197394-c2f91dd7-bb76-4b87-92b8-c4f6cd6f2f8b.png)
![2022-03-08_02 16 59](https://user-images.githubusercontent.com/4822803/157197442-77427ca9-3be3-439d-ab36-257c0ef9ba7c.png)
![2022-03-08_02 11 05](https://user-images.githubusercontent.com/4822803/157197477-ca6f22ee-7773-4547-8c57-71e0f4de7bf0.png)
![2022-03-08_02 10 00](https://user-images.githubusercontent.com/4822803/157197519-987d4159-b4d5-4d2f-a7b3-a13ace5aa55f.png)
![2022-03-08_01 40 52](https://user-images.githubusercontent.com/4822803/157197595-08fcf1ef-f082-4ed9-bcd2-f03a1fed95a9.png)
![2022-03-08_01 41 47](https://user-images.githubusercontent.com/4822803/157197651-6dff4d00-bcaf-4d05-840a-68dbc45c0d55.png)
![2022-03-08_02 12 55](https://user-images.githubusercontent.com/4822803/157197717-508a2653-39ef-42b1-84cc-4058bca27060.png)
.

### Your Proposal

Identify the mod the structure is from (I suspect "alchemical wizardry") and find out if it is meant to generate like this naturally, and attempt to generate the structure with only that mod enabled to review for differences/similarities to what is on the Zeta server. Review any changes relating to this mod since previous GTNH modpack updates for any clues on what may have caused this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Barhandar** [comment]
It's someone's Demon Portal, not a natural structure. Blame whoever activated it anywhere within ten thousand blocks of the origin.

**Comment by boubou19** [comment]
why in the world did someone thought it was a great idea to pollute the OW with that? Now that it happened once, i'll have to look into a way of protecting all the ow of the officials.

**Comment by Sphyix** [comment]
I guess that's something important to do @boubou19 
Let's avoid polluting other ow on other servers :P

**Comment by chochem** [comment]
another server just experienced this:
https://discord.com/channels/181078474394566657/234936569360809996/988495463248433203
