### ISSUE TITLE
No Empty Cell generated when emptying Water Cells into Water Tank

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9897]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When emptying a water cell into the Water Tank, an empty cell should be generated in the bottom output.

### The Reality

The water cell is consumed, the water is added to the tank, but no empty cell is generated

### Your Proposal

This should be fixed so that the empty cell is generated. Universal Cells are not affected by this issue and nor are buckets.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TwoTailedFox** [comment]
It would definitely be appreciated

**Comment by TwoTailedFox** [comment]
Similar issue, when depositing Lava Cells into the GT++ Advanced Boiler, the cell is also consumed (When it should be put into the cell above)

**Comment by henrydukepickle** [comment]
Not sure if this is the same bug, but sometimes when filling GT cells with water in a GT tank, it seems to void them. Very annoying for water electrolysis setups.

**Comment by TwoTailedFox** [comment]
This behavior is still present in dev29.

**Comment by eigenraven** [comment]
Fixed by <https://github.com/GTNewHorizons/Railcraft/pull/28>, should be in next dev
