### ISSUE TITLE
Bug in quest "one anvil...better make that two"

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9900]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

So i was crafting 2 anvils for this quest with the crafting station, after i added all the required materials for the 2 anvils into the grid i pressed shift+click to grab 2 anvils and to end quest successfully. Expected: quest completed. Reality: somehow even when both anvils were crafted at the same time, quest counted only one being crafted and it showed 1/2 anvils complete instead of showing 2 anvils complete

### The Reality

none

### Your Proposal

none

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Task 1 is now optional. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9711
