### ISSUE TITLE
possible incorrect world map update

### ISSUE THREAD

**Issue by VasyaOrk** [GTNewHorizons/GT-New-Horizons-Modpack#9902]
### Your GTNH Discord Username

VasyaOrk

### Your Pack Version

2.1.2.3QF (with additional mods)

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Update 2.1.2.2QF2 -->2.1.2.3QF
Use existing map (correctly loaded in 2.1.2.2QF2)
server ack me about fml confirm
In server logs I see an error with block ID and many warnings about incorrect NBT

When I try connect to server - server crash : 
......
Description: Exception ticking world
java.lang.ClassCastException: jds.bibliocraft.tileentities.TileEntityFancySign cannot be cast to vazkii.botania.common.block.tile.TileSpecialFlower
	at vazkii.botania.common.block.BlockSpecialFlower.getLightValue(BlockSpecialFlower.java:120)
.....
Trying to delete additional mods, delete fastcraft, downgrade botania, bibliocraft, netty patch - crash server or, crash both

Create new map (with additional mods, with fastcraft, without downgrades) - correctly created and loaded
Place "FancySign" in world - all work, no crash

I collect some logs in different experiments

https://drive.google.com/file/d/1hHcUIHTJ-Ada9oBFNpzd9AEiygupZp_S/view?usp=sharing

### Crash Report

[crash-2022-03-08_19.56.26-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8208912/crash-2022-03-08_19.56.26-server.txt)
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8208914/fml-server-latest.log)
[level.dat_before_update.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8208930/level.dat_before_update.zip)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by VasyaOrk** [comment]
I find a solution :
unsafe : i delete all content of FML\BlockedItemIds section in my level.dat file
World correctly loaded
safe solution : i can't find (((
---
please, close this issue ... ((((

**Comment by eigenraven** [comment]
this is some block id table corruption, I don't think there's anything we could do here
