### ISSUE TITLE
Change Multi Amper Energy hatches logic

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#9904]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.3QF

### Your Proposal

Change how machines interact with multi Ampere hatches from tec tech
Atm they give machine A * Eu/t power to work with, so with 64A IV enerhy hatch 
you can overclock machine to UV voltage ( 64 * 5192 = 524k eu/t)
My suggestion is :
-Gate recipes to Tier of Hatch + 1 so with 64A iv you can only do luv recipes
but leave logic of overclocking,it means that if u supply machine with 64A IV, it will OC  like if it have UV voltage 

### Your Goal

This will allow to safelly ad Multi Ampere ENergy hatches to All machines without Tierskipping, especially in GT++ machines, that i believe, dont support them because of tierskipping

### Your Vision

Will make pack better

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GlodBlock** [comment]
it's a definitely no if you want a multi amp hatch can run a tier+1 recipe. a 64a iv hatch or a 4096a laser iv hatch is still a iv hatch so it should not run or overclock anything beyond that. the multi amp hatch should only be used for parallel, like you can run 64x iv recipes with a 64a iv hatch.

**Comment by GTNHAfx237v7** [comment]
With 64A IV energy hatch you can run UV recipes in PA but it’s properly gated by needing a UV tier machine inside.

**Comment by GTNH-Colen** [comment]
I'd imagine this is more complex than it first appears given that most multis cannot even handle > 2^31-1 EU/t, even the MEBF fails in this regard still. So that would also need to be addressed given a lot of lasers far exceed this.
