### ISSUE TITLE
any circuit cant work

### ISSUE THREAD

**Issue by kuso2020** [GTNewHorizons/GT-New-Horizons-Modpack#9906]
### Your GTNH Discord Username

KUSO2020#1784

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I want to use any MV circuit to mark the recipe
![屏幕截图 2022-03-09 141602](https://user-images.githubusercontent.com/101241062/157386296-4421c6fa-db26-4904-a105-bffc45b4dafd.jpg)

### The Reality

But ae cant require any MV circuit 
It is that AE cannot recognize this OreDictionary as new item 'any circuit'
![屏幕截图 2022-03-09 141818](https://user-images.githubusercontent.com/101241062/157386418-05b79229-8534-4cd6-a813-b1bb362e2453.jpg)
![屏幕截图 2022-03-09 141925](https://user-images.githubusercontent.com/101241062/157386433-1d2460d2-b41a-46ed-befa-4a865e7e9f46.jpg)

### Your Proposal

I hope it can work in next version

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
This any circuit are helper items and not for crafting. Before oredict not working.
@GlodBlock did you check if you fix work in ae

**Comment by GlodBlock** [comment]
they are used for fix the broken oredict thing in gt recipe generation instead of real use ingame.

**Comment by boubou19** [comment]
can we hide them in nei to avoid confusion like that?

**Comment by riking** [comment]
@kuso2020 You need to encode the exact circuit item that you want ae2 to choose to autocraft.
