### ISSUE TITLE
Stack of Mushroom stew, when eaten, replaces stack with 1 bowl

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9908]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When eating from a stack of Mushroom Stew, the stack should decrease by one with a bowl being added back to the player's inventory

### The Reality

When a stack of Mushroom Stew is eaten, the entire stack is replaced by a single bowl.

### Your Proposal

Fix behavior so that stack can be eaten from without stack being nullified.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Introduced by https://github.com/GTNewHorizons/GT5-Unofficial/pull/952. This increased stacksize but did not consider patching the custom vanilla method that normally gives you the empty bowl back and deletes the whole stack,
```
net.minecraft.item.ItemSoup#onEaten
```
