### ISSUE TITLE
Add a new recipe for sodium bisulfate to save on chlorine and so it isn't just another salt recipe.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9909]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.3QF

### Your Proposal

I was making plastic boards, and I was getting sick of how much chlorine they ate, so I was looking through the recipe and noticed sodium persulfate was another option that didn't contain chlorine, however, on looking down the chain, I noticed that for some reason the only way to make it was with salt, and while this is grounded in reality, there is another way to make it irl that should be exemplified in this pack, that being:

NaOH + H2SO4 → NaHSO4 + H2O

this is the second common formula used irl to make sodium bisulfate and I believe it would be a great addition to the pack, since currently there isn't much of a reason to use sodium persulfate, but the addition of this recipe would allow for some chlorine savings in a tier that is already sapped of chlorine from pretty much everything, including the titanium production line!

### Your Goal

I think that this would give the second plastic board line a small boost that would give it a reason to be used of iron (III) chloride, and for that reason I think we should add this recipe into the game! though if you want to nerf it, gate it at EV or late HV so that you have to use at least some chlorine first!

### Your Vision

I obviously said my vision above this first lmfao.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
Sodium Persulfate is indeed underutilized, but gating this new recipe at a new tier would put it at a situation in which chlorine is much easier to get than before, which would make iron III chloride still the most used alternative. I'll take a look at this and see how the two options could become the easiest for different playstyles.

**Comment by YanFett** [comment]
Can confirm. Once you find iron(III)Chloride sodiumpersulfate is useless. This needs change.

**Comment by cubic-chariot** [comment]
Another option would be making the reaction
- 2x salt + 1000L H2S04 -> 1x NaHS04 (sodium bisulfate) + 1000L HCl

take only one salt instead of two, and adding the reaction
- 1x NaOH + 1000L HCl -> 2000L salt water.

This would make the production of sodium persulfate a chlorine-neutral process.

**Comment by miozune** [comment]
Chlorine is not consumed now due to https://github.com/GTNewHorizons/GT5-Unofficial/pull/1062. Though I cannot find a way to make salt out of chlorine or hydrochloric acid, so adding another recipe is still a thing.

**Comment by POPlol333** [comment]
I'll be taking this later when I'll be done with my work on the SC and the dragonblood
