### ISSUE TITLE
Increasing FPS

### ISSUE THREAD

**Issue by Aintripin** [GTNewHorizons/GT-New-Horizons-Modpack#9910]
### Your GTNH Discord Username

Aintripin#4768

### Your Pack Version

2.1.2.0

### Your Proposal

Increasing FPS by adding a feature from another project:
The project's name is CubixWorld and they got a GregTech server: https://cubixworld.net/servers/gregtech (installation of their launcher is required)
Thing is I get over 100 FPS playing online (usually it's around 120 with it's top of 130) which is significantly higher than playing on any GTNH server. It's also lag-free. I asked a moderator of theirs what is that all about and he said it was their own development. So, it might be on the client's side, I guess? It'd be awesome if you took a look at it 

### Your Goal

Increasing FPS is always a good experience. Sometimes it's barely possible to play this modpack because you're getting some slideshow. Decreasing the load time will positively affect the game exprerience as well

### Your Vision

It will absolutely make this modpack better!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
Do they have a gregtech server? or do they have a GTNH server? Because if it's just a decreased amount of mods then it's normal. Also it's questionnable to have a custom launcher to add mods that touch your game engine. It would be better if you analyze your game with sparks/warmroast/visualvm because we could track down what part of the game is laggy and fix it
