### ISSUE TITLE
Neutron Reflector recipe is bugged, again

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#9912]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3

### Your Server

Private server

### Your Expectation

I try to craft Neutron Reflectors into Thick Neutron Reflectors so I can actually make a fusion reactor. The required recipe needs ID `4230:1`

### The Reality

Creating Neutron Reflectors outputs `4230`, thus, the recipe is impossible 

### Your Proposal

Change recipe so that it doesn't need the extra `:1` there. Also, tone down the amount of Graphite by half for all recipes, cause holy good god this thing eats up so much unnecessary Graphite

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Fixed in dev
