### ISSUE TITLE
Tinkers' parts that are made in part builder are not in NEI

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#9920]
### Your GTNH Discord Username

KiloJoel#3044

### Your Pack Version

2.1.2.3QF

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

basic tinkers part needed in early game should be visible in NEI.

### The Reality

~~The recipes for the thaumium parts don't exist and~~ The parts are not in nei. This is the case for all materials that are used in the part builder - obsidian, netherrack, magical wood, thaumium etc. Even basic stuff like iron, flint!
![image](https://user-images.githubusercontent.com/17787093/157778949-8f3223de-aeb7-4dbc-a052-44df7ce1a7fc.png)

I can't find any issue or discussion about this so I assume it was unintentional.

### Your Proposal

Readd the parts to nei or fix whatever is disabling them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by KiloJoel** [comment]
Ok I'm a moron, totally forgot you make thaumium parts in the part builder. So the recipes do still exist.

However it's still an issue that the parts don't exist in nei, because that would mean people don't know they exist.

**Comment by Dream-Master** [comment]
Check inpure core config maybe the only hidden in nei

**Comment by Dream-Master** [comment]
During the incompatibility guess tinkers gregworks ignore thaumcraft material. Same for gretech (tico oredict and unification is of via cfg)

**Comment by KiloJoel** [comment]
Just noticed this is also a problem for materials processed in the smeltery too. The recipes still exist if you look for them through uses, but the items don't show in NEI. This makes it quite a significant bug.
![image](https://user-images.githubusercontent.com/17787093/160875019-3434d7b7-9566-4f72-a002-f437276012f3.png)
![image](https://user-images.githubusercontent.com/17787093/160875094-2c518756-7ff2-49f9-b732-4b3056113d36.png)

**Comment by ALongStringOfNumbers** [comment]
I am seeing this issues as well on 2.2.0.0 for materials like Obsidian, Steel, Iron, Ardite, etc, which are all shown in the tooltip of the casts.
![2022-10-20_21-13](https://user-images.githubusercontent.com/31759736/197110361-54cfe288-7023-4a0b-a9e3-47946afedab8.png)

Basically any material that is shown in the tooltips of casts like this, I cannot find the corresponding parts in NEI. The only exception is Pig Iron.

**Comment by chochem** [comment]
I changed that ticket a bit, this really isnt about extruders after all. Basic parts like iron/flint (/thaumium) need to be visible in NEI

**Comment by chochem** [comment]
have recipes for the part builder show in NEI would be a bonus

**Comment by YannickMG** [comment]
I always thought they were excluded on purpose as not to spam NEI, but it is annoying that they're missing.

**Comment by boubou19** [comment]
isn't it filtered through inpure core?

**Comment by chochem** [comment]
still a big annoyance that comes up regularly.

@YannickMG you are missing the point.

For example: search for 'iron pickaxe head'. What you will get is 9 different special iron pickaxe heads that nobody ever uses (dark iron, magnetic iron, ...) but NOT the normal iron pickaxe which actually is very important for new players.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/210a32cb-47ac-4dea-8d90-4a9706e0f6a6)

**Comment by Frikkle** [comment]
Additionally, we just noted that NEI displays the recipe for the Pickaxe Head Cast by using a Wooden Pickaxe Head, which has no recipe, which causes confusion amongst new players. Telling them to make a Cobblestone pickaxe head for the cast helps.
