### ISSUE TITLE
make acid battery recharchable

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#9926]
### Your GTNH Discord Username

tom#6482

### Your Pack Version

2.1.2.3qf

### Your Proposal

i think nobody even uses acid batterys.
if one where to use sulfuric acid for energy, he'd probably make an acid generator rather than keeping refilling and emptying batterys.
they also have low capacity, so wouldn't be OP.
it would also make it more realistic, since lead-acid battery are more durable than lithium iirc...?

### Your Goal

make stuff more balanced while also more realistic.

### Your Vision

ha-ha cluster of 16x battery buffers full of sulfuric acid goes brrr (you can already do that whith sodium, probably even easier and cheaper to do).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
go and burn the acid in the acid generator from Bartworks. I add a lv machine for it.
