### ISSUE TITLE
Dragging ghost items from bookmarks makes wrong stack size

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#9932]
### Your GTNH Discord Username

KiloJoel#3044

### Your Pack Version

2.1.2.3QF

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Tried to drag a 64 stack ghost item from the bookmarks section of nei. Expected stack size of 64.

### The Reality

Ghost item stack size was 1 (or maybe 0?)

From search side:
![image](https://user-images.githubusercontent.com/17787093/158000761-3635da62-68f8-4740-a256-b8d7f926d287.png)

From bookmark side:
![image](https://user-images.githubusercontent.com/17787093/158000791-bec839d0-0ad0-412f-bc5b-b9bb967b30de.png)

### Your Proposal

Make ghost items from bookmarks section have the correct stack size.

This may be related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9931 but seems to be a separate bug since the linked issue occurs with ghost items from either side.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by slprime** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/pull/188

**Comment by miozune** [comment]
While this is a feature, I think it should not be applied to "normal" bookmarks. Clicking on right panel and left one behaves differently is not intuitive.

**Comment by KiloJoel** [comment]
I agree. Maybe as a compromise between the two, it could retain the original behaviour for stack size 1 items. And use the bookmarked stack size if it's not 1.

**Comment by miozune** [comment]
More precisely,
bookmarks that has saved with `ctrl` key -> keep stack size (even if its stack size is 1)
ditto without -> give max size

**Comment by slprime** [comment]
I'll think about it

**Comment by KiloJoel** [comment]
Quick extra bit of info. This also affects spawning items in creative as well as creating ghost items.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/240
