### ISSUE TITLE
Crash when click on items in Nei

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#9934]
### Your GTNH Discord Username

DreamMasterXXL

### Your Pack Version

2.1.2.4-dev

### Your Server

SP

### Type of Server

Open To LAN

### Your Actions

Click on a Fuel Bucket game crash

### Crash Report

https://gist.github.com/Dream-Master/2311f9f74455ca05afa452710ee0b1d8
crash
https://gist.github.com/Dream-Master/1039be37b06253816cf608c2cc039fe0
log

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
seems to crash with other items as well
try to look for potin pipe recipe

**Comment by Pxx500** [comment]
I've also encountered a problem when I enter singleplayer and use NEI too early the game will crash, you have to wait a while to use it without a crash, might as well look into that.

**Comment by miozune** [comment]
@Pxx500 's crash might have been fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/200
