### ISSUE TITLE
Crash from PREINITIALIZATION to INITIALIZATION after updating the instance

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#9935]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.1.2.3qf

### Your Server

private mp server

### Type of Server

Vanilla Forge

### Your Actions

Updated my 2.1.2.0 instance to the latest available MultiMC Pack Instance 2.1.2.3qf

I checked against mod duplications but there aren't anything and it is clearaly stated to be an ID problem
which hasn't occoured befor updating the version.

### Crash Report

https://paste.ee/p/2esF2

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Chaoschaot232** [comment]
Well, until this is getting resolved the mod GTNH-Lanth is kicked out because without this mod, what ever it does, the game is starting.

**Comment by glowredman** [comment]
Line 128: `  [✔️] Botdustries-1.7.10-1.2.5-ab6ae9e`, Botdustries is replaced by GTNH: Lanthanides, which uses the same Werkstoff IDs to keep old world intact. As discussed in #german-general, this is due to a error-prone updat procedure (coping the new files first and then deleting old versions).
