### ISSUE TITLE
Ghost Circuit selection type

### ISSUE THREAD

**Issue by Lithorn** [GTNewHorizons/GT-New-Horizons-Modpack#9936]
### Your GTNH Discord Username

Lithorn#3961

### Your Pack Version

2.1.2.2QF2

### Your Proposal

Ghost circuit slot can be changed many ways but.. Currently the bio circuit is exactly the way it should be scrolled to, but when scrolling up instead of starting at 1 on the programmed circuits you start at 24 instead

I'd like to suggest the scrolling change to be altered so that when you start with nothing set >>

Scrolling up will start the programmed circuit line at 1 and continuing to scroll up will cause it to go to 24 and stop. Scrolling down will take it back down to 1 or nothing set, and further scrolling down should then start the bio circuits at 1 and scroll all the way down to 24 and stop. Like a slider going from -24 to 24 with 0 being neutral. 

### Your Goal

To feel more streamlined when selecting circuits via scrolling

### Your Vision

It would make using the scroll wheel feel more natural 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Duplicate of #9809
