### ISSUE TITLE
Server crash on post initialization (MagicBees)

### ISSUE THREAD

**Issue by AlexandrVozmitel** [GTNewHorizons/GT-New-Horizons-Modpack#9939]
### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Don't know

### Your Actions

server core: UltraMine

Updated the server from 2.1.2.1 to 2.1.2.3qf, in the process of post initialization the server crashes.
Managed to start rolling back the mod `MagicBees` to version 2.5.7-GTNH.

### Crash Report

[crash-2022-03-12_13.05.43-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8238700/crash-2022-03-12_13.05.43-server.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8238701/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
Cannot be reproduced on forge server nor thermos (since zeta didn't crash). Probably something to do with ultramine.

**Comment by Glease** [comment]
Turns out this is a problem with org.ow2.asm after all. They emit suboptimal frame info than stock javac, which happens to contain a client only class. Adding `-Dorg.ultramine.core.asm.repairJavaClassFrames=false` should get rid of this crash if your ultramine jar contains [this commit](https://gitlab.ultramine.ru/ultramine/ultramine_core/-/commit/043fae2eaf175785cdb357763477862ba2392271).

Ultramine goes through every class to help repair frames that are broken by other transformers. This is what it was before ultramine visitor:
```text
  public java.lang.Object getClientGuiElement(int, net.minecraft.entity.player.EntityPlayer, net.minecraft.world.World, int, int, int);
    descriptor: (ILnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;III)Ljava/lang/Object;
    flags: ACC_PUBLIC
      StackMapTable: number_of_entries = 2
        frame_type = 252 /* append */
          offset_delta = 39
          locals = [ class java/lang/Object ]
        frame_type = 39 /* same */
```
After ultramine it becomes 
```text
  public java.lang.Object getClientGuiElement(int, net.minecraft.entity.player.EntityPlayer, net.minecraft.world.World, int, int, int);
    descriptor: (ILnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;III)Ljava/lang/Object;
    flags: ACC_PUBLIC
      StackMapTable: number_of_entries = 2
        frame_type = 252 /* append */
          offset_delta = 39
          locals = [ null ]
        frame_type = 255 /* full_frame */
          offset_delta = 39
          locals = [ class magicbees/client/gui/GUIHandler, int, class net/minecraft/entity/player/EntityPlayer, class net/minecraft/world/World, int, int, int, class net/minecraft/client/gui/inventory/GuiContainer ]
          stack = []
```
Notice how `net/minecraft/client/gui/inventory/GuiContainer` is showing up in stack map table.

**Comment by Glease** [comment]
On second thought, this could also be a bug in ultramine's class writers. They are not using the stock ClassWriter to compute frames, which seems to override getCommonSuperClass. The `null` in the FRAME_APPEND is very suspicious...

No idea which is the case though.

**Comment by AlexandrVozmitel** [comment]
after the change in https://github.com/GTNewHorizons/MagicBees/pull/8 server starts
