### ISSUE TITLE
Game crashes when I try to open a world

### ISSUE THREAD

**Issue by gregtechnewhorizonsisgod** [GTNewHorizons/GT-New-Horizons-Modpack#9941]
### Your GTNH Discord Username

HighGroundCat#2385

### Your Pack Version

2.1.2.3 dev

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Trying to load the world gives a rendering error ( Also I play on MultiMc ) 

### Crash Report

https://paste.ee/p/YcYf2

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
You probably have a corrupted item in hand, though yes the game probably shouldn't just crash outright.
