### ISSUE TITLE
Increase rate of Oxygen Compressor (Galacticraft)

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#9943]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3

### Your Proposal

Its current rate is 40/s for Oxygen from storage into Oxygen Tank

### Your Goal

Increase its rate to around 250 or even 500 or so Oxygen/s

### Your Vision

It takes way too long and takes seemingly & exponentially forever the higher your oxygen tanks get. I ain't wanting to play the waiting gimmick game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TrainerSnow** [comment]
That would make the low tier tanks be filled in 2 to 4 sec which is a bit fast no? Cant we make it so that every oxygen cell takes xx seconds to fill, independant of its storage amount?

**Comment by ScriptedPiky** [comment]
That's also a possibility, though the internal tank wouldn't be able to fill the much larger tanks all that quickly. Wonder what can be done or if there's another way of implementing this in a better fashion
