### ISSUE TITLE
[GT++] Chunkloader MK I~III doesn't work.

### ISSUE THREAD

**Issue by SHIBUYAENNI** [GTNewHorizons/GT-New-Horizons-Modpack#9944]
### Your GTNH Discord Username

ENNISHIBUYA#3552

### Your Pack Version

2.1.2.3 QF

### Your Server

Single-player

### Type of Server

Single Player

### Your Expectation

I need a single-block machine that loads more chunks. (obviously, the world anchor loading range is not large, and it is also inconvenient)

### The Reality

![0](https://user-images.githubusercontent.com/96222276/158056731-a68f9eaa-3afa-46dd-86b2-e8dac0e2bb0c.png)
But in practice, it doesn't work.   The machine is inactive.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hikari1nVoid** [comment]
AFAIK this stuff never worked just like other uncompleted sbms in GTPP.
