### ISSUE TITLE
Duplicate Dalisenite EBF recipes

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#9950]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

-----

### The Reality

How alisenite have UV and MV recipes in EBF
![image](https://user-images.githubusercontent.com/39595617/158144819-97123811-fd89-449b-b752-fb3de970fd36.png)
![image](https://user-images.githubusercontent.com/39595617/158144863-b7ff1e6b-6f1e-467e-be82-1d3b3e34ef61.png)
*

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
It's still in 2.2.0.0. The MV one should be removed.
![MV](https://user-images.githubusercontent.com/85604068/192773671-f6ec0bcb-5403-4e53-bb41-406c8cd6a0f8.png)
![UV](https://user-images.githubusercontent.com/85604068/192773676-287f61b8-9652-4b69-97b8-403844b2eb29.png)

**Comment by Dream-Master** [comment]
ah nice autogenerated recipes i guess
