### ISSUE TITLE
Crash when crafting plates from liquid. Bug Extra Cells.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#9952]
### Your GTNH Discord Username

Pilad

### Your Pack Version

2.1.2.3qf

### Your Server

Single

### Type of Server

Single Player

### Your Actions

Save https://drive.google.com/file/d/1BQ0EBHf3CvkeFxNjp4Vy-yBcBGJYsmss/view?usp=sharing
Place the WIP template from the inventory and order the rubber plate. 
If a flat fluid interface is used, then there is no crash. Craft completed successfully. 

### Crash Report

https://pastebin.com/Y8q9KM5w

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by eigenraven** [comment]
Should be fixed by the ec2 rewrite
