### ISSUE TITLE
Recipe for Ashes in Compressor

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9954]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Proposal

Tiny pile of ash could not be compressed in compresser into Ashes, please add it

### Your Goal

null

### Your Vision

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
You mean tiny piles from gt? Did any other tiny pile can be compressed?

**Comment by MadRatSRP** [comment]
> You mean tiny piles from gt? Did any other tiny pile can be compressed?

yes, dunno about other ones but i don't see any reasons why they shouldn't be able to
