### ISSUE TITLE
More ways to get copper in alloy smelter

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9955]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Proposal

Right now you can get bronze in alloy smelter from only copper/tin dusts/ingots and for doing that with cassiterite and chalcopyrite you need to get dust first, make copper and tin ingots from them and only then place it in alloy smelter. 
Its really annoying and i think that alloy smelter should need to support any copper or tin variant of dusts or ingots for making bronze and variants like tin+chalcopyrite, cassiterite + copper, e.t.c. should work like that as well.

### Your Goal

null

### Your Vision

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by lordclips** [comment]
I'm pretty sure the point of not doing it with Chalcopyrite or Cassiterite is that they're not purely Copper or Tin so it would alloy weirdly. This really is just a case of "Smelt the thing then alloy" and I don't get why there'd need to be a pointless workaround for something that simple

**Comment by MadRatSRP** [comment]
> I'm pretty sure the point of not doing it with Chalcopyrite or Cassiterite is that they're not purely Copper or Tin so it would alloy weirdly. This really is just a case of "Smelt the thing then alloy" and I don't get why there'd need to be a pointless workaround for something that simple

so when smelting chalcopyrite or cassiterite dust it becomes purely tin or copper ingot, but when doing parallel thing but with alloy smelter its not pure :?

**Comment by TrainerSnow** [comment]
I'll answer with a question, why do i need to smelt my iron ore into an iron ingot, why cant i directly craft a bucket from the or, when its essentially the same?
Chalcopyrite isnt pure copper, but smelting it "wastes" everything thats not copper. 
If small things like this annoy you, this pack may not be for you, I'm afraid.

**Comment by lordclips** [comment]
Basically what Trainer said: The smelting burns off impurities (or you could think they're in the ingot but the impurities don't matter) so you're left with the actual pure substance that is turned into bronze, which is the point

**Comment by MadRatSRP** [comment]
I got your idea, so are there any ways to improve this process instead of smelting chalcopyrite/cassiterite into tin/copper ingots and then working with them?

**Comment by Dream-Master** [comment]
I have the same issue with smelt iron dust to Steel in ebf. So if we use different kind of impure metals (Chalcoperite, Casseterite) for make Bronze we need to do the same thing with Magnetite, Brown Limonite, Yellow Limonite etc. for steel smelting.

**Comment by Dream-Master** [comment]
We can do this but i need to have a downside to not purifying it. Maybe a eu or amount malus

**Comment by Dream-Master** [comment]
@lordclips @MadRatSRP do a list which stuff need to be in a recipe for bronze.

**Comment by lordclips** [comment]
Will do oh benevolent overlord

**Comment by lordclips** [comment]
All ores presented as dusts

For Bronze alloying:
- Cassiterite
- Cassiterite Sand
- Chalcopyrite
- Tetrahedrite
- Malachite

And since it was brought up otherwise for other alloys, I'll note (a few) here as well:

Steel: 
- Pyrite
- Magnetite
- Banded Iron
- Yellow Limonite
- Brown Limonite
- Basaltic Mineral Sand
- Granitic Mineral Sand

Cupronickel:
- Chalcopyrite
- Tetrahedrite
- Malachite
- Garnierite
- Pentlandite

Invar:
- Pyrite
- Magnetite
- Banded Iron
- Yellow Limonite
- Brown Limonite
- Basaltic Mineral Sand
- Granitic Mineral Sand
- Garnierite
- Pentlandite

Just to name a few extras whose dusts would need to be added for such a change
