### ISSUE TITLE
Extreme Heat Exchanger Wrong fluid Output

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#9956]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Was testing Extreme heat exchanger(EHE)
exepcted to get supercritical and superheated steam from tin plasma recipe

### The Reality

it looks like i got supercritical steam instead of superheated

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
the nei tells the threshold is 1L/s, that means tin plasma will only output the supercrital steam. it is intented
![image](https://user-images.githubusercontent.com/60341015/158305150-f60fcc4a-0ceb-45b9-9d74-fb9da0b679e0.png)

**Comment by LewisSaber** [comment]
It it indeed that i got 146461568000(146ML) of supercritical steam from 100mb of tin plasma?

**Comment by GlodBlock** [comment]
it should be 913444L supercritical steam per 100mb tin plasma.

**Comment by LewisSaber** [comment]
Also does it mean 100k eu per bucket or 100 eu per bucket 
![image](https://user-images.githubusercontent.com/39595617/158326660-8fd392c6-958b-4a47-b458-e940c6329e8b.png)
also this rotor makes only 30k eu/t when its supplied at optimal flow
![image](https://user-images.githubusercontent.com/39595617/158326792-fccccbc8-d1a6-4e84-a258-0895d527424c.png)

**Comment by GlodBlock** [comment]
100k eu per bucket


>  also this rotor makes only 30k eu/t when its supplied at optimal flow ![image](https://user-images.githubusercontent.com/39595617/158326792-fccccbc8-d1a6-4e84-a258-0895d527424c.png)
 if 1B is 100K eu then it should make: 512000 * 100 /20(steam/s * eu per 1 steam / ticks in second) = 2560000 eu/t

that seems like a bug, look into it later
