### ISSUE TITLE
Align Crop Manager Fertilizer Use w/ Crop Matron

### ISSUE THREAD

**Issue by schneid3306** [GTNewHorizons/GT-New-Horizons-Modpack#9958]
### Your GTNH Discord Username

schneid3306#7813

### Your Pack Version

2.1.2.3qf

### Your Proposal

It is my understanding that the Crop Manager was created to be a more lag friendly version of the forestry farm. Currently, the Crop Manager blows through fertilizer.

With the Crop Matron (or by hand) when you fertilize a crop, it gives it 100 fertilizer. When the fertilizer drops to 99, the Crop Matron (or player) will fertilize again, and it will jump to 199. The Crop Matron does not appear to fertilize again until the crop drops below 100 (the player cannot manually add more fertilizer until it drops to at least 99). When the Crop Matrons do re-fertilize the crops, it jumps up by 100 (so 99 to 199 again). Basically, each fertilizer is worth 100 fertilization stats.

On the other hand, the Crop Manager fertilizes a plant from 0-100. It then fertilizes again at 99, and the fertilizer stat only goes back up to 100. I think this is what is causing the Crop Manager to completely blow through fertilizer. Even for a 9x9 crop field, you can blow through two and a half stacks of fertilizer instantly because it just continually fertilizes the crops, because only the first fertilizer is worth 100, and each subsequent fertilizer is worth 1.

I would love to be able to use the Crop Manager in lieu of the Forestry Farm. I am currently using it along side a bunch of Crop Matrons because it is impossible to keep up with the fertilizer demands. I have attached images showing the fertilizer levels of crops at 199.![](https://user-images.githubusercontent.com/101597354/158248996-70e16076-dbdc-4693-a94e-2973fa404b02.png)

### Your Goal

Crop Managers aren't a viable option at any scale until they use fertilizer in a similar manner to the Crop Matron. It is seemingly impossible to keep up with the fertilizer demand currently. I would like to fix that.

### Your Vision

I think that this would make the Crop Manager the go to farm above forestry farms for IC2 crops. It would also keep everything centralized for the player instead of having to use the Crop Manager along side Crop Matrons for fertilizing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by schneid3306** [comment]
I am not sure if this is a bug or a suggestion. I think suggestion is more appropriate, because this may be intended functionality, but feel free to re-classify.

**Comment by NexusNull** [comment]
It makes a machine absolutely unusable, personally I'd classify it as a bug.

**Comment by schneid3306** [comment]
I think this is still an issue.

**Comment by kuba6000** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/217
