### ISSUE TITLE
Unlimited Health

### ISSUE THREAD

**Issue by Tintec** [GTNewHorizons/GT-New-Horizons-Modpack#9959]
### Your GTNH Discord Username

Tintec#1780

### Your Pack Version

2.1.2.3qf

### Your Server

Private

### Type of Server

Don't know

### Your Expectation

Fought Gaia with bloodmagic armor.

https://user-images.githubusercontent.com/48184123/158264281-2585a2ae-c669-42ef-81fe-7d5f78b6f552.mp4

### The Reality

Got unlimited extra Hearts that diddent dissapeare.

### Your Proposal

I think it has something to do with my chestplate rune infusion.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tintec** [comment]
Server type is Thermos

**Comment by MadRatSRP** [comment]
Now you can mine bitcoin on these hearts ;)
