### ISSUE TITLE
Railcraft water tanks disassemble into Stainless

### ISSUE THREAD

**Issue by Jonodonozym** [GTNewHorizons/GT-New-Horizons-Modpack#9961]
### Your GTNH Discord Username

Jono#7396

### Your Pack Version

2.1.2.0

### Your Server

Private server

### Type of Server

Don't know

### Your Expectation

Make railcraft water tanks with iron or steel and place them in a disassembler to get the respective type back or nothing at all 

### The Reality

RC water tanks instead give stainless rods regardless, letting you get stainless steel at LV. May need to place and break them first.

### Your Proposal

Disable the RC water tank's disassembler recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment]
gives iron in 2,3gf
![image](https://user-images.githubusercontent.com/39595617/158452821-ae561a4c-a4ea-4e32-b1e3-87e50b31bc56.png)
