### ISSUE TITLE
Incorrect display of NEI when being used with Crafting station

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#9967]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

![баг неи](https://user-images.githubusercontent.com/29717217/158474100-f7a4d92e-320a-454f-8c31-a4ffbfa4c26e.png)

### The Reality

null

### Your Proposal

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BreakingLead** [comment]
what's wrong?

**Comment by MadRatSRP** [comment]
> what's wrong?

![image](https://user-images.githubusercontent.com/29717217/158540989-1b7dc820-5731-478c-a69f-6fcefb833bfa.png)
This text should be centerised between arrows

![image](https://user-images.githubusercontent.com/29717217/158541069-c68422c6-4d38-4394-85d4-281504e4f36a.png)
this text isnt visible properly

and the central window should be more centralised against user's search bar

**Comment by miozune** [comment]
Probably fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/240
