### ISSUE TITLE
Gt++ molecular transformer issues

### ISSUE THREAD

**Issue by GTNHAfx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#9972]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Tried to set up the new GT++ molecular transformer. Placed down the controller and used the multiblock structure hologram projector to see the layout. Noticed the controller facing up, tried to rotate it to face forward.

### The Reality

rotation is not possible. circular arrow is displayed, but wrenching does not turn the controller in any direction.

### Your Proposal

make it rotate the controller properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
Could this be from here?
https://github.com/GTNewHorizons/GTplusplus/blob/d9bb8c4e5ad7fc75d3a6798b193bf500ccb48a44/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialMolecularTransformer.java#L263

I’m not code savvy but seems to me like it forces a certain direction to face, and only this direction?

**Comment by Ngar1** [comment]
If controller is in center top, surounded by 8 blocks - there is no reason for rotating forward, or?
![grafik](https://user-images.githubusercontent.com/7759876/160235280-b8aff5ba-31e5-4641-928a-a0429a3345b8.png)

**Comment by GTNHAfx237v7** [comment]
Well with structurelib you can rotate the entire multi. The controller shows the circular arrow but nothing happens when you use a wrench on it.

**Comment by GTNH-Afx237v7** [comment]
Additional:
The resonance chamber and modulator blocks currently only work as Tier 1. There are three more tiers available, however they don't serve any function. You can craft them but when installing them into the multi it will return "invalid structure".

**Comment by miozune** [comment]
Some of the multis like Charcoal Pile Igniter don't accept rotating forward for reasons. If you want to rotate this multi, convince Alkalus.
