### ISSUE TITLE
Methods of generating cobblestone

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9978]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Proposal

Current only method of generating cobble can be really laggy. Depends on the speed, it can go as high as 4ms with a world accelerator
![javaw_W6tbCC26qO](https://user-images.githubusercontent.com/17811922/158684213-488b5b42-947d-4707-b9ca-ac99197f6dfc.png)

This is the only setup that can give stacks/tick of cobble.

Alternative idea could be to have a singleblock that can act as an infinite storage of cobblestone. This solves 2 issues, moving immense quantities of cobblestone after it's produced, and production speed of it. 
So something like an "Infinite Item Chest" but locked to cobblestone only.
It can be tiered to uv+ and ideal recipe would require some octuple compressed cobblestone with field generators, in a extreme crafting table. It should be recipe expensive or require power to operate.

### Your Goal

Avoid cobblestone production stupid lag

### Your Vision

+

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pnc6lx** [comment]
![~E)( ~A93UF9)22157FO3{8](https://user-images.githubusercontent.com/49830847/158752049-ba515915-c322-42a3-8b54-b9ed3132de2b.png)
gt++ have a multiblock cobblestone generator. in UV it can produce 64 in 1tick

**Comment by LewisSaber** [comment]
its named Boldarnator

**Comment by Sphyix** [comment]
> use a Rock Breaker? May be it works in Process Arrays, than you have a powerfull source of cobbl, or?

It doesn't work in a PA and i currently need 7 stacks/tick

**Comment by Pnc6lx** [comment]
> > use a Rock Breaker? May be it works in Process Arrays, than you have a powerfull source of cobbl, or?
> 
> It doesn't work in a PA and i currently need 7 stacks/tick
there is gt++ version rock breaker called Boldarnator

**Comment by Sphyix** [comment]
> there is gt++ version rock breaker called Boldarnator

Not in 2.1.2.0 I guess, time to wait for new release

**Comment by EnderProyects** [comment]
I was looking issues and for this if I remember correctly there is a thaumcraft cobble generator ( a block)

**Comment by boubou19** [comment]
is it able to sustain several thousand cobble per second tho?

**Comment by EnderProyects** [comment]
I haven't tested the speed, or with world accelerators

**Comment by EnderProyects** [comment]
Well the thaumic stone strudder normally has a speed of 0.5 cobble per second, in this pack is of 16 per second, with the Ulymate Time anomally well, is an entire vanilla chest in less than a second, is instantaneous, dont produce any lag and dont consume anithing ( only the accelerator) 
![image](https://user-images.githubusercontent.com/45178400/161339375-b283345d-f5cc-42e8-9d7d-03f3bbcd2a10.png)

**Comment by boubou19** [comment]
can you put an infi chest as the output and measure the lag on the time anomaly with a tricorder? because the ExU setup lags a lot due to the time anomaly (between 1 and 2.5 ms)

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/161344156-5db01c99-6390-4f88-bbc7-a97a4bcfff0d.png)
This?

**Comment by boubou19** [comment]
yeah this, however i see that the WA has its arrow not fully blue, which means it doesnt have 6A UV. try giving it 6A UV and retry.

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/161344924-efd662c6-ac9c-43f6-a7a7-a47dd4a298c3.png)

**Comment by EnderProyects** [comment]
Allso well, you can add more thaumic struders arround the accelerator

**Comment by boubou19** [comment]
that's decent, @Sphyix you need to check this

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/161345176-37cd2903-d13c-4ab0-9e47-3226d9095a34.png)
And I think the recipe is very eassy
