### ISSUE TITLE
Strange areas of world generation lacking decorations

### ISSUE THREAD

**Issue by TenchiRyokoMuyo** [GTNewHorizons/GT-New-Horizons-Modpack#9984]
### Your GTNH Discord Username

TenchiRyokoMuyo#1721

### Your Pack Version

2.1.2.3

### Your Server

51.161.57.5:25566

### Type of Server

Don't know

### Your Expectation

I added Dynmap and Pregenerator to the modpack, to allow me to generate the world before play, to reduce lag, as well as view the world as it was generating. I expected to be able to pregenerate the nearest 100 or so chunks in each direction from spawn, and view it from our dynmap viewer located at http://51.161.57.5:4954/

### The Reality

Instead of generating properly, large areas of land are missing what I would describe as 'decoration' blocks. Things that get added after basic world generation. This includes but not limited to snow, grass, flowers, tree leaves, wood, and structures. 

It results in large area's of land being 'cut through' with no access. 

As such, I deleted the world, and restarted a new seed, to see if it was an odd seed interaction.
![2022-03-16_21](https://user-images.githubusercontent.com/84601180/158843295-9c2bd9cb-ed8d-41ae-b5ce-4547ec8f57a7.png)
![7dffb0e5917dc44d34d9d5e1de1d4171](https://user-images.githubusercontent.com/84601180/158843310-05c6d8d9-77f5-45ca-a189-f6a928b6fb6b.jpg)

And the problem persisted amongst all world generations and seeds.

### Your Proposal

I am unsure if this is a problem with Pregenerator generating, but it seems that it's recommended to use by many other players. I'm thinking this may be something unique to 2.1.2.3?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can you try it on an earlier pack, perhaps 2.1.2.0 or similar? I suspect that pregnerator is somehow not triggering the same thing a "player" does.

**Comment by mitchej123** [comment]
If you use speiger's pregenerator there is an option to do 90% of it and leave the final decoration for first load.  The final features are often not generated if this approach is not taken.

The other option that does work is get a mod or command block to rapidly teleport you around in the radius you want to generate the chunks in game.

**Comment by TenchiRyokoMuyo** [comment]
![a6df57bf8434aac42e090edddd60ac3d](https://user-images.githubusercontent.com/84601180/158902846-5f70e9ac-ff2d-44ae-8599-6aae6ea9d1ae.png)

Just tried this on 2.1.2.0. Still getting similar results. Large area's of land missing detail. I'm going to look up a command block sequence to try that method out instead. It seems as of right now, pregenerator may not work for GTNH, regrettably.

**Comment by mitchej123** [comment]
Honestly the command block teleportation is the most reliable way to do it.  Everything else is full of hacks and workarounds.  Rapidly teleport your player in a circular fashion to generate the chunks.

**Comment by TenchiRyokoMuyo** [comment]
CommandBlocks are not something I'm incredibly familiar with. I tried one, it didn't work for me. I went ahead and manually generated some large area's, and it seems that the problem doesn't exist when generated by normal means. So it's definitely some conflict with how the Pregenerator works with GTNH. I haven't seen this issue in other modpacks, so I don't have much info to provide. 

If you have a suggestion on a commandblock system that would work, I'd love that. The two that I found don't seem to work for 1.7.10, and I'm certainly not knowledgeable enough to create a system myself, haha. 

I'm still looking into the suggestion on a pregenerator for decoration being saved until loaded by a player. I think that would also be a good solution.

**Comment by mitchej123** [comment]
@KaneHart you found one that worked, didn't you?

**Comment by bjin2000** [comment]
Try this one: https://gaming.stackexchange.com/questions/32316/how-do-i-pre-generate-a-minecraft-world

**Comment by TenchiRyokoMuyo** [comment]
@bjin2000 That would be a great option, but this is a rented server, I don't think I'll have the ability to do so.
