### ISSUE TITLE
Aluminium in the EBF should use nitrogen again

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#9991]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.1.2.2

### Your Proposal

Before the aluminium rework, aluminium dust in the EBF had an optional nitrogen requirement to increase processing speed. After the rework this was changed to oxygen.

This doesn't make sense chemically, aluminium is highly reactive and providing the dust with pure oxygen will rather create alumina rather than smelting into a pure aluminium ingot. You can search for videos on "thermite" to see the actual result of trying this

Hence, I'd suggest that the EBF recipes for alu dust and ticon alu into aluminium ingots use nitrogen again.

### Your Goal

-

### Your Vision

If all other things are equal, scientific accuracy should prevail.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
sure will change that to nitrogen not even remeber why this was changed

**Comment by Dream-Master** [comment]
i exchange the gas in the alu recipe.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/501ecf79566f4a8040fe2d871e99d7c0e842f695
