### ISSUE TITLE
Compressor recipe for 9 x GT Sapphire gives wrong Block of Sapphire

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9993]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Proposal

Change the output of the compressor recipe for 9 x GT Sapphire to use GT's Block of Sapphire rather than BoP's Block of Sapphire.

### Your Goal

Have GT machines output GT materials where possible

### Your Vision

As GT is core to the pack, ensuring that GT items are used where possible is crucial for players managing their inventory.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
Any word on fixing this one?

**Comment by TwoTailedFox** [comment]
I don't think this is completed

**Comment by Dream-Master** [comment]
> I don't think this is completed

can you chisel another block ?
