### ISSUE TITLE
Add cables for MV+ Superconducting wirres

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9994]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Proposal

To have MV+ wires with 0 EU loss have a cable variant

### Your Goal

Rubber jackets prevent electrocution, and cabled up wires allow players to expand their base without risk of this happening.

### Your Vision

Allowing players to craft a cable of a 0 EU-loss wire (possible with an expensive rubber option to compensate)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
Superconductors already don't electrocute...

**Comment by TwoTailedFox** [comment]
My mistake, thought all naked wires did.
