### ISSUE TITLE
Saltroot IC2 Crop has missing textures.

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9995]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The Saltroot crop should maintain correct textures.

### The Reality

The crop shows a missing texture and does not seem to be able to calculate size correctly.

### Your Proposal

This should be fixed so crop growth can be properly calculated and the correct texture applied

![2022-03-19_17 36 22](https://user-images.githubusercontent.com/13187606/159132134-4315a333-1a8c-4ec1-928b-fd2e0a782b60.png)
.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
There was a bug where saltroot crops would continue to grow even after reaching their max growth stage. This has been fixed as of https://github.com/GTNewHorizons/GoodGenerator/pull/25. Could you check if the textures are missing for the growth stages up to 3?

**Comment by miozune** [comment]
Confirmed fix
