### ISSUE TITLE
Assembler recipe for Computer Monitor Cover does not use oredict

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9997]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Proposal

To alter recipe for Assembler that, like the shaped crafting recipe, will allow the player to use alternatives for Rose Red, Lapis Lazuli and Lime Dye.

### Your Goal

To ensure players can use alternatives in place of the standard items.

### Your Vision

To ensure feature parity with Crafted and Assembler recipes and to provide the same alternatives in materials.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
Any word on fixing this one?

**Comment by TwoTailedFox** [comment]
The recipe isn't broken, it's just not using oredict for the Assembler. I haven't seen a fix in the Git log pertaining to this.

**Comment by chochem** [comment]
it has ore dict support in the crafting table but not in the assembler (on 5-dev with some changed mods)

**Comment by TwoTailedFox** [comment]
OK, so the Assembler still needs an oredict-complaint recipe.

**Comment by TwoTailedFox** [comment]
Any update on this one being looked into?
